### ISSUE TITLE
Decoder errors when playing Car on Safari

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#1015]
When playing the Car asset on Safari, it stops after ~15 seconds and throws a 3016 error, a 3015 error, and several "InvalidStateError (DOM Exception 11): The object is in an invalid state." errors. The video then enters a buffering state, but the time continues advancing forward until it reaches the end. It still plays the audio according to the little audio playing icon in the URL bar, but no sound is produced.
I've tried all of our test assets and haven't seen this with any other asset. I was testing with Safari 10.1.2.

**Comment by TheModMaker** [comment]
The first error that occurs is a decoder error.  This only happens with adaptation; when switching to an affected track manually (when we clear the buffer first), the error doesn't occur.  Since this is a decoder error, this is likely a platform issue, but it may have to do with how we adapt.

**Comment by TheModMaker** [comment]
I am fairly sure this is a limitation of the Safari decoder.  This may be caused by bad content, or just that Safari doesn't support this kind of content.  Safari plays other similar content fine, and it looks like we are doing all the correct things for this content.

I have reduced the problem to only when adapting (or switching without clearing the buffer).  When we clear the buffer (and implicitly reset the decoder), the content plays fine.  It also plays fine on the stream by itself.  I think the streams are somehow incompatible with each other.  I also think this only applies to the 426x240 video stream.  One difference I notice between that and the other streams is that in the SPS the `pic_order_cnt_type` is different.  The Safari decoder may not support changing this field since it changes the way frame parsing happens.

We could remove that video stream from the manifest, but we don't control the original asset (it's a YouTube test asset).  We could either drop the asset completely or make a copy that doesn't have that representation.

**Comment by joeyparrish** [comment]
It's not representative of YouTube-encoded content, [it's old, and it's unmaintained](https://www.youtube.com/embed/MdFeUw3p7zQ?start=124&end=140&autoplay=1).  I move we drop it.

**Comment by joeyparrish** [comment]
The fix has been cherry-picked to v2.2.x and will be released in v2.2.2.
