### ISSUE TITLE
A DASH manifest's minBufferTime always overrides rebufferingGoal

### ISSUE THREAD

**Issue by taryodor** [google/shaka-player#1025]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes

**What version of Shaka Player are you using**:
2.2.1

**Can you reproduce the issue with our latest release version**:
Yes

**Can you reproduce the issue with the latest code from `master`**:
yes

**Are you using the demo app or your own custom app**:
custom

**If custom app, can you reproduce the issue using our demo app**:
no, my stream is sealed from outer world

**What browser and OS are you using**:
Chrome on VM Win10

**What are the manifest and license server URIs**:
not accessible to outer world

*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
no

**What did you do?**
wanted to use shaka with our Dash live stream

**What did you expect to happen?**
I would expect, that buffered video will correspond with bufferingGoal setting

**What actually happened?**
Oven though manifest minBufferTime is 2 and rebufferingGoal is 45, Shaka buffer maximaly 2 seconds of video

**Comment by TheModMaker** [comment]
First, there are two configs for this `bufferingGoal` and `rebufferingGoal`.  The `bufferingGoal` specifies how much to buffer while we are playing; `rebufferingGoal` specifies how much content to buffer before we start playing again.  In both cases, we will take the larger of the config and `minBufferTime`.  Check out the [buffering tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-network-and-buffering-config.html) for more info.

```js
player.configure({streaming: {bufferingGoal: 45}})
```

Second, live streams are a bit different.  Because we are playing at the "live edge", there doesn't exist any more content ahead of the playhead, so there is nothing to buffer.  One option is to add a `suggestedPresentationDelay` to the manifest.  This specifies the delay from the live edge that the player should play at.  We will buffer past this, allowing more content to be buffered.

**Comment by joeyparrish** [comment]
As explained by @TheModMaker, `bufferingGoal` is for buffering ahead, and may not be achievable for a live stream played at the edge.  `rebufferingGoal` is for startup and rebuffering, as is `minBufferTime` in the manifest.  If `minBufferTime` is larger than `rebufferingGoal`, it will override `rebufferingGoal`.

@taryodor, does this answer your question?

**Comment by taryodor** [comment]
@joeyparrish
question fully answered, many thanks.

**Comment by joeyparrish** [comment]
Glad we could help!
