### ISSUE TITLE
[question] How to get a list of available segments?

### ISSUE THREAD

**Issue by mad-gooze** [google/shaka-player#1036]
Hello!

Is is possible to get a list of currently available live segments for DASH stream? I need to extract segment duration info.

**Comment by vaage** [comment]
@mad-gooze I am afraid that I do not understand your question. Could you please provide some clarification. Are you asking is there a way to know what segments are available on the server for a given live stream when looking at a DASH manifest - or are you asking at any point during playback know what segments have been downloaded and are therefore available to the player at that exact point in time?

**Comment by mad-gooze** [comment]
Yes, I mean segments that are available on the server for a current moment.

**Comment by joeyparrish** [comment]
Not directly.  We don't have an API for that, but you can get it indirectly by shimming the manifest parser to examine the parsed segment references.  You could also use a network response filter to intercept the unparsed manifest and get the info you need from that.

**Comment by joeyparrish** [comment]
#1043 may also help, if the info you need can be had from the Track APIs in the player.

Does this help answer your question?

**Comment by vaage** [comment]
@mad-gooze Was @joeyparrish able to answer your question? If so feel free to close the issue.

**Comment by mad-gooze** [comment]
@joeyparrish Shimming the manifest parser should by done by using `opt_manifestParserFactory` in [load()](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#load) and passing an object that proxies default `shaka.dash.DashParser`? It's unclear for me from docs which fields I should observe to watch for available segments. Could you add a more detailed example of how do I do that please?

**Comment by joeyparrish** [comment]
From the manifest (`shakaExtern.Manifest`), you can find the individual streams (`shakaExtern.Stream`), which have methods for finding segment references.

**Comment by mad-gooze** [comment]
Thanks, I have successfully extracted `SegmentReference` using `getCurrentSegmentReference()`!

Actually I understood that I need a more narrow case - I want to get info about currently playing segment (like url and duration) and subscribe for a segment change. Is there simpler API for that?

**Comment by joeyparrish** [comment]
We don't have an API for that, as far as I can recall.

If we did expose currently-playing segment, it would have to be based on a lookup of currentTime in the segment index of the Stream, which would be complicated.  We track what we're currently streaming, but what is being played from the buffer could be different.  We may have been streaming video Stream A, then B, then A again, and now C.  We don't track enough information to know which was put into what part of the buffered timeline.  And that example doesn't even involve clearing the buffer, seeking, or segment overlap.

Even if we did have the data, we would have to expose to you as many as three segment references for the current time: video, audio, text.

Because of the way streaming and buffering works, and because of the architecture of what we already built, it would be difficult to track what segments are in buffer in what positions.  What might be easier would be to track what segments we have streamed and notify you as we stream them, but that could be done through server-side logging as well.

**Comment by joeyparrish** [comment]
We are adding a method to the player to retrieve the parsed manifest. That should at least make it easier to access the manifest without needing to shim the parser.

**Comment by joeyparrish** [comment]
@mad-gooze, we added a method called [getManifest()](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#getManifest) to get the internal manifest structure from the player.  Does this help?

**Comment by mad-gooze** [comment]
This method greatly simplifies code in my case, thx!

**Comment by joeyparrish** [comment]
Glad we could help!  I'll go ahead and close this issue, but if you need any further assistance, please let us know.
