### ISSUE TITLE
Use Network Information API to react to network changes

### ISSUE THREAD

**Issue by beaufortfrancois** [google/shaka-player#1067]
You may want  to use the Network Information Web API to react propertly to network connection changes.
See https://googlechrome.github.io/samples/network-information/ and http://wicg.github.io/netinfo/#-dfn-networkinformation-dfn-interface

**Comment by TheModMaker** [comment]
We are already going to use the Network Information API to determine the default bandwidth estimate (see #994).  We could also use this to help with network changes, but browser support is non-existent outside of Chrome (see [caniuse](http://caniuse.com/#feat=netinfo)).

**Comment by joeyparrish** [comment]
Ideally, we would be able to use network changes to "forget" history we've built up in the bandwidth estimator, but that could also be tricky.  Since our default estimator reacts quickly to drops in bandwidth (we take the min of fast and slow moving averages) we should still be able to recover from network changes without this.

We'll keep it on the backlog for now, until we can experiment a bit with it and determine what value there would be in using this information to enhance our estimate.

**Comment by avelad** [comment]
@joeyparrish is it possible migrate it to 3.0.x?

**Comment by joeyparrish** [comment]
Unfortunately not.  We are being strict about semver now, so this will go into v3.1.  You are always welcome to build from source until then, or to cherry-pick changes in your own fork of v3.0.x.  Sorry for the inconvenience!
