### ISSUE TITLE
Seek not working for my stream

### ISSUE THREAD

**Issue by JobaDiniz** [google/shaka-player#107]
Hi, I'm testing [this stream](http://vods3.telenorhu-cdn.ottcloudservices.com/00/00/01/14988_707D062960D4E822/_46088_AXH-HCARDS00103A_UUX_H264_1200kbps_AAC_und_ch2_64kbps.mpd) at http://shaka-player-demo.appspot.com/ and if I seek to any position, player stops and I get several errors in console: **Error: An unknown error has occurred in the CDM.
    at Error (native)
    at ic.h.Od (http://shaka-player-demo.appspot.com/shaka-player.compiled.js:65:113)**

_PS: if stream does not work, just ask another one... they are tokenized streams_

**Comment by joeyparrish** [comment]
When I play this content, without seeking, I find that the video stalls at 9 seconds.  When I've seen this behavior in the past, the problem is usually that the license we received did not contain the correct key.

Unless you specify a license server URL in the test app UI, the license server used is http://widevine-proxy.appspot.com/proxy .  My guess is that this is not the correct license server for this content, and that we get 9 seconds of playback because the first 10 seconds of the content are clear.

I can't reproduce the behavior you are describing.  Is there a license server URL I should be using to override the default?

**Comment by JobaDiniz** [comment]
You're right, sorry. I'll test with the right license server.
Mt actual problem is that seeking takes too long, sometimes 10 seconds
(when using the right license server)
