### ISSUE TITLE
Firefox DRM issue

### ISSUE THREAD

**Issue by gleb-shchavlev** [google/shaka-player#1073]
Hello.

I have problem with Firefox DRM.

I use windows OS and Shaka Player v2.2.3-debug from https://shaka-player-demo.appspot.com/demo/.

Shaka player works fine in Chrome (63.0.3236.0, 64 bit) and Edge (40.15063.674.0), but does not work in Firefox (56.0.1, 64 bit, widevine module version 1.4.8.1008). Blank screen.

Chrome and Firefox link:
https://shaka-player-demo.appspot.com/demo/#asset=https://nginx.dev.cdnnow.ru/live/index.mpd;license=https://one.drmnow.ru/widevine;

Edge link:
https://shaka-player-demo.appspot.com/demo/#asset=https://nginx.dev.cdnnow.ru/live/index.mpd;license=https://one.drmnow.ru/playready/rightsmanager.asmx;lang=ru;

Where is no javascript or network errors.

What's can be wrong with Shaka in Firefox?

**Comment by cpeterso** [comment]
I see "Shaka Error NETWORK.HTTP_ERROR (https://nginx.dev.cdnnow.ru/live/3466666.m4a)" in both Firefox 56.0.1 and Chrome 62. In the devtools console, I see CORS network errors:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://nginx.dev.cdnnow.ru/live/3675000.m4v. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://nginx.dev.cdnnow.ru/live/3675000.m4a. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://nginx.dev.cdnnow.ru/live/3675000.m4v. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
(video:1) failed fetch and append: code=1002
```

**Comment by joeyparrish** [comment]
@gleb-shchavlev, please check your CORS setup.  Are you working around CORS in Chrome with something like --disable-web-security?

**Comment by gleb-shchavlev** [comment]
CORS errors was on 404 answers, fixed.

Sometimes need to move slider to the right of player window to make stream live.

Where is no CORS problem if translation goes in live.

**Comment by joeyparrish** [comment]
Okay, thanks.  Moved back to the triage list.

**Comment by TheModMaker** [comment]
There was a bug where we didn't set the start time in live streams correctly.  It has been fixed and you can use the nightly instead to use the correct start time:

https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://nginx.dev.cdnnow.ru/live/index.mpd;license=https://one.drmnow.ru/widevine;lang=en-US

We have reproduced the playback bug.  It appears to be a platform issue.  Both Firefox and Chrome are generating the same license requests and we get back a reasonable license response, but Firefox is failing to playback the content.  I'll look into the CDM more to see about extra logging info to help.

Here are the logs from the about:media plugin:

```
HTMLMediaElement debug data

    http://localhost/shaka/demo/#asset=https://nginx.dev.cdnnow.ru/live/index.mpd;license=https://one.drmnow.ru/widevine;lang=en-US
        blob:http://localhost/dc6250f9-7780-4870-bd9a-762b898bbcf6
        currentTime: 23877.21199987602 readyState: 1
        Quality: -- (total:0 dropped:0 corrupted:0)
        Buffered ranges: [(23866.732, 23874.989)(23875.012, 23883.325)(23883.348, 23891.661)]
        SourceBuffer[0]: (23866.676, 23874.989)(23875.012, 23883.325)(23883.348, 23891.661)
        SourceBuffer[1]: (23866.732, 23891.699)
        Internal Data:
            Audio Decoder: ffmpeg audio decoder
            Audio Frames Decoded: 6
            Audio State: ni=0 no=0 wp=0 demuxr=0 demuxq=0 decoder=0 tt=-1.0 tths=-1 in=3 out=3 qs=0 pending=0 wfd=0 eos=0 ds=0 wfk=0 sid=6
            Video Decoder: Chromium CDM video decoder
            Hardware Video Decoding: disabled
            Video Frames Decoded: 0 (skipped=0)
            Video State: ni=0 no=0 wp=1 demuxr=0 demuxq=0 decoder=0 tt=-1.0 tths=-1 in=500 out=0 qs=500 pending:0 wfd=1 eos=0 ds=0 wfk=0 sid=7
            Dumping Data for Demuxer: 7f85d2d06c00
            Dumping Audio Track Buffer(audio/mp4a-latm): mLastAudioTime=23877.218000
            Audio Track Buffer Details: NumSamples=1077 Size=851260 Evictable=358051 NextGetSampleIndex=454 NextInsertionIndex=1077
            Audio Track Buffered: ranges=[(23866.676000, 23874.989000), (23875.012000, 23883.325000), (23883.348000, 23891.661000)]
            Dumping Video Track Buffer(video/avc): mLastVideoTime=23891.699000
            Video Track Buffer Details: NumSamples=750 Size=8057719 Evictable=5371813 NextGetSampleIndex=750 NextInsertionIndex=750
            Video Track Buffered: ranges=[(23866.732000, 23891.699000)]
            EME Info: Key System=com.widevine.alpha SessionsInfo=(sid=8C41A0D82A52A25CA37F10E9834D8908(kid=61656435306535326532336437653461 status=usable))
            MediaDecoder State: channels=2 rate=44100 hasAudio=1 hasVideo=1 mPlayState=LOADING mdsm=7f85cae16800
            MediaDecoderStateMachine State: GetMediaTime=23877212000 GetClock=-1 mMediaSink=7f85d5127030 state=SEEKING mPlayState=1 mSentFirstFrameLoadedEvent=0 IsPlaying=0 mAudioStatus=idle mVideoStatus=waiting mDecodedAudioEndTime=23877218219 mDecodedVideoEndTime=0mAudioCompleted=0 mVideoCompleted=0
            VideoSink Status: IsStarted=0 IsPlaying=0 VideoQueue(finished=0 size=0) mVideoFrameEndTime=0 mHasVideo=0 mVideoSinkEndRequest.Exists()=0 mEndPromiseHolder.IsEmpty()=1
```

**Comment by cpeterso** [comment]
@cpearce, I can reproduce this Shaka Widevine failure in Firefox 56+ on Windows 10. It works in Chrome.

I see the following EME errors in the browser console (Ctrl+Shift+J), but I don't see any errors in the devtools console (Ctrl+Shift+K):
```
MediaKeySystemAccess::GetKeySystemStatus(org.w3.clearkey) result=available msg=''
MediaKeySystemAccess::GetKeySystemStatus(com.widevine.alpha) result=available msg=''
navigator.requestMediaKeySystemAccess promise rejected 0x80530009 'Key system is unsupported'
```

**Comment by cpearce** [comment]
Thanks for reporting this. I can also repro on Linux. I've filed [Mozilla Bug 1409988](https://bugzilla.mozilla.org/show_bug.cgi?id=1409988) to track fixing this in Firefox.

**Comment by cpearce** [comment]
I think this may be fixed in Firefox Nightly buy [Mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1409670), but the test URL  https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://nginx.dev.cdnnow.ru/live/index.mpd;license=https://one.drmnow.ru/widevine;lang=en-US no longer works in Firefox or Chrome for that matter.

@gleb-shchavlev are you able to either download and test Firefox Nightly on your content, or provide a URL to content that we can test with? That will help us confirm whether this issue is fixed or not. Thanks!

**Comment by gleb-shchavlev** [comment]
I restart stream. It's available right now.

**Comment by gleb-shchavlev** [comment]
Just checked on Firefox 57.0b12 (64-bit).
It does not work.
The behavior is same.

**Comment by joeyparrish** [comment]
@gleb-shchavlev, I don't think that's what @cpearce meant.  Can you try on the nightly version of Firefox?

https://www.mozilla.org/en-US/firefox/nightly/all/

**Comment by gleb-shchavlev** [comment]
Oh, ok. Tried. Chunks downloaded, white screen in player window.
Error apears:
`Shaka Error MEDIA.VIDEO_ERROR (3,,NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - class mozilla::ipc::IPCResult __cdecl mozilla::gmp::ChromiumCDMParent::RecvDecodeFailed(const unsigned int &): ChromiumCDMParent::RecvDecodeFailed)`

**Comment by KieronAllsop** [comment]
Adding my experience with what appears to be the same bug. However the one caveat is the following behaviour only occurs when automating playback - I get NO errors when manually playing the same content on the same browsers. I should add that the these are real machines (not VMs) and it is only since the latest round of browser updates that this occurs.

Automation setup
- Robot framework
- Selenium Standalone Server 3.7.1 (grid and node)
- Selenium 3.7.0
- Geckodriver 0.19.0
- Chromedrvier 2.33
- Firefox version 56 and 57
- Chrome version 62 and 63
- Windows 10 

Error occurs when trying to playback content for which the 'HDCP Required' rule must be enforced.

Firefox output (console)

`Media resource blob:https://urm.latens.com/429e435a-9c5a-4347-9846-462a6472345e could not be decoded.
demo
Player error 
Object { category: 3, code: 3016, data: [?], message: "Shaka Error MEDIA.VIDEO_ERROR (3,)", stack: "shaka.util.Error@https://urm.latens.com/boomplayer/lib/util/error.js:77:13\nshaka.Player.prototype.onVideoError_@https://urm.latens.com/boomplayer/lib/player.js:1760:17\n" }
main.js:258:3
Media resource blob:https://urm.latens.com/429e435a-9c5a-4347-9846-462a6472345e could not be decoded.
demo
Media resource blob:https://urm.latens.com/429e435a-9c5a-4347-9846-462a6472345e could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: class mozilla::ipc::IPCResult __cdecl mozilla::gmp::ChromiumCDMParent::RecvDecodeFailed(const unsigned int &): ChromiumCDMParent::RecvDecodeFailed
`

Chrome output (media://internals)

Timestamp | Property | Value
------- | ---------- | -----------
00:00:00 00 | origin_url | https://urm.latens.com/
00:00:00 00 | frame_url | https://urm.latens.com/boomplayer/demo/
00:00:00 00 | frame_title | Shaka Laka Player
00:00:00 00 | url | blob:https://urm.latens.com/a410ce94-1715-4449-bc37-d620f73ab15e
00:00:00 03 | pipeline_state | kStarting
00:00:10 643 | has_cdm | true
00:00:10 669 | found_audio_stream | true
00:00:10 669 | audio_codec_name | aac
00:00:10 727 | found_video_stream | true
00:00:10 727 | video_codec_name | h264
00:00:10 735 | debug | DecryptingAudioDecoder: failed to init decoder on decryptor
00:00:10 736 | audio_dds | true
00:00:10 736 | audio_decoder | FFmpegAudioDecoder
00:00:10 744 | video_dds | false
00:00:10 744 | video_decoder | DecryptingVideoDecoder
00:00:10 744 | pipeline_state | kPlaying
00:00:10 747 | info | DecryptingDemuxerStream: no key for key ID A63F23DCD98445E9AC1201E4A50E5D32
00:00:10 755 | info | DecryptingVideoDecoder: no key for key ID A63F23DCD98445E9AC1201E4A50E5D32
00:00:10 648 | duration | 157.04
00:00:12 210 | info | DecryptingDemuxerStream: key was added, resuming decrypt
00:00:12 210 | info | DecryptingVideoDecoder: key added, resuming decode
00:00:12 212 | info | DecryptingDemuxerStream: no key for key ID A63F23DCD98445E9AC1201E4A50E5D32
00:00:12 223 | info | DecryptingVideoDecoder: no key for key ID A63F23DCD98445E9AC1201E4A50E5D32
00:00:15 17 | pipeline_state | kSuspending
00:00:15 18 | pipeline_state | kSuspended
00:00:35 15o | info | Selected video track: []

Will gladly supply any further information if needed.

**Comment by joeyparrish** [comment]
@gleb-shchavlev, is this still an issue for you in Firefox?  If so, can you provide an updated manifest and license URL we can use to re-test?

**Comment by gleb-shchavlev** [comment]
Nope, issue was fixed. It was bug in drm packager code.
