### ISSUE TITLE
Native subtitles contol button is shown even for playlists without text streams

### ISSUE THREAD

**Issue by mad-gooze** [google/shaka-player#1081]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: [x]

**What version of Shaka Player are you using**: 2.2.3

**Can you reproduce the issue with our latest release version**: [x]

**Can you reproduce the issue with the latest code from `master`**: Did not check yet

**Are you using the demo app or your own custom app**: Demo

**If custom app, can you reproduce the issue using our demo app**: [x]

**What browser and OS are you using**: Google Chrome

**What are the manifest and license server URIs**:
https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/heliocentrism/heliocentrism.mpd;lang=ru;nativecontrols

**What did you do?**
Enable native controls in playlists without text streams.

**What did you expect to happen?**
No subtitles control button.

**What actually happened?**
![shaka player demo 2017-10-24 11-50-31](https://user-images.githubusercontent.com/1188779/31933364-94a40af0-b8b1-11e7-9d4c-c21533fa7e31.png)

**Comment by theodab** [comment]
I see the problem; the text displayer makes a text track in the video whether or not the stream has captions.
Unfortunately, there is no good way to fix this. I could make it not create a text displayer in such situations, but it would be an incomplete solution. The closed caption button would still show up if you viewed a stream with captions and then a stream without. That can't be avoided, because the API for text tracks has no method to remove them, and even a 'disabled' text track will cause the closed caption button to appear.
If this behavior is a major problem for your application, a custom TextDisplayer is a possible solution. You can find the API for TextDisplayers [here](https://shaka-player-demo.appspot.com/docs/api/shakaExtern.TextDisplayer.html) in our documentation.

**Comment by mad-gooze** [comment]
Thanks! For now I will stick to hiding this control when there are no text tracks via shadow dom pseudo classes where possible.
```css
video::-webkit-media-controls-toggle-closed-captions-button {
        display: none;
}
```
