### ISSUE TITLE
Should AbrManager#stop return a Promise?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1090]
I noticed this while troubleshooting an unrelated problem. `AbrManager#stop` doesn't return a Promise:

```
/**
 * Stops any background timers and frees any objects held by this instance.
 * This will only be called after a call to init.
 *
 * @exportDoc
 */
shakaExtern.AbrManager.prototype.stop = function() {};
```

However it is treated like it does in `Player#destroyStreaming_`:

```
var p = Promise.all([
  this.abrManager_ ? this.abrManager_.stop() : null,
```

It's a little confusing.

**Comment by joeyparrish** [comment]
I don't see any technical reason for it, nor any historical one.  It has been that way since AbrManager was introduced for v2, and stop() has never returned a Promise.

To explain what that does, you can pass non-Promise values to a Promise.all, and the effect is as if it was a Promise resolved with that value.  For example:

```js
var p0 = Promise.resolve(0);
var p11 = 11;
var p22 = new Promise(function(resolve) {
  setTimeout(function() { resolve(22); }, 2000);
});

Promise.all([ p0, p11, p22 ]).then(function(values) {
  console.log('VALUES', values);
  console.assert(values.length == 3);
  for (var i = 0; i < values.length; ++i) {
    console.assert(values[i] == i * 11);
  }
});
```

So in this way, Player can shut everything down without caring whether each method returns a Promise or not.  But there's no reason we couldn't have just done this before the Promise.all:

```js
if (this.abrManager_) this.abrManager_.stop();
```

**Comment by joeyparrish** [comment]
So to go back to the original question, "should stop() return a Promise?"

In terms of the shutdown code, it doesn't matter from Player's point of view.

If your custom AbrManager needs to do anything asynchronous to shut down, then we can change it to return a Promise.  Otherwise, there's not much point.

Another historical note that may explain why it doesn't return a Promise already:

AbrManager is an external interface, but IDestroyable is not.  IDestroyable is used inside the core of Shaka, and IDestroyable mandates that destroy() return a Promise.  For some of our internals, async destroy() is necessary.  But since AbrManager is a plugin interface with a stop method instead of an internal class implementing IDestroyable, there's no requirement for it to return a Promise.

Does that answer your question?

**Comment by chrisfillmore** [comment]
I actually just thought it may have been an oversight in the AbrManager interface, since as you say, custom implementations may want an async shutdown. But I also don't see the point in making things async without a reason. Thanks for the answer.

**Comment by joeyparrish** [comment]
No worries.  If anybody needs async shutdown, it's a backward compatible change to make that return a Promise in future (thanks to the Promise.all behavior described above).
