### ISSUE TITLE
Can't Playout Custom DASH URL - js dependencies seems missing (deps.js)

### ISSUE THREAD

**Issue by tbaylet** [google/shaka-player#11]
http://localhost/shaka2/third_party/closure/goog/deps.js Failed to load resource: the server responded with a status of 404 (Not Found)
base.js:413 goog.require could not find: shaka.player.DashVideoSourcebase.js:413 goog.logToConsole_
base.js:448 Uncaught Error: goog.require could not find: shaka.player.DashVideoSource
http://localhost/shaka2/assets/poster.jpg Failed to load resource: the server responded with a status of 500 (Internal Server Error)
3app.js:450 Uncaught ReferenceError: shaka is not defined
app.js:450 Uncaught ReferenceError: shaka is not defined

**Comment by joeyparrish** [comment]
When running in uncompiled mode, deps.js is required for goog.require to find the necessary source files.  This file is not checked into the sources, since it is generated as part of the build process.

You are getting an HTTP 404 on deps.js because you have not run the build scripts.  The quick answer is to run ./build/gendeps.sh to generate deps.js.  You could also run ./build/all.sh to run all build scripts, including deps generation and compilation.

For more information, please see [the development tutorial](http://shaka-player-demo.appspot.com/docs/tutorial-dev.html) in the docs.

The HTTP 500 error on poster.jpg is probably due to some kind of misconfiguration of your web server, since that is a static asset and can't itself generate any such error code.

**Comment by joeyparrish** [comment]
I'm going to close this issue, but please feel free to reopen it if you have further problems with deps.

**Comment by tbaylet** [comment]
Joey. Thanks for feedback. Working fine with build.
