### ISSUE TITLE
I need to re-publish emsg events when the playhead has reached emsg.startTime. What should I compare against?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1101]
When Shaka encounters `emsg` events in a stream, it parses the boxes and immediately publishes those events to the application. Our ads provider (YoSpace) has asked us to enqueue these events and republish them to their SDK when the playhead arrives at the `emsg.startTime`.

I am considering the following approach:

1. Listen for `emsg` events from Shaka
2. Listen for `timeupdate` events from videoElement
3. When an `emsg` event is received, push the event into a queue
4. When a `timeupdate` event is received, inspect the queue. For each `emsg` event which has `startTime <= playheadTime`, republish this event to the ad SDK

I'm hoping you can advise me about how to determine `playheadTime` in step 4. The `emsg.startTime`, I understand, is an absolute presentation timestamp. I need a value in the same frame of reference. Should I use `Player#getPlayheadTimeAsDate() / 1000`? Or should I just use `videoElement.currentTime`? Is there a difference?

Let me know if I can provide more information, and thank you in advance for any advice.

**Comment by TheModMaker** [comment]
`getPlayheadTimeAsDate` returns a `Date` object, so you probably shouldn't use division on it (though it seems to work).  But it also only works on live streams, not VOD.  In a live stream, `getPlayheadTimeAsDate` returns the wall-clock time of the playhead position.  So if it is 10:30 now and you are playing 10 minutes behind the live edge, it will return 10:20.

`video.currentTime` will return the current playhead time in presentation time.  This is likely the time you want since that will be the time of `emsg.startTime` and `emsg.endTime`.

**Comment by chrisfillmore** [comment]
Thanks @TheModMaker, I'm grateful for the help.
