### ISSUE TITLE
Autoplay checkbox in demo UI is confusingly named

### ISSUE THREAD

**Issue by sandersaares** [google/shaka-player#1114]
I was just trying to inspect the state of the player before any playback in the demo app and realized it was starting playback even though I had not checked the autoplay checkbox. I assume that should not happen?

The state of the checkbox seems to have no impact on what happens after I press the load button. Tested on Chrome 62 and Firefox 56 by entering custom URL.

**Comment by joeyparrish** [comment]
The demo app does its own autoplay at the app level, because the autoplay attribute on the video element doesn't work on Android.  Take a look at `demo/asset_section.js`, the bottom of `shakaDemo.load()`, which says:

```js
  // While the manifest is being loaded in parallel, go ahead and ask the video
  // to play.  This can help with autoplay on Android, since Android requires
  // user interaction to play a video and this function is called from a click
  // event.  This seems to work only because Shaka Player has already created a
  // MediaSource object and set video.src.
  shakaDemo.video_.play();
```

If you create your own application and don't call `video.play()`, you will find that the autoplay attribute does what you would expect (except on Android, where it is often ignored).

**Comment by sandersaares** [comment]
Well, okay then. I was just looking at a checkbox saying "autoplay" not being checked and the video starting playback automatically, which seemed wrong to me as a plain user of the demo app. But if it is by design then it is by design, I guess.

**Comment by joeyparrish** [comment]
Where is this checkbox?  I don't see it in Chrome on Linux.

If this is a thing users can toggle outside of our demo UI, we could make the `play()` call dependent on the state of `video.autoplay`.  It would be simple and might remove a source of surprise for users of the demo app.

I just want to find where that checkbox is so I can reproduce.

**Comment by joeyparrish** [comment]
I didn't see it any checkbox in Firefox on Linux, either.  What browser & OS are you using, and where does the autoplay checkbox appear?

**Comment by sandersaares** [comment]
Illustration attached: 

![image](https://user-images.githubusercontent.com/9914262/32590937-aa561624-c525-11e7-934f-4e137d690847.png)

**Comment by joeyparrish** [comment]
Ah!  I see!

Here's the source of confusion:

HTMLMediaElements have an `autoplay` attribute which has the effect of calling `play()` when a source is loaded.  If this attribute is set, most platforms (not always on Android) will start playing the video as soon as you call `player.load()`.  I was looking for a checkbox for that provided by the browser, similar to the one you get for the "loop" attribute when you right-click a video element.

That checkbox in configuration is something else.  It has the effect of automating the "Load" button when you refresh the page.  It's useful for manual testing and debugging, when you need to edit some code and reload the page to quickly reproduce an issue.  It's also useful in bug reports, so that bugs reproduce when the page loads.

The checkbox you're referring to should not be named "Autoplay", to avoid confusion.  Instead, we should call it something closer to what it does: "Load content on page load".

Does that makes sense?  If that explanation helps, we will go ahead with renaming the checkbox in the demo UI.

**Comment by sandersaares** [comment]
Yes, that sounds like it would indeed be an improvement.

**Comment by joeyparrish** [comment]
Excellent.  Thanks for the feedback!

**Comment by joeyparrish** [comment]
The name change has been cherry-picked to v2.2.6.
