### ISSUE TITLE
increase bufferBehind to max segment size

### ISSUE THREAD

**Issue by thatsnotright** [google/shaka-player#1123]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: yes, similar issues but not seem to match exactly

**What version of Shaka Player are you using**: 2.2.5

**Can you reproduce the issue with our latest release version**: yes

**Can you reproduce the issue with the latest code from `master`**: yes

**Are you using the demo app or your own custom app**: both

**If custom app, can you reproduce the issue using our demo app**: yes

**What browser and OS are you using**: Chrome, FF on Linux and MacOS

**What are the manifest and license server URIs**: 
https://s3.amazonaws.com/shakagapskipissue/manifest.mpd

I enabled CORS on this so it should be playable from https://shaka-player-demo.appspot.com/ with large gap skipping enabled.

**What did you do?**

When playing back this file the large gap event is triggered about 10 seconds before a segment boundary.  The DTS and PTS look OK to me in the segments (based on mp4box) and concatenating the video plays back nicely in ffmpeg.  dashjs reference player will play back this manifest correctly as well (but does not support large gap skipping, which is a feature we need).

If you seek to 0:37 and let the player go through, about 0:40 to 0:41 it will just skip 10 seconds to the beginning of the next segment.

**What did you expect to happen?**

I expect no large gaps on segment boundaries, and in the provided manifest I expect 1 large gap around the 2:29 mark.

**What actually happened?**

10 seconds of video at the end of every segment is skipped.  I don't know if this is a problem caused by how we are segmenting or encoding the video, or if it is an issue with shaka but the same manifest plays correctly in dashjs (until the actual large gap, in which case dashjs does not skip ahead).

**Comment by TheModMaker** [comment]
The problem is that you have 50 second video segments that only have one keyframe.  As we play, we only keep `bufferBehind` amount of content buffered.  This means we remove content that is further than this far back.  Because of how MSE works, when we remove something, the browser will remove up to the next keyframe.  This means when we get to 0:37, we will try to remove 0:00-0:07.  Since there are no keyframes past that, the browser will remove the entire segment, up to 0:51.

You have three options: (1) reduce the segment size, (2) increase the keyframe (GOP) interval, or (3) change the `streaming.bufferBehind` configuration so we keep more buffered.

Although, we should change it so `bufferBehind` will be overridden by the max segment size to avoid this problem.

**Comment by thatsnotright** [comment]
Fantastic, the bufferBehind update works around the issue for now.  We can't change the i-frame interval, unfortunately, so this is the GOP boundary.

**Comment by joeyparrish** [comment]
Fix cherry-picked for v2.3.2.
