### ISSUE TITLE
How should I manage buffering states when license is reaching maxAttempts?

### ISSUE THREAD

**Issue by adgllorente** [google/shaka-player#1126]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes

**What version of Shaka Player are you using**:
Master

**Can you reproduce the issue with our latest release version**:
Yes

**Can you reproduce the issue with the latest code from `master`**:
Yes

**Are you using the demo app or your own custom app**:
The demo app.

**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**:
Mac + Chrome

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**
Let's suppose license server is responding quite slowly and maximum attempts are reached. I'm listening the event ``buffering`` to show/hide a custom spinner in the player. When player reaches buffering goal, the event ``buffering`` is sent with ``false`` and I hide the spinner but since license is not resolved yet, the player seems frozen to the user.

Should the buffering event take into account the license management? Should I be checking another thing apart from the buffering event to show/hide my spinner?

Thanks.

**Comment by TheModMaker** [comment]
There is a `waitingforkey` event on the `<video>` element that is fired when the browser stops playing because it doesn't have the required keys.  You could also listen to the `canplay` or `playing` video event that is fired once it resumes.  We wanted to do this in the past, but the timing of these events is not specified and doesn't always work cross-browser.  We couldn't provide a consistent detection of when we didn't have the required keys.

The `buffering` event is only used to track the buffered content.  The browser is stopping playback because it doesn't have the keys.  But otherwise there is no way to detect what the browser can play without trying to actually play it.

See w3c/encrypted-media#284

**Comment by adgllorente** [comment]
Thank you so much for the information, I guess we will have to wait for a more consistent way to handle this situation.
