### ISSUE TITLE
[CAF] cast.framework.media.ShakaPlayer category: 3 code: 3016

### ISSUE THREAD

**Issue by colde** [google/shaka-player#1129]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:
Yes

**What version of Shaka Player are you using**:
I am using whatever is bundled with the CAF framework for Chromecast Casting.
Console is logging: cast_receiver_framework.js:66  [  0.012s] [cast.receiver.CastReceiverManager] Version: 2.0.0.0055

**Can you reproduce the issue with our latest release version**:
Not entirely sure. I am using the sender from https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1 and the receiver from http://www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js
I am not sure if there is anyway to control the bundling there.

However, the issue strangely does not present itself when using the Shaka Player demo at https://shaka-player-demo.appspot.com/demo/

**Can you reproduce the issue with the latest code from `master`**:
I can't even reproduce it with https://shaka-player-demo.appspot.com/demo/

**Are you using the demo app or your own custom app**:
I was testing with a custom sender.

**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**:
Google Chrome 62 on macOS High Sierra

**What are the manifest and license server URIs**:
Since this is movie content i prefer not to divulge that. If necessary i will try and get some content encoded with a different source.

**What did you do?**
I setup a simple sender as described in https://developers.google.com/cast/docs/chrome_sender_integrate

Basically, my sender looks like this:
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Cast Test</title>
</head>
<body>
	<script src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1"></script>
<script>
	initializeCastApi = function() {
	  cast.framework.CastContext.getInstance().setOptions({
	    receiverApplicationId: "D0E8DBC4",
	  });
	};
	
	startVideo = function() {
		var castSession = cast.framework.CastContext.getInstance().getCurrentSession();
		
		var mediaInfo = new chrome.cast.media.MediaInfo("<streamurl>", "application/dash+xml");
		var request = new chrome.cast.media.LoadRequest(mediaInfo);
		castSession.loadMedia(request).then(
		  function() { console.log('Load succeed'); },
		  function(errorCode) { console.log('Error code: ' + errorCode); });
	};
	
window['__onGCastApiAvailable'] = function(isAvailable) {
  if (isAvailable) {
    initializeCastApi();
  }
};
</script>
  <button is="google-cast-button"></button>
</body>
</html>
```

I then load the page, setup the cast by clicking on the button, and run startVideo(); using the console.

**What did you expect to happen?**
Working playback.

**What actually happened?**
Playback for at few seconds, then i get an error:
		  cast_receiver_framework.js:66  [ 18.879s] [cast.framework.media.ShakaPlayer] category: 3 code: 3016
		  Ld @ cast_receiver_framework.js:66

When testing with another piece of content, it seems to work.

**Why do i not think this is a decode error**
When using the Shaka Player to play this content on Chromecast, the content plays back without issue. This seems to suggest it is related to the bundled Shaka Player in the Cast Receiver perhaps being out of date?

**Comment by theodab** [comment]
Shaka Player's cast receiver isn't really designed to work with default cast receivers. We have our own cast sender too; I suppose we should probably make a tutorial on how to use it, since it's not fully obvious, but you can examine the demo app or look at the class info for [shaka.cast.CastProxy](https://shaka-player-demo.appspot.com/docs/api/shaka.cast.CastProxy.html) in the documentation.

Looking at your code in particular, you aren't doing anything to activate Shaka Player at all. The Chromecast [has built-in support for MPEG-DASH playback](https://developers.google.com/cast/docs/player), so it might be that you are getting that to play the media. There are bound to be problems if Chromecast's player library and Shaka Player both think they own the video element. A 3016 error is sent by the cast receiver if the video element throws an error, so it'll happen even though Shaka Player has not actually loaded anything.

**Comment by joeyparrish** [comment]
It sounds like you have an issue with CAF, but everything is working in Shaka Player.  Is that correct?

I don't know what version of Shaka Player is built into CAF.  You will have to ask the Cast team for support on that.

Error 3016 indicates a decoder error, which comes from the Chromecast platform in this case.  If you want to go deeper, you'll need to the Cast team for support.

I'm sorry we weren't able to help you with CAF directly, but if you [file a bug with the Cast team](https://developers.google.com/cast/docs/support), please link to that bug here so that people who run across this issue will be able to follow along to the resolution.

Does this help?

**Comment by colde** [comment]
@joeyparrish Yes. That is correct. The issue is with CAF (which bundles the shaka-player receiver at least)

And yes, i figured there would be a chance that you wouldn't know, and that i should go talk to the Cast team, i just figured that you guys helped them package it, and had a update process in place as well.

Yeah, i've read that 3016 seems to be a decoding error. But since it works with the shaka-player receiver, and not with CAF. It seems unlikely to actually be a decoding error, it seems more likely that the receiver in CAF is not setting things up correctly.

I'll file an issue with the Cast team. They unfortunately don't seem as responsive as you guys.
