### ISSUE TITLE
High latency loading many videos at once

### ISSUE THREAD

**Issue by buggles333** [google/shaka-player#1166]
**Have you read the FAQ and checked for duplicate issues:**
Yes

**What version of Shaka Player are you using:**
2.2.6

**Can you reproduce the issue with our latest release version:**
Yes

**Can you reproduce the issue with the latest code from master:**
Yes

**Are you using the demo app or your own custom app:**
Custom App

**What browser and OS are you using:**
Windows 7, Chrome 62

**What did you do?**
I have 4 videos loading on the page at once but only the first is set to autoplay, the files are all HLS file with 2 second segements and I have setup ABR and Streaming like so..

```
  player.configure({
  abr: {
    defaultBandwidthEstimate: 5000000,
  },
  streaming: {
      bufferingGoal: 4,
      rebufferingGoal: 2
  }
});
```

**What did you expect to happen?**
I expected the first video to play

**What actually happened?**
The first video does eventually play but takes a long time to start, in the console I can see "Load Latency: 20.453"

The videos are being served from a CloudFront instance, do you think the slow start time is down to me loading 4 videos on one page?

**Comment by theodab** [comment]
The load latency message plays when the video fires a loadeddata event, which happens when the video has loaded enough data to render a frame; because we are downloading things in segments, this means it is fired soon after the first segment loads. Thus it's possible that this is a result of network issues from downloading four segments at once, each at the highest possible bitrate (you set your defaultBandwidthEstimate quite high). It's also possible this is some kind of jam at the MediaSource level from trying to set up and decode samples for four videos at once, I suppose. Either way, it seems likely to be a result of having four videos at once.
An easy way to test this would be to disable some of the videos and see how long it takes for Shaka Player to load.

**Comment by joeyparrish** [comment]
I have seen in the past that browsers tend not to make more than 2 TCP connections per server domain.  (Haven't checked in a while, so this may not be true any longer.)  If your videos are all hosted in the same place, trying to load 4 at once may be a really bad idea.  If you have the bandwidth to sustain loading all 4 at once, you could work around this by using different subdomains (x1.foo.com/video1.mpd, x2.foo.com/video2.mpd) that all lead to the same place.

But I would recommend that you try something a little bit different.  Even without autoplay, shaka.Player will stream and buffer data up to the buffering goal.  Try waiting to load videos 2, 3, and 4 until after the previous video is loaded:

```js
player1.load(videoUrl1).then(function() {
  return player2.load(videoUrl2);
}).then(function() {
  return player3.load(videoUrl3);
}).then(function() {
  return player4.load(videoUrl4);
});
```

This may help the first video start more quickly.

**Comment by joeyparrish** [comment]
@buggles333, have we answered your question?  Is there anything else we can do to help?

**Comment by vaage** [comment]
Closed due to inactivity, @buggles333, please feel free to reopen this issue if it is still an issue for you.
