### ISSUE TITLE
IMA ads SDK demo and tutorial

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1169]
We should add the IMA ads SDK to our demo app and write a tutorial explaining how to integrate Shaka Player with IMA (and by extension, other ads SDKs).

If, during this process, we discover ways the library could make ads integrations easier, we should enhance the library itself.

**Comment by chrisfillmore** [comment]
We spend quite a lot of time integrating with ad SDKs, including [YoSpace](http://www.yospace.com/), [FreeWheel](http://freewheel.tv/), and IMA. Currently my team doesn't handle this work, it's done by downstream teams which use our player abstractions, but I often provide support.

One feature I developed recently to handle emsg events from Shaka is a simple queue which collects emsg events, and polls the video element to check if the playhead has passed the `startTime` for any emsg events in the queue. If it has, republish the event. The recommended polling interval is 250ms.

Would such a feature be useful to Shaka? Perhaps it could be a configurable parameter on the player, something like `emsgPollingInterval`, which could be set to `0` to disable the behaviour. I could submit a PR for this, if you want.

**Comment by TheModMaker** [comment]
@chrisfillmore We actually already do something similar with the `<EventStream>` elements in DASH.  We poll the current time and fire `timelineregionenter` and `timelineregionexit` when we enter/exit a region.  We should probably just extend that behavior for the emsg boxes too.

**Comment by joeyparrish** [comment]
@chrisfillmore, if you want to submit a PR to extend the timeline event behavior to emsg boxes, please do!

**Comment by boredom2** [comment]
Concerning the mentioned "best Ways" to use SHAKA together with a "VAST/VPAID/IMA" Environment (i.e. the optimal Way to change the Source of a <video> between a SHAKA Instance and a simple Ad-MP4, which may be handled by the Player itself (own VAST Approach) or the IMA SDK (or potential other Ad Plugins) and back to SHAKA with the same time (or maybe a little before) - is it currently planned to cover all that unter a Plugin/Interface or how would you do this most efficiently with SHAKA 2.4 right now? (I noticed, that you postponed that to 2.5, but I was still curious :P).
The Reason why I ask is the more-and-more present Behaviour  of more-and-more Browsers to not-start Videos, that are created by Script, but only due to a User Gesture. Although I understand the Reasons, we used to work with 2 Video Instances on top of each other to maintain SHAKA under the Ad-Player. We still do this in some Cases, but I would prefer an approach within one <video> Tag, Im just not sure, what you would consider as best appraoch here to make the permanent switch between various Video Sources as easy and fast as possible?

Thanks a lot!

**Comment by vaage** [comment]
Just as a note on this, because it has been sitting for a while and I saw @TheModMaker reference it in another #1818. We made a proof-of-concept internally, but we never settled on an actual "best practice" position.  I don't think it has been documented here, but as @TheModMaker commented on in #1818, the UI may be used as part of ad integration.
