### ISSUE TITLE
Is Promise.reject() legitimate?

### ISSUE THREAD

**Issue by dcharbonnier** [google/shaka-player#1171]
Even if Promise.reject(); is syntactically correct, it's a very bad practice, making very hard to debug problems. All rejections should have an error object instance of Error.

**Comment by TheModMaker** [comment]
We don't use Error objects, we use a custom error object `shaka.util.Error`.  Any Promise rejections on public APIs should be rejected with an instance of that type.  If it doesn't, can you say exactly where it happens?

Internally we use `Promise.reject()` for simplicity since we don't need a specific error.  It is common to do this in larger Promise chains for fallbacks or when we just wrap a native error code.  For example, if a network error occurs (no matter what it is), we will retry the request.  So it doesn't matter that the error object is `undefined`, what matters is that we hit the `catch()` callback so we run the retry logic.

Unfortunately, using an explicit error object for every Promise rejection would be a lot of work.  We would need to create new error codes for internal-only use, which could confuse users and risks the error propagating to an app.

But again, if a public API has returned an empty rejection object, that is definitely a bug.  Otherwise we will continue to avoid it if possible, but continue to use it to simplify our code.

**Comment by joeyparrish** [comment]
Agreed.  If there are public APIs rejected with anything other than shaka.util.Error, that's a bug.  Otherwise, it's working as intended.

**Comment by joeyparrish** [comment]
@dcharbonnier, have you found any void Promise rejections in our public APIs?  If not, I think this is all working as intended for now.

**Comment by dcharbonnier** [comment]
no, just that bluebird is complaining is you don't disable warnings and that this https://github.com/google/shaka-player/blob/f0c85093b4238b1907c1eac41eff03d7b8dd6da4/lib/dash/dash_parser.js#L1465 could be way more easy to debut for example.

**Comment by joeyparrish** [comment]
Okay.  We are working toward some general mechanisms for cancellation of Promise chains within the project, at which point `Promise.reject()` will likely go away.  We are only using it now for rejections that we know will be swallowed (such as on cancellation or destroy).
