### ISSUE TITLE
SegmentReference has no public fields

### ISSUE THREAD

**Issue by mrlika** [google/shaka-player#1200]
I am trying to integrate P2P assisted streaming solution with Shaka player. To do it I need to download segments ahead of player not sequentially over both HTTP and WebRTC/RTCDataChannel connections, cache them, return them to the player by request.

I am trying to use shakaExtern.Manifest as abstraction over HLS and DASH manifests to get future segments.

To get segments ahead of player I create custom ManifestParser as a Decorator to HLS and DASH parsers.

Manifest->Period->Variant->Stream->GetSegmentReference returns SegmentReference that has no public fields according to documentation that makes it useless in many cases:
https://shaka-player-demo.appspot.com/docs/api/shaka.media.SegmentReference.html

But fortunately position, startTime and endTime fields are not mangled in the object. And uris can be accessed by mangled names (i.e. to get URIs of segment I call segmentReference.a() )

Can the fields be public to be used for example in Decorator Pattern or external to Shaka Player code?

**Comment by joeyparrish** [comment]
In v2.2.5, we introduced a new method on `Player` called `getManifest()`.  This should help you avoid a custom manifest parser.

The constructor of `SegmentReference` is exported, but the other public methods are not currently.  That is because we had expected the only use of `SegmentReference` in the application would be by custom manifest parsers.  Every method we export adds to the size of our compiled bundle, so we don't export more than we think we will need in the application.

To export the public methods and make them available outside the library, add the @export annotation.  See also this doc on exports: https://github.com/google/shaka-player/blob/master/docs/design/export.md

We would be happy to take a pull request for this if you have time.  Thanks!

**Comment by mrlika** [comment]
Thanks for pointing to getManifest method. I will prepare pull request soon.

**Comment by mrlika** [comment]
I add the fields like:

```
/**
 * The offset from the start of the resource to the
 * end of the segment, inclusive. null indicates that the segment extends
 * to the end of the resource.
 *
 * @type {?number}
 * @export
 */
shaka.media.SegmentReference.prototype.endByte = 0;
```

It compiles, no errors or warnings, documentation looks also Ok but names are still shortened inside constructor call. I can not find annotation to prevent this behavior.

**Comment by joeyparrish** [comment]
I'm so sorry, I gave you bad information.  `@export` is for prototype methods, not for member variables on `this`.  I was thinking you needed to export prototype methods, not member variables.

There used to be `@expose` for member variables, but that is no longer supported by the compiler.

Let me dig into this a bit and get back to you.

**Comment by joeyparrish** [comment]
I think the best thing to do is to create exported getters for SegmentReference's fields.  Sorry I didn't realize this at the beginning!
