### ISSUE TITLE
"The command line is too long" from build\all.py

### ISSUE THREAD

**Issue by sandersaares** [google/shaka-player#1228]
I pulled latest master branch and got the error below when running build\all.py.

This is on Windows 10 v1709.

```
c:\Source\shaka-player>c:\Python27\python.exe build\all.py
[INFO] Generating Closure dependencies...
[INFO] Running Closure Compiler linter...
[INFO] Running eslint...
The command line is too long.
```

The script stops at the above point.

**Comment by joeyparrish** [comment]
The problem seems to come from the addition of eslint, specifically.  It's the long list of files, combined with the use of `node_modules/.bin/eslint.cmd` on Windows.  The cmd script passes through the arguments, which breaks the command-line limit.  python's `subprocess.Popen` is not what triggers the error.

**Comment by joeyparrish** [comment]
Related to work on issue #1157

**Comment by joeyparrish** [comment]
Cherry-picked to v2.3.1.
