### ISSUE TITLE
[Shaka Player Demo] License requests don't contain necessary HTTP headers, when removing DRM-protected assets from the offline store.

### ISSUE THREAD

**Issue by vladimir-kazakov** [google/shaka-player#1229]
Some DRM-protected assets have [licenseRequestHeaders](https://github.com/google/shaka-player/blob/21783b06a23972eb720ea9dc2c58b01f25c9a9b3/demo/common/assets.js#L590), which are needed in order to acquire a license. When the playback is started, a license request is being sent to a license server. This request has mentioned license request headers, as expected.

After the asset was stored in the offline storage (by clicking the "store" button in the "offline" section), removing this asset from the offline store (by clicking the "delete" button) sends a license request again, but this time license request headers are not added to the license request, which is wrong. The license request headers must be added to the license request in this case as well. These license request headers are often used for authentication, so without them, license requests fail.

**Comment by joeyparrish** [comment]
This should be reproducible using the Axinom multi-DRM asset, but a platform that supports offline DRM content is required.

**Comment by TheModMaker** [comment]
@joeyparrish We can't use the Axinom assets since they don't allow persistence.  But we can use any of the demo Widevine assets with the header authentication endpoint in the [license authentication tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html).

@vladimir-kazakov I have confirmed that this happens.  But it is important to note that this is an app problem.  It is the job of the app to authenticate any license requests as needed.  So if you are storing things offline, then you need to store whatever authentication info that is needed along with it (e.g. using the [opt_appMetadata](https://shaka-player-demo.appspot.com/docs/api/shaka.offline.Storage.html#store) property).

I will update the demo app to do this.  But a custom app will need to configure the `Player` that is given to the `Storage` instance with any needed authentication.

**Comment by joeyparrish** [comment]
Fix cherry-picked for v2.3.2

**Comment by barinbritva** [comment]
Still doesn't work for me.

**Comment by TheModMaker** [comment]
@barinbritva What doesn't work?  What steps did you take to get a problem?  This only applies to the demo app; if you are using a custom app, it is your responsibility to set up any authentication before calling `storage.remove`.
