### ISSUE TITLE
Offline Storage fails with IDB error

### ISSUE THREAD

**Issue by Moiahbabi** [google/shaka-player#1230]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes.
**What version of Shaka Player are you using**: 2.3.0
**Can you reproduce the issue with our latest release version**: Yes.
**Can you reproduce the issue with the latest code from `master`**: I used the Demo app
**Are you using the demo app or your own custom app**: Both.
**If custom app, can you reproduce the issue using our demo app**:

**What browser and OS are you using**:
Chrome version 63.0.3239.132 (Official Build) (64-bit), Windows 10 (OS Build 16299.192)
**What are the manifest and license server URIs**: Demo App Manifests list

*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?**
loading Sintel 4k (MP4 only/WebM only), and clicking the store button.

**What did you expect to happen?**
Successful Offline storage & playback. 

**What actually happened?**
Got this error:
Failed to execute 'add' on 'IDBObjectStore': The object store uses out-of-line keys and has no key generator and the key parameter was not provided.

**Comment by joeyparrish** [comment]
Confirmed.  Reproduced on the first try for me in Chrome with the latest code.

**Comment by joeyparrish** [comment]
We are working on a fix.  As a work-around, you can clear your IndexedDB storage in the Chrome debugger.

**Comment by joeyparrish** [comment]
This affects all app upgrades to v2.3 where there was any offline content stored by an earlier version.  All v2.3.x releases are affected.

**Comment by joeyparrish** [comment]
We are going to implement the quickest fix we can for this issue: a new error code to detect upgrade issues and a new method to delete the existing database.  This will allow applications to recover from this issue, albeit at the expense of any content already stored by end-users.  The changes will appear in our next release, v2.3.2.

**Comment by joeyparrish** [comment]
To track the long-term fix, in which we will support reading data from older versions, subscribe to #1248.

**Comment by Moiahbabi** [comment]
I was able to store/read/delete offline content once I deleted the old database. however, I just want to note that reading/deleting data from old databases (in my case v2.2.7) worked just fine, but adding new content to the old db was not possible due to this error. this was tested on my custom app.

thanks.

**Comment by joeyparrish** [comment]
We are unable to add new content because of a problem in the schema of the upgraded tables.  During our investigations, we found that the mis-upgraded tables were only part of the problem.  Larger tables could not be upgraded at all, leaving the v2.2 content completely inaccessible if it is over a certain size.

**Comment by vaage** [comment]
We have removed the upgrade code using this list of CLs:

965dc8e1007324540c0ce885c5c346be3b9b3ea4
c168ee86ad61ae856d4d71cee6264622c151db91
9e89a90d3cdbe5c13eb9b2f8e11612b99a739894
4147e77f051fea715a5939da29de2ce632235926
bd2b163743c0fcc8ddc358f916a4356d0b1cdf04
With these CLs, if your storage needs to upgrade, the storage operation will fail with the error UNSUPPORTED_UPGRADE_REQUEST. If you catch this you can delete the database backing storage by using shaka.offline.Storage.deleteAll. In the error, data[0] will have a list of original content uris so that you can re-download all the content again.

To get updates on progress on supporting older storage version, please follow #1248.

**Comment by joeyparrish** [comment]
Fixes cherry-picked for v2.3.2
