### ISSUE TITLE
Shaka player setup

### ISSUE THREAD

**Issue by DanielMartine** [google/shaka-player#1238]
Hi there, I'm living dash.js cause i can't find how to manage live streaming with properly seek range etc.
May i ask you some help to understand how to work with? I successful compile shaka player, below is my situation, i read about live steaming:
`shaka.player.DashVideoSource.event:SeekRangeChanged` that this line could archive the effect, but i don't know where to put it, basically i need a live skin without seeker play and pause but this effect on the seeker is very nice, however i don0t know how to modify the player, could you help me a little?
Thanks,
Dan

MPD:
```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.7.2-DEV-rev358-g433fbcc3-master  at 2018-01-20T02:34:44.293Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT16.000S" type="dynamic" publishTime="2018-01-20T02:34:44Z" availabilityStartTime="2018-01-20T01:33:04.192Z" timeShiftBufferDepth="PT0H1M20.000S" minimumUpdatePeriod="PT0H4M0.000S" maxSegmentDuration="PT0H0M10.000S" profiles="urn:mpeg:dash:profile:isoff-live:2011,http://dashif.org/guidelines/dash264">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>manifest.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period id="DID1" start="PT0H0M0.000S">
  <AdaptationSet segmentAlignment="true" maxWidth="768" maxHeight="432" maxFrameRate="25" par="16:9" lang="eng">
   <Representation id="1" mimeType="video/mp4" codecs="avc1.64001E" width="768" height="432" frameRate="25" sar="1:1" startWithSAP="1" bandwidth="87054">
    <SegmentTemplate media="104e_dash_track1_$Number$.m4s" timescale="12800" startNumber="1" duration="102400" initialization="104e_dash_track1_init.mp4"/>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" lang="eng">
   <Representation id="2" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="48000" startWithSAP="1" bandwidth="16762">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <SegmentTemplate media="104e_dash_track2_$Number$.m4s" timescale="48000" startNumber="1" duration="384000" initialization="104e_dash_track2_init.mp4"/>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

BASIC USAGE STEP:

```
<!DOCTYPE html>
<html>
  <head>
    <!-- Shaka Player compiled library: -->
    <script src="dist/shaka-player.compiled.js"></script>
    <!-- Your application source: -->
    <script src="myapp.js"></script>
  </head>
  <body>
    <video id="video"
           width="640"
           poster="//shaka-player-demo.appspot.com/assets/poster.jpg"
           controls autoplay></video>
  </body>
</html>
```

```
var manifestUri = 'video/manifest.mpd';

function initApp() {
  // Install built-in polyfills to patch browser incompatibilities.
  shaka.polyfill.installAll();

  // Check to see if the browser supports the basic APIs Shaka needs.
  if (shaka.Player.isBrowserSupported()) {
    // Everything looks good!
    initPlayer();
  } else {
    // This browser does not have the minimum set of APIs we need.
    console.error('Browser not supported!');
  }
}

function initPlayer() {
  // Create a Player instance.
  var video = document.getElementById('video');
  var player = new shaka.Player(video);

  // Attach player to the window to make it easy to access in the JS console.
  window.player = player;

  // Listen for error events.
  player.addEventListener('error', onErrorEvent);

  // Try to load a manifest.
  // This is an asynchronous process.
  player.load(manifestUri).then(function() {
    // This runs if the asynchronous load is successful.
    console.log('The video has now been loaded!');
  }).catch(onError);  // onError is executed if the asynchronous load fails.
}

function onErrorEvent(event) {
  // Extract the shaka.util.Error object from the event.
  onError(event.detail);
}

function onError(error) {
  // Log the error.
  console.error('Error code', error.code, 'object', error);
}

document.addEventListener('DOMContentLoaded', initApp);
```

**Comment by DanielMartine** [comment]
I can't understand how to customise UI controls

**Comment by joeyparrish** [comment]
`shaka.player.DashVideoSource.event:SeekRangeChanged` is from our v1 API, which we no longer support.  The document in which you found that is very old, and should be disregarded.  The rest of your sample code appears to be from our v2 API, which is current.  The docs for our latest release are here: https://shaka-player-demo.appspot.com/docs/api/index.html

UI controls are not part of Shaka Player at this time.  We provide the library and an API on which you can build your application and your controls UI if you wish.  You can also use the browser's built-in video controls if you wish.  In your sample HTML above, you have the `control` attribute on the `<video>` tag, which enables the browser's built-in controls.  The browser's built-in controls do not generally work well for live streaming.

The method you want in the v2 API is [`player.seekRange()`](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#seekRange).  There is no corresponding event because the range changes as playback progresses, so you can simply poll `seekRange()` when you are playing live content.  You can use [`player.isLive()`](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#isLive) to determine if something is live content.

Custom video controls can be overlayed over the `<video>` element using CSS, and you can put whatever you like there.  Be sure to remove the `controls` attribute from the `<video>` element to disable the browser's built-in controls.  For a fully-worked example of video controls, you can refer to the ones in our demo app:
  - https://github.com/google/shaka-player/blob/v2.3.x/demo/common/controls.js
  - https://github.com/google/shaka-player/blob/v2.3.x/demo/common/controls.css
  - https://github.com/google/shaka-player/blob/v2.3.x/demo/index.html
  - https://github.com/google/shaka-player/blob/v2.3.x/demo/demo.css

We hope to be able to provide a reusable video controls component in the future, but for now, we hope these examples will be helpful.

**Comment by DanielMartine** [comment]
Thanks so much @joeyparrish your thread is the perfect starting point!
