### ISSUE TITLE
Request for comments on leap second handling

### ISSUE THREAD

**Issue by sandersaares** [google/shaka-player#1242]
DASH-IF has published document for community review.

LEAP SECOND HANDLING CLARIFICATIONS

* The change request against IOP v4.1 for [Community Review is accessible here](http://dashif.org/wp-content/uploads/2018/01/CR-leapseconds-community-review.pdf)
* Community review is open until April 15th, 2018. Addition to IOP is expected by Q2/2018.
* Comments may be submitted through the [public bugtracker](https://gitreports.com/issue/Dash-Industry-Forum/DASH-IF-IOP).
* This addition adds the following main features: Clarifies how to handle leap seconds and how to avoid common pitfalls

It would be very desirable to hear some feedback from player developers on this topic!

**Comment by vaage** [comment]
@joeyparrish could you take a look at this?

**Comment by joeyparrish** [comment]
@sandersaares, that all looks fine to me.  Realistically, we are not going to implement a leap-second-aware clock, though.  The whole thing is predicated on the use of availabilityStartTime to compute the perfect presentation timeline.  But we already can't count on availabilityStartTime because of encoder drift.  See #999.  Ultimately, we will ignore availabilityStartTime for all but SegmentTemplate+duration manifests.

**Comment by sandersaares** [comment]
Thanks for taking a look! Glad to hear there was nothing surprising in there.

Do I understand it right from your comment about leap-second-aware clock that whatever browser based timing mechanism is used by Shaka is not leap second aware? That is to say, when Shaka currently adds a `period@start` to `MPD@availabilityStartTime`, is the former added as a duration of Unix ticks, thereby ending up with a result N seconds in the future compared to real time (where N is the elapsed count of leap seconds)?

**Comment by joeyparrish** [comment]
We use `Date.parse` to parse XML date strings.  I don't know if it is leap-second aware or not.  We convert date strings into seconds since 1970.  See [`shaka.util.XmlUtils.parseDate`](https://github.com/google/shaka-player/blob/bd2b163743c0fcc8ddc358f916a4356d0b1cdf04/lib/util/xml_utils.js#L106).

In your example, we compare the results of `Date.parse` with the results of `Date.now` to understand how long the stream has been running and compute the ideal presentation time of the live edge.  Clock sync, if used, will offset `Date.now` by some amount first.

**Comment by ddorwin** [comment]
For what it's worth, EME's definition of time is at https://w3c.github.io/encrypted-media/#time. It defers to ECMAScript Date Objects where "[In time values leap seconds are ignored.](https://tc39.github.io/ecma262/#sec-time-values-and-time-range)"

**Comment by sandersaares** [comment]
It does indeed look like `Date.parse` ignores leap seconds, which will likely lead to an availability timeline de-sync for content that uses real-time-accurate timing.

I will close this now as comments were received and questions answered. Thanks!
