### ISSUE TITLE
Change MediaSourceEngine to use Blobs

### ISSUE THREAD

**Issue by vaage** [google/shaka-player#1244]
Blobs leave a smaller memory footprint as they are more like temp files. This makes it fast to move data between processes. We would like to change MediaSourceEngine to use Blobs instead of ArrayBuffers.

**Comment by TheModMaker** [comment]
This would be a really nice addition, but we can't use Blobs with MediaSource.  The [appendBuffer](https://w3c.github.io/media-source/#idl-def-sourcebuffer) method accepts a [BufferSource](https://www.w3.org/TR/WebIDL-1/#common-BufferSource), which is only an `ArrayBuffer` or an `ArrayBufferView` (i.e typed arrays).

**Comment by vaage** [comment]
The conversion from Blob To BufferSource can be done in MediaSourceEngine, allowing Blobs to be used everywhere else.

**Comment by TheModMaker** [comment]
Why?  The advantage of Blob is it is not in main memory.  If we could just tell MediaSource "pull from this response object", then that would be a reason to use Blobs.  But since we can't, we need to copy the blob to main memory anyway, so why not have XHR do it for us?  It would probably be more efficient for XHR to copy the data than for us to copy it.  We also sometimes need to parse the response anyway, so we would need to have a lot of extra logic to avoid reading/copying the Blob twice.  I can't think of a reason to use Blobs if we can't pass them to a browser API that uses it (e.g. MediaSource or EME).

The exception may be to support storage.  But I don't think we should pipe Blobs through our whole system just so we can get a little efficiency when *storing* content.

**Comment by vaage** [comment]
@joeyparrish ?

**Comment by joeyparrish** [comment]
I had suggested we use Blobs everywhere, since XHR, Fetch, and IndexedDB all support blobs.  But if MediaSource doesn't support them, and we will need to read network responses in some places anyway, we should probably just use Blobs in IndexedDB after all.

**Comment by joeyparrish** [comment]
Sorry for the confusion.  I should have researched a little more before suggesting this.
