### ISSUE TITLE
Live/DVR Stream again

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#1251]
## NOTE: For bugs, if you delete this template, we will send it again and ask you to fill it out.

**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
yes

**What version of Shaka Player are you using?**:
2.3.0

**Can you reproduce the issue with our latest release version?**:
yes

**Can you reproduce the issue with the latest code from `master`?**:
yes

**Are you using the demo app or your own custom app?**:
own app (no HTTPS for this Stream)

**If custom app, can you reproduce the issue using our demo app?**:
sadly no (no HTTPS)

**What browser and OS are you using?**:
Windows 10 , Firefox + Chrome

**What are the manifest and license server URIs?**:
http://spiegelaos1.spiegel.adaptive.level3.net/egress/bhandler/sponrtmp/nexxtv/manifest.mpd

**What did you do?**
load Shaka, start Manifest

**What did you expect to happen?**
LiveStream shoudl start and play continuously

**What actually happened?**
LiveStream stops after a few Seconds (sometimes longer) and does not continue. I can see, that permamently Manifest Parts are loaded, but it does not restart/continue. Video-Object-wise, I see a lot of "waiting", "seeking", "stalled".
The Stream does run smothly without any Issues in BitMovin and DASH-IF though, so it may be a Problem, with our Implementation (hopefully :P) or something does not work correctly here.

As far as I understand, this is a "DVR" LiveStream (which enables seek-back), I am not sure, if I must handle such a Stream differently to a "normal" Live-Live Stream (no Seek-back). If yes, thats maybe the Problem. It would be nice, if you could help me getting on on how to handle this Stream (including finding out what Amount of Time can be seeked back and how to control that.) As far as I can judge, this is not handled inside the Docs - a normal "load Manifest and done" is not enough in this Case.

As always - thanks a lot!

ps: sadly, I cannot deliver a HTTPS for this Stream currently, thats why I couldnt test it in the DemoApp.

**Comment by BucherTomas** [comment]
@boredom2  You actually can load an http stream with the https demo app. You just need to temporarily disable the mixed content error in browser.

This used to work fine in Chrome and Shaka just by enabling unsafe scripts in the new shield icon that pops up in the address bar once you attempt to load an http stream, but it no longer works with Shaka version 2.3.0 and newer. Something to be looked at by Shaka team?

Interestingly enough, it still does work even with new Shaka versions and Firefox. Just attempt to load your stream, click then on the green padlock icon in address bar, click on "show connection details" arrow and finally click on "Disable protection for now" button.

**Comment by boredom2** [comment]
Hi there.
Thanks for that - I can load it in FireFox now.
But the Result is like in our Player - permanent Loading and Updating, but no Playback anymore (cannot find Segment).
So is this a SHAKA-related Problem then?

**Comment by vaage** [comment]
@boredom2 I was able to reproduce your issue using @BucherTomas suggestion of using FireFox (thanks).

I can confirm that after the initial buffered content, it seems to no longer be able to buffer the next segments. When I look at the logs I see:
```
(audio:2) update_: playheadTime=11729.85899567604 bufferedAhead=0
(audio:2) next position unknown: nothing buffered
(audio:2) looking up segment: presentationTime=11729.85899567604 currentPeriod.startTime=0
(audio:2) cannot find segment: currentPeriod.startTime=0 lookupTime=11729.85899567604
```

So the problem lies with not being able to buffer the content, but I don't know why. I am gonna have someone else look at your manifest to see if there is an issue there before digger further into the player.

**Comment by vaage** [comment]
@boredom2 When if request your manifest, even if I wait 10 minutes between requests, I don't see the time in the segment timeline advancing. Correct me if I am wrong, but shouldn't the segment timeline be getting updated?

**Comment by BucherTomas** [comment]
As of the time of writing, segments are returning 504 in the example stream, but the manifest still works and it is returning `cache-control` http header set to `max-age=600`, which means that it can be actually cached up to 10 minutes twice along the way,

1. Level3 CDN used for delivery honoring the header provided by origin (or configured for this Level3 service explicitly) is caching the manifest on their nodes which is proved by their `Age` http headers.
2. Browser also honoring the header is caching it locally.

Player is then provided with stale manifest for 10 minutes. The cache-control header of the manifest for live streams needs to be set to less than what `minimumUpdatePeriod` in the mpd states so that it can be properly refreshed both on CDN and in the browser.

Not sure, though, how it could have worked in Bitmovin and Dash-IF, maybe the caching was configured differently at that time? Also, the live stream is generated by Wowza Streaming Engine which does not support true DVR for MPEG-DASH streams yet, so it should not be a factor in your issue.

**Comment by boredom2** [comment]
Hi there.
Thanks for your Analysis and yes - due to the Fact, that this was a LiveStream, I couldnt let it up "forever", its a Stream from our Clients. It is also right - "Level3" (the german Outlet of the US Century Link CDN) uses Wowza here, and I knew, that this would make Problems :)
I can arrange another Session tomorrow if this would help find out whats wrong here. Would this be helpfull?

**Comment by BucherTomas** [comment]
Based on what I saw, I'd first focus on getting the cache-control header right for the mpd manifest.

Set the value to 1 second or ask the administrators of the server to do it, if you don't have access. Wowza has `mpegdashCacheControlPlaylist` property for it in the application.xml when in http origin mode, however, I also noticed that copied server user agent returned from CDN is in fact nginx so there might be some cache or proxy nginx between Wowza and the CDN. In that case check and update the value there if needed.
If you find that the origin server is set up correctly, then it might be also caused by some default setting of the CDN itself, in that case you would need to request the change with them.

Once that is done, the manifest will be properly refreshed for the player every time it tries to reload it and then you can have a look at the stream again.

**Comment by TheModMaker** [comment]
@boredom2 Please fix the caching problems and give us a new manifest URL so we can test it.

**Comment by boredom2** [comment]
Hi there. Good Timing.
We had a long Conversation with the CDN and they accepted that the Caching was not optimally configured. Their latest Stream run completely in 2.3.1 today - so far, I would say - SHAKA is doing well :)
Thanks again for these in-depth Analysis!
