### ISSUE TITLE
Add support for picture-in-picture API

### ISSUE THREAD

**Issue by hbengali** [google/shaka-player#1252]
https://wicg.github.io/picture-in-picture/

Has already been implemented on Chrome for Android. Support in desktop versions of Chrome is being worked on.

**Comment by chrisfillmore** [comment]
I believe this is supported in Safari right now (at least I've seen the behaviour, I haven't checked if it's indeed this API). But what does this have to do with Shaka?

**Comment by boredom2** [comment]
I wished it would be supported, but Safari uses the iOS-way (webkitPresentationMode). I would also say, that this is off-topic for SHAKA as Engine (but a very interesting Topic :P).

**Comment by joeyparrish** [comment]
Once the [linked draft spec](https://wicg.github.io/picture-in-picture/) can be tested in Chrome, we will add support to our demo app to show how it can be used with Shaka Player.  We do not anticipate any changes to the library itself for this.

**Comment by humanamburu** [comment]
Hi @joeyparrish,

Chrome 70 officially supports PiP (https://developers.google.com/web/updates/2018/10/watch-video-using-picture-in-picture).

I've checked the new API and PiP really looks good and works OK but unfortunately only for one video source.

Something is going wrong when I'm trying to load a new video. Shaka loads a new manifest and I can hear a video sound but the PiP screen is black 😢 But when I close the PiP window, I can see usual playback and everything works fine.

I'm understand that PiP feature isn't implemented as part of Shaka API but could you please advice, is it expected behavior for 2.3.3 Shaka and PiP will work only after Shaka Player updates or smth probably wrong with my implementation?

**Comment by joeyparrish** [comment]
We haven't investigated PIP yet, but we will do so very soon.  At this time, we don't have any advice on this.  We expect that PIP can be completely outside the Shaka Player library, but we could be wrong.  For now, I suggest you double-check your implementation.  In fact, if you can send us a snippet, that might help us both.

**Comment by ismena** [comment]
FYI: We plan for PiP to be a part of the (coming soon) Shaka UI Layer, but, as Joey mentioned, we have not worked on the implementation yet.
