### ISSUE TITLE
Live multi periods with $time template

### ISSUE THREAD

**Issue by sym39** [google/shaka-player#1265]
Hello all,

## NOTE: For bugs, if you delete this template, we will send it again and ask you to fill it out.

**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
YES

**What version of Shaka Player are you using?**:
2.2.9, 2.3.1

**Can you reproduce the issue with our latest release version?**:
yes

**Can you reproduce the issue with the latest code from `master`?**:
no

**Are you using the demo app or your own custom app?**:
demo app

**If custom app, can you reproduce the issue using our demo app?**:
-

**What browser and OS are you using?**:
firefox 58.0 on linux

**What are the manifest and license server URIs?**:
*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

See below
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

**What did you do?**
Try to make multi periods working with live

**What did you expect to happen?**
the content is played smoothly  

**What actually happened?**
the player stops, except if the _Jump large gaps_ is checked

## Description

first, this is more a question than a bug report, I would like to know what I should do to make DASH live  multi periods work with ShakaPlayer.
 
For the moment, I am unable to make multi periods working correctly:
what I do is modifying a live stream with one period to another live stream with multiple periods.
I take care to insert periods at the same time and to name them the same to avoid Shaka Player to be lost. 

- With only one video track or one audio track, it hangs rarely, but with both tracks (audio + video), it quickly stops unless the large gaps option is checked; when the option is checked, the content quickly hangs then restart;
- I regularly see the message _Ignoring large gap at XXXX.XXX_ but when I check the generated manifests, I do not see any gap in it:
-- a new period always begins at the same time (I check it in the generated manifests)
-- there is no gap between the last period and this new period (idem)

I tried multiple ways to generate the periods:
- by setting the period @start arguments to 0 everywhere, and @presentationTimeOffset to 0
- by setting the period @start to relative duration of the period, and the @presentationTimeOffset to the same value (arranged with the timescale) - I can not make it work at all with Shaka Player

Some questions:
- Is it correctly supported to put 0 as period.@start for all periods
- is it mandatory to put a specific dash event (I put none)
- what does mean the assertion message _Assertion failed: SegmentReferences are incorrect segment_index.js:317:5_
- is it mandatory to have as many audio fragments as video fragments in a period? I tried to avoid it but it does not seem to change the result
- is it correctly handled, for the older or the newer period to have one empty adaptation set for a media? I tried to avoid it but it does not seem to change the result
- would it be better to have the same timescale for all representations?

Attached is an example of some generated manifests.

Thanks,
[mans.zip](https://github.com/google/shaka-player/files/1682721/mans.zip)

Sylvain

**Comment by TheModMaker** [comment]
First, how about I explain how Periods work in Dash.  A Period represents an independent piece of the presentation timeline.  This can be thought of as a single video (or a piece of it).  Times within a Period are relative to the Period start, so you could insert a Period before another and the times would fix themselves.  This allows you to stitch together independent videos without much effort.

What this means for your case is that each Period needs to have the correct times.  The times in the media need to start at 0 within each Period.  You can use `presentationTimeOffset` to adjust the segment times so they start at 0.  It is important to note that the segment times in the manifest need to match those in the media.  You can't just adjust the times in the manifest because once we append the media segment, it will appear at the wrong time in the `<video>` element.  The `presentationTimeOffset` will also adjust the media times, so the media segment will appear at the correct time.

Each Period also needs to have a duration.  This can be done by using the `duration` attribute on the `<Period>` element, or it can be done implicitly by setting the `start` of the Period that follows it.  Many manifests will only use the `duration` attribute since it makes it easier to add a new Period without having to adjust the `start` time of every following Period.  However, you need to set the `start` of the first Period or we will assume it is 0, which for live may not be what you want.  Since you set the start of every Period to 0, the first Period will have a duration of 0, which is not allowed.

Here is an example:  With a `availabilityStartTime` of `2018-01-01T00:00:00Z`, a Period start of `PT30S`, and a `timescale` if 1.  If a segment starts at 300 with a `presentationTimeOffset` of 100 that puts the time within the Period at 200 seconds.  Add the Period start and the segment will really play 230 seconds into the live stream, or a wall-clock time of `2018-01-01T00:03:50Z`.

Also note that you need to split Periods at a segment boundary (on all streams).  So if you split a stream at 30s; the first Period needs to have *at least* 30 seconds of content and the first segment of the next Period must start at 0, which will align with the end of the previous Period.  If you use `presentationTimeOffset` to offset the segment and it starts at before 0, we won't be able to play it due to browser limitations.  We can only play segments whose period-relative start time is 0 or greater.

> I take care to insert periods at the same time and to name them the same to avoid Shaka Player to be lost.

If you mean every Period in the manifest has the same `id` and `start` time, that is invalid.  A Period with the same `id` must represent the same content.  So in a manifest update, if we see a Period with the same `id`, we will think it is the same as the previous update and try to merge things.  Different Periods require different `id`s.

> * Is it correctly supported to put 0 as period.@start for all periods

You can't have the `Period@start` be 0 for all Periods, that means that every Period starts at the same time, so they will overlap (which isn't allowed).  The Period time must start at the time you want it to appear in the presentation.

> * is it mandatory to put a specific dash event (I put none)

Nope, just update the manifest.  Make sure you set `minumumUpdatePeriod` so we will fetch the updated manifest.

> * what does mean the assertion message *Assertion failed: SegmentReferences are incorrect segment_index.js:317:5*

This may be a bug on our part, but since you are setting all the Periods start to 0, that is likely the problem.  You can't have overlapping Periods.

> * is it mandatory to have as many audio fragments as video fragments in a period? I tried to avoid it but it does not seem to change the result

The number of segments per Period doesn't matter and doesn't have to match.  The audio and video can have different number of segments and different Periods can have different count.  The important thing is that the amount of media content is correct.  If the Period says it has a duration of 30 seconds, then you need *at least* 30 seconds of media content for all streams.

> * is it correctly handled, for the older or the newer period to have one empty adaptation set for a media? I tried to avoid it but it does not seem to change the result

I am fairly sure this isn't allowed.  I think each `AdaptationSet` requires at least one `Representation`.  Each `Representation` requires having segment info.  So you can't have a `Representation` without any segments in it.

> * would it be better to have the same timescale for all representations?

It doesn't matter.  Usually the timescale in the manifest matches the timescale of the media.  In this case, the representations won't have the same timescale since audio and video usually use different timescales.

Hopefully this will help.  Does this answer all your questions?

**Comment by sym39** [comment]
Thanks a lot for your response. 
I have still questions / need some clarification to make sure I have understood.

For what I understand, the most important problems in my implementation is that
- `period.@start` must really be set and can not be 0 for all periods
- the timeline should be the same for all tracks: it is not allowed to have a track that is somewhat shifted in the manifest, even if this does not cause problems with only one period 

> What this means for your case is that each Period needs to have the correct times. The times in the media need to start at 0 within each Period. You can use presentationTimeOffset to adjust the segment times so they start at 0.

Speaking from 0 confuse me a bit, it reminds me static content. I guess you mean I have to play with `period.@start`  and `@presentationTimeOffset` so that the time of a fragment is correct. Something like `start_time = ast + period_start - pto + t` 

> Each Period also needs to have a duration. This can be done by using the duration attribute on the <Period> element, or it can be done implicitly by setting the start of the Period that follows it. Many manifests will only use the duration attribute since it makes it easier to add a new Period without having to adjust the start time of every following Period. However, you need to set the start of the first Period or we will assume it is 0, which for live may not be what you want. Since you set the start of every Period to 0, the first Period will have a duration of 0, which is not allowed.

What about period that are not complete? I understand I have to ensure the timeline begins at the same time for all tracks (audio/video/text)?

> Here is an example: With a availabilityStartTime of 2018-01-01T00:00:00Z, a Period start of PT30S, and a timescale if 1. If a segment starts at 300 with a presentationTimeOffset of 100 that puts the time within the Period at 200 seconds. Add the Period start and the segment will really play 230 seconds into the live stream, or a wall-clock time of 2018-01-01T00:03:50Z.

OK.

> Also note that you need to split Periods at a segment boundary (on all streams). So if you split a stream at 30s; the first Period needs to have at least 30 seconds of content and the first segment of the next Period must start at 0, which will align with the end of the previous Period. If you use presentationTimeOffset to offset the segment and it starts at before 0, we won't be able to play it due to browser limitations. We can only play segments whose period-relative start time is 0 or greater.

OK, I understand I really have to make sure my timeline is the same for all fragments

> If you mean every Period in the manifest has the same id and start time, that is invalid. A Period with the same id must represent the same content. So in a manifest update, if we see a Period with the same id, we will think it is the same as the previous update and try to merge things. Different Periods require different ids.

I was not clear, each period has an unique id inside the MPD, but I take care that those ids remain the same between multiple manifest update.

> You can't have the Period@start be 0 for all Periods, that means that every Period starts at the same time, so they will overlap (which isn't allowed). The Period time must start at the time you want it to appear in the presentation.

What is strange is that it looks to work (even if it fails rarely) with only one content (audio or video but not both). May be I was lucky?


> Nope, just update the manifest. Make sure you set minumumUpdatePeriod so we will fetch the updated manifest.

OK, it was set.

> This may be a bug on our part, but since you are setting all the Periods start to 0, that is likely the problem. You can't have overlapping Periods.

OK, I will see.

> The number of segments per Period doesn't matter and doesn't have to match. The audio and video can have different number of segments and different Periods can have different count. The important thing is that the amount of media content is correct. If the Period says it has a duration of 30 seconds, then you need at least 30 seconds of media content for all streams.

I was not clear, I meant the same number of fragments of same duration (and without discontinuity at all)

> I am fairly sure this isn't allowed. I think each AdaptationSet requires at least one Representation. Each Representation requires having segment info. So you can't have a Representation without any segments in it.

I will try to avoid it.

> It doesn't matter. Usually the timescale in the manifest matches the timescale of the media. In this case, the representations won't have the same timescale since audio and video usually use different timescales.

OK.

> Hopefully this will help. Does this answer all your questions?

Thanks a lot, now, it is time to me to change the implementation and to retry.

Sylvain

PS : Annotated version of a manifest with necessary corrections to make it hopefully correct
```
<MPD
  xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
  availabilityStartTime="2015-01-01T00:00:00Z"             <-- unix timestamp is 1420070400
  publishTime="2018-01-31T22:04:47.310073Z"
  minimumUpdatePeriod="PT2S"
  maxSegmentDuration="PT3S"
  minBufferTime="PT0S"
  <Period
    id="period_97365820"                                   <-- unique period name inside the manifest
    start="PT0S">                                          <-- period has begun in the past and it is 
    <AdaptationSet                                          -- incomplete because the window length is 
      id="1"                                                -- not long enough
      <SegmentTemplate
        timescale="48000"
        initialization="dash2-$RepresentationID$-init.mp4"
        media="dash2-$RepresentationID$-$Time$.mp4">
        <SegmentTimeline>                                  <-- still no presentationTimeOffset means it is 0                                  
          <S t="4673560004160" d="95232" />                <-- 2018-01-31 22:03:53.4Z (4673560004160/48000.0 = 97365833.42,date -d @$((1420070400+97365833)) "+%Y-%m-%d %T" --utc
          <S d="96255" />                                   -- duration of audio fragments 
          <S d="96257" />                                   -- are around 2 sec.
          <S d="96256" />
          <S d="95232" />
          <S d="96255" />
          <S d="96257" />
          <S d="96256" />
          <S d="95232" />                                  <-- 9 items, around 18 sec.
        </SegmentTimeline>                                 ==> first item must be removed so that audio and video begins and ends
      </SegmentTemplate>                                       at the same time (see below video)
      <Representation
        id="audio_20005=96000.track_id=20005"
      </Representation>
    </AdaptationSet>
    <AdaptationSet
      id="2"
      <SegmentTemplate
        timescale="25"
        initialization="dash2-$RepresentationID$-init.mp4"
        media="dash2-$RepresentationID$-$Time$.mp4">
        <SegmentTimeline>                                  <-- still no presentationTimeOffset means it is 0                                  
          <S t="2434145885" d="50" r="7" />                <-- 2018-01-31 22:03:55.4Z
        </SegmentTimeline>                                  -- notice the first video begins 2 seconds later than the audio
      </SegmentTemplate>                                    -- only 8 items (16 seconds)
      <Representation                                          ==> The timeline must be changed
        id="video=100000.track_id=10000"                       ==> so that it begins at the same time
      </Representation>                                        ==> in this case, the first audio fragment may begin one fragment later
      <Representation                                          ==> to be in sync with video
        id="video=110000.track_id=10001"
      </Representation>
    </AdaptationSet>
  </Period>
  <Period
    id="period_97365850"                                   <-- unique period name inside the manifest, this period is complete
    start="PT0S">                                          ==> start must be 16 sec
    <AdaptationSet
      id="1"
      <SegmentTemplate
        timescale="48000"
        initialization="dash2-$RepresentationID$-init.mp4"
        media="dash2-$RepresentationID$-$Time$.mp4">
        <SegmentTimeline>                                  ==> presentationTimeOffset must be 16 sec. (16*48000) so that I do not have to change the t=                                  
          <S t="4673560867392" d="96255" />                <-- 2018-01-31 22:04:41.4Z
          <S d="96257" />
          <S d="96256" />
          <S d="95232" />
          <S d="96255" />
          <S d="96257" />
          <S d="96256" />
          <S d="95232" />
          <S d="96255" />
          <S d="96257" />
          <S d="96256" />
          <S d="95232" />
          <S d="96255" />
          <S d="96257" />
          <S d="96256" />                                  <-- 15 items
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation
        id="audio_20005=96000.track_id=20005"
      </Representation>
    </AdaptationSet>
    <AdaptationSet
      id="2"
      <SegmentTemplate
        timescale="25"
        initialization="dash2-$RepresentationID$-init.mp4"
        media="dash2-$RepresentationID$-$Time$.mp4">
        <SegmentTimeline>                                  ==> presentationTimeOffset must be 16 secs (16*25 here)                                  
          <S t="2434146285" d="50" r="14" />               <-- 2018-01-31 22:04:11.4Z
        </SegmentTimeline>                                 <-- 15 items
      </SegmentTemplate>
      <Representation
        id="video=100000.track_id=10000"
      </Representation>
      <Representation
        id="video=110000.track_id=10001"
      </Representation>
    </AdaptationSet>
  </Period>
  <Period
    id="period_97365880"                                   <-- unique period name inside the manifest
    start="PT0S">                                          ==> start must be 16+30=46
    <AdaptationSet
      id="1"
      <SegmentTemplate
        timescale="48000"
        initialization="dash2-$RepresentationID$-init.mp4"
        media="dash2-$RepresentationID$-$Time$.mp4">
        <SegmentTimeline>                                  ==> presentationTimeOffset must be 46                                  
          <S t="4673562308160" d="95232" />                <-- 2018-01-31 22:04:11.4Z
        </SegmentTimeline>                                  -- only one item
      </SegmentTemplate>                                    
      <Representation
        id="audio_20005=96000.track_id=20005"
      </Representation>
    </AdaptationSet>
    <AdaptationSet
      id="2"
      <SegmentTemplate
        timescale="25"
        initialization="dash2-$RepresentationID$-init.mp4"
        media="dash2-$RepresentationID$-$Time$.mp4">
        <SegmentTimeline>                                  ==> presentationTimeOffset must be 46                                  
          <S t="2434147035" d="50" r="1" />                <-- 2018-01-31 22:04:41.4Z
         </SegmentTimeline>                                 -- 2 items
      </SegmentTemplate>                                    ==> Last item must be removed
      <Representation
        id="video=100000.track_id=10000"
      </Representation>
      <Representation
        id="video=110000.track_id=10001"
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

**Comment by TheModMaker** [comment]
Your first Period looks good.  It starts at 0, but the first audio segment starts at `4673560004160`, which will be played at `AST + periodStart + ((t - PTO) / timescale)`, which will be `2018-31-01T22:03:53Z`.  The first Period contains 16 seconds of content.  You're comment says `start must be 16 sec`, but you didn't change the time in the XML.

It's important to note that there is actually little difference between a VOD and Live manifest.  The only difference is that we update Live manifests and we start playing at the "live edge" rather than 0.  But the timelines are actually the same.  The `availabilityStartTime` specifies the wall-clock time that represents 0 in the presentation timeline.  The first segment in your manifest will appear at 97365833 seconds in the presentation timeline.  When the player starts playing the live stream, it looks at `now - AST` and uses that to determine where to start playing.  So assuming `publishTime` is the time you fetched the manifest, we'll start playing at 97365887 seconds.

Now here is the problem: even though the first Period is correct and only has 16 seconds of content, it actually goes from 0 to 97365851.4 seconds.  There is no content until 97365833 seconds, where you specify the first segment to be.  So if you want to have the second Period start after the first, you'll need to specify the start time as `PT97365851.4S`.

So lets ignore the first Period and focus on the second.  We'll have the start time be `PT97365851.4S`, which will put it where we want it in the presentation timeline.  Now the media segments within that Period need to start at 0.  The manifest specifies that the first segment starts at `4673560867392 / 48000`, or 97365851 seconds.  Segment times are relative to the Period, so we add the Period start time to get a presentation time of 194731702.4 seconds, or over 37 months from now.

So we need to adjust the media times back so it appears at the correct time within the Period.  This is easily done by just setting the `presentationTimeOffset` value to the start time of the Period.  So that will be `97365851.4 * timescale` or 4673560867200 (for audio).  This will adjust the media time to appear at 0, so when we add the Period start, will put the presentation time in the correct spot.

It is important to start with the exact same number of seconds when calculating PTO for each stream.  So you'll set the video stream's PTO to `97365851.4 * 24` or 2434146285.  If you simply try setting PTO to the time of the first segment, you'll get A/V desync.

So the correct second Period would be (with some unchanged stuff removed):

```xml
<Period id="period_97365850" start="PT97365851.4S">
    <AdaptationSet id="1">
      <SegmentTemplate
        timescale="48000"
        presentationTimeOffset="4673560867200"
        initialization="dash2-$RepresentationID$-init.mp4"
        media="dash2-$RepresentationID$-$Time$.mp4">
        <SegmentTimeline>
          <S t="4673560867392" d="96255" />
        </SegmentTimeline>
      </SegmentTemplate>
    </AdaptationSet>
    <AdaptationSet id="2">
      <SegmentTemplate
        timescale="25"
        presentationTimeOffset="2434146285"
        initialization="dash2-$RepresentationID$-init.mp4"
        media="dash2-$RepresentationID$-$Time$.mp4">
        <SegmentTimeline> 
          <S t="2434146285" d="50" r="14" />
        </SegmentTimeline> 
      </SegmentTemplate>
    </AdaptationSet>
</Period>
```


------

> What about period that are not complete? I understand I have to ensure the timeline begins at the same time for all tracks (audio/video/text)?

Every Period needs to be complete except for the first and last ones.  The first one can have missing segments at the beginning, but must have a start and duration.  The last Period can have a non-specified duration and you can add segments as they are being generated.

> I was not clear, each period has an unique id inside the MPD, but I take care that those ids remain the same between multiple manifest update.

Ok, that is the correct behavior.

**Comment by sym39** [comment]
Thanks again for your response.
I have modified the way periods are created using your advice, and it is working.

At first, I had the assertion `Assertion failed: SegmentReferences are incorrect segment_index.js:317:5`. The assertion is gone after ensuring the start date of the initial period was fixed to the date of the period, not the date of the first available fragment.

Sylvain

Here is an example of the manifest (some tags are hidden for clarification)
```
<MPD
  xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
  availabilityStartTime="2015-01-01T00:00:00Z"
  minimumUpdatePeriod="PT2S"
  timeShiftBufferDepth="PT47.994667S"
  maxSegmentDuration="PT3S"
  minBufferTime="PT0S"
  <Period
    id="period_97428730"
    start="PT26840H48M10.040S">
    <AdaptationSet
      id="1"
        presentationTimeOffset="4638090721920"
        initialization="dash2-$RepresentationID$-init.mp4"
        media="dash2-$RepresentationID$-$Time$.mp4">
        <SegmentTimeline>
          <S t="4676579971647" d="96257" />
          <S d="96256" />
          <S d="95232" />
          <S d="96255" />
          <S d="96257" />
          <S d="96256" />
        </SegmentTimeline>
      <Representation
        id="audio_20005=96000.track_id=20005"
      </Representation>
    </AdaptationSet>
    <AdaptationSet
      id="2"
        presentationTimeOffset="2415672251"
        initialization="dash2-$RepresentationID$-init.mp4"
        media="dash2-$RepresentationID$-$Time$.mp4">
        <SegmentTimeline>
          <S t="2435718785" d="50" r="4" />
        </SegmentTimeline>
      <Representation
        id="video=100000.track_id=10000"
      </Representation>
      <Representation
        id="video=110000.track_id=10001"
      </Representation>
    </AdaptationSet>
  </Period>
  <Period
    id="period_97428760"
    start="PT27063H32M40.040S">
    <AdaptationSet
      id="1"
        presentationTimeOffset="4676580481920"
        initialization="dash2-$RepresentationID$-init.mp4"
        media="dash2-$RepresentationID$-$Time$.mp4">
        <SegmentTimeline>
          <S t="4676580548160" d="95232" />
          <S d="96255" />
          <S d="96257" />
          <S d="96256" />
          <S d="95232" />
          <S d="96255" />
          <S d="96257" />
          <S d="96256" />
          <S d="95232" />
          <S d="96255" />
          <S d="96257" />
          <S d="96256" />
          <S d="95232" />
          <S d="96255" />
          <S d="96257" />
        </SegmentTimeline>
      <Representation
        id="audio_20005=96000.track_id=20005"
      </Representation>
    </AdaptationSet>
    <AdaptationSet
      id="2"
        presentationTimeOffset="2435719001"
        initialization="dash2-$RepresentationID$-init.mp4"
        media="dash2-$RepresentationID$-$Time$.mp4">
        <SegmentTimeline>
          <S t="2435719035" d="50" r="14" />
        </SegmentTimeline>
      <Representation
        id="video=100000.track_id=10000"
      </Representation>
      <Representation
        id="video=110000.track_id=10001"
      </Representation>
    </AdaptationSet>
  </Period>
  <Period
    id="period_97428790"
    start="PT27063H33M10.040S">
    <AdaptationSet
      id="1"
        presentationTimeOffset="4676581921920"
        initialization="dash2-$RepresentationID$-init.mp4"
        media="dash2-$RepresentationID$-$Time$.mp4">
        <SegmentTimeline>
          <S t="4676581987904" d="96256" />
          <S d="95232" />
          <S d="96255" />
          <S d="96257" />
        </SegmentTimeline>
      <Representation
        id="audio_20005=96000.track_id=20005"
      </Representation>
    </AdaptationSet>
    <AdaptationSet
      id="2"
        presentationTimeOffset="2435719751"
        initialization="dash2-$RepresentationID$-init.mp4"
        media="dash2-$RepresentationID$-$Time$.mp4">
        <SegmentTimeline>
          <S t="2435719785" d="50" r="4" />
        </SegmentTimeline>
      <Representation
        id="video=100000.track_id=10000"
      </Representation>
      <Representation
        id="video=110000.track_id=10001"
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>

```

**Comment by TheModMaker** [comment]
Glad to hear you got it working.  Does this answer all your questions?

**Comment by sym39** [comment]
> Glad to hear you got it working. Does this answer all your questions?

Yes this is OK, thanks a lot again. (So I will close the issue)

Sylvain
