### ISSUE TITLE
Debug buffered ahead does not match stream buffered ahead

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#127]
It looks like the stream.js bufferedAhead count is out of sync from the bufferedAhead count in the sample app debug panel. Sometimes they are 20 seconds apart. I'm not sure which is correct but the bufferedAhead count in the stream.js is often significantly higher than the debug one. This might be causing problems because, assuming the debug panel is correct, the stream is incorrectly thinking it has reached it's buffering goal when according to the debug panel it has not.

**Comment by tdrews** [comment]
The debug panel checks video.buffered whereas SourceBufferManager checks each audio/video buffer individually, so some discrepancy is expected (due to the timing between inserting audio segments and inserting video segments); however, a 20 seconds difference does seem quite large. I'll investigate.

**Comment by tdrews** [comment]
I believe SourceBufferManager.bufferedAhead() and the debug panel are functioning correctly:
I added the lines
```javascript
if (app.player_ && app.player_.videoSource_) {
  shaka.log.debug('VIDEO BUFFERED: ', ahead);
  shaka.log.debug(
      'VIDEO SOURCE BUFFERED: ',
      app.player_.videoSource_.streamsByType_['video'].sbm_.bufferedAheadOf(currentTime));
  shaka.log.debug(
      'AUDIO SOURCE BUFFERED: ',
      app.player_.videoSource_.streamsByType_['audio'].sbm_.bufferedAheadOf(currentTime));
}
```
to the bottom of `app.updateBufferDebug_` and changed
`window.setInterval(app.updateDebugInfo_, 50);` to
`window.setInterval(app.updateDebugInfo_, 500);` to avoid log spam.
I'm seeing `video.buffered` is approximately the minimum of audio buffered and video buffered. Sometimes audio buffered or video buffered is ahead of the other, likely due to fetch latency and insertion order.

If you're seeing something different with this logging, please feel free to reopen.
