### ISSUE TITLE
Does shaka support play ad in chromecast receiver?

### ISSUE THREAD

**Issue by huangh0604** [google/shaka-player#1283]
Hi All:

I found that chromecast receiver uses same video tag to play ad.
So if it is playing dash(usging cast.player.api.Player) content, then we begin to request ad.
The IMA SDK will close media source and begin to play ad, after finishing playing ad. It can't recover to play content, because the media source have been closed.

So, I want to ask does anyone caught this issue? And Does shaka support to play ad in chromecast receiver?

**Comment by joeyparrish** [comment]
Ideally, IMA could use a second video tag so that Shaka Player could be paused and maintain state while the ad plays in a second tag which overlays the first.

Some devices, though, can only support one video tag.  If the Chromecast can only support one video tag, you will have to tear down Shaka Player during the ad.  In this case, I suggest storing `video.currentTime` before IMA takes over.  Then, when IMA is done, you can call `player.load(manifestUri, startTime)`, where `startTime` is the stored value of `video.currentTime`.  This way, Shaka Player will resume where it left off.

Does this help?

**Comment by huangh0604** [comment]
In you opinion, it seems can have it a try.
But when IMA takes over the video tag, it will flush the buffer that we cached the content.

Although, we can use you method to continue to play at currentTime, we have to reload manifest and cache buffer to video tag.
And it's redundant and waste the bandwidth.

Cry~, Cry~, Cry~

So, it seems I have to use google cast sdk which supported ad.
But in this way, I can use many special or cutomize features of shaka.player.

**Comment by joeyparrish** [comment]
That's true, it will flush the buffers when IMA takes over.  There's nothing we can do about that.  If the hardware only supports one video element at a time, we can't keep the content buffered in MediaSource during the ad break.

I'm sorry to give you bad news.  Please let us know if we can do anything else for you.
