### ISSUE TITLE
not to download audio if muted

### ISSUE THREAD

**Issue by kuznetcoff777** [google/shaka-player#1300]
## NOTE: For bugs, if you delete this template, we will send it again and ask you to fill it out.

**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**:

**Can you reproduce the issue with our latest release version?**:

**Can you reproduce the issue with the latest code from `master`?**:

**Are you using the demo app or your own custom app?**:

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:

**What are the manifest and license server URIs?**:
*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

Just like in https://github.com/google/shaka-player/issues/1058
But to make the same with audio. The case is that we want to implement on web site little player that is playing stream and muted initially (bitrate about 100kbit), so to minimize network loading (audio is 96kbit) it will be perfect solution.

**Comment by TheModMaker** [comment]
We have no intention of implementing this.  This would require an extremely large amount of work to implement.  We can't just ignore audio, if we don't append data to the SourceBuffer, the browser will wait for the audio.  We **might** be able to remove the buffer, but that probably won't work well on all platforms.  Plus, it is really likely that adding a new SourceBuffer will not be supported once playback has started.  So we will likely have to reset the entire media stack (including re-appending video segments) once you unmute audio.  Plus, there will be a huge delay between unmuting the audio and hearing the audio since we will need to download the segments.

If you don't want to play audio, you can create a video-only manifest.  We might consider a video-only or audio-only mode; but that wouldn't be able to change once we start playback.

**Comment by kuznetcoff777** [comment]
@TheModMaker 
That what i just thought about while reading your firsrt sentences - about another mainfest with video only. 
Rhanks for idea!
