### ISSUE TITLE
How is license renewal handled?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1320]
We are dealing with a license expiry issue across multiple device platforms (not just web), and I'd like to be sure I understand how expiry / renewal is handled in Shaka / EME.

Is the license renewal flow initiated by EME? As far as I can tell from the spec and DrmEngine, the correct flow is as follows:
- A MediaKeySession will publish `message` with a type value `license-renewal`
- DrmEngine will send a license request

If this is the case then I take it that the initial license must contain some parameters telling the CDM to do this.

So license renewal is not meant to be handled via the expiry mechanism? Meaning:
- A MediaKeySession will publish `keystatuseschange`
- The player checks for expired keys
- If all expired, the player sends a license request

I take it that Shaka does not, and will not, support that flow. Is that correct? That makes sense now that I think about it, I just want to be sure I've understood correctly.

Thanks for your insight.

**Comment by joeyparrish** [comment]
Correct.  Renewal is triggered by a CDM-initiated `message` event.  We do not request a new license when the old one expires.

We make certain assumptions based on Widevine recommendations and the typical structures we see from applications and content owners.  Expiration and renewal are policies that content owners control.  A few of typical setups are:
  - Typical VOD: License expires after X minutes, which can be extended through renewal.  Renewal is attempted Y minutes (Y < X), so renewal would have to fail (X/Y)-1 times in a row before we risk an expiring license.
  - Typical offline: License expires X minutes after playback begins, with no renewal.  The user is expected to complete watching the content by then.
  - Typical live: License rotates every X minutes, which causes us to create a new session every X minutes.  Old sessions expire after X * Y minutes (some multiple), at which point they get closed.  There will be up to Y overlapping sessions at any time.  Renewal is not used.

In general, renewal is a tool for concurrency detection.  If a content owner wants to keep track of how many clients are watching movies under the same user credentials, they can observe renewal attempts within a certain window and set a threshold, above which they suspect account sharing or related forms of abuse of their service.  By setting a short license expiration (say, 5 minutes) and a shorter renewal period (say, 1 minute), an abusive user cannot watch for more than 5 minutes without getting an updated license.  A well-behaved user would have a quick exchange with the server every minute, and could tolerate up to 4 renewal failures without interrupting playback.

If there is another use-case that we're missing in which content should be automatically relicensed after expiration, rather than using license renewals during playback, please let us know so we can discuss the requirements.

**Comment by chrisfillmore** [comment]
Thanks for the breakdown! I did not realize that renewal and rotation were different concepts. One thing I'm still unclear on: How is rotation handled? What signals Shaka that rotation must happen? If DrmEngine isn't listening for `encrypted` events (due to pssh in the manifest), how does it know to create a new session? (updated kid's from the manifest maybe...?)

Thanks again.

**Comment by joeyparrish** [comment]
Rotation is different from renewal.  In renewal, a 'message' event triggers the renewal exchange, which results in the original license/session being extended.

In rotation, an 'encrypted' event triggers the creation of a new session, which is typically deliberately short-lived.

This means that if you have a PSSH in the manifest, key rotation will break, because we follow the DASH guideline that the PSSH in the manifest supercededs any that might appear in the content itself.  So if there is a PSSH in the manifest, we don't listen to the 'encrypted' event at all.  See #1107 for more.

**Comment by chrisfillmore** [comment]
Thanks again for the information. I think our organization is still looking for an appropriate solution, or set of solutions, that can work across device platforms, since different players and DRM's behave differently.

**Comment by joeyparrish** [comment]
Understood.  Let us know if there are ways we can be more flexible to accomodate different paradigms.
