### ISSUE TITLE
Unable to guess manifest type by file extension or by MIME type. webm video/webm, error code is 4000

### ISSUE THREAD

**Issue by techterbium** [google/shaka-player#1328]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**:2.3.2

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Did not try

**Are you using the demo app or your own custom app?**: Own

**If custom app, can you reproduce the issue using our demo app?**: Did not try

**What browser and OS are you using?**: Chrome (Electron App), MacOSx

**What are the manifest and license server URIs?**:NA
*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

**What did you do?**
I am trying to load a mp4 or webm file in google shaka player. 
URIs tried
URI1: http://techslides.com/demos/sample-videos/small.webm
URI2: http://techslides.com/demos/sample-videos/small.mp4
**What did you expect to happen?**
Play the video
**What actually happened?**
I am seeing below error.
Unable to guess manifest type by file extension or by MIME type. webm video/webm

![image](https://user-images.githubusercontent.com/4904359/36867719-f94c73c4-1dbb-11e8-855f-29bee3d3bd6a.png)

**Comment by joeyparrish** [comment]
Currently, we require a manifest such as DASH or HLS.  We do not play back individual files, such as these webm files, because these are not supported through MediaSource.  We currently only do playback through the MediaSource API.

We have an open feature request to add support for single files (https://github.com/google/shaka-player/issues/816) but we are still working toward that.  There are many foundational things that have to change for this, and it will take some time to get there.  You can follow #816 if you are interested to track progress.

Thanks!

**Comment by techterbium** [comment]
Thanks for the reply @joeyparrish.
