### ISSUE TITLE
Question: Handling casting properly with Widevine - Dash.

### ISSUE THREAD

**Issue by sergioavazquez** [google/shaka-player#1348]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
2.3.3
**Can you reproduce the issue with our latest release version?**:
It's not an issue.
**Can you reproduce the issue with the latest code from `master`?**:
It's not an issue.
**Are you using the demo app or your own custom app?**:
custom app
**If custom app, can you reproduce the issue using our demo app?**:
not an issue.
**What browser and OS are you using?**:
Chrome.
**What are the manifest and license server URIs?**:
*(NOTE: you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
*(NOTE: a copy of the manifest text or an attached manifest will **not** be enough to reproduce your issue, and we **will** ask you to send a URI instead)*

My goal is to seamlessly cast a live - DASH -Widevine stream and later on, stop it and resume playback on the transmitter device. Repeat this as many times as needed. 

I refresh the token for windevine's proxy periodically and store it. Whenever I update the player's stream I update the proxy's token and everything works great.

My question is, what's the best way to handle proxy's token expiring while streaming?

Since the stream doesn't change when starting - stopping a cast I don't get to update my proxy's token and sometimes leads to failure when switching.

 This makes sense, the player sends the license proxy it was using to stream the content but it can't start a new one with it because it expired. The problem is that when it does, I can't handle the error since it doesn't trigger any event, at least not a player error event.
`player_.addEventListener('error', this_.onErrorEvent);`
or a `caststatuschange` event:
`castProxy_.addEventListener('caststatuschanged', (event)=>{this_.onCastChangedEvent(event)});`

I'm currently forcing a content reload after cast starts - stops so I get a chance to update the token but I get a `LOAD_INTERRUPTED` error. If I don't do this, it looks like the player is loading indefinitely. 

Is there a better way to handle this? 

Thanks in advance.

**Comment by TheModMaker** [comment]
I'm not sure what you mean by `proxy token`.  Do you mean a cookie/query parameter/etc that you set in a request filter?  Or is it a query parameter on the manifest URL?  Or is it a parameter on the license server URL?

In general, custom license handling (e.g. using a request/response filter) requires a custom receiver app.  The default demo receiver doesn't allow you to set a filter on the Chromecast since we can't send functions over the network.  If you have custom license handling, you will probably need a custom receiver app that will register the filters on the Chromecast side.  Then you could just use your own methods of sending a message to the Chromecast containing the token (or update the token on the Chromecast itself).

Also note that `LOAD_INTERRUPTED` is not really an error.  It is returned from the first call to `load()` to indicate that it was interrupted; the second call to `load()` should succeed and playback should work.

**Comment by sergioavazquez** [comment]
I'm referring to this part of the asset: 
```
licenseServers: {
      'com.widevine.alpha': https://yourServer.com/proxy?token=123456789&expires=1520531199,
    }
```

Once I get a `LOAD_INTERRUPTED` error, updating streams don't `autoplay` anymore. 
Even if I keep updating it. This means that after loading an asset `video_.paused` is `true` which according to Shaka's documentation is how we should evaluate whether a device has `autoplay` capabilities or not. 

This is the error I get when the token expires, Is there a way to handle it?
```
POST https://your.server.com/proxy?token=oRTDazSjdAkvvj8fpC31Vb7QmFS7IhFh54E9U&expires=1520530864 401 (UNAUTHORIZED)
```

Hope it makes more sense know!

**Comment by TheModMaker** [comment]
So what you do is:

1. Start playback locally.
1. Token expires, local playback continues.
1. Start casting.
1. Playback fails due to expired token.

Is this correct?  I think the problem is that when we cast, we start a new playback session.  So the license request on the Chromecast fails since the token is expired.  In this case, you just need to update the license server in the Player configuration:

```js
player.configure({
  drm: {
    servers: {
      'com.widevine.alpha': 'https://your.server.com/proxy?token=newToken',
    },
  },
});
```

This will make us use that license server from that point forward.  If you used the `CastProxy` version of the player, this will work on the sender and affect the Chromecast.  If you call this before casting, we will use that configuration when we start playing on the Chromecast.

> This means that after loading an asset `video_.paused` is true which according to Shaka's documentation is how we should evaluate whether a device has `autoplay` capabilities or not.

I don't know where you got this, but this is wrong.  `video.paused` can be false for a number of reasons, the main one is we don't have content yet.  The video will remain paused until there is content downloaded, even if autoplay is set.

**Comment by sergioavazquez** [comment]
For the first part, yes. That's exactly my case and I think that will solve it!!
For the second part I might've not explained myself properly and it turns out I didn't get that from the documentation but from Shaka's demo `master/demo/common/control.js` 
I meant if `autoplay` is true and `video_.paused` is true after `loadeddata` event is fired it means device might not have `autoplay` capabilities. And it's been working for me!

Here's the source,
```
/**
 * Used by the application to notify the controls that a load operation is
 * complete.  This allows the controls to recalculate play/paused state, which
 * is important for platforms like Android where autoplay is disabled.
 */
ShakaControls.prototype.loadComplete = function() {
  // If we are on Android or if autoplay is false, video.paused should be true.
  // Otherwise, video.paused is false and the content is autoplaying.
  this.onPlayStateChange_();
};
```
Does that make sense now? Thanks and sorry for the inconvenience! I'll let you know if token update works!

**Comment by TheModMaker** [comment]
> I made it work by updating when the user presses the cast button. The only downside I found here is that if chromecast's session is canceled from Chrome's button or for any other reason, content playback fails to resume on device. (Since the cast btn on my app has not been pressed.)

If you cancel casting, there is nothing on the Chromecast.  It should go back to the standby window.  If you try to cast again, it is an entirely new session and you'll need to ensure the Player is setup with the correct configurations to play the content.

`CAST_CANCELED_BY_USER` means that we lost connection with the Chromecast; so if you change the configuration, it will only affect the local instance, not the Chromecast.

> Maybe the right approach is to update the license every time a new token is fetched instead of doing it when starting - stopping cast.

That would be the correct behavior.  If your license server URL changes, you should update the player.  Currently you don't need to update the URL since we only make one license request at the beginning; once we have the license, we don't need to make any other requests to the license server.  But you should keep the license server URL updated in case we need to make requests in the future.  For example, if your proxy changes to use renewals, we'll need to periodically renew the license, which will fail if the token is expired.

**Comment by sergioavazquez** [comment]
So bottom line is, updating just when needed is not the best approach and it's clearly not designed to work this way. I'm going to keep license updated and forget about this.
Thanks!!
