### ISSUE TITLE
Status of UTCTiming spec?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1354]
I was asked the following question regarding UTCTiming:

_Do you know why the players e.g. Shaka implement this when the spec is not finalized?_

I'm not familiar with the history of UTCTiming in the spec, or what it's current status is. Some people are concerned that UTCTiming is in draft form and not finalized, and thus we should not implement it.

I understand Shaka team can't advise on my organization's specific situation, but I'm hoping to offer a coherent answer to the question above.

**Comment by TheModMaker** [comment]
I didn't know this, but apparently UTCTiming isn't in the DASH spec itself.  So they may be correct about it being in the draft spec.  But, it has been in the IOP guidelines (which have several finalized versions) for a while now.  Also, we focus on implementing the IOP guidelines, not really the DASH spec itself.  UTCTiming is in the finalized versions of the IOP.  I would also think that it is a stable feature since it has been pushed by DASH IF.

As for why it should implemented, because there is no other way to synchronize the client and server.  The DASH spec just says that it must be synchronized already, but doesn't specify how.  The IOP adds the UTCTiming element to allow clients and servers to synchronize the clocks.  This is really important for live streams since segment availability is based on the current wall-clock time.

**Comment by joeyparrish** [comment]
Also, we support syncing with the `Date` header of an arbitrary URL via configuration, so you don't really need to use UTCTiming in the manifest if that particular method works.  (That is also one of several UTCTiming schemes currently specified.)  Any uncacheable endpoint you control would work, so long as the server returns a `Date` header corresponding to "now".

**Comment by chrisfillmore** [comment]
Thanks for the information!

**Comment by sandersaares** [comment]
UTCTiming is specified in ISO/IEC 23009-1:2014/Amd 1:2015.
