### ISSUE TITLE
[Question] How to achieve low (~2s) latency with shaka+ffmpeg?

### ISSUE THREAD

**Issue by andreymal** [google/shaka-player#1355]
Example:

```
ffmpeg -f x11grab -r 30 -video_size 640x360 -i :2.0 \
  -pix_fmt yuv420p -c:v libx264 -preset ultrafast -profile:v baseline -g 15 -b:v 600k \
  -an -map 0:0 \
  -f dash -min_seg_duration 1000 -remove_at_exit 1 -window_size 100 \
  /home/andreymal/org/dash_delay_test/dash/manifest.mpd
```

With dash.js this stream has ~2s delay. But with shaka it has ~5s delay!
Screenshot: https://i.imgur.com/6FNpvLQ.png

I tried to set rebufferingGoal/bufferingGoal/bufferBehind to zero or other small values (0.1 .. 2.0), but this doesn't help.

Is it possible to get ~2s delay with shaka, or I have to use dash.js?

https://github.com/google/shaka-player/issues/1287 also doesn't help me (`-use_template 1` increases the delay, minBufferTime is not configurable in ffmpeg, segment length is already 0.5s etc.)

Currently you can see my stream here:

https://home.andreymal.org/dash_delay_test/dashjs.html
https://home.andreymal.org/dash_delay_test/shaka.html
https://home.andreymal.org/files/clock.html (this page is source for this stream)
https://home.andreymal.org/dash_delay_test/dash/manifest.mpd (has `Access-Control-Allow-Origin: *` HTTP header)

**Comment by ismena** [comment]
@TheModMaker I feel like this one's for you :)

**Comment by TheModMaker** [comment]
https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=https://home.andreymal.org/dash_delay_test/dash/manifest.mpd;lang=en-US;build=uncompiled

The reason you are seeing a delay is because we are buffering.  If I play the stream on the nightly page, I see that the playhead is always at about `-0:02`, or 2 seconds behind the live edge.  So I would think we have a latency of about ~2s, but we are stuck buffering a lot.  Also note that I can push the playhead further forward by typing `video.currentTime += 0.2` a few times.  So I can get smooth playback at about ~2.5s delta.

The reason we are buffering is because we don't know about the future segments.  Like I said in #1287, using `SegmentList` means we need to wait for a manifest update before we can learn about new segments.  We also have a 3 second minimum between manifest updates.  Using `SegmentTemplate` with `duration` will help a lot.  Without an example of `SegmentTemplate` it will be hard to diagnose why the other manifest would have a longer delay.

**Comment by andreymal** [comment]
`-use_template 1` creates `SegmentTemplate` without `duration`, perhaps this is the reason why this did not help me.

But after your comment, I noticed that `use_template 1 -use_timeline 0` creates `SegmentTemplate` with `duration`, and now shaka player has ~2.5s delay as expected, thanks for the help! (Looks like `-use_timeline` argument was implicitly enabled by default, ffmpeg documentation has nothing about defaluts.)

P.S. But your link is not working now, it prints `Shaka Error NETWORK.HTTP_ERROR (chunk-stream0-00001.m4s, TypeError: NetworkError when attempting to fetch resource.,1)` :)

**Comment by andreymal** [comment]
Another small question about this stream (uses `-use_template 1 -use_timeline 0` now): shaka downloads chunk [N] while chunk [N+3] is also available:

![](https://i.imgur.com/8eJGEP2.gif)

Is it possible to reduce the delay here?

**Comment by TheModMaker** [comment]
Your segments are 0.5 seconds, so there will likely be 1 or 2 off because of network delays and the time it takes for us to react to the new segment.  Is the encoder and the browser running on the same machine?  This could be caused by a very slight clock-sync difference.  Maybe you could look into FFmpeg's documentation or code and change the `availabilityStartTime` to a bit forward.   This controls where we think the live edge is.  By moving it forward from what it is set to now, you might be able to get the player to request those segments.  But I don't think there is any other settings you could change to get better.

**Comment by andreymal** [comment]
I tried to change `availabilityStartTime.`, but it's dangerous: shaka can try to download a nonexistent chunk :)

It seems that 2s delay is the minimum limit in practice. Thanks for the answer!
