### ISSUE TITLE
Stream freezes when to seeking to the end in Safari

### ISSUE THREAD

**Issue by hghazzi** [google/shaka-player#1363]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes, found a similar issue that was closed as "bad content"

https://github.com/google/shaka-player/issues/1068

**What version of Shaka Player are you using?**:  v2.3.3

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Haven't tried

**Are you using the demo app or your own custom app?**: Both

**If custom app, can you reproduce the issue using our demo app?**: Yes

**What browser and OS are you using?**: Safari 11.0.3 on macOS High Sierra 10.13.3

**What are the manifest and license server URIs?**:

https://shaka-player-demo.appspot.com/demo/#asset=//storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;lang=en-US;build=uncompiled

**What did you do?**

1. Begin playing the stream
2. Seek to the very end

**What did you expect to happen?**

The player goes to the complete state (the last frame is displayed and the play button appeared)

<img width="694" alt="screenshot 2018-03-16 17 21 34" src="https://user-images.githubusercontent.com/584053/37545418-26067462-293f-11e8-8eea-19ced320c734.png">

**What actually happened?**

Doesn't happen consistently, but the player will be blank at 1:00 but is still in the playing state (play button doesn't appear). Isn't reproducible in Chrome.

<img width="686" alt="screenshot 2018-03-16 17 25 46" src="https://user-images.githubusercontent.com/584053/37545419-261a7f5c-293f-11e8-8e5d-cb93d127727c.png">

**Comment by theodab** [comment]
Reproduced. Notably, when the player gets into this state, the video's seeking attribute is true. So this looks like it might be some issue where seeking begins, but never completes.

**Comment by theodab** [comment]
This issue has been around since 2.0.9, at least. I reproduced it on a number of archived versions of the player. So it's not the result of some new change.

I've reproduced it on the "Angel One" and "Sintel" assets, and it's quite consistent for all of those, but not on any of the other Shaka assets. So there's something about those assets and not, say, "Tears of Steel" or "Dig the Uke".

I was also able to get the United Streaming version of "Tears of Steel" into a non-paused non-playing state by seeking to 734.24s, on Safari. That seems consistent too, but in that case the video wasn't "seeking" so it may or may not be the same issue.

**Comment by TheModMaker** [comment]
This may be related to #1014.

**Comment by theodab** [comment]
I was able to reproduce this with a [test page](https://storage.googleapis.com/shaka-demo-assets/_bugs/1363/index.html) that does not use Shaka Player at all, so this looks like a Safari bug rather than a Shaka Player bug.
I have [filed a bug ](https://bugs.webkit.org/show_bug.cgi?id=184094)on the webkit bugzilla for this issue.

**Comment by joeyparrish** [comment]
Closing this stale external (non-Shaka) issue. If you disagree, please reply with @shaka-bot reopen, and it will be automatically reopened.
