### ISSUE TITLE
What happens if a period ends in the middle of a segment?

### ISSUE THREAD

**Issue by sandersaares** [google/shaka-player#1375]
Say that I have live streams where a new period (e.g. ad break) can happen at any time, including in the middle of the last segment from the previous period.

In practice, I observe with Shaka that the last segment appears to be played to the end before the new period starts.

Do you have suggestions on how to best handle this type of situation, from a player developer perspective, for the minimally disruptive switchover? What do you see the player responsibilities as in this scenario and what do you expect the packager to care for?

**Comment by TheModMaker** [comment]
I don't think we should play the last segment to the end, we should truncate the last segment based on the Period duration (or the start of the next Period).  Could you post an example manifest where this happens?

What we (should) do is truncate the last segment at the Period boundary and then append the segments from the next Period.  We use MSE's [appendWindowEnd](https://w3c.github.io/media-source/#dom-sourcebuffer-appendwindowend) to tell the browser to drop any frames that appear after the Period.  It should provide a gap-free transition.  The end of a Period is usually easy to handle; what can be more complicated is how to handle the next Period.  If you return from the ad and want to play that partial segment as part of a new Period, there will be problems.

If you use `presentationTimeOffset` to make the first segment appear before the Period start, it will cause playback problems in the browser.  When we append segments we use [appendWindowStart](https://w3c.github.io/media-source/#dom-sourcebuffer-appendwindowstart) to cut off anything the appears before the Period start.  This ensures that any new content doesn't override the existing content.  However, this causes a problem since when removing content, the browser will remove up to the next keyframe.  So if the first keyframe is right before the Period start, we may "lose" the whole segment since the browser will remove to the next keyframe.

So it is important to have the first segment start after the Period start.  But ending with a partial segment should be fine.

**Comment by sandersaares** [comment]
Thank you for the answer! I will attempt to find some content to reproduce the behavior I mentioned. I wonder if I perhaps misjudged the behavior if you expect it to cut accurately.

**Comment by TheModMaker** [comment]
> > So it is important to have the first segment start after the Period start
>
> I assume I can read this as "on or after"?

Yes.

Were you able to find any content that reproduces the problem?  Do you have any other questions?

**Comment by sandersaares** [comment]
I have not had time to dig into this, I fear. Let's close it for now - I will reopen if I have a specific repro now that I know this is actually meant to work.
