### ISSUE TITLE
Corruption on seek

### ISSUE THREAD

**Issue by byronclark** [google/shaka-player#142]
When playing an on demand video from a Wowza server, there is video corruption when seeking to a location between keyframes. The corruption disappears as soon as the next keyframe is hit. Testing was performed using http://shaka-player-demo.appspot.com/

Here's the test stream we're using: http://184.72.239.149:1935/vod/mp4:sample.mp4/manifest.mpd

Example recording of the corruption seen: https://www.dropbox.com/s/keficu1rkvphpub/shaka-corrupt-on-seek.mov?dl=0

The same behavior is also seen in the dash.js reference player on Mac: Dash-Industry-Forum/dash.js#678

**Comment by tdrews** [comment]
Is this only happening with Chrome 44 on Mac?

**Comment by byronclark** [comment]
I see the corruption in both Chrome 44 and Safari 8.0.7 on Mac. I do not see *any* corruption on seek in Chrome 44 on Windows.

**Comment by tdrews** [comment]
This issue is unlikely to be a player issue: the player provides the browser with media segments; it's up to the browser to correctly decode and render them. As this issue occurs across browsers, I'd guess that it's a decoder issue.

Can you file a public bug on [the Chromium issue tracker](https://code.google.com/p/chromium/issues/list)?

**Comment by byronclark** [comment]
Chromium bug filed: https://code.google.com/p/chromium/issues/detail?id=516039

**Comment by tdrews** [comment]
Thanks. I'll leave this issue open until the cause has been identified.

**Comment by tdrews** [comment]
Looks like this is a browser issue.
