### ISSUE TITLE
Shaka player recovery from failures

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#1427]
When internet disconnect and connect when the video is played, shaka player will play the video that is buffered. But after the internet is connected it doesnot automitically resume the video. If will continue to show the loading progress icon. 

Steps to reproduce the issue:
1. Play the video
2. Ofter some time disconnect the internet by switching off wifi (or make offline in the chrome network debug tools)
3. Play will continue till the buffer is completed
4. After playing the buffered video, connect the wifi (or make online in chrome network debug tools)
5. Now shaka player will not automitically resume the video. It will continue showing the loading icon for ever.

Players like youtube player, videojs player will automitically resume the video in above scenario.
When the use uses mobile internet it is generally expected that they will loose internet connection. So the video should resume automitically when reconnected for best user experience.

We are using little old version of shaka player. I have tried this in the shaka player demo also. Everywhere the issue exists.

Please help in fixing this issue

**Comment by TheModMaker** [comment]
We have logic to retry after network failures.  If we detect some problem, we will retry up to a configurable amount.  Once we have hit that limit, we will raise an event on the Player object and stop.  If it is a live stream, we will, by default, continue retrying forever.  We assume that network errors in live streams are transient and will recover eventually.  But VOD content we assume doesn't change, so we won't retry forever.

You could fix this in your app by adding the following:

```js
window.addEventListener('online', function() {
  player.retryStreaming();
});
```

That event is raised once the browser gets back online, then that method will cause us to restart streaming again.  But since this is a simple thing to do, we should do it for you.

**Comment by sridhard** [comment]
@TheModMaker any updates on this

**Comment by joeyparrish** [comment]
@sridhard, this is marked as an enhancement, and targeted for v2.5.  When a change has been made related to this issue, github will show a link to the change and close the issue.

**Comment by joeyparrish** [comment]
Enhancement cherry-picked to v2.4.5.  I said v2.5.0 before, but I wasn't reading my own notes when I was cherry-picking things.  Whoops.  Enjoy!
