### ISSUE TITLE
Generate audio to fill gaps

### ISSUE THREAD

**Issue by beaufortfrancois** [google/shaka-player#1436]
Some other media players (such as Theo Player) know how to handle when a (audio+video) source buffer has only video data for few seconds.

It would be great if Shaka provide this "feature".

MSE doesn't allow empty audio chunks for an audio/video source buffer BUT it is not rare that audio is missing for some reason.

Could we somehow generate some fake blank audio chunk?

@joeyparrish

**Comment by beaufortfrancois** [comment]
FYI @ygoto3

**Comment by joeyparrish** [comment]
If the source content is muxed (audio+video in the same segment), I believe Shaka Player would create a single SourceBuffer for audio+video content.  If the source content is demuxed (audio and video in separate segments), then we would create two SourceBuffers: one for video, one for audio.

So it is the content creator who decides how many SourceBuffers there are by deciding whether or not to separate audio & video segments.  Industry best practice seems to be to separate audio & video, and we recommend this, as well.

Browsers tend to stall when there is a gap.  A gap is defined by the intersection of the buffered ranges of all SourceBuffers. If there are two SourceBuffers, and either one is missing some content at a given point, that's a gap.  If there is only one SourceBuffer, any missing content in it is obviously a gap.

Browsers will play through "small" gaps, but each browser defines "small" differently.  Shaka Player has a feature called "gap jumping", which you can configure to application preferences.  In short, if we find a gap in the content, we will seek to jump over it.  You can tell us whether to jump over small gaps or all gaps, and you can define what "small" means.  See [our docs on StreamingConfiguration](https://v2-3-7-dot-shaka-player-demo.appspot.com/docs/api/shakaExtern.html#.StreamingConfiguration), specifically the "smallGapLimit" and "jumpLargeGaps" fields.  Here's an example of setting them:

```js
player.configure({
  streaming: {
    smallGapLimit: 2.0,  // seconds
    jumpLargeGaps: true,  // if true, small gap limit doesn't matter
  },
});
```

If, hypothetically, we were to generate a blank audio chunk, it would have to be encoded with the same codec as the playing content and contained in the same container.  So that would mean, for example, generating valid AAC data and wrapping it in a valid fMP4 segment with the correct timestamps and other parameters to fit seamlessly into MSE's SourceBuffer.  This is **not** something reasonable for Shaka Player to do, in my opinion.  We would have to support many combinations of codecs & containers, and even doing it for AAC+fMP4 is unreasonable for a JavaScript application.

Hopefully the explanation of the SourceBuffer situation will help with content creation, and hopefully the gap-jumping feature will help deal with the gaps that inevitably appear in some live content.

Thanks!
