### ISSUE TITLE
Get custom header in registerResponseFilter

### ISSUE THREAD

**Issue by Mathieu-R** [google/shaka-player#1439]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.3.7

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**: custom app

**If custom app, can you reproduce the issue using our demo app?**: Yes

**What browser and OS are you using?**: Chrome 66 and OSX 10.13.3

**What are the manifest and license server URIs?**:

**What did you do?**
I'm tracking response length through `registerResponseFilter()` in order to calculate data-volume consumed.    
I would like to bail if the response comes from the service-worker cache.

To do that that I send back a custom header (`x-from-cache)` from my service-worker.    
```js
slicedResponse.headers.set('x-from-cache', 'true');
``` 

And then in `registerResponseFilter function` I try to read it.
```js 
networkEngine.registerResponseFilter((type, response) => {
  // user does not want to limit-data => do not track.
  this.settings.get('limit-data').then(ok => {
    if (!ok) return;
  });

  // response from cache
  const fromSwCache = response.headers.find(h => h === 'x-from-cache');
  if (fromSwCache) {
    return;
  }

  // we're only interested in segments requests
  if (type == shaka.net.NetworkingEngine.RequestType.SEGMENT) {
    // bytes downloaded
    const value = response.data.byteLength;
     // update idb cache to save the user data volume consumed
     updateDataVolumeDebounced({userId: this.props.userId, value});
  }
}); 
```

**What did you expect to happen?**
`x-from-cache` to be in the header of response

**What actually happened?**
`x-from-cache` is not in the header of response.

**Comment by TheModMaker** [comment]
First, `response.headers` is a "simple" JavaScript object, so it doesn't have a `find` method.  You could do something like:

```js
const cached = Object.keys(response.headers).indexOf('x-from-cache') >= 0;
```

Second, can you provide the source code for your service worker?  My guess is that the header isn't getting set or your are returning the old response (without the header) from the service worker.  We should support this case, you can read more in the [service worker tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-service-worker.html).

Third, your first part about settings is presumably async since it uses `then`, so the code below it will run before the callback.  Meaning it will not stop the method if `ok` is falsy.  We do support async response filters, so you could have the function be `async` and use `await`.

**Comment by Mathieu-R** [comment]
First, thanks for your answer.

Here's the code that create a ranged-response in my `service-worker`. 
You can find the part where I set the header in the bottom. 

```js
const createRangedResponse = (request, response, rangeHeader) => {
  return response.arrayBuffer().then(buffer => {
    // aaa-bbb, aaa, bbb
    let [full, start, end] = /(\d*)-(\d*)/.exec(rangeHeader);

    if (start === '') {
      start = buffer.byteLength - Number(end);
      end = buffer.byteLength;
    } else if (end === '') {
      start = Number(start);
      end = buffer.byteLength;
    } else {
      start = Number(start);
      end = Number(end) + 1;
    }

    if (start < 0 || end > buffer.byteLength) {
      return new Response('Range not satisfiable', {status: 416});
    }

    const slicedBuffer = buffer.slice(start, end);
    const slicedResponse = new Response(slicedBuffer, {
      status: 206,
      headers: response.headers
    });

    //console.log(`ranged response from service-worker from ${start} to ${end}`);

    slicedResponse.headers.set('x-from-cache', 'true');
    slicedResponse.headers.set('Content-Length', slicedBuffer.byteLength);
    slicedResponse.headers.set('Content-Range', `bytes ${start}-${end - 1}/${buffer.byteLength}`);
    return slicedResponse;
  });
}
```

**Comment by TheModMaker** [comment]
I cannot reproduce any problem.  By editing our service worker I am able to add the header fine and it appears in the header object.  Are you sure the above code is being executed?  Are you sure the service worker is running and the correct version?  (I frequently have "Bypass for network" checked for testing)  You can check the Application tab of Chrome DevTools to see what the service worker is doing.

Could you post a link to a hosted page that you can't get working?  You can send it privately to shaka-player-issues@google.com if you prefer.

**Comment by Mathieu-R** [comment]
I tried again in production mode with all your tips.
I still don't get `X-From-Cache` header however if I check the response in the network panel of chrome. I have this header.

![image](https://user-images.githubusercontent.com/16360664/40068280-878959d6-5868-11e8-8044-e2daef464a98.png)

For the hosted page: https://www.streamwave.be/

**Comment by TheModMaker** [comment]
First, I noticed your service worker had an error in the `onfetch` callback where `url.hostname.contains` causes an exception and the callback isn't invoked.  But after commenting out that block, I was able to see the problem.

The problem is that is a cross-origin request, so [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) rules apply.  Even though you are creating the response artificially in the service worker, you still need to follow CORS rules.  In this case, the `X-From-Cache` header isn't in the CORS allowed headers, so JavaScript can't access the header.  If I look at the XHR object and call `xhr.getResponseHeader('x-from-cache')`, I get an error saying `Refusing to get unsafe header "x-from-cache"`.

The easiest fix would be to add a `Access-Control-Allow-Headers: X-From-Cache` header to your CDN so the header can be added in the service worker.  But I'm not sure how to fix this if you don't control the headers on the CDN.

**Comment by Mathieu-R** [comment]
How did you test if the header `x-from-cache` is gettable ?
I added `Access-Control-Allow-Headers: X-From-Cache` on my CDN, but still don't get it.

**Comment by TheModMaker** [comment]
I actually didn't test it... my bad.

The correct header is `Access-Control-Expose-Headers: X-From-Cache`.  I tested it by making a request to my local webserver using XHR and calling `xhr.getResponseHeader` on the result.  I didn't test with Shaka Player, but I am confident that this will work.

**Comment by Mathieu-R** [comment]
Yes, the problem is on the nginx side. 
Closing the issue.
