### ISSUE TITLE
subtitle tracks are diabled

### ISSUE THREAD

**Issue by samanmohamadi** [google/shaka-player#1443]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.3.7

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: No

**Are you using the demo app or your own custom app?**: My own

**If custom app, can you reproduce the issue using our demo app?**: Yes

**What browser and OS are you using?**: Chrommium v66

**What did you do?**
I use shaka-player with plyr.
plyr detect and show caption by listening to 'cuechange' event, but shaka-player set caption mode to 'disabled' which prevent 'cuechange' event to be fired.
setting mode to 'hidden' fix the this issue.
https://github.com/google/shaka-player/blob/8065bd54a8389746b48bdade4efdc4e2a8a11e26/lib/text/simple_text_displayer.js#L58

**Comment by theodab** [comment]
As far as I can tell from poking around on github, plyr adds event listeners for `cuechange` when the player is created, and then `simple_text_displayer` disables all current tracks and makes a new one upon loading a manifest. So plyr was made on the assumption that the text tracks don't change, and `simple_text_displayer` disposes of any previous text tracks because it wants to use special Shaka Player text tracks.

I'm not sure if compatibility with other player frameworks is really a goal for Shaka Player. I can ask around, but I can't promise that we will actually make any changes for this.

However, there are solutions you can implement on your side. Two possibilities I can think of:
1. If you have some text track that plyr is trying to use, you could try setting that text track's label to `shaka.text.SimpleTextDisplayer.TextTrackLabel_` ("Shaka Player TextTrack"). This will cause `simple_text_displayer` to identify it as being a Shaka Player text track, and re-use it instead of disabling it. I can't guarantee this will work, though, as it's kind of hacky.
2. Implement a custom text displayer. We have a plugin interface for text displayers. You could just copy the code of `simple_text_displayer`, make your alterations for plyr compatibility, and give it a new class name. Then before loading an asset, you configure the player to use it:
```js
// Where 'player' is Shaka Player, and 'video' is the video element:
player.configure({
  textDisplayFactory: () => {
    return new MyTextDisplayer(video); // Or whatever you called the new class.
  }
});
```

**Comment by samanmohamadi** [comment]
Thanks, I tried the second way and it's working now.
