### ISSUE TITLE
FairPlay support with com.apple.fps.1_0 key system.

### ISSUE THREAD

**Issue by FeliceGeracitano** [google/shaka-player#1447]
Hi Guys,
Thanks for the great work on the Shaka player.

I'd like to ask if you are interested in a PR that enable support for Fairplay DRM with com.apple.fps.1_0 key system. I got a solution working with my DRM contents and I'd love to use only the Shaka player to handle the different platforms.

Thanks in advance

**Comment by chrisfillmore** [comment]
Hi @FeliceGeracitano, there is a ticket for HLS-FP support via native Safari player: https://github.com/google/shaka-player/issues/997

I also recommend you read the discussion at https://github.com/google/shaka-player/pull/1199. That pull request is for `com.apple.fps.2_0` support, but there is discussion of `com.apple.fps.1_0`. I'm not a member of Shaka team, so this is my own opinion, but I think that Shaka should not wrap the Safari player, because they are logically at the same level of abstraction. It would make more sense to define an interface and have two separate implementations: the existing `shaka.Player` and another `shaka.SafariPlayer` (or something similar).

**Comment by FeliceGeracitano** [comment]
Hi @chrisfillmore 
Thanks for the bugs links.

I see your point now. Configuration object will have no effect since safari will handle the streaming. 
I'l be Happy to help on #997 if is needed.
Related to the separate implementations, could that lead to shaka.SafariPlayer for `com.apple.fps.1_0` and shaka.Player for `com.apple.fps.2_0`?

**Comment by chrisfillmore** [comment]
Speaking strictly hypothetically, yes. Personally I would say the client application would need to decide which player implementation to use at some point.

**Comment by joeyparrish** [comment]
Hi @FeliceGeracitano.  We are planning to wrap Safari's native HLS player to support `com.apple.fps.1_0`.  This will allow applications to use Shaka Player on iOS, but as Chris points out, very little of Shaka's config will have any effect on iOS.  The goal with that is just to make things a little simpler, so that apps don't have to write two different sets of logic for iOS and for everything else.  This is tracked in #997 (native HLS) and #382 (FairPlay).

I would love to support FairPlay on top of MSE on Safari, which would be `com.apple.fps.2_0` and would allow Shaka Player to handle DASH & HLS without using Apple's native HLS implementation.  This doesn't seem to be officially supported by Apple yet, and I was unable to make it work the last time I tried it (about one year ago, June 2017).  There is a long discussion in #382 about whether or not this approach is even feasible, but @chrisfillmore made some progress in PR #1199, which I have not had time to review or test in detail.

Does this answer your question?

**Comment by joeyparrish** [comment]
My pleasure.  Sorry we didn't get you the answers sooner.
