### ISSUE TITLE
DRM Dash Live Stream doesn't work

### ISSUE THREAD

**Issue by desenhista** [google/shaka-player#1453]
**Have you read the FAQ and checked for duplicate issues:** yes

**What version of Shaka Player are you using:** 2.4.0

**Can you reproduce the issue with our latest release version:** yes

**Can you reproduce the issue with the latest code from master:** yes

**Are you using the demo app or your own custom app:** demo app and custom app

**If custom app, can you reproduce the issue using our demo app:** yes

**What browser and OS are you using:** Win 10 Chrome

**What are the manifest and license server URIs:**
_(you can send the URIs to shaka-player-issues@google.com instead, but please use GitHub and the template for the rest)_
sent to shaka-player-issues@google.com

**What did you do?**
Load live stream and press play

**What did you expect to happen?**
Stream started

**What actually happened?**
Infinite loading indicator.
In console I see:
Updating manifest...
dash_parser.js:1251 actual update period 5.864
streaming_engine.js:1387 (audio:11) looking up segment: presentationTime=4195502.9263 currentPeriod.startTime=0
streaming_engine.js:1387 (video:2) looking up segment: presentationTime=4195502.9263 currentPeriod.startTime=0

**Comment by ismena** [comment]
Hi @desenhista, I'm getting a 403 error for your manifest. Are you restricting access by region or something like that?

**Comment by desenhista** [comment]
Hi @ismena 

has restriction by region. sorry for that.
I will remove the restriction and as soon as I do, I'll let you know


thank you so much

**Comment by desenhista** [comment]
Hi @ismena

Can you give me an ip or range of ip to put on the white list of akamai?

Thanks

**Comment by ismena** [comment]
Here are our IP blocks:
IPv6 block: 2620:0:1008::/48
IPv4 block: 104.132.51/24

**Comment by ismena** [comment]
@michellezhuogg @joeyparrish 
Could one of you take this over is this/next week's bug cop?

**Comment by joeyparrish** [comment]
@desenhista, I tried to reproduce the issue today, but I'm getting HTTP 403 errors.

**Comment by desenhista** [comment]
Hi @joeyparrish 
Please, can you try again?

thank you very much

**Comment by joeyparrish** [comment]
I can see the issue now, but I've run out of time to work on it today.  I'll look again tomorrow and dig into why it is failing.

**Comment by joeyparrish** [comment]
Here's my analysis of the content:

Current unix timestamp when I fetched the manifest (`now`): 1528995655
Stream start according to the manifest's `availabilityStartTime` attribute (`ast`): 1527269598
Time in seconds since stream start (`live_edge = now - ast`): 1726057
Most recent video segment start time (`latest_start`): 501643046354
Most recent video segment duration (`latest_duration`): 900900
Most recent video segment end time (`latest_start + latest_duration`): 501643947254
Video timescale (`timescale`): 90000
Most recent video segment end time in seconds (`latest_end_seconds = (latest_start + latest_duration) / timescale`): 5573821.636
Offset between live edge and segment (`latest_end_seconds - live_edge`): 3847764.636

The most recent segment ends 3847764.636 seconds (44.5 days) in the future.  Since the content timeline is inconsistent, this is bad content that we don't currently support.

In the future, after #999 is closed, we will be able to play content like this.  In the mean time, I suggest you file a bug with the encoder vendor to fix this.

**Comment by desenhista** [comment]
Thank you very much @joeyparrish
