### ISSUE TITLE
New features for offline section

### ISSUE THREAD

**Issue by odedhutzler** [google/shaka-player#1454]
Upon closing issue #1248, are you considering pause / resume & renew license features?

We also thought of constantly updating the manifest in the DB, so if the browser / tab is closed accidentally, the user will be able to continue the download from where it ended. Are you considering some kind of anti-failure mechanism?

**Comment by joeyparrish** [comment]
Yes, we have been discussing how to manage this.  We don't have a detailed design, but tentatively, we will make this dependent on background fetch (#879).  On platforms that support it, background fetch will allow us to move offline downloads to the service worker.

Because service workers can outlive the page and are shared among multiple tabs for the same origin, service worker downloads could help resolve some tricky issues with multiple tabs trying to resume the same download.

We haven't worked out the details, and we could be wrong, so this plan might still change.  Thanks!

**Comment by TheModMaker** [comment]
We will track these features in their original bugs, #1301 for pause/resume and #1347 for offline license renewal.
