### ISSUE TITLE
ReferenceError: 'Symbol' is undefined in IE 11

### ISSUE THREAD

**Issue by rounce** [google/shaka-player#1455]
Test on demo: https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;lang=ru-RU;build=compiled
<a href="https://ibb.co/dvQ4Qy"><img src="https://preview.ibb.co/javSdJ/image.png" alt="image" border="0"></a>
This error appeared in commit b27ea82e
There's no issue when build=debug_compiled

Perhaps you need to add a polyfill and describe it in the readme.

**Comment by ismena** [comment]
@joeyparrish Could you take a look if you have a chance? (The mentioned commit is yours and I don't have access to IE today). If not, I'll check this out later this week.

**Comment by joeyparrish** [comment]
Will do.

**Comment by joeyparrish** [comment]
The issue appears in the release build, but not the debug build.

To dig into this, I started by examining the compiled code and looking for `Symbol`.  The debug and release builds both have this, but it looks a little different.

I tried to put a breakpoint in the code, but IE was making that difficult and wouldn't let me see the compiled bundle, possibly because there was a source map.  The code that is breaking, though, was inserted by the compiler and doesn't map back to anything in the uncompiled library sources.

To better debug, I edited the compiled library and used http://jsbeautifier.org/ to format the first several lines of the compiled code, including the code that polyfills `Symbol`.  My plan was then to add console logs to help me debug it.

While doing this, though, I noticed that only the release build uses a module wrapper.  I commented out the module wrapper, and the problem went away.  So it has something to do with the interaction between the Closure Compiler's inserted polyfill and our module wrapper.

**Comment by joeyparrish** [comment]
The code inserted by the compiler doesn't work in a wrapper.  It does not appear to be our wrapper's fault.

In some places, the compiler-inserted code refers to `$jscomp.global.Symbol` (which works), and in others, it refers to `Symbol` (which only works without the wrapper or on browsers with native `Symbol` support).  This mistake appears in the definitions of `$jscomp.makeIterator`, `$jscomp.generator.Generator_`, and `$jscomp.iteratorFromArray`.  This bug appears to be present in the latest Closure Compiler sources.

I will patch it locally in our pre-built compiler, then create a PR to send the changes to the Closure Compiler team.

**Comment by joeyparrish** [comment]
Compiler patch: https://github.com/joeyparrish/closure-compiler/commit/ab6ead338d7a03f1caa335eae2de8e977b61c901

**Comment by ismena** [comment]
@joeyparrish Boy, am I glad I asked you 😛

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.9 and v2.4.1.
