### ISSUE TITLE
[Question] Mixing Dash live and Dash on demand

### ISSUE THREAD

**Issue by philippk80** [google/shaka-player#1461]
Hello,
I have the requirement to build a application that acts as on demand service but shouldn't save multiple version of the converted original video file. But it should support multiple video profiles.
Which way would you go? 

I thought about two possibilities:

1. Use shaka with dash on demand and refer in the manifest to multiple versions of the video that not really exists and the server will compute the needed conversions per request.
Will this affect the choosing of the quality on shaka side negative because of possible longer loading times for videos chunks?

2.  Use shaka with dash live. But then I have the problem that I'm not able to skip parts or see the full duration on client side. Or am I wrong?

Thanks.

**Comment by ismena** [comment]
Hi @philippk80,
Could you describe your use case in more detail?

You want to take a VOD dash manifest and only make 1 stream available per content type (only one video, one audio and one text regardless of user's network speed, language preference etc.). Is that right?
Does the manifest itself have multiple renditions (many video/audio versions)?

**Comment by philippk80** [comment]
I try to explain it. 
I want to provide the video with multiple quality profiles like youtube, netflix, ... ( I think that is the most common requirement) Now is the problem that I have to keep the needed disk space as low as possible.
Because of this I thought about saving only the file with the best quality. This should allow me to make something like a realtime rendering when someone requests some media. Maybe it should be said that there won't be as much clients as netflix and youtube must handle. (Maybe something between 1 to 5)

I thought about building a HTTP interface which provides for example following endpoints and will be included in the manifest:
http://server.com/player/{mediaId}-4k.webm
http://server.com/player/{mediaId}-1080p.webm
http://server.com/player/{mediaId}-720p.webm
http://server.com/player/{mediaId}-480p.webm

But only the 4k one exists physically on the disk. So the others will be rendered partially when the client requests a chunk. 
So the player should be able to switch between the resolutions and I don't have to safe all version of the video. 
Is this too optimistic because of performance or is this possible?

**Comment by ismena** [comment]
@philippk80 I think I understand the idea. Let me bring in <s>the big gun</s> our most experienced team member.

@joeyparrish I feel like you might be able to give better advice on the general technical direction of the project in question.

**Comment by philippk80** [comment]
Yesterday I tryed to make a performance test with VP9 and a desktop pc. The results won't let me go with this approach even on 720p for performance reasons. I don't know if I would get better results if using another codec.

**Comment by TheModMaker** [comment]
My guess is that you wouldn't be able to do this because of the performance limits.  VP9 has a tendency to be just fast enough to support live, meaning a 10 second segment would take 10 seconds to encode.  H.264 might be better, but I would guess you wouldn't be able to do what you want.

But to answer your questions: you want a normal VOD manifest.  Live manifests just mean that there is a "live edge" which represents what you are recording.  But every resolution of the content is still available up to that time.  So even though the content doesn't exist physically on the disk, it is still a VOD manifest.

You can account for the delays in generating the segments in the `bandwidth` property in the manifest.  You can artificially increase this value to indicate it will take longer to download.  Although this is not really an ideal since that's not what's happening, but it should work to make ABR choose the correct streams.

Really what you should do is just provide a few resolutions on disk and not transcode them.  You could provide original, 360p for really slow networks, and maybe 720p for medium networks.  But transcoding on-demand will probably cause too much delays.
