### ISSUE TITLE
Cant play live stream from ffmpeg

### ISSUE THREAD

**Issue by Tilakv** [google/shaka-player#1467]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**:
Version 2.0 
**Can you reproduce the issue with our latest release version?**:
Yes
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
custom
**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Google-chrome and Linux
**What are the manifest and license server URIs?**:

**What did you do?**
A rendered application creates pipe images, which are encoded by ffmpeg and written as chunks in the form of webm video. The client with shakaplayer opens the image but cant see the video. 
**What did you expect to happen?**
I expected the video to be played when loading the manifest file, but only the image is seen. 
**What actually happened?**

**Comment by Tilakv** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<MPD
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="urn:mpeg:DASH:schema:MPD:2011"
  xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011"
  type="dynamic"
  minBufferTime="PT1S"
  profiles="urn:mpeg:dash:profile:isoff-live:2011"
  availabilityStartTime="2018-06-19T11:51:17Z"
  timeShiftBufferDepth="PT60S"
  minimumUpdatePeriod="PT0S">
<Period id="0" start="PT0S" >
<AdaptationSet id="0" mimeType="video/webm" codecs="vp8" bitstreamSwitching="true" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
<ContentComponent id="1" type="video"/>
<SegmentTemplate timescale="1000" duration="2000" media="tea_pot_$RepresentationID$_$Number$.chk" startNumber="1" initialization="tea_pot_$RepresentationID$.hdr"/>
<Representation id="360" bandwidth="1000000" width="512" height="512" codecs="vp8" mimeType="video/webm" startsWithSAP="1"></Representation>
</AdaptationSet>
</Period>
</MPD

**Comment by TheModMaker** [comment]
Can you please provide an example manifest URL that reproduces your problem?  You can send it privately to shaka-player-issues@google.com if you prefer.  We may also be able to work with an example FFmpeg command, but it would be preferable to have the manifest URL (and please send a URL, not the manifest text, we need to be able to play the content).

My guess is FFmpeg is converting a static image to a video stream and that is what we are playing.  What you may want to try is having FFmpeg output a static file instead to verify it is generating the video you want.  You may get more help on the FFmpeg mailing list (ffmpeg-user@ffmpeg.org).  If I run the following command, I can play the manifest fine.

```sh
ffmpeg -i sintel.mp4 -c copy -f dash manifest.mpd
```

**Comment by Tilakv** [comment]
The commands below is for creating chunks:

/home/user/bin/ffmpeg -f rawvideo -vcodec rawvideo -pix_fmt bgr24 -video_size 512x512 -threads 1 -probesize 32 -r 100 -i /home/user/raw_render/src/image_out -map 0 -vcodec libvpx  -b:v 5000k -keyint_min 60 -g 60 -f webm_chunk -header /var/www/html/tea_pot_360.hdr -chunk_start_index 1 -chunk_duration_ms 10000 /var/www/html/tea_pot_360_%d.chk

The following is for creating manifest file:

/home/user/bin/ffmpeg -f webm_dash_manifest -live 1 -i /var/www/html/tea_pot_360.hdr -vcodec libvpx  -map 0 -f webm_dash_manifest -live 1 -adaptation_sets "id=0,streams=v" -chunk_start_index 1 -chunk_duration_ms 10000  /var/www/html/tea_pot_live_manifest.mpd

**Comment by Tilakv** [comment]
I am using the local host and I dont have a URI for the manifest file,
instead have a local path. However, I have updated the thread with the
attachments of the manifest file, and ffmpeg commands.

Thanks,
Tilak

2018-06-19 23:08 GMT+02:00 Jacob Trimble <notifications@github.com>:

**Comment by TheModMaker** [comment]
To properly test this, I would need access to the media segments too, not just the manifest.  But could you try playing the generated media files?  You could do something like:

```sh
cat tea_pot_360.hdr tea_pot_360_1234.chk > my_video.webm
```

Then try playing the WebM file in any video player like VLC or just open in Chrome.  I suspect that file will be a still image.

What I think is happening is FFmpeg is taking the source image and converting it to a video of that one image.  FFmpeg first reads the input file of `/home/user/raw_render/src/image_out`, which I suspect is a still image.  Then FFmpeg converts that to a video by playing that image for the duration of the video.

**Comment by Tilakv** [comment]
Yes, the video my_video.webm is a still image. I tried to convert it to a feed the render with the mouse coordinates and the new image is created by the render software, but the client plays only a still image. I still need to check if ffmpeg makes a webm video with the images fetched from the renderer. 

I had a working prototype with the real time streaming of the interactive streaming, where the server streams the new images in the form of webm file, with ffserver, ffmpeg, and played by HTML5 video tag. 
Whereas in the DASH implementation, ffserver is not used, and the details like Port number and video file location are not transparent. Apparently, in case of  MP4, the MPD structure is different than webm,

**Comment by Tilakv** [comment]
/home/user/bin/ffmpeg -f rawvideo -vcodec rawvideo -pix_fmt bgr24 -video_size 512x512 -threads 1 -probesize 32 -r 100 -i /home/user/raw_render/src/image_out -map 0 -vcodec libvpx  -b:v 5000k -f webm output.webm 

THe above command creates the video with the new
[output.webm.zip](https://github.com/google/shaka-player/files/2122789/output.webm.zip)

 mouse co-ordinates

**Comment by TheModMaker** [comment]
This looks like a problem with your FFmpeg command.  I am not that familiar with the FFmpeg command line, so I can't really help.  I would suggest asking this on the FFmpeg mailing lists (ffmpeg-user@ffmpeg.org); you can read more about them on their [website](https://www.ffmpeg.org/contact.html#MailingLists).  From our perspective, we are doing the right thing.  The manifest you gave us contains video segments that show a still video, so that is what we play.

My guess would be that FFmpeg is not re-opening the `image_out` file as it streams.  So it opens it at the beginning and streams until it reaches the end of the file, but it won't see any updates your renderer makes after it starts because it won't re-open the file.  But again, I am not that familiar with the FFmpeg command-line.

**Comment by joeyparrish** [comment]
To create a video from a sequence of images, you might try this guide: https://en.wikibooks.org/wiki/FFMPEG_An_Intermediate_Guide/image_sequence

**Comment by Tilakv** [comment]
When I cat the .hdr video and the .chk file, the output video contains new images. The client however does not play the cumulative chunks. This means that fffmeg reads the new images from the pipe and updates them. 

For eg:       cat tea_pot_360.hdr tea_pot_360_*.chk   | ffplay -   

This plays the video with new images. I am not sure how shaka player interprets the chunks. Does it cumulatively play all the chunks in order with/after a certain timestamp value?

**Comment by TheModMaker** [comment]
Without a playable manifest to test with, we can't reproduce the problem.  Could you setup a live stream that we can access that reproduces your problem?  Or if you could produce a VOD manifest that causes a similar problem, we could help with that.

Could you also explain exactly what you are seeing in the browser?  You said `but only the image is seen` in the original post, but could you elaborate?  Is the video playing or paused?  If you open up the JavaScript console, do you see any logs (you'll need to use the [debug version](https://shaka-player-demo.appspot.com/docs/api/tutorial-debugging.html) of the library)?  What is the value of `video.currentTime`, and is it changing?  What about `video.paused` and `video.playbackRate`?  Can you seek in the video?  If you use the demo page, while playing, what does the seek bar and playhead do?

**Comment by Tilakv** [comment]
I have done some tests and have identified the following:

The issue is with the chunk size and duration. FFMPEG creates a webm chunk of size equal to the GOP, and each chunk starts with a Key frame. To reduce the delay, I used a GOP of 1, and this creates chunk for every frame. For, 60 fps, 60 chunks are created per second, and respectively 30 chunks for 30 fps. 

There is a delay of at-least one chunk ( 1 GOP size ). Which means, a GOP of 120 leads to 4 seconds of delay for 30 fps. The Manifest file loads the chunks periodically at a lower frequency(Approximately each chunk every 2 seconds?). I don't know if this can be configured on the Shaka player ? 

In a real time streaming scenario, there is initially a delay of 1 GOP and if there are more chunks created than it can be loaded by the player, the current stream lags by several frames. 

The question is if the Shaka player can be loaded or configured to retrieve the next chunks as soon as it is created? I played a bit with the "minimumUpdatePeriod" interval, but I could not notice any difference in the frequency chunks are loaded. Instead, the Manifest file is updated more regularly. 

If the GOP is approximately 3 to 4 seconds, then the client loads the next chunks as soon as it is created, otherwise the client player is lagging. 

Thanks!

**Comment by TheModMaker** [comment]
I'm not sure what you mean by "chunks", but you are definitely not creating 30 segments (i.e. files) per seconds, because I doubt we could download and play segments that fast.  I think the segment duration is defined by the `-chunk_duration_ms` flag, which is 10 seconds in your above example.  Setting this too small requires us to download a lot of segments which can cause slowdowns.

As for low-latency options, anything you change can cause buffering problems.  We use conservative defaults for settings to ensure that we avoid buffering (stopping because we don't have enough downloaded).  If you try to play too close to the live edge, we can start buffering and fall behind if we don't get a segment in time.  But if you are fine with that, there are a few options to try:

- Reduce  `rebufferingGoal`, this makes us need less content to continue playing.
    - `player.configure({rebufferingGoal: 1});`
- Add a `suggestedPresentationDelay` attribute to the manifest.
- Use a segment size of 1 second; less and we have trouble downloading all the segments, more increases the delay.

You may also want to *increase* the `minimumUpdatePeriod`.  This may seem weird, but your manifest uses `SegmentTemplate` with `duration`, meaning we don't actually need manifest updates unless you add new Periods.  So a larger update period means we are downloading less so the network can download segments faster.

Also setting an extremely small GOP interval will make your files much larger since you basically won't be compressing anything.  A GOP size of 1 second is the usual value.

**Comment by Tilakv** [comment]
@shaka-bot Thanks for the suggestions! Sorry for the delay to respond. I have tested some settings which are tagged in the previous comments like large minimumupdate_period set to 7200 sec.. I added the element  suggestedPresentationDelay by tweaking the ffmeg source code (hardcoded to zero), as the option is not available to set in ffmpeg command. 

I have set a GOP of 1 sec and a bit more (34 for 30 fps). I have noticed the following:

Sometimes the live session hangs at roughly about downloading 80 chunks. In the beginning of the session, when the client starts, the chunks are requested fast and in synchronization with the generation rate at the server. After playing roughly 40 chunks, the client starts to lag with the server side and the difference can go up to 20-30 chunks depending on the duration of the session. For eg. at time T+80th chunk at the server, the client plays T+60th Chunk. 

Is this a common phenomenon in case of live streaming? 

Thanks,
Tilak

**Comment by TheModMaker** [comment]
It is common for live streams to suffer from drift when the encoder and the clients become different over time.  But it is usually the other direction; the encoder is encoding at 0.99x realtime, so the encoder falls behind over time and can't generate fast enough.  In your case, I think FFmpeg is encoding content faster than realtime, so it generates more content than the player is playing.

You could try passing the `-re` input option.  Since you are reading from a file, this option causes FFmpeg to wait before producing the next input data so it can simulate a live stream.  I think it would cause it to only generate segments at realtime.

**Comment by joeyparrish** [comment]
Our [history live stream](https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-live-assets/player-source.mpd;lang=en-US;noinput;build=compiled) is also generated from a pipe, and uses ffmpeg with the `-re` option.  I think that is a requirement for generating live streams from a pipe.
