### ISSUE TITLE
Retrieve challenge to get license

### ISSUE THREAD

**Issue by AdrienKourga** [google/shaka-player#1469]
Hi !

How can i retrieve a challenge without fake-loading a video segment ?

I want to use the challenge to get the license for offline uses.

**Comment by TheModMaker** [comment]
License requests contain timestamps in them to prevent this kind of usage.  If a license request takes more than a certain amount of time (e.g. a few minutes), the response won't be accepted.  If you want to play protected content offline, I would suggest using our [offline API](https://shaka-player-demo.appspot.com/docs/api/tutorial-offline.html).  It will handle storing the license offline so you can play it.  You can also configure it with `usePersistentLicense` of `false` and it won't store the offline license and instead make a license request when you play the content.

In general, you can't store a license request or license response for later use.  If you want an offline license, you need to use EME to request a special kind of license.  But we handle that for you in our offline API.

**Comment by AdrienKourga** [comment]
Thanks for answering that quickly !
Does it means that if we use the offline api to download a protected content, shaka player will figure out that this content is protected and will send a license request to our license server ? (using the server urls we provide with player.configure() ?)
And if so, just out of curiousity, how does shaka player gets a challenge to retrieve a license without actually trying to play the content ?

**Comment by TheModMaker** [comment]
Correct.  The Player instance you pass to Storage should be configured with any license servers and filters needed to make the license request.  We will automatically get the license and store it correctly.

We detect protected content only using the manifest.  The manifest must contain a `<cenc:pssh>` element that contains the initialization data to generate the license request.  Normally, this element is optional and the browser will pull that info out of the media, but since we don't want to try and play the media, we require that initialization info be in the manifest.

**Comment by joeyparrish** [comment]
The EME API is used to manage licenses, both for streaming and offline storage.  This API does not require a video element to fetch a license, so that is how we are able to retrieve a license without playing the content.

The only requirement for fetching a license is the "init data", which is commonly an MP4 PSSH box.  As @TheModMaker points out, so long as a PSSH appears in the manifest, we have everything we need to store offline protected content (on supported browsers).
