### ISSUE TITLE
Merge throws out new refs from SegmentList + SegmentTimeline + presentationTimeOffset

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1477]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: v2.4.1

**Can you reproduce the issue with our latest release version?**: yes

**Can you reproduce the issue with the latest code from `master`?**: yes

**Are you using the demo app or your own custom app?**: custom

**If custom app, can you reproduce the issue using our demo app?**: haven't tried, but I expect so

**What browser and OS are you using?**: Chrome 68 beta on Linux

**What are the manifest and license server URIs?**: still working on access to those

**What did you do?**
Loaded a live stream with SegmentList + SegmentTimeline + presentationTimeOffset.  On each update, the manifest changes the presentationTimeOffset and startNumber of the SegmentTimeline, but not the timestamps in the SegmentTimeline.  The timeline always contains segments at time 0, 2, and 4.

**What did you expect to happen?**
When merging new refs with old ones, we should end up with more references.

**What actually happened?**
Because both sets of references have the same timestamps, the merge throws out the new ones.  The merge does not happen in context of presentationTimeOffset, so the segment list does not grow and the player is stuck in a buffering state.

**Comment by joeyparrish** [comment]
This was found with the same content as #1478, but with a local change in the DASH parser to avoid creating new periods on each update.

Here's an example of what we had:

```xml
    <SegmentList presentationTimeOffset="221502" startNumber="108" timescale="1000">
      <SegmentTimeline>
        <S d="2000"/>
        <S d="2000"/>
        <S d="2000"/>
      </SegmentTimeline>
    </SegmentList>
```

What I found while debugging was that `SegmentIndex` contains `SegmentReference`s with times 0, 2, and 4.  The structure representing the `<SegmentList>` element contains a field with the PTO, but that is kept outside the `SegmentIndex` object.  When we merge at the `SegmentIndex` level, we throw out the new refs.

I'm suspicious that this might be bad content, though.  The timestamps in the `SegmentTimeline` should be the actual media times, correct?  PTO is meant to align those with the period, as I understand it.

But in this case, PTO changes when we update the manifest, and the segment times stay fixed.  So PTO is being used to adjust the fixed times to the actual media times.

Is it fair to say this is abusing the way DASH is supposed to work?

**Comment by TheModMaker** [comment]
But the Period start is changing, so the absolute presentation times of those segments probably aren't changing (from DASH's perspective).  So even though the first segment in the list starts at 0, you need to add the Period start to it before you can say whether the absolute presentation time changes.

The segment times in the `SegmentIndex` are Period-relative, so the new segments will show 0, 2, 4 because that are the times relative to the new Period start;  but the old segments have times of 0, 2, 4 relative to the old Period start.

This might be allowed by DASH and until v1.4.2 this was allowed by the IOP so long as the absolute presentation times of the segments don't change.  But with the latest IOP, this is disallowed since the Period start can't change.

**Comment by joeyparrish** [comment]
Okay.  Thanks.  I'll mark this "bad content" and WAI as well.
