### ISSUE TITLE
Safari 11  Requested Key System Config Unavailable for clear content

### ISSUE THREAD

**Issue by grantg182** [google/shaka-player#1479]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
v2.4.1-master-11-g759eef96-debug
**Can you reproduce the issue with our latest release version?**:
Yes
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
Own
**If custom app, can you reproduce the issue using our demo app?**:
Uncertain
**What browser and OS are you using?**:
Safari 11.0.3 on macOS High Sierra (10.13.3)
**What are the manifest and license server URIs?**:
Will deploy to an accessible server for this to be possible to check over the internet.
**What did you do?**
Upgraded from 2.2 to 2.4, played an unencrypted MPD.

**What did you expect to happen?**
Successful playback.
**What actually happened?**
Playback failure with the following error:-

shaka.util.Error { "severity": 2, "category": 6, "code": 6001, "data": [], "handled": false, "message": "Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()", "stack": "Error@http://localhost/content/shaka-player/dist/shaka-player.compiled.debug.js:79:779\nhttp://localhost/content/shaka-player/dist/shaka-player.compiled.debug.js:149:216\npromiseReactionJob@[native code]" }

Now, I was unsure why I would hit a Category 6 error (DRM) with an unencrypted, clear piece of content. Since we may play DRM items, we tell shaka the drm servers and advanced policies within the configure() method. Removing this from the configure() method restores functionality pre-2.4 - i.e. successful playback of non-drm content in Safari using Shaka 2.4.

Any ideas? Thanks

**Comment by TheModMaker** [comment]
This is caused by #1094.  Since you have DRM config, we try to initialize EME since we assume there will be encrypted content eventually.  Since Safari doesn't have any EME systems, we fail to initialize.  We should probably not fail if there aren't any key systems in this case.

It should be reproducible with this.  It is a DashIF clear live stream with a Widevine license server URL given to it.  It plays in Chrome (and probably Firefox) but not Safari.

https://shaka-player-demo.appspot.com/demo/#asset=https://vm2.dashif.org/livesim/testpic_2s/Manifest.mpd;license=https://proxy.uat.widevine.com/proxy;lang=en-US;build=uncompiled

**Comment by grantg182** [comment]
Yeah, after wasting the better part of 2 days trying to figure out if this was something I had done (after making several changes to the frontend before upgrading to 2.4), I suspected something had gone awry in 2.4. Will have to revert back to 2.2 unless there's some quick fix to implement. 

Thank you for the quick response 👍

**Comment by theodab** [comment]
I just put a CL out to fix it. Hope to have it submitted by the end of the day, if possible.

**Comment by grantg182** [comment]
Great, will keep an eye out. Would be great to not have to revert back to the old methods. I've actually got Shaka set up with a handler which handles pre-roll ads before we init() - coincidentally the exact purpose of the change which caused this broken behaviour! 😿

**Comment by theodab** [comment]
Okay, hopefully that will fix your issue. If not, though, be sure to tell us.

**Comment by grantg182** [comment]
Thanks.

So I've yet to have had a need to bring in a specific commit. Instead, just pulled master and ran with it.

So here's what I've done:-

Dropped drm_engine.js from [this commit](https://github.com/google/shaka-player/commit/3192c02525665305c9694ef77b9784970b5bc05f) into /lib/media/ then did a rebuild, using `python build/all.py` then took the new shaka-player.compiled.js and shaka-player.uncompiled.js and replaced the old version of these (i.e. from 2.4 master).

Cleared all browser cache in Safari and unfortunately I'm still hitting the same error.

**Comment by theodab** [comment]
Hm. My change fixed playback for the assets Jacob provided. I don't think you could have installed it wrong, since the changes were pretty standalone.

Well, whatever. I can look into this more next week. In the meantime, it'd help if you could provide a public server link for the assets in question, to <shaka-player-issues@google.com>. Plus steps to reproduce on the demo app, if possible?

**Comment by grantg182** [comment]
Sorry, edited my last post, all working here now too. Thanks again!

**Comment by theodab** [comment]
No worries! Glad to have helped.

**Comment by joeyparrish** [comment]
This change will be cherry-picked for v2.4.2.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.4.2.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.3.10.
