### ISSUE TITLE
Support blob URLs in Player.load

### ISSUE THREAD

**Issue by pix-dgee** [google/shaka-player#1481]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

Yes

**What version of Shaka Player are you using?**:

2.4.1

**Can you reproduce the issue with our latest release version?**:

Yes

**Can you reproduce the issue with the latest code from `master`?**:

Not tested.

**Are you using the demo app or your own custom app?**:

Custom app.

**If custom app, can you reproduce the issue using our demo app?**:

N/A

**What browser and OS are you using?**:

OSX Chrome 67.0.3396.99 

**What are the manifest and license server URIs?**:

N/A

**What did you do?**
Our use case is playing many short clips back to back. To increase performance, we are attempting to preload the manifests, store them as Blob URIs, and pass the Blob URI into the `load` method.

All manifests work as expected when passed in as regular URLs, passing in the urlObject fails.

Searched open issues, and found some references that indicate that this should be doable:

https://github.com/google/shaka-player/issues/1247 : Seems to indicate that the author is doing this and it's working except when trying to Chromecast.

https://github.com/google/shaka-player/issues/395 : Seems to indicate that blob urls are working but the author wants to avoid cache busting.

Tried various scheme registrations, eg. `shaka.net.NetworkingEngine.registerScheme('blob', shaka.net.HttpFetchPlugin);`, none worked.

**What did you expect to happen?**

Expected the manifest to be successfully loaded from the objectUrl in the same way it would be from passing in the network URL.

**What actually happened?**

Received the following error:

![image](https://user-images.githubusercontent.com/7050202/42115483-e5027108-7ba7-11e8-976c-b5d05b89d727.png)

**Comment by pix-dgee** [comment]
```
return fetch(
            'https://host.com/stream.mpd',
            { headers }
        )
            .then(response => response.blob())
            .then( blob => {
                return window.URL.createObjectURL(blob);
            })
```

**Comment by pix-dgee** [comment]
I inlined much of this to isolate the issue. I'm still seeing the error with the following sample code:

```
fetch(
                this.stream, // eg. 'https://host.com/stream.mpd'
                { headers }
            )
                .then(response => response.blob())
                .then( blob => {
                    const url = window.URL.createObjectURL(blob);
                    this.load(url); // wraps.shaka.Player.load
                });
```

**Comment by joeyparrish** [comment]
There are a few problems with this in today's Shaka Player:

1. No plugins are registered to handle blob: URIs.  This is tribial to fix by registering either XHR or Fetch to handle blobs: `shaka.net.NetworkingEngine.registerScheme('blob', shaka.net.HttpFetchPlugin);`
2. With blobs, neither extension nor MIME type can be used to deduce which manifest parser to use.  If only there were some way to append ".mpd" to the URI without breaking it.  This is moderately annoying, but easy to fix with the manifestParserFactory argument of player.load: `player.load(uri, null, shaka.dash.DashParser);`
3. Relative URIs in the manifest are broken because the original manifest URI is lost.  This can be worked around with either absolute URIs or the use of BaseURL element in DASH.

With those three problems worked around, I can verify that blob URIs **would** work in the latest release.  For now, I recommend you use these workarounds.

For the future, I will mark this as an enhancement on the backlog to make the use of Blob URIs easier.

We should:
1. register scheme plugins to handle blob URIs
2. have some easier way to specify the parser to use, such as passing a MIME type or extension string in place of a specific parser
3. consider a parser configuration that would override the base for relative URIs found in a manifest

**Comment by pix-dgee** [comment]
Thanks so much for being so responsive, @joeyparrish! I had tried using the `HttpFetchPlugin` but didn't think about how it wouldn't be identifiable as a DASH manifest. Passing in the DashParser resolved the issue.

I now have this working - our manifests do in fact use relative urls, but until I can co-ordinate a backend change, I'm just manually transforming it in the client before I save it to the Blob. 

Regarding your recommended enhancement, that all sounds great. I would say that what we're doing is hardly common practice, so I don't think it's critical functionality, but would definitely be nice to have.

**Comment by pix-dgee** [comment]
Thank you, that sounds like exactly what we're trying to accomplish!

**Comment by pix-dgee** [comment]
Updating this with some additional info. Using `HttpFetchPlugin` in conjunction with `shaka.dash.DashParser` works like a charm in recent versions of Chrome. 

Unfortunately, as we're relying on Castlabs' prepackaged electron releases ( https://github.com/castlabs/electron-releases ) to enable Widevine support in Electron, we discovered that this surfaces the same `1000` error attached above when using Chrome 59.

**Comment by pix-dgee** [comment]
Absolutely. Was just commenting in case some lost soul wanders into this thread in the future, I don't expect any action to be taken ;) Sorry if that was unclear.

**Comment by joeyparrish** [comment]
Gotcha.  Thanks!

**Comment by kocoten1992** [comment]
> There are a few problems with this in today's Shaka Player:
> 
> 1. No plugins are registered to handle blob: URIs.  This is tribial to fix by registering either XHR or Fetch to handle blobs: `shaka.net.NetworkingEngine.registerScheme('blob', shaka.net.HttpFetchPlugin);`
> 2. With blobs, neither extension nor MIME type can be used to deduce which manifest parser to use.  If only there were some way to append ".mpd" to the URI without breaking it.  This is moderately annoying, but easy to fix with the manifestParserFactory argument of player.load: `player.load(uri, null, shaka.dash.DashParser);`
> 3. Relative URIs in the manifest are broken because the original manifest URI is lost.  This can be worked around with either absolute URIs or the use of BaseURL element in DASH.
> 
> With those three problems worked around, I can verify that blob URIs **would** work in the latest release. For now, I recommend you use these workarounds.
> 
> For the future, I will mark this as an enhancement on the backlog to make the use of Blob URIs easier.
> 
> We should:
> 
> 1. register scheme plugins to handle blob URIs
> 2. have some easier way to specify the parser to use, such as passing a MIME type or extension string in place of a specific parser
> 3. consider a parser configuration that would override the base for relative URIs found in a manifest

Will this method still work now at newer version ?

When I try it on v3.1.0, it said:
```js
shaka-player.ui.js?id=2a5664041f59d0b5fd86:272 Uncaught (in promise) TypeError: d.toLowerCase is not a function
    at ya.b (shaka-player.ui.js?id=2a5664041f59d0b5fd86:272)
    at Ca (shaka-player.ui.js?id=2a5664041f59d0b5fd86:22)
    at Da.next (shaka-player.ui.js?id=2a5664041f59d0b5fd86:23)
    at shaka-player.ui.js?id=2a5664041f59d0b5fd86:24
    at new Promise (<anonymous>)
    at Fa (shaka-player.ui.js?id=2a5664041f59d0b5fd86:24)
    at H (shaka-player.ui.js?id=2a5664041f59d0b5fd86:24)
    at ji (shaka-player.ui.js?id=2a5664041f59d0b5fd86:272)
    at ya.b (shaka-player.ui.js?id=2a5664041f59d0b5fd86:374)
    at Ca (shaka-player.ui.js?id=2a5664041f59d0b5fd86:22)
```

**Comment by joeyparrish** [comment]
> `shaka-player.ui.js?id=2a5664041f59d0b5fd86:272 Uncaught (in promise) TypeError: d.toLowerCase is not a function`

It looks to me like you passed a non-string to a method expecting a string.  I would suggest you double-check your application code.  Did you pass a Blob object instead of a Blob URL?  You need to call `URL.createObjectURL(blob)` to create a URL from a Blob.

**Comment by kocoten1992** [comment]
Thank you, but I'm deep down in the rabbit hole by now, it is because `player.load` third argument in v3.1.0 required string https://github.com/google/shaka-player/blob/master/lib/player.js#L1040 - I'm using 'application/dash+xml' now,

in v2.4.1 it is https://github.com/google/shaka-player/blob/e844a0ff958b98cdd422f52f907a844142cdb8d6/lib/player.js#L676-L677,

I'm at the network-engine now, think I'll post a solution for the next gen when I'm done

**Comment by joeyparrish** [comment]
Okay.  Makes sense to me.

**Comment by joeyparrish** [comment]
We'd be happy to have a PR, if you're interested to contribute your solution back.

**Comment by kocoten1992** [comment]
For anyone looking solution in 2021, v3.1.0:

1. register blob scheme
```
shaka.net.NetworkingEngine.registerScheme('blob', shaka.net.HttpFetchPlugin.parse, shaka.net.NetworkingEngine.PluginPriority.PREFERRED, true);
```

2. `player.load(computedMpdBlobURL, null, 'application/dash+xml')`
3. Relative URIs in the manifest are broken because the original manifest URI is lost. This can be worked around with either absolute URIs or the use of BaseURL element in DASH.

@joeyparrish , I'm not sure how to compose a PR for this, may you guide me little ?

**Comment by joeyparrish** [comment]
It looks like you can add the code in part 1 to the bottom of the fetch plugin, and turn parts 2 and 3 into a tutorial to add to the documentation.  That would be a complete PR for this, in my opinion.  Since we can't generally solve the issue of relative URIs, the best thing may be just to document it clearly alongside instructions for creating a blob from an MPD.

Tutorials are written in markdown and compiled by jsdoc.  They live in `docs/tutorials/`, and need to be referenced from `docs/tutorials/index.json` to show up in our top-level tutorials list in the live docs.

Does this help?
