### ISSUE TITLE
Duplicate tags for release commits?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#1485]
I noticed that since v2.3.7 there are now commits tagged with `-master`:

<img width="119" alt="screen shot 2018-07-04 at 11 37 54 am" src="https://user-images.githubusercontent.com/7190265/42285894-ea61198a-7f7e-11e8-973b-1c0158344e8c.png">

I see that they are different than the release branches themselves. Do they just capture the state of `master` at the time of the release?

**Comment by joeyparrish** [comment]
Yes, that's exactly right.  They are used to generate saner version numbers for master branch builds.  This was part of the fix for #1420, although most of the changes took place in our release and tagging process rather than in the code itself.

Before that change, master builds would say something like v2.3.0-158-blah, up until v2.4.0.  There was no way to see that the most recent release had been, say, v2.3.8, and that the master branch build was more closely related to that or v2.4.0 than v2.3.0.  Now that we tag the master branch at each release, that tag is what shows up in master branch builds, which is arguably more informative.

**Comment by chrisfillmore** [comment]
Thanks for the explanation Joey, wasn't sure if it was intentional or not.
