### ISSUE TITLE
providing pre-fetched Sidx data

### ISSUE THREAD

**Issue by krvangala** [google/shaka-player#1496]
Hi,
In our framework , we pre-fetch SIDX tables for bitrates (we generate single sidx file containing sidx tables for bitrates and audio also). We have updated dash.js accordingly when it requires initial segment data, we provide pre-fetched data.  We plan to use shaka instead of dash.js.

What is the best location in source  or method to achieve this in shaka?
Thanks
Krishna

**Comment by joeyparrish** [comment]
I'm not sure where this would best fit.

Can you elaborate on how you prefetch the SIDX tables?  Is it done on the client in the same page context as playback?  Would it be sufficient to trust the browser cache to supply the SIDX when requested by Shaka Player?

Can you also explain why you prefetch the SIDX?  Could you not get the bitrate information from the manifest or from the player?  (We provide this information from the manifest in our tracks API.)

**Comment by krvangala** [comment]
Sorry for not give enough info. Our back end creates a single file containing  sidx information for all streams. This file prefect he'd even before starting playback. Now I would like to use this pre downloaded data instead of calling http server again. This reduces the rate switching  delay. Thanks

**Comment by joeyparrish** [comment]
I don't think there is a simple way to do this in Shaka Player at the moment.

In case you want to dig around and find a way to do this, the SIDX is fetched in [lib/dash/segment_base.js](https://github.com/google/shaka-player/blob/ecd27fbf45b5ddec9a05804386977fbbc7772f8d/lib/dash/segment_base.js#L146) and parsed in [lib/media/mp4_segment_index_parser.js](https://github.com/google/shaka-player/blob/ecd27fbf45b5ddec9a05804386977fbbc7772f8d/lib/media/mp4_segment_index_parser.js#L38).

Since this use-case was never part of our design, I don't have a good recommendation for you.  If you come up with a suggestion, please let us know!

**Comment by joeyparrish** [comment]
Closing for lack of interest/response
