### ISSUE TITLE
Live stream end behaviour when playhead is behind live point?

### ISSUE THREAD

**Issue by Feenposhleen** [google/shaka-player#1499]
Hello,
I'd love some input on an undesired behaviour that we are seeing in latest Shaka, using DASH. This could be related to manifest contents or something else, but I feel at a loss. Not posting as a bug, since I'm unsure which part of the pipeline is the culprit.

So this is an example scenario:
0. Clock is 0.55
1. Start a live stream which starts at 0.0 and ends at 1.0
2. Scrub back to 0.30
3. Five minutes passes; your "offset wall time" is 0.35, actual wall time is 1.0

EXPECTED: Stream continues and ends after 25 minutes
ACTUAL: Stream stops and the video element emits an "ended" event

As a brutal workaround, we can reload the manifest using the current time as start time, which works fine but leads to a sub par user experience and extra complexity.

Any input is appreciated, thanks!

**Comment by joeyparrish** [comment]
I don't think I understand the timeline.  Can you put together an example that we could use to experience this effect and better understand it?

Also, what do you mean when you say it's both live and it "ends"?  What happens at the end in terms of the manifest?

**Comment by Feenposhleen** [comment]
Our live stream segments are always kept even after the event has ended, to be available for a while as catch-up. The manifest doesn't change. Loading such a manifest after the event has ended works fine. Loading it while live also works, but as soon as wall time passes the end of the "live presentation", and no matter where the playhead is, Shaka emits an `ended` event and stops playback. A practical example:

1. I want to see the live soccer game that started one hour ago, so I start the stream. 
2. I want to see the entire game, so I seek to the start and continue to watch from there.
3. One hour before the game ends for me, the stream dies, because it ended according to wall clock.

The segments are still there, and the manifest is the same. Loading it again results in VOD-like catchup behaviour, which is expected and good. Hard to explain, but I hope that made it slightly clearer. :)

**Comment by vaage** [comment]
@Feenposhleen I think I understand the scenario you're explaining.

Since all the segments are still available, it is possible to convert the live manifest to a VOD manifest and Shaka Player does support this transition .

@kqyang from the Shaka Packager team talks about the attributes that need to change in the manifest to allow this in this [issue](https://github.com/google/shaka-packager/issues/321#issuecomment-361336181).

So when your live stream ends, the server can update the manifest to be VOD and when the player fetches the updated copy it should switch from playing the live stream to the VOD stream automatically.

@joeyparrish Did I miss anything?

**Comment by kqyang** [comment]
@vaage For @Feenposhleen use case, converting to VOD shouldn't be needed as long as the buffer depth is big enough. From what @Feenposhleen described, it sounds like the buffer depth is unlimited. Perhaps Shaka Player can be improved to not terminating the live stream when the live event ends if the playback is in the past? I wonder how `end` is signaled in @Feenposhleen's stream and in what condition `ended` event is emitted in Shaka Player?

**Comment by Feenposhleen** [comment]
@vaage @kqyang Thanks. As I pointed out, loading the exact same manifest after the event has ended results in well functioning VOD playback (starting from beginning, etc). This indicates to me that changes in the manifest would not be required. If Shaka supports manifest attributes being modified on the fly as @vaage described, then the logic to do so might need to account for this scenario as well.

**Comment by joeyparrish** [comment]
@Feenposhleen, it should be easy enough to convert live to VOD during playback, so long as the presentation timeline does not change.  The timestamps seen by the video element are in the presentation timeline.

For example, if your live stream starts at availabilityStartTime of 2018-07-25 18:00:00 UTC, then that should be the wall time of the first segment, and its presentation timestamp should be 0.  If you later convert to VOD that starts at the same segment, the presentation timeline hasn't changed.

If, though, your live stream starts at wall time 2018-07-25 18:00:00 UTC, but with availabilityStartTime of availabilityStartTime of 1970-01-01 0:00:00 UTC, then your first segment's timestamp is 1532541600.  If you later convert to VOD and give that first segment a timestamp of 0, your presentation timeline has changed.

There is no easy way to support changing the presentation timeline like that during a MediaSource playback.  During the playback session, you can't just change the timeline and expect the browser to understand it.  Nor is it very easy to map between two (or more) timeline changes in the player to manage it above the browser.

Since we don't have any examples of your content to work from, I can only guess that your timeline is changing when you convert from live to VOD.  When you reload the manifest, you're starting a new MediaSource session with a completely new timeline, which explains why this corrects playback in your case.

If your presentation timeline isn't changing, then it could be a Shaka Player bug.  We would need a way to reproduce the issue from our own workstations to find out more and solve the problem.

**Comment by Feenposhleen** [comment]
@joeyparrish I'm very sorry, but it turns out that I've been wrong; the manifest does indeed change. The timeline part seems to remain pretty much the same, with the exception of the removal of `presentationTimeOffset`. The relevant snippets from the manifests:

**Live manifest:**
```xml
<MPD
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="urn:mpeg:dash:schema:mpd:2011"
  xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
  xmlns:cenc="urn:mpeg:cenc:2013"
  xmlns:mas="urn:marlin:mas:1-0:services:schemas:mpd"
  type="dynamic"
  availabilityStartTime="1970-01-01T00:00:00Z"
  publishTime="2018-07-27T07:11:37.024180Z"
  minimumUpdatePeriod="PT2S"
  maxSegmentDuration="PT2S"
  minBufferTime="PT12S"
  profiles="urn:mpeg:dash:profile:isoff-live:2011,urn:com:dashif:dash264">

[...]

<SegmentTemplate
  timescale="48000"
  initialization="foo-bar-$RepresentationID$.dash"
  media="foo-bar-$RepresentationID$-$Time$.dash">
  <!-- 2018-07-27T06:24:39.682645Z / 1532672679 - 2018-07-27T07:11:30.562645Z -->
  <SegmentTimeline>
    <S t="73568288624767" d="92160" r="1463" />
  </SegmentTimeline>
</SegmentTemplate>
```

**Same manifest after event ended:**
```xml
<MPD
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="urn:mpeg:dash:schema:mpd:2011"
  xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
  xmlns:cenc="urn:mpeg:cenc:2013"
  xmlns:mas="urn:marlin:mas:1-0:services:schemas:mpd"
  type="static"
  mediaPresentationDuration="PT50M22.122645S"
  maxSegmentDuration="PT2S"
  minBufferTime="PT12S"
  profiles="urn:mpeg:dash:profile:isoff-live:2011,urn:com:dashif:dash264">

[...]

<SegmentTemplate
  timescale="48000"
  presentationTimeOffset="73568288622720"
  initialization="foo-bar-$RepresentationID$.dash"
  media="foo-bar-$RepresentationID$-$Time$.dash">
  <!-- 2018-07-27T06:24:39.682645Z / 1532672679 - 2018-07-27T07:15:01.762645Z -->
  <SegmentTimeline>
    <S t="73568288624767" d="92160" r="1573" />
  </SegmentTimeline>
</SegmentTemplate>
```

**Comment by TheModMaker** [comment]
In this case, your timeline is changing.  Even though the `SegmentTimeline` element is the same, the segments appear at different presentation times.  In the live manifest, that first segment plays at a presentation time of 1532672679 seconds, whereas in the VOD manifest it has a presentation time of 0.043 seconds.  We can't easily support changing the timelines like this.

**Comment by TheModMaker** [comment]
We can't really support that kind of content since the presentation time changes.  If you have any other questions, feel free to ask.  You can reopen this issue with a comment with `@shaka-bot reopen`.

**Comment by Feenposhleen** [comment]
@TheModMaker Okay, thanks. I don't quite understand how the presentation time would be 0 in the VOD case though, when there is a `presentationTimeOffset` present of `73568288622720`. To me it would seem that the first segment is at `1 532 672 679.64` seconds in both cases. Am I missing something?

**Comment by TheModMaker** [comment]
The `presentationTimeOffset` adjusts the media time backward.  The calculation for presentation time is always `(S@t - PTO) / timescale + Period@start`, so:

```js
// Live Case:
(73568288624767 - 0) / 48000 + 0 = 1532672679.6826

// VOD Case:
(73568288624767 - 73568288622720) / 48000 + 0 = 0.0426
```

I wrote a doc that may help explain how presentation times and segment times work:
<https://github.com/google/shaka-player/blob/master/docs/design/dash-manifests.md>

**Comment by Feenposhleen** [comment]
@TheModMaker Great doc! I can see now how a transition between the timelines would be complex. I suppose the conversion between media time and the "segment timeline" is a very core component of the manifest parser. I will then try to silver tape together a fix using request filters instead. Such a great escape hatch while waiting for slow moving encoder changes.

Thanks for all the assistance!
