### ISSUE TITLE
Questions on networking engine's design

### ISSUE THREAD

**Issue by vaage** [google/shaka-player#1500]
Networking Engine is passed around a lot in our code base. Normally it is created by the player and then pass down multiple function calls.

In the past we have talked about why sharing a networking engine is so important. Normally the request filters are the strong reason to share an instance.

It feels like the code-base could be easier to work with if we did not always need to pass networking engine around. If either the networking engine was a singleton or the filters were globally applied, it feels like it would be easier to work with.

So, why was networking engine designed to be:
  1. Always used as an instance variable
  2. Request filters are scoped to a specific networking engine

**Comment by chrisfillmore** [comment]
Keep in mind that there may be multiple `Player` instances running at once (e.g picture-in-picture or tiled playbacks). Here is a use case for which the use of a singleton seems problematic to me: As a Shaka client developer, I want to be able to add a header to segment, manifest, and license requests, on a per-stream basis. (We need to track requests for specific streams with a unique GUID.) Keeping in mind that a stream URL may change over the course of playback, how will I differentiate between multiple streams playing at the same time?

Simply making the code base easier to work with does not seem like a motivating reason, IMO. I worry that many use cases (potentially new and unexpected ones) would be adversely affected by the use of a singleton.

**Comment by joeyparrish** [comment]
@chrisfillmore, I think you're spot on.  There are multiple NetworkingEngine instances so that there can be multiple Player instances.  Since networking filters are registered on the engine instance, and because those are used (among other things) for authentication, it should stay a per-Player instance.

The tension here is that we (especially @vaage) are working to make things like Storage independent of Player.  This means that Storage now needs a NetworkingEngine that it may not necessarily be able to get from a Player instance.
