### ISSUE TITLE
[QUESTION] Does Shaka player have SDK ?

### ISSUE THREAD

**Issue by YingChen-dci** [google/shaka-player#1517]
Hello,

I'd like know does Shaka Player have SDK for iOS/Android APP developing or not? Or Does Shaka player only for browser playback?

**Comment by chrisfillmore** [comment]
If you are asking about native app development, video playback on iOS is generally handled exclusively by Apple's AVPlayer using [HTTP Live Streaming (HLS)](https://developer.apple.com/streaming/).

If you want to play video in a browser on iOS, Shaka does not support this yet, but you can follow progress on #997. You can play streaming video in Safari on iOS [using The `<video>` element](https://developer.apple.com/library/archive/technotes/tn2224/_index.html#//apple_ref/doc/uid/DTS40009745-CH1-DEPLOYYOURMEDIA-HTML5_VIDEO_ELEMENT).

For video playback in native apps on Android, the Google standard is [ExoPlayer](https://github.com/google/ExoPlayer), though there are other alternatives on Android. If you would like to play video in a browser on Android (or via [Progressive Web App](https://developers.google.com/web/progressive-web-apps/)), Shaka supports this.

You can also use Shaka in TV/set-top-box HTML5 environments (Tizen 2017 TV's are officially supported).

**Comment by TheModMaker** [comment]
Shaka Player only supports browser environments and environments where there is a JavaScript interpreter with the required types available (e.g. [MSE](https://w3c.github.io/media-source/)).  This can include smart TVs like the Tizen TV.  We do not support native apps since they aren't written in JavaScript (some frameworks allow you to write JavaScript, but they don't have MSE or other browser types we need).

**Comment by YingChen-dci** [comment]
I see. 
Thank you very much for your information.
