### ISSUE TITLE
Support downloading of Dash manifests that do not have inline PSSH value

### ISSUE THREAD

**Issue by bartsidee** [google/shaka-player#1531]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
2.3.x

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Demo

**If custom app, can you reproduce the issue using our demo app?**:
N/A

**What browser and OS are you using?**:
Electron with Widevine CDM enabled:
https://github.com/castlabs/electron-releases

**What did you expect to happen?**
Ability to download Dash content (ondemand) with DRM (widevine) that does not have inline PSSH data in the manifest

**What actually happened?**
- Downloading Dash with no inline PSSH value in the manifest throws a "NO_INIT_DATA_FOR_OFFLINE" error on download initiation:
https://github.com/google/shaka-player/blob/05b071d7fa66a23a91ba44c34667bbe0d0e81644/lib/offline/storage.js#L753
- Downloading Dash with inline PSSH value in the manifest downloads & plays successful
- Both Dash manifest types (inline vs no inline PSSH) do play successful in an online environment

The inline PSSH property should be optional in the manifest specification, but mandatory to be available in the binary fragments. Shaka seem to be correctly supporting this for online playback, but for the offline download initiation it seems to be depending solely on the inline PSSH value. 

We are trying to understand if this is a bug or if there is a limitation that prevents shaka from using the PSSH value in the binary fragments while downloading content.

**Comment by TheModMaker** [comment]
This is a limitation of Shaka Player.  If you will have internet connection when you play later, I think you can store it with `usePersistentLicense=false` and we won't store the licences.  But it requires internet access to play the content:  `storage.configure({usePersistentLicense: false})`

When we store content, we need to create an EME offline session so we can play the encrypted content later.  To create the session we need the init data, which is usually PSSH data.  If it is in the manifest, we can just pass it to EME to create the offline session.  But if we don't have it, we need to get it from the media.  In a streaming situation, we pass the media to the browser and it gives us an `encrypted` event with the PSSH data in it.  But when we are storing content, we can't give it to the browser since we don't want to create a `<video>` element and have to deal with MSE.

We could parse the segments while we store them and look for the PSSH data.  We don't do this since it would really complicate the storing logic and doesn't work for other container formats.  It might be easier for MP4 since we have an `Mp4Parser` type to make parsing easier, but trying to support WebM would be much harder since we don't have a simple parser for it.

**Comment by bartsidee** [comment]
Thank you for the detailed answer. 

Understanding the limitations and complications, would it not be possible to create a small utility method as a fallback that would be able to capture the PSSH from the downloading (mp4) segments (without overhauling the logic to much and/or introducing complex parsers).

The below might be an interesting reference:
https://github.com/youtube/js_mse_eme/blob/586255b3261dd63b951246b2ef01085f9bc26ef5/js/lib/eme/encryptedMediaPortability.js#L109

**Comment by bartsidee** [comment]
Great! We have been working on a solution and have been able to make this work by using the shaka mp4 atom parser on the initial segment to extract the pssh. We will share a PR for review once ready

**Comment by joeyparrish** [comment]
Excellent!  A PR is very welcome.

**Comment by avelad** [comment]
@joeyparrish , i think that it's necessary reopen the issue because the change was reverted in https://github.com/google/shaka-player/commit/625938e2f96f18bb40045a24f73b646615c16c41

**Comment by joeyparrish** [comment]
Yes, good catch.  Thanks!
