### ISSUE TITLE
Error parsing DASHEventMessageBox (emsg) without message_data.

### ISSUE THREAD

**Issue by damienlevin** [google/shaka-player#1535]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
Shaka Player v2.4.3-uncompiled
**Can you reproduce the issue with our latest release version?**:
Yes
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
Demo app
**If custom app, can you reproduce the issue using our demo app?**:
N/A
**What browser and OS are you using?**:
Chrome/Mac
**What are the manifest and license server URIs?**:
https://storage.googleapis.com/dlevin/dash_id3/manifest_id3_v0_no_data.mpd
**What did you do?**
Play a stream with emsg with empty message_data.
**What did you expect to happen?**
Working playback since according to the spec:

> message_data: body of the message, which fills the remainder of the message box. This may be empty depending on the above information. The syntax and semantics of this field must be defined by the owner of the scheme identified in the scheme_id_uri field.

Note that it works with:
http://reference.dashif.org/dash.js/v2.9.0/samples/dash-if-reference-player/index.html

**What actually happened?**
Playback error and following stack:

>   | shaka.media.StreamingEngine.parseEMSG_ | @ | streaming_engine.js:1780
>   | shaka.util.Mp4Parser.parseNext | @ | mp4_parser.js:233
>   | shaka.util.Mp4Parser.parse | @ | mp4_parser.js:161
>   | shaka.media.StreamingEngine.append_ | @ | streaming_engine.js:1740
>   | (anonymous) | @ | streaming_engine.js:1509
>   | Promise.then (async) |   |  
>   | shaka.media.StreamingEngine.fetchAndAppend_ | @ | streaming_engine.js:1507
>   | shaka.media.StreamingEngine.update_ | @ | streaming_engine.js:1247
>   | shaka.media.StreamingEngine.onUpdate_ | @ | streaming_engine.js:1103
>   | setTimeout (async) |   |  
>   | shaka.media.StreamingEngine.scheduleUpdate_ | @ | streaming_engine.js:2209
>   | mediaSourceEngine.init.then.then | @ | streaming_engine.js:885
>   | Promise.then (async) |   |  
>   | shaka.media.StreamingEngine.initStreams_ | @ | streaming_engine.js:875
>   | shaka.media.StreamingEngine.init | @ | streaming_engine.js:418
>   | shaka.Player.load | @ | player.js:779
>   | async function (async) |   |  
>   | shaka.Player.load | @ | player.js:676
>   | (anonymous) | @ | asset_section.js:323
>   | Promise.then (async) |   |  
>   | shakaDemo.load
> 
>

**Comment by theodab** [comment]
I have an experimental CL that handles `EMSG` boxes with empty message_data. Easy enough.

Shaka Player is also having trouble skipping the `MDAT` box, though. Looking at the range requests we are making, it seems like it's only downloading part of the `MDAT` box for some reason? Like, it doesn't download the last ~250ish bytes, and our mp4 parser tries to seek past the end of the data and errors. The DASH-IF reference player also downloads that range, so apparently that is intentional.

**Comment by TheModMaker** [comment]
The media segment is invalid.  The size of the `mdat` box is 265 bytes too large.  The `mdat` starts at offset 2517 and has a size of 0x00093aef, so it ends at 607428, which is 265 bytes larger than the file.  The 5 `emsg` boxes have a total size of 265, so it looks like your encoder is not accounting for that when it calculates the size of the `mdat`.

We will definitely support the empty data field; but we have to consider if we want to support this kinds of bad content or not.

**Comment by TheModMaker** [comment]
Actually I was incorrect, I didn't see the range requests.  Your `sidx` is incorrect.  @theodab  was correct and we aren't requesting the whole `mdat`.  The reason is because your `sidx` is slightly off, by 265 bytes.

The first entry in the `sidx` doesn't account for the 5 `emsg` boxes, so the `referencedSize` attribute is 265 bytes too small, so the first segment is too small.  This plays fine in a streaming situation since the browser will just append the segments one after another, but if you seek, you'll get a segment in the middle of where it should be.

**Comment by damienlevin** [comment]
Very good catch on the bad segment - I'll try to update that sample content I posted.
Also, by doing a quick look at the code there doesn't seems to be support for emsg version 1, is that correct ? If so, I'm happy to create a sample stream and open an issue.

Thanks.

**Comment by TheModMaker** [comment]
The `emsg` box is defined by the DASH spec in ISO/IEC 23009-1; from the 2014 version, I only see version 0 specified.  Could you provide a spec for `emsg` version 1?  And yes, you can file another issue for that, we don't support it.

**Comment by damienlevin** [comment]
Until I file a ticket with a sample stream, you can look at CMAF spec:  https://www.iso.org/standard/71975.html and https://www.iso.org/standard/68960.html
