### ISSUE TITLE
Persistence licences doesn't work

### ISSUE THREAD

**Issue by drobazko** [google/shaka-player#1551]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
2.2.8

**Can you reproduce the issue with our latest release version?**:
The problem is that with the latest version my legacy application doesn't work.

**Can you reproduce the issue with the latest code from `master`?**:
The problem is that with the latest version my legacy application doesn't work.

**Are you using the demo app or your own custom app?**:
No

**If custom app, can you reproduce the issue using our demo app?**:
No

**What browser and OS are you using?**:
Chrome 56 - Windows,
Chrome 56 - macOS 10.13.6

**What are the manifest and license server URIs?**:
ezdrm widevine

**What did you do?**
I'm trying to play DRM-ed DASH live stream via Shaka player.
The cofiguration I'm passing to Shaka player is:

```
    var widevineLicense = [
      'https://widevine-dash.ezdrm.com/proxy?pX=<app-code>',
      'username=' + window.flashvars.drmP3,
      'password=' + window.flashvars.drmP4,
      'contentId=' + window.flashvars.assetId
    ].join('&');

    this.player.configure({
      drm: {
        servers: {
          'com.widevine.alpha': widevineLicense
        },
        advanced: {
          'com.widevine.alpha': {
            'videoRobustness': 'SW_SECURE_DECODE',
            'persistentStateRequired': true
          }
        }
      }
    });
  };
```
**What did you expect to happen?**
I'm expecting that the license will be requested once via request 

> https://widevine-dash.ezdrm.com/proxy?pX=<app-code>&username=<user-name>&password=<password>&contentId=

 and then will be used from local storage.

**What actually happened?**
My application is just list of live channels with and without DRM. User can switch between live channels.
I'm expecting that the license will be requested once via http call above, persisted in browser, and then if user clicks on the same DRM-ed live channel, then no calls to retrieve the license will happen.

Appreciate your help guys.

**Comment by TheModMaker** [comment]
We don't support using persistent licenses for that, we only support persistent licenses when storing content offline.  If you use `shaka.offline.Storage` to store content offline, we'll use persistent licences to allow playing the protected content offline; but we don't support using persistent licences to avoid licenses requests between playbacks.

Note that `persistentStateRequired` is EME terminology that refers to what the CDM is allowed to do when we create it.  By stating that persistent state is required, the CDM can store information in files, but it doesn't actually refer to storing licenses offline; the licenses we request are still only streaming licenses.

This also may be a difficult feature to add since it is difficult to associate the new stream with the existing keys.  Even if the manifest is the same, the content may be different.  Also if the key IDs are the same, we still may not be allowed to use the same license due to policy requirements (the CDM may reject using the license with this content).  So it is usually best to always request a license for this content so we are sure that we get a license that works with this content.

(also I don't know if Chrome 56 supports persistent licenses, I think it is a newer thing on desktop.  Persistent state can be supported but persistent licences may not be supported)

**Comment by drobazko** [comment]
@TheModMaker, huge thank you for your detailed answer.
