### ISSUE TITLE
Live Dash with repeating 3 second periods lead to "cannot find segment" error

### ISSUE THREAD

**Issue by TheJohnBowers** [google/shaka-player#1552]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
2.4.3 from published app spot demo page
**Can you reproduce the issue with our latest release version?**:
Yes
**Can you reproduce the issue with the latest code from `master`?**:
Haven't tried
**Are you using the demo app or your own custom app?**:
Demo App
**If custom app, can you reproduce the issue using our demo app?**:
NA
**What browser and OS are you using?**:
Chrome Macos
**What are the manifest and license server URIs?**:
These following are unencrypted live dash streams, and as such they do not need a license server URI:

HANGING:
~3 second Repeating Loop
https://content.uplynk.com/channel/1dc8b01513994f568dea7e8c46db5c54.mpd

WORKING:
~4 Second Repeating Loop
https://content.uplynk.com/channel/246501a276064de9aecc345e8a6db84c.mpd

**What did you do?**
Playback works for the repeating 4 second stream, but hangs very quickly for the repeating 3 second stream with:

"cannot find segment: currentPeriod.startTime=11.946 lookupTime=2.987"

both seem to work reasonable well with exo player.

**What did you expect to happen?**
I tried fiddling with my manifest a few different ways, as I normally have 4096 on full slices.  So the templates all have duration 4096, but I couldn't come up with anything that would get Shaka to not hit this playback error reliably.  So I figured I would submit an issue to you guys and see if there was a change that was required in the player, or if perhaps there is something obvious I am not doing in the manifest in this case, but exo does seem to handle it and we have an internal player implementation that does as well.

The case is special in that my segments are normally 4.096 long and this 2.987 second long segment repeating over means the manifest never sees a slice that is actually the normal 4.096 seconds long.  So the template duration of 4096 is never seen.

**What actually happened?**
Stalled playback

**Comment by michellezhuogg** [comment]
Could you please test with our lately build https://nightly-dot-shaka-player-demo.appspot.com/ ?

**Comment by TheJohnBowers** [comment]
no difference

**Comment by TheJohnBowers** [comment]
It is extremely easy to reproduce by just using the manifest urls provided.

**Comment by michellezhuogg** [comment]
I'm able to reproduce it. We'll work on fixing this issue.

**Comment by joeyparrish** [comment]
Something odd is happening with this content.  Period IDs and start times are not stable across updates.  There appears to be some rounding error.  For example, in a test run this morning, I captured and analyzed 5 consecutive manifest updates:

| start times  | manifest 1 | manifest 2 | manifest 3 | manifest 4 | manifest 5 |
| --- | --- | --- | --- | --- | --- |
| period 1 | 0.000 | 0.000 | 0.000 | 0.000 | 0.000 |
| period 2 | **2.987** | **2.986** | 2.986 | 2.986 | 2.986 |
| period 3 | 5.973 | 5.973 | 5.973 | 5.973 | 5.973 |
| period 4 | 8.960 | 8.960 | 8.960 | 8.960 | 8.960 |
| period 5 | **11.947** | **11.946** | 11.946 | 11.946 | 11.946 |
| period 6 | 14.933 | 14.933 | 14.933 | 14.933 | 14.933 |
| period 7 | 17.920 | 17.920 | 17.920 | 17.920 | 17.920 |
| period 8 | **20.907** | **20.906** | 20.906 | 20.906 | 20.906 |
| period 9 | -- | 23.893 | 23.893 | 23.893 | 23.893 |
| period 10 | -- | -- | 26.880 | 26.880 | 26.880 |
| period 11 | -- | -- | -- | 29.866 | 29.866 |
| period 12 | -- | -- | -- | -- | 32.853 |

Between manifest 1 & 2, some of the period start times and IDs change slightly.  I think this may be confusing Shaka Player, because it sees them as new, separate periods from the first versions.  If you wait long enough, playback eventually starts working once those first few periods (and their doppelgängers) drop out of the manifest.

**Comment by joeyparrish** [comment]
Please see what you can do about the manifest stability.  Since the first few periods went away, I've had continuous playback at the live edge for 200+ manifest updates, so I expect we'll see the problem go away once you fix the IDs & start times.  Thanks!

**Comment by TheJohnBowers** [comment]
Oh tricky.... I thanks for having a look at this.   I have a fix I am going to deploy for this very shortly.  I figured it was possible that it was an issue with the manifest, but I am just couldn't see what it might be.
