### ISSUE TITLE
Widevine encrypted video not playing in demo shaka player

### ISSUE THREAD

**Issue by suchitht** [google/shaka-player#1573]
Installed shaka packager in linux server. Encrypted video using widevine encryption

packager in=myaudio.mp4,stream=audio,output=audio.mp4 in=myvideo.mp4,stream=video,output=video.mp4 --enable_widevine_encryption --key_server_url https://license.uat.widevine.com/cenc/getcontentkey/widevine_test --content_id 7465737420636f6e74656e74206964 --signer widevine_test --aes_signing_key 1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9 --aes_signing_iv d58ce954203b7c9a9a9d467f59839249 --mpd_output h264.mpd

The mpd file created was used to play in demo jw player(http://demo.jwplayer.com/developer-tools/http-stream-tester/?playerversion=8) opened in firefox browser(also tried chrome) The file path was given and the widevine url was set to https://license.uat.widevine.com/cenc/getcontentkey/widevine_test

(In firefox)The player showed:

    ERROR: 241011 - A network request was made without proper crossdomain credentials.

(In chrome) the player showed:

    ERROR: 240000 - Unknown shaka error; for more context we recommend checking the source error.

I tried demo shaka player too with custom asset. It asked manifest path, Custom license server and Custom license certificate URL(https://shaka-player-demo.appspot.com/demo/#lang=en-US;build=uncompiled). what to give as custom license server confused me and so I didn't go forward with it.

Can somebody help me?

**Comment by TheModMaker** [comment]
Please fill out the form in the issue template.  Note that we don't provide support for Shaka Packager or JW Player, you should talk with them if you have a problem with them.  Please test with the our hosted demo or a custom app using Shaka Player that you can share.  Specifically, we'll need the manifest URL (not a copy of the manifest) so we can reproduce the error.

From the Firefox error, it looks like a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) error, you should check to see the host or CDN you are using is setting the correct CORS headders.

Since it is encrypted content, you need to provide a license server URL, you can ignore the certificate URL.  Since you are using the `widevine_test` provider, you probably want <https://proxy.uat.widevine.com/proxy>.

If you still have a problem, please give us the following information:

-------

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**:

**Can you reproduce the issue with our [latest release version](https://shaka-player-demo.appspot.com/demo/)?**:

**Can you reproduce the issue with the [latest code from `master`](https://nightly-dot-shaka-player-demo.appspot.com/demo/)?**:

**Are you using the demo app or your own custom app?**:

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:

**What are the manifest and license server URIs?**:

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by suchitht** [comment]
I have created 2 encrypted files
http://192.168.172.74:8085/key/wide/h264.mpd
http://192.168.172.74:8085/key/wide2/h264.mpd

Both are not playable in the demo shaka player with https://proxy.uat.widevine.com/proxy

Error: Shaka Error NETWORK.HTTP_ERROR (http://192.168.172.74:8085/key/wide2/h264_master.m3u8,TypeError: NetworkError when attempting to fetch resource.,0)

**Comment by suchitht** [comment]
Have you read the FAQ and checked for duplicate open issues?:
**Yes, Error code 1002, about setting CORS. No idea on how to set CORS header**

What version of Shaka Player are you using?:
**v2.4.4 compiled release (https://shaka-player-demo.appspot.com/demo/#asset=http://192.168.172.74:8085/key/wide2/h264.mpd;license=https://proxy.uat.widevine.com/proxy;lang=en-US;build=compiled)**

Can you reproduce the issue with our latest release version?:
**I guess that was your latest version**

Can you reproduce the issue with the latest code from master?:
**NA**

Are you using the demo app or your own custom app?:
**using the demo app**

If custom app, can you reproduce the issue using our demo app?:
**NA**

What browser and OS are you using?:
**Firefox, Windows**

What are the manifest and license server URIs?:
**manifest**
http://192.168.172.74:8085/key/wide/h264.mpd
http://192.168.172.74:8085/key/wide2/h264.mpd
**license server**
https://proxy.uat.widevine.com/proxy

What did you do?
**created widevine manifest file using shaka packager, using server https://proxy.uat.widevine.com/proxy and tried to play the encrypted content on your demo app**

What did you expect to happen?
**decrypt the video file and play using the key server https://proxy.uat.widevine.com/proxy**

What actually happened?
**Instead of playing the file the app showed the error 1002**

**Comment by vaage** [comment]
@suchitht The manifest URLs you provided are local to you. We cannot use those to reproduce the issue.

Based on the information you have provided, Error 1002 is a HTTP error ([source](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html)). However with out a way to reproduce your issue there is not much I can tell you.

What I can suggest is:
1. Host the content where we can access it.
2. Try packaging the content without encryption to test if your setup is functioning as expected. If you can package the same content in the clear and play it back, then it means there is something wrong when you try to encrypt, but at least the scope of the problem has been narrowed down.

**Comment by TheModMaker** [comment]
Chances are this is either a CORS error or a mixed-content error.  You entered the url using `http`, but the hosted demo is accessed using `https`, so the browser won't load the content.  You have two options: host the manifest and media on a server using `https`, or host your own demo site and access it using `http`.

As for CORS errors, you can read about it here: <https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS>.  Basically you need to set special headers if the site accessing the content is at a different URL than the content you are trying to access.  Since the hosted demo is on a different domain, you need to set CORS headers for the manifest and segments so the demo can access it.  How you set the headers depends on how you are hosting your content, so look at the documentation for your server host.
