### ISSUE TITLE
Rejected with system code (18)

### ISSUE THREAD

**Issue by robertoviola** [google/shaka-player#1590]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
2.4.4
**Can you reproduce the issue with our latest release version?**:
Yes
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
Demo app
**If custom app, can you reproduce the issue using our demo app?**:
Yes
**What browser and OS are you using?**:
Raspbian Jessie and Raspbian stretch, Chromium browser 56
**What are the manifest and license server URIs?**:
https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd;lang=en-US;build=uncompiled
**What did you do?**
Load the asset and play the content
**What did you expect to happen?**
To play
**What actually happened?**
DRM_LICENSE_RESPONSE_REJECTED (Rejected with system code (18))
The player does not play the content since the license request is rejected.

**Comment by imalex** [comment]
Chrome 58 or earlier is no longer supported by Widevine.

**Comment by TheModMaker** [comment]
LICENSE_RESPONSE_REJECTED means the browser rejected the response we got from the license server.  My guess would be the old version of Chromium you're using doesn't support a new protocol the license server is using.  You should upgrade your browser.

**Comment by robertoviola** [comment]
@shaka-bot reopen

**Comment by robertoviola** [comment]
Actually I am using Qt5.9 which uses Chromium 56 as a runtime for the shaka-player. Do you know if there are any workaround for making a Qt5.9+Shaka-player solution to work? Or the only possibility is to change Qt for a newer version?

**Comment by joeyparrish** [comment]
The problem is that Chromium 56 is no longer supported by Widevine.  You will have to use at least Chromium 59.  According to the [Qt WebEngine documentation](https://doc.qt.io/qt-5/qtwebengine-overview.html#qt-webengine-core-module), the latest version is based on Chromium 65, so I would expect an upgrade to solve your problem.

As for a workaround, this is something that is completely outside of the player's control.  The Widevine CDM (the DRM client) in Chromium 56 is being rejected by the Widevine license server (the DRM server).  If that server will not accept requests from that client, we can't do anything to change that in JavaScript.

Does this answer your question?

**Comment by robertoviola** [comment]
Ok, thank you for the explanation.
