### ISSUE TITLE
Windows 10 - Chrome crashes while using shaka player

### ISSUE THREAD

**Issue by niralipatelgoogle** [google/shaka-player#1592]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: V2.4.4

**Can you reproduce the issue with our latest release version?**: V 2.4.4 is the latest stable relase

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**: demo app

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**: Windows 10 / Chrome 69.0.3497

**What are the manifest and license server URIs?**:
Sent via email

**What did you do?**
Play the above stream in Chrome with license server url. The stream will play but at some point the chrome will crash and and error will be displayed as: "Something went wrong while displaying this webpage." Sent screenshot via email for more details.

**What did you expect to happen?** The stream should play without any error.

**What actually happened?**
The browser crashes randomly. The issue is sporadic and not 100% reproducible.

**Comment by joeyparrish** [comment]
Is this a live stream?

Does it crash with dev tools open?

What about with dev tools closed?

I haven't reproduced with your content, but in the past, I have seen similar issues with live streams while dev tools is open.  It turned out in my case that the network panel of Chrome's dev tools was running out of memory.  So long as you are recording network traffic (on by default when you open dev tools), the payloads of those requests are kept in memory for inspection by dev tools.  So if you watch a 4Mbit/s HD stream, you will eat up 1.8GB RAM per hour.

Clicking on the red "recording button" in the network panel will turn off recording of network traffic.  If that doesn't help, please let us know, and we can take a look at your content.

**Comment by niralipatelgoogle** [comment]
The issue appears for VOD with live profile MPD. I tried to reproduce it by closing the dev tools window and it doesn't happen any more. So it must be the memory consumed by the network traffic as you have explained. Thank you for looking into this.

**Comment by joeyparrish** [comment]
Happy to help!  I wonder if it would be worth filing a bug on Chrome to ask that some limit be put on memory consumption in the network panel.
