### ISSUE TITLE
Why do shaka send 2 license request with PlayReady?

### ISSUE THREAD

**Issue by PatrikCarlander** [google/shaka-player#1618]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
Latest online demo shaka player.
**Can you reproduce the issue with our latest release version?**:
yes
**Can you reproduce the issue with the latest code from `master`?**:
not tried
**Are you using the demo app or your own custom app?**:
 demo app
**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Window 10 and Microsoft Edge 17.17134 
**What are the manifest and license server URIs?**:
I play the demo stream in demo player
Unified Streaming
Tears of Steel (PlayRead)

**What did you do?**
Play the stream debug with fiddler.
**What did you expect to happen?**
Shaka send 2 license request (this is PlayReady so it's not a certificate request)
**What actually happened?**
It should only send one license request

**Comment by PatrikCarlander** [comment]
Shaka v2.4.4

**Comment by chrisfillmore** [comment]
I don't have a Windows machine handy, but quick question: can you confirm the first request is not a preflight OPTIONS request?

**Comment by PatrikCarlander** [comment]
Yes it's actually 4 requests 2 OPTIONS and 2 POST.

**Comment by PatrikCarlander** [comment]
![fiddler](https://user-images.githubusercontent.com/5682260/47121508-30681680-d273-11e8-9cf9-f6f6868525c2.jpg)

**Comment by PatrikCarlander** [comment]
Here is the reason
shaka.media.DrmEngine.prototype.onEncrypted_ = function(event) {
let initData = new Uint8Array(event.initData);

first initData array is 1604 length.
second initData array is 802 length.
If you split first initData in 2 pieces, then both are equal to the second initData. 

Because Uint8ArrayUtils.equal(initData, this.activeSessions_[i].initData)
return false, Shaka do 2 license request with PlayReady with Edge.

We have to fix this because license request cost money.
I don't know why first initData is duplicated, maybe stream issue by Unified Streaming (duplicated data in first segment) or issue with Edge.
We using Unified Streaming and have same issues with our streams.

This fix it, but I only check first part. 
for (let i = 0; i < this.activeSessions_.length; ++i) {   
  let preInitData = (initData.length * 2 === this.activeSessions_[i].initData.length) ?      
    this.activeSessions_[i].initData.slice(0, initData.length) : this.activeSessions_[i].initData;    
  if (Uint8ArrayUtils.equal(initData, preInitData)) {
	shaka.log.debug('Ignoring duplicate init data.');
	return;
  } 
}

**Comment by TheModMaker** [comment]
I've confirmed that this happens.  This is probably a browser bug; Microsoft has a new key system that is better spec-compliant that (hopefully) won't have these kinds of issues.  You can read more in #1495.

Unfortunately we can't parse the PSSH data to dedup them like this.  This may work for PlayReady, but other key systems may require these duplicate entries.  For example, this won't work for Widevine which requires that multiple PSSH boxes be passed in as-is.  We could do this conditionally on PlayReady, but in light of #1495, I don't think we should add more workarounds when it does work as-is.

A workaround you could do is to add the init data into the manifest.  If your manifests have a `<cenc:pssh>` element, we will use that instead of the data in the media.  This will allow you to avoid the extra license request and will also initialize the sessions earlier instead of waiting for the `encrypted` event.

**Comment by joeyparrish** [comment]
Closing this stale external (non-Shaka) issue. If you disagree, please reply with @shaka-bot reopen, and it will be automatically reopened.

Follow #1495 for our eventual support of com.microsoft.playready.recommendation.
