### ISSUE TITLE
Shaka player does not provide key_ID to the Clearkey server

### ISSUE THREAD

**Issue by robertoviola** [google/shaka-player#1636]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
YES
**What version of Shaka Player are you using?**:
2.4.4
**Can you reproduce the issue with our latest release version?**:
YES
**Can you reproduce the issue with the latest code from `master`?**:
YES
**Are you using the demo app or your own custom app?**:
BOTH
**If custom app, can you reproduce the issue using our demo app?**:
YES
**What browser and OS are you using?**:
Firefox
**What are the manifest and license server URIs?**:
**Manifest:** https://storage.googleapis.com/shaka-demo-assets/angel-one-clearkey/dash.mpd
**Server 1:** https://cwip-shaka-proxy.appspot.com/clearkey?_u3wDe7erb7v8Lqt8A3QDQ=ABEiM0RVZneImaq7zN3u_w
**Server 2:** my custom Clearkey Server
**What did you do?**
Play the content with a custom Clearkey Server
**What did you expect to happen?**
The player send a POST request containing the key_ID retrieved from the PSSH inside the manifest.
**What actually happened?**
The player does not provide the key_ID when sending the POST request. It works with Server 1 because the player send to the server both key_ID and key through the URL query (_u3wDe7erb7v8Lqt8A3QDQ=ABEiM0RVZneImaq7zN3u_w), but does not work with Server 2 (my custom server).
Does it have sense that the player provide to the server both key and key_ID (it could play the content without requesting the server since it has all it needs to play)?
Why the player does not parse the manifest in order to send the POST request with the Key_ID?

**Comment by TheModMaker** [comment]
We don't parse PSSH data, we only send the data verbatim to the browser or the license server.  When we see a PSSH data in the manifest, we pass it to the browser; then it creates a license request (binary) which we send verbatim to the license server.

But from what I can tell, the license request does contain the key IDs.  The POST data is  actually just JSON data that contains the key ID.  For example, on the Shaka Player demo I see the POST data contain `{"kids":["_u3wDe7erb7v8Lqt8A3QDQ"],"type":"temporary"}`.  Here is a description of the [license request format](https://w3c.github.io/encrypted-media/#clear-key-request-format).

We include the keys in the URL to avoid having to hard-code these keys on our server, but you would normally parse the POST data and look up the correct key.  Note that normally the keys aren't available.  The reason we have the keys now is because it is in the license server URL, not in the media.  So generically we can't avoid the license request.

**Comment by TheModMaker** [comment]
Does this answer all your questions?
