### ISSUE TITLE
The player replaces the poster image with the first frame of the video for particular URIs

### ISSUE THREAD

**Issue by gldraphael** [google/shaka-player#1643]
The poster image gets replaced by the first frame of the video for specific URIs. Please check this JS Fiddle for a repro: https://jsfiddle.net/17cgays4/11/

We've generated the URIs using Azure Media Services. The URIs generated for a resource works like it should. However when using a [filter](https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-dynamic-manifest-overview) on the same asset, the player replaces the poster image with the first frame of the video. Everything else seems to work like it should.

-----

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.4.4

**Can you reproduce the issue with our latest release version?**: Yes   
**Can you reproduce the issue with the latest code from `master`?**: Haven't tried.   

**Are you using the demo app or your own custom app?**: Custom, doesn't matter though.   
**If custom app, can you reproduce the issue using our demo app?**: 

**What browser and OS are you using?**: Google Chrome 69.0.3497.100 (Official Build) (64-bit) / MacOS 10.14

**What are the manifest and license server URIs?**:
**Working URI:** `https://amplilymedia-usea.streaming.media.azure.net/38df02d2-ae86-449f-9bab-05a570e77758/5d3997b5-396c-40fd-a074-5ab0909a.ism/manifest(format=mpd-time-csf)`
**Failing URI:** `https://amplilymedia-usea.streaming.media.azure.net/38df02d2-ae86-449f-9bab-05a570e77758/5d3997b5-396c-40fd-a074-5ab0909a.ism/manifest(format=mpd-time-csf,filter=10MinuteTi-filter-1257a65813ef4e5aa5f2f352c94261f1)`   
(Clear streaming -- no licenses)

**What did you do?**    
**What did you expect to happen?** expected the poster image to stay   
**What actually happened?** the poster image got replaced

**Comment by theodab** [comment]
When the poster is and isn't drawn is a behavior of the browser, not Shaka Player. Specifically, the poster is drawn if the video is on the first frame and has not yet been played. The filtered manifest you provide doesn't feed in the first few segments, but the video element knows that they are there due to the timing data in the mp4 files... so the poster never draws.
That's on-spec behavior, by the way; see the [w3 spec on video elements](https://www.w3.org/TR/2011/WD-html5-20110113/video.html#video). I don't think they were thinking of your specific use case when they were designing it.

As far as what we can do about this...
1. We could re-package the incoming media files to change all of their timing data, so that the first segment passed in is now the actual first segment. That would be an impractically large change for this problem, though, and also might require preloading the entire video before playing (depending on how we do the re-packaging).
1. We could handle drawing the poster manually, instead of leaving it to the video element. This is probably the easiest solution, but adding new elements to the DOM is outside the purview of the core Shaka Player library.

Option number one there is almost definitely out of the question. Option number two... maybe. We'll consider it. For now, though, I'll mark this issue as external.

**Comment by TheModMaker** [comment]
The reason the poster stops being displayed in that asset is because there is a gap at the start.  When we start playing, we see the gap at the start and seek over it.  Because the time is no longer 0, the browser stops displaying the poster.

**Comment by joeyparrish** [comment]
Closing this stale external (non-Shaka) issue. If you disagree, please reply with @shaka-bot reopen, and it will be automatically reopened.
