### ISSUE TITLE
[app] How do I generalize my app for many videos?

### ISSUE THREAD

**Issue by shabab11** [google/shaka-player#1671]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

Have you read the FAQ and checked for duplicate open issues?:
yes

What version of Shaka Player are you using?:
2.3

Can you reproduce the issue with our latest release version?:
yes

Can you reproduce the issue with the latest code from master?:

Are you using the demo app or your own custom app?:
demo

If custom app, can you reproduce the issue using our demo app?:

What browser and OS are you using?:
chrome, windows 10

What are the manifest and license server URIs?:

What did you do?
I am able to play video and subtitles, download contents, add chapters. But all these I have done for one video. I tried to do this for many videos but I have to load manifest, create instances for each and every video again and again. I have tried to generalize the code so that I need not to do that again and again but it didn't worked.

What did you expect to happen?
I am expecting to play many video without changing the code every time. for an example if you are creating an application which may have millions of video under video on demand (VOD) you can not create millions of instances and make changes that many time. Do we need to automate in someway or is their any compliance issue so that its making harder to customize Shaka.

What actually happened?
Failed to do

**Comment by joeyparrish** [comment]
@shabab11, if you spend some time playing with our demo application, you will see that we have many, many videos with diverse features and configurations.  We host all of these in a single application, and we don't rewrite the application for each asset.

Can you please give us an example so that we can help you better?  If you can, please show two snippets of code for two different videos so that we can see how you have your code structured.  Then we can suggest another way to organize your code into a more generic video player.

You may also want to look at our demo app's code to see how we organize our assets.  I'll guide you through what we've done to solve this problem.

Our demo assets are described with metadata in demo/common/assets.js ([permalink](https://github.com/google/shaka-player/blob/6b1ca2d229b855e4064d7d13dc0918bd020eab43/demo/common/assets.js#L666)).  Here's a simplified version of what's in there:

```js
const testAssets = [
  {
    name: 'Angel One (multicodec, multilingual)',
    manifestUri: 'https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd',
  },
  {
    name: 'Multi-DRM, multi-key',
    manifestUri: 'https://media.axprod.net/TestVectors/v7-MultiDRM-MultiKey/Manifest.mpd',
    licenseServers: {
      'com.widevine.alpha': 'https://drm-widevine-licensing.axtest.net/AcquireLicense',
      'com.microsoft.playready': 'https://drm-playready-licensing.axtest.net/AcquireLicense',
    },
    licenseRequestHeaders: {
      'Foo': 'Bar',
    },
  },
];
```

Then, in demo/asset_section.js is the code that reads this metadata and configures the Player instance ([permalink](https://github.com/google/shaka-player/blob/master/demo/asset_section.js#L197)).  Here's a simplified version of that:

```js
function setupPlayer(player, asset) {
  // Add any standard config that is common across assets.
  player.configure('manifest.dash.clockSyncUri', 'https://shaka-player-demo.appspot.com/time.txt');

  // Add any specialized config for this asset.
  if (asset.licenseServers) {
    player.configure('drm.servers', asset.licenseServers);
  }

  // Configure network filters.
  if (asset.licenseRequestHeaders) {
    const networkingEngine = player.getNetworkingEngine();
    networkingEngine.registerRequestFilter((requestType, request) => {
      if (requestType != shaka.net.NetworkingEngine.RequestType.LICENSE) return;
      for (let k in asset.licenseRequestHeaders) {
        request.headers[k] = asset.licenseRequestHeaders[k];
      }
    });
  }
}
```

Does any of that help?

**Comment by shabab11** [comment]
@joeyparrish thanks let me work through again with my code and I will ;provide you the snippets if am unable to make it work. Can I borrow some time for the issue to be open lil longer if possible?

**Comment by joeyparrish** [comment]
Sure.  We will leave the issue open and tagged as "question".  You should have several days before anything automatic kicks in.

If the issue goes idle for many days, our bot will ping and ask if you still need help.  If it goes idle for many days after that, the bot will close it automatically.  If it is closed by the bot, the bot provides instructions on how you can ask the bot to reopen the issue for you.

**Comment by shabab11** [comment]
Sounds good...........thank you :)
