### ISSUE TITLE
Questions about widevine content.

### ISSUE THREAD

**Issue by cutekyu** [google/shaka-player#1697]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
I checked FAQ and duplicate issue, but I cannot find

**What version of Shaka Player are you using?**:
2.4.5 uncompiled

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:
Yse

**Are you using the demo app or your own custom app?**:
demo app

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
webos and using chrome broswer

**What are the manifest and license server URIs?**:

**What did you do?**
we are trying to port level3 widevine in webos. But we cannot play any more after 10 seconds. 
we made ES dump file which is "Angel One" content (multi code, multilingual , widevine) to check differerce with clear content.
There are  little difference in buffer header, other data is totaly same. 
clear content: ".. 00 00 00 01 41 9B 32 78 43 C9 94 C0 97 FF .."
widevine content: ".. 89 47 91 C3 E8 8D 8C BC 30 74 DD 6A C1 DD.."
In my opinion, we made dump file when decrypt was done, so it should same as clear content. 
But it's not same. 
Please give a advice. 

**What did you expect to happen?**
play well in whole content

**What actually happened?**
cannot play any more after 10 seconds

**Comment by TheModMaker** [comment]
> In my opinion, we made dump file when decrypt was done, so it should same as clear content.
> But it's not same.
> Please give a advice.

I don't know what you are referring to.  It should be impossible to determine the bytes of the data after decryption.  How are you getting the data?

Could you post a manifest and license server URL that reproduces your problem?  Does the content play on desktop Chrome?  Usually the video stops with no errors like that when we don't get the correct keys from the license server.  This happens when you use the wrong proxy, the proxy is setup incorrectly, or the `pssh` data in the manifest/media is incorrect.  But without having the content, it will be difficult to determine why it doesn't have the correct keys.

**Comment by cutekyu** [comment]
Thank you for your advice.
we resolved this issue.
The reason of this issue was my wrong code in Subsample Decrypt funtions in CDM.
Anyway, Thanks for your opinion.
