### ISSUE TITLE
Setting maxBandwidth to less than lowest bandwidth track plays highest bandwidth track

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#170]
If you have a track with multiple video variants, set the maxBandwidth property to less than the bandwidth of the lowest variant. (ex: if the lowest quality is 135000, set maxBandwidth to 100000). The player will then start fetching chunks from the highest quality available. Ideally if your restrictions are set below the level of the lowest variant, the player should start fetching the lowest quality videos chunks, not the highest.

**Comment by joeyparrish** [comment]
Good catch.  Essentially, the restrictions make it so that there are no usable tracks.  This isn't a scenario we had really considered, so we need to decide how we want the Player to behave if this happens.

In the mean time, at an application level, you should definitely not place external limits that result in all tracks being restricted and unusable.

**Comment by sanbornhnewyyz** [comment]
Yeah this is really low priority for us because we have no reason to set restrictions like this. It just seems like counterintuitive behaviour so I figured I'd report it.

**Comment by sanbornhnewyyz** [comment]
Quick update: With the latest change, it seems the behaviour is different now. Instead of playing the highest track it fails with cannot read property 'segmentIndexSource' of null.
