### ISSUE TITLE
UI looks different on IE

### ISSUE THREAD

**Issue by TheModMaker** [google/shaka-player#1709]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes

**What version of Shaka Player are you using?**:
master

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Demo

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
IE11 on Windows 10

**What are the manifest and license server URIs?**:
Any asset (but tested with first `Angel One (multicodec, multilingual)`).

**What did you do?**
Show controls.  May need to run `shakaDemo.localPlayer_.onBuffering_(true)` to show buffering spinner.

**What did you expect to happen?**
Controls should look the same as other browsers.

**What actually happened?**
- Seek bar and volume bar have a small height. (see also #1703)
- Play/pause button is smaller than other browsers.
- Buffer spinner appears outside pause circle and is impossible to see on black video.
- Buffer spinner isn't animating the same (it just spins, doesn't change size).
- Volume icon appears slightly clipped on the right side.
- Volume bar is black (instead of white) when full screen.

**Comment by joeyparrish** [comment]
The seek bar issue is covered in #1703.  The issues with the volume bar (clipped, disappears in fullscreen) are actually the same issue (range input styles are broken on IE).

The play/pause button resizing is broken on IE, but I think we should do away with it anyway.  The button size should be pure CSS in my opinion.

Since the resizing is broken on IE, this leads to the spinner being outside the button.  If you disable resizing of the button and spinner, you can see the same behavior on Chrome.  So we should just make the button's default size in CSS a tad bigger.

The CSS animation for the stroke on the SVG circle doesn't work on IE, and it sadly never will.  IE doesn't support animating that attribute.

Consolidated to-do list for this issue:
 - increase default play button sizing to encompass the spinner
 - fix IE-specific range input styling
