### ISSUE TITLE
Changing audio cause video buffer clear.

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1714]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.5.0-beta2

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**: Both

**If custom app, can you reproduce the issue using our demo app?**: Yes

**What browser and OS are you using?**:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 (Chrome 70 - Ubuntu 18.04)

**What are the manifest and license server URIs?**:
https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

**What did you do?**
Load the stream. Observe Buffer Info with getBufferedInfo(), change the audio language 

**What did you expect to happen?**
Only audio buffer is cleared. We only change the audio not the resolution.

**What actually happened?**
Audio and Video buffer are cleared

**Comment by TheModMaker** [comment]
How are you changing the audio language?  Are you using `selectAudioLanguage` or `selectVariantTrack`? 

I'm fairly sure it should work with `selectVariantTrack`, but if you are using `selectAudioLanguage`, it may not because of how we switch streams.  My guess would be that you do this early and ABR hasn't stabilized yet, so when we select a new track with the new preference, ABR selects a different video stream and so we clear the buffer.

**Comment by avelad** [comment]
I’m using selectVariantTrack

**Comment by TheModMaker** [comment]
It looks like when we clear the audio buffer, it triggers a seek to flush the media.  Because the audio buffer is empty, it is considered an unbuffered seek and we clear everything.  We shouldn't be doing this.
