### ISSUE TITLE
UI: play button is always hidden when video is playing

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#1749]
Regression introduced in 4f08dab.

Giving the button width does not automatically adjust it's height. The button ends up being left with height of 0.

**Comment by joeyparrish** [comment]
I was sure I tested this thoroughly, so this was confusing.  But I've just figured out how this happened.

During testing, I had made some changes to make it easier to play with the CSS in Chrome's debugger.  I wanted the play button and spinner to be on the screen all the time and highly visible, so that my real-time tweaks in the debugger would show up.  I had the following local diff that wasn't part of my commit:

```diff
diff --git a/ui/controls.less b/ui/controls.less
index 0367e0ac..f96b1b6a 100644
--- a/ui/controls.less
+++ b/ui/controls.less
@@ -50,7 +50,7 @@ See https://goo.gl/egXAJY for explanation of
 how CSS cascade rules work. */
 button.shaka-hidden,
 .shaka-hidden {
-  .hidden();
+  //.hidden();
 }
 
 button.shaka-displayed,
diff --git a/ui/less/spinner.less b/ui/less/spinner.less
index 24a2672c..b39bb3f2 100644
--- a/ui/less/spinner.less
+++ b/ui/less/spinner.less
@@ -40,7 +40,7 @@
 .shaka-spinner-path {
   /* Fall back for IE 11, where the stroke properties cannot be animated,
    * but the spinner still rotates. */
-  stroke: #202124;
+  stroke: red;
   stroke-dasharray: 20, 200;
   stroke-dashoffset: 0;
 
```

This made all hidden things shown, and made the spinner path bright red.

It turns out that my button-width change only worked in concert with this diff I was using for debugging.  Because I didn't retest after removing the debugging change, this regression was released to `master`.  :disappointed: 

Putting `display: none;` on the buffering spinner via `.shaka-hidden` makes the spinner take up no space, which is what causes the play button height to go to 0.  We could use `visibility: hidden` on the spinner instead, which would cause it to take up space while invisible, but this would also cause it to be rendered at all times.  On slow devices like a v1 Chromecast, wasteful animation rendering tends to be an issue.  [citation needed]

So I'm going to look for another solution.
