### ISSUE TITLE
Shaka Player History - HLS_COULD_NOT_PARSE_SEGMENT_START_TIME

### ISSUE THREAD

**Issue by vaage** [google/shaka-player#1764]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:

**What version of Shaka Player are you using?**:
Shaka Player v2.5.0-beta2-101-g7d7b0742-uncompiled (nightly)

**Can you reproduce the issue with our latest release version?**:
Yes

**Can you reproduce the issue with the latest code from `master`?**:
Yes

**Are you using the demo app or your own custom app?**:
Demo App (Nightly Uncompiled)

**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
Browser: Chrome 71.0.3578.98
OS: Linux

**What are the manifest and license server URIs?**:
Demo Asset: Shaka Player History (live, HLS)

**What did you do?**

1. Select "Shaka Player History (live, HLS)" from Asset list.
2. Press "Load"
3. Wait

**What did you expect to happen?**
Expected to see asset play.

**What actually happened?**
Playback did not start. Error throw `MANIFEST.HLS_COULD_NOT_PARSE_SEGMENT_START_TIME`

**Comment by TheModMaker** [comment]
The reason I added the "Why didn't we catch  this sooner" label was because a demo asset was failing and we may want to investigate ways of detecting this sooner.  We have talked about running an automated test to detect asset problems in the past, but all our assets aren't stable on all platforms.  Maybe start with Chrome Linux, since if it doesn't play there we probably shouldn't have it?

**Comment by joeyparrish** [comment]
Yes, I agree.  We already have an open issue internally on our test infrastructure to do this.
