### ISSUE TITLE
Question about the duplicated representation ID

### ISSUE THREAD

**Issue by hdodev** [google/shaka-player#1769]
Hi,

My question is about an old item "Failure with duplicate Representation ids #508" which is now restricted.
Can you please just confirm again the fact that having 2 Representations with the same ID is not legal from a DASH point of view, even if they are in 2 different AdaptationSets with different IDs?
My purpose is about the fact that from an XML point of view, it seems to be correct no?
Thanks in advance.

**Comment by theodab** [comment]
According to the MPEG-DASH ISO/IEC 23009-1:2014 (which is available [here](https://standards.iso.org/ittf/PubliclyAvailableStandards/c065274_ISO_IEC_23009-1_2014.zip)), in section 5.3.5.2, about a representation's id:
> The identifier shall be unique within a Period unless the Representation is functionally identically to another Representation in the same Period.

So having two representations with the same ID is only valid if those representations are the same. I don't think that we account for that case. If it's really important for you, submit a feature request and we'll consider it.
Otherwise, no, it's not valid. It might make sense from an XML point of view, sure, but the committee in charge of making the spec decided that it would not be valid behavior. It simplifies implementation for applications, as they can store representations in lists indexed by ID, among other things.

**Comment by hdodev** [comment]
Hi, and thank you very much for your answer.
In my case, the adaptations that contains a representation with same IDs are describing subtitles of different languages. 

Let me know if from your point of view it's something eligible to a new Shaka feature, or just an issue to be corrected in my side. Thanks in advance.

Example: With this, Shaka raise the critical error "Duplicated_representation_id"
...
<AdaptationSet id="6" mimeType="application/mp4" segmentAlignment="true" startWithSAP="1" lang="fra">...
<Representation id="SMPTETT-725" bandwidth="300000" codecs="stpp" />
</AdaptationSet>
<AdaptationSet id="7" mimeType="application/mp4" segmentAlignment="true" startWithSAP="1" lang="fra">...
<Representation id="SMPTETT-725" bandwidth="300000" codecs="stpp" />
</AdaptationSet>
<AdaptationSet id="8" mimeType="application/mp4" segmentAlignment="true" startWithSAP="1" lang="deu">...
<Representation id="SMPTETT-725" bandwidth="300000" codecs="stpp" />
</AdaptationSet>
...

**Comment by theodab** [comment]
You'll need to fix your content, yes. On live content, we need the representation id to know how to update properly; when adding in the changes from the new version of the manifest, it lets us know which representations from the old manifest correspond to which representations from the new manifest. If there are duplicate representation ids, we could end up combining representations together.

**Comment by hdodev** [comment]
Hi. Thanks again foir you answer. I sent a notification of the problem to the packager team.
The question is closed.
