### ISSUE TITLE
Should polyfill installation be done before checking browser support?

### ISSUE THREAD

**Issue by salmoro** [google/shaka-player#1775]
In tutorials/basic-usage.md it's stated:

> 4. Install Shaka's polyfills.
> 5. Check for browser support.

From a brief scan of the `polyfill` and `isBrowserSupported` code it's not apparent to me that one would be dependant on the other.
1. Is this accurate?
2. If the answer to 1 is yes then wouldn't it be more efficient to do it in the reverse order (`if (isBrowserSupported()) polyfill.installAll()`)?

**Comment by TheModMaker** [comment]
The polyfills install browser features we need to work.  Since those features don't exist on some browsers, we may incorrectly detect no support on some browsers.  For example, on IE11 we install a polyfill for EME, so we wouldn't detect encryption support until after polyfills are installed.

There is also a reverse example.  On Safari 8 there are unfixable bugs and we need to disable a feature so we say the browser isn't supported there.

**Comment by salmoro** [comment]
Okay then my assumption was inaccurate and I will always install polyfills before checking `isBrowserSupported()`. 
Thanks @joeyparrish and @TheModMaker
