### ISSUE TITLE
Store clear asset while playing

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1777]
Is it possible store a clear asset while playing it?

I want play a asset in multiples times, but i don't want store the asset previous the first play.

**Comment by vaage** [comment]
@avelad Thanks for asking. We currently do not have a "store-as-you-play" system. Doing something like this would require large changes in our architecture since the player is designed to know nothing about storage.

If this is something you feel is important, I would suggest opening a feature request with a full explanation of what you need and how you envision it working. If enough other people express interest in the feature, then @joeyparrish will look at when/where it would fit into our long-term strategy.

**Comment by avelad** [comment]
Only it's a question, your response it's enough. Thanks!
