### ISSUE TITLE
Playing encrypted videos without using any DRM scheme

### ISSUE THREAD

**Issue by doncorleone2019** [google/shaka-player#1780]
Hi,

We would like to play encrypted videos in Shaka player in Internet Explorer without using Playready DRM. But IE does not support ClearKey DRM.

Is there a way to play encrypted videos in Shaka player without using any DRM scheme?

We are encrypting the streams using ffmpeg using the following parameters:

`ffmpeg -i big_buck_bunny.mp4 -encryption_scheme cenc-aes-ctr -encryption_key <encryption_key> -encryption_kid <encryption_kid> encrypted_output_file.mp4`

**Comment by TheModMaker** [comment]
Short answer: No.  We only support playing encrypted videos using EME.  And IE only supports PlayReady through EME.

Long answer: We could technically request the keys and decrypt the media before passing to the browser.  Since the keys are in the clear, we can just handle the decryption ourselves.  We would need to do this to support #850.  But we have no plans on doing this soon.

Also note that ClearKey isn't that secure.  Since the keys are in the clear, it is trivial for someone to get the keys and decrypt the content.  To get the benefits of using encryption, you have to use a DRM scheme to protect the keys.

**Comment by doncorleone2019** [comment]
Thank you for your response!
