### ISSUE TITLE
Unexpected green background on video

### ISSUE THREAD

**Issue by macoybarayan** [google/shaka-player#1781]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5

**Can you reproduce the issue with our latest release version?**
No

**Can you reproduce the issue with the latest code from `master`?**
No

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Safari / MacOs

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://shaka-player-demo.appspot.com/demo/#asset=https://s3-ap-southeast-2.amazonaws.com/replay-encoded/Video/5_5c4e670216516/hls/play.m3u8;lang=en-US;build=uncompiled

**What did you do?**

**What did you expect to happen?**

**What actually happened?**
For chrome and firefox browser, it plays well and no problem. But on safari browser, it has green background on the video. 
![screen shot 2019-01-24 at 5 53 23 pm](https://user-images.githubusercontent.com/15721473/51815638-56369a00-22fd-11e9-8b5b-7a98de56cb6f.png)

**Comment by michellezhuogg** [comment]
Hello @macoybarayan , I am not able to reproduce your issue in Safari on Macbook. Did the green background appear with a specific version of Safari?

**Comment by michellezhuogg** [comment]
I was using the same version of Safari. And now it seems I don't have access to the content anymore.

**Comment by damianmiles** [comment]
Hi, I have just re checked this, and its the same issue on Safari. https://www.getreplay.com.au/video/GSE I am using 12:02 Safari. It doesn't appear on Chrome on Mac.

**Comment by joeyparrish** [comment]
There is no green background added by Shaka Player.  The green you're seeing would be an artifact of the decoder.  Since this doesn't show up with all content, I expect it's an incompatibility of some kind between the encoder and the decoder.

I would recommend you first check for updates to your encoding software.  Next, I would suggest you file bugs on both your encoding vendor and Apple Safari.

Unfortunately, this is an issue we have no influence over at the JavaScript level.  Sorry we can't do more to help!
