### ISSUE TITLE
Shaka playlist / preload

### ISSUE THREAD

**Issue by jkringen** [google/shaka-player#1800]
I know there have been a couple issues logged talking about a feature request that would allow a "preload" of a stream as a blob or buffer object, etc. But I'm not clear on where that all is right now.

We are trying to setup a video playback system that will allow us to smoothly and quickly transition from 1 video to the next without having to load the video on demand as we switch videos. Ideally, it would be nice if we could somehow preload stream data via a Shaka API call and then apply that buffer when we choose to play that video content. 

Is there any current way, by developing a custom extension for the Shaka player, or anything else you would suggest?, where we could have the player framework buffer stream data and then hold it somewhere temporarily until it is needed?

I have not taken time at all to look further into Shaka as far as customizing it or developing extensions/plugins, so I thought I'd pose the question here and see how possible something like this is with the current player.

Thanks!

**Comment by joeyparrish** [comment]
> Ideally, it would be nice if we could somehow preload stream data via a Shaka API call and then apply that buffer when we choose to play that video content.

That sounds exactly like our plan for preload, which is tracked in #880.  We will not be able to work on it until after some big refactors in v2.6, though, which we think will take us all of Q2 2019.  So you can expect preload some time in Q3.  I've just updated #880 with a similar note on the timeline.

There aren't many good options to get the same effect with today's Shaka Player.  Here is what I can think of off the top of my head:

1. Since Shaka currently requires a video element to begin loading content, you can create a second, hidden video element and associated Player instance (video2/player2 below).  You can call `load()` on the player2 while player1 is playing out the end of the current content.  When the current content ends (`ended` event from video1), you can hide video1 and show video2, call video2.play() and player1.unload().  This is probably your best bet, and it should work on desktop and mobile, but it probably won't work on every device (smart TVs, game consoles, other platforms which may only support one video element at a time).  If you're okay with this restriction, it's probably the most robust solution with today's Shaka Player.

2. For a single instance of Player, if content were cached in advance through any mechanism, you could reduce the load latency.  However, it is very tricky to guess or force what bitrate you'll be loading when you do call `load()`, so caching segments in advance may be infeasible.  Providing segments from cache also has the potential to skew bandwidth estimates, so we really don't recommend going this route in any case.  If you must go this route for some reason, we have guidance on how to make sure the Player knows which responses are coming from a ServiceWorker cache: https://shaka-player-demo.appspot.com/docs/api/tutorial-service-worker.html

3. You could do the same as in option 2 above, but by providing pre-cached responses through our networking plugins instead of a ServiceWorker cache.  The same issue with guessing or forcing bitrates applies, though.  I wouldn't recommend this, either.

**Comment by joeyparrish** [comment]
Does this answer your question?
