### ISSUE TITLE
Offline support on Ios browsers

### ISSUE THREAD

**Issue by macoybarayan** [google/shaka-player#1811]
Does shaka player support offline download on IOS browsers?

**Comment by theodab** [comment]
Shaka Player does not currently support iOS browsers at all; see issue #997. We hope to have that done by the end of March, but no guarantees. I don't know if downloading will also work then, offhand. According to MDN, [IndexedDB is supported on iOS](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API), so it'd be possible.

**Comment by joeyparrish** [comment]
iOS support for Shaka Player will be dependent on Apple's built-in HLS implementation.  This is because iOS does not support MediaSource.  Not only is MediaSource necessary for our JavaScript-based HLS implementation, but it is necessary for our offline playback support (both clear & encrypted).

So offline support on iOS will not be possible until Apple enables MediaSource on iOS.  Please file an issue with Apple to let them know that this matters to you: https://developer.apple.com/bug-reporting/

I have it on good authority that Apple will take this feedback into consideration.  When your issue is filed, please post a link or ID number here so that we can refer to it in future conversations with Apple on this topic.  Thanks!

**Comment by macoybarayan** [comment]
Ahh yes.. Thanks for the clarification. :)

Sent from Yahoo Mail on Android 
 
  On Sun, Feb 24, 2019 at 2:05 AM, Shaka Bot<notifications@github.com> wrote:   
@macoybarayan Does this answer all your questions? Can we close the issue?
