### ISSUE TITLE
Support for seamless multi-codec switching

### ISSUE THREAD

**Issue by PaulChira46** [google/shaka-player#1815]
Hi,

According to what I've read in other two opened issues (#1013 , #1071), my understanding is that currently there is no way to seamlessly switch between Adaptation Sets with different codecs during the playback, and the implemented logic still relies on the "best codec" selection during the load of the manifest.
Would it be possible to achieve this by somehow changing the player code, or it depends on MSE that still doesn't provide support for switching between codecs ? Or otherwise is the browser (we are using Microsoft EDGE) that currently doesn't provide support for it ?

We currently have an MPD manifest with two different Audio Adaptation Sets with same language, same role but with different codecs (ec-3, mp4a), different audio channels (2, 6) and different bandwidth.
We are trying to find a way in order to allow the user to select between the two audio tracks. I've looked inside the player code and it looks quite difficult to achieve this due to the Variant Tracks logic and dependencies with the chosen codec.
Do you have any suggestions in order to achieve this or currently there is no solution ?

Best Regards,

Paul

**Comment by TheModMaker** [comment]
We currently don't support changing codecs at all.  Once we start playing with a codec, we can't change it under normal circumstances.  But there is a new standard to allow switching between codecs that we could use on supported browsers, but we haven't implemented it yet.  See #1528.

If there is no browsers support for codec switching, we don't want to support switching because it would require tearing down the media stack and won't be seamless.

Also, as described in #1013, we will use the `preferredAudioChannelCount` setting to choose the initial audio stream.  So if you set it to 6, we'll choose the 6 channel audio initially; otherwise we will choose the 2 channel one.  But you'll be unable to change to a different codec after playback starts.

**Comment by PaulChira46** [comment]
Hi,

Thank you again for the feedback!
By now I've managed to change the "best codec" logic with the selection of a specific audio/video codec combination that is  driven by the user. 
Of course, this still requires reloading the manifest and it's not seamless but for now it is a good tradeoff.

BR,

Paul
