### ISSUE TITLE
How to get video to continually buffer

### ISSUE THREAD

**Issue by pineapplejoe** [google/shaka-player#1825]
We have video that is about 30 to 60 mins. I'd like the video to continually buffer at current or better quality. 

Is there a way to do this?

**Comment by vaage** [comment]
Hello @pineapplejoe, thanks for the question!

I know of two ways for you to achieve this behaviour:
 - Update the `minBandwidth` and `maxBandwidth` in the Abr config each time an adaptation event fires.
 - Create a custom Abr Manager. You could copy and modify our implementation `shaka.media.SimpleAbrManager`. This would allow you to dial-in your raising-bandwidth behaviour exactly as you need.

Does that help?

**Comment by pineapplejoe** [comment]
Sorry - I wasn't very clear.  I mean that I want buffering to happen continually.  Now it seems to buffer a little bit into the future and then it stops buffering.    

I dont want it to stop.  I want it to try and prefetch the entire thing.

I know that I can save the video explicitly but that is something you do before you watch.  I want to be able to start watching right away and never stop buffering.  

Does this make sense?

**Comment by theodab** [comment]
In that case, you can set `streaming.bufferingGoal` to `Infinity`, and it will buffer to the end of the video. Do note that this could result in the player wasting a lot of bandwidth if, say, the user changes languages or something, and the player ends up re-downloading everything. So probably not great on mobile.

**Comment by pineapplejoe** [comment]
> In that case, you can set `streaming.bufferingGoal` to `Infinity`.

Oh interesting.  

What quality level will be downloaded?  The current one or will it be variable as network capacity changes?

**Comment by theodab** [comment]
If network conditions change it will potentially adapt, yes. Since you are buffering a long time ahead, that might mean that a short dip in network bandwidth could lead to a few low-quality segments showing up minutes later.

**Comment by pineapplejoe** [comment]
cool.  thank you!

**Comment by joeyparrish** [comment]
It's also worth noting that an aggressive buffering goal won't work on all devices.  If we try to buffer more than the browser has memory to store, we will get a "quota exceeded" error, which we handle by reducing our buffering goal.

What's critical is that we reduce it multiplicatively.  So if we reduce to 90% of infinity... That's still infinity.  And so on, until we give up and fail playback.

So please don't use a buffering goal of infinity.  :-)

Instead, I recommend a goal of video.duration (after loading the clip, so that value has meaning) or some fixed value on the scale of the video duration (like 10 minutes, or 2 hours, or whatever).
