### ISSUE TITLE
Chrome Widevine CDM Deprecation

### ISSUE THREAD

**Issue by grantg182** [google/shaka-player#1831]
With the upcoming mass cull of Chrome CDM versions for Widevine, we will need to notify users that their Chrome version in unsupported.

Would we expect requestMediaKeySystemAccess to fail on unsupported versions of Chrome, or a DRM.FAILED_TO_GENERATE_LICENSE_REQUEST, or other?

Thanks.

**Comment by joeyparrish** [comment]
I'm not sure.  This is all still very new, and we have yet to run any tests to understand the new behavior.  As it was explained to me, though, I believe the rejection will happen at the license server.  An older Chrome version with a matching CDM will still be consistent on the client side, but license servers will (by default) reject requests from those clients.  I believe there will be a way for Widevine servers/proxies to override this behavior and permit older clients, but I don't know what it is yet.

**Comment by chrisfillmore** [comment]
If I've understood correctly it sounds like the Widevine server will return an error. So your license proxy should be configured to understand that error and send an error response back from the license request. Sending an error response back will cause Shaka to publish 6007 LICENSE_REQUEST_FAILED. Your client app should inspect this error to determine if the failure is because the user's Chrome CDM is out of date.

**Comment by joeyparrish** [comment]
@chrisfillmore, that all sounds right to me.

**Comment by joeyparrish** [comment]
@grantg182, does this answer your question?

**Comment by grantg182** [comment]
@joeyparrish yep, that'll do it. Will look into a solution shortly and *hopefully* it'll do the trick when the time comes. Thanks @chrisfillmore !
