### ISSUE TITLE
Live streaming - Static mpd to dynamic mpd

### ISSUE THREAD

**Issue by saibalaji10** [google/shaka-player#1832]
For my project, I want to use segments that are of different sizes. I am using FFmpeg for this case. 

I'll be encoding the video with a segment size of 2 seconds and when the client requests to increase the size, I'll end the current process and encode the video with the segment size of two.

Can shaka player support this use case, I guess this is similar to VOD. 

I am facing difficulty in this. When the MPD changes from dynamic to static, the video stops requesting the MPD again (Hence plays as a stored video, not live)and when I am trying to start encoding again, there is no change in the video(Behaves as stored video).

I want Shaka to check the MPD again whether it is static or dynamic, even after the MPD becomes static,

**Comment by joeyparrish** [comment]
If your MPD *may* need to be refreshed, you should always mark it as dynamic.  This will ensure that the client will refresh when required.  A VOD clip can still be dynamic without any issues.

You can use `minimumUpdatePeriod` to ask us to refresh periodically, or you can omit this property, signal an `<InbandEventStream>` with the appropriate schema, and embed an `emsg` box in the content to trigger a manifest refresh only when necessary.

Does this answer your question?

**Comment by saibalaji10** [comment]
> If your MPD _may_ need to be refreshed, you should always mark it as dynamic. This will ensure that the client will refresh when required. A VOD clip can still be dynamic without any issues.
> 
> You can use `minimumUpdatePeriod` to ask us to refresh periodically, or you can omit this property, signal an `<InbandEventStream>` with the appropriate schema, and embed an `emsg` box in the content to trigger a manifest refresh only when necessary.
> 
> Does this answer your question?

Once I stop the encoding process with FFmpeg, the MPD changes from dynamic to static. I'll start the encoding process again. The MPD is dynamic now. Shaka is not identifying this state(1.It identifies when the MPD goes from dynamic to static but not when it is changing from static to dynamic). I want the second one for my use case. The minimum update period will not be in static MPDs. 

In my case, I'll rewrite the same MPD with the same name for the second process. I tried leaving out the `MediaPresenationDuration` and changing the MPD to `dynamic` in shaka-player.compiled.js.

But the player stops playing when the first segment of the next encoding process starts without showing any error.

**Comment by joeyparrish** [comment]
> Once I stop the encoding process with FFmpeg, the MPD changes from dynamic to static. I'll start the encoding process again. The MPD is dynamic now. Shaka is not identifying this state

That's because static manifests don't get refreshed, according to the spec.  They are static: they don't change.  So if you expect them to change, you need to make sure they don't get labeled as "static".  If you can't get this from ffmpeg, you can either put another layer in between ffmpeg and delivery to the client, or you can ask for support from ffmpeg to control this behavior, or you can patch ffmpeg to do what you want.

But fundamentally, if the manifest says "static", we don't refresh it, because you've told us not to by putting "static" in it.  This is working as intended.

**Comment by saibalaji10** [comment]
Yeah, you are right. It is working as intended. But in my use case, the MPD changes from static to dynamic and I want the player to do a single check to find the change(Static to dynamic), and then load the segments which are getting updated in the MPD.

I tried doing this but the player hangs without showing any error, after fetching the MPD(ie. Before loading the segments).

Is there any solution for this ?

**Comment by vaage** [comment]
@saibalaji10 I am sorry that your use-case does not naturally work with our model. Our parsers are meant to follow spec and it sounds like your situation may be out-of-spec.

Content is not meant to go from static to live. Live content has a method of signaling the player when it should check for an update, static content does not have this.

In your use-case, where is the update signal ("to do a single check to find the change") coming from?

**Comment by saibalaji10** [comment]
In my use case, once I start the encoding process again with FFmpeg, the same MPD file will change from static to dynamic. 
Hence, I need a single check after some **time** (say 500ms), so that the file changes from static to dynamic again, and the normal process of dynamic MPD will continue.

**Comment by vaage** [comment]
In your use-case, how will FFmpeg signal to the player(s) that it re-started the encoding process?

**Comment by saibalaji10** [comment]
> In your use-case, how will FFmpeg signal to the player(s) that it re-started the encoding process?

This is what I am missing right now. FFmpeg cannot signal the player. Hence I need the player to check the MPD again so that It can find that FFmpeg re-started the encoding process.

Will that be possible?

**Comment by vaage** [comment]
I will need more information before I can help. I don't understand how the each part of your project is working together. In your original post you said:

> when the client requests to increase the size

This makes it sound like the player and server have a 1-to-1 relationship and are talking with each other. Could you explain to me how the various parts of your project are communicating with each other and what they are saying to each other?

**Comment by saibalaji10** [comment]
Yes, let me give a low-level overview of my project. 

I have a client which constitutes of Shaka player and a server(Java Jetty HTTP/2 Server) which runs FFmpeg commands.

First, the server will initially start the encoding process with a segment size (say 1 second). 

The client which has the Shaka player will play the segments and based on certain conditions, the client will request the server to generate segments with a different segment size(Say 2 seconds).

For this, I have to stop the encoding process(Now the MPD changes from dynamic to static). The server will start the encoding process again with a new segment size(MPD changes from static to dynamic). This is where I need Shaka to recheck the MPD and start the routine for dynamic MPD again. This is where I am stuck now.

**Comment by vaage** [comment]
Thanks @saibalaji10, I think I have a better understanding, please tell me if this summary of the problem is accurate:

> In this project, the server is hosting a live stream and can change the segment size mid-stream (as requested by the client). When the server terminates the FFMPEG process, FFMPEG changes the manifest from LIVE to VOD. When Shaka Player sees that the manifest is VOD, it stops checking for manifest updates, preventing it from resuming the stream once encoding resumes.

**Comment by saibalaji10** [comment]
Yeah @vaage, you are right.

**Comment by vaage** [comment]
So @saibalaji10 there are a couple recommendations I can make,

- You could change how you serve the MPD. Your web server could refuse the server the VOD copy of the asset and only server the LIVE copies. This would require a change to your web server code.
- You could create a copy of our [DASH Manifest parser](https://github.com/google/shaka-player/blob/master/lib/dash/dash_parser.js), change it to treat all DASH manifest as LIVE manifests, and register it via our manifest parser plugin system ([tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-manifest-parser.html)). 

Either way will require some effort on your part, but these would be the two options I could consider if I was in your shoes.

Does this help?

**Comment by saibalaji10** [comment]
Thank you @vaage, the second option seems good. Will work on it.

Thank you for your help.

**Comment by TheModMaker** [comment]
Also note that when you start the encoding process again, you'll need to have the new segments start after the ones from the previous manifest.  It is possible for FFmpeg to start segment times at 0 or some other arbitrary time, which will cause problems.  Also, you can't change the `availabilityStartTime` after playback has started; so if the new manifests have a new value it will cause problems.  You also need to encode the same content as before since you can't change things like stream resolutions, codecs, codec settings, etc.

Are you using `SegmentTemplate` with `duration` or are you using `SegmentList`?  If you change the segment size, it will likely cause problems if you are using the `duration` attribute in the manifest.

**Comment by saibalaji10** [comment]
Hello @TheModMaker,  I am using `SegmentList`. I am encoding the same content. 

I have made some changes in the manifest parser. The only problem I am facing right now is : 

Consider the situation where the encoding is done till 25th segment ( ie. chunk-stream0-025.m4s). 

When FFmpeg stops the encoding for this segment size and then restarts the process, the segment index for the new segment size starts from 1 again( ie. chunk-stream0-001.m4s).

Shaka now starts fetching the segments only after the 26th segment and it leaves all the segments from 1st to 25th.

**Comment by saibalaji10** [comment]
> Hello @TheModMaker, I am using `SegmentList`. I am encoding the same content.
> 
> I have made some changes in the manifest parser. The only problem I am facing right now is :
> 
> Consider the situation where the encoding is done till 25th segment ( ie. chunk-stream0-025.m4s).
> 
> When FFmpeg stops the encoding for this segment size and then restarts the process, the segment index for the new segment size starts from 1 again( ie. chunk-stream0-001.m4s).
> 
> Shaka now starts fetching the segments only after the 26th segment and it leaves all the segments from 1st to 25th.

The playback is paused till the player fetches the 26th segment

**Comment by saibalaji10** [comment]
As the latest update:

Tried modifying the Segment_Index, Segment_List.js, Now I am able to fetch all the segments in between (In the given example, It is 0th to 25th). But as soon as I start re-encoding, parameters like `End in bufferData.video[0] ` turns to 0. I guess the video time is being reset. Shaka appends only the 26th segment into the buffer and the play resumes here. Others are being fetched only but not appended. Is there any solution for this?

**Comment by TheModMaker** [comment]
Like I said, the new segments need to appear after the old ones.  What is happening is FFmpeg starts over at 0.  When you start the encoding again, the new segments start at 0 and we think they are the same as the ones we already have.  And once we append them to the `<video>`, the new segments appear at the wrong time.

My guess is that it is impossible to do what you want without a custom packager.  The new segments from the new manifest need to start after the segments from the previous manifest and FFmpeg has no way of knowing when that is.

Just to be clear, here is what is happening: your previous manfiest says it has segments from 0:30-2:00, then we get a manifest update with the new manifest and it has segments from 0:00-0:45.  We normally will just ignore them since we already have those segments in the index, but if you append the first segment from the new manifest it will appear at time 0:00, not 2:00 like you want.  There is no way to change this since this is expected behavior; the manifest says it starts at 0 seconds so that's where we put it.

I also suggest you take a look at [this doc](https://github.com/google/shaka-player/blob/master/docs/design/dash-manifests.md) for more info on the presentation timeline and why this happens.

**Comment by TheModMaker** [comment]
One idea for this to work is to have a proxy on the server to intercept the manifest and edit it before giving it to the client.  This only works if FFmpeg encodes the segments starting at 0.  You can check this by playing the manifest and checking `video.buffered.start(0)` at the beginning.

When you start playing, just serve the manifest as-is.  Make sure to not serve the "static" version; if you set retry parameters in the Player you can just return a 400 response and we'll retry and you should have the new "dynamic" version by then.  Once you get a request to change the segment size, you'll be changing the manifest to change its `Period@start` time.  The attribute should be 0 or not present from FFmpeg.  You need to set this value to the media time that the transition happens.  So if you changed segment times at 2:30, then set the `Period@start` to "PT2M30S" ([format](http://www.datypic.com/sc/xsd/t-xsd_duration.html)).

This will adjust the new content to be later in the timeline so the new content you're encoding will be adjusted to the correct time.  The server will need to remember the adjustment and return the same value for each request.  If you get another request to change the segment times, add that time to the amount of content you've generated since the last time.

**Comment by saibalaji10** [comment]
<img width="542" alt="Screenshot 2019-03-12 at 8 30 06 AM" src="https://user-images.githubusercontent.com/38804730/54171729-6798c780-44a1-11e9-80de-52ded30fac31.png">
<img width="543" alt="Screenshot 2019-03-12 at 8 30 27 AM" src="https://user-images.githubusercontent.com/38804730/54171730-6cf61200-44a1-11e9-8255-f5caa2ebdec9.png">
<img width="564" alt="Screenshot 2019-03-12 at 8 32 09 AM" src="https://user-images.githubusercontent.com/38804730/54171731-6cf61200-44a1-11e9-8733-ad7d569a75c9.png">

I have attached the screenshots from the console.

First, the video.buffered.start has one element(Pic 1) and then it becomes two once I start re-encoding(Pic 2). The segments are not appended in the buffer during this time. Then again video.buffered has one element and then the segments get appended to the buffer and the video starts playing(Pic 3).

**Comment by joeyparrish** [comment]
@saibalaji10, what you are doing is non-standard.  We can't continue to offer support for this.  If you can modify Shaka Player to get the effect you want from this non-standard arrangement, then please do.  It's open source, and you make any changes you like in your fork.  But our support resources are limited, and we have to draw the line somewhere.  We've chosen the DASH InterOp Points (IOP) to define what we can and can't invest time in.

Instead, let us try to recommend a standards-based solution that we *could* support.

It seems that ffmpeg's manifest output is not able to express what you are trying to do.  This makes sense, because ffmpeg has no state to span the change in segment size.  You're starting ffmpeg again, and it believes (correctly) that the stream has started over.

One option could be to modify ffmpeg in some way to get output consistent with your unique use case.  For example, you could make ffmpeg always output type=dynamic.  Or you could modify ffmpeg to allow you to change the segment size on-the-fly.  Or you could build your own application with libavcodec, libavformat, etc instead of using the ffmpeg command line front-end.

Another option would be to have ffmpeg output segments and use a separate DASH packager to output the manifest.  What you are doing maps *very* well onto multi-period DASH.  Each time you change the segment size, ffmpeg starts over at zero, and your packager creates a new period that stitches onto the end of the previous one.  Each period has an internal timeline independent of the others, so ffmpeg is free to start over without any state from before.

I *strongly* recommend that you investigate multi-period DASH for this.  I think it will save you a lot of trouble in the end, it's standards-based, and or doesn't involve modifying ffmpeg or Shaka Player

**Comment by saibalaji10** [comment]
Thank you for your support @joeyparrish. This is very helpful
