### ISSUE TITLE
Why playback rate is changed to 0 when buffering?

### ISSUE THREAD

**Issue by odedhutzler** [google/shaka-player#1836]
Hi,

What is the purpose of changing `playbackrate` to `0` when the video buffers?
https://github.com/google/shaka-player/blob/7148354aaba336f7eb827aa7d591e1fe20ca4397/lib/media/video_wrapper.js#L144

Thanks,

Oded

**Comment by joeyparrish** [comment]
To get consistency across browsers, Shaka Player does not detect when the browser goes into a buffering state.  Instead, it manages buffering state explicitly at the player level.  When the buffer runs low, it interrupts playback.

To do this, we had two basic options: `.pause()`, or `.playbackRate = 0`.  We found that setting `playbackRate` to 0 was less disruptive because it allowed applications & users to manage play/pause state independent of buffering state.

In discussions with colleagues at Chrome & YouTube, though, it has recently come to my attention that we should re-evaluate this strategy.  By preventing the browser from completely underflowing, we inhibit the browser's ability to instrument buffering on its own.

So this behavior may change in the future.  More research is needed.

Does this answer your question?

**Comment by odedhutzler** [comment]
@joeyparrish yes, thanks for the detailed explanation.
