### ISSUE TITLE
Nightly demo produces NO_VIDEO_ELEMENT after a failed load

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#1843]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
master

**Can you reproduce the issue with our latest release version?**
no - does not affect v2.4.7 or v2.5.0-beta3

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo app

**What browser and OS are you using?**
ChromeOS 72, but it happens on desktop Chrome, too

**What are the manifest and license server URIs?**
Any that produce an error during loading.

**What did you do?**

1. Load anything that will fail to load, such as the URL "foo": https://nightly-dot-shaka-player-demo.appspot.com/demo/#asset=foo;lang=de;build=uncompiled
2. Then click load again

**What did you expect to happen?**
The same `NETWORK.BAD_HTTP_STATUS (https:foo,404,,[object Object],0)` error both times, as happens on v2.5.0-beta3 and v2.4.7.

**What actually happened?**

The second load results in the error `PLAYER.NO_VIDEO_ELEMENT ()`.  It seems that something is wrong with the latest load graph changes.

Changing to another asset that should work still results in `NO_VIDEO_ELEMENT`.  So it seems that the first error put the `Player` into an unrecoverable error state.

**Comment by vaage** [comment]
This issue is on my radar, there is a TODO in the `handleError` method in `shaka.Player` with all the information needed to fix the issue.

Because I know that reloading the page each time an error occurs can interrupt one's workflow, I can't image we would want this to issue to remain open for longer than necessary. Since I am out of the office until Monday, I would invite anyone interested in helping out to read the information in the TODO and resolve the issue.

**Comment by joeyparrish** [comment]
Awesome, thanks @vaage!

**Comment by kevinscroggins-youi** [comment]
I can confirm that I am also seeing this on Tizen as well, possibly after creating additional player instances.
