### ISSUE TITLE
HLS variant wrongly guessed as video (it is audio)

### ISSUE THREAD

**Issue by fadomire** [google/shaka-player#1850]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.0-beta3

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Mac with Chrome and Safari

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
sent via email

**What did you do?**

load manifest in demo app

**What did you expect to happen?**
content play with video and audio

**What actually happened?**
only audio is playing
no video

apparently the "guess audio" / "guess video" part of the code is not working for our manifest
it wrongly guess that an audio only variant is a video variant
as a side effect, when choosing best codec, it removes all the video codec and only keep mp4a audio ones

maybe our manifest dont respect best practice i don't know

thanks

**Comment by vaage** [comment]
@fadomire I have looked into your content and it appears to be using TS. Because many browsers do not support TS natively, we integrate with MuxJs to transmux content from TS to Mp4.

Using Chrome on Linux and OSX, I have traced through the code and have found the following this:

- `Player` knows this is audio-video content. Calling `player.isAudioOnly()` will return `false` and I even verified this by going through the filtering code and sure enough the output is a variant with an audio and video stream.
- `StreamingEngine` is initialized to stream both audio and video streams.
- `MediaSourceEngine` is initialized to play both audio and video streams and creates the transmuxer for both streams.
- `MediaSourceEngine` is transmuxing content from TS to MP4 and appending it to `MediaSource`.

With media source initialized for audio and video, if either stream was not appending data, the player would stall, it is not doing this, so we should be able to assume that data is being consumed by media source. How "empty" frames are being appended, I don't know. But base on the above, I can't find anything wrong with Shaka Player.

I checked if you content would play with `src=` in Safari, and it does. My thoughts are that MuxJS may not support your content and is providing empty frames.

Since MuxJS is not something we own, I would suggest spending some time looking into that. If there is a configuration option that allows it to work with your content, I am sure we can provide a channel to configure MuxJS via the `Player.configure()`.

**Comment by fadomire** [comment]
Thanks for the detailed check and explanation. There is still some things i dont get.

From what i understood the manifest contains 6 different variant
BANDWIDTH=282000,CODECS="mp4a.40.2,avc1.42C01E",RESOLUTION=416x234
BANDWIDTH=563000,CODECS="mp4a.40.2,avc1.42C01E",RESOLUTION=480x270
BANDWIDTH=775000,CODECS="mp4a.40.2,avc1.42C01E",RESOLUTION=640x360
BANDWIDTH=1409000,CODECS="mp4a.40.2,avc1.4D401F",RESOLUTION=1024x576
BANDWIDTH=69000,CODECS="mp4a.40.2"
BANDWIDTH=137000,CODECS="mp4a.40.2"

when i check in demo app with debug enabled, i see that the ```chooseCodecsAndFilterManifest_``` remove the 4 first and leave only the 2 last

sorry if this seems confused, i admit i'm missing some knowledge there

**Comment by vaage** [comment]
You are seeing the next step in filtering; the single codec filter. We filter variants so that we only have variants that we can safely adapt between without re-initialize the media pipeline.

We then group variants by which codecs they use, and then pick the group that will most likely yield the best user-experience. By the end of this process, there are only two variants we can play.

**Comment by fadomire** [comment]
ok so maybe our manifest should provide more variant with codec mp4a.4.2
cause it seems we are missing on high resolution variant here no ?

**Comment by vaage** [comment]
If you wanted to ensure a consistent quality of experience across the different codecs, I would recommend having the same resolutions available across the different codecs.

One a similar note, MP4 in HLS is supported by Shaka Player. If possible, using mp4 for audio and video would allow you to avoid trans-muxing on non-ts platforms.

**Comment by fadomire** [comment]
Thanks for all infos

**Comment by fadomire** [comment]
after some more investigations, i would still need some more guidance from you if possible

we are packaging our HLS manifest with Unified Streaming
http://docs.unified-streaming.com/

in the manifest i sent you, as a result, we expect to at least have the following variants : 
1. RESOLUTION=416x234, AUDIO="audio-aacl-64", NAME="Audiodescription", LANGUAGE="fr"
2. RESOLUTION=416x234, AUDIO="audio-aacl-64", NAME="Français", LANGUAGE="fr"
3. RESOLUTION=416x234, AUDIO="audio-aacl-64", NAME="English", LANGUAGE="en"
4. RESOLUTION=480x270, AUDIO="audio-aacl-128", NAME="Audiodescription", LANGUAGE="fr"
5. RESOLUTION=480x270, AUDIO="audio-aacl-128", NAME="Français", LANGUAGE="fr"
6. RESOLUTION=480x270, AUDIO="audio-aacl-128", NAME="English", LANGUAGE="en"
7. RESOLUTION=640x360, AUDIO="audio-aacl-128", NAME="Audiodescription", LANGUAGE="fr"
8. RESOLUTION=640x360, AUDIO="audio-aacl-128", NAME="Français", LANGUAGE="fr"
9. RESOLUTION=640x360, AUDIO="audio-aacl-128", NAME="English", LANGUAGE="en"
10. RESOLUTION=1024x576, AUDIO="audio-aacl-128", NAME="Audiodescription", LANGUAGE="fr"
11. RESOLUTION=1024x576, AUDIO="audio-aacl-128", NAME="Français", LANGUAGE="fr"
12. RESOLUTION=1024x576, AUDIO="audio-aacl-128", NAME="English", LANGUAGE="en"

when i check the demo from hls.js with our manifest it returns 6 possible audio tracks and 4 possible resolutions
https://video-dev.github.io/hls.js/demo/

could you give it a try and let us know why shaka implementation differs ? i feel my skills gets to their limits, but i'm learning

side note : i dont really understand why you are saying in other issues that TS chunks are only supported natively on Edge and Chromecast and why we need mux.js on Safari mac, when putting the manifest in native video tag src, on Safari Mac it gets played properly, playing video and audio. and even when we check video.audioTracks it returns the 3 language we expect (fr, fr-audio-desc, en)

**Comment by vaage** [comment]
@fadomire I will try my best to isolate each of your questions and address them one-by-one. For this I will quote what I understand the question to be, followed by an answer.

> Why does Shaka Player require mux js on some platforms?

MediaSource tells us what codecs are supported on what platforms, we do not hard code this information, we query the system for it. In browsers, the src= and media source solutions are often separate solutions. It is common for one to support something while the other does not.

> Why does Shaka Player report two languages when Native Src= on Safari reports three languages?

The reason Shaka Player reports two languages ("fr" and "en") is that there are only two languages reported via the LANGUAGE params. We do not know why Safari reports data for language that comes outside of the LANGUAGE params.

> Why are there not 12 variants?

By the time we are done parsing the manifest and give it to the player, we have dropped the audio streams with the name "Audiodescription". This can be seen by no audio stream has the label "Audiodescription". This leaves eight variants initially being in the manifest. By the time we start playback this has been filtered down to 2 variants because it is looking at common codecs (see my comments from earlier).

> Where are there "Audiodescription" streams going?

The "Audiodesription streams are being dropped by the HLS parser because they are missing an uri. Having a uri is a requirement for the parser to understand audio streams.

@fadomire, does this answer your questions?

**Comment by fadomire** [comment]
@vaage thanks
> Why does Shaka Player require mux js on some platforms?
very clear. MediaSource does not support TS without transmuxing. Direct src= does.

> Why does Shaka Player report two languages when Native Src= on Safari reports three languages?
indeed there is only 2 language. And when i said Safari Native src= report 3 languages, it is not really true. i was refering to the Web audioTracks API that return the following
0: AudioTrack {id: "0", kind: "description", label: "Audiodescription", language: "fr", enabled: true, …}
1: AudioTrack {id: "1", kind: "main", label: "English", language: "en", enabled: false, …}
2: AudioTrack {id: "2", kind: "main", label: "Français", language: "fr", enabled: false, …}
so Shaka is correct to report 2 languages

> Why are there not 12 variants?
> Where are there "Audiodescription" streams going?
when i force URI on our "Audiodescription" #EXT-X-MEDIA then it appears properly !
but i thought URI was not mandatory per HLS spec
specificaly, in our case the doc says
> When its URI attribute is omitted, the EXT-X-MEDIA tag can indicate that the media described is included in the URI of the EXT-X-STREAM-INF tag.
source : https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming/adding_alternate_media_to_a_playlist

also with forced URI in our manifest we still have another issue. we now only see the "Audiodescription" variants. not any other ones.
The following code in shaka makes our variant be skipped
```
      const videoStreamUri =
          videoInfos[i] ? videoInfos[i].verbatimMediaPlaylistUri : '';
      const audioStreamUri =
          audioInfos[i] ? audioInfos[i].verbatimMediaPlaylistUri : '';
      const variantUriKey = videoStreamUri + ' - ' + audioStreamUri;
      if (this.variantUriSet_.has(variantUriKey)) {
        // This happens when two variants only differ in their text streams.
        shaka.log.debug('Skipping variant which only differs in text streams.');
        continue;
      }
```

if i comment it and test, we have the all 12 variants as expected

**Comment by vaage** [comment]
@fadomire we will be investing resources in HLS in our 2.7 release. Our initial implementation has grown old and if I remember correctly was only meant to cover the core elements of HLS, not all. The best way to get the spec-issue resolved, will be to file an issue citing the part of the spec that we are not respecting. This will make it easier for us to allocate resources to. In this case, I would actually suggest that you file it as a feature request since it would be extending our implementation to include an additional spec detail.

As for skipping variants, I would suggest that you open another issue that focuses on that. If you can host a copy of your manifest with the Audiodescription uris included and file a bug saying that variants are being skipped, we will be more able to dedicate resources to investigating that issue.

**Comment by fadomire** [comment]
will do thanks

**Comment by fadomire** [comment]
i created a feature request for optionnal URI spec
will open another issue for variant skipped before closing this one
