### ISSUE TITLE
Shaka and not correct availabilityStartTime interpretation

### ISSUE THREAD

**Issue by kuznetcoff777** [google/shaka-player#1853]
Hi!
We use big DVR(more then 12 hours) and we need very presize timeline for correc adver insertions. 
At now we use in our config constant shift for 5 seconds back. I wondered why we had to do it... After some investigation and help from encoder developers i found that:
Ind documentation https://standards.iso.org/ittf/PubliclyAvailableStandards/c065274_ISO_IEC_23009-1_2014.zip there is a phrase: "3.1.36 
Segment availability start time 
latest time instant in wall-clock time at which a Segment becomes an available Segment"
So when we use 5-sec segmens and begin to make mpeg-dash, AST = time of when first segment was writed totally and player can play from only ther second segment and time in time line is shifted ahead for 5 seconds, It means that shaka player takes AST for timing on timeline do it not so correctly, thats why we have to put some shift in config.

Will code somehow be reviewed to keep up with the standard?

I forgot to say that if to use lagre shift (offset) then it begin to appear another issues, like time lag or fetching segments that are not appeared yet (depends on offset is + or -)

**Comment by kuznetcoff777** [comment]
I forgot to say that if to use lagre shift (offset) then it begin to appear another issues, like time lag or fetching segments that are not appeared yet (depends on offset is + or -)

**Comment by vaage** [comment]
@kuznetcoff777 Thank you bringing this to our attention. To answer your question, "Will code somehow be reviewed to keep up with the standard?", the dash parser will be refactored in 2.6 as part of our code health release. However, we have not included time to audit the standards. We normally rely on the community to notify us if something has fallen out of spec. Whenever we fall out of spec, filing a bug is the best way to help us keep in-spec.

Filing a bug (with sample content) allows us to see how we are out of spec, allows others in the community to help raise the priority of the issue, and provides the opportunities for community members to contribute pull requests.

Does that answer your question?

**Comment by TheModMaker** [comment]
The `availabilityStartTime` attribute doesn't have to be related to be the wall-clock time a specific segment is written.  It is just used as a reference time for the presentation times.  See section 5.3.1.2, Table 3 where it says:

> For `@type='dynamic'` this attribute shall be present. In this case it specifies the anchor for the computation of the earliest availability time (in UTC) for any Segment in the Media Presentation.

The segment's availability start time (the wall-clock time you can download a segment) is equal to the sum of the manifest's `availabilityStartTime` attribute, the `Period@start` time, the segment's start time, and the segment duration.  So a segment becomes available only after the live edge has passed the end time of the segment.  This is explained in section 5.3.9.5.3.

So assuming the `availabilityStartTime` attributes specifies when you started the live stream, and the first segment your encoder creates starts at 0, then no adjustments are needed since the segment only becomes available once the live edge passes the end time of the segment.

You can also take a look at [this doc](https://github.com/google/shaka-player/blob/master/docs/design/dash-manifests.md) for more info on the timeline and the live edge.  Especially the bottom of the doc deals with the availability window.

**Comment by kuznetcoff777** [comment]
I think so, thanks
