### ISSUE TITLE
Audio sample rate changes across periods not detected on ChromeCast

### ISSUE THREAD

**Issue by salmoro** [google/shaka-player#1866]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.4.7 and 2.5.0-beta3

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Haven't tied

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chromecast 3

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
ChromeCast 3 (Chrome/71.0.3578.99)

**What are the manifest and license server URIs?**
Will email to shaka-player-issues@google.com immediately after issue is created so that I can reference this issue.

**What did you do?**
1. Place MPD URL in demo app
2. Cast demo app to ChromeCast 3.
3. Start playing from the beginning until 3rd period begins (48 seconds in)

**What did you expect to happen?**
Audio should sound normal as it does when not casting

**What actually happened?**
Audio sounds distorted and as if it was being played underwater.

**Notes:**
Very likely this is a ChromeCast (/Chrome) issue but since we don't have visibility/control with its updates and I couldn't find a bug of this sort reported on Chrome, I figured coming here might be a better bet than re-encoding all of our content or waiting out for a newer chrome version to be pushed to ChromeCast.
I hope my title on this issue is not misleading as I've kind of given it my own diagnosis which might be wrong.
The reason I suspect this is related to sample rate changes is because when I play the 3rd period on its own or if I begin the player at the 3rd period it plays well. Plus I see that periods 1 & 2 have a sample rate of 44k and period 3 of 48k so I suspect the issue is that Chrome hasn't detected the change and therefore it comes out distorted. I hope my hunches are more of a lead than a mislead.
Thank you.

**Comment by joeyparrish** [comment]
Your hunch sounds pretty reasonable, but if you're right, we won't be able to do anything about it.  That sort of platform bug would be pretty difficult to work around.  I can't think of a way to deal with that off the top of my head.

Do the 48kHz periods only have 48kHz audio?  Or also alternative streams in 44kHz?
Do the 44kHz periods only have 44kHz audio?  Or also alternative streams in 48kHz?

If there's a universal sample rate available across all periods, we could potentially work around the issue by filtering out streams to choose the sample rate that's universal in this content.  Otherwise, I think we might be stuck.  If we are stuck, I can help file a bug with the Chromecast team.

**Comment by salmoro** [comment]
@joeyparrish Thanks. The answer to your two questions is Yes, per period the sample-rate is the same.

In the end we worked around this by re-encoding our content  so that all periods have consistent Sample-rates and this indeed solved our issues.

Thanks!

**Comment by joeyparrish** [comment]
Thank you for the update!
