### ISSUE TITLE
How to monitor seekRange updates

### ISSUE THREAD

**Issue by vksbansal** [google/shaka-player#1868]
Hi Shaka Team,

The question is regarding DVR live stream

I am trying to update the time when the player is paused to inform user how much he has lagged from the live time.

In order to do that I am listening to the event `timeandseekrangeupdated` which is not invoked ever.

   ```
this.videoTag.addEventListener('timeandseekrangeupdated', () => {
            // not get called
        });
this.player.addEventListener('timeandseekrangeupdated', () => {
            // not get called
        });
```

Could you please provide the information of the event which is fired whenever seek range is updated?

Many thanks,
SHAKA FAN,
Vikas Bansal

**Comment by TheModMaker** [comment]
I don't know where you got that event name, but it doesn't exist.  You can take a look at our [documentation](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#.event:AdaptationEvent) for a list of the events we fire.

The seek range changes as time passes.  It goes from the current time to a certain time in the past.  So as the wall time moves forward, so does the seek range.  When you call `seekRange` we calculate it based on the current wall clock time.  So each time you call it it will return a new value as time moves forward.

**Comment by ismena** [comment]
@TheModMaker It's a UI event, thrown from the controls. I suck for not documenting them (there's more :/) and should do better :)

@vksbansal Are you using our UI library? If that's the case, the event is fired by the controls, rather than the player.
`
const ui = yourVideoElement.ui;
const controls = ui.getControls();
controls.addEventListener('timeandseekrangeupdated', blah);
`

If you're not using the UI lib, the event won't exist!
You did not explain in too much detail what your use case is for the event, so I'm not sure if it will be helpful or not.
Try it out, if it turns out not to serve your purpose, let us know, we'll see what we can do.

**Comment by joeyparrish** [comment]
I noticed that in @vksbansal's code snippet, the even listener is on player & video tag instead of the controls object.  That is probably the issue here.  @vksbansal, does that help?

**Comment by vksbansal** [comment]
@TheModMaker thanks for bringing the clarity. I am building my own UI on the shakaplayer, here is an a video that is being played using shakaplayer https://www.airtelxstream.in/movie/gravity/HOOQ_MOVIE_53828

Allow me to explain the scenario,

**What is the type of stream?**
Live widevine (.mpd)

**when I need the event?**
when a user has paused the video

**why I need the event?**
When a user has paused the video when I need to show the seek bar showing the current time in the seek bar. Either I need to use **settimeout** to update the seek bar or find an event that fires whenever you hit the index file to stay updated about the live stream.

please feel free to ask me more if above explanation is not as required.

Many thanks,
Vikas Bansal

**Comment by TheModMaker** [comment]
As @ismena noted, that event only exists if you are using our UI.  So if you are building your own UI, you won't see that event.

That event is just invoked every 1/8th of a second.  It is the same as using `setInterval`.  So in your UI you should just use `setTimeout`/`setInterval` to check for updates.  Since the timeline is changing continuously as wall time moves, there is no event for when that happens.
