### ISSUE TITLE
Multiplexed audio+video with separate audio group

### ISSUE THREAD

**Issue by fadomire** [google/shaka-player#1875]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**Is your feature request related to a problem? Please describe.**

in our HLS manifest the first #EXT-X-MEDIA do not have an URI
in current shaka HLS implementation that means it will be dropped

as per HLS spec URI is optional for #EXT-X-MEDIA
> When its URI attribute is omitted, the EXT-X-MEDIA tag can indicate that the media described is included in the URI of the EXT-X-STREAM-INF tag.

source : https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming/adding_alternate_media_to_a_playlist

**Describe the solution you'd like**

as per the spec if for a EXT-X-MEDIA the URI is missing, then we should look into the #EXT-X-STREAM-INF to get the URI 

**Describe alternatives you've considered**

**Additional context**

more info and discussion in #1850

**Comment by ismena** [comment]
@fadomire Is it a case of a TS stream carrying both audio and video?

**Comment by fadomire** [comment]
@ismena hmm yes in our case the TS stream carry both audio and video
but this feature request is more generic than that i think

**Comment by ismena** [comment]
Yeah, sorry, I was just trying to understand the concrete use case :)
Do you have stream for us to test?
I looked through the comments in #1850, but I don't think there was a stream there.

**Comment by fadomire** [comment]
yes i got the authorization to share the stream :
https://ios-q1-ssl.tf1.fr/2/USP-0x0/53/75/13615375/ssm/13615375.ism/13615375.m3u8

**Comment by michellezhuogg** [comment]
Hello @fadomire ,
Thank you for sharing the stream!
For this file, Shaka is not loading the video successfully not merely because of dropping #EXT-X-MEDIA tags without URI. The playlist claims separate audio and video streams, however there's audio and video together in the video streams in TS, and that's where we get inconsistent information and fail to load the video.
Do you have a more clear content that we can test with?

**Comment by fadomire** [comment]
Hello @michellezhuogg 
what do you mean by more clear content ?

we have this stream too
https://ios-q1-ssl.tf1.fr/2/USP-0x0/18/80/13631880/ssm/13631880.ism/13631880.m3u8

also i'm not sure i understand what you mean by "The playlist claims separate audio and video streams" how can i check that in the manifest ?

we dont do anything special when packaging. We use this packager "Created with Unified Streaming Platform(version=1.8.4)"

**Comment by ismena** [comment]
Hey @fadomire 
How familiar are you with the HLS manifest structure? There's something in the first piece of content you provided (we haven't looked at the second one yet, but will do) that totally confuses the player and it's a bit tricky to explain.
I will do it (explain), but I don't want to annoy you with a lecture on HLS spec if you're pretty familiar with it already.
Let me know and I'll walk you through what's up with that manifest!

**Comment by ismena** [comment]
UPD: Your second piece of content has the same pattern! :)

**Comment by fadomire** [comment]
hey @ismena i'm not familiar enough with HLS spec so an explanation would be great !

basicly, we just use Unified Streaming Platform command line to create our manifest (dash and hls) and expect them to respect the specs :)

**Comment by ismena** [comment]
Ok, there we go: HLS spec has media tags and variant tags.
Variant tags describe combinations of media, something like "you can use this video with this audio, here are the codecs you will need and this is how much bandwidth it will take". They look like this (from your content):
```
#EXT-X-STREAM-INF:BANDWIDTH=282000,CODECS="mp4a.40.2,avc1.42C01E",RESOLUTION=416x234,FRAME-RATE=25,AUDIO="audio-aacl-64"
13615375-audiodescription=64000-video=200395.m3u8?
```
// Use the video from the uri "13615375-audiodescription=64000-video=200395.m3u8?" with any audio from audio group "**audio-aacl-64**" (I'll explain about audio groups in a sec).

There are also media tags that describe specific media, like "This is an audio playlist, it's in French and it has two channels".
Audio tags look like this:
`#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-64",NAME="English",LANGUAGE="en",CHANNELS="2",URI="13615375-eng=64000.m3u8?"`

There might be several of them with the same group id (same audio in different languages, for example).

Now, the original reason for this issue was that we did not take multiplexed streams into account and assumed all media tags will have a uri. Not true. If video and audio are carried in one stream, one of them will have a media tag (usually audio), but no uri.

So, here's the deal with your content.
It has several audio media tags: 
1) Audio in English, has it's own uri
2) Audio in French, has it's own uri
3) Audio in French, does not have it's own uri, is multiplexed with the video.

The Variant tag says,  we can pair the video with any of these audios.
But we can't! There is no way we can separate audio and video multiplexed together and play the video with another audio stream. Safari might be able to do it cause they're not working through Media Source, but not us.
Even if we stop looking for the URI tag where none exists, what happens is we try to treat a video+audio stream like a purely video stream and it's not working.
The only thing we can actually play is the multiplexed stream of video and audio together.

I think, the best we can do is try and discard all the audios that we can't play and proceed with that single multiplexed stream. I'll try and schedule this work for our 2.7 hls-focused release.

In the meantime, do you have any control over the manifest of your content? I can do a quick-ish fix to not require the uri, but to get your content to play both audio and video (the multiplex stream that we can feasibly play), you'll need to cut the other audio variants from the manifest (for now, until we can work around this structure). Is this something you can do?

**Comment by ismena** [comment]
Sorry for the wall of text, let me know if you have any questions.

**Comment by joeyparrish** [comment]
Please check with Unified Streaming to see if you are running the latest software from them.  If not, try updating first to see if this is an issue they have already dealt with.

**Comment by fadomire** [comment]
ok i will check on their side
i will also read the detailed reply from @ismena (thanks), read it quickly but need more time

but one thing is that for e.g hls.js allow us to choose between all the variants we expect as you can see in their demo with our manifest
https://video-dev.github.io/hls.js/demo/

is there something special they do ? not meaning to say it is better over there, i choosed shaka for many reasons and happy with the choice

**Comment by ismena** [comment]
@fadomire Maybe they are better at some things at hls.js, nothing wrong with that ;)
We'll take a look, see if we can learn from them how to handle this case better!

**Comment by ismena** [comment]
UPD: I've taken a look at hls.js. My best bet is, they're handling transmuxing differently.
If given a multiplexed ts stream, they demux it to two separate streams, one video and one audio.
We mux it back to a single mp4 stream (or rather mux.js does for us).
It is the limitation of our current architecture and something we're not planning to change in the near future (not this year at least).
This might change if it turns out to be a vital use case for the industry, but for now it is what it is :(

If there's any chance you can encode your content to be consistent in terms of multiplexing/not multiplexing streams, it would be awesome. Sorry about that!

**Comment by fadomire** [comment]
thanks for taking a close look

i will see with our backend if something can be done

**Comment by ismena** [comment]
The original bug us still relevant: we should not require the URI for all media tags :)

**Comment by ismena** [comment]
Nooope, this is still an issue!

**Comment by joeyparrish** [comment]
In the latest code on master, this plays, but audio-only for some reason.  In spite of that, we show video as having been buffered.  This could be a mux.js bug.

**Comment by joeyparrish** [comment]
Same results in v2.5.8.

**Comment by joeyparrish** [comment]
Same results with latest mux.js release, v5.5.1.

This might require some digging through chrome:media-internals to understand why we have apparently buffered video, but no frames are being shown.

**Comment by joeyparrish** [comment]
Oh, now I see.  The parsed manifest shows an audio stream with the codecs set to "mp4a.40.2" and a video stream with the codecs set to ... "mp4a.40.2" again.  So that's how we have video "buffered".  The "video" we're sending in is actually audio.

So not a mux.js bug after all.

**Comment by joeyparrish** [comment]
I can see where our parser gets confused, but honestly, I get confused, too, when I try to read your master playlist.  Here's what I see (with irrelevant attributes removed for ease of reading):

```
# AUDIO groups
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-64",NAME="Audiodescription",LANGUAGE="fr"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-64",NAME="English",LANGUAGE="en",URI="13615375-eng=64000.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-64",NAME="FranÃ§ais",LANGUAGE="fr",URI="13615375-fra=64000.m3u8"
```

These are the audio media tags.  There are actually 6 of them, but only 3 appear here, for the sake of discussion.

One of those three media tags has no URI, and I'm supposed to use the URI of the EXT-X-STREAM-INF instead.  So far, I understand that.  That doesn't seem to be the main problem, though.  At worst, we would filter out that one media tag, and the audio description track would be unavailable.  That's not what I'm seeing, though.  I'm seeing no video.

```
# variants
#EXT-X-STREAM-INF:CODECS="mp4a.40.2,avc1.42C01E",RESOLUTION=416x234,AUDIO="audio-aacl-64"
13615375-audiodescription=64000-video=200395.m3u8
#EXT-X-STREAM-INF:CODECS="mp4a.40.2,avc1.42C01E",RESOLUTION=480x270,AUDIO="audio-aacl-128"
13615375-audiodescription=128000-video=401562.m3u8
```

These are audio-video variants.  There are actually 6 of them, but only 2 are pictured here.  In the case of the first audio media tag above, I should be using the audio that's muxed into the video stream.  We don't support that at the moment, so we drop those URI-less media tags.  But so far, this all makes sense, too.

```
# variants
#EXT-X-STREAM-INF:BANDWIDTH=69000,CODECS="mp4a.40.2",AUDIO="audio-aacl-64",SUBTITLES="textstream"
13615375-audiodescription=64000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=137000,CODECS="mp4a.40.2",AUDIO="audio-aacl-128",SUBTITLES="textstream"
13615375-audiodescription=128000.m3u8
```

This is where I get confused: the audio-only variants.  These each appear refer to an audio-only stream, but also to an explicit audio group.  Am I meant to ignore the audio group?  Or ignore the URI of the EXT-X-STREAM-INF?  Or somehow group one set of audio streams with another?

I found two things along the way.  First, the parser is mistakenly identifying the audio-only variants as streams with video.  This, plus some logic to choose the best codecs, is how we wind up dropping the other variants and playing audio-only streams as if they were video.  I have a simple fix for this.

But fixing that issue reveals the next issue: We can't transmux a multiplexed stream, and then add another non-multiplexed audio stream to it.  We get decoder errors from Chrome.  Now this is indeed an architectural limitation for our transmuxer.  We send muxed audio+video in, we get muxed audio+video out.  Adding another audio stream to that is not supported by the browser.

If I hack the HLS parser to ignore the audio groups and just play the multiplexed content alone, it plays, with both audio and video.  But this is a total hack, and not something we can commit.  For one, it limits us to the muxed-in audio only, which is the audio description track for the blind.  For another, there's no obvious way to detect from the master playlist itself that the video-having variants contain their own audio.  In fact, because they have an audio group attached, we reasonably assume they don't.

So, finally, I will fix the mis-identification bug in the HLS parser that tricks us into treating the audio-only streams as video.  But beyond that, we simply cannot support this content structure (multiplexed audio+video with a separate audio group).  I apologize for any inconvenience.
