### ISSUE TITLE
Multi-period with presentationTimeOffset can overwrite previous period

### ISSUE THREAD

**Issue by kilohaty** [google/shaka-player#1882]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v2.4.7

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome/73.0.3683.103 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://res.kilohaty.com/test/1.mpd

[shaka demo](https://shaka-player-demo.appspot.com/demo/#asset=https://res.kilohaty.com/test/1.mpd;lang=zh-CN;build=uncompiled)

**What did you do?**

the mpd file has 2 periods (25fps), each period is 3 seconds, and the second period  has set the presentationTimeOffset.
I seek at 00:00:02:920, the video's picture is the second video's picture.

**What did you expect to happen?**
seek at 00:00:02:920, the video's picture is the first video's picture.

**What actually happened?**

the video's picture is the second video's picture, the second period overwrite previous period.

**Comment by TheModMaker** [comment]
We use MSE's `appendWindowStart` to chop off any content before the Period start.  This means that any content from the second Period that happens before its Period start gets removed.  This is provided by the browser and we can only control what the value is, not its behavior.  The behavior is to remove anything that appears before that value and up to the next keyframe.  This means that if the value is 3, and there are keyframes at 2.9 and 6, the browser will remove everything up to 6 seconds.

We adjust this value slightly back to account for rounding errors in the Period start number.  This means that [up to 0.1 seconds](https://github.com/google/shaka-player/blob/4334f1956b77c529df7772c87f837370b0f16be1/lib/media/streaming_engine.js#L309) before the next Period can be content from the next Period.  If we don't do this, then a slight rounding error in the Period start can cause us to remove the keyframe at the start of the Period and lose the first [GOP](https://en.wikipedia.org/wiki/Group_of_pictures).

Note that since we see that frame, it is probably a keyframe.  So if we didn't do this, then the browser would probably remove the first GOP in the second Period and there would be a several second gap.  We may even lose the whole Period depending on the GOP interval.

**Comment by kilohaty** [comment]
Thank you a lot for your answers! 
I tried setting APPEND_WINDOW_START_FUDGE_ to 0 and using all keyframes videos.
Sometimes the picture is accurate, sometimes it is still the case. 
I don't know what to do to make the picture accurate, because I need to make a editing tool,  this is very important.

**Comment by TheModMaker** [comment]
Can you share some content that the picture isn't accurate in?  It is accurate for me with the manifest you provided initially.

**Comment by kilohaty** [comment]
Hi @TheModMaker 
In this demo page [demo](https://shaka-player-demo.appspot.com/demo/#asset=https://res.kilohaty.com/test/1.mpd;lang=zh-CN;build=uncompiled),
After load assert, I manually seek to 00:00:02:920 in the devtools console.
`document.querySelector('video').currentTime = 2.92`
The picture is the second video's picture.
But the second video should start from 00:00:03:000

**Comment by TheModMaker** [comment]
- Navigate to your link
- Open DevTools
- Enter `shaka.media.StreamingEngine.APPEND_WINDOW_START_FUDGE_=0`
- Click Load button and pause video
- Enter `video.currentTime = 2.92`

If I do those steps, I get the expected Big Buck Bunny frame.  APPEND_WINDOW_START_FUDGE_ is being used to adjust the append window start, which is why you see the next Period's frame.  If you set that value to 0, it should be accurate.  You need to set this before loading content and it only works in uncompiled mode.  Do you have any content where setting APPEND_WINDOW_START_FUDGE_ to 0 doesn't fix it?

**Comment by kilohaty** [comment]
Hi @TheModMaker 
I made a case again. [demo](https://shaka-player-demo.appspot.com/demo/#asset=https://res.kilohaty.com/test/2.mpd;lang=zh-CN;build=uncompiled)
Each period is also 3 seconds long. The first video is a LOL game, and the second video is a shooting game.

**Comment by TheModMaker** [comment]
The new manifest has a slightly different behavior of showing the previous Period's frame at exactly 3 seconds.  This is probably because your second Period has invalid segment times.

The `S@t` attribute needs to match what is encoded in the media.  I notice that the first segment in the second Period actually starts at 0, so the `S@t` attribute should be 0, not 6640.  Secondly, the second segment in the Period has a `S@t` attribute that is less than the first segment.  So the segments are out of order (or you just manually edited the first, which you can't do).

**Comment by TheModMaker** [comment]
You should also look at [this doc](https://github.com/google/shaka-player/blob/master/docs/design/dash-manifests.md) for a more detailed explanation of the presentation timeline and how to correctly handle the times in multi-Period content.

**Comment by TheModMaker** [comment]
Does this answer all your questions?  Can we close this issue?
