### ISSUE TITLE
Bug: Fullscreen button on iOS 

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1909]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes 

**What version of Shaka Player are you using?** Master

**Can you reproduce the issue with our latest release version?** N/A

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Safari , iOS 12.2 (iPhone 8)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Any HLS stream

**What did you do?**

Load any HLS stream 

**What did you expect to happen?**
Fullscreen button is not shown, due the Fullscreen API is not available on the platform
https://caniuse.com/#search=fullscreen

Note: I think that in iPad should work, but i didn't test.

**What actually happened?**

Fullscreen button is shown

**Comment by avelad** [comment]
Note: You can put the video element on fullscreen with `document.getElementById('video').webkitEnterFullscreen()` in the Demo App over iOS.

**Comment by joeyparrish** [comment]
This is a bit subtle here.  Apple didn't implement the standard fullscreen API with a prefix at all.  They instead implemented a video-specific API of their own.  You can't fullscreen just anything.  You have to fullscreen the video element itself, losing you access to custom controls.

So polyfilling it will be tricky.

**Comment by joeyparrish** [comment]
For now, fullscreen in our UI is disabled on iOS.

**Comment by joeyparrish** [comment]
I've just done some experimentation with this, and there seems to be no way to polyfill the standard fullscreen API.

We have already fixed our UI not to show the fullscreen button on iOS.  Applications not using our UI will not see requestFullscreen on Element, but have the option to use the video-specific, webkit-prefix iOS API for fullscreen if they want to give up on custom controls.

Since it seems that there's nothing more we can do here, I will close this issue.
