### ISSUE TITLE
Publish Shaka Player UI as npm package

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#1916]
Currently exists shaka-player in npm https://www.npmjs.com/package/shaka-player

Is possible publish shaka-player-ui in npm? I want use `const shakaUI = require ('shaka-player-ui');`

**Comment by theodab** [comment]
Seems like a good idea to me.

**Comment by joeyparrish** [comment]
I'm not sure we need a separate package.  It's really just two build configurations of the same thing, and shaka-player.ui.js is already built and deployed on the existing package.

With nodejs, you can address the UI build in the existing package like this:

```js
const shaka = require('shaka-player/dist/shaka-player.ui.js');
```

The UI build fails to load in a nodejs environment because it depends on things like `document`, but it's a UI, and that will always be the case.

Are you trying to load the UI in nodejs?  Or some other module loader?

**Comment by avelad** [comment]
We are using webpack for load Shaka Player. 
But you're right, we can use your suggestion.

Thanks for the feedback. I close this issue.
