### ISSUE TITLE
Multiperiod is not preloaded with certain manifests

### ISSUE THREAD

**Issue by bwidtmann** [google/shaka-player#1919]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
latest

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
chrome + mac

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://demo.yospace.com/vincent/pro7/dash-mp-13.mpd

**What did you do?**

start video with native browser controls enabled and watch buffer. second period is not preloaded until first period is playbacked completely.

**What did you expect to happen?**
player should start preload buffer of second period during playback of first period. check out this manifest where it works: https://s3.eu-central-1.amazonaws.com/mxd-mediavault/vast/dash-mp-11-1.mpd

**What actually happened?**

We see the missing preload between ads (multiperiods) only on certain manifests: https://demo.yospace.com/vincent/pro7/dash-mp-13.mpd

We created a handcrafted multiperiod manifest with Unified Streaming where preloading works perfectly: 
https://s3.eu-central-1.amazonaws.com/mxd-mediavault/vast/dash-mp-11-1.mpd

Can you please check if it is a content issue or a player issue?

**Comment by TheModMaker** [comment]
You have a gap between the two Periods.  The Player jumps the gap automatically and the Shaka UI displays the buffered ranges ignoring the gap, but the native controls seem to stop after the first buffered range.  You can look at `video.buffered` to see the buffered ranges.  Also note that you may need to increase the `streaming.bufferingGoal` value to make Shaka Player buffer far enough to get past the first Period; the default is only 10 seconds.

**Comment by vto5623** [comment]
Hi,

I work on the same project.
Could you please specify in which manifest you detected a gap?

I inspected and found no gaps in https://demo.yospace.com/vincent/pro7/dash-mp-13.mpd.

However I have found a 15.6ms gap in https://s3.eu-central-1.amazonaws.com/mxd-mediavault/vast/dash-mp-11-1.mpd (because 1st Period audio is 20.0156sec long and video is 20sec long, but 2nd Period start at PT20.0156).

What is weird is that the player does not preload segments as expected for the manifest with no gaps, but preloads them correctly for the other one which has gaps.

Thanks

**Comment by TheModMaker** [comment]
I tested with https://demo.yospace.com/vincent/pro7/dash-mp-13.mpd and saw that it has gaps.  Just because the manifest doesn't have any gaps doesn't mean the content doesn't.  The first segment of the second Period starts 0.08 seconds after the Period start, so there is a slight gap between the Periods.  This is normally fine, but apparently causes problems with the native controls' display.

We still buffer past the gap, it is just that the native controls don't show it.  If you use the Shaka UI, you'll see we buffer to the end.  If I load either of the assets you provided and set the `streaming.bufferingGoal` to 200, it will buffer the whole video to the end.  You need to use the Shaka UI or a custom UI to see it because the native controls don't show it correctly (a browser bug).

**Comment by vto5623** [comment]
Got it, many thanks.

**Comment by bwidtmann** [comment]
thanks for clarification.
