### ISSUE TITLE
Transmuxing MPEG2-TS with DRM

### ISSUE THREAD

**Issue by shvelo** [google/shaka-player#1935]
Hello, does transmuxing work on encrypted M2TS streams, so you can play DRM HLS on unsupported platforms?

**Comment by theodab** [comment]
At the moment, we have no sample input that is encrypted MPEG2-TS. In fact, we have no sample content that is MPEG2-TS at all, because the bitcodin assets we were using as sample content for that before have weird CORS issues at the moment.

Decryption for DRM is handled by the browser, after we pass the media segments to it. Transmuxing is done right before appending the media segments, by [muxjs](https://github.com/videojs/mux.js).

So it depends on if muxjs can transmux from encrypted TS to encrypted MPEG2-TS. I asked around a bit, and it sounds like something like that is theoretically possible, depending on the exact encryption scheme used. I don't know if muxjs supports that in particular, though. If you try it out and it doesn't work, we can help you file a bug on muxjs if you want.

**Comment by shvelo** [comment]
Not yet, I'm still experimenting. 

At the moment, there are some bugs that prevent shaka-player to even attempt playing encrypted TS, which are solved with manual intervention in `media/drm_engine.js` before I find a more elegant solution. I have to use `video.mimeType.replace('mp2t', 'mp4')` before passing it to `willSupport`, because browsers that require transmuxing obviously don't support DRM for MPEG2-TS.

Mux.js still can't transmux encrypted TS at the moment, and I'm looking into it right now.

**Comment by TheModMaker** [comment]
What kind of DRM are you talking about?  Is this FairPlay, a custom DRM solution, or clear key?  Is this similar to AES-128 as in #850?  Is there a way to get the keys in JavaScript?

If this is FairPlay or another DRM provider, there is nothing we can do since support is dependent on the browser.  So even if we could transmux it to MP4, the browser would still not support the DRM system needed to decrypt it.  But if it is AES-128 or something similar where we can get the keys, we could always decrypt the content in JavaScript before passing it to the transmuxer.  Follow #850 for that feature.

**Comment by shvelo** [comment]
This is CENC generated by Shaka Packager, trying both Clear Key and Widevine.

**Comment by shvelo** [comment]
I've almost got it to play using my own fork of mux.js which generates appropriate boxes for CENC MP4 playback, except the `senc` box, because Shaka Packager seems to always use subsample encryption

**Comment by joeyparrish** [comment]
Renaming the issue and changing the tags.  Please let us know if you land a PR in mux.js to resolve this.  At that point, we can update our version of mux.js to include your changes.  Thanks!

**Comment by joeyparrish** [comment]
Closing this stale external (non-Shaka) issue. If you disagree, please reply with @shaka-bot reopen, and it will be automatically reopened.
