### ISSUE TITLE
Content-Type not parsed in the correct way

### ISSUE THREAD

**Issue by petar11199** [google/shaka-player#1946]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 2.5.0

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Custom

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?** Google Chrome 74, Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

Load DASH stream

**What did you expect to happen?**
I expected Shaka player to correctly parse 
`Content-Type: application/dash+xml;charset=utf-8;profiles="urn:mpeg:dash:profile:isoff-live:2011,urn:hbbtv:dash:profile:isoff-live:2012"` and set `mime type` to `application/dash+xml` and play the stream.

**What actually happened?**

Shaka throw 4000 error `UNABLE_TO_GUESS_MANIFEST_TYPE.`

I think this is caused because stream response header returns Content-Type which Shaka Player doesn't parse in the correct way.

I did manage to fix this by going to `../lib/media/manifest_parser.js` in Shaka player directory. Then in method `shaka.media.ManifestParser.getFactory_` I added `mimeType = 'application/dash+xml'`; at the beginning of that function. 
And that works fine, but it isn't really a good solution for me because it involves messing with source code.

Any help would be appreciated . Thanks.

**Comment by TheModMaker** [comment]
As a workaround, you can pass the mime type to load, `player.load(url, null, 'application/dash+xml')`.  But we should actually parse the `Content-Type` header instead of just using it for string comparison.

**Comment by mimse** [comment]
Hi 

We are having the same problem.

We are getting this url 

https://csm-e-cepreurxaws101j8-5rarw7tm1jwg.bln1.yospace.com/179380410/1.mpd;jsessionid=895FAD293C4D1F0E52B527DA3AAA778D.csm-e-cepreurxaws101j8-5rarw7tm1jwg.bln1.yospace.com;jsessionid=895FAD293C4D1F0E52B527DA3AAA778D.csm-e-cepreurxaws101j8-5rarw7tm1jwg.bln1.yospace.com?yo.ac=true&ppid=88db9bcf94224e7fb10066553ab1fa61&externalId=tv2_mdash_avc1_nodrm

from yospace. Shaka player is unable to detect the content type from the extension.
It tries to resolve the content type by calling the manifest file

https://github.com/google/shaka-player/blob/8c8552ae7cfbabede8ee6c5d3cf00f38622c2c67/lib/media/manifest_parser.js#L219

The server that hosts the manifest file returns this content type "application/dash+xml;charset=utf-8"

It compares the result here 

https://github.com/google/shaka-player/blob/8c8552ae7cfbabede8ee6c5d3cf00f38622c2c67/lib/media/manifest_parser.js#L81

And because "application/dash+xml;charset=utf-8" is not in the list it throws 4000 error UNABLE_TO_GUESS_MANIFEST_TYPE.

I see 3 solutions

1) Add "application/dash+xml;charset=utf-8" to the list
2) Do a split on ";" and only take the first part
3) call load with the right content type as @TheModMaker said

The problem with solution number 3 is that we are seeing the problem when using shaka player with the CAF SDK. The CAF SDK wrapper does not provide the load function with the content type, even when set in the CAF SDK.

**Comment by joeyparrish** [comment]
This should be easy enough to fix by splitting the detected mime type on semicolon and using the first part only.  Feel free to create a PR for this.
