### ISSUE TITLE
Header name is set to lower case

### ISSUE THREAD

**Issue by jpiechowiak** [google/shaka-player#1952]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.0

**Can you reproduce the issue with our latest release version?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**What browser and OS are you using?**
Windows 10 + Chrome

**What did you do?**
I tried to use following piece of code to send DrmChallengeCustomData header:

`player.getNetworkingEngine().registerRequestFilter((type, request) => {
    if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
        request.headers['DrmChallengeCustomData'] = customData;
    }
});`

**What did you expect to happen?**
Header should be send with specified name.

**What actually happened?**
Header was sent and his name was set to lower case: drmchallengecustomdata instead of DrmChallengeCustomData. My license server is case sensitive in this manner, so video isn't starting.

![headers](https://user-images.githubusercontent.com/5213586/58020456-6ff82900-7b08-11e9-85e7-72178e7cc282.png)

**Comment by joeyparrish** [comment]
@jpiechowiak, this is working as intended.

If we store header names in a map and refer to a header with inconsistent case, we may end up sending a duplicate header or failing to read a header which is present with a different case.  So we normalize header names to lowercase.

This works in general because the [HTTP spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) is very specific about header case:
> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.

So if your server will not accept lowercase headers or your server-side application does not normalize the input, I'm afraid your server is at fault.

Does this answer your question?

**Comment by jpiechowiak** [comment]
Well it will be difficult to change this one, because server is working for a longer time, and I don't have ability to change this behaviour because I'm not developing server side.

Is there any option for simple, temporary workaround for my case?

**Comment by joeyparrish** [comment]
After looking again, I find that I was mistaken.

The behavior of converting headers to lowercase is not part of Shaka Player at all.  That conversion is done by the Fetch API in the browser (specifically the `Headers` class), again, per spec.  With `Headers`, there is actually no way for you to control this.  Here's an example:

```js
h = new Headers();
h.set('Foo-Bar', 'Foo-Bar');
f = await fetch(location.origin, {headers: h});
```

If you run this in the JS console, then go examine the network panel of the debugger, you'll see that the header name is "foo-bar", all lowercase.

I have found experimentally that using a plain old Object instead of `Headers` will get you a case-sensitive request header, but I don't know how reliable this is across browsers:

```js
h = {'Foo-Bar', 'Foo-Bar'};
f = await fetch(location.origin, {headers: h});
```

You could make the equivalent change in Shaka Player by making two modifications:

Here, you could replace the `Headers` object built from `request.headers` with `request.headers` directly:
https://github.com/google/shaka-player/blob/d23e4a6b382d7e29f113b9e5de661e1166c3176e/lib/net/http_fetch_plugin.js#L42-L45

And here, for browsers without Fetch, you would remove the emulation of the `Headers` behavior in XHR-based requests by replacing `lowercasedKey` with `key`:
https://github.com/google/shaka-player/blob/d23e4a6b382d7e29f113b9e5de661e1166c3176e/lib/net/http_xhr_plugin.js#L111-L116

My advice to you is to make these changes in a fork of Shaka Player, then ask your server-side folks to fix the server-side applications to normalize request headers.  As soon as the server is fixed, you could unfork Shaka Player to make updates and bug fixes easier to adopt again.  (I recommend against trying to maintain a _permanent_ fork, but of course, you are allowed to do whatever you like with the source.)

Does this help?

**Comment by jpiechowiak** [comment]
Yes, it does. Thank you :)

**Comment by mhosman** [comment]
Same issue here! @joeyparrish your solution is not working for me. Maybe I'm doing something wrong?
