### ISSUE TITLE
Surround sound with HLS

### ISSUE THREAD

**Issue by raestrada95** [google/shaka-player#1963]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
-Yes

**Is your feature request related to a problem? Please describe.**

I can not play surround sound on the Chromecast, in the example that you have the only option of sorround is with Dash, could you give an example of 5.1 with HLS?

**Describe the solution you'd like**

can you add an example of 5.1 with HLS? in the demo that I leave below.

https://v2-4-7-dot-shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine-hls/hls.m3u8;lang=es-ES;channels=6;noadaptation;build=compiled

**Comment by joeyparrish** [comment]
Some of our demo assets were missing the channel count metadata necessary to make this work.  I have updated all of the "Angel One" clips (see the "Search" tab in the demo), which have both stereo and 5.1 surround versions of the English audio.

If you are playing an audio language other than English, you will get stereo, because those tracks are only available in stereo.  If you select English, the number of channels will be based on your configured preference (`preferredAudioChannelCount`).

If your preference is 6 or more, you get surround sound.  Otherwise, you get stereo.  To configure `preferredAudioChannelCount` in the demo app, open the config panel on the left, expand "Language", and fill in "Preferred Audio Channel Count" (default is 2).

In all cases, the application can use `selectVariantTrack()` to select any track, regardless of the `preferredAudioChannelCount` setting.

Does this solve your issue?

**Comment by raestrada95** [comment]
Hi  joeyparrish thanks for your answer. I've noticed that 6-channel AAC audio only works with the Chromecast 1, When I do the same with my Chromecast Ultra, this does not work. Keep working it's 2 channels. In some forum I read that the Chromecast ultra no longer has support for AAC of 6 channels that is true?

**Comment by joeyparrish** [comment]
I don't have any special insight into the capabilities of the device.  There was missing metadata in the manifest before, and now that has been fixed.  In all cases, we pass the metadata to the device when we query what it supports.  After removing anything which is not supported, we use preferences to pick between different numbers of channels.

If `getVariantTracks()` does not return 6-channel audio on Chromecast Ultra, then either the device does not support it, or we made a mistake in how we formatted the query.

Please confirm what behavior you're seeing.

**Comment by joeyparrish** [comment]
We've updated the assets to fix the metadata, and as far as I can see, everything is working as it should.  If you still have issues, please feel free to reopen the issue or file a new one.  Thanks!
