### ISSUE TITLE
progressCallback is not called when using player.configure

### ISSUE THREAD

**Issue by brunottonurb** [google/shaka-player#1974]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Shaka Player 2.5.1

**Can you reproduce the issue with our latest release version?**
Happens on the latest version.

**Can you reproduce the issue with the latest code from `master`?**
Cannot build latest `master`: `IOError: [Errno 2] No such file or directory: [...]/shaka-player/dist/locales.js'`

**Are you using the demo app or your own custom app?**
Custom React App

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Ubuntu 18.04, Chrome & Firefox

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What did you do?**

Edit: Might be relevant: Init player w/o a video element (attach later) with `new shaka.Player();`

Pass a progressCallback via
```
player.configure({
  offline: { progressCallback },
  ...
});
```

**What did you expect to happen?**
I expect the progressCallback to be called while a download is in progress, same as when using the deprecated
```
storage.configure({ progressCallback });
```

**What actually happened?**
`progressCallback` is not called at all. Is called when using the now deprecated storage configuration above.

**Comment by joeyparrish** [comment]
Re: "Cannot build latest master: IOError: [Errno 2] No such file or directory: [...]/shaka-player/dist/locales.js'", this should be fixed now in master.  If this persists, please file a separate issue for it.  Sorry for the inconvenience.

Here are my steps to reproduce the issue:

```js
player = new shaka.Player();
storage = new shaka.offline.Storage(player);
progressCallback = (content, percentage) => console.log('progress', content, percentage);
player.configure({ offline: { progressCallback }});
storage.store('https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd');
```

This is working correctly with both v2.5.1 and the latest from `master`.

I think your problem may be that you have not supplied a `Player` instance to the `Storage` constructor.  If you don't do this, then they do not share a config.

What's deprecated is not configuring progress on `Storage`, though.  You will always be able to configure `Storage` directly.  What's deprecated is the use of `{ progressCallback }` instead of `{ offline: { progressCallback } }`.  `Storage` now takes a full config object of the same format as `Player`, and the full config has absorbed the storage config from v2.4.

So there are two solutions for you:

```js
// Pass Player instance to Storage, then configure on Player:
storage = new shaka.offline.Storage(player);
player.configure({offline: { progressCallback }});

// -OR-

// Keep Storage independent, and use the new field location inside "offline":
storage = new shaka.offline.Storage();
storage.configure({offline: { progressCallback }});
```

I've just verified that both solutions work correctly on v2.5.1 and `master.

Does this answer your question?

**Comment by brunottonurb** [comment]
Thank you very much for the explanation!
