### ISSUE TITLE
shaka.util.StringUtils.fromCharCode throws call stack limit error for low end device

### ISSUE THREAD

**Issue by dobrusev** [google/shaka-player#1985]
Hi team,

I am running shaka player (v2.4.3) on low spec set top box and I got a runtime exception for call stack limit reached when parsing the manifest. I was able to go around it changing the max cycle iteration value in shaka.util.StringUtils.fromCharCode from 16k to 8k. 

I don't want to maintain a separate shaka player just for this change. I wonder what will be the proper solution here so can we include this change in shaka? Don't think exposing config param is worth it ... 

There is one more thing that I want to ask. VOD playback (DASH + Widevine)  look stable but we have issues with Live playback where the device crash because it reaches its memory limits. Is there a way to optimize memory usage?

Thank you in advance!

**Comment by joeyparrish** [comment]
You could certainly reduce it to 8k in a PR, with a comment explaining why that is the limit.  That seems like a reasonable solution to me.  Would you be willing to send us a PR for that?

As for the memory usage in live, it depends on where that memory is going.

You could try configuring the player with lower values for bufferingGoal, bufferBehind, and rebufferingGoal.  That could reduce memory used by the media stack to store segments and frames and such.

If that doesn't help, we'll need to dig into a memory profile to find out what the issue is.  That would require access to the device and a debugger.  If this is a device we can get off the shelf somewhere, you can give us details and we can look into adding one to our lab environment.  If not, then you may have to help us out by doing some profiling on our behalf.

But hopefully the buffering config will make a difference.  Try that first and let us know how it goes.

**Comment by dobrusev** [comment]
Thanks for the quick reply,

I will make the PR after I try bufferingGoal, bufferBehind, and rebufferingGoal. Will check with the box provider how we can get memory profile. Please can you provide an email that I can contact you for the eventual device delivery.

**Comment by NicolasSiver** [comment]
Hello,

I have decided to use this conversation since we are seeing a regression in `2.5.3` regarding the video playback on Samsung Tizen TV devices.

We are using HLS (`mux.js 5.1.3`), Live Broadcast, with 4 seconds segment duration. We see that even Premium devices would crash after some time of playing.

We are conducting tests and collecting more information but in `2.4.6` we did not see any application crashes on Premium devices:

### Test Results for `2.5.3` (In Progress)

![image](https://user-images.githubusercontent.com/135263/61806664-1d880100-ae06-11e9-9993-840e45a78aaa.png)

### Test Results for `2.4.6`

![image](https://user-images.githubusercontent.com/135263/61806866-7a83b700-ae06-11e9-80f5-d407e9e840b4.png)

Let me know if you need more information about device models.

Regards,
Nicolas

**Comment by joeyparrish** [comment]
@NicolasSiver, please file a new issue.  This one is closed, and your comments do not appear to have anything to do with this issue's topic.

The issue templates will guide you on providing the information we need to address your issue.  Please answer all questions in the template.  Thanks!

**Comment by NicolasSiver** [comment]
@joeyparrish sure. Created separate ticket - https://github.com/google/shaka-player/issues/2059

**Comment by joeyparrish** [comment]
Thanks!
