### ISSUE TITLE
Shaka and not correct availabilityStartTime interpretation №2

### ISSUE THREAD

**Issue by kuznetcoff777** [google/shaka-player#1986]
Hi! Issue is reated to https://github.com/google/shaka-player/issues/1853

I made a test stream (link#1 sent to shaka-player-issues@google.com) with 5-sec segments (gop=1 second) and burned-in timecode. 
-encoder started at "Initial timecode: 08:53:45:01" (MSK timezone)
-first segment appeared Modify: 2019-06-11 08:53:50.000000000 +0300
-second segment appeared Modify: 2019-06-11 08:53:55.000000000 +0300
In MPD file i see availabilityStartTime="2019-06-11T05:53:55Z" (by standard it have to be 2019-06-11T05:53:50Z, it is encoder bug and fixed in newer versions, but anyway it does not matter now).

When i watch stream (link#1) then i see this timeline 
![link-1](https://user-images.githubusercontent.com/15265762/59247436-01e6e380-8c28-11e9-8cd1-5c2fee69c695.png)

I made an mpd file with changed availability start time (minus 10 seconds) (link#2) and now player timeline is correlated with burned-in timeline.
![link-2](https://user-images.githubusercontent.com/15265762/59247437-01e6e380-8c28-11e9-8605-05dbccc31cb0.png)

So to get correct time line we have to manipulate availabilityStartTime in mpd file or make some constant with player config to shift back timeline.

I want to understand if shaka doing all properly and if not will be it fixed?

**Comment by theodab** [comment]
I tried out the assets you sent, and for both of them the baked-in time is significantly off of the video's currentTime. Like, about 9-10 hours off. If you try again now, do you see a large time discrepancy like that? Or does the second stream look correct to you, still?

**Comment by kuznetcoff777** [comment]
"Like, about 9-10 hours off. If you try again now, do you see a large time discrepancy like that? " - seems to be that some time zone issues. I see all correctly.

**Comment by theodab** [comment]
I tried setting my timezone to MSK. Now I see an even bigger time difference. I think I may have misunderstood what you are expecting.

At the moment, it looks like the burned-in time is the current time of day in the MSK timezone, correct?

And you are expecting the video's currentTime to be equal to the burned-in time, and thus the current time of day. But the video element's currentTime is the time since the broadcast began. So I'm not sure why your screenshots show 8:57:17 instead of the ~4 minutes it was since the broadcast began.

So I guess I should ask... What browser are you using? Do you have a custom UI with different time drawing behavior? That specific UI you are showing is kind of familiar looking, but I can't quite place it. Am I missing something obvious here?

**Comment by kuznetcoff777** [comment]
"it looks like the burned-in time is the current time of day in the MSK timezone, correct?" - yes
"What browser are you using?" - ff, chrome latest
"Do you have a custom UI with different time drawing behavior?" - seems to be yes, i will try to find out more about it in several days

**Comment by kuznetcoff777** [comment]
Here it is
var playheadTime = shakaPlayer.getPlayheadTimeAsDate()
return Math.floor(playheadTime / 1e3 - opts.liveTimeDelta)

where liveTimeDelta - is our constant 10 seconds

**Comment by kuznetcoff777** [comment]
@theodab ?

**Comment by TheModMaker** [comment]
`availabilityStartTime` represents the wall-clock time the live stream started.  So the presentation (or media) time of 0 is the same as the `availabilityStartTime`.  So:

```js
video.currentTime = 726163;
availabilityStartTime = Date.parse('2019-06-11T05:53:55Z') / 1e3;  // 1560232435;
currentTime = video.currentTime + availabilityStartTime;  // 1560958598
timeAsDate = new Date(currentTime * 1e3);  // Wed Jun 19 2019 08:36:38 GMT-0700
```

But the burned in time shows `18:36:28`.  So my guess is your encoder is off by 10 seconds.

**Comment by kuznetcoff777** [comment]
No, encoder is ntp synchronised totally.

"availabilityStartTime represents the wall-clock time the live stream started" - not fully correctly:
From ticket https://github.com/google/shaka-player/issues/1853
"Segment availability start time
latest time instant in wall-clock time at which a Segment becomes an available Segment"
So when we use 5-sec segmens and begin to make mpeg-dash, AST = time of when first segment was writed totally and player can play from only ther second segment and time in time line is shifted ahead for 5 seconds, It means that shaka player takes AST for timing on timeline do it not so correctly, thats why we have to put some shift in config."

And from the beginning of this ticket:
"In MPD file i see availabilityStartTime="2019-06-11T05:53:55Z" (by standard it have to be 2019-06-11T05:53:50Z, it is encoder bug and fixed in newer versions, but anyway it does not matter now)"

Shaka interprets avaailablity start time not correctly, not by standard

**Comment by TheModMaker** [comment]
The `@availabilityStartTime` attribute is not the same as the `Segment availability start time`.  The former is the anchor point specifying the start of the presentation (DASH table 3):

> For `@type='dynamic'` this attribute shall be present. In this case it specifies the anchor for the computation of the earliest availability time (in UTC) for any Segment in the Media Presentation.

The `Segment availability start time` is the start time that a *specific segment* becomes available.  When a specific segment is available is when the live edge of the stream passes its end time.  (DASH section 5.3.9.5.3):

> For services with MPD@type='dynamic', the Segment availability start time of a Media Segment is the sum of
> - the value of the MPD@availabilityStartTime,
> - the PeriodStart time of the containing Period as defined in 5.3.2.1,
> - the MPD start time of the Media Segment, and
> - the MPD duration of the Media Segment.

**Comment by kuznetcoff777** [comment]
"In this case it specifies the anchor for the computation of the earliest availability time (in UTC) for any Segment in the Media Presentation."- does it mean to be the very beginning of the event start?

So it seems to be means encoder soft does not correctly put availabilityStartTime in mpd

**Comment by dudeskidaddy** [comment]
availabilityStartTime is the wall clock in Z when the MPD manifest is made available and the first segment has been written.   The segment duration might *not* match the segment duration in the Dash Settings if the GOP aligned boundary doesn't match.  This can typically happen if the framerate, GOP, fragment length and segment length do not align.   You are probably seeing a 10 second difference because the duration of that segment was automatically adjusted and is not 5 seconds, but is now 10 seconds.  If you cat the init mp4 and first video mp4 and run media info you will probably see this.  Sometimes this happens if frame rate = follow input and the user isn't in control of the output framerate.  In this case the muxer will adjust as needed.  If you set the fragment lengh = 3, segment length = 6, gop =90 and frame rate = 30, this will produce 6 second segments.  The first segment is created exactly 6 seconds into the encode and the AST= wall clock when that first segment and first instance of the manifest was written.

**Comment by kuznetcoff777** [comment]
It seems to be we speak about different things, as TheModMaker says AST and Segment AST has different meanings. And i just want to find out what is AST in manifest file. Now i think that it must be time of when encoding started. But in standard it is described not so obviously:
"For @type='dynamic' this attribute shall be present. In this case it specifies the anchor for the computation of the earliest availability time (in UTC) for any Segment in the Media Presentation."

**Comment by dudeskidaddy** [comment]
AST is not when encoding started.  It is when the  first segment is available as it says in the last sentence of your message.  

The segment start time refers to the start time of each arbitrary segment in the playlist.  Each segment has its own segment start time.  

You are getting an AST of 10 seconds after the encoding started because the segment is 10 seconds long and isn’t available until the entire segment has been written.

Brian

**Comment by kuznetcoff777** [comment]
@dudeskidaddy if you are right about "AST is not when encoding started. It is when the first segment is available as it says in the last sentence of your message.", then shaka does not interpretate correctly availabilityStartTime. But @TheModMaker says that AST and Segment AST is different things.

Look at my issue description carefully, i described everything with details.

**Comment by TheModMaker** [comment]
@dudeskidaddy As I stated in my [comment](https://github.com/google/shaka-player/issues/1986#issuecomment-503684559) above, the AST is just used as a reference point.  It doesn't *have* to be anything.  It is just used to determine availability and to align the presentation timeline with the wall clock.

The AST is the same as presentation time 0.  So a segment starting at 30 seconds has a wall-clock time of `AST + 30`.  It doesn't matter what the value of AST is so long as it is consistent with the presentation timeline.
