### ISSUE TITLE
Shaka player crash when playing Live stream with 5hr DVR window - Linux/Chrome/Shaka 2.5.2

### ISSUE THREAD

**Issue by rohitsw-g** [google/shaka-player#1990]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
2.5.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**

**Are you using the demo app or your own custom app?**
Demo App

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome on Linux

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://dai.google.com/linear/dash/event/5JICoZBiRaOjaJsloSUWBw/manifest.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

**What did you do?**
After running the stream for a while (non-deterministic, somewhere between 30mins to 2hrs), the player crashes. No apparent information is available in the console.

**What did you expect to happen?**
Playback should continue uninterruped.

**What actually happened?**
Player crashes.

**Comment by rohitsw-g** [comment]
![_Player_Crash](https://user-images.githubusercontent.com/51722349/59304419-3b3e4400-8c66-11e9-8270-b017adf3af0f.png)
![Console_Logs](https://user-images.githubusercontent.com/51722349/59304429-3f6a6180-8c66-11e9-85ed-e661595fd1c7.png)

**Comment by theodab** [comment]
I tried running the stream on macOS to see if the problem happened there. I ran it for a bit over 2 hours and nothing strange happened. Tomorrow I'll try on Linux.
In the meantime, you can try running in Very Verbose logging mode. That might give you more information.

**Comment by joeyparrish** [comment]
When it crashes, do you have the JS debugger open?  If so, then the debugger itself is keeping network requests in memory, which will eventually crash the page while live streaming.  To work around this, go the network panel and click the red circle to stop recording requests, then click the clear button to remove the ones that are still in memory.

**Comment by rohitsw-g** [comment]
Sorry for the delay. I was able to repro the crash on Linux+Chrome even without any debugging enabled.

**Comment by TheModMaker** [comment]
I can reproduce.  Note this is a *browser* crash, not a Shaka Player crash.  This is caused by the browser and there may be little we can do to help.  Having DevTools open with the Memory tab shows a small usage of ~100MB being used and it is fairly consistent through playback.  Looking at Chrome's crash reporter, it says this is OOM, but I don't think this can be helped from JavaScript.  This is probably a memory leak in Chrome.

To reproduce, be sure to have the tab be "active".  This means you either need to have the tab visible, or have a PIP window open.  Otherwise the tab may become inactive and the browser will more aggressively free things and reduce JavaScript timers.

**Comment by joeyparrish** [comment]
Closing this stale external (non-Shaka) issue. If you disagree, please reply with @shaka-bot reopen, and it will be automatically reopened.
