### ISSUE TITLE
Custom license request by delegation

### ISSUE THREAD

**Issue by hdodev** [google/shaka-player#1995]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**Is your feature request related to a problem? Please describe.**
Our license server is accessible only via a request done by a custom library (for security motivations). 

**Describe the solution you'd like**
What works correctly, is to enrich (Query/Header/Body) the request done by Shaka, in the registerRequestFilter. We can then parse and make what is needed in the registerResponseFilter.
The idea is to be able to tell the Player we d'like to do the request ourself, having access to the challenge (request.body) needed for licence request, and once done to trigger ourself the registerResponseFilter to get licence back.

**Describe alternatives you've considered**
Maybe we can try to directly overwrite the class in which the request is really done in order to user our secure library there. But maybe there is a risk to corrup manifest/chunks requests and so on. Please let me know.

**Additional context**
N/A

**Comment by chrisfillmore** [comment]
Looks like this is the same as #1075. The solution for you is to register your own networking plugin and delegate from there.

**Comment by theodab** [comment]
If your concern is that you need to handle the process of querying the license server yourself, then I agree with @chrisfillmore that a networking scheme plugin seems like the best solution here. You can register those via `shaka.net.NetworkingEngine.registerScheme`. See `lib/net/http_xhr_plugin.js` if you want an example of an existing scheme plugin for reference.
When providing the license server to Shaka Player, you'd just provide a fake URI with a custom scheme, and register a scheme plugin to that scheme. Then you can make a request to the real URI, in your own code.

**Comment by TheModMaker** [comment]
Also note that you can change the headers and body of the request from a request filter.  What else would you need to change from the request that can't be done from the request filter?

**Comment by chrisfillmore** [comment]
@TheModMaker I think the issue for a lot of Shaka's clients is that they don't control various other aspects of their infrastructure (in the author's case, he needs to use a custom SDK to integrate with his license proxy). As you might imagine, this is common in an enterprise context. Also these enterprise-level solutions often consider many other client platforms (mobile and set-top-box), which have bigger user bases than web browsers. So it can be hard, as web developers, to appeal to our headend teams to support us.

NetworkingEngine poses persistent architectural difficulties for my team. If I had my way, I would rearchitect it so that:
- There was a business layer separating all other Shaka components from NetworkingEngine directly, so that clients could implement custom business logic if needed (for example, delegating networking externally where required)
- Networking logic and server business logic were separate. Currently the networking plugins evaluate server status codes, which is wrong, because this is highly application-specific and resides in a completely separate logical layer from networking.

IMO network filters support only trivial use cases. Relying on these filters for any more complex behaviour results in a client wrapper around Shaka filled with egregious hacks. It would be vastly simpler for clients if Shaka supported delegated networking.

**Comment by TheModMaker** [comment]
Then you can write your own scheme plugin, or replace the http/https versions.  The scheme plugin is what handles the network request and converts the HTTP codes to error objects.  So you could write your own scheme plugin to handle the network request and change the request how you like and send it from your custom SDK.  You can also handle the response codes as you like.  You can take a look at the [OfflineScheme](https://github.com/google/shaka-player/blob/master/lib/offline/offline_scheme.js) for a minimal example.

So you can either (a) replace the http/https schemes with your own, or (b) use a fake scheme and handle that your self.  For just drm, when you configure the license server, use your fake scheme instead.  Something like `fake://foo.com` will make us use your `fake` scheme plugin, but the segment/manifest requests will still go through the normal http/https schemes.

**Comment by hdodev** [comment]
Hi every body, and thanks for all the answers.

Yes in my case, for security reasons, some secret IDs are embeded in an internal obfuscated library, and are required by a proxy in front of licencer...

Anyway, the networking scheme plugin solution you described works correctly. I can close this feature.
