### ISSUE TITLE
map audio bitrates to video bitrates

### ISSUE THREAD

**Issue by kuznetcoff777** [google/shaka-player#2001]
Hi! If i have several mpeg-dash video resolutions/bitrates and several audio bitrates, can i map then somehow? for example 
lowres audio - to lowres video
hires audio - to hires video

I dont want to get situations when video is hires and audio is lowres.

**Comment by ismena** [comment]
Hmm, I don't think dash supports specific audio/video combinations the way hls does.
@TheModMaker, amiright?
You could write logic to manually prefer certain variants to the others, but that won't work for abr.

If you're open to re-packaging your content as hls, that is certainly an option there.

**Comment by TheModMaker** [comment]
In DASH, you specify a list of audio tracks and a list of video tracks.  There isn't really a way to specify that some audio tracks go with specific video tracks.

One option you could do is write a custom AbrManager class that proxies to our version.  It could filter out the variants (audio+video pairs) you don't want to play and let our AbrManager pick from the remaining.

Also note that we'll play the highest quality we think we can play.  So if we can play high resolution video, we will probably pick the high resolution audio since it only costs a little bit more.  In fact, we will usually always play the high resolution audio unless we can't play with that little bit more bandwidth.  Having multiple "resolution" for audio is fairly rare since the difference is usually small.

**Comment by kuznetcoff777** [comment]
Strange that hls supports it it manifest, but dash not...
