### ISSUE TITLE
Use file url with "?" cause change in request and error

### ISSUE THREAD

**Issue by grandemestre** [google/shaka-player#2007]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
- Yes

**What version of Shaka Player are you using?**
v2.5.2

**Can you reproduce the issue with our latest release version?**
-Yes

**Can you reproduce the issue with the latest code from `master`?**
-Yes

**Are you using the demo app or your own custom app?**
Demo App

**What browser and OS are you using?**
Windows 10 - Google Chrome 75.0.3770.100 64 bits

**What are the manifest and license server URIs?**
http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-manifest.mpd

**What did you do?**

When I use an mpd file url with "?" it stops to provide it working properly. Instead of making a GET request it starts to do HEAD request and does not GET.
http://example.com/curl/index.php?url=http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-manifest.mpd

**What did you expect to happen?**
What in a URL with or without "?" a GET request was made
http://example.com/curl/index.phpurl=http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-manifest.mpd

**What actually happened?**
When I use an url file with "?" a HEAD request is made instead of GET and this causes a problem because it does not have the body. Do I remove "?" works correctly.
![shaka](https://user-images.githubusercontent.com/18264177/59964439-012b3880-94d7-11e9-9026-a76ae966a785.jpg)

**Comment by theodab** [comment]
For the "with ?" URL, our manifest parser is detecting the file extension of the URL as `php`. That is a file type that does not have a manifest parser associated with it, so it then makes a `HEAD` request to try to figure out what the content type is based on the `content-type` header in the response.
In the "without ?" URL, it is able to successfully tell that the file extension is `mpd`, and thus does not need to make the `HEAD` request.

So, really, the problem is that our code does not expect the file extension to show up within the URL parameters. I don't know if this is a common enough problem for us to fix; we could, as a fallback, look at any file extension inside the URL parameters, but that would probably be over-fitted to your specific use-case. For instance, it could cause problems if someone has a non-manifest URL inside their URL parameters (like an URL pointing to some extra metadata).

But you should be able to fix this pretty easily on your end! Try passing in an explicit `mimeType` when calling `Player.load`. It's an optional argument, after the optional `startTime` argument. So you'd do something like...
```js
myPlayer.load(url, undefined, 'mpd'); 
```

**Comment by joeyparrish** [comment]
Instead of `'mpd'`, use the DASH MIME type of `'application/dash+xml'`.  That parameter does not accept a file extension.

**Comment by joeyparrish** [comment]
As for the extension being part of the path vs the URL params, that part is working as intended.  Extensions are part of the path.  URL params may contain another URL, but that is not part of the resource path.
