### ISSUE TITLE
Load is interrupted when subtitle fails to load

### ISSUE THREAD

**Issue by thecuriousdev** [google/shaka-player#2022]
Package: HLS

The load is getting interrupted when the subtitle (specified in the manifest) fails to load. Getting a SEV 2 error and not able to recover from it. This looks very fragile, wanted to understand why it's a critical error when we can continue the playback without the subtitle. Or is there a way to recover from this?

**Comment by joeyparrish** [comment]
@thecuriousdev, please provide us with more information so that we can reproduce the issue.  It's hard to guess what's wrong without the ability to see the problem ourselves.

Here's our bug template in brief:


**What version of Shaka Player are you using?**


**Can you reproduce the issue with our latest release version?**


**Can you reproduce the issue with the latest code from `master`?**


**Are you using the demo app or your own custom app?**


**If custom app, can you reproduce the issue using our demo app?**


**What browser and OS are you using?**


**What are the manifest and license server URIs?**
*NOTE:
  You can send the URIs to <shaka-player-issues@google.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.  You can copy the URI of the demo app to send us the
  exact asset, licence server, and settings you have selected there.*


**What did you do?**
*Steps to reproduce the bug*
