### ISSUE TITLE
Help with "large gap" detection

### ISSUE THREAD

**Issue by vto5623** [google/shaka-player#2025]
Could you please help me understand why the player detects a "large gap" between the 2nd and the 3rd segments in the following sample?

Player: https://shaka-player-demo.appspot.com (v.2.5.3 debug on Firefox and Chrome Iron)
Asset: https://demo.yospace.com/vincent/dash/3956/manifest.mpd (scrub to far left when the asset starts to play from the beginning)

> Ignoring large gap at 534072.936696 size 1.0903039999539033
gap_jumping_controller.js:235:6

Sounds like there could be a gap at the end of the 2nd segment (ie. t=5340657870920) because the gap is detected at "534072.936696" which is within the 2nd segment "boundaries".

Could you please confirm that?

Many thanks.

**Comment by joeyparrish** [comment]
What this means is that there is a gap of size 1.090 seconds at time ~534,072.937 seconds in the buffer.  The buffer in question is an intersection of the buffered audio and video streams, and the timestamps are after any period or presentation time offsets are applied and the segments are demuxed by MediaSource.

This gap detection isn't based on the manifest at all, but rather on the demuxed/buffered media at the MediaSource level.  It could be that your manifest is somewhat inaccurate.  This is common at period boundaries, and I noticed that segment 2 is the end of period 1 and segment 3 is the start of period 2.

You can use tools like [thumb.co.il](http://thumb.co.il/) to parse the mp4 files and see the timestamps in them if you'd like to investigate the timestamps in your content.

Shaka Player, by default, assumes that a sufficiently large gap is a mistake in the content encoding, and that it would be better to make sure the developer notices by stopping and issuing a warning.  A smaller gap is jumped automatically, as this can be caused by a rounding error.

I think in this case, it's likely true that this is a mistake in your content encoding/packaging.  So I strongly recommend you look into fixing your packager/encoder or filing a bug against the vendor of your packager/encoder.

You can control Shaka Player's behavior, though, if you want.  You can change the threshold of what's considered a "small" gap with `player.configure('streaming.smallGapLimit', limitSizeInSeconds)`.  The default is 0.5 seconds.  You can also ask the player to skip all gaps, regardless of size, with `player.configure('streaming.jumpLargeGaps', true)`.  You could also ask the player to jump individual large gaps by listening for the `largegap` event from the player and calling `event.preventDefault()`.

Does this help?

**Comment by vto5623** [comment]
Yes this helps.

I will check all these segments and see whether segments before/after the Period boundary are correct or not.

**Comment by joeyparrish** [comment]
> I need to leave this ticket open though because I want to be sure that the player is not seeing a fake data gap and stalling for no reason.

Sounds good.  @shaka-bot will ping the issue in a few days to see if you still need help, and will then close it a few days later if you don't reply.  If that happens, though, it will give you instructions on how to reopen the ticket.

**Comment by vto5623** [comment]
I will close this ticket now since we found genuine data gap in some segments.
Many thanks for your help.

**Comment by joeyparrish** [comment]
We're always happy to help!
