### ISSUE TITLE
Some chrome play DRM streams reported LICENSE_RESPONSE_REJECTED (code 11)

### ISSUE THREAD

**Issue by hongfeih** [google/shaka-player#2038]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.3

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
demo app 

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome 75.0.3770.142 on Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
https://shaka-player-demo.appspot.com/demo/#audiolang=zh-CN;textlang=zh-CN;uilang=zh-CN;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;panel=HOME;build=uncompiled

**What did you do?**
Just play

**What did you expect to happen?**
play to end

**What actually happened?**
Just some Chrome reported LICENSE_RESPONSE_REJECTED (code 11), while most others are good.
Firefox is good.

![image](https://user-images.githubusercontent.com/2166532/61353393-4d815280-a8a2-11e9-83f1-e6fca6bf370c.png)

**Comment by theodab** [comment]
I tried to reproduce this problem on our Windows 10 test machine, which is also running Chrome 75.0.3770.142, and did not see any problems after several attempts. Is this a rare issue, or does it happen to you consistently?

The `LICENSE_RESPONSE_REJECTED` error means that the license was successfully downloaded, but it failed in some way when the browser's MediaKeySession tried to process the data. According to the error message, the problem was "operation aborted". I don't know what would cause that to happen offhand, though; without being able to reproduce it, or find any online references for that specific error, I can't say anything more conclusive.

**Comment by hongfeih** [comment]
Thanks @theodab.
Right, it only happened on few machines (3 found issue among 100+), and it keep happening on these 3 machines. I can't reproduce it either on my machine.
Will update when we find more about this error, thanks again.
Maybe I can close this issue for now...

**Comment by joeyparrish** [comment]
@hongfeih, I looked up code 11 in some internal Widevine documentation, and it's deprecated.  The devices which are failing might be using an outdated version of Chrome or an outdated/unsupported version of the Widevine CDM.  Try installing updates to the browser and all extensions and see if that helps.

**Comment by hongfeih** [comment]
Thanks @joeyparrish.
Chrome is updated (75.0.3770.142), Widevine CDM module is also latest (4.10.1440.18), no additional extensions installed.
Even strange, one machine here was good last Friday, but not good now. 
Also checked with dash.js, also not working. 
Agreed should be cdm error on particular machine.

**Comment by joeyparrish** [comment]
I still can't reproduce the issue on Chrome 75 on Linux.  (I haven't retested on Windows yet.)  I'll go talk to the Chrome CDM team and see if I can get any tips on what might cause this.

**Comment by joeyparrish** [comment]
The Chrome CDM team has just shown me that system code 11 was removed in 2015.  So that can't possibly be the issue.

You screenshot doesn't show code 11.  It says "operation aborted".

If you can still reproduce this issue, can you please give us an updated screenshot showing the full error code, and preferably also JS console logs?

**Comment by hongfeih** [comment]
I saw one machine which was reproduced this issue just recovered today, should not be a issue of shaka-player, so I'll close it, thanks.

**Comment by joeyparrish** [comment]
Thanks for letting us know!
