### ISSUE TITLE
Angel One fails with "Invalid State Error" on Edge

### ISSUE THREAD

**Issue by fcolley** [google/shaka-player#2052]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Build: v2.5.4-master-7-g7c271bab

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Shaka Player Demo

**What browser and OS are you using?**
Environment: Win10 Edge 

**What did you do?**
Steps:
1. Navigate to: https://nightly-dot-shaka-player-demo.appspot.com
2. Launch video asset and select "Angel One"
3. Wait until the end of the video (which is about a minute long)

Actual Result: 
After ~36-39 seconds, the video stops and the console output contains this error: 
"Media Source Opperation Threw (Invalid State Error)" this is listed as "Error data[0] exception"

Expected: 
This content would play until the end (FYI -- this is unencrypted content)

Note:
- Surprisingly, this does not happen with Win10 Internet Explorer
- Also, if you download the content in Edge it plays until the end

**Comment by TheModMaker** [comment]
I don't see the error, but I do see the stream stop at around 39 seconds.  It appears like the segments are being appended, but they don't show up as buffered in the browser.  If I disable buffering handling, the browser still stops at the end of the buffered range (so it's really unbuffered).  The `appendWindowEnd` is set correctly, so they aren't being dropped.

One thing I notice is this doesn't happen with the MP4 version, only the WebM version.  I thought Edge disables VP9 support unless there is hardware support; so it may be that this policy changed recently and now we are playing VP9 and there is something Edge doesn't like with it.  I'm thinking this is a platform bug.

I've also confirmed this happens when we download too.  The reason it doesn't appear to in the default demo is because by default it (a) picks MP4 when downloading and (b) only downloads 480p, which doesn't have this problem.  It definitely happens with the 576p version.

**Comment by joeyparrish** [comment]
@TheModMaker, we could try re-encoding and re-packaging to another URL with the latest libvpx and ffmpeg, just to make sure it's not an encoding bug.

**Comment by joeyparrish** [comment]
I'm going to repackage this content now to test the theory that something was wrong with it.

**Comment by joeyparrish** [comment]
The repackaged version plays through to the end on Edge, so I'm going to assume that the version we packaged in June 2019 had some minor encoding issue that disagrees with Microsoft's decoders.

There was a small issue with the new version not getting all the correct resolutions, though, so I will fix some small bugs in Shaka Streamer and test again before updating the official copies of "Angel One" in our demo.

**Comment by joeyparrish** [comment]
I fixed a few Streamer bugs (fixes yet to be reviewed) and replaced "Angel One" with a fresh re-encode using that.  Everything is working correctly on Edge now.
