### ISSUE TITLE
Download livestream

### ISSUE THREAD

**Issue by Aeroxander** [google/shaka-player#2080]
I would like to download a livestream through the client, but in the Shaka Player demo this option isn't available, would this still be possible?

**Solution**

I would like to download a livestream (or at least once the livestream is finished)

**Alternative**

I could just develop a download function in my server to make it work through there instead of client-side...

**Additional context**

I'm creating a livestream that renders very slowly (1 FPS) while the actual video footage is 30fps. 
I was just wondering if Shaka Player handles this well and if downloading the stream is possible.

I know livestreaming works through fragmented videos and as the user has downloaded them anyway, it would be nice if the user could download the entire stream at the end.

But I wouldn't know if this is possible as only every 30 seconds a new frame is created.

Otherwise I will just use websockets to send an image every second and have the user download the video at the end of the livestream.

**Comment by TheModMaker** [comment]
A live stream is constantly being generated, so we can't really download it (which is why we don't allow it).  We have no way of knowing when to stop downloading.  Also, live streams have different timelines which can cause playback problems; for example, live segments usually have a large timestamp, but when playing VOD, you expect the video to start at 0.

Once a live stream has ended, it should be considered VOD and you should be able to download it fine.  Why not just wait for the end and download it then?

Your content is 30fps but your machine is only generating a frame every second?  If that's the case, the live edge will be moving forward expecting the video to be generated in real time.  The fact that your server is generating slower than real time means you can't watch the live stream as a normal live stream anyway.  So it would be best to wait until it is finished and watch it as VOD.

Is the goal to be able to generate slowly over time, but watch what has been generated already while you wait?  What you could do is use a normal live stream with a large (or infinite) availability window so all the content is available.  Then seek to the start of the live stream and watch from there.  Eventually you'll get 404 errors once you hit the end of what is available.  The downside being a large timeline of unavailable content; but you could use a custom UI to only display a timeline of content that is already generated (using signaling from your server to tell what it has generated up to).

**Comment by Aeroxander** [comment]
Thanks for letting me know, I'll be happy enough with being able to download it at the end!

And exactly, the server is just rendering GPU heavy images slowly and my plan is to stitch them frame-by-frame with FFMPEG, then I will probably upload the MPD and fragmented MP4's to AWS S3 as they are created

I wouldn't know exactly how to create a large availability window, can I configure that in Shaka Player?

**Comment by joeyparrish** [comment]
> I wouldn't know exactly how to create a large availability window, can I configure that in Shaka Player?

It depends on what software is writing the MPD.  It's an attribute in the MPD that you'd want to change for this.  For example, there's a command-line option for it in Shaka Packager.

You can also ask the Player to override what's in the manifest:

```js
player.configure('manifest.availabilityWindowOverride', Infinity);
```
