### ISSUE TITLE
Multiaudio HLS_COULD_NOT_PARSE_SEGMENT_START_TIME

### ISSUE THREAD

**Issue by bencecsire** [google/shaka-player#2095]
Dear Support,

We are using JWplayer to playback streams. We have chromecast sync issue with multiaudio hls streams. I've reached Google Support and they recommended to open a ticket here.
This is my ticket on Google issuetracker: https://issuetracker.google.com/issues/138327332

This is the manifest I use: https://wowza35-vhg.connectmedia.hu/chromecast/TVE-016_2a_hls_EN.smil/playlist.m3u8
I've only tried with your demo app, and I could not play the stream too, because of HLS_COULD_NOT_PARSE_SEGMENT_START_TIME. Please, can you help me find out what could be the problem? 

With JW player I can play the stream in browser, also I tried other demo pages and it is working (Bitmovin, Theo, Wowza player). However maybe the issue is with packaging, just other players accept this type of manifests too. Can you help me find out what could be the problem, why I can't playback this stream with Shaka Player?

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Only demo app

**Can you reproduce the issue with our latest release version?**
Haven't tried

**Can you reproduce the issue with the latest code from `master`?**
Haven't tried

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Windows 10, Google Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://wowza35-vhg.connectmedia.hu/chromecast/TVE-016_2a_hls_EN.smil/playlist.m3u8

**Comment by joeyparrish** [comment]
@bencecsire, thanks for your report.  If you check back in on the Google issue tracker, you'll see an update from the Cast team that they made a mistake, and this particular content is not being played in Shaka Player on Chromecast.  They are using a different player in your case.

The reason it fails to play on Shaka Player is because we try to extract segment timestamps in our HLS parser, and this is an error-prone system, especially for text streams.  We are working on refactors that will correct this, but they are not ready yet.  You can track #1563 and #1558 for this work, if you're curious.

But since your actual issue is with the Cast team's player, I'll close this issue and direct you back to Google's issue tracker to get help from the Cast team.  Thanks!
