### ISSUE TITLE
Support live streams

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#21]
Shaka Player should support DASH live content.

**Comment by TobbeMobiTV** [comment]
The livesimulator developed for DASH-IF, http://vm2.dashif.org/livesim/testpic_2s/Manifest.mpd plays in dash.js and in the dev branch of ExoPlayer. Would be nice if you could make it play in shaka-player as well. More info available at http://vm2.dashif.org/

**Comment by joeyparrish** [comment]
Hi Torbjörn,

Thanks for the link!  We will be sure to make that part of our testing as we work on this feature.

**Comment by sanbornhnewyyz** [comment]
Can I just get clarification on 404 errors? If I use the stream @TobbeMobiTV provided then I get a ton of 404s but the stream appears to be playing back fine. I noticed in deb2100
that you're ignoring these. Does that mean these 404s are acceptable and we can safely ignore them as long we we're getting playback?

**Comment by joeyparrish** [comment]
Yes, 404s are not ideal, but tolerable.  In the case of a live stream, a particular segment yielding 404 means the server has not made it available yet.  This could be a result of bad clock sync, or it could mean that we are trying to buffer ahead of the live edge.  This should not be fatal to playback.

Depending on suggestedPresentationDelay, minBufferTime, and the particular style of manifest, we may or may not see 404s in v1.3.0.  Our Stream and SegmentIndex classes were designed before we supported live content, so we sometimes request segments which are not yet available.

We plan to refactor streaming and indices in 1.4.0 to fix this, after which only clock sync issues and broken manifests should be able to cause a 404.  Even then, we will still tolerate 404s and issue clock sync warnings rather than abort playback.

**Comment by sanbornhnewyyz** [comment]
Great, thanks a lot of the explanation.

**Comment by sanbornhnewyyz** [comment]
Has shaka been tested with live encrypted content? I've hit a snag trying to play live encrypted content. I can't see where the problem is so I was wondering if you've done this before. This might help me to narrow down the source of the problem.

**Comment by joeyparrish** [comment]
Yes, it has, both with static keys and with key rotation.  From an EME point of view, live content is nothing special.

**Comment by sanbornhnewyyz** [comment]
Okay, that's what I figured but I wanted to check because I can't figure out why it's breaking down for me. Thanks.

**Comment by TobbeMobiTV** [comment]
I'd just like to add that my live simulator is meant as a reference test stream and is very strict on the timing. The segments are only made available during the exact interval which is defined by the DASH standard depending on the availabilityStartTime, startNumber, segmentDuration, and timeShiftBufferDepth. If the request is too early or too late, the simulator actually sends back the amount of time mismatch in the body of the 404 response.

To avoid 404's due to bad timing, the first thing is to make sure about is that the server and client clocks are synchronized. This can be done using the new DASH UTCTiming mechanism. The simulator supports this direct and head mode in its development version at http://vm2.dashif.org/livesim-dev/utc_direct-head/testpic_2s/Manifest.mpd.
