### ISSUE TITLE
HLS Event Playlist: Getting QUOTA_EXCEEDED_ERROR when seek to a different position 

### ISSUE THREAD

**Issue by thecuriousdev** [google/shaka-player#2121]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
2.5.4

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `master`?**
YES

**Are you using the demo app or your own custom app?**
Tried both

**If custom app, can you reproduce the issue using our demo app?**
YES

**What browser and OS are you using?**
Chrome 76 MacOS 10.14, But reproducible in other platforms as well

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Unfortunately, I can't share this stream publicly :( 
Note: Stream is working fine in other players.

**What did you do?**

Tried playing an HLS event playlist, and seeked backward to a different position.

**What did you expect to happen?**
The content should play.

**What actually happened?**

Shaka kept downloading and appending segments to the buffer, eventually got a QUOTA_EXCEEDED_ERROR.
I tried debugging the issue. Few observations,  
1. The source buffer is not triggering any error on appendBuffer
2. `bufferedAhead` and `SourceBuffer.buffered` remained 0 hence the streaming engine kept requesting for new segments.
3.  If I update child manifest with `#EXT-X-PLAYLIST-TYPE:VOD`, it'll work fine
4. handleQuotaExceeded_ method in streaming_engine is working as expected

**Comment by thecuriousdev** [comment]
@shaka-bot reopen

**Comment by thecuriousdev** [comment]
I've uploaded a test stream `https://thecuriousdev.github.io/trailer/master.m3u8` please have a look

@shaka-bot reopen

**Comment by thecuriousdev** [comment]
I've attached a screen recording of the issue as well,
[shaka-player-issue-edited.mp4.zip](https://github.com/google/shaka-player/files/3603847/shaka-player-issue-edited.mp4.zip)

**Comment by anuragkalia** [comment]
I am also facing the exact same issue. Is there any resolution for this?

**Comment by theodab** [comment]
Looking at your example manifest, it seems that `StreamingEngine` is trying to buffer all the way to the live head, no matter where you tell it to seek to. So you're getting a `QUOTA_EXCEEDED_ERROR ` when you seek back far enough that it tries to over-fill the buffer.
Not sure why yet. I'll need to look into this more.

**Comment by theodab** [comment]
It looks like that's happening because, for event playlists, when you perform an unbuffered seek, we are not re-loading the initialization segment.
Specifically, we get the initialization segment from the EXT-X-MAP tag. If there is no EXT-X-MAP tag, we assume that there is no initialization segment.
Reading up about event playlists, segments cannot be removed from them, so presumably it's safe to use the first segment as an initialization segment. Like, there won't be a rolling window, such that the first segment will drop out eventually.

So I think this is probably safe to classify as a bug, anyway? I'll have a CL out for review for this soon, ideally. Sorry for the wait!

**Comment by anuragkalia** [comment]
I did not see any update on this ticket. When can we expect v2.6 of shaka to be released?

**Comment by joeyparrish** [comment]
For a discussion of v2.6 release date, see: https://github.com/google/shaka-player/issues/2208#issuecomment-548474623

Please note, however, that this issue is a bug, and a fix for it would be eligible for cherry-pick to v2.5.x .  So you don't necessarily have to wait for v2.6.  It really just depends on how soon we can determine the cause and fix it.

**Comment by theodab** [comment]
After much investigation, it is looking like this is a problem with mux.js, the tool that we use to turn `ts` content into `mp4` content for platforms that do not support `ts`. For whatever reason, if you perform an unbuffered seek backwards with multiplexed `ts` content, the resulting `mp4` outputs will start having empty audio tracks. This causes MediaSource to not register the output as being within a buffered range, and thus we keep buffering further and further ahead until we go past our quota.
This also means that, if you perform a very short unbuffered seek, such that it doesn't go over the quota, it will successfully start playing again, but without audio.

I have filed an issue for this on the github page for mux.js: https://github.com/videojs/mux.js/issues/312
You can track the progress of that bug there.

In the meantime, we can theoretically fix this by tearing down and re-creating the transmuxer between each operation. That seems like a very inefficient solution, however, so I'm not sure if it would be a good idea to implement.

**Comment by joeyparrish** [comment]
Closing this stale external (non-Shaka) issue. If you disagree, please reply with @shaka-bot reopen, and it will be automatically reopened.

Also, I'm reasonably sure this was fixed in today's 5.5.3 release of mux.js.
