### ISSUE TITLE
"b.player.TB is not a function" message when casting video from ChromeCast Eureka

### ISSUE THREAD

**Issue by MayreLew** [google/shaka-player#2130]
Pre-conditions:
Have a Chromecast Eureka device set up on a TV set and ready to cast.

Device:  Macbook Air
Chrome Version 75.0.3770.142 (Official Build) (64-bit)

TO REPRO:
1. Open a Chrome Browser and enter the following URL, try all three:

wvpl release ubuntu:
https://shaka-player-demo.appspot.com/demo/?#asset=https://storage.googleapis.com/wvmedia/cenc/h264/llama/llama_sd.mpd;license=https://ats.sandbox.google.com/cloud?sdk=LICENSE_SDK_WVPL&build=RELEASE&os=UBUNTU;lang=en-US;logtoscreen;trickplay;play;build=compiled;noinput

wvdrm release ubuntu:
https://shaka-player-demo.appspot.com/demo/?#asset=https://storage.googleapis.com/wvmedia/cenc/h264/llama/llama_sd.mpd;license=https://ats.sandbox.google.com/cloud?sdk=LICENSE_SDK_WVDRM&build=RELEASE&os=UBUNTU;lang=en-US;logtoscreen;trickplay;play;build=compiled;noinput

wvpl release centos:
https://shaka-player-demo.appspot.com/demo/?#asset=https://storage.googleapis.com/wvmedia/cenc/h264/llama/llama_sd.mpd;license=https://ats.sandbox.google.com/cloud?sdk=LICENSE_SDK_WVPL&build=RELEASE&os=CENTOS;lang=en-US;logtoscreen;trickplay;play;build=compiled;noinput

2. Click on the "cast" feature to cast video onto TV.

RESULTS:
A message appears on the browser window stating:  ""b.player.Tb is not a function"

Please see attached screenshot.
![Message on the Shaka Player window with Chromecast Eureka](https://user-images.githubusercontent.com/51837636/64055840-f5e23200-cb43-11e9-88a0-8daeb8036688.JPG)

.

**Comment by TheModMaker** [comment]
This reproduces with any asset and with any Chromecast version.  It looks like some function is getting renamed incorrectly.  We are probably calling a non-exported method during this path.  It only happens for Release compiled mode, not for uncompiled mode or Debug compiled mode.

**Comment by TheModMaker** [comment]
The good news is this only affects our UI, so people using custom a UI won't see this error.  The bad news is I think this error has existed for a long while, so I'm not sure why we haven't seen it yet.  We need to be sure to test on compiled mode for releases.

I think the problem is this: https://github.com/google/shaka-player/blob/c0e7a9b62a57f73ef26d511e3d40d2dd0f014cb6/ui/seek_bar.js#L153

It is fetching the seek range from the Player.  When running in compiled mode, the compiler converts this to the internal method name to reduce size; but the object is actually a proxy object, so the function doesn't exist.  Since the UI is compiled with the rest of the code, the compiler thinks it can use the internal method names there.

**Comment by joeyparrish** [comment]
This fix was never cherry-picked to v2.5.x.  I'm working on merge conflicts now.

**Comment by joeyparrish** [comment]
Confirmed that this is still reproducible on v2.5.9.

**Comment by joeyparrish** [comment]
Cherry-picks have been pushed to v2.5.x and confirmed working through both manual and automated tests.
