### ISSUE TITLE
Is the default `initDataTransform` identity function configuration intended?

### ISSUE THREAD

**Issue by mseeley** [google/shaka-player#2136]
👋 there. :)

I'm working on converting our bespoke FairPlay implementation to work within 2.5.5.

While stepping through Shaka's implementation I arrived at this code in `drm_engine`:

https://github.com/google/shaka-player/blob/c0e7a9b62a57f73ef26d511e3d40d2dd0f014cb6/lib/media/drm_engine.js#L1020-L1029

I read this as, if a client has not specified a `playerConfiguration.drm.initDataTransform` callback then the default implementation should be used.

But, it turns out Shaka has a default identity function setup in configuration:

https://github.com/google/shaka-player/blob/c0e7a9b62a57f73ef26d511e3d40d2dd0f014cb6/lib/util/player_configuration.js#L85

So, as a client, if I omit `playerConfiguration.drm.initDataTransform` than the default handling in `drm_engine` is ignored.

I want to believe the default impl in `player_configuration` is unintended based on the `function | undefined` documentation: https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.PlayerConfiguration

Thanks for your feedback.

**Comment by mseeley** [comment]
Providing `drm.initDataTransform` a value of `false` or `null` still results in the default identify function taking precedent.

I've gone ahead and copied the implementation from `drm_engine` into my client implementation. The identity function default isn't appropriate for FairPlay and it's transform requirement.

**Comment by joeyparrish** [comment]
The way our configuration system works, a value of `undefined` means "reset to the default value".  A value of `false` or `null` fails our type checking system (which is looking for `function`), so that call would have no effect.

For example:

```js
// Show the original value
player.getConfiguration().drm.initDataTransform
  (initData) => initData

// Change the value
player.configure('drm.initDataTransform', (initData) => 5)
  true

// Show the changed value
player.getConfiguration().drm.initDataTransform
  (initData) => 5

// Configure an invalid type, which is ignored
player.configure('drm.initDataTransform', null)
  Invalid config, wrong type for .drm.initDataTransform
  false

// This retains the previous value
player.getConfiguration().drm.initDataTransform
  (initData) => 5

// Reset to default with undefined
player.configure('drm.initDataTransform', undefined)
  true

// Show the default value has taken effect again
player.getConfiguration().drm.initDataTransform
  (initData) => initData
```

As far as I can tell, the use of the identity function is an intentional default.  If you want to transform it in some other way, just supply the transformation function you need.

I don't understand what you mean when you say you're copying the implementation into your client.  The implementation of what, exactly?  The identity transform?  Something else?

**Comment by TheModMaker** [comment]
@joeyparrish He is talking about the first code snippet he linked to.  Since the default function exists, it is "truthy" so the first branch is always hit, even with a default.  This means the second branch never happens and the default FairPlay transform isn't applied.  We'll need some way of detecting that the function is a default without checking for "truthy" values since the function always exists under our current model.

**Comment by mseeley** [comment]
Hi @joeyparrish + @TheModMaker. Yep this was it:

> This means the second branch never happens and the default FairPlay transform isn't applied

Thanks a lot for breaking down `configure` behavior @joeyparrish. That was really thoughtful. :+1:

When reusing a `player` object between playbacks would either approach below reset _all_ drm options to their defaults? Or, would we perhaps have to provide `configure` an undefined value for each `drm` key previously configured?

```
player.configure('drm', undefined)
```

```
player:configure({ drm: undefined });
```

**Comment by TheModMaker** [comment]
Yes, either of those options should recursively reset all the DRM configurations.  There is also a `player.resetConfiguration()` method you can use to reset all configurations to the default.

**Comment by mseeley** [comment]
Thank you very much @TheModMaker.
