### ISSUE TITLE
Correct Way to Live-DVR Window Computation

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#2137]
Hi there,

I know, that there are a lot of Discussions about Live Stream with Availibility Window (DVR) and how to handle that correctly. I am not an Expert in these Things, but I would like to know the following, as we have to implement such a Functionality into our Video Players:

- given a DASH LIVE / DVR Manifest (which works), we would like to know the "start" of the LiveStream in Order to compute the correct Seekbar. If the Start is behind the Availibility Window, at least the maximal Start Position, this Stream can have.
- I tried various Ways in Shaka (and also testet the Manifest in SHAKA Debug Player Page), but I was not able to get the right Value. As we control these Streams (the are created with Azure Media Services for Live), we know, when we "started" the Stream and the maximal Window Duration (1 Hour).
- We tried getPlayheadTimeAsDate() and getPresentationStartTimeAsDate() and seekRange() to get the correct Values - but both seekRange() and presentationStartTimeAsDate() only showed a 3 Minute Time Duration. Its 3 Minutes always, even if the Stream is live since 10 or 20 Minutes.
- I can always create a new Stream and send you the Manifest, but what in general would be the correct Way to show the current (possible) Duration of the Stream. (btw, I could not make this Stream run with the correct Seekbar in any Shaka Player, but the Bitmovin Test Player showed the correct Duration) - so somewhere, this Information must be available :)

Thanks!
Christoph

**Comment by TheModMaker** [comment]
> * given a DASH LIVE / DVR Manifest (which works), we would like to know the "start" of the LiveStream in Order to compute the correct Seekbar. If the Start is behind the Availibility Window, at least the maximal Start Position, this Stream can have.

First, you don't need the "start" time to calculate the seek window, you only need the live edge and the duration.  In a live stream, only the last `timeShiftBufferDepth` seconds are available.  The only time the start time matters is either if there is no `timeShiftBufferDepth` or if the stream started recently and there is not enough content yet.  Otherwise the seek range is the current live edge and some time backwards from that.

Secondly, you don't need to calculate anything yourself.  We have a `seekRange` method that returns the current seek range.  This returns times based on `video.currentTime` that are allowed to seek within.  You can use this to control the seek bar.

> * We tried getPlayheadTimeAsDate() and getPresentationStartTimeAsDate() and seekRange() to get the correct Values - but both seekRange() and presentationStartTimeAsDate() only showed a 3 Minute Time Duration. Its 3 Minutes always, even if the Stream is live since 10 or 20 Minutes.

First, the duration of the window is controlled by the `timeShiftBufferDepth` attribute.  So if this value is only 3 minutes, then the seek window will be 3 minutes, at any point in the live stream.  Second, you can have a larger `timeShiftBufferDepth` than there are segments in the manifest.  We are allowed to "remember" segments from old manifest updates to extend the window.  So if your manifest only shows the last 3 minutes of segments, when we first start playing you can't seek further back than that since we don't know about those segments.

**Comment by boredom2** [comment]
Hi there,

thank you for the Insights.
Indeed, the produced MPD Manifest from MS Azure does not include a "timeShiftBufferDepth" Attribute.
Furthermore, I was able to eliminate the Problem at the first Place, as this seems to be an Issue with the CDN (too much Caching).

Nevertheless, what still is an Issue, is that Shaka has a Problem with this Manifest. It is possible to play "the history", but if the Stream is initiated with null - or if we seek to "liveEdge", the Debug Version of Shaka displays: "No Period ID given for Period with start time 0, Assigning a default.". This is followed by "Updating manifest..." and this repeats itself eternally, without ever starting the Stream.
Again - if we seek backwards, then the Stream will play. But any time we try to get to "live" again, the loop begins again and it never stops.
Is there anything we can do about that?

Thanks!
Christoph

**Comment by TheModMaker** [comment]
Could you send us a manifest URL for that issue?  When it is stuck, is the video time moving forward?  If you wait long enough, does it start?
