### ISSUE TITLE
Fetch versus XHR

### ISSUE THREAD

**Issue by riksagar** [google/shaka-player#2147]
Hi all,

I’ve been looking at the Shaka code, and I see there’s an option to use the browser _fetch API_ for segment retrieval. 

But when I looked at the _http_fetch_plugin_ implementation, the code downloads the whole segment and returns a single filled ArrayBuffer on completion.  This implementation seems to have no advantage over XHR.  I was hoping it would progressively deliver bytes as they became available.  Am I misunderstanding how it works?

Reason I’m asking: Our DASH content is in a single fragmented MP4 file.  If fetch would progressively deliver bytes to MSE we could use a single open-ended request for the stream.  It would be more efficient than requesting fragments individually.  It may potentially reduce start time too, as we can deliver the bytes to MSE before the fragment download is finished.

I’d be curious to know what your current fetch-based implementation offers over using XHR?

Thanks,
Rik.

**Comment by ismena** [comment]
Hi @riksagar 
Let me loop in the local fetch/XHR plugin expert. @theodab could you advise?

**Comment by theodab** [comment]
To be honest, we mostly made the Fetch plugin out of a desire to use the newest APIs whenever possible. We don't get any special benefit from using it, really. I guess at some point there was a hope that it might be more clean, code-wise, than XHR, but the Fetch API turned out to not really be much of an improvement for us.

If you want, we could put this down as an enhancement request, to (when appropriate) use the Fetch plugin to progressively download single-file content. I'm pretty sure it'd require some big changes to how we download segments, though, so no guarantees.

**Comment by joeyparrish** [comment]
Initially, we added Fetch support to keep up with evolving web APIs and make sure XHR can some day be deprecated.  To implement low-latency streaming (#1525), Fetch would need to be pipelined through to MediaSource.  This would also benefit you in your scenario, in which you have a single segment in your manifest.

As @theodab points out, though, this could turn out to be a big, time-consuming change.

**Comment by riksagar** [comment]
Hi @joeyparrish/@theodab, thanks for the replies,  Yes, this answers my question.  you can close the issue.  I may experiment with an open ended fetch and see if we get better performance for our playback (e.g., fewer buffer underruns or higher throughput).

Thanks,
Rik.
