### ISSUE TITLE
A way to validate the user credentials trough an external API.

### ISSUE THREAD

**Issue by metinkata** [google/shaka-player#2151]
Hi, I have a specific need, which boils down to validating the user credentials, so that if he is authorized he will be allowed to play the video, otherwise not.

The ways to do that easily is trough page-level JS manipulations of the player (like hiding the player or using the play(), pause(), stop() functions). All of these are not so secure ways to hide any content. 

Is there a specific function / filter / listener, where I can register a custom function and until this function is resolved the player can not be played at all.

I tried something like this:
```js
 player.getNetworkingEngine().registerRequestFilter(function (type, request) {
    if (type != shaka.net.NetworkingEngine.RequestType.LICENSE) return;
    // If we already know the token, attach it right away:
    AuthorizeTheCustomer().done(function(){
      console.log('Have auth token, attaching to license request.');
      request.headers['CWIP-Auth-Header'] = authToken;
      return;
    })
})
```

AuthorizeTheCustomer() function opens a popup, where the viewer enters his username and password, which get checked in our system and the promise is resolved.

AuthorizeTheCustomer() returns its result after the player is loaded so that the attached authToken to the request object is missed and due to that the encrypted content does not get decrypted.

Probably this place is not a good hook at all. I tried with the same idea with the asynchronous header authentication - as is shown in the player's documentation. Still the same issue.

I am using version 2.5.0 of Shaka Player.

Thanks for your ideas in advance :)

**Comment by TheModMaker** [comment]
There are a few ways you could do this.  The easiest would be to just not call `load` until after you have authenticated them.  An alternative would be to restrict the manifest fetch on the server side (which would also increase security) and have a request filter attach the credentials to the manifest request.  So the server wouldn't return the manifest unless the request had the required authentication.  You could also do the same thing with the license request (see the [license authentication](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html) tutorial).

If you want to do it entirely client-side and want to do it in a license request filter, you could define an asynchronous request filter.  The filter will "block" until your authentication is complete and since the license isn't available, the browser can't play the content.  The problem is that this isn't really the purpose of the asynchronous filters and a long delay like this would probably cause a bad user experience.  A better option would be to do the authentication before calling `load`.  To to an async require filter, you would do:

```js
player.getNetworkingEngine().registerRequestFilter((type, request) => {
  if (type != shaka.net.NetworkingEngine.RequestType.LICENSE) return;
  return new Promise((resolve) => {
    AuthorizeTheCustomer().done(() => {
      console.log('Have auth token, attaching to license request.');
      request.headers['CWIP-Auth-Header'] = authToken;
      resolve();
    });
  });
});
// Or if AuthorizeTheCustomer() is a "real" async method that returns a Promise.
player.getNetworkingEngine().registerRequestFilter(async (type, request) => {
  if (type != shaka.net.NetworkingEngine.RequestType.LICENSE) return;
  await AuthorizeTheCustomer();
  console.log('Have auth token, attaching to license request.');
  request.headers['CWIP-Auth-Header'] = authToken;
});
```

**Comment by metinkata** [comment]
This was helpful. Thank you very much :)
