### ISSUE TITLE
Opera TV support (possible SourceBuffer polyfill)

### ISSUE THREAD

**Issue by hackerdude** [google/shaka-player#216]
Hi,

I am working on an older browser that doesn't have an appendBuffer, but instead has an append() in its sourceBuffer. It should be a simple matter of doing:
```javascript
sourceBuffer.append(new Uint8Array(data))
```

I would like to write a polyfill for this so I don't disturb the mainline, but I can't see where I would be able to get to the SourceBuffer prototype to add it.

It seems that to even get to a SourceBuffer class I'd have to create a MediaSource, open it, and then add a sourcebuffer, then get to its prototype.

It seems like a whole bunch of work for adding a method. Am I missing something? Is the SourceBuffer class somewhere on the typical JS VM prototype tree?

**Comment by joeyparrish** [comment]
Hrm, tricky situation.  If there's no SourceBuffer constructor exposed, it seems like you will not be able to write a polyfill for it.

What browser are you trying to support?

**Comment by hackerdude** [comment]
Opera TV browser (which is Opera Presto with the EME extensions). Runs on various STBs.

Without access to the SourceBuffer, it looks like (pcode) would look like:

```javascript
      if (typeof(_sb.appendBuffer) == 'function') {
        _sb.appendBuffer(initData)
      } else {
        //pcode
        _sb.emit('updatestart')
        _sb.emit('update')
        _sb.append(new Uint8Array(initData))
        _sb.emit('updateend')
      }
```

This would be in source_buffer_manager.js and offline_video_source.js.

I forked and I'm making a branch to play around with. No checkins yet. First I want to get it to work.

**Comment by joeyparrish** [comment]
Okay.  Let me know how it works out, and then we can discuss the possibility of merging.

**Comment by joeyparrish** [comment]
Hi @hackerdude, any news on a polyfill?  If you are still working on this, I will leave the issue open for you.

**Comment by Biggytv** [comment]
This would be helpful to me too.

**Comment by joeyparrish** [comment]
Shaka's position has always been to support current web standards, and to use polyfills where necessary to compensate for certain platform variations.  It sounds like Opera TV is not up-to-date on MediaSource, but Shaka team has neither the time nor the hardware to work on a polyfill for this.

Since @hackerdude has not responded in three weeks, I'm going to close this as "will not implement".  If anyone wants to develop the polyfill and send us a PR, I would be happy to review it.  Just let us know you're working on it so I can re-open this issue.  Thanks!
