### ISSUE TITLE
Enable access of the Contants object in the shaka-player npm package

### ISSUE THREAD

**Issue by AGMETEOR** [google/shaka-player#2203]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.5

**Can you reproduce the issue with our latest release version?**
Yes, because 2.5.5 is the latest.

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
No

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Google Chrome on MacOS Siera

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What did you do?**

In my react component file...
```
import shaka from '../../../node_modules/shaka-player/dist/shaka-player.ui';
shaka.ui.Constants.SEEK_BAR_BASE_COLOR = 'rgb(0,0,255, 0.3)';
```

**What did you expect to happen?**
I expected the seek bar to have a light blue color based on the rgba value provided

**What actually happened?**

Application fails and I receive this error in the console
```
TypeError: Cannot set property 'SEEK_BAR_BASE_COLOR' of undefined
```

**Comment by joeyparrish** [comment]
This was never our intent.  Changing a constant makes it not constant.  :-)

We had always intended for style to be overridden via CSS.  But the seek bar colors are constructed in code using these constants, so it's not necessarily possible to change the colors and keep the same gradient effect purely in CSS.

I see three options:
1. We could accept PR #2204 to allow you to change these constants.  It's the least work, but also a little strange/hacky.
2. We could reimplement the seek & volume bars as nested, colored divs instead of a range input element.  That would allow each div to have a separate class whose color you could change purely in CSS, but the element would no longer be semantically correct.  This would cause issues with screen readers and require us to do additional work to make the elements accessible.
3. We could offer a configuration for the volume & seek bar colors.  This would be more work than option 1, but would be in keeping with the design of Shaka Player.  You would change the colors via `ui.configure()` instead of by overwriting a constant.

I'm inclined toward option 3, which seems like the best balance to me.  While you're waiting for us to implement option 3, you could certainly continue using option 1 in your fork.  Would that work for you?

**Comment by AGMETEOR** [comment]
@joeyparrish thank you very much for getting back on this issue :). Option 3 seems like the best solution and I could use my fork in the meantime. I think it would also be nice if it's stated somewhere in the docs that with the npm package it's not "possible" to override those color constants with the current version `2.5.5`.
