### ISSUE TITLE
Due date for release 2.6

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2208]
According to: https://github.com/google/shaka-player/blob/master/roadmap.md
`v2.6 - 2019 Q3 (estimated)`

The current state is: `68% complete 49 open 108 closed`

Is it reasonable to expect this before Q1?

**Comment by ismena** [comment]
@avelad Joey will tell with more confidence, but since he's on business trip and may or may not see the issue until late next week, here's my best estimate.
AKAIK, the biggest feature that we're holding the release for is period flattening (isolating the concept of periods to the DASH parser).
Last time I checked, it was moving slowly, but steadily. 
I think it's reasonable to expect 2.6 in Q4.
@joeyparrish amiright?

@avelad are there specific features you're interested in for 2.6?

**Comment by avelad** [comment]
I'm interested in:
https://github.com/google/shaka-player/issues/2195 --> `Allow disable the audio parsing/decoding/.. in DASH/HLS with a config` Is possible backport to 2.5.x?
https://github.com/google/shaka-player/issues/1531 --> `Support downloading of Dash manifests that do not have inline PSSH value.` Is possible backport to 2.5.x?
https://github.com/google/shaka-player/pull/2134 --> `Add change event to audiotracks and texttracks.` Is possible backport to 2.5.x?
https://github.com/google/shaka-player/issues/1169 --> `IMA ads SDK demo and tutorial` (in progress, I saw commits in the repo)

**Comment by ismena** [comment]
Understood!
I'll discuss with Joey what we can do to make the listed implemented features available. (I'm not important enough to make the call :p).
If you don't hear from either him or me by the end of next week, please ping this issue.
(Joey comes back from vacation in a week, I'll try to bring it up with him right away).

**Comment by avelad** [comment]
@shaka-bot , please wait one week.

**Comment by joeyparrish** [comment]
Hi, everyone.  Thanks for your patience.

As @ismena mentioned, period flattening (#1339) and associated refactors (#892) are blocking v2.6, but I am actively working on those things.  I apologize for the inconvenience.

We could release v2.6 without those things, but we are in the middle of several breaking changes to the internal manifest structure, which will require updates to all manifest parser plugins and any applications which use `player.getManifest()`.  If we release v2.6 before those changes are complete, we just have to make more such changes in v2.7 and break it again.  I would prefer to avoid that, but I welcome your feedback if you disagree.

As for which changes we can backport to v2.5.6:

#2195/#2196 (Disable audio via config): Yes, because the feature is trivial.
#1531/#2164 (Offline DASH without inline PSSH): Maybe.  It's a bigger change, and therefore may have more complex merge conflicts and introduces more risk.  I'll try to cherry-pick it and see how it goes.  If it can be cherry-picked, we'll do additional testing in our lab before pushing it.
#2134 (Fix tracks in UI w/ src=): Yes, because it's a bugfix & trivial.
#1169 (Ads work): No, because the work is non-trivial, incomplete, and not yet functional.

**Comment by sath33sh** [comment]
@joeyparrish Just a reminder, I'd like have the following changes in v2.5.6:
#2076 Duplicate CEA-608 caption lines
#2077/#2175 Include event ID in findSimilarRegion_() check

**Comment by avelad** [comment]
I'd like have the next change in v2.5.6 also:

https://github.com/google/shaka-player/commit/8f57efbe9f698b0a3e8a22a80d9d126a6c503cee

**Comment by avelad** [comment]
@joeyparrish Do you have any ETA for 2.5.6?

**Comment by joeyparrish** [comment]
The engineer who was working on the v2.5.6 release is out sick today.  I expect we'll be able to complete the process later this week.

**Comment by joeyparrish** [comment]
I'm told that all of the changes requested here have been cherry-picked for v2.5.6, except the ads work, for the reasons I mentioned before.

**Comment by mimse** [comment]
Hi would it be possible to cherry pick #2215 for 2.5.6 as well
Thanks in advance.

**Comment by TheModMaker** [comment]
That has also been cherry-picked.  Most of the commits since v2.5.5 have been cherry-picked.  I'll hopefully be pushing the branch soon.
