### ISSUE TITLE
Suggestion: add constants to represent the events

### ISSUE THREAD

**Issue by leandromoreira** [google/shaka-player#221]
I was reading the documentation about the [buffering events](https://shaka-player-demo.appspot.com/docs/shaka.player.Player.html#event:BufferingEvent) and then I went to the [source code](https://github.com/google/shaka-player/blob/d84428b42fb954ac4573e4fe98066fce26655d0f/lib/player/player.js#L68) and saw:

```javascript
/* @fires shaka.player.Player.BufferingEvent */
```

Both places lead me to think that the namespace was the event constant itself.

```javascript
player.addEventListener(shaka.player.Player.BufferingEvent, this._bufferingHandler)
```

Maybe it would be good to create them as "constants" or even create them as static property of an event class.

```
Events.BUFFERING_EVENT = 'buffer'
```

**Comment by leandromoreira** [comment]
I could create a PR for both approach if you will.

**Comment by leandromoreira** [comment]
Or yet just a documentation with all available events to listen to.

```
playing, error, ...
```

**Comment by joeyparrish** [comment]
Hi Leandro,

It sounds like you have two separate issues:

1) documentation is confusing
2) buffering events are unreliable

Is this accurate?

**Comment by leandromoreira** [comment]
Thanks @joeyparrish ! 

Yes for 1) and 2) I might be wrong about buffering events being unreliable. Let me check deeper about this first.

**Comment by leandromoreira** [comment]
BTW @joeyparrish I just ported [shaka as a playback](https://github.com/clappr/dash-shaka-playback) to the player [Clappr](https://github.com/clappr/clappr), thank you very much, you guys did an amazing work, it was very easy to integrate/use/learn shaka :beers:

**Comment by joeyparrish** [comment]
@leandromoreira Glad to hear it!

Did you retest and determine if buffering events are reliable?  We have automated test cases for these, but if we missed something, we'd love to know.

**Comment by leandromoreira** [comment]
yes, I did! 

We still need to rely on [`stalled, waiting`](https://github.com/clappr/clappr/blob/master/src/playbacks/html5_video/html5_video.js#L32-L33) events and some tricks while in [`progress`](https://github.com/clappr/clappr/blob/master/src/playbacks/html5_video/html5_video.js#L209-L231).

AKA we're going to use a mix of these techniques + [shaka events](https://github.com/clappr/dash-shaka-playback/blob/master/index.js#L80-L81)

**Comment by joeyparrish** [comment]
Okay, since we've determined that the buffering event is working correctly, it's just an issue of documentation.

We already have all events documented in one place.

If you look at the [docs](http://shaka-player-demo.appspot.com/docs/index.html), in the bottom of the right-hand side you'll see a list of all events.  If you set the documentation view to in the top-left corner to *'Show: exported'* (which is the default), then the list is only those publicly exported events you can listen for on the Player object.

If you click on a particular event, such as [BufferingEvent](http://shaka-player-demo.appspot.com/docs/shaka.player.Player.html#event:BufferingEvent), you'll see the type property with the value *'bufferingStart' or 'bufferingEnd'*.

Does that help?

**Comment by leandromoreira** [comment]
@joeyparrish yes, thanks :)

**Comment by joeyparrish** [comment]
Excellent.  Sorry for all the confusion, and thanks for using Shaka Player!
