### ISSUE TITLE
m3u8 stream problems - Access to fetch at _ from origin _ has been blocked by CORS policy

### ISSUE THREAD

**Issue by xhubeny2** [google/shaka-player#2227]
Hello,
I am trying to build an app in ReactJS with component with Shaka Player. I tried to copy component from this readme:

https://github.com/amit08255/shaka-player-react-with-ui-config/tree/master/with-default-ui

and even import this library:

https://github.com/matvp91/shaka-player-react

and if I want to play this video stream:

https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

i have theese errors in console and the video doesn't play...
![console](https://user-images.githubusercontent.com/14809495/68307537-b6881280-00ab-11ea-861a-7d3ab8c91bb8.png)

Could anybody help me, please?

I tried this streams as well:
https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8
https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd
but everything worked well, so the problem is only with the video stream above.

I am totally beginner with Shaka Player, sorry.
Thank you for any help.

**Comment by joeyparrish** [comment]
This is a CORS issue, or Cross Origin Resource Sharing.  CORS is a set of restrictions built into the browser to prevent certain types of attacks on users.  In short, your server must declare to the browser that it will allow access to the things you're loading.  It does this through HTTP response headers.

Here's an MDN article to explain in detail: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

In your case, it's a preflight request (HTTP "OPTIONS" request) being rejected by the server (Akamai).  So you may need to contact Akamai for support.

Alternately, you could host your page on the same origin (domain) as the content.  Then the requests won't be cross-origin, and CORS will not kick in.

Does this help?

**Comment by xhubeny2** [comment]
Thank you so much! 
Can I have one more question? Why some requests from this video stream are ok and some have this CORS issues? This screenshot is from loading the same video...

![console2](https://user-images.githubusercontent.com/14809495/68364913-9732c900-012f-11ea-9099-3d02f016a4f7.png)

Isn't it just about some options in the player?

Thank you

**Comment by joeyparrish** [comment]
It's not about player options.  CORS works differently for different requests based on their characteristics.  For example, a pre-flight requests is required for range requests, but may not be for non-range requests.  See the MDN article for details: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

In particular, this part on the rules for simple vs pre-flight requests: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Examples_of_access_control_scenarios

The content segments themselves may require us to do things that trigger pre-flight.  So you have some indirect control over this through your content.  For example, if every segment is its own file, and you never attach any additional request headers in your app, we will usually not trigger pre-flight.  But if you use SegmentBase in DASH or otherwise have segments accessed through a byte range on a file, pre-flight must be supported by the server.  There's nothing the player can do to avoid it.

Does this help?

**Comment by xhubeny2** [comment]
> Does this help?

Ok, I see. Thank you!
