### ISSUE TITLE
Create and submit a playlist for Chromecast

### ISSUE THREAD

**Issue by ivansteff** [google/shaka-player#2242]
Is it possible to pass an array or list with stream links to chrome cast?
For example, there is a playlist with a list of films, is it possible to transfer links to the stream of these films, and start the next movie in the list. That it would be possible to close the browser and the broadcast was not interrupted at the end of the film. Is it possible to do this?

**Comment by theodab** [comment]
We don't have anything like that, no.

**Comment by joeyparrish** [comment]
If you can build a browser-side app that plays through a playlist using Shaka Player, you can easily add cast.  Because state is proxied, it doesn't matter if you're casting or not.  Your app would get the same notifications when a presentation ends, and your call to `load()` the next item in the list would work exactly the same.

We don't have any explicit playlist features with or without cast, but you should be able to build this without too much trouble.

Does this help?

**Comment by joeyparrish** [comment]
@theodab just pointed out that I misread your question.  If you want to close the browser and have the playlist continue on the receiver without being controlled by the sender, you would need to add logic for playlists in your receiver app.  This wouldn't be too tough, either, though.  We don't have any explicit playlist features, but getting a receiver-side notification when playback ends (video's `ended` event) will let you start the next item in the list by calling `player.load()`.

To pass the list to the receiver, you could use `shaka.cast.CastProxy`'s `setAppData` method to pass the playlist or anything else you need.  On the receiver side, you would provide `appDataCallback` to the constructor of `shaka.cast.CastReceiver` and get notified whenever a sender connects or if it calls `setAppData` after connecting.

Does this help?

**Comment by ivansteff** [comment]
@theodab That would be a useful feature.

**Comment by ivansteff** [comment]
@joeyparrish  &  @theodab  Thanks for the quick in the detailed answer!
As soon as I implement this, I will add the code here.
