### ISSUE TITLE
HLS live streaming gets 4032 codec error

### ISSUE THREAD

**Issue by zhulduz** [google/shaka-player#2266]
Hi team!

I have tested some hls streams, got the 4032 error in Chrome, etc (except Safari).
Log:
`Dropping variant - video not compatible with platform type=video codecs=avc1.4d0028,mp4a.40.2 bandwidth=undefined frameRate=24 width=1920 height=800`

If I check through `canPlayType`, so the codes are really not supported.
`const result = document.createElement('video')
result.canPlayType('video/mp2t;codecs="avc1.4d0028,mp4a.40.2"')`

So, why other players can play the same stream in Chrome?
https://bitmovin.com/demo
https://videojs.github.io/videojs-contrib-hls

Can you please help me with understanding?

thanks in advance)

**Comment by TheModMaker** [comment]
We don't use `video.canPlayType` since we aren't using `src=` playback.  You need to use `MediaSource.isTypeSupported`.  Chrome doesn't support playback of MP2-TS content, so we need to transmux it to MP4.  We do this using mux.js, but you need to include it separately.  For example:

https://github.com/google/shaka-player/blob/d4d0c4f8880038f6df7371b87b6bc4d36c4aa570/demo/index.html#L40

Does the stream work in the [hosted demo](https://shaka-player-demo.appspot.com/)?  Can you post your manifest (or send it to shaka-player-issues@google.com)?

**Comment by zhulduz** [comment]
Muchas gracias!
It works, thanks for the quick response 👍
