### ISSUE TITLE
Synchronise two player instances

### ISSUE THREAD

**Issue by jonasandero** [google/shaka-player#2275]
I want to play back two "viewports" of the same "scene" - synchronised using two HLS-playlists and two instances of shaka-player. Some how, I need to use the same timesource. Is there an API for this or any projects that addresses this?

**Comment by joeyparrish** [comment]
There isn't anything for that in Shaka Player itself, but I've seen a demo of something similar by a synchronization library/service.  The demo used Shaka Player, and it kept playbacks in sync across devices.  I've forgotten the name of the library/service, though.  Hopefully someone else here remembers and can comment.  I failed to turn it up in a Google search.

I expect it worked by synchronizing peers over a WebRTC data channel or server relay, then varying `video.playbackRate` to speed up or slow down playback very slightly until the peers were in sync.

For your case, you have both players in the same browser, so there's no need to sync two different devices.  You could periodically check the two videos and do something like this (**totally untested**):

```js
const delta = video1.currentTime - video2.currentTime;
const bigThreshold = 0.5;
const bigSlowdown = 0.92;

const smallThreshold = 0.1;
const smallSlowdown = 0.98;

if (delta < -bigThreshold) {
  // 2 is FAR ahead!
  video1.playbackRate = 1;
  video2.playbackRate = bigSlowdown;
} else if (delta < -smallThreshold) {
  // 2 is SLIGHTLY ahead.
  video1.playbackRate = 1;
  video2.playbackRate = smallSlowdown;
} else if (delta > threshold1) {
  // 1 is SLIGHTLY ahead.
  video2.playbackRate = 1;
  video1.playbackRate = smallSlowdown;
} else if (delta > threshold2) {
  // 1 is FAR ahead!
  video2.playbackRate = 1;
  video1.playbackRate = smallSlowdown;
} else {
  // They are close enough!
  video1.playbackRate = 1;
  video2.playbackRate = 1;
}
```

If it works (**untested**), this would keep the two players within 0.1s of each other, with all the parameters being constants you can play with to get it the way you want.

Does this help?

**Comment by jonasandero** [comment]
Yes, I found a few efforts on the web, like https://github.com/Syncplay/syncplay. 

Our challenge is that we stitch videos of for example soccer using cameras covering half of the field/scene and render a virtual-panorama view with OpenGL. Currently we deliver one stream with left/right field stacked in each frame. For quality and delivery optimisation reasons, we want to deliver them as two different streams/urls.

The point is that they must be _exactly_ in sync. Any delta will result in that the stitched result looks weird. So I want to bind the time-source of the players to the same clock.

**Comment by joeyparrish** [comment]
Well, there isn't really any time source concept in HTML5 video at the API level.

I'm not sure if it's specified in the W3 standards how sync works, or if it's implementation-defined. 
 I could imagine an implementation that syncs video games to the audio output clock, since I know some open source desktop players that do it that way.

If all playbacks are synced to the same clock in the browser implementation, it would just be a problem of getting them initially synced, then resynced if one has to buffer.  But all of this would depend on the platform, and you'd need to test and retest in every supported browser to make sure there's no critical difference in implementation.

But since your application is extremely sensitive to sync issues, you might have to keep delivering them in one stream.  I'm not sure there's anything better we could offer you.
