### ISSUE TITLE
ui textDisplayer crashes the player

### ISSUE THREAD

**Issue by mihaiav** [google/shaka-player#2286]
1. Create a new player
2. call configure "textDisplayFactory" with a shaka.ui TextDisplayer instance
3. Load a video without subtitles 
4. Load an invalid manifest (.e.g "http://google.com").

Expected result:
1. The player raises a recoverable exception
2. The player may be reused

Result:
1. The player raises a recoverable exception
2. shaka ui crashes the player in a unrecoverable state. 

Possible solution :  
 https://shaka-player-demo.appspot.com/docs/api/ui_text_displayer.js.html line 85 should check if this.textContainer_ is Truthy

**Comment by joeyparrish** [comment]
Perhaps the issue is how you configured it.  The textDisplayFactory field takes a factory function, not an instance.  And that instance needs to be properly constructed with the required parameters, like the video element and the video container element.

Does this help?

If not, can you please post a snippet of your configuration code?

**Comment by mihaiav** [comment]
You are right. Although I was providing a function to the textDisplayFactory field,  the TextDisplayer instance was static thus the reason why shaka.ui was throwing  exceptions. After I moved the textDisplay instance creatuib inside the "factory" function I no longer get exceptions from shaka.ui.
