### ISSUE TITLE
Dash Offline

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#2295]
Hi,

Shaka player support download feature. We have a feature to download the files using our downloader and play using shaka player. I have the below queries:

1. Is there any api of shaka player which can be used to fetch the license. We want to fetch the license when the content is downloaded using our downloader.
2. Can we play the downloaded files(Using our downloader) by using the shaka player?
3. We have to give the contentId/Kid of the content to our DRM partner to get the license. How can we get the contentID/Kid using shaka player?

**Comment by theodab** [comment]
This would be possible, though it'll take some work.

1. We don't have any API for this. Storing it manually via persistent license requests isn't too hard though.
```js
const session = mediaKeys.createSession('persistent-license');
session.generateRequest('cenc', initData);
// TODO: store the session ID (session.sessionId) for later use
session.addEventListener('message', async (event) => {
  const response = await fetch(licenseServerUrl, {method: 'POST', body: event.message});
  await session.update(response);
});
```
2. The best way to play content stored via your custom storage system, the best approach would probably be a custom URI scheme plugin. You can register one with `shaka.net.NetworkingEngine.registerScheme`; see [the data URI plugin](https://github.com/google/shaka-player/blob/master/lib/net/data_uri_plugin.js) for an example implementation. So you'd play the asset as though it were online, but call it under a fake URI you registered the plugin under (e.g. "stored://manifest12.mpd"). Then your custom scheme plugin can return the desired data, from your storage system. You will also need to make a custom manifest parser, for parsing the stored version of the manifest; this is so that you can associate the manifest with your stored session IDs (by setting the `offlineSessionIds` variable in the manifest object).
3. Are you using FairPlay? If so, and if you are using the default content ID derivation, you can get the content ID like this:
```js
shaka.util.FairPlayUtils.defaultGetContentId(drmInfo.initData.initData);
```

For a while, we were considering a storage plugin, for providing your own custom backend for storage (replacing our IndexedDB implementation) as necessary. We didn't end up making it because the storage interface was greatly in flux at the time, and we would have been unable to provide a stable interface for developers. As of now, however, storage is a bit more finalized, so if you think that something like that would suit your needs, we could maybe work on it in the future.

**Comment by sridhard** [comment]
@theodab thanks for quick reply.

1. We are using DASH. Is there any way to get contentId in DASH?

2. Your idea of storage plugin is very good. This will perfectly suit our needs. It will be great if shaka-player support it

**Comment by theodab** [comment]
1. In the case of DASH, I'm not sure what you mean by "contentId". Do you mean the URI of the asset? If so, you can use `shaka.Player.getAssetUri()`.

1. I'll file an enhancement request for that, then.

**Comment by sridhard** [comment]
thanks
