### ISSUE TITLE
Unable to play video in Safari.

### ISSUE THREAD

**Issue by 2rohith2** [google/shaka-player#2299]
I have read: https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html docs

I have added Server certificate & License wrapping in my code.

But the execution doesn't go inside license wrapping, i.e `player.getNetworkingEngine().registerRequestFilter` function.

Does anyone faced this earlier ?

**Comment by theodab** [comment]
What kind of content are you playing? If you're playing HLS content, by default on Safari we use Safari's playback (e.g. src=). That's because if you want to, say, use FairPlay, you have to let the browser handles it.
If you want to have Shaka handle HLS content on Safari, you can set the `streaming.useNativeHlsOnSafari` config to be `false`.

**Comment by TheModMaker** [comment]
You can't use `streaming.useNativeHlsOnSafari=false` with FairPlay, you need to use `src=` to use FairPlay (the default).  When are you calling `registerRequestFilter`?  That needs to be before you call `load`.  Can you post your code?
