### ISSUE TITLE
Poor UI Behavior with Roles

### ISSUE THREAD

**Issue by bloomtom** [google/shaka-player#2307]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Firefox 71 and Chrome 79

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
A test manifest is available [here](https://bloomtest.nyc3.digitaloceanspaces.com/roles/test5.mpd).
[Demo Link](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://bloomtest.nyc3.digitaloceanspaces.com/roles/test5.mpd;panel=CUSTOM%20CONTENT;build=uncompiled)

**What did you do?**
Produce a DASH manifest containing multiple audio or subtitle tracks in different adaptation sets with the same language code but different roles.

**What did you expect to happen?**
Audio and subtitle tracks with the same language but different roles appear showing both the language and the role, and the user can select any of these roles.

**What actually happened?**
Audio roles are not visible. Only a single element for each language is visible. The user cannot switch between roles, and they probably don't even know more than one role exists.
Subtitle roles are visible as duplicates, but selecting one causes all of them to be checked in the UI, and only one is actually displayed. The user cannot select the role they want.

I can select these roles using `selectTextLanguage` and `selectAudioLanguage`, but the UI remains inconsistent.

Comparison of Shaka and the DASH reference player.
![EryOZzs0](https://user-images.githubusercontent.com/4093170/71061962-53bc7900-2137-11ea-8b03-e6f6db980caf.png)

[MPD attached as a txt](https://github.com/google/shaka-player/files/3976947/test5.txt)

**Comment by theodab** [comment]
Yeah, this looks like a problem. Thanks for the report!

**Comment by theodab** [comment]
Ok, I've changed the UI to show each role for a given language.
I also added a new UI configuration, `trackLabelFormat`, which determines how we make the labels for audio and text language selections. It defaults to `shaka.ui.TrackLabelFormat.LANGUAGE`, which just shows the language; you might want to set it to `shaka.ui.TrackLabelFormat.ROLE`, to show the role but not the language, since it looks like the roles in your content are designed to be displayed without their associated language.

If you think that we need to do any more work to get role selection up to snuff, feel free to re-open this issue and tell us. The person who is normally in charge of UI stuff is out right now, and I might have made some incorrect design decision here.

**Comment by joeyparrish** [comment]
These changes have been cherry-picked for v2.5.8.
