### ISSUE TITLE
How to build a version of Shaka that's unminified?

### ISSUE THREAD

**Issue by VictorChen** [google/shaka-player#2312]
Due to our complicated build system, we won't be able to utilize the `.map` files. Is there a way to build Shaka unminified so it's easier to work with? Currently, I'm running the following command to build Shaka:

```
python build/build.py +@core +@dash +@networking
```

which outputs:

```
shaka-player.ui.js
shaka-player.ui.map
```

 Thanks!

**Comment by joeyparrish** [comment]
Check out the `--name` option in `build.py`, since the default is "ui" and you aren't using the UI components of the library.  See `build.py --help` for the full list of options.

We have `build.py --mode debug`, but that's not completely unminified.  It avoids renaming members, but still renames local variables.

You could use the uncompiled "build" of Shaka.  To do this, you include the Closure library's base file, a deps file mapping our sources, and then a bootstrap file which requires all the others:

```html
    <!-- Closure base: -->
    <script src="third_party/closure/goog/base.js"></script>
    <!-- Deps file: -->
    <script src="dist/deps.js"></script>
    <!-- Shaka Player uncompiled library: -->
    <script src="shaka-player.uncompiled.js"></script>
```

But that would be everything, not just the specific pieces you want.  And it's outside of the build system you want to use.

If you want to have the build system concatenate the relevant sources for you, without actually compiling them, that's not something it supports today.  I think it would be possible to add, though.

For now, if want to concatenate the sources yourself, you can use the lists of files in build/types/ to decide what to concatenate.  For example, build/types/core contains:

```
+../../lib/abr/ewma.js
+../../lib/abr/ewma_bandwidth_estimator.js
+../../lib/abr/simple_abr_manager.js

+../../lib/debug/asserts.js
+../../lib/debug/log.js

etc
```

You should be able to construct a file list from your build command and concatenate the sources.

Or, if you feel like contributing, you could add an additional mode (beyond release & debug) that sets the compiler's `-O` flag to `BUNDLE`, which should get you the output you want.

Does this help?

**Comment by VictorChen** [comment]
@joeyparrish thanks for that. I tried changing `-O` to `BUNDLE`, and re-running:

```
python build/build.py +@core +@dash +@networking
```

which generates an unminified `shaka-player.ui.js`. However, it's missing some necessary code for it to run.

I tried copying/pasting `third_party/closure/goog/base.js` & `dist/deps.js ` to the beginning, but it still complains about:

```
goog.require could not find: shaka.ui.Localization
```

Do you know what else I need to do to get this file to run?

**Comment by joeyparrish** [comment]
The localization file is part of the UI library, and it's in a file generated from the UI translations.  You shouldn't need it since you didn't include `+@ui`.

I just changed `-O SIMPLE` to `-O BUNDLE` and built with:

```
python build/build.py +@core +@dash +@networking --name foo --debug --force
```

This produced `dist/shaka-player.foo.debug.js`.

I loaded this in place of the compiled bundle in the "Basic Usage" tutorial: https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html

This failed, complaining about goog.require, which is in Closure base, so I added that.  Then it complained about goog.assert, from lib/debug/assert.js, so I added that.  Then it complained about shaka.log, so I added lib/debug/log.js.  Then it complained about missing shaka.util.Iterables...

And then I realized the compiler with `-O BUNDLE` only seems to bundle the top-level requirements.  It doesn't seem to traverse the deps tree and pull in the things goog.require'd by the top-level classes and plugins.

So this would be non-trivial to fix, and I don't have any suggestions off-hand.

The best fallback for you may be to try gathering the list of sources from build/types/ and concatenating them yourself.

**Comment by VictorChen** [comment]
thanks, I'll do that over Christmas.
