### ISSUE TITLE
How to ensure mutually exclusive playback of videos among a group of videos.

### ISSUE THREAD

**Issue by varunk19** [google/shaka-player#2320]
I created a webpage that consists of 6 videos and when I click on one of them it plays. But while it is playing, if I click on another video they both play at the same time. I'm using Shaka player to play them. Please help me as I'm new to using Shaka player and coding in JavaScript.

My code repository link is:
https://github.com/varunk19/Mobiotics-assignment

**Comment by joeyparrish** [comment]
You should look into the API of the video element.  When you play one video, you can pause the others.  https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement

For example, since you're using the browser's built-in controls (video.controls=true), you can listen for the 'play' event from the video element and then call .pause() on all the others.

Does this help?
