### ISSUE TITLE
Content plays, but Shaka throws Error 6008: DRM.LICENSE_RESPONSE_REJECTED.

### ISSUE THREAD

**Issue by londonshliach** [google/shaka-player#2349]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
2.5.8

**Can you reproduce the issue with our latest release version?**
Yes.

**Are you using the demo app or your own custom app?**
Both.

**What browser and OS are you using?**
Chrome 79 on Windows.

**What are the manifest and license server URIs?**

Manifest:
https://jem-ccdb-media.s3.amazonaws.com/video/dist/jobs/4de6b1b9-1adf-4935-a9ef-797aed6d9144/dash_vp8/master.mpd

DRM Server:
https://widevine-dash.ezdrm.com/proxy?pX=96B958

**What did you do?**
Played content in Shaka player (and on Shaka Demo page).

**What did you expect to happen?**
Play with no errors.

**What actually happened?**
The content played, but Shaka throw a 6008 Error:  "DRM.LICENSE_RESPONSE_REJECTED (The response parameter is empty.)"
The error did not prevent the content from playing.

Looking in the network tab, I see that Shaka makes 4 calls to the DRM server, and the final call results in the Error.

This content plays correctly in the Dashif reference player without any errors.
Dashif only makes 2 calls to the DRM server.

I wanted to know what this error means (since the full content plays), and what is the purpose of the extra calls to the DRM server.

Thanks.

**Comment by joeyparrish** [comment]
Chrome on Windows & Mac will do an extra round trip compared with Linux, to retrieve the server certificate.  So on my Linux machine, I get 2 license requests instead of 4.

Similar to your experience, though, the second request has an empty response.  I can't say why it's empty, because that is up to the license service provider, EZDRM.  Given an empty response, the CDM is clearly correct to reject it, which is what triggers the `LICENSE_RESPONSE_REJECTED` error code in Shaka Player.  So all of that on the client is working as intended, though it's not clear why the server would send an empty response.

As for dash.js not sending that second request, my guess it that we have a difference in how we process PSSHs.  Your manifest contains two different Widevine PSSHs for the same key ID in the same AdaptationSet.  This triggers Shaka Player to create two DRM sessions and make two independent license requests.  It's possible that dash.js combines the PSSHs, or ignores the second one.  I don't know their behavior on this.

Can you explain why the content looks this way, with two different Widevine PSSHs for the same key ID?  It might help us understand if we're making a mistake in how we process it.

**Comment by londonshliach** [comment]
It appears that we had a problem in our trans-coding pipeline.

I removed the extra PSSH and it plays fine in Shaka.

Thank you very much.

**Comment by joeyparrish** [comment]
Glad we could help!
