### ISSUE TITLE
HLS stream on iOS error 3016

### ISSUE THREAD

**Issue by rdglge** [google/shaka-player#2379]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.8

**Can you reproduce the issue with our latest release version?**
My understanding is that 2.5.8 is latest

**Can you reproduce the issue with the latest code from `master`?**
Have not tried master

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
No. I am running my own webserver on a private network.

**What browser and OS are you using?**
iOS 12.3.1 Safari

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
na

**What are the manifest and license server URIs?**

**What did you do?**

I am attempting to play back an audio only hls stream. This stream plays back on Chrome under Windows 10

**What did you expect to happen?**
Playback to happen

**What actually happened?**

The master play list is downloaded. The next playlist is not downloaded. No media segment files are downloaded.

An error code 3016 is thrown. In the data array element zero the value 4 is reported.

It is as if the playback is not even attempted.

<img width="792" alt="Screen Shot 2020-02-05 at 10 20 33 AM" src="https://user-images.githubusercontent.com/6098314/73861175-43a14b80-4802-11ea-84aa-9c9081a19f23.png">

**Comment by rdglge** [comment]
This issue can also be seen by visiting the following url in Safari on iOS:

https://rdglge.github.io/shaka-demo/

**Comment by joeyparrish** [comment]
Here are the docs for error code 3016: https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:3016

The docs currently state:

Name | Value | Type | Description
-- | -- | -- | --
VIDEO_ERROR | 3016 | number | The video element reported an error. <br> error.data[0] is a MediaError code from the video element.  <br> On Edge & IE, error.data[1] is a Microsoft extended error code in hex. <br> On Chrome, error.data[2] is a string with details on the error.

This is typically a decoder error, but could be some other internal error thrown by the browser.  This error is always fatal to playback, and can't be recovered.  In our experience, some content that plays elsewhere will be rejected by Apple's hardware decoders.

We also have an entry in our FAQ about this: https://shaka-player-demo.appspot.com/docs/api/tutorial-faq.html

The entry currently says:

> **Q:** I am getting decoder errors or `VIDEO_ERROR` or error code 3016.
> 
> **A:** This error is given to us when the browser can't play the content.  This
is out of our control and is usually caused by bad content.  On Chrome you can
check `chrome://media-internals` for more info (see https://github.com/google/shaka-player/issues/489#issuecomment-240466224)

Does this help?

**Comment by rdglge** [comment]
I don't see how it is a decoder issue when no segment files have been downloaded. Have you tried https://rdglge.github.io/shaka-demo/ in Safari on iOS?

The docs you quote don't mention Safari.

After receiving this error, I have tried the stream by passing the playlist to an html5 standard audio tag. Safari on iOS plays the stream successfully.

**Comment by joeyparrish** [comment]
Since this is iOS, it may not be a decoder error.  But on iOS, we have to hand playback off to the browser by setting the `src` attribute of the media element to the master playlist URL you passed to `load()`.  Error 3016 means "the browser threw an error from the video element", which is typically a decoder error on MediaSource-supporting browsers, but could be any playback error from the browser.  With Apple's native HLS, it's hard to say what triggered it.

But I'm not sure you'd see segment files downloaded with native HLS playback.  That would all be handled inside the browser, rather than segments being requested by Shaka Player.

**Comment by BucherTomas** [comment]
@rdglge Try to remove the AUDIO attribute from your master.m3u8 playlist. Just keep this:
`#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS="mp4a.40.2"`

The AUDIO attribute shouldn't be present in your master as it does not include another audio playlist that the group id in AUDIO attribute would refer to.

**Comment by rdglge** [comment]
@BucherTomas I tried your suggestion.

The stream plays back now. I no longer see the 3016 error.

It looks like the problem was in the master playlist.

For the record, the Network tab of the web inspector does show the media segment files being transferred.

In the ideal case the error message from shaka would indicate the problem was in the master playlist.

I will close this because the media plays back now.

**Comment by joeyparrish** [comment]
> In the ideal case the error message from shaka would indicate the problem was in the master playlist.

If there were any way to differentiate, then we would.  But the error from the browser is extremely generic, and since we are not handling the playlist ourselves, there is no way for us to know.
