### ISSUE TITLE
How to make Shaka Player provide a custom User-Agent parameter

### ISSUE THREAD

**Issue by georgio-sd** [google/shaka-player#2398]
1. How can I make Shaka Player provide a custom User-Agent parameter when it requests video files? I prefer to change something in the source code and recompile, so it would not be so easy to find out.

2. How can I identify Shaka Player's requests on a web server in order to prevent video from accessing by other software?

**Comment by joeyparrish** [comment]
Well, there's a lot to answer here.  Let me try to explain.

> How can I make Shaka Player provide a custom User-Agent parameter when it requests video files?

I have never thought about changing a UA header from JavaScript.  I guessed it wouldn't be allowed, since the UA header is meant to identify the browser (the "User Agent" in W3C terms) to the server.

It turns out that it's more nuanced than that.  It *used* to be disallowed by the fetch API spec, but the spec now allows it.  Firefox updated to follow this spec change, but Chrome did not.  So as of today, you can set a custom UA string from JavaScript in Firefox, but not in Chrome.  I don't know the status of this in Safari.

Here's a stackoverflow post I found during my research:
https://stackoverflow.com/questions/42815087/sending-a-custom-user-agent-string-along-with-my-headers-fetch

That SO links to this open Chrome bug on the issue, which has been open since 2015:
https://bugs.chromium.org/p/chromium/issues/detail?id=571722

You can easily set request headers in Shaka Player.  Our tutorial on license server authentication (https://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html) has an example of setting request headers specifically for license requests and specifically to authenticate a user, but you can generalize that to any header on any request.

However, if not all browsers let you set that UA header, there's no point.  Especially when it's disallowed in the most common browsers out there.

> How can I identify Shaka Player's requests on a web server in order to prevent video from accessing by other software?

If your goal is to make sure that only your web client can access the content, a UA header or any other predictable header is a bad idea.  It would be trivial for an attacker to discover the value you were sending and replicate it.  It would be as if the UA string you chose were a password, and you hard-coded that password into your web app and shared that password among all your users.

Do your users have individual logins, or is your app accessed anonymously?  If your users have logins to use your app, you could have your server validate an authentication token when the player requests segments.

The best ways to secure your content would be either to require authentication for access to the content segments or to encrypt the segments and require authentication to get a license to decrypt (DRM).  But both of those solutions require some kind of authentication so you know a request is coming from an authorized user.

Does any of this help?

**Comment by georgio-sd** [comment]
Yes, absolutely! Thanks a lot! I will keep the question open for a while. I will try to apply one of your recommendations.

**Comment by joeyparrish** [comment]
Sounds good.
