### ISSUE TITLE
Cancel a download in progress does not cancel future downloads of segments

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2417]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 2.5.9

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** In the demo app you need use the console to see it, due the demo page doesn't allow cancel a download in progress

**What browser and OS are you using?**
Chrome 80 macOS Catalina

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Any asset downloadable in the demo page

**What did you do?**

```
const storage = new shaka.offline.Storage();
storage.store('https://storage.googleapis.com/shaka-demo-assets/sintel-mp4-only/dash.mpd');
setTimeout(() => {
  storage.destroy();
}, 1000);
```

**What did you expect to happen?**
The download is cancelled and the future download of segments are aborted and then all data downloaded are deleted.

**What actually happened?**

The download is cancelled and the future download of segments are not aborted (so all data is downloaded) and then all data downloaded are deleted.

**Comment by joeyparrish** [comment]
I haven't tested this experimentally, but looking at the code, I can see the issue clearly.  Storage.destroy() waits on all pending operations to complete, including store().  We should be able to interrupt the DownloadManager queue in downloadManifest_.

I'm also seeing a possibly-unrelated bug in store() where it sets an in-progress flag, but there are paths through the code which never reverts it to false.  If you try to store a live stream, it appears as though you'll never be able to use that Storage instance again.  Same if manifest parsing fails.  :-(

I'm not sure why we have this flag in the first place, though.  Canceling DownloadManager is not immediately doable because it's a local variable, not a member.  That would make sense design-wise if we could do multiple store operations at once, but that member flag is meant to explicitly prevent it.

So this is a little bit of a mess.

**Comment by joeyparrish** [comment]
Forked the in-progress flag issue to #2432.

Related issues:
 - #1301: Add pause/resume for downloads.  Related because this will involve interrupting the DownloadManager as well, but in a different way.  Both issues require DownloadManager not to be a local variable.
 - #1362: A specific API for cancelation, without destroying Storage.  If destroy() can cancel correctly, then a top-level API for cancelation will be trivial.
 - #1432: Multiple concurrent store() operations on the same Storage instance.  Moving DownloadManager to a member Map or Array could be part of the solution to this issue, too.
