### ISSUE TITLE
Add a lower res Widevine-encrypted asset

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#2423]
An ask from the Widevine test community :)
Apparently, the test path includes downloading a WV-encrypted asset and downloading an HD asset every time slows the test pass down.

**Comment by joeyparrish** [comment]
When the Shaka Player demo stores offline content, it uses the default track selection callback, which doesn't store the HD tracks.  So the real issue is likely something else, such as the length of the content.  For example, storing 15-minute-long Sintel is likely to take much longer than the 1-minute-long Angel One clip.

It may be that they don't know they can click on the "search" tab and find several encrypted assets to download.  Sintel is the only encrypted content that shows up on the front-page.
