### ISSUE TITLE
Firefox unable to seek in video

### ISSUE THREAD

**Issue by janliska** [google/shaka-player#2427]
We use Shaka player at our streams and it works great at chrome. But at firefox it either don't event start or stops when user moves the seek bar. I will send link to application via email.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
2.5.9

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `master`?**
YES

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
NO

**What browser and OS are you using?**
Firefox, macOS/win

**What are the manifest and license server URIs?**
Will send it via email

**What did you do?**
Play the video in sent link. If it plays, I move the seek bar

**What did you expect to happen?**
Video should start, when user moves the seek bar, it jumps to given playtime and play the video

**What actually happened?**
Video didn't start / stopped when seek

**Comment by joeyparrish** [comment]
What version of Firefox are you using?

**Comment by joeyparrish** [comment]
Also, I see your report says 2.5.9, but the demo you sent appears to be using 2.5.8.  Not sure if this is relevant yet.

**Comment by joeyparrish** [comment]
I'm unable to reproduce on Firefox ESR 68 on Debian Linux, but I **can** reproduce on Firefox 73 on both Ubuntu Linux & Mac.

The error message from the browser was hard to see because of a bug in your app.  You have an error handler like this:

```js
onPlayerError_(errorEvent) {
  doSomethingWith(event.detail);   // <-- should be errorEvent.detail
}
```

But with a debugger, I was able to extract the details from that `errorEvent`.  The `message` field of `errorEvent.detail` says:

> Shaka Error MEDIA.VIDEO_ERROR (3,,NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - ipc::IPCResult mozilla::gmp::ChromiumCDMParent::RecvDecodeFailed(const uint32_t &): ChromiumCDMParent::RecvDecodeFailed)

Which leads me to believe this is a bug in either the Widevine CDM or in Firefox's integration with it.  The CDM version appears to be 4.10.1440.19 in both Firefox 73 (failing) and in Firefox ESR (working), so it may be more likely to be a Firefox bug than a CDM bug.

With your permission, I'll share your application link and credentials privately with the Widevine CDM team to try to find out more.  Would that be okay?

**Comment by janliska** [comment]
@joeyparrish Yep, no problem. Feel free to share the link with Widewine CDM team ;-)

**Comment by joeyparrish** [comment]
Thanks.  If this turns out to be a Firefox bug, as I'm beginning to suspect, we may have to provide repro steps to someone at Mozilla.

I don't know what systems they might have for sharing the access credentials privately.  If we end up filing a Firefox bug, I will CC you on it by email and let you coordinate access for whomever needs it.

**Comment by Pompator** [comment]
We were able to find out that error happens in the moment of change of m4v init file. This occurs when changing ABR profile or during seeking over DASH <Period>.
For testing you can use the previously sent https://drm-test.livesporttv.cloud/issue/index.php (login and password was sent by 'janliska' 28 February 2020, in case of need I can send again).

Latest tests on 77.0.1 (64-bit) and Nightly 79.0a1 (2020-06-08) (64-bit) both for Windows (tested also on earlier versions since inception of this issue).

Would like to receive clarification of anything else? Please let me know.

**Comment by martinstark** [comment]
We are experiencing the same issue in Shaka 3.0.4. Seeking for DRM content in Firefox (79.0) will result in an uncaught promise. 

We will test on 2.5.6, as we have a different platform on that version where it works. Tthere are a few more things that differ between the platforms, so if it's not the shaka version we'll try to better isolate it.

**Comment by martinstark** [comment]
Tested 2.5.6, same issue. The issue only happens when seeking while shaka is trying to fetch a different bitrate variant. If we wait until shaka has switched to the highest bitrate, seeking works fine.

**Comment by kocoten1992** [comment]
> Tested 2.5.6, same issue. The issue only happens when seeking while shaka is trying to fetch a different bitrate variant. If we wait until shaka has switched to the highest bitrate, seeking works fine.

confirmed, I manual select stream, and seeking never fail, it only fail when shaka trying stabilize what stream to select.

**Comment by Pompator** [comment]
read this https://bugzilla.mozilla.org/show_bug.cgi?id=1618529

**Comment by joeyparrish** [comment]
Based on that report, this looks like a Firefox bug triggered by certain values in certain fields in encrypted content.  We'll track the fix on Mozilla's bug tracker for now, since it doesn't look like there's anything Shaka Player could do to work around it.

**Comment by joeyparrish** [comment]
Mozilla has closed the bug as fixed in Firefox 83.

**Comment by joeyparrish** [comment]
Mozilla has decided to pull the fix into Firefox ESR.

**Comment by joeyparrish** [comment]
Mozilla has decided to cherry-pick the fix into Firefox 82 beta, which is expected to go stable on 2020-10-20.  They will not pull the fix into Firefox 81.
