### ISSUE TITLE
Can I completely disable the full screen functionality?

### ISSUE THREAD

**Issue by KentukiS** [google/shaka-player#2436]
Hi,
There were some problems with adding text on top of the player into fullscreen mode, so i thought "can i just turn off full screen mode?" . I will be very grateful if you can tell me about this question.
Or how i can add my text on top of the video in full screen?
I’m thinking about resolving this issue for several days but I think the answer is pretty obvious!
Thanks for the answer!

**Comment by theodab** [comment]
You can change what buttons show up in the UI by configuring the UI. See [our tutorial on the subject](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html).

So for example, to remove the fullscreen button, you could use this code:
```js
const uiConfig = ui.getConfiguration();
// Remove the fullscreen button, but keep all other buttons.
uiConfig.controlPanelElements = uiConfig.controlPanelElements.filter((element) => {
  return element != 'fullscreen';
});
ui.configure(uiConfig);
```

Even without the button, though, a user could theoretically still trigger fullscreen using the JavaScript console, by calling the video element's `requestFullscreen` method. If you want to prevent that, you could over-write that method, and replace it with a no-op.
```js
video.requestFullscreen = () => {};
```

**Comment by joeyparrish** [comment]
If you're having trouble placing text on top in fullscreen mode, it may be because your text is not inside the fullscreen container.

A web app's fullscreen mode makes an arbitrary element (chosen by the developer) the fullscreen element.  For example:

```js
const container = document.querySelector('.shaka-video-container');
container.requestFullscreen();
```

If your text is outside that element, then it won't show up in fullscreen mode.

This also means that stubbing out `requestFullscreen` on `video` won't help, because that's not the element we place in fullscreen mode.  If you just want to remove the fullscreen button from the UI, follow @theodab's instructions above.

**Comment by KentukiS** [comment]
Thank you very much ! You're the best guys)
