### ISSUE TITLE
Non-standard DASH PlayReady UUID

### ISSUE THREAD

**Issue by fergalhanley** [google/shaka-player#2440]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.9

**Please ask your question**
Is there a way to easily specify in the config a key system Id for the DRM that will be returned in the manifest? I'm attempting to playback a PlayReady protected video but the key system Id in the manifest is "79f0049a-4098-8642-ab92-e65be0885f95" but I can see that Shaka has "9a04f079-9840-4286-ab92-e65be0885f95" listed in its map for default key systems Ids. When I replace the key system Id in the player code (purely for test purposes), I can get the player to initiate playback but it is scrambled. I can see that the licence URL is being retrieved from the content protection and the license request is successful.
BTW this is a Brightcove asset reportedly using PlayReady 4.0. I'm testing on a Smart TV (LG). We have a legacy player that can playback the assets correctly so I know the assets are in theory good.

**Comment by theodab** [comment]
As it is now, you can set the `dash.customScheme` config value, if this is from a DASH manifest. This should be a callback that takes in the `ContentProtection` DOM Element, and returns an array of `shaka.extern.DrmInfo` objects that contain the relevant DRM info(s). That is, admittedly, a fair bit of work.

I guess we could also add a way to add non-standard key system IDs so that the parser could use the default process for those, if that would be easier for you. That wouldn't be a big change.

It looks like `79f0049a-4098-8642-ab92-e65be0885f95` is the ID for an old version of PlayReady. There's very little documentation left that mentions it, but I did find an old Microsoft document from 2012 that references that ID. If a legacy player is playing this content but we aren't, even when the DRM engine is told that this is in fact PlayReady content, it's possible there's some implementation difference between the versions of PlayReady that we aren't accounting for. Fixing that would require having some content samples to test with, though.

**Comment by joeyparrish** [comment]
You should be able to add that ID to the map in the DASH parser.  See `shaka.dash.ContentProtection.defaultKeySystems_` in `lib/dash/content_protection.js`.  We'd be happy to accept a PR for this.
