### ISSUE TITLE
How to use debug version and log when importing?

### ISSUE THREAD

**Issue by ngbrown** [google/shaka-player#2465]
I'm using `shaka-player` in a react app, so importing through NPM.  I wanted to debug something with additional logging, but switching to the `shaka-player/dist/shaka-player.ui.debug` doesn't work at all.

I eventually traced it down to the fact that nothing is exported and `wrapper.js` isn't applied when compiling the debug version:

https://github.com/google/shaka-player/blob/64896d70b0b916e379070b1e99f76efc9b118d71/build/build.py#L81-L85

How should we proceed in this situation?  WebPack doesn't usually allow things to ambiently be on global.

**Comment by ngbrown** [comment]
Specifically in a non-ejected `create-react-app`, the WebPack configuration can't be changed to allow ambient global definitions.

**Comment by joeyparrish** [comment]
We must have assumed that module loaders would be used only in production, and didn't consider that for debugging.  So the wrapper is not applied in the debug build.  I'm sure this is something we can change.

I suppose it's safe to change even in the release branch.  If you're using v2.5.x and a module loader, you can't use the debug build today because of the lack of wrapper.  If you're not using a module loader, and you're inserting a script tag directly into your HTML, then the debug build should work with or without the wrapper.

I'll test this and let you know.

**Comment by joeyparrish** [comment]
It seems to work, and it is very simple to add the wrapper.

There is a slight difference, which is that non-exported classes are not available through the wrapper.  Private members of objects are still accessible with their original names in the debug build with the wrapper.

So I think this is an acceptable trade-off.
