### ISSUE TITLE
Language attribute 'spa' v 'es' in HLS Fairplay

### ISSUE THREAD

**Issue by zhulduz** [google/shaka-player#2480]
Hi, shaka-player team!

Our team has one question. We have next HLS playlist
```
#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="eng a1",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="eng",URI="https://domain/tracks-a1/mono.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="spa a2",DEFAULT=NO,AUTOSELECT=YES,LANGUAGE="spa",URI="https://domain/tracks-a2/mono.m3u8"
#EXT-X-STREAM-INF:AUDIO="aac",CLOSED-CAPTIONS=NONE,RESOLUTION=1280x720,FRAME-RATE=29.970,CODECS="avc1.4d001f,mp4a.40.2",AVERAGE-BANDWIDTH=2840000,BANDWIDTH=3550000
https://domain/tracks-v1/mono.m3u8
```
This playlist works on all browsers, but we can't select audio tracks in Safari.

We noticed that if we set `LANGUAGE ='es'` instead of `LANGUAGE ='spa'`, audio tracks in Safari work. 
Do you have any descriptive answer why in MacOS Safari it doesn't work, but in IOS it work?

thanks in advance)

**Comment by joeyparrish** [comment]
Playback on iOS and in many cases on desktop Safari, HLS is played using Apple's native HLS implementation, as opposed to ours.  On iOS, this is because we have no choice (no MediaSource API to do our own).  On desktop Safari, this is the only way to get FairPlay support (for now).

When using Apple's native HLS, we are limited in what we can control.  For example, we can choose audio tracks, but we can't choose the resolution.

When we use our own HLS implementation, we are in complete control.  When we are in control, one of the things we do is normalize the language tags to their shortest form.  For example, both "spa" and "es" identify Spanish, but the canonical form is "es".  HLS specifies that language tags use the shortest form (via reference to [RFC 5646](https://tools.ietf.org/html/rfc5646)).

I don't know if Apple's native HLS will do this language tag normalization for us, so you may be expected to supply 100%-compliant playlists with "es" instead of "spa".

While we're all working from home due to the pandemic, I don't have access to an iOS device.  Can you check something on iOS to help me identify a possible workaround?  Please load the content with `language="spa"`, then open the JS debugger and run this against your Player instance:

```js
player.getVariantTracks().map(t => t.language);
```

What is the array of languages returned by that?

If you're using our demo, you can get a player instance with:

```js
player = video.ui.getControls().getLocalPlayer();
```

Thanks!

**Comment by zhulduz** [comment]
Thanks for the response!
Sorry, I need to clarify about IOS: we tried to launch the same stream through a native player AVPlayer, so there it was possible to switch audio tracks.

I tried to log tacks in `MacOS + Safari`
> const player = video.ui.getControls().getLocalPlayer()
> player.getVariantTracks().map(t => t.language)
< ["en", "es"]

So, I see that tags are normalized, but shaka-player can't switch the tracks 😢 
We can share with you our stream, can we send it in the private dialog?

Thanks, @joeyparrish for trying to help us 🙏

**Comment by zhulduz** [comment]
```diff
3,4c3,4
<         "id": 2,
<         "active": true,
---
>         "id": 4,
>         "active": false,
6c6
<         "bandwidth": 0,
---
>         "bandwidth": 3550000,
9,12c9,12
<         "kind": "main",
<         "width": null,
<         "height": null,
<         "frameRate": null,
---
>         "kind": null,
>         "width": 1280,
>         "height": 720,
>         "frameRate": 29.97,
14,17c14,17
<         "mimeType": null,
<         "codecs": null,
<         "audioCodec": null,
<         "videoCodec": null,
---
>         "mimeType": "video/mp2t",
>         "codecs": "avc1.4d001f, mp4a.40.2",
>         "audioCodec": "mp4a.40.2",
>         "videoCodec": "avc1.4d001f",
19,26c19,22
<         "roles": [
<             "main"
<         ],
<         "audioRoles": [
<             "main"
<         ],
<         "videoId": null,
<         "audioId": null,
---
>         "roles": [],
>         "audioRoles": [],
>         "videoId": 3,
>         "audioId": 1,
32c28
<         "originalAudioId": "0",
---
>         "originalAudioId": "eng a1",
36,37c32,33
<         "id": 1,
<         "active": false,
---
>         "id": 5,
>         "active": true,
39c35
<         "bandwidth": 0,
---
>         "bandwidth": 3550000,
42,45c38,41
<         "kind": "main",
<         "width": null,
<         "height": null,
<         "frameRate": null,
---
>         "kind": null,
>         "width": 1280,
>         "height": 720,
>         "frameRate": 29.97,
47,50c43,46
<         "mimeType": null,
<         "codecs": null,
<         "audioCodec": null,
<         "videoCodec": null,
---
>         "mimeType": "video/mp2t",
>         "codecs": "avc1.4d001f, mp4a.40.2",
>         "audioCodec": "mp4a.40.2",
>         "videoCodec": "avc1.4d001f",
52,59c48,51
<         "roles": [
<             "main"
<         ],
<         "audioRoles": [
<             "main"
<         ],
<         "videoId": null,
<         "audioId": null,
---
>         "roles": [],
>         "audioRoles": [],
>         "videoId": 3,
>         "audioId": 2,
65c57
<         "originalAudioId": "1",
---
>         "originalAudioId": "spa a2",

```

Guys, this is diff `player.getVariantTracks()` between fixed and not fixed playlists

Original playlist - shaka-player can not switch audio tracks in Safari
https://s3.eu-central-1.amazonaws.com/dropshare.yurtaev.link/index_fix_uri_spa.m3u8

Fixed playlist - shaka-player can switch audio tracks in Safari
https://s3.eu-central-1.amazonaws.com/dropshare.yurtaev.link/index_fix_uri.m3u8

**Comment by joeyparrish** [comment]
I have remote access to a Mac for testing purposes.  I can't hear the audio, but I can look at the "active" field of the Track objects returned by the player.  Based on that, I get these results:

 - 3-letter version (non-compliant)
   - `selectVariantTrack(getVariantTracks[1])` works
   - `selectAudioLanguage('es')` does nothing
 - 2-letter version (normalized)
   - `selectVariantTrack(getVariantTracks[1])` works
   - `selectAudioLanguage('es')` works

What's interesting about that is that both versions of the content produce a track list with normalized language codes.

There's probably a place in the code paths for native HLS where we're missing a language normalization step.

**Comment by joeyparrish** [comment]
This is fixed in the `master` branch and in [the nightly build of our demo](https://nightly-dot-shaka-player-demo.appspot.com/demo/).  This should be relatively easy to cherry-pick to our next v2.5.x release, as well.  Please let us know if it's working for you now.

**Comment by zhulduz** [comment]
@joeyparrish , great! It works! Thanks a lot 👍
