### ISSUE TITLE
Audio track without URI tags

### ISSUE THREAD

**Issue by zhulduz** [google/shaka-player#2481]
Hi team!

I have one question about HLS playlist with audio tracks without URI tags. We have a next playlist:
```
#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="eng a1",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="eng"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="spa a2",DEFAULT=NO,AUTOSELECT=YES,LANGUAGE="spa",URI="tracks-a2/mono.m3u8"
#EXT-X-STREAM-INF:AUDIO="aac",CLOSED-CAPTIONS=NONE,RESOLUTION=1280x720,FRAME-RATE=29.970,CODECS="avc1.4d001f,mp4a.40.2",AVERAGE-BANDWIDTH=2910000,BANDWIDTH=3640000
tracks-v1a1/mono.m3u8
```
There are strange cases with this streams
- Chrome: in chrome shakaplayer can't play the stream at all
- FireFox: shakaplayer can play the stream, but doesn't see any audio tracks
- Safari:  shakaplayer can play the stream, it see two audio tracks, but doesn't afford to switch audio tracks

[Link](https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://fl104.test.cdn.alphaott.com/fx_without_drm/index.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled) with the playlist to check.

What do you think, what is incorrect with this playlist?

Thanks in advance, guys )

**Comment by joeyparrish** [comment]
I think the playlist may be incorrect.  Here's why:

Without a URI for the audio stream, this would mean the video playlist contains multiplexed content (audio+video in the segments).  If there's an additional audio stream in a separate playlist, that playlist would be demuxed audio-only segments.

Because of the way the MediaSource API works, there's no reasonable way to play content containing both muxed and demuxed segments.  And if Safari's authoritative native HLS implementation can't completely handle it, that's another good sign that something is wrong with the content.

Does this help?

**Comment by zhulduz** [comment]
Hi @joeyparrish.
Thank you for your help!

Yes, you helped us. We will continue to talk with our Media server about the playlist format.

**Comment by joeyparrish** [comment]
Glad we could help!
