### ISSUE TITLE
load promise doesn't resolve on iOS Safari

### ISSUE THREAD

**Issue by naktinis** [google/shaka-player#2483]
I'm reusing a title of a previously closed issue #2062, because it looks the same, but I can still reproduce it with the latest version and I don't see a way to reopen it.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Not sure how to register events on demo app

**What browser and OS are you using?**
Safari on iOS 13.4

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What did you do?**
Load an m3u8 playlist using shaka load method.

**What did you expect to happen?**
load() promise should resolve and loadeddata on the video should be called without user intervention.

**What actually happened?**
load() promise is only resolved and loadeddata is only called when user clicks "play" on the video.

However, if I set video.src manually and call video.load() directly, it works as expected.

Below is a gist which I used to reproduce this. In the code you can choose which loading method (shaka vs video.src) to use by commenting out one of them.

https://gist.github.com/naktinis/8c3e6423a988a60a93378684a090e3d9

**Comment by theodab** [comment]
Reproduced. I'll look into why this is happening.

**Comment by theodab** [comment]
It looks like, for some reason, media elements on iOS Safari don't fire `loadeddata` or `loadedmetadata` events until there's some user interaction, or the `load` method is called (which is why the simple example in your gist works). See this [StackOverflow answer](https://stackoverflow.com/a/40006785).

So we could make the load method call the `load` method on the video element, which I don't think will break anything. It's not necessary on other platforms, but I guess iOS Safari is just weird.

In the meantime, this can theoretically be solved by setting the media element to autoplay. But that's not an option in every case, obviously.

**Comment by marcelbeumer** [comment]
Hi @theodab and @joeyparrish. In our team we are trying to integrate Shaka and stumbled on the same issue. 

With `.load()` you are forcing preloading the stream, also when the video element has set `.preload` to `metadata`. It even tries to preload the entire stream instead of just a segment or two (at least on the simulator)! And in our case we don't want to preload anything except for the manifest.

There is a way to reliably get the `loadedmetadata` event on Safari/iOS. This is what works in our own internal (custom; non-Shaka) player code with progressive sources, and, though only briefly tested, with HLS sources too:

```
// ... add event listeners
videoElement.src = ''; // always get loadedmetadata also when source did not change
videoElement.preload = 'metadata'; // we force preloading to be off but want to know if manifest is ok
videoElement.src = source.url;
// loadedmetadata (or error ;)) will happen…
```

In our tests (but please verify as we tested `preload=metadata` much better) `loadedmetadata` will also be fired when using `preload=auto`. The `ShakaPlayer.load()` can then just resolve on `loadedmetadata` instead of `loadeddata` as it does now. In case the video element is set to `preload=none` a hard throw/reject may be appropriate.

We're not sure if it affects Shaka, but please note that Safari iOS sometimes has issues with the scenario: (1) load source -> (2) seek -> (3) play. You will need a tick between step (2) and (3) (`await new Promise((r) => setTimeout(r, 0));`

**Comment by joeyparrish** [comment]
@marcelbeumer, I'm not sure if I understood you.  Are you saying that the fix we put in place is wrong, and that we shouldn't call `video.load()` because the app may have `preload=metadata` or similar on the video element?

It seems to me that if they call `player.load()`, calling `video.load()` inside that would be reasonable.  In fact, `preload=` on the video element has no effect with Shaka Player at all as far as I can tell, since we don't set the `src=` attribute until `player.load()` is called.

Am I misunderstanding something?

**Comment by marcelbeumer** [comment]
Hi @joeyparrish, thanks for your quick reply! :) Yes, I think the fix is wrong, and I think there’s a better fix that satisfies more use-cases. I’ll try to rephrase a bit. I also created a JSFiddle that demonstrates the proposed fix and demonstrates the issue with `.load()` (https://jsfiddle.net/marcelbeumer/uo912fjw/show)

I think the current fix is not good, as it does the following on code level on iOS/Safari (in case of using native HLS aka `LoadMode.SRC_EQUALS`):

1. Do `videoElement.src = ` on the video element with the HLS source (https://github.com/google/shaka-player/blob/master/lib/player.js#L2016)
2. Call `videoElement.load()` as the fix to get the `loadeddata` event you wait for (https://github.com/google/shaka-player/blob/master/lib/player.js#L2050)
3. Wait for `loadeddata` to resolve (and `error` to reject) the `shakaPlayer.load()` promise (https://github.com/google/shaka-player/blob/master/lib/player.js#L2039)

There are two problems with this.

1. By waiting for `loadeddata` (in whatever way you get to that event) **you don’t allow the use-case of wanting to load the HLS manifest, but not pre-load the video segments** (yet). Only loading the manifest is default browser behavior when using preload=metadata on the video element. You then want to wait for `loadedmetadata`, as `loadeddata` will not happen (until you call `.play()` or `.load()`). 
2. Even if you want (or don’t mind) to preload some video segments, by calling `.load()` you are not only pre-loading the first few video segments, but **iOS/Safari will preload the entire HLS stream, so all the segments**! It’s hard to imagine this is desired default behavior. 


(Note: replying to your comment; because `shakaPlayer.load()` is the only way to set sources on the video element, and `videoElement.load()` forces loading the entire video I don’t think it means the same, and it’s not a reasonable thing to do)

My suggestion is to wait for the `loadedmetadata` event instead. When the video element has `preload=metadata` it will only load the manifest, and if it has `preload=auto` the browser will determine how far it should preload (differs on Safari/macOS and Safari/iOS). You could implement the following logic (if not mostly in place already) that in our tests is reliable for progressive sources, and during some initial testing also seems reliable for HLS sources (but please re-test as we only did big QA effort on progressive so far):

1. Register event handlers first. Not sure if order matters here, but that’s what we do
2. Unset sources `videoElement.src = ''`. I’m not sure where exactly but I think Shaka is already doing this
3. We always (re)set `videoElement.preload = 'metadata'`. Not sure if that is truly needed, and in case of Shaka you probably want to keep the value the video element already had (none/metadata/auto). Personally I would just throw/reject when the video element has preload=none, because it’s an unworkable setting for loading sources
4. Set `videoElement.src` to the HLS source (`has.mediaElement.src = has.uri;`)
5. On `loadedmetadata` resolve, on `error` reject 


(Note: in case you need to set an initial time offset, you **do** need to work with loadeddata, but **only** to set the currentTime)

Please have a look at this JSFiddle. It implements all this stuff: waiting for loadedmetadata, working with an initial currentTime, and demonstrating how `.load()` forces preloading the entire stream: https://jsfiddle.net/marcelbeumer/uo912fjw/show. Check network traffic to see the differences.

**Comment by joeyparrish** [comment]
Reopening while we investigate the information from @marcelbeumer.

**Comment by joeyparrish** [comment]
Some commits for historical reference:

 - 831dfa616804e07a098327a130f91666169a848f
 - 5411838f7c2b514c47f7b22081b490d766fc0211
 - 9af3b9e2470e37ddc1d8159e14aa88bbb28d1667

> (Note: in case you need to set an initial time offset, you **do** need to work with loadeddata, but **only** to set the currentTime)

This is handled in lib/media/playhead.js using `loadeddata`.  If we change the `load()` Promise event, that can still be handled with `loadeddata`.

It seems to me that if you want to preload the playlist only, that would be more in line with the preload API that we have planned.  As it stands now, the `Player.load()` method is meant to actually load content, but with src= mode, the distinctions are less clear.

If the browser's native HLS implementation has no limit to the amount of content it buffers when you call `.load()`, that's not something we can control, as far as we know.  (If we could, we would.  Please correct me if I'm wrong.)  And unlimited HLS buffering in Safari *sounds* like a bug that should be filed on WebKit.

But, all of that said, I don't see any reason why we shouldn't be able to use `loadedmetadata` to resolve the `load()` Promise.  Your jsfiddle works for me, and I've made a few modifications to try out more variations.  I've testing preload `metadata`, `auto`, `none`, and unset, and I made a few other small changes to make it more similar to Shaka Player's internals.

You're right about `preload=none` causing problems.  With that, `play()` is required to get the `loadedmetadata` event.

I didn't fully understand what you were trying to tell me until I modified your fiddle and played with it in Safari.  Mine is at https://jsfiddle.net/8wmdknys/4/ .  Here are the results I've compiled:

`preload=` | `loadedmetadata` fires | `loadeddata` fires | browser default in...
----- | ----- | ----- | -----
`auto` | after `src=` is set | automatically after `loadedmetadata` | desktop Safari, iOS Safari, iOS Chrome
`metadata` | after `src=` is set | after `play()` or `load()` | desktop Chrome, Android Chrome
`none` | after `play()` or `load()` | automatically after `loadedmetadata` |

The original bug report did not include a specific `preload` value.  On my copy of desktop Safari, it seems to default to `auto`.  Although our tests show the same default on iOS, it's possible that a different version may have defaulted to `metadata`, which would explain the symptom in the bug report.

It looks like the browser default can be read from JavaScript, even if there is no `preload` attribute in the HTML.  So we should be able to warn the app developer or try to implement some fallback behavior if `preload=none` is set or if it's the default for some browser we haven't tried.

**Comment by marcelbeumer** [comment]
Great @joeyparrish, thanks! Let me know if we can help in any way!

Wrt to what `shaka.load()` means and does: as a developer I expected `shaka.load()` to load the "video sources" to a certain point depending on (Shaka) prefetching settings. The minimum being only the playlist/manifest (with a zero second prefetching setting of sorts), and from that point on x-amount of video segments. For non-MSE/set-src there's no control beyond what the preload attribute does so it's either manifest-only or however-far-the-browser-wants. I think you basically write the same thing, or do I misunderstand it?

**Comment by joeyparrish** [comment]
This should now be fixed in the master branch and in the nightly build: https://nightly-dot-shaka-player-demo.appspot.com/demo/

I expect to be able to cherry-pick everything to v2.5.x and release in v2.5.12 soon, as well.

Please let us know if you have any further issues with this!

**Comment by avelad** [comment]
@joeyparrish , this change breaks the change of https://github.com/google/shaka-player/issues/2269

Setting preferredAudioLanguage and preferredTextLanguage only works with loadeddata in Safari. And with this change it was changed to loadedmetadata

**Comment by joeyparrish** [comment]
I'll move the language setup to HAVE_CURRENT_DATA and leave the Promise resolution at HAVE_METADATA.  @avelad, does that sound good?

**Comment by avelad** [comment]
Yes, that would work.

**Comment by joeyparrish** [comment]
Great.  I'll add a regression test, as well.

**Comment by joeyparrish** [comment]
It isn't working the way I expected.  I find that selecting tracks on HAVE_CURRENT_DATA / loadeddata results in:
 - audio track selection works, but the effect is not **observable** until a few hundred ms later
 - text track selection works, but gets **reverted** by some unknown process a few hundred ms later

:-(

I believe this deserves its own issue, so I'll start a new one.

**Comment by joeyparrish** [comment]
Filed #2593 to track.  Sorry for the trouble!
