### ISSUE TITLE
Ad UI's localization isn't handled well for any language but English

### ISSUE THREAD

**Issue by ismena** [google/shaka-player#2485]
1) Select something other than English as your UI languages (I tried 'de', 'ru', and 'zh').
2) Pick an asset with an ad. 
3) :(

This is true for both ad counter and the 'ad X of Y' tracker. Something seems to go wrong with our resolution of the formatted loc strings.

**Comment by ismena** [comment]
Since my "what went wrong" step isn't terribly detailed: ad UI looks is formatted like " [AD_TIME:0:05/0:10]" instead of just showing "0:05/0:10," which expected behavior.

**Comment by theodab** [comment]
Hm. I think the code for converting the raw translated files back into the final files must not be working correctly.
Looking at, for example, `de.json`, the `AD_TIME` entry is:
```
"AD_TIME": "Werbeanzeige: [AD_TIME:0:05/0:10]",
```

Our script is supposed to translate that into:
```
"AD_TIME": "Werbeanzeige: [AD_TIME]",
```


I... probably should have tested that script more thoroughly, huh. I wonder what's wrong with it.

**Comment by theodab** [comment]
Looking at the python script for translating, I have to wonder if the translation console, in the output, fills the contents of the "example" field in where the placeholder was before. That would explain these results, anyway; the current code expects the entire placeholder markup to be present in the translation console output. If the problem was in the regex, I'd expect to be seeing tons of JSON in the resulting files instead.

**Comment by joeyparrish** [comment]
We can fix the files in our repo now to unblock the next release.  Then we have a little more time to fix the automation that extracts the translations from our internal translation system.
