### ISSUE TITLE
HLS timestamp issues with MediaSource

### ISSUE THREAD

**Issue by buriedgod** [google/shaka-player#2527]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.10

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
haven't tried

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
chrome on linux (amd64) / MacOS Catalina

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Haven't tried / using those.

**What are the manifest and license server URIs?**

Cannot be public.

**What did you do?**

A live manifest is playing fine on Safari on a Mac ( using native HLS on Safari ), but when the same manifest is tried to be played else where it is shows buffering for a little time and doesn't play at all.

Update: 
I have tried to diagnose the problem on other platforms.
Here are my observations :
When giving the Start at segment boundary, on a fresh start, the shaka player plays till the bufferingGoal duration, (ie, if it is 30s it plays fine for 30s and then stalls).
I put the logs on v2, and here's my interpretation: the timeNeeded set from the first segment is way too higher than it should be, after the first buffered data is played, it stalls by trying to increment the presentation time second by second to reach there but will be too far away.
But this problem is not happening on a Safari on a MacOS where native play is used by the shaka player.

**What did you expect to happen?**
Shaka player to play based on the hls manifest on other platforms and browsers too.

**What actually happened?**

The player stalls by setting a wrong timeNeeded, that's way too large than expected and waits for the timeNeeded to match with the presentationTime.

![Screenshot from 2020-04-23 23-06-16](https://user-images.githubusercontent.com/33516031/80131125-62201300-85b7-11ea-97d4-eee4a85069ac.png)
![Screenshot from 2020-04-23 23-07-18](https://user-images.githubusercontent.com/33516031/80131137-68ae8a80-85b7-11ea-9ab1-a31abd7369f7.png)

**Comment by joeyparrish** [comment]
> Shaka Plays HLS only on Native HLS on safari not on chrome or firefox or in other platforms

Native HLS playback only exists in Safari, iOS, and Android.  It is not available on other platforms.

> the timeNeeded set from the first segment is way too higher than it should be

This sounds like an issue with the timestamps in our segment index.  It is likely to be content-specific, since we don't see that same issue with all HLS content.

> **What are the manifest and license server URIs?**
> Cannot be public.

We provided an email address in the bug template where you can send private URIs.  They will not leave the Shaka Player team at Google.  Please reference this issue number when you send them.

You can also try the other HLS content in our demo to see if there is a way to reproduce it with public content.  Please see this page in our nightly demo: https://nightly-dot-shaka-player-demo.appspot.com/demo/#panel=ALL_CONTENT;panelData=HLS

If you can't give us a way to reproduce the issue, then there is no way we could fix it.

**Comment by buriedgod** [comment]
thanks for the quick respose @joeyparrish !
I will have the Priavte URI sent in a day, sorry about the delay, i have to get some approvals.

Update on bug hunting: I went back to the transcoder logs and it has an error ( this is from ffmpeg) [mp4 @ 0x7f8394039f00] Non-monotonous DTS in output stream 2:0; previous: 4578422225, current: 778956; changing to 4578422226. This may result in incorrect timestamps in the output file.

This is causing the playback block on Shaka Player , but still curious about how Apple Native HLS handles this and plays it smoothly.

Note: I was actually confused at the Bug Report Template on how to refer the issue to the email, because at the bug report drafting there is no issue id attached to it.

**Comment by joeyparrish** [comment]
`MediaSource` uses the timestamps in the container, with some adjustments set by the JavaScript app (in this case, by Shaka Player).  So if there is a bad timestamp, that would affect playback.

Native HLS could ignore the timestamps in the container and just stitch each segment in after the previous.  We don't know anything about how Apple's native HLS would work internally.

`MediaSource` has a similar mode where the timestamps don't matter, but we don't use it in Shaka Player.  This is partly because it didn't exist when we started the project, and partly because we would need to do more to manage it, especially around seeking.

**Comment by joeyparrish** [comment]
Based on your ffmpeg log message, though, I would suppose the content itself is at fault.  If the timestamps are suddenly discontinuous, there would have to be a discontinuity tag in the playlist.  If not, we would not be able to play it correctly.

Also, please note that discontinuity tags are only supported in v2.6+, so you should test on the nightly build of Shaka Player as well: https://nightly-dot-shaka-player-demo.appspot.com/demo/

If the content doesn't work on the nightly build, my next question is whether or not it has a discontinuity.  If it doesn't, then I would label this issue as "bad content".  If it does, then we can look into it once you share the URI.

Does this help?

**Comment by buriedgod** [comment]
@joeyparrish it helped a lot! Thanks a lot for your inputs!!
and there was no discontinuity tag in the playlist, and wasn't playing in the nightly build too.
Please label this as a bad content.

**Comment by joeyparrish** [comment]
Done.  I would suggest filing an issue against ffmpeg next and letting them know that when this happens, they should add the discontinuity tag to the playlists.  Thanks!
