### ISSUE TITLE
Missing event for audio track changed

### ISSUE THREAD

**Issue by itaykinnrot** [google/shaka-player#255]
When choosing an audio track i expect the play to notify me once the track changed.
Doesn't work for both clear buffer and leave buffer.
I tried listen to trackchanged event. [Live]

Thanks,

**Comment by joeyparrish** [comment]
The 'trackschanged' event does not tell you when you selected a new track.  It tells you when the list of tracks has changed.  To quote [the documentation](http://shaka-player-demo.appspot.com/docs/shaka.player.StreamVideoSource.html#event:TracksChangedEvent), it is fired "when one or more audio, video, or text tracks become available or unavailable."

For example, if an MPD update includes Representations that weren't there before, you might have new tracks.  Or if Representations go away, you might lose tracks.

Another example is if you have encrypted content with different keys for SD/HD/UHD.  If you only have SD keys, for example, you will only see SD tracks.  If a subsequent license request returns keys for HD, you will then have new HD tracks available.

In your case, the tracks have not changed.  You have selected a different track.  Since you did it explicitly, you know that you did it.  Therefore in our view, you should not need an event to tell you about it.

Does this help clear things up?

**Comment by joeyparrish** [comment]
Since it has been three weeks without comment, I am closing this issue.  If you still need help with this, please let us know and I will reopen the issue.
