### ISSUE TITLE
How to get bufferingHistory, streamHistory & bandwidthHistory info in shaka player?

### ISSUE THREAD

**Issue by JeffrinManovaPrabahar** [google/shaka-player#2560]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.9-debug

**Please ask your question**
As per [this doc](http://v1-6-2.shaka-player-demo.appspot.com/docs/shaka.player.Player.html) `getStats()` returns `shaka.player.Stats` which has `bufferingHistory, streamHistory & bandwidthHistory`, but when I call `getStats()` it is not returning those details. Is that doc an outdated one? If so how can I get these details `bufferingHistory, streamHistory & bandwidthHistory` in latest version of shaka player?

**Comment by TheModMaker** [comment]
This was changed since 1.6.  Check our our [latest documentation](https://shaka-player-demo.appspot.com/docs/api/index.html) for more info.  Specifically, [here](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.Stats) is the new struct.  The new names are `stateHistory` and `switchHistory`.

**Comment by JeffrinManovaPrabahar** [comment]
Thank you @TheModMaker .
