### ISSUE TITLE
Error 3004 MP4_SIDX_WRONG_BOX_TYPE in react front end shaka player initialization

### ISSUE THREAD

**Issue by lovgrandma** [google/shaka-player#2571]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.10

**Please ask your question**
After providing access to my s3 objects via cloudfront and fixing the CORS issues, I am receiving error 3004 in my console on the React front end when loading the manifest. Is there any insight on why this error is occuring?

Error shown in console: `Error code 3004 object F {severity: 2, category: 3, code: 3004, data: Array(0), handled: false} `

The error is shown in the documentation as:

`MP4_SIDX_WRONG_BOX_TYPE | 3004 | number | The MP4 SIDX parser found the wrong box type. Either the segment index range is incorrect or the data is corrupt.`

The data is definitely not corrupt because when I download them from s3 using the cloudfront links they all play properly. At first I was getting Cors errors on the cloudfront linked playback files, but when I changed my cors info I do not get those errors so I assume it is accessing the files easily.

I am generating the mpd using a shaka packager script in my code. I am accessing the manifest with a url like this "https://XXXXXXXXXXXXX.cloudfront.net/2671973acf374aa6b4de19fe83033196-mpd.mpd"

I have included the mpd in a txt format here
[exampleMpd.txt](https://github.com/google/shaka-player/files/4624906/exampleMpd.txt)

**Comment by theodab** [comment]
Without actually being able to see your media files, it's hard to say what the exact problem is. Without that information, the two possibilities that come to my mind are:

1. The ranges provided in the manifest are incorrect. Your example manifest has, in it, some byte ranges that tell the player what parts of the media files to download. If the ranges are incorrect, the parser might be unable to locate the `sidx` box.

1. The media files aren't fragmented mp4. A non-fragmented mp4 will be playable in a browser or media player, but it does not contain a `sidx` box and is not structured to be downloaded in segments.


If your content cannot be shared publicly, you can send confidential things to <shaka-player-issues@google.com>. URIs that we can use to try to play your content are ideal, but an MPD and a corresponding mp4 file will probably also suffice for diagnosis. Knowing the exact commands you are using with Shaka Packager will probably be useful too, in case the problem is with the manifest.

**Comment by lovgrandma** [comment]
> Without actually being able to see your media files, it's hard to say what the exact problem is. Without that information, the two possibilities that come to my mind are:
> 
> 1. The ranges provided in the manifest are incorrect. Your example manifest has, in it, some byte ranges that tell the player what parts of the media files to download. If the ranges are incorrect, the parser might be unable to locate the `sidx` box.
> 2. The media files aren't fragmented mp4. A non-fragmented mp4 will be playable in a browser or media player, but it does not contain a `sidx` box and is not structured to be downloaded in segments.
> 
> If your content cannot be shared publicly, you can send confidential things to [shaka-player-issues@google.com](mailto:shaka-player-issues@google.com). URIs that we can use to try to play your content are ideal, but an MPD and a corresponding mp4 file will probably also suffice for diagnosis. Knowing the exact commands you are using with Shaka Packager will probably be useful too, in case the problem is with the manifest.

I sent the uri's to that address. I will repeat my issues here. I am unsure how to calculate the correct ranges, I apologize if this is already in the documentation. Also, I don't think my mp4's are fragmented, so I will look into ffmpeg commands to achieve this. Any guidelines as to how to do this nicely for shaka player would be appreciated. An example command that runs in my server script is:
`cd scripts/src/out/Release && packager.exe in=../../../../temp/ed71f5aa6fae488e94e77a7e30c56af2-audio.mp4,stream=audio,output=ed71f5aa6fae488e94e77a7e30c56af2-audio.mp4 in=../../../../temp/ed71f5aa6fae488e94e77a7e30c56af2-480.mp4,stream=video,output=ed71f5aa6fae488e94e77a7e30c56af2-480.mp4 in=../../../../temp/ed71f5aa6fae488e94e77a7e30c56af2-360.mp4,stream=video,output=ed71f5aa6fae488e94e77a7e30c56af2-360.mp4 --mpd_output ../../../../temp/ed71f5aa6fae488e94e77a7e30c56af2-mpd.mpd"`
