### ISSUE TITLE
Using signed cookies 

### ISSUE THREAD

**Issue by lovgrandma** [google/shaka-player#2573]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.10

**Please ask your question**
I am trying to use Cloudfront signed cookies in order to prevent public access to hosted videos and only allow them on the website. My application correctly stores httpOnly CloudFront cookies to the users browser and I have used the following code below to enable cross resource credentials. 
```
player.getNetworkingEngine().registerRequestFilter(function(request_type, request) {
       request.allowCrossSiteCredentials = true;
});
```

Everything works well when I set the cloud front access to public, videos playback fine. But when I set "Restrict Viewer Access (Use Signed URLs or Signed Cookies)" on aws cloudFront and whitelist ALL cookies, they still do not get sent in the request (Shows in network) How do I get shaka player to use these cookies in its request for resources? The error I receive is `failed to fetch 1002`

Cookies names are "CloudFront-Key-Pair-Id, CloudFront-Policy and CloudFront-Signature"

**Comment by joeyparrish** [comment]
Please check out the "Cookie Authentication" section in our [License Server Authentication tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html), specifically the CORS part which says:

> Cookies are considered "credentials" by the browser's XmlHttpRequest API, and credentials may not be sent cross-origin unless:
> 
> 1. [explicitly requested by the application](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Requests_with_credentials) **AND**
> 2. [explicitly allowed by the destination server](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Access-Control-Allow-Credentials)

Part one of this is handled by `request.allowCrossSiteCredentials = true` in your request filter, so that's taken care of.

Part two is that if your server doesn't send the `Access-Control-Allow-Credentials` header in the preflight (`OPTIONS`) response, then the client will not send the cookie.  This is a web standard implemented inside the browser, so we have no control over this in Shaka Player.

We can't see what's being sent between your browser and your server, and we are no experts on Cloudfront, but if setting "Restrict Viewer Access" changes the CORS response headers coming from your server, that might explain the difference.

Does this help?

**Comment by lovgrandma** [comment]
> Please check out the "Cookie Authentication" section in our [License Server Authentication tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html), specifically the CORS part which says:
> 
> > Cookies are considered "credentials" by the browser's XmlHttpRequest API, and credentials may not be sent cross-origin unless:
> > 
> > 1. [explicitly requested by the application](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Requests_with_credentials) **AND**
> > 2. [explicitly allowed by the destination server](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Access-Control-Allow-Credentials)
> 
> Part one of this is handled by `request.allowCrossSiteCredentials = true` in your request filter, so that's taken care of.
> 
> Part two is that if your server doesn't send the `Access-Control-Allow-Credentials` header in the preflight (`OPTIONS`) response, then the client will not send the cookie. This is a web standard implemented inside the browser, so we have no control over this in Shaka Player.
> 
> We can't see what's being sent between your browser and your server, and we are no experts on Cloudfront, but if setting "Restrict Viewer Access" changes the CORS response headers coming from your server, that might explain the difference.
> 
> Does this help?

This helps very much so. I am debugging right now. If this doesnt work I may just avoid it and make access public until I start using something a little more sophisticated like widevine

**Comment by TheModMaker** [comment]
Does this answer all your questions?  Can we close this issue?
