### ISSUE TITLE
v2.6 renamed to v3.0

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#2598]
Hi everyone,

After some internal discussion, we have decided to rename our upcoming v2.6 release to v3.0.  This is primarily because this release breaks compatibility with our previous manifest structure, but also because we have not been strict about semantic versioning in the past.

From now on, we will try to follow the rules of [semantic versioning](https://semver.org/) closely.  This means v3.14.159, for example, should be an API-compatible drop-in replacement for v3.0.0.  We will continue to change and deprecate interfaces if they remain backward compatible, but we will no longer remove any deprecated feature without a major version bump.  We will try to batch such removals together to reduce major-number-churn.

There will be two caveats, though, to our compatibility strategy:

1. Some features may be marked as "beta" features in the future, as a signal that the API is not yet stable and could change at any time.  We are still discussing how this would work, and we welcome your input.

2. We still anticipate changes to the internal manifest structure and manifest parser plugin interface in the future.  There is high-level feature work planned that could affect these areas, so apps that call `getManifest()` or provide their own manifest parsers will have to consider these parts of the API "beta" for now and make changes at minor version upgrades.  We expect that custom manifest parser plugins and users of `getManifest()` will be rare.  So if you do either of these things in your app, please provide feedback on this issue to help us understand your use cases so we can make better plans.

Thanks!
-Joey, on behalf of the Shaka Player Team

**Comment by avelad** [comment]
We are using the following

`player.getManifest().presentationTimeline.getMaxSegmentDuration()`

This is used so that in the debugging panel that we have we can have information without having to go to the file and see what is coming to us. If there is a way to expose this elsewhere I would stop using it, for example stats or a new api at the player level

**Comment by joeyparrish** [comment]
Sounds good.  Please start a new feature request for that.  It should be easy to add that to getStats().  And if you're feeling motivated, please feel free to follow that up with a PR.  :-) Thanks, Álvaro!

**Comment by OrenMe** [comment]
we are using getManifest to calculate the buffer target value by accessing getSegmentAvailabilityEnd and getSeekRangeEnd and current segment length via periods.variants.
This is used for low level analytics for our use case.

How can we expose this data? maybe add some callback for each segment availability with this data instead of exposing it via stats, something like the analytics listener in exoplayer.
