### ISSUE TITLE
DASH Widevine Playback : Ununderstable 4012 error

### ISSUE THREAD

**Issue by hdodev** [google/shaka-player#2600]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, I found the same kind of problem, but I'm don't have Playready DRM, nor multi-periods.

**What version of Shaka Player are you using?**
2.5.10

**Please ask your question**
I have the following error, but I don't understand where the key is missing. In manifest? In chunks?
- In manifest I have the default_key_id
- In manifest I have the pssh

{"severity":2,"category":4,"code":4012,"data":[{"hasAppRestrictions":false,"missingKeys":["30303030303030303030303231363235"],"restrictedKeyStatuses":[]}],"handled":false}}]

Thanks for your help.

**Comment by TheModMaker** [comment]
4012 is [RESTRICTIONS_CANNOT_BE_MET](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:4012).  This means all streams are restricted and we cannot play anything.  The `data` field gives some more info about why this happens.  In this case, we don't have the `30303030303030303030303231363235` key.  This is likely because your license server hasn't returned the required keys or the `default_kid` attribute is incorrect.

**Comment by hdodev** [comment]
HI @TheModMaker , thanks for the answer. I will contact my Licenser team, but I tkink it's maybe to due to the key rotation of my Live stream.

For the moment, let's close the question, I'll reopen it if need.

Best regards
