### ISSUE TITLE
Error 405 + Nginx

### ISSUE THREAD

**Issue by theraw** [google/shaka-player#2616]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
tried to look around didn't find smth useful

**What version of Shaka Player are you using?**
latest

**Please ask your question**
why shaka player loads this `m3u8` successfully
```
https://us.akami.dopemovie.cdn.nightproxy.com/test1/test1.m3u8
```
but fails with this 
```
https://us.akami.dopemovie.cdn.nightproxy.com/test2/aac45a27-4bf5-4c51-b34c-cef25afa7cf3/_apis/git/repositories/0a9a750f-d64c-4775-9a99-7c213c0f40fa/items?path=/test1.m3u8


Request URL: https://us.akami.dopemovie.cdn.nightproxy.com/test2/aac45a27-4bf5-4c51-b34c-cef25afa7cf3/_apis/git/repositories/0a9a750f-d64c-4775-9a99-7c213c0f40fa/items?path=/test1.m3u8
Request Method: HEAD
Status Code: 405 
Remote Address: 94.245.93.91:443
Referrer Policy: no-referrer-when-downgrade

core.js:6210 ERROR Error: Uncaught (in promise): shaka.util.Error {
  "severity": 2,
  "category": 1,
  "code": 1001,
  "data": [
    "https://us.akami.dopemovie.cdn.nightproxy.com/test2/aac45a27-4bf5-4c51-b34c-cef25afa7cf3/_apis/git/repositories/0a9a750f-d64c-4775-9a99-7c213c0f40fa/items?path=/test1.m3u8",
    405,
    "",
    {
      "cache-control": "no-cache, no-store, must-revalidate",
      "content-length": "93",
      "content-type": "application/json; charset=utf-8",
      "expires": "-1",
      "pragma": "no-cache"
    },
    0
  ],
  "handled": false
}
```

i mean is the same `test1.m3u8` file only url is longer, what's the reason?!

**Comment by joeyparrish** [comment]
HTTP 405 means "Method Not Allowed".  The server has rejected one of our requests.

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

Can you check the networking panel of the browser's debugger to see what the method was?  If it's a GET request being rejected, then that would clearly fall on your server, because GET should definitely be supported.  If it's an OPTIONS request, that is also for your server to fix, but then I would point you to MDN's articles on CORS (Cross Origin Resource Sharing):

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

CORS can be thought of as the rules for how browsers access content from a different origin than the page.  It's not up to the JS app to control.  The server needs to explicitly allow cross-origin access from the requesting origin.

Specifically, OPTIONS requests are part of CORS Pre-Flight requests which happen when certain conditions are met in the request.  It's a way to get permission from the server _before_ the real GET request happens, instead of the browser potentially rejecting the response _after_ it happens.  See more on pre-flight here:

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests

Does this help?

**Comment by TheModMaker** [comment]
In this case, we are sending an explicit HEAD request to guess the manifest type.  Since your URL doesn't have a normal file extension in it, we send a HEAD request and use the `Content-Type` of the response to determine how to parse the manifest.  You could alternatively pass the content type as a third argument to `player.load`.

**Comment by theraw** [comment]
@joeyparrish it's a simple reverse proxy which contains same cors rules the only thing that changes is url in test1 is shorter url, and in test2 url is longer and contains `? and =`

@TheModMaker afaik https://en.wikipedia.org/wiki/Filename_extension file extension is `.m3u8` both urls contain the same `.m3u8` at the end the only thing that changes is that one is longer and it contains `? and =` and the other one is shorter

**Comment by TheModMaker** [comment]
In the second URL, the `.m3u8` at the end is part of a query parameters.  They are just extra data to pass along with the request and do not affect the path being queried.  The file path being queried is called `items`, you are just passing some extra data that happens to also have a file extension.  But we have no way of knowing the query parameters are paths, they could be anything.

**Comment by theraw** [comment]
@TheModMaker thanks for explanation
