### ISSUE TITLE
Local .mpd files not streaming in Node.js

### ISSUE THREAD

**Issue by pranjal5399** [google/shaka-player#2622]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, I have read and there isn't a similar issue.

**What version of Shaka Player are you using?**
v 2.5.12

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
NA

**What browser and OS are you using?**
Browser: Chrome. OS: Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

NA
**What did you do?**
I have a video file (.mp4) in my system in C drive I have converted it into .mpd using FFmpeg and fluent-FFmpeg in Node.js and then copy-pasted the .mpd file path in javascript var manifestUri = " " variable.

**What did you expect to happen?**
I expected that the video would play

**What actually happened?**

Error 1001 in the console was the output.
Can you please tell me where and how to put these .mpd files so that they would get played on the browser
![Capture](https://user-images.githubusercontent.com/61688724/83997391-e833c580-a97b-11ea-81f4-10df5bb310fc.PNG)

**Comment by TheModMaker** [comment]
You need to enter a web URL, not a local file path.  So `/foo/bar` won't work since it will interpret the path as a web URL relative to the current web page.  Some browsers support local files using `file:///foo`, but not all browsers allow reading local files.  You need to serve the MPD and segments on a web server for the browser to be able to read them.

**Comment by joeyparrish** [comment]
The URL in your screenshot has `/sample.mp4/sample.mpd` in it.  Do you have a folder called sample.mp4?  Seems odd.

In any case, your local web server returned HTTP 404, so that is not the correct URL.  We can't tell you what the correct URL would be, because that is dependent on your server and how you set it up.

Does this help?

**Comment by pranjal5399** [comment]
I do have a folder name sample.mp4 which contains sample.mpd. @TheModMaker can you give me some idea on how to serve the MPD and segments on a web server for the browser. Any resources will help

**Comment by pranjal5399** [comment]
@joeyparrish can you give me some idea on how to serve the MPD and segments on a web server for the browser. It would really be of great help

**Comment by joeyparrish** [comment]
I would suggest you Google "Apache setup" and add a search term for whatever operating system you're using.  It's free, open-source, and available across Linux, Windows, and Mac.  You can use it locally for testing and development without needing to host anything publicly.

You could also chose to use a hosting service or cloud storage service to host content publicly, if you want.  I wouldn't bother until I was ready to publish something, though.

**Comment by pranjal5399** [comment]
Thank you @joeyparrish .
