### ISSUE TITLE
Bad content, audio-video misaligned, video starts at 2.002s

### ISSUE THREAD

**Issue by apblack96** [google/shaka-player#2640]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
v3.0.0-2-ga8318f50 and v3.0.0 (uncompiled)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo App

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome and MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

N/A
**What are the manifest and license server URIs?**
Due to contractual obligations we are unable to provide the manifest and license server URI's however I can provide any browser network traffic and try and provide any additional information you need.

**What did you do?**
Created a custom content stream for a VOD asset. Filled out Manifest URL, Name, Custom License Server URL.
Went to play the asset using the Shaka Player build v3.0.0-2-ga8318f50 and nightly Shaka Player build the player is requesting a segment that is not the first segment of the video.
So playback does not work for the first x amount of time in the video.

This issue occurred in an earlier release of the 2.5.x branch. (See Issue #2111)
**What did you expect to happen?**
Asset to Playback properly

**What actually happened?**
When attempting to play an asset on the latest build of Shaka Player v3.0.0-2-ga8318f50 and the nightly build at (https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;) the player is requesting a manifest segment that is not the first segment of the asset. Therefore the asset starts playing at 1:22:50 seconds rather than the beginning of the asset. We tested another VOD asset and saw the same behavior.

**Comment by joeyparrish** [comment]
> **What are the manifest and license server URIs?**
> Due to contractual obligations we are unable to provide the manifest and license server URI's however I can provide any browser network traffic and try and provide any additional information you need.

I don't see any way for us to debug this issue for you.  I believe you, but there's no way for my team to work on an issue unless you can provide *some* way to reproduce it.

Can you find any free content that exhibits the same behavior?

Can you run some free content (Big Buck Bunny, Sintel, etc) through the same encoder/packager and share that with us?

**Comment by apblack96** [comment]
@joeyparrish I've got Sintel running through our environment. I have sent the manifest and license services server URI to shaka-player-issues@google.com. Please let me know what you find!

**Comment by joeyparrish** [comment]
I see `Ignoring large gap at 0 size 2.002` in the JS console when I play this.

`player.getBufferedInfo()` shows that audio starts at 0.046433, but video starts at 2.002.

Looking at the MPD, both audio and video `<SegmentTemplate>` elements have `startNumber="1"` and `presentationTimeOffset="0"`.

If I construct the URL for segment number 0, I get HTTP 404, so we know the `startNumber` is correct.

Since `presentationTimeOffset` is 0, we are not manipulating the timestamps at the `MediaSource` level at all.  I have confirmed in the debugger that `timestampOffset` is 0 on the video `SourceBuffer`.

If I fetch the init segment and first segment for each video and audio, concatenate the init segment and media segment for each video and audio, and analyze them in the command-line `mp4info` tool, I see that the first sample for audio has a timestamp of 46 ms, while the first sample for video has a timestamp of 2002 ms.

So the timestamps in the content actually do not start at 0.  The MPD doesn't match the underlying media, and video doesn't match audio.

If you seek in Shaka Player to time 2.002 seconds, playback begins at the beginning.  We're not skipping the first segment, but the first segment has the wrong timestamp.

Please report this to your packager/encoder and see if they can offer you any support.  In some cases, this could be a bug in the packager/encoder, or it could be a problem with the configuration or inputs fed to it.

Does this help?

**Comment by apblack96** [comment]
@joeyparrish So I understand you point with a misaligned video and audio segment, and I will definitely take a look at our encoder/packager setup to see what happened. However I want to not that we are able to get this same piece of content to stream without issue using the https://bitmovin.com/demos/stream-test player, Im wondering if there is some additional feature you can add to remedy this on Shaka Player.

**Comment by joeyparrish** [comment]
It is *possible* that we could distrust the metadata in the MPD *and* the timestamps in the media and *somehow* rewrite all the timestamps and correct broken media... but that way lies madness.

We don't have the resources to support arbitrarily broken content, because there are roughly infinite ways it could be broken.  Besides this, a fix for one piece of bad content could break another piece of bad content we tried to fix, or even break *good* content, all the while horribly complicating the source code.

If you have a concrete suggestion for a way we could interpret your content to make the system more robust, I'm all for it.  Otherwise, whatever Bitmovin does is their own proprietary magic, and perhaps that's one of the reasons they can charge whatever it costs.  You're always welcome to choose the solution that works best for you.
