### ISSUE TITLE
Buffering settings in live stream mode

### ISSUE THREAD

**Issue by EduardWorrk** [google/shaka-player#2680]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.1 (2020-06-18)

**Please ask your question**
When pause is pressed, I want the video to start from the place where there was a pause in live stream mode. I tried buffering settings, but this did not give any effect. What parameters are needed to achieve this effect?

**Comment by ismena** [comment]
Is your content LIVE or HLS? For LIVE streams, when they are unpaused, we will start from the same point unless it's outside the availability window (already played segments can become unavailable in the server in LIVE streams).
By default, we treat availability window in HLS streams as 0 (assume that segments disappear right away), and for DASH we try to get this value from the manifest (I can't remember at the moment where it is exactly, but I can find it if you're interested).

You can configure this though! 
If you know that in how long the segments will be available in your LIVE content, you can set the [availabilityWindowOverride](https://github.com/google/shaka-player/blob/606457488f77e9cf5cac2c82e94bb4ce35d50e2a/externs/shaka/player.js#L671) value in the manifest configuration.

Let me know if this makes sense at all (I know it's a lot of random info). I can help you with configuring the values for the player, if that works for your app.

**Comment by EduardWorrk** [comment]
@ismena Yes, I really need help with the settings. 

 Format: Live

I need when you click on a pause lasting 3-5 minutes, the video starts from the same point where the pause was pressed. I have already tried different settings:
     streaming: {
          bufferingGoal: 100,
          durationBackoff: 1,
          rebufferingGoal: 50,
          bufferBehind: 60,
        },
But it had no effect.

**Comment by joeyparrish** [comment]
Buffering is separate from what is called the "availability window" in DASH.  Conceptually, a segment is only "available" for a certain amount of time, after which the server may choose to delete that segment and you can no longer request it.  We don't play anything that is not "available".

So what you want to configure is the availability window, not the buffering settings.

In DASH, the manifest specifies how long the content is available using the `timeShiftBufferDepth` attribute in the XML.  Look for that in your manifest and see what it says.  If you configure the player with a larger availability window, streaming may _fail_ after you unpause, because the segment may have been deleted from the server after that.

You're welcome to try it, though, and see if it works for this particular content:

```sh
player.configure('manifest.availabilityWindowOverride', 5 * 60);  // 5 minutes
```

If you are the content owner, you should also be able to control this through the `timeShiftBufferDepth` attribute in the manifest.  You may be able to find documentation for your encoder/packager on how to configure this when generating a live stream.
