### ISSUE TITLE
HLS http stream, captions aren't showing.

### ISSUE THREAD

**Issue by interlark** [google/shaka-player#2689]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** yes

**What version of Shaka Player are you using?** 3.0.1

**Please ask your question**
I'm trying to play [demo hls stream](https://storage.googleapis.com/shaka-demo-assets/apple-advanced-stream-ts/master.m3u8) but I can't see captions. Also I tried to play other multi-captions hls streams but all I see is one entry named "Shaka Player TextTrack" which's not working - subtitles aren't not coming. 
Maybe I do something wrong?

https://codepen.io/interlark/pen/pogrXjx
![image](https://user-images.githubusercontent.com/20641837/85944240-b5fbff00-b94e-11ea-8c20-9e62f936f77d.png)

**Comment by interlark** [comment]
I think the only way to control subtitles is shaka's API, html 5 controls useless here.

**Comment by michellezhuogg** [comment]
Hello @interlark , thank you for reaching out! It's a bug and we'll fix it.
To unblock you now, if you load [Shaka UI library](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html), you'll see a control panel with captions display button, and captions will be displayed.

Reproduce steps:
https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;alwaysStreamText=true;uilang=en;asset=https://storage.googleapis.com/shaka-demo-assets/apple-advanced-stream-ts/master.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled;nativecontrols
1. On nightly build page, disable Shaka Control.
2. Load the sample manifest
3. Captions button should be in the control panel, but it's not always shown.
4. Captions should be displayed. 
    By setting the text visibility to true, the captions can be displayed.

**Comment by TheModMaker** [comment]
We only support playing captions through our API.  You can't switch text tracks through HTML tracks.  This is because we can't control which track is selected or when they are changed, so we don't know when to stream the tracks.  Using our API allows us to only download the track that is being played.

Using the native controls is not really supported.  This is especially true for live streams and for text tracks.  You can use our UI or create your own based on our API.

@michellezhuogg, if you change the `streaming.alwaysStreamText` config to `true`, it should play.  Since we don't know when you enable the text tracks, we don't know when to start streaming the track.  Changing this config makes us always download the captions.

**Comment by joeyparrish** [comment]
I've confirmed that adding `player.configure('streaming.alwaysStreamText', true);` to the codepen linked above allows subs to be shown with native controls.  This is working as intended.

The reason you need this configuration is that we normally only stream text that is being shown.  If captions are off, we don't waste the bandwidth.  This was a feature requested specifically by the community.

But with native video controls, we don't know when you've switched them on.  There's no event for this in HTML5 video.  So the only way to get us to stream text without using our API to turn it on is to use the `streaming.alwaysStreamText` flag.

Does this help?

**Comment by interlark** [comment]
Yes, that helps, thank you, I think the issue could be closed.
