### ISSUE TITLE
play abnormally when change the source stream‘s resolution

### ISSUE THREAD

**Issue by FeiCao** [google/shaka-player#271]
Hi, I play the steam with 1280x800,  when I change the resolution to 320x200, player play abnormally, something like mosaic. I try to use another shaka-player to play the changed stream directly, it play well with the resolution 320x200

In this case, may I refresh the video tag or clear the buffer? thank you!

**Comment by tdrews** [comment]
This seems like a decoder issue. What browser/browser-version are you using? What platform are you on?

Also, in your MPD file, is the initialization segment for 1280x800 different from the one for 320x200?

**Comment by FeiCao** [comment]
browser: Google Chrome 41.0.2272.118
platform:windows 7 Professional Edition  Service Pack 1

I have changed the initialization segment for different resolution, but I found that  shaka-player did not read new initialization segment anymore. 

there is no update for segment's resolution information(https://github.com/google/shaka-player/blob/c45a3c273f8b285c07e095da1de8e55adbb3b181/lib/media/manifest_updater.js#L339).

**Comment by tdrews** [comment]
The Player doesn't actually feed any resolution information into the browser: the browser's decoder figures it out from the segments themselves. The code you linked to has to do with changing initialization segments between manifest updates for live streams; I don't think it's relevant to the issue.

I believe one of two things is occurring:
  1. The initialization segments in the manifest are not correct. There should be a unique initialization segment for each Representation.
  2. There is an issue with the browser's decoder and/or the content.

I'd like to rule out 1 first. Can you share your MPD file? If not, can you confirm if your MPD file uses `<SegmentBase>`, `<SegmentList>`, `<SegmentTemplate>`, or `<SegmentTemplate>` together with `<SegmentTimeline>`?

**Comment by FeiCao** [comment]
[mpd.zip](https://github.com/google/shaka-player/files/101732/mpd.zip)
There are two MPD files, "live-a.mpd" is before change resolution, "live-b.mpd" is after.

**Comment by tdrews** [comment]
Both of these MPDs have only one Representation. What does the original MPD look like that has more than one Representation?

**Comment by FeiCao** [comment]
I update the id=0 Representation directly, is there something wrong with it ?

**Comment by joeyparrish** [comment]
@FeiCao I think we misunderstood your original question.  Let me see if I am getting it now.

You have a live stream with one Representation, and you want to change the resolution mid-stream by modifying the manifest.  Is that correct?

**Comment by FeiCao** [comment]
yes, you are right!

**Comment by joeyparrish** [comment]
That is not supported by DASH as far as I can tell, and it's definitely not supported by Shaka.

Shaka only fetches the init segment when it changes Representations, not when it updates a live manifest.  AFAIK, no player would reload the init segment, as it is assumed static once created.  The init segment sets up the decoder, and for hardware decoders in particular, feeding low-res media segments after a high-res init segment may result in a tiling effect.

If you *must* modify the manifest in this incompatible way, you will have to get the Player to fetch a new init segment.  Options for this include:

1. Reload the video source (player.load()) to cause the entire pipeline to be recreated.  (This is hacky.)
2. Replace the old Representation with a new one (different ID) so that the Player knows they are different.  (This is not well-tested, and we have not seen examples of encoders which do this.)

However, neither of these is going to be a great option.  What are you trying to accomplish by modifying the manifest in this way?  Perhaps we can help you find a better way to do it.

**Comment by FeiCao** [comment]
Thank you very much, I just want to support all kinds of Resolutions in living streams, but the streams have different Resolution, For example, stream one has 1280x800 and 320x200, stream two has 1920x1080 and 1280x720. I can not enumerate all Resolutions in Representations.
 First, I modify the init segment and MPD to update the video's Resolution. And Second, I want to modify the Shaka that fetches the init segment at regular time and updates the decoder's info. Thus I may solve this problem. 
This is my idea, I am not sure that decoder can decode correctly, please give me some advices.

**Comment by joeyparrish** [comment]
Well, just changing the Representations and init segments out from under the Player is not in keeping with the DASH spec.  I think the best way to express what you are doing in DASH is to put a duration on the Period and start a new Period when the resolutions change.

Shaka will support multi-Period content starting with v2.0.

**Comment by FeiCao** [comment]
I changed MPD file and add a new Representation when change the Resolutions, but the player just request the MPD file, [live.zip](https://github.com/google/shaka-player/files/132141/live.zip) please help me for check the MPD file, thank you

**Comment by joeyparrish** [comment]
@FeiCao, what you're doing is not compatible with either DASH or MSE.  There are two big problems with what you are doing.

1. Initialization segments contain information such as resolution.  The init segment is used to set up the browser's decoder.  If you just change the source without a matching init segment, the browser will not be able to display the new content correctly.  This is fundamental to MSE in a browser.

2. If you are changing source material and output resolution, and you only have one resolution available at a time, you need to express this correctly in a way that a DASH client understands.  Changing the existing Representation is not correct.  Adding a new Representation is not correct.  There are two ways to handle this correctly as far as I can tell:
 * Add a new Period to contain the new material.  (Multi-period content is supported starting with Shaka v2.)  The Representations do not have to match across Periods.
 * -OR- Run your sources through an encoder first so that the output stream and manifest does not need to change at all.

That's the best advice I can offer you.  If you need help with Shaka specifically, please don't hesitate to ask.
