### ISSUE TITLE
How to getStats() using FairPlay on Safari

### ISSUE THREAD

**Issue by hooili** [google/shaka-player#2727]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
version: 3

**Please ask your question**
Hi, may i know how to get statistics for nerds using FairPlay on Safari as we know that we can use getStats() to get statistics on Chrome. Please advise. Thank you.

**Comment by michellezhuogg** [comment]
Hello,

If you're playing HLS content on Safari, we default to using native src= playback. When doing this, we don't have much info since the browser handles playback. You can use MSE playback on Safari by setting the configuration 'streaming.useNativeHlsOnSafari' to false, but you can't do this for FairPlay content.
