### ISSUE TITLE
Audio/Video sync issues with Multi-Period DASH stream

### ISSUE THREAD

**Issue by rohitsw-g** [google/shaka-player#2736]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.1 uncompiled

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Using Demo App

**Are you using the demo app or your own custom app?**
Demo App

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome, OSX

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Manifest with ads: https://dai.google.com/linear/dash/event/FDWzsDMPTgenPVLrU8sRJQ/manifest.mpd

**What did you do?**
The base stream is looped content from AWS Elemental encoder. The manifest contains ads and content embedded in different MPD periods. 

1. Start playback, verify that audio and video are in sync.
2. Leave the stream running for 30 mins+
3. Check the audio and video and you can see a noticeable sync issue between the audio and video. 

**What did you expect to happen?**

A/V should be in sync for the duration of the stream

**What actually happened?**

Video starts lagging behind the audio. The sync is noticeably bad after 30 mins, but it does start happening after a few period changes once the content starts playing.

**Comment by TheModMaker** [comment]
If this is caused by prolonged playback and not a specific point in the live stream, then this is an issue with the content or the browser.  We don't control A/V sync, we just append the media to the browser and it handles playback.  What may be happening is your media content doesn't include enough media samples or contains gaps and the browser is just playing through the audio.  Something similar happened in #707.

**Comment by theodab** [comment]
I tried to run your content in the DASH.js reference player, to see if the problem also occurred there. However, that player freezes on most period transitions in your content, so it doesn't play long enough to accumulate any time difference.

**Comment by ismena** [comment]
I haven't seen the exact repro, but after running the stream for a while I see the same variant-multiplying pattern as in #2716  
I suspect that we might be getting overwhelmed with computing for them and video processing may be suffering as a result.
We should update this once #2716 is resolved and ask the reporter to check if it's still an issue. 

@rohitsw-g Please note that this content also duplicates every audio stream and also some video streams, which is a pattern I saw several times before with IMA's DASH live streams. When it's convenient, let's talk about the ways this type of content gets packaged and see if there might be a way to do it that won't result in duplicating streams. If this can be done, your DASH live content will be better set up to be played on any player.

**Comment by ismena** [comment]
@rohitsw-g 
I have confirmed that the fix for #2716 also applies to this issue.
The fix will be included in our next release. Once the release is out, let's go through this again and make sure that it doesn't repro on your side as well.

I will update the bug once the new release is ready later this week.
