### ISSUE TITLE
Cosed Captions out of screen

### ISSUE THREAD

**Issue by accedosupport** [google/shaka-player#2742]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.12

**Can you reproduce the issue with our latest release version?**
on latest Chromecast Firmware

**Can you reproduce the issue with the latest code from `master`?**
on latest Chromecast Firmware

**Are you using the demo app or your own custom app?**
Chromecast built-in Shaka Player

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
latest Chromecast version 1.42.183786

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
latest Chromecast version 1.42.183786

**What are the manifest and license server URIs?**
Video Source: https://players.brightcove.net/4649357664001/default_default/index.html?videoId=5316955436001
Captions: http://streamtvago.akamaized.net/media/v1/text/vtt/clear/5481942443001/826317d1-0b50-4bfc-bd0f-2341f33158d3/48480786-1719-47ea-8755-24a65b19aaca/text.vtt?akamai_token=exp=1596815185~acl=/media/v1/text/vtt/clear/5481942443001/826317d1-0b50-4bfc-bd0f-2341f33158d3/48480786-1719-47ea-8755-24a65b19aaca/text.vtt*~hmac=88242517fc89253ec0a35e1dcc669966745a0841131b66370dfc0f3afcd9fbb9

**What did you do?**

Start playback enable ClosedCaptions

**What did you expect to happen?**
Captions should be aligned according vtt file and inside screen

**What actually happened?**
Closed Captions(valid webvtt files with UTF-8 encoding) are cut or outside the screen
- Incomplete text on VTT file at time 00:19.786  shows only "-<i> MasterChef</i> m'" 
![image](https://user-images.githubusercontent.com/10600797/87999765-df312a80-cac9-11ea-85ba-6bfbb884d1eb.png)

- Text outside the screen at 07:49.636 shows only (olossales. J') this one seems to have both issues, sentence not complete and also caption is placed outside the screen
![image](https://user-images.githubusercontent.com/10600797/87999749-d2143b80-cac9-11ea-8b3a-ea9b304e2d2b.png)

**Comment by theodab** [comment]
I tried your captions file with the most recent version of Shaka Player, and the captions aren't being cut in the way that you show.

When you say "Chromecast built-in Shaka Player", are you referring to the Cast Application Framework? Because we are not responsible for maintaining that; the Cast team is. The CAF does not currently use the latest version of Shaka Player, I believe. You can [contact the Cast team](https://developers.google.com/cast/support) for support.

**Comment by accedosupport** [comment]
Thank you very much theodab, you know if this was a known bug on 2.5.12 or previous?

**Comment by theodab** [comment]
I can't think of any issue like this off the top of my head. Looking back a few versions in our history, it doesn't seem to be present in any of the last few v2.5 releases either.

I suppose it's also possible that this is a bug with their text displayer. They aren't using our builtin one, because that does not handle the italics tags you have in your captions.

**Comment by accedosupport** [comment]
thenk you @theodab , looks like if I remove the styling align, line, position and start variables captions are centered at the bottom and displayed correctly
