### ISSUE TITLE
Playback stops after setting BufferingGoal but no error throwed

### ISSUE THREAD

**Issue by iplus26** [google/shaka-player#2743]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
2.5.1 and 3.0.1

**Please ask your question**
I'm not quite sure it's a bug or not...

I'm using shaka-player with widevine, DASH and Chrome on macOS. After I set `BufferingGoal` to 120 (2 minutes), or 5 minutes, video playback sometimes stops without errors. 

For example, duration of video is 39 minutes 18 seconds, playback may stop at 6:42 or 8:18 (random time). When it stopped at 6:42, the future two minutes content was buffered (I checked `Content-Range` headers of network requests and did the calculation) but not played, playback just freezed.

The weird thing is no error was thrown at console or shaka error event. I also tried the uncompiled version and set log level to V1 but not luck.

Could you help me or give some advice to debug? Is it could be a memory issue?

**Comment by iplus26** [comment]
Btw, when it happens, no event (`waiting`, `suspend`, etc) is triggered by native video element either. `timeupdate` event stops.

**Comment by ismena** [comment]
Hi @iplus26 does this happen with your custom content or it is reproducable with one of our streams?
If it's your content, please send the manifest link/drm info at shaka-player-issues@google.com (or post here, if that's ok) so we could take a look.
Thanks!

**Comment by iplus26** [comment]
@ismena email sent! thanks for reply

**Comment by NoChance777** [comment]
Same here! If I set network speed to "Slow 3G" for example,  I've never got a "waiting" event from video element. Is there another way for detecting stalling?

**Comment by TheModMaker** [comment]
Sorry for the delays.  Unfortunately without a playable manifest URL, we can't be of much help since we cannot reproduce ourselves.  You could also post logs with a log-level of Debug or V1 and that could help.  Also, you should listen for the `buffering` event from the player to see when we enter a buffering state.  We don't cause a `waiting` event since we stop before the end of the buffer.  You can also check the currently buffered ranges using `video.buffered` or `player.getBufferedInfo()`.  It's possible video has buffered but audio is not.

One likely cause is that your segments have incorrect timestamps.  So when we append a segment, it appears at the incorrect time in the video timeline and we can't move forward since we have nothing buffered.  But without something to play ourselves, we can't diagnose that.

Also, does the problem go away if not setting the `bufferingGoal`?  Does the video play to the end then?  When the video stops, is it at a consistent time?  Does the problem change if you disable ABR?

**Comment by iplus26** [comment]
Thank you for replying. I understand the difficulty of diagnose without a reproduce case, while I cannot share a manifest url with you since it's behind our private business logic. Therefore, I shall close this issue before I can have more information to share.
