### ISSUE TITLE
seekbar and time/duration is not showing in dvr LIVE stream.

### ISSUE THREAD

**Issue by unnatimane** [google/shaka-player#2753]
I have added 'time_and_duration' in control element and by default seekbar is showing for recorded stream.

But for **live dvr enabled stream**, it's showing LIVE icon instead of time and seekbar is missing.

Can we seek in live as same as recorded??

**Comment by michellezhuogg** [comment]
Hello,

Are you playing with HLS contents?
For HLS, the availability window defaults to the presentation delay by design, and makes the live stream unseekable. This is consistent with Apple's HLS implementation.
To make it seekable, you can config 'manifest.availabilityWindowOverride' to a large number.
