### ISSUE TITLE
Text segment requests continue after cancelation

### ISSUE THREAD

**Issue by interlark** [google/shaka-player#2764]
On latest ShakaPlayer I've met one bug situation.
I have 2 text tracks and ```streaming.bufferingGoal: 60 * 3```.
Once I paused my video and switched from one text track to another and while ShakaPlayer had been buffering next track I toggled text tracks visibility: https://github.com/google/shaka-player/blob/9456fd1da85c10ed09f8bdaa50c3e297bf3562e2/lib/player.js#L3507 which called https://github.com/google/shaka-player/blob/a534dca88351466164b64389530ab53dcc6ffb39/lib/media/streaming_engine.js#L250 
which called https://github.com/google/shaka-player/blob/a534dca88351466164b64389530ab53dcc6ffb39/lib/media/streaming_engine.js#L256

And this thing actually hadn't get all the requests stopped, it quickly stopped only one requests while there was many of them.
![image](https://user-images.githubusercontent.com/20641837/88949578-de0fb280-d2ac-11ea-8f47-9808152056bc.png)

When I switched text visibility back, it started to download double-chunks.
![image](https://user-images.githubusercontent.com/20641837/88949857-4199e000-d2ad-11ea-81d7-27eb54b31551.png)

When I switched to old text track Shaka Player had been downloading 2 text tracks at the same time.
![image](https://user-images.githubusercontent.com/20641837/88950274-d6044280-d2ad-11ea-91f0-4b309c91d2d3.png)

Somehow ```setTextTrackVisibility(false)``` broke Streaming Engine while it was in text-buffering state.
You can reproduce this issue making ```streaming.bufferingGoal``` bigger or your internet connection slower.

**Comment by joeyparrish** [comment]
Thank you for filing this issue, but we will need some specific information in order to address it.  This is why we use issue templates for bugs, feature requests, etc:
 - https://github.com/google/shaka-player/issues/new/choose
 - https://github.com/google/shaka-player/issues/new?assignees=&labels=&template=bug_report.md&title=

Here's the bug template, for your convenience.  Comments have been converted to italics so you can see them in this post:

-----

_NOTE: If you ignore this template, we will send it again and ask you to fill it out anyway._

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**


**What version of Shaka Player are you using?**


**Can you reproduce the issue with our latest release version?**


**Can you reproduce the issue with the latest code from `master`?**


**Are you using the demo app or your own custom app?**


**If custom app, can you reproduce the issue using our demo app?**


**What browser and OS are you using?**


**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**


**What are the manifest and license server URIs?**
_NOTE:
  You can send the URIs to <shaka-player-issues@google.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.  You can copy the URI of the demo app to send us the
  exact asset, licence server, and settings you have selected there._


**What did you do?**
_Steps to reproduce the bug_


**What did you expect to happen?**


**What actually happened?**
_A clear and concise description of what the bug is_
_If applicable, you may add screenshots to help explain your problem._

**Comment by interlark** [comment]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** ```True```


**What version of Shaka Player are you using?** ```v3.1.0-pre \ v3.0.2```


**Can you reproduce the issue with our latest release version?** ```Yes```


**Can you reproduce the issue with the latest code from `master`?** ```Yes```


**Are you using the demo app or your own custom app?** ```shaka player + any hls stream with 2 vtt text tracks```


**If custom app, can you reproduce the issue using our demo app?** ```demo app have too low streaming.bufferingGoal, I dont think demo app can show the bug```


**What browser and OS are you using?**  ```Chrome and FireFox```


**For embedded devices (smart TVs, etc.), what model and firmware version are you using?** ```None```

**Comment by joeyparrish** [comment]
> demo app have too low streaming.bufferingGoal, I dont think demo app can show the bug

Can you please try again with the demo?  This could be a useful data point.  You can configure the buffering goal in the demo app by clicking the menu in the top-left corner, then expanding the "Streaming" section of the config.  There you will find "Buffering Goal".  Just set that value before you click the "Load" button to load the content.

Thanks!

**Comment by interlark** [comment]
Alright, I recorded this issue on [demo](https://imgur.com/1W4PY8L).
Here's the steps you can see on this screencast.
1) I increased ```streaming.bufferingGoal``` to ```600``` 
2) Seeked to the middle of the stream and waited until it buffer all .ts chunks.
3) I slowed down internet connection.
4) I turned on captions and turned them off.
These steps brought me to the bug. After them you will be fetching *.webvtt chunks with turned off captions.

PS.
On this [demo](https://imgur.com/tyrU6iU) I switch captions back and get double fetching *.webvtt chunks.

**Comment by joeyparrish** [comment]
Thank you!

**Comment by interlark** [comment]
@joeyparrish, Also here's quick [fix](https://pastebin.com/HhGHmf1E) to walkaround this issue for your last [commit](https://github.com/google/shaka-player/commit/6c85c8cbfc1df2a2c8a34ff8b548b2fcf5ff7dea) if you like
