### ISSUE TITLE
How to extend default UI configuration and extend `shaka.ui.SeekBar` element for custom purpose?

### ISSUE THREAD

**Issue by alexkonst** [google/shaka-player#2769]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest (master)

**Please ask your question**
Hello.

I'd like to customize the player by adding a table of contents: a new button on control panel and overflow menu with a list of chapters ([here](https://prnt.sc/tuhriz) and [here](https://prnt.sc/tuhqwm) is what I'm after).

- First problem I've got into is passing some configuration parameters to my element. I tried to extend the default configuration object, but I've got an error `Invalid config, unrecognized key .chapters`. How can I pass configuration to my extension?
- Second, I'd like to show custom marks on the `SeekBar`, but I don't see how it may be done. Is it possible to add custom code, or markup, or approach it in any other way?

Any advice would be helpful. Thank you.

**Comment by ismena** [comment]
Hi @alexkonst 
Let me make sure - you have created a custom UI element for your chapters menu (looks very cool btw :)) like we mention in the [tutorial](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html) and are trying to add it to the UI config?

For the seekbar marks, there's no official way to do it, but I can suggest a hack, if you're interested :blush:
We have a `div` with a `class="shaka-ad-markers"` directly overlaying the seek bar that we add special marks to for content with ads. You can see how we do it [here](https://github.com/google/shaka-player/blob/606457488f77e9cf5cac2c82e94bb4ce35d50e2a/ui/seek_bar.js#L245).
(Basically, you figure out where on the timeline you want the marks and color the appropriate points of the element).

If you're not planning on serving content with ads, you can use this element to add your marks to it.
This is a bit more on the advanced user side, but since there's currently no easy way to accomplish this, I thought I'd at least mention it give you the option.

**Comment by alexkonst** [comment]
Yes, we defined element like this:
```js
shaka.ui.ChaptersMenu = class extends shaka.ui.Element {...};

shaka.ui.ChaptersMenu.Factory = class {
  create(rootElement, controls) {
    return new shaka.ui.ChaptersMenu(rootElement, controls);
  }
};

shaka.ui.Controls.registerElement('chapters_menu', new shaka.ui.ChaptersMenu.Factory());
```

Then added `'chapters_menu'` to UI config.
```js
// videoElement and playerElement defined earlier
const player = new shaka.Player(videoElement)
const ui = new shaka.ui.Overlay(player, playerElement, videoElement)

const config = {
  controlPanelElements: [
    'play_pause',
    'time_and_duration',
    'spacer',
    'mute',
    'volume',
    'fullscreen',
    'chapters_menu', // <-- our custom element
    'overflow_menu',
  ],
  overflowMenuButtons: ['quality', 'playback_rate'],
}

ui.configure(config)
```

And it works fine (there is button on control panel, click on it opens overflow menu, but without content).
The problem is i need to pass list of chapters to `ChaptersMenu` element instance. Tried through ui config, but get error `Invalid config, unrecognized key .chapters`. Example of config.

```js
const config = {
  chapters: [
    { time: 0, title: 'Intro' },
    { time: 5, title: 'Chapter 1' },
    { time: 10, title: 'Chapter 2' },
    { time: 15, title: 'Chapter 3' },
    { time: 20, title: 'Outro' },
  ],
  controlPanelElements: [
    'play_pause',
    'time_and_duration',
    'spacer',
    'mute',
    'volume',
    'fullscreen',
    'chapters_menu',
    'overflow_menu',
  ],
  overflowMenuButtons: ['quality', 'playback_rate'],
}

ui.configure(config)
```

Maybe somehow i can get link to instance of `ChaptersMenu` from `ui`? For example, i can add setter method for chapters..

> For the seekbar marks, there's no official way to do it, but I can suggest a hack, if you're interested 😊

Thanks for advice, i will try to find solution in this way.

**Comment by joeyparrish** [comment]
I see the issue with ChaptersMenu.  You can't pass arbitrary configs through Shaka Player's config system, because it only merges known keys and issues warnings for unknown keys.  Perhaps this is something we could open up to extensions somehow in the future.  If that's useful, please file a new feature request and we'll keep it in mind.  But for now, this is working as intended.

One way you can handle the chapter config is through the factory, which will let you store whatever you want.  For example:

```js
shaka.ui.ChaptersMenu = class extends shaka.ui.Element {
  constructor(rootElement, controls, chapters) {
    super(rootElement, controls);

    this.chapters_ = chapters;
  }
};

shaka.ui.ChaptersMenu.Factory = class {
  constructor(chapters) {
    this.chapters_ = chapters;
  }

  create(rootElement, controls) {
    return new shaka.ui.ChaptersMenu(rootElement, controls, this.chapters_);
  }
};

shaka.ui.Controls.registerElement('chapters_menu', new shaka.ui.ChaptersMenu.Factory(chapters));
```

Or even more dynamically through a callback:

```js
shaka.ui.ChaptersMenu = class extends shaka.ui.Element {
  constructor(rootElement, controls, getChapters) {
    super(rootElement, controls);

    this.getChapters_ = getChapters;
  }

  someMethod() {
    const currentChapters = this.getChapters_();
    // ...
  }
};

shaka.ui.ChaptersMenu.Factory = class {
  constructor(getChapters) {
    this.getChapters_ = getChapters;
  }

  create(rootElement, controls) {
    return new shaka.ui.ChaptersMenu(rootElement, controls, this.getChapters_);
  }
};

shaka.ui.Controls.registerElement(
    'chapters_menu',
    new shaka.ui.ChaptersMenu.Factory(() => {
      // Calculate and return chapter metadata here
    }));
```

There are many ways you could pass metadata or callbacks through the factory into your custom element.  These are just two ideas that came to mind.  You can judge whatever is best for your application architecture.

Does this help?

**Comment by alexkonst** [comment]
@joeyparrish yes, that's what I was looking for.
Thank you for your help.

**Comment by joeyparrish** [comment]
Awesome!  Does this answer all of your questions?  Or should we leave this open regarding putting markers on the seek bar?

**Comment by alexkonst** [comment]
I think this information will be enough. We can close issue.
Thank you.
