### ISSUE TITLE
Retreiving master HLS playlsit/manifest from the media playlists

### ISSUE THREAD

**Issue by ThomasSkinner** [google/shaka-player#2774]
I'm looking for a way to get a master HLS playlist from a media playlist, so shaka can play the media. 

This could be useful with streamlink. You can get the media playlists for twitch, but you can't get a master playlist.
 
Is there a way to convert to the media playlist to the master playlist? I think I would need codec information for that.

**Comment by joeyparrish** [comment]
> When i use the options --stream-url and --json

I don't recognize those option names, and Shaka Player doesn't have command-line options.  What tool are you referring to with those?

**Comment by joeyparrish** [comment]
I am not a lawyer, but you may also want to review the [Twitch Terms of Service](https://www.twitch.tv/p/legal/terms-of-service/), where section [9 ("Prohibited Conduct")](https://www.twitch.tv/p/legal/terms-of-service/#9-prohibited-conduct) currently states:

> You agree that you will comply with these Terms of Service and Twitch’s Community Guidelines and will not:
> ...
> xi. **access** any website, server, software application, or other computer resource owned, used, and/or licensed by Twitch, including but not limited to the Twitch Services, **by means of any robot, spider, scraper, crawler, or other automated means** for any purpose, **or bypass any measures Twitch may use to prevent or restrict access** to any website, server, software application, or other computer resource owned, used, and/or licensed by Twitch, including but not limited to the Twitch Services;
> ...

So I don't believe we can help you specifically with gaining access to Twitch content playlists through Shaka Player.  If you have more general questions about using HLS with Shaka Player, we would happy to answer those.

For example, you mention converting media playlist to master playlist.  You would indeed need codec information for this, ideally, though without that info, Shaka Player will make an assumption that the content is H.264 and AAC.

https://github.com/google/shaka-player/blob/3b63f19c41817ff92cfe80176a67f2f47254b827/lib/hls/hls_parser.js#L825-L830

We have had requests in the past to support media playlists directly (see #2300), but we do not support those at this time because media playlists lack much of the metadata necessary for MediaSource-based playback in the browser.

Does this help?

**Comment by ThomasSkinner** [comment]
Thanks for the info. Yes that helps. How could I get the codec information from just the media playlist manifests, or is this impossible?

**Comment by joeyparrish** [comment]
I don't believe there is any codec information in the media playlist.  Hypothetically, you could get it from the media itself if you download the init segment, but that's not trivial.  I expect that if you know in advance a little bit about the content your application uses, you could supply that information without deriving it from the media playlist.  Or you could get it out of band somehow.
