### ISSUE TITLE
 26/5000 does not play in chromecast

### ISSUE THREAD

**Issue by Richjard** [google/shaka-player#2780]
I am testing chromecast and when I press send it does not play the video that is in localhost, but it does play the video that is in the demo https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

**Comment by joeyparrish** [comment]
If your URL begins with "http://localhost", you should remember that "localhost" always refers to the machine making the request.  If you try to cast the video, the URL is transferred to the Chromecast exactly.  To the Chromecast, "localhost" means the Chromecast itself, which is not where your web server is.

If you try using your web server's hostname or IP for the video URL, that may solve the issue for you.

Does this help?

**Comment by Richjard** [comment]
I put my web server the host but it still does not reproduce me

**Comment by Richjard** [comment]
mi servidor web lo tengo en mi red  quizas sea eso el problema?

**Comment by Richjard** [comment]
I have my web server on my network, maybe that is the problem?

**Comment by joeyparrish** [comment]
If the server hosting your content is not accessible to a client device, then that device will be unable to play the content.  This includes the Chromecast.

**Comment by Richjard** [comment]
my web server is on apache

**Comment by joeyparrish** [comment]
It's not really a matter of what server software you're using.  If the actual device hosting the server must be accessible from the Chromecast.  If there is a firewall or NAT router between them, it will not work without additional configuration of your network.  Networking is a big topic, and setting up your local network, router, etc would be beyond the scope of the support we can offer you.

If your Chromecast and web server are on the same local network, and the device running the server has no firewall, it should work.  If it doesn't work with the hostname, please try using the IP address instead.  Chromecast devices use Google DNS instead of the local network DNS, so local network hostnames may not be resolvable by a Chromecast.

Does this help?
