### ISSUE TITLE
How can I check if my browser supports FairPlay?

### ISSUE THREAD

**Issue by qba86** [google/shaka-player#2786]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.14

**Please ask your question**
How can I check if my browser supports FairPlay? For Widevine I'm do something like this:

`

    // I check basic API
    if (!!window['MediaKeys'] &&
        !!window.navigator &&
        !!window.navigator.requestMediaKeySystemAccess &&
        !!window['MediaKeySystemAccess'] &&
        !!window['MediaKeySystemAccess'].prototype.getConfiguration
    ) {
        //  If APIs are present, I check if I get access to EME with basic parameters
        //  Additionally, we check if the promise lasts longer than 2 seconds. because the browser
        //  Samsung Browser and iOS Safari Browser hang in this place, which makes it impossible to jump
        //  to the native Promise catch
        return timeout(
            window.navigator.requestMediaKeySystemAccess(
                'com.widevine.alpha',
                [
                    {
                        videoCapabilities: [
                            { contentType: 'video/mp4; codecs="avc1.42E01E"' },
                            { contentType: 'video/webm; codecs="vp8"' }
                        ]
                    },
                ]
            ), 2000)
            .then(() => {
                return true;
            })
            .catch(() => {
                return false;
            });
    } else {
        return false;
    }
`

**Comment by theodab** [comment]
The same approach should work for FairPlay, I'd think. Just instead of putting the Widevine key system identifier (`com.widevine.alpha`) in, put in the one for FairPlay (`com.apple.fps`). There's also `com.apple.fps.1_0`, `com.apple.fps.2_0`, and `com.apple.fps.3_0`, which are different CDM versions I think, though I don't know offhand what the differences are.

Incidentally, Shaka Player has a method for probing support for DRM systems, manifest types, etc: `shaka.Player.probeSupport`
```js
shaka.polyfill.installAll();
if (shaka.Player.isBrowserSupported()) {
  shaka.Player.probeSupport().then((support) => {
    console.log('DRM key systems supported:', support.drm);
  });
}
```
You can also see the output of that function [in the demo](https://shaka-player-demo.appspot.com/support.html), if you follow the "Browser Support Test" link.

**Comment by qba86** [comment]
Thx, works perfectly :)
