### ISSUE TITLE
Error 6012 when attempting to configure playready

### ISSUE THREAD

**Issue by ThomasSkinner** [google/shaka-player#2791]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
latest
**Please ask your question**

I'm trying to configure shaka to work with a private license and content server that is suppose to support playready.

Here is the beginning part of the manifest file
```
<MPD xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" minBufferTime="PT2S" type="static" mediaPresentationDuration="PT120.066666S" xmlns:cenc="urn:mpeg:cenc:2013" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011">
    <Period id="0">
        <AdaptationSet id="0" contentType="audio" lang="eng" subsegmentAlignment="true">
            <ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="19b0d4db-ee8a-49a5-9abd-1eaffaafc5d8"/>
            <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95">
                <cenc:pssh>AAACOnBzc2gBAAAAmgTweZhAQoarkuZb4IhflQAAAAEZsNTb7opJpZq9Hq/6r8XYAAACBgYCAAABAAEA/AE8AFcAUgBNAEgARQBBAEQARQBSACAAeABtAGwAbgBzAD0AIgBoAHQAdABwADoALwAvAHMAYwBoAGUAbQBhAHMALgBtAGkAYwByAG8AcwBvAGYAdAAuAGMAbwBtAC8ARABSAE0ALwAyADAAMAA3AC8AMAAzAC8AUABsAGEAeQBSAGUAYQBkAHkASABlAGEAZABlAHIAIgAgAHYAZQByAHMAaQBvAG4APQAiADQALgAwAC4AMAAuADAAIgA+ADwARABBAFQAQQA+ADwAUABSAE8AVABFAEMAVABJAE4ARgBPAD4APABLAEUAWQBMAEUATgA+ADEANgA8AC8ASwBFAFkATABFAE4APgA8AEEATABHAEkARAA+AEEARQBTAEMAVABSADwALwBBAEwARwBJAEQAPgA8AC8AUABSAE8AVABFAEMAVABJAE4ARgBPAD4APABLAEkARAA+ADIAOQBTAHcARwBZAHIAdQBwAFUAbQBhAHYAUgA2AHYAKwBxAC8ARgAyAEEAPQA9ADwALwBLAEkARAA+ADwAQwBIAEUAQwBLAFMAVQBNAD4ARwBsAE8AUwA1AGkARABhAHcARQBRAD0APAAvAEMASABFAEMASwBTAFUATQA+ADwALwBEAEEAVABBAD4APAAvAFcAUgBNAEgARQBBAEQARQBSAD4A</cenc:pssh>
```

The error object has a error.data attribute indicating:
```org.w3.clearkey```

I configure the shaka player like this before I load the dash manifest

```

      player.configure({
        drm: {
          servers: {
            'com.microsoft.playready': res.drm.playready.url //license server url
          }
        }
      });
      player.getNetworkingEngine().registerRequestFilter(function(type, request) {
        if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
          for (const [key, value] of Object.entries(res.drm.playready.keyRequestProps)) {
            // some headers needed for license server request
            request.headers[key] = value
          }
        }
      });

```

What am I missing? Does this dash file just not support playready like it's suppose to?

**Comment by joeyparrish** [comment]
The `ContentProtection` element in your manifest has the UUID for PlayReady (`9a04f079-9840-4286-ab92-e65be0885f95`) so that seems to be in order.  I don't know why you would see a reference to ClearKey in the error, though.

Do you have any other configuration not seen here, such as `drm.clearKeys`?  Configuration carries over between calls to `player.load()`, and you can reset the configuration to defaults with `player.resetConfiguration()`.  You can also reset a piece of the configuration by using an explicit `undefined`, such as `player.configure('drm.clearKeys', undefined)`.

Does any of this help?  If not, we may need you to fill out the complete bug report template and provide us with a content URL and a way to reproduce the issue.
