### ISSUE TITLE
Make UITextDisplayer CSS-independent

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2817]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**Is your feature request related to a problem? Please describe.**

At this time, the default captions positioning is done using css. This should be done in the UITextDisplayer class
https://github.com/google/shaka-player/blob/146eeef1e5b9ae1a5c715dc85493468c6e5b82bf/ui/less/containers.less#L218-L224

The problem is that the CSS is set on the UI part when UITextDisplayer does not depend on the UI part.

**Describe the solution you'd like**

Add the default styles here:
https://github.com/google/shaka-player/blob/146eeef1e5b9ae1a5c715dc85493468c6e5b82bf/lib/text/ui_text_displayer.js#L48

**Describe alternatives you've considered**

Leave current behavior

**Comment by joeyparrish** [comment]
Can you please clarify your setup?

Do you want to use the UITextDisplayer without the full Shaka Player UI?  Or use the Shaka Player UI, but not the CSS we provide?  Or is it something else and I've completely misunderstood?

**Comment by avelad** [comment]
@joeyparrish , I want to use UITextDisplayer without the full Shaka Player UI.

**Comment by joeyparrish** [comment]
I have been uncomfortable with having some styles in CSS and some in JS.  The styles we apply in JS can't be overridden by an application's own CSS, so I have also been hesitant to move anything from CSS to JS.

I can see the argument that we should move the layout styles to JS, though, because the text displayer can't correctly lay out text without them.  Would you agree that the div styles should stay in CSS, though?

https://github.com/google/shaka-player/blob/146eeef1e5b9ae1a5c715dc85493468c6e5b82bf/ui/less/containers.less#L226-L232

In particular, I'm thinking about `font-size`, which is what is applied when generic VTT subtitles have no additional style info.  Applications might want to customize that to fit the layout/size of the application, whether or not they use our UI.  The same may be true of background and text color.

**Comment by avelad** [comment]
Yes, I totally agree I just want to move the following styles:
```
text-align: center;
display: flex; 
flex-direction: column; 
align-items: center; 
justify-content: flex-end; 
```

I'm going to do a PR with these changes.
