### ISSUE TITLE
Clarification of 3016 error, Buffers did not monotonically increase

### ISSUE THREAD

**Issue by hdodev** [google/shaka-player#2833]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, no corresponding errors with this 3016 root cause

**What version of Shaka Player are you using?**
2.5.10

**Please ask your question**

I try to understand this error that appears exclusively when running Shaka on Tizen TV:
onshakaError : {"severity":2,"category":3,"code":3016,"data":[3,null,": Buffers did not monotonically increase."]}

The conditions are:
- 3 streams in DASH manifest : 1) 1920x1080/6,4Mbps/50fps, 2) 1440x1080/4,5Mbps/25fps, 3) 1280x720/3Mbps/25fps.
- When the available bandwidth decrease quickly from 12 Mbps to 5 Mbps for example, Shaka selects the 720p profil and the error is triggered.
- When I suppress the 720p stream from available streams, the problem doesn't appear (but I often have buffering instead).

Can you please explain me what does mean exactly this error? Could it be something managable by Shaka by configuring differently "buffers" or could it be directly linked to the Tizen Tv capacities?

Thanks in advance for your help!

**Comment by TheModMaker** [comment]
3016 is [VIDEO_ERROR](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:3016), which is just a forwarded error from the browser.  That error string, is copied from what the browser gives us; so we don't have any control or knowledge of what this means.  Based on the message and your behavior, there are two possibilities:

First, your 720p stream has frames that are out of order.  If you play that stream by itself, does it work?

Secondly, the browser is choking when we switch streams because we are appending a segment that has some frames that are already buffered.  If your streams aren't aligned, we'll need to append a segment that overlaps some already buffered content.  We've seen other browsers have problems with this before.  So we highly suggest your streams be aligned.  This means that each segment covers the same time from each stream.  For example: each stream has segments 0-10, 10-20, etc.  If you have a stream with 0-8,8-18,18-28, you may have problems.

If you could send us some example content that reproduces this, we may be able to provide more info.  You can send it privately to <shaka-player-issues@google.com> if you want.

**Comment by hdodev** [comment]
Thanks for the answer.

The 720p stream alone works, and even some transitions are ok, so if your hypothesis is correct, that mean it's localized temporaly.
But when we configure all streams to be 50 fps, the problem disapears completely. So according to what you said, maybe a rounding timestamp problem...

I'll see if I can share a stream with you, but as the problem is random, and requires very bad access network conditions to be reproduced, I don't want you to waste your time.

**Comment by TheModMaker** [comment]
Were you able to get a sharable stream?  Is this still an issue for you?  You could also try manually switching streams with `player.selectVariantTrack`; the second argument is a boolean for whether to clear the buffer.  Passing `false` will simulate ABR by not clearing the buffer, but passing `true` will clear the buffer and maybe make the error go away.

**Comment by hdodev** [comment]
Hi @TheModMaker . We found a problem in our streams, the "tftd" value is not aligned between different profiles and so buffer recoveries appear. We are trying to correct it, but your note could be used as long as the problem exists, if in native ABR behaviour we can force the flush of the buffer, as you said when you make manually the selectvariantTrack(). Is it so configurable?

**Comment by TheModMaker** [comment]
Sorry for the delay.  I don't think it's a good idea to have a setting for that.  ABR is meant to be smooth, and clearing the buffer would guarantee the video stop (or at least stutter).  If you really need this, I think you could create a new AbrManager class and forward the call to our version and change the arguments.  The callback given to AbrManager allows clearing the buffer, so you could do it in your version.

Since this seems to be a stream or platform bug, I'm going to close.
