### ISSUE TITLE
Live: Init segments called at each manifest refresh when being at the closest possible of the edge

### ISSUE THREAD

**Issue by valotvince** [google/shaka-player#2856]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
v3.0.x

**Can you reproduce the issue with our latest release version?**
✅ 

**Can you reproduce the issue with the latest code from `master`?**
✅ 

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes, simply go to
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://livesim.dashif.org/livesim/segtimelinenr_1/utc_head/testpic_6s/Manifest.mpd;panel=ALL_CONTENT;panelData=LIVE;build=uncompiled

and see in the network that init segments are always called back even though we don't change of variant

**What browser and OS are you using?**
Mac, Windows, Chrome / Edge Chromium

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

See demo link above 🔝 

**What did you do?**

See demo link above 🔝 

**What did you expect to happen?**

Init segments should be fetched only when loading the variant for the first time, not each time the manifest refreshes.

ℹ️   Interesting fact: If you seek back into the live and far from the edge (like 1 minute), the bug doesn't appear anymore. If you seek back to the edge, the bug appears again

**Comment by joeyparrish** [comment]
My guess is that this is caused by a bug in the manifest parser.  StreamingEngine does not check the inner contents of InitSegmentReference to determine if two of them are equal.  Instead, does a simple `==` to check for the same object.  If the object changes, it assumes it's a new init segment.  In this scheme, it is the job of the manifest parser to keep track of InitSegmentReference objects and not to create new ones on manifest updates.

So we can either fix the DASH parser, or change the scheme and do a deep comparison of InitSegmentReferences.

This is all guess-work without having reproduced the issue, though.

**Comment by joeyparrish** [comment]
It appears that the DASH parser recreates InitSegmentReference objects and does not properly cache them.  This is the root of the issue.

Either we should fix the parser to cache them, or add an `equals()` method that can be used in place of the `==` operator in `StreamingEngine` to loosen the requirements on manifest parsers.
