### ISSUE TITLE
Are keyboard shortcuts available ?

### ISSUE THREAD

**Issue by Forium777** [google/shaka-player#2859]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Almost yes.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
Lastest release

**Please ask your question**
Hi,
I'm wondering if it is possible to use keyboard shortcuts by any way ? I tried to use well-known 'space' and 'F' shortcut to pause and fullscreen but player didn't react. Is it implemented ? If yes, how can I enable them ? If no, is it planned ?

Thanks!

**Comment by joeyparrish** [comment]
For keyboard accessibility reasons, you can use tab to navigate to individual UI controls and manipulate them with the keyboard.  For example, while the seek bar has focus, left and right arrows will seek.  (Caveat: I just discovered that our focus indicator in the UI is broken.  See #2863)

We don't have any global keyboard shortcuts, though, but you can easily add these to the window or document with your own app-level event listener.  For example:

```js
videoContainer = document.querySelector('.shaka-video-container');

document.addEventListener('keydown', (e) => {
  if (e.key == 'f') {
    videoContainer.requestFullscreen();
    e.preventDefault();
  } else if (e.key == ' ') {
    if (video.paused) {
      video.play();
    } else {
      video.pause();
    }
    e.preventDefault();
  }
});
```

We wouldn't do this by default, because a global listener would be a bad idea for applications with more than one instance of Shaka Player.

Does this help?

**Comment by Forium777** [comment]
It does, thanks!

For people who want basics keyboard controls :
```js
document.addEventListener('keydown', (e) => {
    const videoContainer = document.querySelector('video');
    let is_fullscreen = () => !!document.fullscreenElement
    let audio_vol = video.volume;
    if (e.key == 'f') {
        if (is_fullscreen()) {
            document.exitFullscreen();
        } else {
            videoContainer.requestFullscreen();
        }
        e.preventDefault();
    }
    else if (e.key == ' ') {
        if (video.paused) {
            video.play();
        } else {
            video.pause();
        }
        e.preventDefault();
    }
    else if (e.key == "ArrowUp") {
        e.preventDefault();
        if (audio_vol != 1) {
            try {
                video.volume = audio_vol + 0.05;
            }
            catch (err) {
                video.volume = 1;
            }
        }
    }
    else if (e.key == "ArrowDown") {
        e.preventDefault();
        if (audio_vol != 0) {
            try {
                video.volume = audio_vol - 0.05;
            }
            catch (err) {
                video.volume = 0;
            }
        }
    }
});
// Tested on Chrome 85 stable
```
