### ISSUE TITLE
Safari issues with non-0 CTS

### ISSUE THREAD

**Issue by barbibulle** [google/shaka-player#286]
When playing content where the CTS of the first frame of the first fragment is not 0, on Safari 9, the player gets "stuck".
It can be unstuck by fiddling with the seek bar (not a 100% guarantee, but by moving the seek bar a few times, the playback usually ends up working). Sometimes a seek back to 0 will show the little PacMan icon and stay there.
The same content works find in Chrome and Firefox.

It is definitely strange to have content for which the first frame CTS isn't 0, but I can't find a specific part of the spec that definitely forbids it.
So the question is: should this be supported by Shaka? Is this a bug in Safari? or is the content just non-compliant?

I've posted an example of such content here:
http://www.bok.net/tmp/dash/cts_offset/stream.mpd

**Comment by joeyparrish** [comment]
I'm not sure if this is valid content or not, but it's common enough that I feel we should find a simple solution.

The behavior for this kind of thing varies between browsers.  In Chrome, for example, gaps of less than 250ms do not seem to stall the media pipeline.  I'm not aware of any standard requirements around this, though.

If you are willing to continue hosting that stream for a while, we will take a look in the next few weeks and see if there's a simple way to deal with it across browsers.

**Comment by barbibulle** [comment]
Thanks. I'll leave the stream on the server for a while.

**Comment by joeyparrish** [comment]
Different browsers seem to treat the first video segment differently.  The test is to append the init segment and the first video segment to a SourceBuffer and then check SourceBuffer.buffered.start(0).  Here are the results:

| Safari 8 & 9 | Firefox 44 on Linux | Chrome 48 on Linux | IE11 & Edge13 on Win 10 |
| ----- | ----- | ----- | ----- |
| 83ms (CTS) | 83ms (CTS) | 0ms (DTS) | 0ms (DTS) |

I'm not sure which is implementations are correct in this, but it causes Shaka to behave differently since we use buffered.start(0) to calculate drift.  Ideally we could be resilient in all cases, but right now I think I need to do some digging into which (if any) is to-spec with MSE.

**Comment by jernoble** [comment]
It looks like the problem for Safari is rounding from a floating point value (0.083333) to a rational time value (2/24). Represented as a double, the seek time ends up as 0.083333333333333329, which is ever so slightly less than 2/24 (or, 0.08333333333333333).

So Safari thinks that the media has seeked into an unbuffered range, and fails to re-enqueue upcoming samples correctly.

**Comment by joeyparrish** [comment]
The latest Shaka v2 code in `master` does not error on this content.  The buffered range on Safari 9 starts at 83ms, but Safari refuses to jump the gap from 0.  Using Firefox on the same Mac, I also see that the buffered range starts at 83ms, but Firefox will automatically jump the gap from 0.

So I'm tempted to say that Shaka is doing everything it can now, and that the rest is a Safari issue.

Does anyone here know the right procedure to file bugs against Safari?  Googling ["safari bug report"](https://www.google.com/search?q=safari+bug+report) doesn't turn up an obviously correct result.  The closest seems to be ["Apple - Safari - Feedback"](http://www.apple.com/feedback/safari.html), but that is not so much a public bug report as a comments form.  *"please note that we cannot respond to the comments you submit."*

["Apple Bug Reporter"](https://bugreport.apple.com/problem/viewproblem) seems more appropriate, but if you search for "Safari" in the bug tracker, you get zero results.  Is that the wrong place?  Or are all the bug reports private?

**Comment by jernoble** [comment]
@joeyparrish Actually, it's either a bug in Safari, Chrome, & Firefox, or it's a bug in Edge, depending on the outcome of https://github.com/w3c/media-source/issues/54.

Edge is using the decode timestamp to fill their .buffered ranges, and the other browsers are using the presentation timestamp.

You can file a bug against Safari at http://bugreport.apple.com, or against WebKit at http://bugs.webkit.org/. But I would argue that in light of the likely result of the media-source issue above, Safari and WebKit are unlikely to change their behavior here.

**Comment by joeyparrish** [comment]
Yes, what I meant was that regardless of the outcome of w3c/media-source#54, Safari doesn't jump a tiny 83ms gap at the start like other browsers seem to do.

Firefox is using CTS and Chrome is using DTS, but both are willing to skip tiny gaps in the buffer during playback.  (Chrome doesn't do this for the content in question here, but I have seen it skip small gaps in other content.)

@barbibulle, I've mirror your content here for my bug report: https://storage.googleapis.com/shaka-demo-assets/_bugs/safari-non-zero-cts/stream.mpd

@jernoble, I've filed a bug against WebKit here: https://bugs.webkit.org/show_bug.cgi?id=156316

Thanks, everyone!

**Comment by KbdBrucd777** [comment]
yesir let me think before i drank.

**Comment by joeyparrish** [comment]
@KbdBrucd777 :beers:

**Comment by KbdBrucd777** [comment]
hold  im nee at this  very new

**Comment by KbdBrucd777** [comment]
this is how it went with my new computer day before yesterdat and the worthless punk im about to go find now got into my computer and all i have been trying to do is emaik a guy back for a job.  im 42, have a 1 month old baby and a pissed off wife cuz this pervert wants to watch me all day  2015-08-05.....  :SymSilentBootstrap : 0x0E44 : 0x0E48 :Information Command Line: "C:\Program Files (x86)\SymSilent\SymsilentBootrstrap.exe

**Comment by KbdBrucd777** [comment]
damn i screwed up  hold

**Comment by KbdBrucd777** [comment]
"C:\Users\Admin~1\AppData\Local\Temp\7zS46B00EEC\SymSilent"/install

**Comment by KbdBrucd777** [comment]
thats how theres 15 muthrf:!&;&!jn peioke connectee to my wifi my wife bought me while i was in the hospital recovering from a wreck that this scum caused by driving me insane  i just want to use a gotdamn computer to emailwhats required so I can take care of my family and maybe enjoy my kid for a day. BUt no, all my technology is Linux now and I didnf jnow anyrhing about Linux untl i went yo the compurer store last week. now im having to do this crap all day when I just want to get my life back  its sick and i hope whoever gets there thrills before I go rip a head or headss off and smear their flesh across concrete. they hacked ny 4th iphone making it dead rhe day afrer my wifes emergency C-section from our baby boy having to be pulled out 6 weeks early. the cause was the unbeklical cord wrapped around his head twice. im headed to wrap a cord around the peopke latched to my life this am. any help to put these bloodsucking maggots down woukd be greatky appreciated. its daily hell ive been having to fight just to use technology in the last 6 months.

**Comment by joeyparrish** [comment]
@KbdBrucd777, your comments are unrelated to this project.  I'm not sure why you are leaving them here.

I have locked this issue to prevent further comments and I am deleting the inappropriate comments you have left (strong language, violent threats, and the medical saga of a newborn).
