### ISSUE TITLE
Dash with multi period doesn't play and return error 4037

### ISSUE THREAD

**Issue by zhoresh** [google/shaka-player#2883]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.04

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
N/A

**Are you using the demo app or your own custom app?**
CBS Cast receiver app

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chromecast

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Chromecast 1.47

**What are the manifest and license server URIs?**

**What did you do?**
Play content with Ads

**What did you expect to happen?**
Content should be playing

**What actually happened?**
Nothing played. Shaka return error 4037

**Comment by TheModMaker** [comment]
Please provide a manifest URL.  You can send it privately to <shaka-player-issues@google.com> if you want.

**Comment by joeyparrish** [comment]
The manifest URL was sent privately.  @TheModMaker, can you please take a look today?

**Comment by TheModMaker** [comment]
The problem is that your content includes Periods that add streams with different codecs.  Most of the Periods have MP4 and AC3, but some also have EC3.  Since we don't support switching codecs, we try to create a single "path" through the Periods with the same codec.  Since we can't with EC3, we throw this error.

If you control the packager, you can remove the EC3 streams and it should work.  We could also ignore streams that have additional codecs or somehow handle this better.
