### ISSUE TITLE
Multi-Period: Get the correct variant / text streams for the current period

### ISSUE THREAD

**Issue by valotvince** [google/shaka-player#2887]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
✅ 

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
✅ 

**What version of Shaka Player are you using?**
v3.0.3

**Please ask your question**
How could we get the current variants / text streams for the playing period ? That would be helpful to prevent showing audio tracks / subtitles tracks which disappear from period to period, and that would be really helpful in case of a live start-over or time-shifting.

- P1
  - French Audio
  - English Audio

- P2
  - French Audio

... and English audio might appear back in another Period

**Comment by joeyparrish** [comment]
Let's expand your example slightly for the sake of discussion:

 - P1: French & English
 - P2: French
 - P3: French & English
  
In v2.5, we modeled DASH periods internally, and tracks were per-Period.  So if you transitioned from P1 to P2, the English audio track would disappear.

This caused issues, however.  For example, if the user selects English in P1, they would be forced into French at P2.  Then when they reach P3, should we play French or English?

Obviously, as a human reading this example, you would want English back.  However, it was difficult to know from the API what the user's intent was, and there are cases less obvious than language.  An app can select any track with `selectVariantTrack()`, and we don't know what attribute caused them to select that track.  So how can we maintain that user intent across periods?  In short, we can't.

So in v3.0+, we combine periods and create tracks that span DASH periods.  So the combined tracks from our example look like this in v3:

 - French: P1 French, P2 French, P3 French
 - English: P1 English, P2 French, P3 English

Because we've explicitly mapped tracks across periods in advance, there's no automatic track changes at period boundaries.  A app's or user's selection is always preserved, no matter what track attributes were used to make the selection.

Does this help?

**Comment by valotvince** [comment]
@joeyparrish Thank you for the explanation :)
