### ISSUE TITLE
Synchronize current time on Desktop & Mobile

### ISSUE THREAD

**Issue by codihaus** [google/shaka-player#2897]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.5

**Please ask your question**

Hi

I'm streaming from an HLS source to the client and using Shaka Player.

My idea is to create an online streaming class, where my student can answer the question while watching streaming.

Everything is fine, but there's a problem with the difference in timing counting.

I want to wait until the student is at the same time point as mine, and it will show the question.

So here's my method.

![Web 1920 – 1@2x](https://user-images.githubusercontent.com/68498487/95377823-4910e180-090d-11eb-8565-35755b6ecd15.png)

You will see, as on the left side - it's mine screen, which is playing the stream, and base on my current time, I will send the signal that contains my timestamp to my students.

And I will compare 2 current times (as I understand, it's the current live stream time) (one got from WebSocket signal, one is my student).

If it matches> it will show the question.

Unfortunately, it never matches. The student using a mobile phone, his current time only 30, while mine is 41200. And I couldn't show the question/quiz at all.

So, can you please help me out or give me some more information about this?

Thank you!

**Comment by joeyparrish** [comment]
Do I understand correctly that the HLS stream is live?  Does it happen to use TS segments instead of MP4?

In current versions of Shaka Player, HLS VOD content will be offset such that it begins at 0.  This would be consistent across viewers, though, since VOD content is static.  For HLS live content, or for DASH content regardless of VOD or live, we do not change the timestamps.

However, for *TS* content, which we can only support through transmuxing provided by `mux.js`, we can't guarantee that mux.js is not manipulating content timestamps when it converts TS into MP4.  So two viewers joining the live stream at different times would see different timestamps from the video element's point of view.

Furthermore, there are issues with certain smart TV platforms (#2327, #1610) in which large timestamps trigger bugs in the platform and cause playback problems.  To solve this, I have been working on a change in which we would offset all live streams so that the beginning of the HLS playlist or DASH seek range at the time the viewer joins would be offset to 0.  This would mitigate the TV platform bugs by reducing the magnitude of the timestamps, but it would cause your issue to occur in a wider range of content.  So I would advise you not to rely on `currentTime` for live streams long-term.

For now, with current versions of Shaka Player, I'm assuming that you are seeing this problem because the content is TS and being transmuxed into MP4 on the fly.  (If that is not the case, please let me know!)  So you should be able to avoid it by using MP4-based content, which I would recommend regardless.

A more future-proof solution might be to use `player.getPlayheadTimeAsDate()` instead of `videoElement.currentTime` for this comparison.  It returns a wall clock time instead of a video timestamp.  It's based on when the playlist was first loaded, so if the playlist gets updated once per segment on the server side, comparisons across clients will probably be accurate to within one segment or so.

Does this help?

**Comment by joeyparrish** [comment]
Oh, one other wrinkle.  Since you mentioned mobile specifically, and you're talking about HLS, I should have figured you might be dealing with iOS.

On iOS, we rely on Apple's native HLS implementation for playback, so `getPlayheadTimeAsDate()` can only return values provided to us by Apple, and we have no control over them.  I believe they should be compatible, but as far as I know, we have never verified that these values are the same across iOS and, say, desktop Chrome.

Please let us know how it works out, and if we can do anything else to assist you.

**Comment by codihaus** [comment]
Hi @joeyparrish 

Thank you for your advice, it really helpful and contain the deep root problems.

What you're understanding is correct, I'm trying to solve the problem on iOS with livestream HLS format.

So, as in your comment mentioned:

1/ I'm using mux.js to transfer it to mp4, so each viewer joins at a different time has a different timestamp.
2/ getPlayheadTimeAsDate() depend heavily on iOS to return the values, so we have no control.

On the #1, mux.js has "keepOriginalTimestamps" option that might help, I don't know, but I will give it a try. The documentation also stated that it might make the difference in audio-video alignment.

To set keepOriginalTimestamps as true in Shaka Player, do you have any idea or documentation to implement to our player?

With #2, as we have no control, and if keepOriginalTimestamps does not work, I have these following ideas, didn't try, but it might be a light and you might see which can be done with it:

- We will read the last segment info, which contains the last time point in segment metadata, so we will know which time is the latest. With this, it might be a little bit mismatch with the actual time, but at least we have something to compare

- We can tell the student's player to seek to our time and start a separate timer (teacher time + iOS native time)

I'm not sure if it works, but I will give it a try, if you have any idea, can you please let me know?

Ah, also on this similar issue https://github.com/google/shaka-player/issues/356 I got a code

```
var playHeadDate = new Date(player.manifest_.presentationTimeline.presentationStartTime_*1000 + videoElm.currentTime*1000)
```

But it's from 2016, and I have tried but it does not work anymore. Do you have any idea?

Thank you very much!!

**Comment by joeyparrish** [comment]
`var playHeadDate = new Date(...` is essentially what is inside `getPlayheadTimeAsDate()`, so you should just use that method directly.  Try it on iOS and on desktop and see if the results are comparable.

As for mux.js, it's configured inside Shaka Player and there's no control over that offered to apps.  But you probably don't need to do anything with that.  `getPlayheadTimeAsDate()` is meant to normalize timestamps to wall-clock time.

If `getPlayheadTimeAsDate()` doesn't work, you could try using MP4-based content, which would take mux.js out of the picture.  If it's a pain to redo your live stream in MP4 just to find out if it will work, you can try ours: https://storage.googleapis.com/shaka-live-assets/player-source.m3u8  That should at least let you find out if the timestamps are more in sync across devices, and if it works, you have a content-based solution available to you.

We have an issue with the tools generating that stream which causes occasional 403 errors that show up in Shaka Player, but the stream plays anyway, so you can ignore them.  It's a bug in the content upload, not the player.
