### ISSUE TITLE
Mono and stereo tracks considered incompatible

### ISSUE THREAD

**Issue by naktinis** [google/shaka-player#2908]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
N/A

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
N/A

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What did you do?**
Used a manifest that has both mono and stereo audio tracks as alternatives. Mono is used for extremely low bandwidth networks.

**What did you expect to happen?**
Adaptive streaming should be able to switch between mono and stereo tracks.

**What actually happened?**
Mono tracks were deemed incompatible with stereo tracks by `areAudiosCompatible_` (adaptation_set.js).

There is the following check:
```
    // Audio channel counts must not change between adaptations.
    if (a.channelsCount != b.channelsCount) {
      return false;
    }
```

I tried removing this restriction and both Firefox and Chrome seem to switch between stereo and mono tracks just fine. Is this restriction necessary? Would it possible to remove it or make it optional?

**Comment by joeyparrish** [comment]
When a user only has two speakers, 6-channel content is generally downmixed to 2 channels, and usually badly.

I always struggle with surround sound content on my home TV because of this.  The dialog is too quiet, so you turn it up, then an action scene comes and it's way, way too loud, and we wake up the kid.

Or take the same experience and imagine it with headphones on, and you blast your eardrums when the action starts.

When content is mastered for 2 channels, the volume is usually much more even.

So, if I'm watching something and the player automatically switches between 2 and 6 channels, potentially over and over again during playback as my bandwidth estimate fluctuates, I will be really, really agitated as a user.

I see how adapting between mono and stereo might be okay, but the restriction was put in place with stereo and surround in mind.  In retrospect, this should absolutely be explained in comments in that part of the code.

Does this help?  Is there a reason why adapting between stereo and mono would be desirable?  Or are you just curious about a seemingly arbitrary restriction?

**Comment by joeyparrish** [comment]
Oh, I should have read more carefully.  You did explain why you want to adapt between them:

> Used a manifest that has both mono and stereo audio tracks as alternatives. Mono is used for extremely low bandwidth networks.

I'll mark it as an enhancement to make an exception for switching between stereo and mono specifically.

**Comment by joeyparrish** [comment]
We would welcome a PR for this if you are interested to contribute!  Otherwise, we will get to it eventually, but much of our other work is higher priority right now.

**Comment by naktinis** [comment]
True, I could imagine 5.1 -> stereo switch being annoying and undesirable. Basically in our case we were exploring the way of catering for very low bandwidth cases (when audio size starts becoming significant) and one option would be to switch to mono and save half the audio bandwidth but still have intelligible speech.

**Comment by joeyparrish** [comment]
Yeah, that makes sense.  I think you could add a special case for comparing stereo and mono.  Something like:

```js
// Don't adapt between channel counts, which could annoy the user
// due to volume changes on downmixing.  An exception is made for
// stereo and mono, which should be fine to adapt between.
if (a.channelsCount > 2 || b.channelsCount > 2) {
  if (a.channelsCount != b.channelsCount) {
    return false;
  }
}
```

If you have time to test this out, update tests, and submit a PR, I would be happy to review it.  Thanks!

**Comment by avelad** [comment]
PR --> https://github.com/google/shaka-player/pull/2911
