### ISSUE TITLE
Shake can support TTML (text-based) outside MP4 fragments?

### ISSUE THREAD

**Issue by zengjunjun** [google/shaka-player#2912]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.x

**Please ask your question**
Hi~
   Shake can support TTML (text-based) outside MP4 fragments?
   Where can I find the simple demo for MP4 with TTML? I cannot reproduce the demo in (https://shaka-player-demo.appspot.com/demo/#audiolang=zh-CN;textlang=zh-CN;uilang=zh-CN;asset=https://storage.googleapis.com/shaka-demo-assets/tos-ttml/dash.mpd;panel=ALL_CONTENT;panelData=SUBTITLES,MP4;build=uncompiled)

Thanks

**Comment by zengjunjun** [comment]
Thanks
But , I mean I cannot setting outside TTML track . 
```
    <video id="video"
           width="640"
           controls autoplay>
    <track src="s-eng.ttml"
           kind="subtitles"
           label="TTML"
           srclang="en"
           type="application/ttml+xml"/>         
    </video>
```
And，I get  two track title.  Why  `Shaka Player TextTrack`   alway show?  And The TTML cannot work ,and  this title disappear in next time.
![image](https://user-images.githubusercontent.com/12684236/96209730-e40b5a80-0fa2-11eb-8aae-2f9d2d6026f3.png)
![image](https://user-images.githubusercontent.com/12684236/96210265-208b8600-0fa4-11eb-91ef-71c5aa3bd87e.png)

**Comment by zengjunjun** [comment]
Use the demo in tutorial :
https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html

I repalce this 
```
const manifestUri =
    'https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd';
```
with https://storage.googleapis.com/shaka-demo-assets/tos-ttml/dash.mpd.

It cannot work in localhost ,but it worked in [shaka-player-demo.appspot.com](https://shaka-player-demo.appspot.com/demo/#audiolang=zh-CN;textlang=zh-CN;uilang=zh-CN;asset=https://storage.googleapis.com/shaka-demo-assets/tos-ttml/dash.mpd;panel=ALL_CONTENT;panelData=SUBTITLES,MP4;build=uncompiled).

**Comment by joeyparrish** [comment]
> It appears that the Chinese subtitles in that particular video are broken, but the other languages are working.

I was completely wrong!  Looking at the UI in Chinese, which I do not speak, I mistook the selected language of "off" or "none" with "Chinese".  This confused me because language names are always shown in that language, regardless of the UI language.  But with the UI in Chinese, I saw a Chinese word and assumed it said "Chinese", when in fact, it said "off".

**Comment by joeyparrish** [comment]
> But , I mean I cannot setting outside TTML track .
>
> ```html
>     <video id="video"
>            width="640"
>            controls autoplay>
>     <track src="s-eng.ttml"
>            kind="subtitles"
>            label="TTML"
>            srclang="en"
>            type="application/ttml+xml"/>         
>     </video>
> ```

No, you can't do that.  Setting a `<track>` element creates a track through the browser, not through the player.  Most browsers don't support TTML.  Instead, you should use the `player.addTextTrack()` method of Shaka Player.  For example:

```js
player.addTextTrack(
  's-eng.ttml',  // uri
  'en',  // language
  'subtitles',  // kind
  'application/ttml+xml',  // mimetype
  null,  // codec
  'TTML');  // label
```

**Comment by joeyparrish** [comment]
> Why Shaka Player TextTrack alway show?

Because you are using the browser's built-in controls, which show you `<track>` elements and `TextTrack` objects on the video element, not the text tracks of Shaka Player.  Shaka Player creates a single `TextTrack` ([web API](https://developer.mozilla.org/en-US/docs/Web/API/TextTrack)) on the video element, then populates it with individual text cues based on the selected track within Shaka Player.  We don't map each internal text track to a `TextTrack` object on the platform.

Instead, you should use the Player APIs `player.getTextTrack` and `player.selectTextTrack` if you want to build your own UI, or use our UI and get it for free: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html

Our UI library not only shows you what you would expect from tracks and languages, but also offers things the browser's built-in controls can't, like resolution selection, and others.  And it's completely configurable and extensible: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html

Does this help?

**Comment by zengjunjun** [comment]
Thanks
