### ISSUE TITLE
widevine sucks

### ISSUE THREAD

**Issue by loweswebmaster** [google/shaka-player#2917]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Yes

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
android

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
no

**What are the manifest and license server URIs?**

no

**What did you do?**

I try to get key for netflix amazon

**What did you expect to happen?**
Key is given for amazon netflix

**What actually happened?**

widevine says no more nexus 6 because they suck

**Comment by loweswebmaster** [comment]
widevine
playready
fairplay streaming
cisco videoguard
adobe primetime

**Comment by loweswebmaster** [comment]
widevine
playready
fairplay streaming
cisco videoguard
adobe primetime

**Comment by loweswebmaster** [comment]
widevine
playready
fairplay streaming
cisco videoguard
adobe primetime

**Comment by loweswebmaster** [comment]
widevine
playready
fairplay streaming
cisco videoguard
adobe primetime

**Comment by loweswebmaster** [comment]
widevine
playready
fairplay streaming
cisco videoguard
adobe primetime

**Comment by joeyparrish** [comment]
> **What did you do?**
> I try to get key for netflix amazon
>
> **What actually happened?**
> widevine says no more nexus 6 because they suck

I can understand how you might be frustrated over the compromise of a device's security and the actions taken by some combination of Widevine, Netflix, or Amazon in response.

However, this is not Widevine.  This is Shaka Player.  Your issue is both completely off-topic, and violates the project's [Code of Conduct](https://github.com/google/shaka-player/blob/master/CODE_OF_CONDUCT.md), which states:

> Examples of unacceptable behavior by participants include:
> 
> - The use of sexualized language or imagery and unwelcome sexual attention or advances
> - **Trolling, insulting/derogatory comments**, and personal or political attacks
> - **Public** or private **harassment**
> - Publishing others' private information, such as a physical or electronic address, without explicit permission
> - **Other conduct which could reasonably be considered inappropriate in a professional setting**

Your PR #2918 titled "delete shitty widevine" is also in clear violation of the same terms.

Given two seemingly deliberate violations of the project's Code of Conduct in rapid succession, your account will be banned from all further activity on the project.  Given that your account was created only a few hours before your posts, possibly for the sole purpose of making these comments, I doubt this will bother you much.

But please, be more considerate in the future.  We're all just humans trying to live and be happy.  It's harder than usual these days.
