### ISSUE TITLE
Release Date for 3.1?

### ISSUE THREAD

**Issue by nebnitt** [google/shaka-player#2945]
Hi folks, 

I was wondering if there was an update to when 3.1 will be released. Per the [roadmap](https://github.com/google/shaka-player/blob/master/roadmap.md) it still says Q3. Thanks for any update you can provide.

**Comment by joeyparrish** [comment]
Hello,

The roadmap is clearly out of date.  Sorry about that!  We have some TTML issues introduced by me during the CEA captions work, and they must be resolved before v3.1 can be released.  @michellezhuogg is working on the fixes.  This is the only blocking issue I am aware of.

Does this answer your question?

**Comment by nebnitt** [comment]
Thanks @joeyparrish  - sounds good. Curious if you have any rough sense of timeline (on the order of weeks/months, even). Appreciate it.

**Comment by avelad** [comment]
Is there a tentative idea when 3.1 is going to be released?

**Comment by ismena** [comment]
Alright, I'm gonna pull the plug and say that we're releasing it by the end of April, hell or high water (: 
(Unless Joey overrides me because Joey's always right).

I'm hoping for sooner cause we have 15 open issues for 3.1, most of them assigned and the team just agreed to invest in bug fixes for the next couple of weeks.

**Comment by joeyparrish** [comment]
From now on, @ismena is always right.  Authority is exhausting.

**Comment by ismena** [comment]
Ok then! We'll shoot for early/mid April, but if not - whatever's ready by May 1 gets released.
