### ISSUE TITLE
Management of forced subtitles

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#2947]
After including the change https://github.com/google/shaka-player/pull/2938 for the parsing of forced subtitles, now the management part remains.

I open this issue to agree how it should work.

Load cases:
1. The user loads a stream that does not have forced subtitles -> The player must continue working as before
2. The user loads a stream that only has forced subtitles -> The player must select by default the forced track of the audio language.
3. The user load a stream that has both forced and unforced subtitles. --> The player should select by default the forced track of the audio language only if the user has not selected another language/role

Language change in the middle of playback:
Open to suggestions.

**Comment by TheModMaker** [comment]
I think the forced subtitles should only have a special effect during startup.  If the app manually selects a track or disables captions, I think we should honor that choice.

First, we have a separate `preferredTextLanguage` property we should use instead of using audio language.

For initial track selection, it should just be like the `stream.primary` field, we select this track over others.  We'll also enable captions if we have a forced track even if they are disabled initially.  Also, we should probably select a forced track of a different language even if it doesn't match the preferred language.  For example, if the preferred language is Spanish and there is a forced subtitle for English, we should still select it since it is better than nothing.

So, if there are any forced tracks, we select one of them based on `preferredTextLanguage` initially and show captions by default.  Otherwise, behavior doesn't change.

**Comment by joeyparrish** [comment]
> Also, we should probably select a forced track of a different language even if it doesn't match the preferred language.

I haven't completely thought this through, but I'm skeptical of this part.

First, are there any situations in which the set of forced sub languages reasonably differs from the set of audio languages?  If not, the choice of behavior in that situation is a bit arbitrary/academic.

I don't think we are in a position to gauge that, having no content or end-users of our own.  @avelad, any thoughts on this?

**Comment by TheModMaker** [comment]
My thought is that one use case for forced subtitles is for fictional languages where the viewer cannot (or usually will not) understand the language.  So having something up will be better than nothing, even if it doesn't match their preferred language.

Also since the audio and text preferences can be different, we may be able to match the user's preferred audio language but not their preferred text language.  This also mirrors how we select audio languages where we'll still play some audio track even if it doesn't match the user's preferences.

**Comment by avelad** [comment]
I think forced subtitles should only match the audio language.

For example:
In the movie Avatar there is a fictitious language, but if the user puts the audio in English, and we do not have forced subtitles in English (content problem), it is not a good idea to put another language (ex: Arabic), because the user would not know what you are saying by not knowing the language.

**Comment by TheModMaker** [comment]
> I think forced subtitles should only match the audio language.

There may be cases where users may understand audio in a language but not read it.  For example, they are learning a new language and want text in their native language.  This is why we have separate configs.

> it is not a good idea to put another language (ex: Arabic), because the user would not know what you are saying by not knowing the language.

I also understand the case where a user won't understand an option; but this will also happen for audio.  If a manifest only specifies Arabic audio, then we'll play it even if the user won't understand it.  We'll always play audio even if it doesn't match.  I'm thinking we should treat forced subtitles the same way.

**Comment by joeyparrish** [comment]
> In the movie Avatar there is a fictitious language, but if the user puts the audio in English, and we do not have forced subtitles in English (content problem), it is not a good idea to put another language (ex: Arabic), because the user would not know what you are saying by not knowing the language.

This is what I was thinking.  A lack of matches between forced subs and audio languages is a content problem.  What we do in a situation where the content is not properly created is a matter of best effort, and somewhat arbitrary.

Jacob, I hear what you're saying about showing something instead of nothing, as that's what we do for audio as a best-effort fallback.  However, I think Alvaro is correct in that showing Arabic subtitles would be unhelpful and confusing for a non-Arabic-speaking user who didn't request them.  And unlike audio, text is not required.  We fall back to the "main" audio language because not playing audio is a bad idea.  But not showing text is comparatively okay.

So I believe the behavior in this corner case of "forced subs exist && no matching text language for audio language" should be not to show text by default.  And in all cases, the API and UI allow the developer/user to do whatever they want.  Text can be disabled through the API or UI, even if forced text tracks exist, and forced tracks in an arbitrary language can be selected when none exist for the user's preferred language.

**Comment by avelad** [comment]
Can you change the issue type to enhancement? I want to work on this in the future.

**Comment by avelad** [comment]
I am going to send a PR with this idea, but before I start writing the code, I prefer to validate with you what we want:

I'm going to create a new configuration parameter that is `preferredTextLanguageForced` (boolean), based on this we will first prefer forced subtitles if they exist, otherwise the full subtitle would be selected.
