### ISSUE TITLE
Stylelint fails on Windows

### ISSUE THREAD

**Issue by mmsreedhar** [google/shaka-player#2985]
[INFO] Linting CSS...
Error: No files matching the pattern "C:\Users\<USER>\PycharmProjects\shaka-player\demo\cast_receiver\receiver_app.css, C:\Users\<USER>\PycharmProjects\shaka-player\demo\demo.less, C:\Users\<USER>\PycharmProjects\shaka-player\
ui\controls.less, C:\Users\<USER>\PycharmProjects\shaka-player\ui\less\buttons.less, C:\Users\<USER>\PycharmProjects\shaka-player\ui\less\containers.less, C:\Users\<USER>\PycharmProjects\shaka-player\ui\less\general.less, C:\U
sers\<USER>\PycharmProjects\shaka-player\ui\less\other_elements.less, C:\Users\<USER>\PycharmProjects\shaka-player\ui\less\overflow_menu.less, C:\Users\<USER>\PycharmProjects\shaka-player\ui\less\range_elements.less, C:\Users\
<USER>\PycharmProjects\shaka-player\ui\less\spinner.less" were found.
    at C:\Users\<USER>\PycharmProjects\shaka-player\node_modules\stylelint\lib\standalone.js:212:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Using PYCharm to build ShakaPlayer

**Comment by joeyparrish** [comment]
It would appear that stylelint is not working correctly on Windows.  I'm not sure if this is purely an issue with stylelint, or with how we call it from our build system.

If you are not planning to contribute to Shaka Player, you may be able to work around it by editing `build/check.py`, locating the following lines:

```py
@_Check('css_lint')                                                              
def check_css_lint(args):                                                        
  """Runs the CSS linter."""
```

and commenting out `@_Check('css_lint')`, which registers this function with the check.py tool.  By commenting out that decorator, the css linting step will be skipped.

While we figure out what is wrong with stylelint on windows, does this workaround help?

**Comment by joeyparrish** [comment]
(This may be relevant to any potential fix: https://github.com/stylelint/stylelint/issues/3624)

**Comment by mmsreedhar** [comment]
commenting check css_lint worked for me.
Thanks for the support

**Comment by joeyparrish** [comment]
Reopening so that we can track future work to fix stylelint usage on Windows.  Thanks!

**Comment by joeyparrish** [comment]
It could be that something as simple as upgrading stylelint could solve the issue, or it could be something wrong in our build scripts, or it could be that we need to pass unix-style paths or something for stylelint to understand the arguments we gave it.  I haven't explored any of these possibilities.  Happy to give pointers to any Windows user who wants to help with this.

**Comment by surajkumar-sk** [comment]
@joeyparrish . i am a windows user and would love to work on this . upgrading stylelint doesn't work . i just installed the latest version of stylelint . the error still prevails .

**Comment by joeyparrish** [comment]
Please look at the class `CssLinter` in `build/compiler.py`.  This runs stylelint in our build scripts, and generates a command line to do so.  If you can run stylelint on Windows manually, and figure out how to make it work in general, you could then modify the `CssLinter` class in Python to generate the command line differently.

I hope that helps!

**Comment by joeyparrish** [comment]
I noticed that the output has backslashes in it (Windows-style paths).  You could try replacing all of those with forward slashes, since forward-slash-style paths should also work on Windows, and hypothetically, a buggy command-line app could be interpreting backslashes as an escape sequence.  I know I've seen various tools behave this way on Windows in the past, especially when cygwin is in the mix (but I'm old and things are generally much better now).

That's the only other thing I can think of, but if that doesn't work, I trust you to investigate and find a viable solution.  Thanks!

**Comment by surajkumar-sk** [comment]
Hi , I ran few tests with stylelint on windows to check for possible causes of error . instead of runing stylelint through build/all.py .
I manually typed stylelint command for a specific file in the shaka-player project .

cmd command - stylelint --config "c:\user\file\shaka-player\.csslintrc" --disable-default-ignores "c:\user\file\shaka-player\demo\demo.less" 

This command gave an error : No FIle Matching The Pattern "c:\user\file\shaka-player\demo\demo.less" 
at C:\Users<USER>\PycharmProjects\shaka-player\node_modules\stylelint\lib\standalone.js:212:12
at processTicksAndRejections (internal/process/task_queues.js:93:5)

exactly as shown in above issue . 

but when i replace all the forward slash with backward slash it starts working fine .
cmd command - stylelint --config "c:/user/file/shaka-player/.csslintrc" --disable-default-ignores "c:/user/file/shaka-player/demo/demo.less" 
the above command didnt display anything . 

so i checked the rules and added "24cm" as a size value which goes against the rules , now when i ran the command again it displays 
demo/demo.less 62:12 unexpected unit "cm" .
which implies the command works .

so replacing forward slashes with backward slashes will work .

**Comment by joeyparrish** [comment]
Nice!  I'm glad that worked.  That should be an easy thing to change where we build the command line in `CssLint`.  Thanks for looking into it!

**Comment by surajkumar-sk** [comment]
when command lines is build the ocations are stored in variables . how do we replace the forward slashes with backward slashes inside a variable which is assigned at run time

**Comment by surajkumar-sk** [comment]
@joeyparrish  . only solution which i am able to think of is writing an if condition before we build the command line in CssLint for checking the operating system and replacing all the ' \' with '/ ' for the varables which save the directory location . this problem only occurs in windows due to few exceptions (mistakes done by microsoft ) so writing an if condition is better . 

so , should i write an if condition and send a PR
