### ISSUE TITLE
Some videos not loading after Safari 14 update

### ISSUE THREAD

**Issue by ScripterYoda** [google/shaka-player#3005]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Not able to check that

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
Safari 14, macOS Big Sur

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

Will be send to shaka-plasyer-issued@google.com

**What did you do?**
Open video in my shaka player - it keeps on loading and does not play. The issue appears only on Safari 14 and only since 14th November. The issue affects only some videos (and even they sometimes suceed in playing). At first I thought it to be a Safari bug, but Your demo seems to be handling the affected videos properly. The affected videos are mainly short (few seconds) and mainly black.

**What did you expect to happen?**
Videos would play.

**What actually happened?**

They just kept on loading. The time of video was displayed correctly and sometimes I could move the video to any point and screen would show proper frame but it would still buffer and not play.

**Comment by ScripterYoda** [comment]
Any update?

**Comment by joeyparrish** [comment]
The content you sent us is working correctly for me in Safari 14.0.2 on macOS Catalina 10.15.7.  I tried Shaka Player v3.0.6, v3.0.7, v3.0.8, and the master branch, and the content plays in all of those versions.

I'm going to try again on another mac with Big Sur 11.1

**Comment by joeyparrish** [comment]
I tried again with Safari 14.0.2 on macOS Big Sur 11.1, with Shaka Player v3.0.6, v3.0.7, and v3.0.8, and the content plays in all of those, too.

> At first I thought it to be a Safari bug, but Your demo seems to be handling the affected videos properly.

It could be that your own application is doing something wrong.  Are you using the native browser controls (`controls` attribute on the `<video>` element) or our player UI?  Are you maybe seeing autoplay restrictions in Safari?  Does it play if you click the play button explicitly on the controls?

I noticed in my tests that autoplay doesn't always work.  If I start the video with a user interaction, by adding it to the "custom content" tab in the demo and then clicking to load it, it would always play.  If I load it via the URL and try to autoplay on load, it doesn't, and I have to click the play button.

It could be that if you're using native browser controls and that autoplay is failing because of Safari's restrictions on autoplay.  If that's the case, it's possible that Safari shows you the spinning "loading" icon, making you think it's not loaded, even though it might be just waiting for you to click play.

Does any of that help?
