### ISSUE TITLE
Shaka API to get the uri of the all the segments of an AdaptationSet

### ISSUE THREAD

**Issue by yvashar** [google/shaka-player#3034]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
latest version

**Please ask your question**
Is there any API to get the uris' of all the segments for a particular AdaptationSet?

**Comment by TheModMaker** [comment]
You can use `player.getManifest()` to get the manifest object, then look at all the [Variants](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.Variant).  You can use `stream.originalId` to get the Representation ID.  Note that because of #3096 you won't be able to use `getUris` in compiled mode.

```js
const manifest = player.getManifest();
for (const variant of manifest.variants) {
  for (const stream of [manifest.video, manifest.audio]) {
    if (!stream) continue;
    await stream.createSegmentIndex();
    for (const ref of stream.segmentIndex) {
      console.log(refs.getUris());
    }
  }
}
```
