### ISSUE TITLE
Add parameter to probeSupport to skip DRM tests

### ISSUE THREAD

**Issue by yethie** [google/shaka-player#3037]
Hi!

I would like to know if there is a way to check whether DASH is supported when shaka.Player.isBrowserSupported() returns true.
Reading the docs it looks like I should avoid using Player.probeSupport() in production.

Thanks!

**Comment by TheModMaker** [comment]
So long as `shaka.Player.isBrowserSupported()` returns `true`, then DASH is supported.  DASH is always supported since it is handled by the library, not the browser.  You can create custom builds without DASH, but the pre-built versions and the default builds contain DASH.

Note that although the manifest format is always supported, the media segments may not be.  Depending on what is in the manifest, the browser may not support it.  For example, if the manifest only specifies WebM content, then the manifest won't be playable if the browser doesn't support it.  This is detected by an error from `player.load()`.  If you know the content ahead of time, you can also use `MediaSource.isTypeSupported` to check for container/codec support.

**Comment by avelad** [comment]
Note: Safari on iOS only supports src=, there is no MediaSource support, but `shaka.Player.isBrowserSupported()` returns `true`

**Comment by TheModMaker** [comment]
Oh yeah, I forgot we special-case Safari.  In that case, you can also check for `window.MediaSource`; this will be truthy on DASH supported platforms, or `undefined` on iOS or a platform where we can't play DASH.  Some platforms (e.g. iOS/Android) support native HLS so we can play HLS even if without `MediaSource`.

**Comment by yethie** [comment]
As @avelad pointed out Shaka Player on iOS does not support DASH even if `shaka.Player.isBrowserSupported()` returns `true`, the same happens on the Playstation 4 browser. So I was wondering if there is a way to detect such cases without writing again the same code that is in `shaka.media.ManifestParser.probeSupport()` an that, as far as I can see, is not exposed.

**Comment by joeyparrish** [comment]
How about we add an argument to probeSupport() to allow you to avoid DRM probes?  It is probing the DRM systems which can result in prompts that interrupt the flow of your app.

**Comment by yethie** [comment]
Hi @joeyparrish, that would be great, thank you!

**Comment by joeyparrish** [comment]
Then I propose we change the signature to `probeSupport(promptsOkay=true)`.  Calling `probeSupport(false)` will therefore skip the DRM tests that may result in prompts.  The docs around this method will need to be updated as well, since IIRC, we currently suggest people not use it in their apps except for debugging.
