### ISSUE TITLE
Fix interactive client-side ads with UI

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#3053]
If an ad contains interactive DOM elements like buttons, the user must be able to click those.  If the user clicks outside the interactive DOM elements of an ad, or if the ad has no such elements, the click should pause the video.

**Comment by joeyparrish** [comment]
Using this ad tag in tests:

https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/simid&description_url=https%3A%2F%2Fdevelopers.google.com%2Finteractive-media-ads&tfcd=0&npa=0&sz=640x480&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=

In the nightly build, interactive buttons are not clickable.  All clicks pause the video.  (Since 655493f4)

In v3.0.6, in the first playback session, interactive buttons are clickable, but clicking outside the buttons does not pause the video.  In the second playback session, interactive buttons are not clickable, and all clicks pause the video (as in the nightly).

Because 655493f4 fixed issues with cleanup of the ad UI, the behavior has at least become consistent.  But until we can make survey-type ads work again, we can't put this particular fix into a release.

**Comment by joeyparrish** [comment]
Click events are received by shaka-text-container and shaka-controls-container.  shaka-text-container should have ignore pointer events, and shaka-controls-container's event handlers could maybe be made aware of the ad and pass the event along.

**Comment by joeyparrish** [comment]
I have a fix for this:

> If an ad contains interactive DOM elements like buttons, the user must be able to click those.

But only by sacrificing this:

> If the user clicks outside the interactive DOM elements of an ad, or if the ad has no such elements, the click should pause the video.

By making the text container ignore pointer events, and making the controls container (except the bottom controls) ignore pointer events while an ad is playing, I have been able to fix interactive ads.  But there doesn't seem to be a good way to get click events that are inside the ad container but not on an interactive element in the ad's iframe.
