### ISSUE TITLE
Disable MediaSession API

### ISSUE THREAD

**Issue by ferferga** [google/shaka-player#3100]
**What version of Shaka Player are you using?**
3.0.7

**Please ask your question**

Hello and thank you very much for using Shaka.

I've been some days investigating how we can add proper MediaSession API support in our app leveraging shaka's own mediasession. However, reading through our docs, it seems there's no way for us to pass our custom ``MediaMetadata`` or action handlers to the MediaSession instance that shaka creates.

For this reason, we would like to disable Shaka's own MediaSession instance, so we can create and handle it completely on our own. However, I tried to find about this in the docs and in the code and it seems there's no way to disable it, unless I'm missing something. Is it possible?

Thank you very much

**Additional context**

Feature request for exposing MediaSession at #3101

**Comment by joeyparrish** [comment]
We don't create a MediaSession instance in Shaka Player, because we don't know any metadata about your content.  You only provide us with a manifest URL.

Our demo app creates a MediaSession instance with metadata about our demo content, but this is done at the level of the demo app, not in Shaka Player itself.

So as far as I can tell, there is no MediaSession usage to disable in Shaka Player.

Does this answer your question?
