### ISSUE TITLE
Feature Request - MergingMediaSource

### ISSUE THREAD

**Issue by FireMasterK** [google/shaka-player#3126]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

So, exoplayer has a feature where you can combine an Audio Track and Video Track without knowing anything about them. I would like to do something similar - but in a browser.

https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/MergingMediaSource.html

**Describe the solution you'd like**

An implementation of this without Dash.

**Describe alternatives you've considered**

Dash, but I don't have the required parameters to create a manifest here, unfortunately.

**Additional context**

https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/MergingMediaSource.html

**Comment by ismena** [comment]
Hi @FireMasterK 
Could you describe the behavior you're talking about in a bit more detail?
You mentioned an implementation without Dash - do you mean some other manifest format like HLS? Or no manifest altogether? How do you envision this?

**Comment by FireMasterK** [comment]
Hi @ismena 
I was envisioning this without any HLS/Dash manifests. It would just take 2 URLs with their mimetype and mux them together for playback.

**Comment by ismena** [comment]
Oh! Fun :)
What are the urls? Segments? Entire presentations in a single file?
I'm not sure we'll well set up for that use case, but let me bug our TL.
@joeyparrish thoughts? :)

**Comment by joeyparrish** [comment]
If the streams are already in fragmented MP4 format, this is feasible.  You can feed them independently to MediaSource, with an optional offset on one or the other to align them, and the browser should be able to play it.

However, this is specifically true of **fragmented** MP4s, which are the sort that are already packaged for DASH or HLS.  It's not going to work for any old MP4 file, as MP4 in general won't be understood by MediaSource.

Also, to support seeking, Shaka Player would have to be able to locate the "sidx" boxes for each stream.  If you don't plan to tell us where they are, as a DASH manifest would, it would be non-trivial to find them, and we may not be able to help you.  This is because unlike ExoPlayer, Shaka Player sits on top of the browser and has no direct access to demuxers.  We need at least that much metadata to be able to locate individual segments within the stream.

If you know a relative offset to align video & audio, and you know where the "sidx" boxes are located (byte ranges into each stream), you could construct a minimal "Manifest" object in Shaka Player to represent this.  We wouldn't care where it came from.

Does this help?

**Comment by FireMasterK** [comment]
That's really helpful explaination, thanks a lot 👍

My best bet is to find a way to get this information, thanks a lot!
