### ISSUE TITLE
Shaka fails to play HLS with error code 4017 (HLS_INVALID_PLAYLIST_HIERARCHY)

### ISSUE THREAD

**Issue by tomraut** [google/shaka-player#3133]
We have issue with our HLS stream which seems to work just fine with demo player but doesn't work in our own custom made player. For some reason when trying to play out https://csm-e-tv4se2-eb.tls1.yospace.com/csm/live/283556008.m3u8?yo.up=https://mtvdashliveusptest1-a.akamaized.net/live/ETEST/ETEST.isml/&yo.ap=https://tv4-ys-intermediate.akamaized.net/prod/&pid=44989&s=44004003&dcid=computers_html5&t=html5%2Cwww.katsomo.fi%2Chttp%3A%2F%2Fwww.katsomo.fi%2C44004003%2Ctesti_15012020_sl1_yospace%2Cpremium it fails with mentioned error.

Is there some special tweaking made on the demo player page, for instance custom HLS manifest parser etc. or how is it so that demo player is able to play mentioned m3u8 playlist without issues but our own player not?

**Comment by tomraut** [comment]
Is there anything custom made on the demo player page which is not included by default in Shaka's compiled library? For some reason on demo page, HLS' parsePlaylist method is called only with media playlists but in our case first playlist gets parsed is the master playlist and thus Shaka throws HLS_INVALID_PLAYLIST_HIERARCHY error.

**Comment by tomraut** [comment]
So, in our case, method createStreamInfo_() inside hls_parser.js calls this:
`const playlist = this.manifestTextParser_.parsePlaylist(
        response.data, absoluteMediaPlaylistUri);`
..where response.data has mysteriously MASTER PLAYLIST data while absolueMediaPlaylistUri refers to VARIANT's URL.

**Comment by TheModMaker** [comment]
We don't do anything special on the demo.  Make sure you are loading the same version of the library and not using some older version.  Can you provide a link to your site so we can see what is going on?  Are you registering any request/response filters in your app that may be affecting the data?  Are you using a service worker or proxy that may be affecting the responses?

**Comment by tomraut** [comment]
Making sure that same version of the library is loaded is kinda tricky as demo page loads Shaka in hundreds of pieces and not the bundled version. So unfortunately, no, this does not answer my question.

**Comment by TheModMaker** [comment]
You can just look at the top-right of the demo to see the version.  The demo loads the uncompiled version by default, but you can change this to the compiled bundle at the bottom of the page in the `DEMO MODE` section.

**Comment by joeyparrish** [comment]
To expand on what @TheModMaker said, the only things special about the demo page are:

1. It loads the uncompiled Shaka Player by default (change to the compiled version at the bottom of the page)
2. You're seeing the latest release by default (currently v3.0.10, but you can find older versions through https://index-dot-shaka-player-demo.appspot.com/)

To be sure it's not an issue with compilation, try this link from the bottom of the demo page to switch to compiled mode: https://shaka-player-demo.appspot.com/demo/#build=compiled  If your content still plays there, the compiled vs uncompiled difference is not relevant.

If your app uses an older version of Shaka Player than the demo, that could easily explain the difference in behavior.  We may have fixed a relevant bug since the release you're using, and upgrading may solve the problem in your app.

If you have a service worker in your app, or network filters installed in your Shaka Player config, this could also explain the issue, since any of those things could alter network responses before we process them.

@tomraut, does this help?

**Comment by tomraut** [comment]
Yes, thanks.
