### ISSUE TITLE
Is There any way to make DRM content Play on Chrome Android devices ?

### ISSUE THREAD

**Issue by tareq-rezk** [google/shaka-player#3150]

**Comment by ismena** [comment]
@joeyparrish @TheModMaker 
I'm sure one of you knows the answer to this. Or both.

**Comment by hamesjarden** [comment]
Have an example / more details? Chrome Android can play widevine protected content just fine.

**Comment by joeyparrish** [comment]
Shaka Player supports DRM on Chrome on Android, and there is nothing special that needs to be done to enable this.

Though most do, not every Android device has Widevine support.  If your device doesn't support Widevine, we can't do anything about this.

You can check for DRM support by loading this page in your browser (also available through the "Browser Support Test" link at the bottom of our demo): https://shaka-player-demo.appspot.com/support.html

At the bottom of the report is a section called "drm".  Inside that, if "com.widevine.alpha" shows "null", you don't have Widevine support.

If you have Widevine support on your device, and you still can't make DRM content play on Android, try this "DRM Configuration" tutorial next: https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html

If you have Widevine support on your device, and you've been through the tutorial, and you still can't make DRM content play, please file an issue using our "bug" template and provide all the information requested there.  Please also include relevant snippets of your application code so that we can see what you're doing.

Does this answer your question?
