### ISSUE TITLE
DRM Cookie Authentication page does not store cookie

### ISSUE THREAD

**Issue by Alpenglow88** [google/shaka-player#3192]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.20

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
N/A

**Are you using the demo app or your own custom app?**
Demo and custom

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome (Version 88.0.4324.192)- Mac Catalina (10.15.7)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Manifest - https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd
DRM server - https://cwip-shaka-proxy.appspot.com/cookie_auth

**What did you do?**
Following the DRM tutorial and attempting to set the cookie auth option for DRM.

Setup request filter to allow cross site credentials as detailed in instructions (before player.load())

```
  player.getNetworkingEngine().registerRequestFilter(function(type, request) {
    if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
      request.allowCrossSiteCredentials = true;
    }
  });

```
**What did you expect to happen?**
Visit set_cookie page (https://cwip-shaka-proxy.appspot.com/set_cookie), visit player page, cookie persists and playback is allowed (no error 6007)

**What actually happened?**
When visiting the set_cookie page then the cookie is set (can see it is with the `document.cookie()` call) but navigating back to the player page does not have the cookie stored and the player throws a 6007 error

**Comment by joeyparrish** [comment]
Chrome recently changed the rules about third-party cookies.  Could this be the cause?

Try opening chrome://settings/cookies and see if allowing all cookies resolves the issue.  If so, we know the new rules are the cause.

https://blog.chromium.org/2020/01/building-more-private-web-path-towards.html
https://www.chromium.org/Home/chromium-privacy/privacy-sandbox#TOC-Turning-Down-Third-Party-Cookies
https://www.wired.co.uk/article/google-chrome-cookies-third-party-ads

**Comment by Alpenglow88** [comment]
@joeyparrish Thanks for this!

Unfortunately, I don't think this is the problem here. 

I am seeing that after navigating to the set_cookie page and back to the Shaka implementation, when attempting to load the asset I am now seeing the `CWIP-Auth-Cookie` stored in the Application tab of the dev tools (which it isn't if you do not visit the set_cookie page first) but I am not seeing it stored in the `document.cookie` response in the console and then the asset fails to load with a `6007` 😞 

It is worth pointing out I think, that I am trying this with localhost as I have not deployed this app version yet (just incase that is causing issues - I know there is some localhost cookie rule changes recently) but I am also seeing this persist across into other non-localhost sites

**Comment by joeyparrish** [comment]
`document.cookie` only shows you cookies for this document.  If that's your test page, it won't show up in the console, and that's expected.  If you go back to cwip-shaka-proxy.appspot.com, you'll see it show up in `document.cookie`.

I can reproduce your results, but what I see is that:

1. The license server sends a cookie in the HTTP response (set_cookie)
2. The cookie is stored by the browser (you can look at the stored cookies in the console or through the lock icon in Chrome next to the URL)
3. The player sets the correct flag to send cross-origin credentials in the request (stepped through it in a debugger to confirm)
4. The cookie is not in the HTTP request headers (as seen in the network panel of the debugger)

To me, this looks very much like Chrome's recently-added third-party cookie restrictions.  I'm not sure if I can definitively prove that, but we're doing everything right in the client as far as I can tell.

I think the only way I could prove it would be to host the license server and test page on the same origin, so that the cookie is no longer cross-origin.  I would expect it to work, in that case.

If cross-origin cookies are dying, then as far as I can tell, the best thing we can do is remove the tutorial that references them.  There are still many other authentication methods available to applications, and same-origin cookies should not only work, but require no configuration in Shaka Player to begin with.

Does this make sense?

**Comment by TheModMaker** [comment]
Can we set the cookie's settings to allow cross-origin access?  Does this doc help https://web.dev/samesite-cookies-explained/?

For example, can the server set `CWIP-Auth-Cookie=abc;  SameSite=None; Secure`?

**Comment by joeyparrish** [comment]
That did the trick!  I'm not sure when the "Secure" cookie attribute became a requirement, but we haven't held any training classes since 2019, so that particular tutorial hasn't been checked in a while.  The fix has been deployed to the cwip-shaka-proxy service.

Thanks, @TheModMaker, for the fix, and @Alpenglow88 for pointing out the issue.
