### ISSUE TITLE
Error codes 3015, 3016, 6008 occur while playing a video.

### ISSUE THREAD

**Issue by KazukiSugiyama107** [google/shaka-player#3194]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
confirmed.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
I haven't explained the error code of `3015`, so I'd like to ask you a question.

**What version of Shaka Player are you using?**
3.0.6

**Please ask your question**
Multiple errors occurred while playing a video in the application provided to the user.
Error codes are `3015`, `3016`, `6008`.

Video being played can be played without problems, and it is a problem that occurs only for specific users.
This is a problem for certain users, and other users can play the video that causes the error.
So I don't think it's a video file issue.

Investigation method for `3016` and `6008` was described in FAQ, but what kind of investigation method should be used for the error `3015`?
Also, is the cause of the `3016` error other than the video file?

Log received by the application side is attached below
#### 3015

```
shaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3015,
  "data": [
  {
  "stack": "Error: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.\n at Object.start (app://./static/js/chunk-eff51980.34f7a034.js:28:54938)\n at hi (app://./static/js/chunk-eff51980.34f7a034.js:28:56580)\n at ci (app://./static/js/chunk-eff51980.34f7a034.js:28:56060)\n at O.b (app://./static/js/chunk-eff51980.34f7a034.js:28:54912)\n at x (app://./static/js/chunk-eff51980.34f7a034.js:10:3532)\n at k.next (app://./static/js/chunk-eff51980.34f7a034.js:10:3829)\n at app://./static/js/chunk-eff51980.34f7a034.js:10:4298\n at new Promise (<anonymous>)\n at F (app://./static/js/chunk-eff51980.34f7a034.js:10:4190)\n at B (app://./static/js/chunk-eff51980.34f7a034.js:10:4330)"
  }
  ],
  "handled": false
 }
```

#### 3016
For error code 3016, you can see two types of error messages.
```
shaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3016,
  "data": [
  3,
  null,
  "PIPELINE_ERROR_DECODE: DecryptingVideoDecoder: decode error"
  ],
  "handled": false
 }
```

```
shaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3016,
  "data": [
  3,
  null,
  "PIPELINE_ERROR_DECODE: DecryptingDemuxerStream: decrypt error 3"
  ],
  "handled": false
 }
```

#### 6008

```
shaka.util.Error {
  "severity": 2,
  "category": 6,
  "code": 6008,
  "data": [
  "Failed to execute 'update' on 'MediaKeySession': Operation aborted. (1000002)"
  ],
  "handled": false
 }
```

**Comment by TheModMaker** [comment]
You are getting decryption and decoding errors.  This is likely caused by the browser no being able to play the content.  For encrypted content, this may be the license server returning the wrong keys.  Otherwise, this is probably caused by those users having problems with their hardware decoders or using different browsers/versions.

3015 and 3016 are basically the same error.  Both are caused by the browser being unable to play the media content.

6008 is [LICENSE_RESPONSE_REJECTED](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6008), which means your license server or proxy returned invalid data that the browser rejected.  Make sure to check out our [license wrapping tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-wrapping.html) if you need to process the response before giving it to us.

Also, you should check the order of the errors you get.  One error is likely to cause others so you should focus on the first one.
