### ISSUE TITLE
Widevine protected content, test vector from dashif  / CableLabs fails to play

### ISSUE THREAD

**Issue by prasadkhambete** [google/shaka-player#320]
DASH Industry Forum has some test vectors for Widevine protected content that are useful for
testing widevine support. These play OK using their reference player at : 
http://dashif.org/reference/players/javascript/v2.0.0/samples/dash-if-reference-player/index.html

The following mpd fails to play using the Shaka Player and displays error 5002  (screenshot attached): 
http://html5.cablelabs.com:8100/cenc/wv/dash.mpd

The license server URL is : 
https://html5.cablelabs.com:8025/

Tested with Shaka Player v1.9.9-alpha

![shakav1 9 9-alpha-error-cablelabs](https://cloud.githubusercontent.com/assets/6602223/14218223/b7f01f38-f807-11e5-8e0f-c672774a01f2.png)

**Comment by joeyparrish** [comment]
I see two issues here:

1. StreamingEngine calculates a 42 drift for the audio stream and subsequently makes a lookup for -42ms in the index.  This should be clamped to 0.
2. The buffering algorithm is exact.  It sees that we've buffered no audio ahead of t=0 (since buffered audio starts at t=42ms), and never leaves the buffering state.  Browser media stacks have a gap tolerance built-in, and so should our buffering algorithm.

**Comment by joeyparrish** [comment]
@prasadkhambete, please try again with the latest sources.  Thanks!
