### ISSUE TITLE
Failed to run the tests in the browser

### ISSUE THREAD

**Issue by sradhanjan** [google/shaka-player#3215]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
2.5.20

**Can you reproduce the issue with the latest code from `master`?**
YES

**What did you do?**

I have cloned the repo and ran " ./build/test.py --browsers Chrome " in the shaka-player directory

**What did you expect to happen?**
program will compile successfully 

**What actually happened?**

![image](https://user-images.githubusercontent.com/56840012/111025142-655b0200-8408-11eb-8e46-ad52aa71d6bb.png)

I have tried the same thing with other browsers also but facing the same problem

**Comment by surajkumar-sk** [comment]
@sradhanjan Does all the browsers stops at the same test that is 1534 of 2090 .

**Comment by sradhanjan** [comment]
@surajkumar-sk this is what I am facing with other browsers

Firefox

![image](https://user-images.githubusercontent.com/56840012/111031441-97328f80-842d-11eb-9ee5-23ba7df26e61.png)

Edge

![image](https://user-images.githubusercontent.com/56840012/111031721-ed540280-842e-11eb-879c-2ff0a5028d57.png)

**Comment by surajkumar-sk** [comment]
@sradhanjan Seems like firefox version 38 doesn't support MediaSource . its browser fault nothing can be done , we need to use different browser . or update firefox for latest version and check if that version supports MediaSource . i think the latest version of firefox does support MediaSource . so try updating it .

for edge it seems like karma is not able to find the edge browser . Is edge browser installed in you computer .

try above things or run the test again in chrome and post a screenshot again . try staying on the cmd window while the tests are running instead of using other applications .

I am not able to reproduce the error . the test runs fine for me on windows 8.1 chrome browser .

**Comment by sradhanjan** [comment]
@surajkumar-sk it seems like your advice was successful

![image](https://user-images.githubusercontent.com/56840012/111034674-c270ab00-843c-11eb-8016-c69046779d5c.png)

**Comment by sradhanjan** [comment]
@surajkumar-sk It seems like your advice was successful, I stayed in cmd while running the tests

![image](https://user-images.githubusercontent.com/56840012/111034732-02379280-843d-11eb-92b0-c582a31bb76f.png)

**Comment by surajkumar-sk** [comment]
@sradhanjan Glad to help. @joeyparrish this issue has been solved and can be closed.
