### ISSUE TITLE
Playback stalls during DASH period transitions

### ISSUE THREAD

**Issue by jennyzhua** [google/shaka-player#3230]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.8

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**What browser and OS are you using?**
Chrome 88.0.4324.192 (Official Build) (x86_64) on Mac OS

**What are the manifest and license server URIs?**
Sent in email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default demo app configurations.

**What did you do?**
Load and play the manifest

**What did you expect to happen?**
Playback transitions from one period to the next smoothly.

**What actually happened?**
Playback stalls after playing the first period.

**Comment by TheModMaker** [comment]
In the second Period, you use the same content as the first.  But in this case, you use `presentationTimeOffset` to adjust the media times backwards.  Since the media already is at 0, you make all the times in the second Period negative, so the segments appear at the wrong times and we don't have anything buffered.  If you remove that attribute, it should work.

**Comment by TheModMaker** [comment]
Ok, I forgot you can use Period duration to chop off part of a `<SegmentBase>`.  When I see `<SegmentBase>` I assume you're using the whole file.  The problem is that as part of manifest parsing, the second Period has a bunch of references that we evict since they appear in the first Period (since you use the same file, but shifted back).  This messes with the index calculation since we think segment 0 was evicted already.

**Comment by asomasundaram** [comment]
When will the fix be released to what version of the Shaka player
