### ISSUE TITLE
Downloading terminates on refreshing the page

### ISSUE THREAD

**Issue by dhruvil-shah** [google/shaka-player#3251]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v3.0.10

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo

**What browser and OS are you using?**
Chrome-Windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What did you do?**
I started downloading the video and refreshed the page.

**What did you expect to happen?**
Downloading to be continued

**What actually happened?**
Downloading gets terminated

**Describe the solution you'd like**
1)We can give an alert while user refresh the page during downloading that it can stop the current progess.
2)We can provide a cancel button as soon as downloading starts and then if user clicks on cancel then just refreshing page will cancel downloading. (Not a good suggestion but still can convert bug to feature)

**Additional context**

Download starts
![image](https://user-images.githubusercontent.com/67452891/111731791-36c2a880-889a-11eb-92f4-f761b0be4f89.png)
After Refreshing
![image](https://user-images.githubusercontent.com/67452891/111731832-4b9f3c00-889a-11eb-91cb-014b0f573d82.png)

**Comment by joeyparrish** [comment]
The solution to this will be "background fetch" support: #879

So long as content downloads happen in the foreground, in the page itself, reloading or navigating away will necessarily stop that process.

Your suggestion could be a reasonable workaround, to allow the user to cancel the page navigation if it's accidental.  But I believe that would be best at the app level, rather than putting an alert in the library.  My instinct is that apps should really have control over that high-level user experience.

**Comment by dhruvil-shah** [comment]
Thank you sir for the information and got the point about your suggestion.
