### ISSUE TITLE
Change in ABR Manager

### ISSUE THREAD

**Issue by aditmehta9** [google/shaka-player#3286]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.10

**Please ask your question**
Is it ok to make a change in the extern/shaka/abr_manager file to fix the bug [#3262](https://github.com/google/shaka-player/issues/3262) and the change is in the [PR](https://github.com/google/shaka-player/pull/3285)

**Comment by TheModMaker** [comment]
I didn't mean you need to ask for permission, we should discuss design and why this change is needed.  Anything in the plugin interfaces can be replaced by the app and implemented themselves.  This means an app can write their own ABR handling and replace it.  We need to handle reverse-compatibility and think about how existing apps will update their code for new requirements.  This also means that if an app has their own ABR handling, they'll need to implement your fix too or they'll still see the old behavior.

Here are some questions to think about with plugin changes:

What changes would you like to make?  Why can't you do it without API changes?  How will you handle backwards-compatibility?  Will old plugins need to update to include this or can they still work?  What extra work would existing plugins need to do to implement this new API?  Would that work be common enough that we should handle it ourselves instead of the plugin?

**Comment by joeyparrish** [comment]
It seems like the underlying bug should maybe be handled by someone on the team who understands the nuances of the API.  I would like to propose that we close this issue, and the associated PR, and that the bug be assigned to a Shaka Player team member.  @aditmehta9, would that be okay with you?

**Comment by aditmehta9** [comment]
Yes, sir @TheModMaker I agree. To fix the bug (Short Description Resolution changes whenever the audio is changed resolution is set to max. possible resolution) now that happens because this.player.selectAudioLanguage is executed from ui/audio_language_selection.js which then calls this.chooseVariantAndSwitch_() in the player file which calls chooseVariant_ in which this.abrManager_.chooseVariant is called which gives us the track of all the available tracks, which will meet the restriction. Now when we call this.player.selectAudioLanguage we need to pass the correct track.height through all these functions so in simple_abr_manager we can return that track. Now in this process, we need to pass height through chooseVariant also so we have to make changes in extern/shaka. Apart from this in /dist/shaka-player.ui.externs.js and /dist/shaka-player.ui.debug.externs.js we need to add 3rd optional parameter for selectaudiolanguage

**Comment by aditmehta9** [comment]
> It seems like the underlying bug should maybe be handled by someone on the team who understands the nuances of the API. I would like to propose that we close this issue, and the associated PR, and that the bug be assigned to a Shaka Player team member. @aditmehta9, would that be okay with you?

I am okay with that but I just wanted to say this change in API fixes the bug.
