### ISSUE TITLE
[1.6.x] Video stops after reach large streamBufferSize

### ISSUE THREAD

**Issue by mctep** [google/shaka-player#333]
Hello! Thank you for your great job!

When I set large `streamBufferSize` (e.g. `4 * 60`) `buffering` of `video` element eventually stops updates and freezes on some fixed value. I have debugged shaka sources and find out that `sourceBuffer` for video stops buffering, but audio buffer updates normally.

If I use default `streamBufferSize` it works perfectly.

I use default adaptation settings.
`"audio/mp4; codecs="mp4a.40.2""`
`"video/mp4; codecs="avc1.4D401E""`

**Comment by mctep** [comment]
There are error thrown after fetch next video segment:
```

DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.
    at Error (native)
    at shaka.media.SourceBufferManager.append_ (http://localhost:8080/lib/media/source_buffer_manager.js:538:24)
    at .<anonymous> (http://localhost:8080/lib/media/source_buffer_manager.js:306:22)
    at shaka.util.Task.startNextStage_ (http://localhost:8080/lib/util/task.js:146:31)
    at .<anonymous> (http://localhost:8080/lib/util/task.js:176:16)
```

**Comment by joeyparrish** [comment]
Yes, there is a limit to what the browser can handle.  It varies by browser, and may vary by platform as well.  There is no API in JavaScript to query this limit, so it will always be possible for an application to set a buffering goal that is too high.

There is a particular exception that browsers are supposed to throw when this happens, and we have plans in v2 to catch and handle it.  (See #258.)  The eventual behavior will be to automatically reduce the buffering goal to something slightly less than what the browser has already buffered.

Unfortunately, there are architectural problems in v1 that make this difficult, so that feature will only be available in v2.  In the mean time, you should set your buffering goal to something smaller than 4 minutes.

It's also worth noting that the browser's limit is generally in terms of bytes, but our buffering goal is terms of time.  You can fit many more seconds of low-bitrate content into the browser's buffer than high-bitrate content.  HD will require a lower buffering goal than SD, and UHD will require a lower goal than HD.  Embedded devices will generally be more limited than desktops.

Does that help?

**Comment by mctep** [comment]
Thank you! Yes, it helps. I understand the problem. I'll not use large buffer size.

Also I have another question.
When I tried to figure out the problem, I found a special behaviour of `sourceBuffer`. It have start buffer position at `0` initially. Some time later the start position begin increase for clearing buffer. Is it behaviour standard API of Media Source Extension or it makes shaka player? I did not find any code in shaka that remove the start of `sourceBuffer` with default playback.

**Comment by joeyparrish** [comment]
In v1, Shaka does not remove old data from the buffer.  The browser's MediaSource implementation will evict old data as it sees fit to meet an internal limit that is not exposed.

In v2, Shaka will remove old data from buffer based on the player's configuration (`streaming.bufferBehind`).  It does this because in some cases and on some platforms, the automatic eviction logic in MediaSource implementations can't be relied on to keep memory usage down.  (See #247.)

**Comment by mctep** [comment]
Thank you for your detailed answers! It helps me.
