### ISSUE TITLE
dash video stream, How to skip video stream error clips，Continue to play the next clip

### ISSUE THREAD

**Issue by juzhiqiang** [google/shaka-player#3355]
video require has been in  `pengind` status , how do I set a timeout to skip video clips
![image](https://user-images.githubusercontent.com/25214312/115495074-6c8fee00-a299-11eb-8db1-f365250e0115.png)

**Comment by theodab** [comment]
You can change the timeout time using the `retryParameters` configurations (see [our documentation](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-network-and-buffering-config.html)).
For example, if you wanted to give a timeout of 10 seconds to segment requests, rather than the default value of 30 seconds, you could do:
```js
player.configure('streaming.retryParameters.timeout', 10000);
```
Then you could listen for errors with the error code `shaka.util.Error.Code.TIMEOUT` (1003) on the player, to know when the player has timed out trying to download something.

Does this help?
