### ISSUE TITLE
How Shaka player detects DRM capability of device and filter unsupported tracks

### ISSUE THREAD

**Issue by krackjack234** [google/shaka-player#3356]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.10 

**Please ask your question**
We are using shaka player to play widevine drm content. We see that on devices which supports only L3 widevine, shaka player is able to filter the tracks (e.g. 1080p) out automatically. When we play on L1 widevine enabled devices, all the tracks are appearing.

We wanted to check how shaka player is able to detect the drm capability of the browser/device and where in code the player is filtering out the unsupported tracks?

**Comment by TheModMaker** [comment]
The manifest contains the key IDs used for a stream.  Then we can look at the key statuses to see which keys are given and usable and filter out any tracks not allowed.  The browser reports which keys we have and whether they can be used.  The high quality tracks are marked as needing L1, so the browser marks these as unusable.

**Comment by krackjack234** [comment]
_"The browser reports which keys we have and whether they can be used"_ : Can you please help us how browser provides this information to detect support for L1 and L3 widevine license?

**Comment by TheModMaker** [comment]
We use the [Encrypted Media Extensions](https://www.w3.org/TR/encrypted-media/) API to handle the licenses.  The license response has requirements in it for what it can be played on.  When the browser handles the license, it sets the key status based on these requirements.  We use [session.keyStatuses](https://www.w3.org/TR/encrypted-media/#dom-mediakeysession-keystatuses) to check what the key status is; any keys with [output-restricted](https://www.w3.org/TR/encrypted-media/#idl-def-MediaKeyStatus.output-restricted) mean we can't use the key because the device doesn't meet the requirements.

**Comment by krackjack234** [comment]
Thanks a lot. This can be closed.
