### ISSUE TITLE
Play webm video with ClearKey DRM 

### ISSUE THREAD

**Issue by darind** [google/shaka-player#3366]
I have a `video/webm;codecs=vp9` that I have encrypted with a hardcoded key using [webm-encrypt](https://github.com/austinleroy/webm-encrypt).

I can successfully decrypt and play the video using the following:

```html
<video preload="auto" controls crossorigin>
    <source src="https://downloads.getfiddler.cc/foo/video_a_encrypted.webm" type="video/webm;codeocs=vp9">
</video>
```

```javascript
var video = document.querySelector('video');

// This is the key I used to encrypt the video
var KEY = new Uint8Array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 ]);

var config = [{
    initDataTypes: ['webm'],
    videoCapabilities: [{
        contentType: 'video/webm;codecs=vp9'
    }]
}];

video.addEventListener('encrypted', handleEncrypted, false);

navigator.requestMediaKeySystemAccess('org.w3.clearkey', config).then(function(keySystemAccess) {
    return keySystemAccess.createMediaKeys();
}).then(function(createdMediaKeys) {
    return video.setMediaKeys(createdMediaKeys);
}).catch(function(error) {
    console.error('Failed to set up MediaKeys', error);
});

function handleEncrypted(event) {
    var session = video.mediaKeys.createSession();
    session.addEventListener('message', handleMessage, false);
    session.generateRequest(event.initDataType, event.initData).catch(function(error) {
        console.error('Failed to generate a license request', error);
    });
}

function handleMessage(event) {
    var license = generateLicense(event.message);

    var session = event.target;
    session.update(license).catch(function(error) {
        console.error('Failed to update the session', error);
    });
}

function toBase64(u8arr) {
    return btoa(String.fromCharCode.apply(null, u8arr)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=*$/, '');
}

function generateLicense(message) {
    var request = JSON.parse(new TextDecoder().decode(message));

    console.assert(request.kids.length === 1);

    // This is the content of the request object for this specific video:
    // {"kids":["rKvaPzLKQkS-gx0Aor9ong"],"type":"temporary"}

    var keyObj = {
        kty: 'oct',
        alg: 'A128KW',
        kid: request.kids[0],
        k: toBase64(KEY)
    };

    return new TextEncoder().encode(JSON.stringify({ keys: [keyObj] }));
}
```

Unfortunately since this code doesn't use MSE, I cannot play this video in Firefox (the `encrypted` event is never raised).

So I am wondering if I can use Shaka Player to achieve that. Here's what I tried but I cannot make the ClearKey to work:

```html
<script src="https://cdn.jsdelivr.net/npm/shaka-player@3.0.10/dist/shaka-player.compiled.min.js"></script>
<video preload="auto" controls crossorigin></video>
```

```javascript
shaka.polyfill.installAll();

const video = document.querySelector('video');
const player = new shaka.Player(video);
player.configure({
    drm: {
        clearKeys: {
            // I am not sure how the keyId must be specified here and how do I retrieve it
            'rKvaPzLKQkS-gx0Aor9ong': '0102030405060708090A0B0C0D0E0F10'
        }
    }
});

window.player = player;

player.load('https://downloads.getfiddler.cc/foo/video_a_encrypted.webm');
```

When I try to run this, chrome doesn't even make a request to download the video but throws the following error:

```
{"severity":2,"category":6,"code":6001,"data":[],"handled":false}
```

So is it possible to configure ClearKey DRM for this kind of video?

**Comment by joeyparrish** [comment]
It sounds like it should be possible to play this file in Shaka, but we're not using MSE in this configuration.  MSE is only used for DASH & HLS, but not for single-file WebM or MP4.  For those, we set `src=` on the video element, just as you do in your sample app.

What is needed for MSE is fragmented content, which we can fetch and append one segment at a time, and a way to map the individual segments (such as a DASH manifest or HLS playlist).  I don't know if your WebM file is already fragmented or not, but it certainly does not have the metadata we need to play it via MSE.

You could use something like [Shaka Streamer](https://github.com/google/shaka-streamer#readme) to create a DASH or HLS version of your content.  Would that be helpful?

**Comment by darind** [comment]
The video content that I need to play is recorded by a Google Chrome plugin using [RecordRTC](https://github.com/muaz-khan/RecordRTC) (based on WebRTC). It represents a capturing of the current chrome tab. 

It seems that WebRTC in Chrome supports only limited video containers and codecs and in order to produce DASH or HLS I will need to do some post processing which I currently cannot do. One of the reasons why I cannot do any server side post processing is because I need end-to-end encryption of the video file. A user password is provided when capturing the tab activity and this same password must be used to play the video in another browser (The video file must be uploaded encrypted to the server). So basically I am constrained to what a browser can offer to capture and play a video :-)

**Comment by gregmsanderson** [comment]
Maybe using this? Just found it. Looks neat. Browser-side post-processing. FFMPEG can turn a webm/mp4 into HLS.

https://github.com/ffmpegwasm/ffmpeg.wasm

**Comment by joeyparrish** [comment]
You know, there's no reason you shouldn't be able to play ClearKey + WebM in Chrome, Firefox, and probably Edge these days (since it moved to Chromium).

I found some issues in the way we connect ClearKey data to src= inputs.  I will soon have a fix in review that will allow you to do this:

```js
player.configure('drm.clearKeys', {'HEX_KEY_ID': 'HEY_KEY'});
player.load(
    'path/to/foo.webm',  // URL
    0,  // start time
    'video/webm; codecs="vp9"');  // MIME type
```

In my experiment today, if we pass the MIME type and codecs from Player to DrmEngine properly, I'm able to initialize ClearKey for you with WebM, through Shaka, without MSE.  (I don't know your key, though, so you'll still have to take care of the ClearKey configuration part.)

**Comment by darind** [comment]
@gregmsanderson, thanks for the pointer. I am aware of the ffmpeg WASM component but unfortunately its license is a bit restrictive for our product and we cannot use it.

@joeyparrish, that's very good news. I would be happy if you are able to support this directly in the player. Although I don't quite understand technically how that would work in Firefox if you don't use MSE? Also I don't understand the difference between `HEX_KEY_ID` and `HEX_KEY`. When I encrypt the webm video, I only provide a [ContentEncKeyID](https://matroska.org/technical/elements.html#ContentEncKeyID). I suppose this corresponds to the `HEX_KEY_ID` but what about `HEX_KEY`? In the sample code I showed (using EME), I provide the value of the key, while the id seems to be some temporary generated:

```
var keyObj = {
    kty: 'oct',
    alg: 'A128KW',
    kid: request.kids[0],
    k: toBase64(KEY)
};
```

**Comment by joeyparrish** [comment]
> I don't quite understand technically how that would work in Firefox if you don't use MSE?

I am not familiar with the status of src= + WebM + EME in Firefox.  But if you don't get encrypted events, I would consider it a Firefox bug.  We can help you file one if needed: https://bugzilla.mozilla.org/

> I don't understand the difference between HEX_KEY_ID and HEX_KEY

Every key in modern DRM has an ID, which is separate from the actual symmetric encryption key.  Keys are always 128 bits, because encryption is done with some particular cipher mode of AES-128.  Key IDs are generally 128 bits as well, though I'm not certain if this is required by containers or DRM systems explicitly.

In Shaka Player's ClearKey config API, we accept these keys and key IDs as hex-encoded strings.  Sometimes you will see an API or tool that wants base64 encoding instead, but we settled on hex a long time ago for Shaka Player.

> When I encrypt the webm video, I only provide a ContentEncKeyID. I suppose this corresponds to the HEX_KEY_ID but what about HEX_KEY?

Yes, from what I can tell from the matroska docs, that is the same as the key ID.  So you'll need that in hex format to provide to Shaka Player.

You'll also need the encryption key itself.  I notice in your original code, you had this:

```js
var KEY = new Uint8Array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 ]);
```

You can convert that to hex in any Shaka-based app with:

```js
const HEX_KEY = shaka.util.Uint8ArrayUtils.toHex(KEY);
```

> the id seems to be some temporary generated:  ... `kid: request.kids[0],`

No, it's not generated.  The key ID is extracted from the content by the browser, and you get it in the ClearKey license request format here.

Earlier you said that you already know the key ID because you provide a ContentEncKeyId, but looking at [the tool you linked to](https://github.com/austinleroy/webm-encrypt), it seems that it only accepts a content key, not an ID.  [Digging further into the source](https://github.com/austinleroy/webm-encrypt/blob/d36a4db433b506b184f4fe505cd01b9fcf3161d5/src/WebmStreamEncryptor.ts#L156-L158) of that tool, I see that it is generating a random ID each time:

```js
        let encKeyId = EbmlTagFactory.create(EbmlTagId.ContentEncKeyID);
        encKeyId.data = crypto.randomBytes(16);
        encryption.Children.push(encKeyId);
```

You may want to choose another tool that lets you specify your key IDs, or you may want to find a tool that will show you the key IDs in your newly-encoded WebM files.

If you really need to be able to play them in Shaka Player without knowing the key IDs in advance, there is a way to handle everything client-side with a hard-coded key only, but it's more convoluted.  I would expect that it would make more sense to know your content's metadata (such as key ID) in advance.  Let me know if you need me to go into details on a client-side solution, though.

**Comment by darind** [comment]
@joeyparrish, thank you very much for the detailed explanation. It all makes sense and now I understand the concept. I will be looking forward to your PR so that I can try the sample code you provided with my encrypted webm files.

As far as the tool I am using for encryption, I will tweak it so that I can specify the keyId as input instead of generating a random one each time. This way I will have a deterministic configuration input for the player DRM section.

**Comment by joeyparrish** [comment]
There's no PR.  We (the Shaka team at Google) reviewed the change internally and merged it.  It was f0f4109, which closed this issue.  You can check out the latest code from GitHub and try it out.  I was able to try the content you linked, but without your key & key ID, I couldn't actually play it.  Let us know how it goes!

**Comment by darind** [comment]
@joeyparrish, I was able to play an encrypted video in Chromium based browsers and Opera but in Firefox doesn't work. It shows "Video can't be played because the file is corrupt".

Here is the code I used:

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Encrypted video test</title>
</head>

<body>
    <video
        controls
        crossorigin
        preload="auto"
        width="640"
        height="264">
    </video>
    <script src="scripts/shaka-player.ui.js"></script>
    <script>
        async function initPlayer() {
            const video = document.querySelector('video');

            const player = new shaka.Player(video);
            player.configure('drm.clearKeys', {
                '15A924B6EC3F485E69D500715D870B54': '0102030405060708090A0B0C0D0E0F10'
            });

            window.player = player;

            player.addEventListener('error', error => {
                console.error(error.detail);
            });

            await player.load('video_b_encrypted.webm', 0, 'video/webm; codecs="vp9"');
        }

        shaka.polyfill.installAll();
        initPlayer();
    </script>
</body>

</html>
```

And here's the corresponding encrypted video file:

[video_b_encrypted.webm.zip](https://github.com/google/shaka-player/files/6439360/video_b_encrypted.webm.zip)

**Comment by joeyparrish** [comment]
The nightly build of our demo (https://nightly-dot-shaka-player-demo.appspot.com/) has been updated to offer a MIME type and extra config fields.  With this, you can test your encrypted WebM content with ClearKey in the demo app:

1. Open nightly demo: https://nightly-dot-shaka-player-demo.appspot.com/
2. Click "Custom Content" tab
3. Click the floating "plus" button in the bottom-right to add custom content
4. Enter the WebM URL into the "Manifest URL" field: https://downloads.getfiddler.cc/foo/video_a_encrypted.webm
5. Enter the full MIME type with codecs into the newly-added "MIME type" field: `video/webm; codecs="vp9"`
6. Click on the newly-added "Extra Config" tab within the asset dialog
7. Enter the following config, with your own key ID and key in the dictionary:

```json
{
  "drm": {
    "clearKeys": {
      "deadbeefdeadbeefdeadbeefdeadbeef": "deadbeefdeadbeefdeadbeefdeadbeef"
    }
  }
}
```

8. Click "Save"
9. Click "Play" on the new custom asset

We hope this helps!

**Comment by joeyparrish** [comment]
> So I suppose that at the moment the only way to make it work in Firefox is by using MSE.

It sounds like that's the case.  I suggest filing a bug against Mozilla to see if they are interested in fixing this.  See https://bugzilla.mozilla.org/ .  If you file an issue and copy the link to your issue here, I can try to bring it to the attention of the right people at Firefox.

**Comment by darind** [comment]
@joeyparrish, thanks, I have submitted a bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1710128
