### ISSUE TITLE
Player stalls when seeking on LIVE edge

### ISSUE THREAD

**Issue by llooz** [google/shaka-player#3393]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=it-IT;textlang=it-IT;uilang=it-IT;panel=CUSTOM%20CONTENT;build=uncompiled
Content URL sent at shaka-player-issues@google.com

**What version of Shaka Player are you using?**
v3.1.0-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

**What did you do?**

1. play content
2. wait for content starting to play
3. click on the negative offset to seek to live edge

**What did you expect to happen?**
Player buffering for some time and then start playing again.

**What actually happened?**

Player stalls and from Network I see that fetches "manifest.mpd" continuosly without fetching segments.

**Comment by defnull** [comment]
I guess this happens because a click jumps to live edge, but `streaming.bufferingGoal` defaults to 10 seconds, which means shaka wants to buffer until the goal is reached. I reduced `streaming.bufferingGoal` to 4 seconds to verify and now shaka stalls until `-00:04` is reached, then continues playing normally.

The same happens when pausing a live stream for too long. After pressing play, shaka notices it has fallen out of the live window, jumps to live edge, and buffers for 4 seconds (in my case).

This also means that `PresentationTimeTracker` will never display `Live` during normal live playback if `bufferingGoal` is greater than one second, which is the hard-coded leeway allowed by `PresentationTimeTracker` (line 85).

**Comment by joeyparrish** [comment]
@llooz, I get "HTTP 403 access denied" when I try to play the content you sent us privately.  Can you please enable access or provide us with a means to authenticate for this content?

@defnull, you're close, but `streaming.bufferingGoal` is not how much we need to start playback.  It's how far ahead we attempt to get before we stop fetching new segments, and does not influence startup or buffering at the live edge.  If the distance to the live edge or VOD duration is less than `bufferingGoal`, it doesn't do anything.

The `streaming.rebufferingGoal` setting is what we need to start or resume playback.  In DASH, we also consider the manifest's `minBufferTime` attribute, which you can disable with `manifest.dash.ignoreMinBufferTime`.

You should also be aware that there are effectively two different live edge concepts: one for buffering (availability), and one for presentation to the user.  The DASH "availability window" means "what's on the server".  This is the "true" live edge, and we can buffer up until that point.  What we show the user as the live edge, though, is offset from this by the "presentation delay".  DASH has a `suggestedPresentationDelay` attribute to tell the player how far these two should be apart, and this is the maximum we can buffer ahead of what the user is seeing.  If it's too small, the player can never achieve "live" in the UI.  If it's too large, buffering is improved at the cost of increased delay of the live event from camera to screen.

You can use `manifest.defaultPresentationDelay` to set the presentation delay used when there isn't one specified in a DASH manifest, and you can use `manifest.dash.ignoreSuggestedPresentationDelay` to ignore the manifest's presentation delay so that only `manifest.defaultPresentationDelay` will be used.

**Comment by defnull** [comment]
Thanks for the detailed explanation. In my tests, the manifests states `suggestedPresentationDelay="PT2S"` and `minBufferTime="PT4.0S"`. This is what ffmpeg outputs for a 2-second segment size. My shaka config sets `streaming.bufferingGoal: 4` and leaves the other values to their defaults.

If I understand you correctly, then shaka should refuse to play until at least 4 seconds are buffered (as required by `manifest.minBufferTime=4s`, which overrules the smaller `streaming.rebufferingGoal` default of 2 seconds). Clicking on the `PresentationTimeTracker` component should jump to the presentation live edge, which is 2 seconds behind the availability live edge (honoring `manifest.suggestedPresentationDelay=2s`). This is too far, and we need 4 seconds buffered minimum.

If the `PresentationTimeTracker` display is relative to presentation live edge, the player should be able to start playing at `-00:02`, because 2 seconds behind presentation live edge means 4 seconds behind availability live edge which is enough to satisfy `minBufferTime` (given a fast internet connection and nearly instant segment downloads). But there is also `minimumUpdatePeriod="PT2S"` in the manifest, which means that both live-edges jump in 2-second steps. Is this the reason I see the player buffering until `-00:03` or `-00:04` is displayed, instead of `-00:02`?

(Sorry for hijacking this issue, I realize that I am asking questions better suited for a mailing list).

To get on-topic again: If the presentation live edge cannot be possibly satisfied because the suggested presentation delay is larger than the minimum buffer size, then perhaps `PresentationTimeTracker` should be made aware of that and instead work relatively to the satisfiable live edge instead of the suggested one? I'm not sure if this is @llooz problem, though. If not, it might be worth discussing in a new issue?

**Comment by joeyparrish** [comment]
> Clicking on the PresentationTimeTracker component should jump to the presentation live edge, which is 2 seconds behind the availability live edge (honoring manifest.suggestedPresentationDelay=2s). This is too far, and we need 4 seconds buffered minimum.

That appears to be true.  I thought that we would see "buffered to the live edge" as sufficient without meeting the `rebufferingGoal` / `minBufferTime` requirement, but that appears not to be the case.  `shaka.media.BufferingObserver` is completely disconnected from the knowledge that we've hit the live edge (`shaka.media.StreamingEngine`).  I may have been remembering the way things were in an older version, back when `StreamingEngine` was more complex (if you can believe that).

> But there is also minimumUpdatePeriod="PT2S" in the manifest, which means that both live-edges increment in 2-second steps. Is this the reason I see the player buffering until -00:03 or -00:04 is displayed, instead of -00:02?

That sounds right.  If the manifest uses `SegmentTemplate@duration` (fixed duration segments), then the update period will not matter.  But if it uses `SegmentTimeline` (each segment described explicitly), then the update period matters.  Without an update, we don't have a description of the segment, and we can't fetch it.  (As the code stands today.  Maybe some predictive fetching would help, but that would be a feature request.)

> perhaps PresentationTimeTracker should be made aware of that and instead work relatively to the satisfiable live edge instead of the suggested one?

That might make sense.  The API that drives this part of our provided UI, as well application-specific custom UIs, is `player.seekRange()`.  This, in turn, is driven by `shaka.media.PresentationTimeline`.  So the adjustments to the live edge would need to be made in `PresentationTimeline`.  It may be as simple as using the max of `presentationDelay` and `rebufferingGoal` / `minBufferTime`, but as `rebufferingGoal` can be dynamically adjusted by the app during a playback session, this would have to be adjusted any time the player config changes.

Interested in sending a PR?

**Comment by joeyparrish** [comment]
@llooz, sorry for the distracting side-conversation with @defnull.  If you can provide us access to your content (still getting HTTP 403), then we can test to see if @defnull's suggestions would solve your issue.

Alternately, you can try setting a higher presentation delay:

```js
player.configure({
  manifest: {
    defaultPresentationDelay: ENTER_DELAY_HERE,
    dash: {
      ignoreSuggestedPresentationDelay: true,
    },
  },
});
```

Or you can set a lower rebuffering goal:

```js
player.configure({
  manifest: {
    dash: {
      ignoreMinBufferTime: true,
    },
  },
  streaming: {
    rebufferingGoal: ENTER_REBUFFERING_GOAL_HERE,
  },
});
```

Or both.  @llooz, please let us know if these suggestions help, and please let us know when/how we can access the content.  Thanks!

**Comment by llooz** [comment]
@joeyparrish sorry for the delayed response, unfortunately the content has some geoblocking restriction and can be accessed only from Italy
I will try to check next week with the content provider if there is a way to get an url without restrictions for testing purposes

**Comment by joeyparrish** [comment]
We can VPN through Italy if that is all that is required.  Thanks!

**Comment by TheModMaker** [comment]
The problem is that when we can't find the segment, `getIteratorForTime` returns an iterator with an index of -1, which causes problems streaming.

**Comment by avelad** [comment]
@llooz The latest release has several changes related to this, it might be worth testing if it has been resolved.

**Comment by joeyparrish** [comment]
@llooz, can you please retest with v3.0.12 or v3.1.1?  This may be resolved now.

**Comment by llooz** [comment]
@joeyparrish @avelad  I've tested again with the same live content on the demo app with v3.1.1. 
When I click on the negative offset it buffers until the offset reaches -0:05 and then plays without stalling forever, so it seems that this issue has been resolved 🥳
