### ISSUE TITLE
video playing from the end of some seconds not playing from start

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/shaka-player#340]
i am playing and tested many links with shaka player but all videos playing from the end of some seconds.

here is the link: http://bsplayer-zohaibghafoor.c9users.io/index.html

**Comment by tdrews** [comment]
If playback starts near the end of the video, the MPD file must be specifying a live presentation.
Can you share your MPD file?

**Comment by ZohaibGhafoor** [comment]
here is one of my mpd files:
https://bsbestsongs.global.ssl.fastly.net/video-data/bollywood/D/Dear-Dad-2016/Dear-Dad-Official-Trailer.mp4/207683_98ecf3e1bda96cb3726ad62d067b5f35/207683.mpd

**Comment by tdrews** [comment]
So, for VOD (static) content, your MPD file should not specify `MPD@availabilityStartTime` or `MPD@timeShiftBufferDepth` (unfortunately the player cannot rely on the MPD's type to determine if a presentation is VOD or live).

We also found an issue with the player: the player was treating certain content as partially VOD and partially live in the demo UI. We'll have patches up soon to correct this issue.

However, you will still need to remove `MPD@timeShiftBufferDepth` from your MPD file since it specifies VOD content.
