### ISSUE TITLE
MPEG-2 TS not working with 3.1 and mux.js

### ISSUE THREAD

**Issue by Benny739** [google/shaka-player#3407]
MPEG-2 TS transmuxing via mux.js is not working in 3.1. 3.0.7 is working fine.

**Comment by joeyparrish** [comment]
Working fine for me: https://shaka-player-demo.appspot.com/demo/#audiolang=de;textlang=de;uilang=de;asset=https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8;panel=ALL_CONTENT;panelData=MP2TS;build=uncompiled

Do you have repro steps for us to follow?  Specific content?  Can you reproduce the issue in our demo?  All of these questions were in the issue template that you deleted.  Next time, please use the template so that we have all the necessary information to investigate your issue.

**Comment by Benny739** [comment]
Sorry for the short bug report, I created 2 codepens:
The codepens are completely identical, one is with 3.0.6 the other with 3.1.

3.0.6 working:
https://codepen.io/benny739/pen/GRomJWE

3.1 not working:
https://codepen.io/benny739/pen/wvJGmJY

It looks like in 3.1 it's throwing error 4032, CONTENT_UNSUPPORTED_BY_BROWSER.

**Comment by joeyparrish** [comment]
Your codepen fails with the same content that works fine in our demo.  Something is different in the codepen, and I'm not sure what.

I tried using both compiled & uncompiled code in our demo, and both work.  So the compiler didn't break anything.

Still investigating.

**Comment by joeyparrish** [comment]
I found the issue.  You need to load mux.min.js _before_ Shaka Player.

This shouldn't be required, though.  So long as muxjs is loaded by the time you call `player.load()`, we would expect everything to work.

The change in behavior occured with the introduction of `shaka.dependencies` in PR #2683.  It was meant to allow apps to inject their own muxjs without loading it globally, but it accidentally created an ordering requirement.

I will see if I can find a simple way to fix it.  In the meantime, please change the order of scripts so that mux.js is loaded before Shaka Player.  This seems to be an effective workaround.
