### ISSUE TITLE
Increase the seek range for 3 hours for live player

### ISSUE THREAD

**Issue by hiren3897** [google/shaka-player#3444]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v3.1.0

**Please ask your question**
Hello,

I want to increase the shaka-range-element shaka-seek-bar range for 3 hours approx(10800 sec) is it possible to do so 

As for default we have approx 898 sec i.e 15 mins.

How can I change or customize it to make it 3hrs seekable? 

Thank you in advance

**Comment by TheModMaker** [comment]
It mostly depends on the manifest.  I assume you're using DASH, since HLS defaults to non-seekable.  For DASH, this is controlled with the `timeShiftBufferDepth` attribute in the manifest.  The best option is to change your encoder to give a longer seek window.  This ensures the content works correctly.

You can override this with the `manifest.availabilityWindowOverride` configuration, but this can cause playback errors depending on your server or manifest.  For example, if the segments no longer exist, you'll get 404 errors trying to play too far in the past.  Also, if the manifest doesn't list those segments, we won't be able to seek back that far since we don't know the segment URLs.

```js
player.configure('manifest.availabilityWindowOverride', 10800);
```

**Comment by hiren3897** [comment]
Hello @TheModMaker 
Thank you for your response I have already tried this and yes you are right it gives me 404 when segments are not available.

I have a question, to have one manifest seekable for 3 hours for example do we need to change some configs in the DASH manifest to make the segments available for 3 hours? 


Thank you in advance :)

**Comment by TheModMaker** [comment]
We don't know which encoder you are using, so you need to look up your encoder settings to see how you can do it.

For the manifest, you need to increase `timeShiftBufferDepth` attribute.  Then  you need to make sure the manifest keeps the segments in the list and the segments remain on the server so long as they are playable.

**Comment by hiren3897** [comment]
Okay @TheModMaker 
I will look after it and I'll ask you if I have any doubts :)

Thank You!
