### ISSUE TITLE
How to get the current rendering quality level + be notified when it changes?

### ISSUE THREAD

**Issue by AradAral** [google/shaka-player#3449]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
3.1.0

**Please ask your question**
I'm in the process of migrating from hls.js to Shaka Player. One rather simple thing that I've been struggling to achieve in Shaka Player is listening to automatic changes in quality level based on `currentTime`; that is, as the video is playing.

Let's say the video starts with the quality level `0`, and then after 2 segments, it automatically switches to `1`. As the video is being played, I'd like to be notified when the 2nd segment ends and the 3rd one begins, since that's when the quality of the video has changed. I'm building a video player and I need to reflect that change in the UI.

To put this a little differently, imagine the video has quality level `0` from 00:00 to 00:20, and quality level `1` from 00:21 to 00:30, I need to somehow get notified when the video playback goes from 00:20 to 00:21, 

In hls.js, this is very straightforward. You could attach an event handler to either the `FRAG_CHANGED` event, or even more specifically the `LEVEL_SWITCHED`  event. And in that event handler you could simply check the value of `hls.currentLevel`. This would be simple in dash.js too. dash.js has a `qualityChangeRendered` event that handles this.

I could find nothing similar in Shaka Player.

**UPDATE:**  I actually just realized that Shaka Player doesn't seem to have a way to **even get** the current quality level, let alone an event for when it changes. Please tell me this is not true!
My question, then, would be the same as [this Stack Overlow question](https://stackoverflow.com/questions/58968045/how-can-we-get-current-rendering-stream-details-in-shaka-player), which was asked about a 1 and a half ago, and still lacks a proper answer.

**What I've tried:**
1. `player.getVariantTracks().find(v => v.active)`
The problem with this is that the `active` track is not the one that's active at `currentTime`. So this doesn't work.

2. `player.getStats().height`
Just like the active track, the information that this method returns isn't based on the current playback position.

**Comment by TheModMaker** [comment]
We only track the currently "selected" track, which is the track that we will download for future segments.  We don't track what we have already buffered.  You can follow #857 for where we'll add a feature for that.  So the track will switch even though the current resolution won't show it since we've buffered old content.

You can detect when the selected track changes with the `adaptation` event.  But again, you won't see the resolution change until we've played through the content that has already been buffered.  There is no event for when the displayed resolution changes.

**Comment by ismena** [comment]
@AradAral Does an [adaptation event](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/shaka.Player.html#.event:AdaptationEvent) work for your purpose?
It's fired when ABR changes tracks.

The docs don't reflect it yet, but we recently added fields for the old and new tracks to the event (can be seen [here](https://github.com/google/shaka-player/blob/master/lib/player.js#L5118) in the current code). 
`event['oldTrack'].width`/`event['oldTrack'].height` (same for newTrack) should give you the resolutions.

Does this help?

**Comment by joeyparrish** [comment]
The events we dispatch are fired when we choose to start fetching something different, rather than when that difference shows up on screen.  We don't track in memory any correspondence between presentation times and which segments/resolutions we buffered.

You can observe a resolution change, however, on the video element.  `video.videoWidth` and `video.videoHeight` attributes (where `video` is your `<video>` element) will tell you the current resolution on screen.

I'll test out [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to see if it will notify you of changes to these properties.

**Comment by joeyparrish** [comment]
I was suspicious that MutationObserver wouldn't help, and I was right.  This doesn't fire on width/height changes:

```js
const mo = new MutationObserver(() => console.log(`${video.videoWidth}x${video.videoHeight}`));
mo.observe(video, {attributes: true, attributeOldValue: true, attributeFilter: ['videoWidth', 'videoHeight']});
```

I believe it's because MutationObserver works on DOM elements only, and videoWidth/videoHeight are only exposed on the JS object, not as DOM attributes.

You could always use a `timeupdate` event to check.  If Shaka were to offer an event for this, it would have to be based on `timeupdate` or polling anyway to observe time changes, so you might as well do this yourself.  This works:

```js
let oldW, oldH;
video.addEventListener('timeupdate', () => {
  if (video.videoWidth != oldW || video.videoHeight != oldH) {
    console.log(`${video.videoWidth}x${video.videoHeight}`);
    oldW = video.videoWidth;
    oldH = video.videoHeight;
  }
});
```

Does this help?

**Comment by AradAral** [comment]
> You could always use a timeupdate event to check.

That's a nice solution.
But correct me if I'm wrong, I think this approach isn't completely reliable since there may be multiple variant tracks with the same width and height but with different bitrates, say.
In such cases, you couldn't definitively infer from the video height/width which track is the one currently playing.

> We only track the currently "selected" track, which is the track that we will download for future segments. We don't track what we have already buffered.

May I ask why? Because honestly, this seems to me to be among the most common requirements. To want to be notified when the video resolution changes so that you can reflect that change in the UI of the video player, say you have a quality menu that the user can choose from, and in that you want the currently-playing quality to be highlighted.
The other big ABR libraries (namely [hls.js](https://github.com/video-dev/hls.js/) and [dash.js](https://github.com/Dash-Industry-Forum/dash.js/)) both support this.
I was almost completely certain that I was missing something obvious. I wasn't expecting to realize that Shaka Player actually lacks this feature.

**Comment by TheModMaker** [comment]
It's  a matter of preference.  Some people may want the UI to show the currently displayed resolution, or some may want to show what will be downloaded in the future.  It may make more sense to show what will be downloaded as it will affect bandwidth the most in the future.  You can follow #857 for the other option.

**Comment by AradAral** [comment]
> Some people may want the UI to show the currently displayed resolution, or some may want to show what will be downloaded in the future.

Please give me one example of a famous video player that does the latter.

**Comment by AradAral** [comment]
Even if there are such examples, there is absolutely no doubt that showing the current quality is definitely much more common.

Wouldn't you agree?

**Comment by TheModMaker** [comment]
> @TheModMaker Could you please give me one example of a well-known video player that does the latter?

YouTube does do this.  It displays the future download rate, not what is displayed.  This is only visible when using "Auto" since it clears the buffer if you manually select.

You can follow  #857 where we'll add that feature.  (also you shouldn't edit your comments since we don't get notifications for that and it is confusing to reply to edited comments)
