### ISSUE TITLE
Play a .ts file using mux.js

### ISSUE THREAD

**Issue by talmelamed** [google/shaka-player#3453]
We've been trying to play a .ts file with mux.js and it seems dot working.
Although if we create a manifest file (m3u8) which direct to a ts file Shaka manages to play it.

We use <script src="https://github.com/videojs/mux.js/releases/latest/download/mux.js"></script> at the top of the html page.
and init the player with muxjs: window.muxjs = muxjs;

I guess it's kind of a flag to use mux.js when getting HLS and can be used also when getiing a .ts file.

**Comment by TheModMaker** [comment]
So is the content playing or not?  You said "not working", but also "manages to play it".  What is the problem here?  If there is an error, what is the error?  What browser are you using?  Can you provide a URL link to the manifest? If the browser supports native TS content (e.g. Safari or Edge), then we'll play it natively instead of repackaging it.

**Comment by talmelamed** [comment]
@joeyparrish Yes, exactly.

**Comment by TheModMaker** [comment]
We don't use mux.js when playing `src=` (direct playback of single file).  This is because we just give the URL to the browser and tell it "play this".  Since we have no control over the network or the playback, we can't transform it as we play.  We also may not be able to download the file and transform it all at once since it may be massive and we can't fit it in memory.  So we only support playing `src=` when the browser supports playing it directly.

**Comment by joeyparrish** [comment]
@talmelamed, does this answer your question?  Sorry we aren't able to help with this.
