### ISSUE TITLE
Is shaka-ui-loaded event a one time dispatch?

### ISSUE THREAD

**Issue by SadiqaliZaveri** [google/shaka-player#3456]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.0 UI Compiled

**Please ask your question**
1. Why does the `shaka-ui-loaded` event not fire again on a new player instance created on the same page?
2. If not the `shaka-ui-loaded` event then which event should one listen for to know the player has loaded along with the UI?

Taking a scenario where multiple videos have to be loaded after an interval. A loader is shown over the player and then removed once this event is fired. The first instance seems to have no such problem. Consecutive player instances created do not fire this event.

I have tried to understand how this works by following the below code but haven't really found anything solid that suggests a one-time initiation.
https://github.com/google/shaka-player/blob/6c528c8f4ae199140d8bc64eac7f5774346e7c6f/ui/ui.js#L324

The code goes something like below
```
/** UI load events */
document.addEventListener('shaka-ui-load-failed', () => {
	console.info('UI elements failed to load')
})

document.addEventListener('shaka-ui-loaded', () => {
	fadeInWebPlayer(videoContainerElement)
	console.info('The video has now been loaded!')
})

/** Use the shaka UI control panel */
const customUI = new ui.Overlay(localPlayer, videoContainerElement,
	videoElement)
```

**Comment by joeyparrish** [comment]
The event fires once, on the _document_, to let you know that the UI _library_ is fully available.  It is not related to any one `Player` instance.

It is common to load scripts with `async` or `defer` attributes, so you may need the event for this reason.  You can use it know when the `shaka` namespace is available globally.

Also, the UI library will search the DOM for `data-shaka-player` and `data-shaka-player-container` attributes, and create `Overlay` and `Player` objects automatically.  If you're using this feature, you may need to wait for the event before accessing `videoElement.ui` to get access to the UI or the underlying `Player` object.

If your application code runs after the Shaka Player library script is fully loaded, and you use the API to create an Overlay explicitly instead of using DOM-based auto-setup, then you may not need the `shaka-ui-loaded` event at all.

The `shaka-ui-load-failed` event is only used if the browser is not supported by Shaka Player.  If you are using the API to explicitly create things (instead of using the DOM-based setup with `data-` attributes), you should call `shaka.Player.isBrowserSupported()` yourself before creating an `Overlay`.

**Comment by SadiqaliZaveri** [comment]
@joeyparrish Thank you for the explanation. I understand it correctly now.

My application code runs after the Shaka Player Library has been fully loaded, so I would not require the event at all.
