### ISSUE TITLE
unable to capture image from live player

### ISSUE THREAD

**Issue by hiren3897** [google/shaka-player#3458]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

yes
**What version of Shaka Player are you using?**
v3.1.0

**Please ask your question**
Hello there,
I am adding a feature in my player to capture an image from the player
I am using a simple methodology for capturing the current image by rendering it on canvas 

```
function snap(video) {
    // Define the size of the rectangle that will be filled (basically the entire element)
    context.fillRect(0, 0, w, h);
    // Grab the image from the video
    context.drawImage(video, 0, 0, w, h);
    console.log(context)
}
```

It works well for the VOD player
but when I try to capture an image from the LIVE player it gives me a blank image!!
Is it because of DRM protection? OR it is not possible to capture images from the live player ?

is it because when is see Video Element src 
      for VOD it starts with ``` src="https://url"```
      for LIVE is starts with ```src="blob:https://url"```?
I don't know what is stopping to capture the image in the live player!!

Is there any way to capture the image from the live player with or without(ignoring) DRM protection ?

if it is possible please let me know. it would be a great help 
Thank you in advance

**Comment by joeyparrish** [comment]
The player has nothing to do with rendering the images, nor with protecting them from capture.

I believe DRM content will be protected from image capture, but it may depend on the DRM vendor or possibly the license policy.

As for VOD vs live, you may be mistaken about the differences in the URL.

`src="https://url"` does not have anything to do with VOD.  This indicates a `src=` playback, which is usually a single file as opposed to DASH or HLS.  This style of play is also used for HLS on Safari in some cases.

`src="blob:https://url"` indicates a DASH or HLS playback using MediaSource.

Either of these styles could be VOD.  On Safari, either could be used for live streams, too.  On other browsers, live streams would always be played with MediaSource using a blob URL.

Also, neither URL style relates to DRM.  DRM playback can be achieved with any type of playback, with `src=` or MediaSource, with VOD or live.

My best guess is that the capture issues are because of DRM.

Does this help?

**Comment by hiren3897** [comment]
Hello @joeyparrish 
Thank you for the quick response.

yes, it helps as it is only because of the DRM protection to the video.

maybe I need to check with the DRM vendor do they allow capturing images or not!

Thank you so much!
I am closing this for now
