### ISSUE TITLE
WebkitMediaKeySession - MEDIA_KEYERR_DOMAIN

### ISSUE THREAD

**Issue by nanandn** [google/shaka-player#3481]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.1

**Please ask your question**

Hi

I am implement the FPS KSM service. When I use the shaka player as the client to test my KSM. I get a key error - code 6 (MEDIA_KEYERR_DOMAIN). I have setup the DRM configuration as mentioned in https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html 

I tried other clients - shaka player, video JS player. All of them give me the same error.

I have tried different playlists, different certificates (developer certificate from apple and production certificate for my company).

I have tried searching for solution all over the web, but I could not find any solution.

Any idea what this error is and how to fix it?

Thanks Anand

**Comment by TheModMaker** [comment]
If you could provide a manifest URL, we may be able to help more.  Since it happens in other players, it is probably a problem with your content.  Are you using an external display or AirPlay?  `MEDIA_KEYERR_DOMAIN` is an error from the browser, so you could just search for that and you may get some hints on what could be wrong.

**Comment by nanandn** [comment]
@TheModMaker I think the problem was with the server certificate (or how it was read).  Once I got the correct certificate, it works.
