### ISSUE TITLE
Decouple Shaka UI from Shaka Player

### ISSUE THREAD

**Issue by shanmugapriyak1788** [google/shaka-player#3488]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
Is it possible to decouple the shaka UI from shaka player? We are building HTML Controls UI library with shaka player UI. Since it is tightly coupled with shaka player, we are unable to bundle with our local player

**Describe the solution you'd like**
Provide a separate bundle for shaka player UI controls that accepts an optional player instance. 

**Describe alternatives you've considered**
We are building a separate UI library and providing it.

**Comment by theodab** [comment]
I don't think that making the player instance optional is the best approach for this. The UI needs to have some sort of coupling to work. Even if we refactored the UI so that the player could be null, a lot of elements would do nothing; the resolution selection wouldn't know what resolutions to display, the seek bar wouldn't know if the presentation is live or not, so on and so forth.

I think the better approach would be to make a new plugin class that is passed to the UI, which encapsulates the points of contact between the UI and the player. For example, it would have an `isLive()` method, and an `isTextTrackVisible()` method, and it would emit various events like `variantchanged` and `trackschanged`. We would have a default one that just acts as a proxy between the UI and Shaka Player, and users could make their own custom ones for their own players.

This would be a significant change to our public interface, however, so it would need to wait for v4.0. It would also make the UI a lot less agile, since if a new UI button needed to access a new value on the player, it would require a breaking change to a plugin interface. And I don't think this is going to be a high priority project, either. No-one else has asked for this, after all.

Honestly, this is something you could do easier than us, since you could just copy and modify our UI code. No need to make a generic solution that can work with any player if your player is the only one it needs to support. I'm not a lawyer, but the Apache License 2.0 does say it allows modification of the original source code.

**Comment by joeyparrish** [comment]
Agreed.  This is an interesting idea, but not a priority for the team and may actually increase the burden of maintaining the library.  There has to be some interface between the UI and the Player, and there is no standard API for players as there is for the media element.  For _our_ UI, that interface is _our_ existing Player API.

I'm going to go so far as to label it "will not implement".  I apologize for any inconvenience this may cause you, but I think it would be disingenuous to keep it on the backlog.  I could be convinced otherwise, but at this time, I don't see this as something we will ever choose to implement.
