### ISSUE TITLE
message: "Shaka Error DRM.LICENSE_RESPONSE_REJECTED()

### ISSUE THREAD

**Issue by bhushanudupa** [google/shaka-player#3503]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Actually this is a duplicate of issue #482 
Since that couldn't help me fix the issue, I'm creating another issue.
**What version of Shaka Player are you using?**
3.0.10

**Please ask your question**
@joeyparrish 
I have been trying to play an audio mpd file which is located in amazon S3 bucket. My configuration in code is as follows.
```
window.player = player;
  player.configure({
    streaming: {
      bufferingGoal: 120,
    },
    retryParameters: {
      timeout: 1000, // timeout in ms, after which we abort
      stallTimeout: 5000, // stall timeout in ms, after which we abort
      connectionTimeout: 80, // connection timeout in ms, after which we abort
      maxAttempts: 6, // the maximum number of requests before we fail
      baseDelay: 500, // the base delay in ms between retries
      backoffFactor: 2, // the multiplicative backoff factor between retries
      fuzzFactor: 0.5, // the fuzz factor to apply to each retry delay
    },
    drm: {
      servers: {
        'com.widevine.alpha': licenseServer,
        'com.microsoft.playready': 'https://foo.bar/drm/playready',
      },
      // advanced: {
      //   'com.widevine.alpha': {
      //     videoRobustness: '',
      //     audioRobustness: '',
      //   },
      //   'com.microsoft.playready': {
      //     videoRobustness: '3000',
      //     audioRobustness: '3000',
      //   },
      // },
    },
    dash: {
      keySystemsByURI: {
        'urn:uuid:SOME-UUID_HERE': http://wvm.ezdrm.com/PlayValue.asp,
      },
    },
  });
```
  
  it loads the mpd file and I could see that the player also displays song duration. But when I click on Play Icon, it will not play.
  
  **Object { severity: 2, category: 6, code: 6008, data: (1) […], handled: false, message: "Shaka Error DRM.LICENSE_RESPONSE_REJECTED ()",**
  
  Please help me fix this issue. Please ask me if you any other information related to this issue.
**Thank you** :+1:

**Comment by TheModMaker** [comment]
First, you shouldn't set `keySystemsByURI` unless you are using a non-standard UUID.  Also, you didn't use the correct name, so you don't need it.  You have it under `dash.keySystemsByURI`, when it should be under `manifest.dash.keySystemsByURI`.

Secondly, [LICENSE_RESPONSE_REJECTED](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6008) is usually caused by your license server wrapping the response in something (e.g. JSON) that needs to be removed before it is passed to the browser.  See [our tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-wrapping.html) on how to do that.  If you look at the network tab, the license request should return a binary blob.

If you provide a manifest and license server URLs, we could help more.  You can send them privately to <shaka-player-issues@google.com> if you prefer.

**Comment by bhushanudupa** [comment]
@TheModMaker 
Thank you for your response. I was using a wrong license server URL. Now it's working fine.
