### ISSUE TITLE
Error 3016 on iOS 14.6 but not on iPad OS 14.6

### ISSUE THREAD

**Issue by FireMasterK** [google/shaka-player#3509]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Not tried, but it's been an issue for months. I can try if requested.

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
Not tried, but I can attempt if requested.

**What browser and OS are you using?**
Safari iOS 14.6

**What are the manifest and license server URIs?**
[dash.xml.txt](https://github.com/google/shaka-player/files/6770785/dash.xml.txt)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Only `streaming.bufferingGoal` is changed to 10.

**What did you do?**
Play a video that has both MP4 streams as well as WEBM streams. I'm aware that iOS does not support webm, but I'm pretty sure it is supposed to fall back to MP4 in that case.

This was conducted on iOS 14.6 on an iPhone 6, and iPad OS 14.6. The video plays on iPad OS but not on iOS.

A build with debug shaka-player can be found at https://1789f5b0.piped.pages.dev/watch?v=9ZBfG3IDTD0

**What did you expect to happen?**
I expected the video to play as expected, like on iPad OS 14.6.

**What actually happened?**
You get a 3016 error in the console, with the video duration being 0s.
![image](https://user-images.githubusercontent.com/20838718/124620048-c36b9380-de96-11eb-85ee-54d7a9cce4fa.png)

Logs on IOS:
[iPhone6s_1789f5b0.piped.pages.dev-1625514166700.log](https://github.com/google/shaka-player/files/6770847/iPhone6s_1789f5b0.piped.pages.dev-1625514166700.log)
Logs on iPad OS (works as expected):
[iPad_1789f5b0.piped.pages.dev-1625514254028.log](https://github.com/google/shaka-player/files/6770852/iPad_1789f5b0.piped.pages.dev-1625514254028.log)

**Comment by BucherTomas** [comment]
There are two factors at play here:

1. There's a difference between iOS and iPadOS. Recent iPadOS versions added so-called Media Source Extensions API (MSE) support for Safari, but IOS still doesn't have it. MSE allows the player to process the stream and feed the browser with data essentially from any streaming protocol as long as codecs within the streams are supported by the browser and the player understands the protocol. iOS doesn't leverage this and streaming protocol parsing is handled natively by the browser, not by the player.
2.  Apple devices support natively HLS protocol, any other adaptive protocol needs to be pre-processed by the player.

Since iOS lacks MSE, the only supported protocol in mobile Safari is HLS. MPEG-DASH is not supported on iOS, but it is in Safari on iPadOS when using an MPEG-DASH player thanks to the presence of MSE that the player can use.

**Comment by FireMasterK** [comment]
Very interesting, thank you!

I now understand that the culprit is iOS not supporting MSE.
