### ISSUE TITLE
Possibility of passing extra argument while creating UI custom buttons 

### ISSUE THREAD

**Issue by hiren3897** [google/shaka-player#3532]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
v3.2

**Please ask your question**
I am creating new features in my player using customized shaka UI.

My every feature is developed in each separate JS files

I want to pass an extra argument `data` in the constructor call it from my main call to append the feature in shaka-player after registering the element 

```javascript
export class AutoplayFeature extends shaka.ui.Element {
    /**
     *
     * @param {!HTMLElement} parent
     * @param {!shaka.ui.Controls} controls
     * @param {!Object<JSON>} data
     */
    constructor(parent, controls, data) {
        super(parent, controls);
        // use the data in my feature
  }
}
```
to pass the data from my `main.js` I have to call like this 
```javascript
new AutoplayFeature(parent, controls, data) // in my main js where I have my data available.
```
Problem: while calling my `AutoplayFeature` it ask for parent argument. how can I get the parent {HTMLElement} of shaka.ui.ELEMENT class.

is it achievable to do this or is it any other way to do achieve this scenario ?

it will be a great help if you can help me with this 

Thank You in advance :)

**Comment by hiren3897** [comment]
Hello, can anyone have an idea about this?
Is this possible to do?
@joeyparrish @TheModMaker

**Comment by nbcl** [comment]
Hello @hiren3897!

> Problem: while calling my AutoplayFeature it ask for parent argument. how can I get the parent {HTMLElement} of shaka.ui.ELEMENT class.

The parent argument should be the location `{HTMLElement}` on where `AutoplayFeature` would be located in the UI!

For example, on `controls.js`, when adding multiple buttons to the control panel, the parent attribute is the controls container, defined by `this.controlsButtonPanel_`.

https://github.com/google/shaka-player/blob/32702483eb9643e45852e29b393ef9f23a346541/ui/controls.js#L797

On the other hand, on `overflow_menu.js`, when adding buttons to the overflow menu, the parent attribute is the overflow menu itself, defined by `this.overflowMenu_`.

https://github.com/google/shaka-player/blob/32702483eb9643e45852e29b393ef9f23a346541/ui/overflow_menu.js#L181

To make sure it is added, `AutoplayFeature` should append itself to the `parent` inside the constructor. For example, if the `AutoplayFeature` button is defined as `this.button`, it should:

```js
this.parent.appendChild(this.button);
```

Finally, the documentation contains an [example](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html) of a custom button that is added directly to the control panel. 

Let me know if this works!

**Comment by hiren3897** [comment]
Hello @nbcl 
Thanks for your response :)

I have learned your explanation very well but the main thing that I exactly want to do is to call my `AutoplayFeature` button and pass mainly three arguments init i.e. `parent`, `controls`, and `data`. So, when I call my `AutoplayFeature` it registers itself in the player and then adds it in `controlPanelElements` so it is enabled in the player.

If I do: 
```javascript
  const parent = document.querySelector('.shaka-controls-button-panel');
  const ui = video.ui;
  const controls = ui.getControls();
  // and pass my related data 
  new AutoplayFeature(parent, controls, data) // in my main js where I have my data available.
```


I am aware of the [example](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html) perfectly and have created many other buttons as well in my project.

Will it work ? or am I doing it in the wrong way?

#### I there any better approach to pass the extra arguments while creating buttons? using [example](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html)

**Comment by theodab** [comment]
If I understand your problem correctly... you have some extra data that is external to the player that a custom button needs to know. Presumably, given your button is called `AutoplayFeature`, it's a collection of JSON that points to the next video(s) in the playlist, or something similar. You can't just bake that data into the button when you register it, since buttons are registered globally, and you can't guarantee that users won't have multiple instances of your player active at the same time. Is that right?

So, with how the library is today, here are the options I can think of:

Option one: Add buttons programmatically, as you seem to be trying right now. For a control panel element, the parent element is `controls.controlsButtonPanel_`. That's a private variable, so I guess you'll want to use an uncompiled build of the player, or modify your local build of the player to make it public. I would recommend against this approach, since it's not how buttons are intended to be added to the control panel, and isn't guaranteed to work correctly (especially in later versions). Weird stuff might happen if the UI is reconfigured, for instance.


Option two: Make a global-scope registry for associated data. Something that maps player to data.
```js
// In the main file:
const ui = video.ui;
const controls = ui.getControls();
const data; // TODO: get data
globalAutoplayData.set(controls.getPlayer(), data);

// In the autoplay button file:
export class AutoplayFeature extends shaka.ui.Element {
  /**
   * @param {!HTMLElement} parent
   * @param {!shaka.ui.Controls} controls
   */
  constructor(parent, controls) {
      super(parent, controls);
      const data = globalAutoplayData.get(controls.getPlayer());
      // TODO: use the data
  }
}
// TODO: and also register a factory for AutoplayFeature, etc
```
This approach will handle the case of multiple players being open at once, but I do admit that having a lot of global-scope variables is messy.


Option three: You could just attach the data to the player. Like...
```js
// In the main file:
const ui = video.ui;
const controls = ui.getControls();
const data; // TODO: get data
controls.getPlayer()['autoplayData'] = data;

// In the autoplay button file:
export class AutoplayFeature extends shaka.ui.Element {
  /**
   * @param {!HTMLElement} parent
   * @param {!shaka.ui.Controls} controls
   */
  constructor(parent, controls) {
      super(parent, controls);
      const data = controls.getPlayer()['autoplayData'];
      // TODO: use the data
  }
}
// TODO: and also register a factory for AutoplayFeature, etc
```
Yeah, compilers won't be too happy about it, but that kind of thing is totally valid in Javascript. Each UI has a single player that does not change, so no need to worry about your data going away.

In the future, I could see an argument for us adding some officially sanctioned field for extra data to the player. Kind of like how our ChromeCast system lets you send arbitrary `appData` to the cast receiver. It'd make this kind of thing a bit more obvious. Although, then users might expect it to be mirrored by the cast receiver, which wouldn't be a good idea, so maybe not...

**Comment by hiren3897** [comment]
Hello @theodab,
First of all sorry for the late response as I was busy with something serious fixings

> If I understand your problem correctly... you have some extra data that is external to the player that a custom button needs to know. Presumably, given your button is called AutoplayFeature, it's a collection of JSON that points to the next video(s) in the playlist, or something similar. You can't just bake that data into the button when you register it, since buttons are registered globally, and you can't guarantee that users won't have multiple instances of your player active at the same time. Is that right?

yes, it is right
this feature is all about displaying the playList when the video gets end with some thumbnails and same as youtube have.

Thank you so much for all the possibilities that you have commented on, I will give it a try to set and get the extra data in my features.

I will try all possible options and let you know which works for me and if I face any problem I can ask you :) 

it seems that the 3rd option would be better to use but I have many other features as well that depend on data lets me see how I can figure it out to do.

Once again thank you so much.

Have a good weekend.
