### ISSUE TITLE
using web audio api with shaka-player #2

### ISSUE THREAD

**Issue by baehongjun0212** [google/shaka-player#3563]
Have you read the FAQ and checked for duplicate open issues?
Yes

What version of Shaka Player are you using?
2.5.11 shaka-player.ui.js

Please ask your question

Hi :) i am trying to use the web audio api along with shaka player.
First of all, thank you for developing Shaka player.

I read the answer to the issue.
: https://github.com/google/shaka-player/issues/2595
This sample code is muted and visualization disappears.
![2 샤카](https://user-images.githubusercontent.com/55692618/127812574-f87c9b76-119c-44cf-9458-fcebdc1dc2c4.png)

Then I found another sample code.
<img width="714" alt="1 샘플" src="https://user-images.githubusercontent.com/55692618/127812478-19f7b905-cf19-44cc-bb8b-03910bbfb72c.png">
Link: https://github.com/loosenRogers/MusicVisualizer-WebAudioAPI
File: https://drive.google.com/file/d/1UazYhEVy0ppev7DyBgwquaD7T2lcGyBm/view?usp=sharing

This sample code does not disappear even if it is muted.

But if you put the video in FileReader,
"Uncaught (in promise) DOMException: Unable to decode audio data" 에러가 발생한다.

**How should I modify the connection part?**
I want to visualize the audio being rendered.

**Comment by joeyparrish** [comment]
I'm not sure what the issue is.  This is probably a combination of a WebAudio quirk and a Shaka Player quirk.

If you're using a createMediaElementSource() in WebAudio, I don't know how the element's muted and volume states will affect the source.

In our UI, we sync the "muted" and "volume" attributes, so that if volume is dragged to 0, we set muted=true.  If volume is dragged above 0, we set muted=false.  So if muted/volume affect WebAudio, it's possible that this feature of our UI makes things more confusing.  Are you using our UI?

How are you muting the video?  Using the UI?  Or `video.muted = true`?  Or `video.volume = 0`?  Some combination of these?
