### ISSUE TITLE
Support PlayReady CustomData field

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#3596]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, and there is an old one that I'm reviving: https://github.com/google/shaka-player/issues/581  (Tagging original requester @AndCycle here JFYI)

**Is your feature request related to a problem? Please describe.**

Partners would like to use the [`CustomData` field of the PlayReady license request](https://docs.microsoft.com/en-us/previous-versions/windows/apps/dn457361(v=ieb.10)?redirectedfrom=MSDN).  Originally, this was rejected as "non-standard", but I believe now I was wrong.  While this would be not be portable to other key systems, and while the more general "license wrapping" approach _is_ portable to all key systems (see ["License Wrapping" tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-wrapping.html)), that doesn't necessarily mean we should reject something Microsoft has documented as part of their protocol.

**Describe the solution you'd like**

Shaka Player already must manipulate the license request from the CDM before sending it to the configured license server.  This happens in `DrmEngine`.  There is no reason we couldn't also offer a config to inject `CustomData` into that request at that time.

**Describe alternatives you've considered**

 - The status quo is always an alternative, but it doesn't offer a solution.
 - License wrapping is an alternative (see link above), but requires customization of the license server endpoint.  `CustomData` support would be superior for apps using PlayReady, for its convenience.

**Additional context**

Proposed solution (which we would welcome as a PR if someone has time to work on it):

1. Add a config field for Shaka to accept `CustomData`.  I would suggest something like `drm.advanced.KEYSYSTEM.customData`.  This should be documented as only being implemented for PlayReady.  The type should be string, it should be documented as base64-encoded arbitrary data, and the default should be set to the empty string.
2. Have `DrmEngine` read this config value, and while transforming the PlayReady license request, add `CustomData` if the config string is non-empty.
3. Add appropriate unit tests.
4. (Ideally) Add an integration test that exercises this against a real license server endpoint.  (Maybe MS's test server?)
4. Vet the solution at a minimum on MS Edge, but preferably also Xbox One and Chromecast.  (We can test for you in our lab on Chromecast and Xbox One, once we have a PR with an integration test.)

**Comment by amfio** [comment]
@joeyparrish by default I **think** the `CustomData` needs to be added to the license request by the CDM as they generate a checksum based on its value so the request will fail if we add it in Shaka.

I think Edge (and therefore presumably Xbox) has a non-spec EME implementation that allows you to pass the value in so that the CDM can to the appending (`MediaKeys.CreateSession( type, initData, cdmData)`) but that won't work for Chromecast or other PlayReady CDM devices.

Some PlayReady servers might have been modified to allow it to be passed in some other way, e.g. via a request header, or even a `ClientInformation` tag within the request itself. I don't think these values are included in the checksum so it shouldn't cause an issue, however I don't think this alternative means of passing the custom data is standardised.

**Comment by joeyparrish** [comment]
Closing for lack of interest.  Thanks!
