### ISSUE TITLE
1002 error while trying to play remote mpd file 

### ISSUE THREAD

**Issue by sekharnadiminti** [google/shaka-player#3604]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=http://40.71.18.239/final.mpd;panel=CUSTOM%20CONTENT;build=compiled

**What version of Shaka Player are you using?**
v3.2.0

**What browser and OS are you using?**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by TheModMaker** [comment]
If you look at the [FAQ](https://github.com/google/shaka-player/blob/master/docs/tutorials/faq.md), you'll see this:

> **Q:** I am getting `HTTP_ERROR` or error code 1002.
>
>**A:** The browser rejected the request.  Look at the browser logs for more
info.  This is usually a CORS error, which means you need particular
headers in the response.  Additionally, with some manifests, we will send a
`Range` header.  This will require explicit approval through the CORS header
`Access-Control-Allow-Headers`.
>
>This can also happen with mixed-content restrictions.  If the site is using
`https:`, then your manifest and segments must also.

If you look at the JavaScript logs, you'll see:

> Mixed Content: The page at '...' was loaded over HTTPS, but requested an insecure resource '...'. This request has been blocked; the content must be served over HTTPS.

You need to load the manifest using `https` due to browser security requirements.

**Comment by sekharnadiminti** [comment]
Thank you for the clarification
