### ISSUE TITLE
Closure error associated with COMPILED flag v1.6

### ISSUE THREAD

**Issue by john-turner** [google/shaka-player#363]
When using the closure compiler and shaka-player as a lib I'm seeing the following error: 
`Uncaught TypeError: this.O is not a function` associated with the `this.logPrefix_()` call in the  following code block in stream.js:

```
shaka.media.Stream.prototype.onUpdate_ = function() {
  shaka.log.v2(this.logPrefix_(), 'onUpdate_');
  shaka.asserts.assert(this.streamInfo_);
  shaka.asserts.assert(this.segmentIndex_);
  shaka.asserts.assert((this.updateTimer_ != null) && !this.resyncing_);
  shaka.asserts.assert(!this.fetching_);

  if (this.started_ && !this.proceeded_) {
    shaka.log.v1(this.logPrefix_(), 'waiting to proceed...');
    this.updateTimer_ = null;
    return;
  }
```

`this.logPrefix_()` seems to only be defined when not compiled at line 

```
if (!COMPILED) {
  /**
   * Returns a string with the form 'Stream MIME_TYPE:' for logging purposes.
   *
   * @return {string}
   * @private
   */
  shaka.media.Stream.prototype.logPrefix_ = function() {
    return 'Stream ' + this.mimeType_ + ':';
  };
}
```

This change occurred from the following commit: https://github.com/google/shaka-player/commit/49e34bce2dcb2f7e49c415a8712e2097268de35f

Versions before this show no error while versions after do.

Setting COMPILED to false as well as removing the compiled check both resolve this issue.

Pull request to resolve this issue: https://github.com/google/shaka-player/pull/362

**Comment by joeyparrish** [comment]
`logPrefix_()` is only used in logs which are not in the compiled build.  I just checked a build of v1.6.5, and the `logPrefix_` doesn't appear anywhere in it.

https://cdnjs.cloudflare.com/ajax/libs/shaka-player/1.6.5/shaka-player.compiled.js

How are you building Shaka Player?

**Comment by john-turner** [comment]
We are building the shaka player as part of our clojurescript project via `lein-cljsbuild.` our closure compilation is using google closure and referencing the shaka-player as a libs `shaka-player/lib`

We have the following closure configuration variables set:
`optimizations advanced`
`closure-extra-annotations {"listens" "exportDoc"}`
```
"COMPILED" true
"goog.DEBUG" false
"goog.STRICT_MODE_COMPATIBLE" true
"goog.ENABLE_DEBUG_LOADER" false
"shaka.asserts.ENABLE_ASSERTS" false
"shaka.log.MAX_LOG_LEVEL" "0"
 "GIT_VERSION" "1.3.0"
```

**Comment by joeyparrish** [comment]
I'm afraid I'm not familiar with ClojureScript (in spite of the similarity to our Closure Compiler).  It sounds like you have an issue with your build system or compiler.  With `MAX_LOG_LEVEL` set to `0`, you shouldn't have any logs or calls to `logPrefix_()`.  Your pull request defines `logPrefix_` for compiled builds, which is the opposite of what we intended for that method.

Since it enables `logPrefix_` for compiled builds to solve a problem we can't reproduce in our build system, I'm afraid I can't accept PR #362 as-is.

Since you aren't using our build system, I'm not sure how we can provide direct support, but I will do what I can to answer any questions you might have.  Closure removes log calls through dead-code stripping when `COMPILED` is `true` and `shaka.log.MAX_LOG_LEVEL` is `0`.  If your compiler doesn't do this, then you may not be able to build Shaka with it.  This project has been designed from the beginning for use with the Closure compiler.

You could always try compiling Shaka Player with our build system and the Closure Compiler, then import that compiled bundle into your project.  Our output is valid, optimized, minified JavaScript, with all public APIs exported to `window.shaka`.  You should have no problems feeding that into your compiler.  That may be the best solution if the ClojureScript compiler is not performing all the same optimization passes that Closure does.

**Comment by john-turner** [comment]
Thanks for you help. There is definitely something wrong with the COMPILED flag and the compiler. I will try to resolve it and post a reference if I find anything that would help someone else with a similar build issue.

Thanks

**Comment by joeyparrish** [comment]
No problem.  We're always happy to help if we can.
