### ISSUE TITLE
Creating custom UI for player

### ISSUE THREAD

**Issue by WINOFFRG** [google/shaka-player#3686]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**Please ask your question**
I want to create a custom UI for the player with the below-mentioned features:
- Buttons with SVG Morphed Animations
- Custom Overflow Menu
- Custom elements like Watermark, Live Tag, Number of Live viewers, etc.

I want to confirm if my method is right or not. I would have to modify the `ui.js` file, Right? Since it is only responsible for creating a basic UI for the player on `data-shaka-player`. So I could design the complete UI using HTML, CSS, and JS, and once UI is done I should move on to adding functionality by registering my elements. Since, the player already has code for basic functionality like `Play/Pause, Volume Bar, Quality Adjustment`. So I can use that JS code and in `ui.js` I just need to pass the ID/Class of that element and for custom elements, I can just register a new one in the factory. Is that right?

**Comment by WINOFFRG** [comment]
Understood Thank You, The simpler way as you explained. But, could you please confirm if the method of which I am talking about i.e making the changes in the `ui.js` file, Is is not recommended? Or is it completely wrong to do that? Because It seems a bit easy for me to create a new project and start with a completely new UI library. 
So instead of using `less`, I will use `sass`. As the basic code for buttons has been provided in their respective files, So I just then need to change element ID/classes everywhere and should give my player the new UI as wanted.

So, instead of first creating the player and overwriting each and every element with the new one, I could save time directly by creating the player with new elements. Does this seem good? Please suggest.

**Comment by nbcl** [comment]
> But, could you please confirm if the method of which I am talking about i.e making the changes in the ui.js file, Is is not recommended?

Right! The recommended way of adding custom elements according to the [documentation](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html), is to create a new file and register the element to the desired component, as this makes it available in the UI without the need of editing preexisting files. If you are looking to customize the options available in the overflow menu, that would look similar to:

```js
shaka.ui.OverflowMenu.registerElement(new myapp.ButtonName.Factory());
```

You can always go to [`ui/`](https://github.com/google/shaka-player/tree/master/ui) and check how the default buttons are built to integrate other functionalities, or as a starting point, take a look on [#3494](https://github.com/google/shaka-player/pull/3494/files) that specifically added a new button while including tests, default values and new styles! 😄

> So instead of using less, I will use sass. As the basic code for buttons has been provided in their respective files, So I just then need to change element ID/classes everywhere and should give my player the new UI as wanted.

If you are looking to edit the styles of the UI without using `Less` you can do it externally by findinding the CSS class names and overriding them, but also note that some visual aspects could be defined via JavaScript on the UI code, like the play and pause icons, as follows:

https://github.com/google/shaka-player/blob/7da2cd59ff7c9a019c13d23f6e73af1c065ed4d3/ui/small_play_button.js#L39-L46

> So, instead of first creating the player and overwriting each and every element with the new one, I could save time directly by creating the player with new elements. Does this seem good? 

Right! Instead of overwriting each element, you could always configure your player not to include any undesired UI element with `ui.configure()`. For example, if you would like to only have the `play` and `volume` buttons plus other `custom_buttons` in your player, you could configure it as follows:

```js
const config = {
  'controlPanelElements': ['play_pause', 'volume', 'custom_button_1', 'custom_button_2']
}
ui.configure(config);
```
 
Let me know if this helps! 😄
