### ISSUE TITLE
How to enable the resolution selection in player controls of the Shaka Player like it's done in the demo?

### ISSUE THREAD

**Issue by talhaimam** [google/shaka-player#3698]
I've been following this issue for a while: https://github.com/google/shaka-player/issues/2676 which is related to my current question.

However, the demo of Shaka Player here:
https://shaka-player-demo.appspot.com/demo/

is designed in the exact same way which we need as a pluggable solution. How is the following achieved in the demo:

![image](https://user-images.githubusercontent.com/18185376/137299418-3a07a5a1-34df-4c4f-9258-87361c518a38.png)

P.S. - I did take a look at the source code but it's not designed in a very helpful manner.

**Comment by theodab** [comment]
If you set up Shaka Player [using the optional UI library](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-ui.html), the quality selector should be one of the default overflow menu buttons. Or do you mean that you want the quality menu as a standalone thing, outside of the Shaka Player UI?

**Comment by talhaimam** [comment]
@theodab I have already played around a lot with the UI library, only to find out that it doesnt make the overflow menu buttons a part of the player itself.

Please refer to the screenshot posted in the question - that is exactly what I need: the resolution selection controls inside the player.

**Comment by theodab** [comment]
I'm not entirely sure what you mean by controls being "a part of the player" in the first place.

Do you mean that you want the button to be in the main UI bar rather than the overflow menu, like in issue #2676 as you listed? I had assumed that wasn't what you meant, because you said "how is the following achieved in the demo", and the demo doesn't do that, but it is possible:
```js
const uiConfig = ui.getConfiguration();
uiConfig.controlPanelElements.push('quality');
ui.configure(uiConfig);
```

For reference, this is how the demo configures the UI:
https://github.com/google/shaka-player/blob/a09d8c9869d5246af540d562f36546a294c2d9e9/demo/main.js#L316-L341
It enables or disables trick play controls as desired, and adds the custom "close" button. That's it, it doesn't change or configure the quality selector at all.
