### ISSUE TITLE
Split REQUESTED_KEY_SYSTEMS_UNAVAILABLE

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-player#371]
The error code REQUESTED_KEY_SYSTEMS_UNAVAILABLE is used when none of the key systems you requested could be instantiated on the platform.  However, we also fail key systems when there is no configured license server.  So the error could occur simply because of a configuration problem.

We should provide a different error code when the key system is available, but the license server is simply not configured.  This would provide a clear path forward for users without diving into the documentation.

**Comment by ddorwin** [comment]
While I don't know the paths that cause this error, you might also consider a new name since failing the EME spec does not distinguish between a key system being unavailable and none of the provided configurations being supported.

An empty configuration should be equivalent to the former, but that may not be advisable. See https://github.com/w3c/encrypted-media/issues/178#issuecomment-216299258.

**Comment by joeyparrish** [comment]
Good point.  We should also update the name REQUESTED_KEY_SYSTEMS_UNAVAILABLE to REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE and be specific in the documentation that user options may cause the error as well as missing key systems.

**Comment by ddorwin** [comment]
More specifically, user options = user configurations/choices and consent.

**Comment by joeyparrish** [comment]
Yes, thank you.  We'll be careful with the wording.
