### ISSUE TITLE
Trying to accelerate playback start

### ISSUE THREAD

**Issue by aletorrado** [google/shaka-player#374]
Hi, I'm trying to accelerate the start of playback, but shaka downloads several chunks before starting to play.

Just to test, I'm configuring the player like this:

```
player.configure({
	streaming: {
		rebufferingGoal: 1,
		bufferBehind: 1,
		bufferingGoal: 1,
		retryParameters: {
			maxAttempts: 5,
		},
	},
})
```

Segments are about 1.5~3 seconds. Why shaka downloads 4~5 segments before starting, when it could start playing with the first one?

Thank you

**Comment by tdrews** [comment]
Hi,

Shaka starts playback as soon as it has downloaded and inserted the init segment and first media segment of each initial Stream chosen (e.g., middle bitrate audio and low bitrate video), regardless of the buffering goals. After it downloads these segments, it will fetch the init segments of each `<Representation>` in the manifest in the background. However, multiple media segments *could* be downloaded before playback begins, since there will always be some delay between when Shaka inserts media segments and when the video element begins playback.

To help rule some things out, can you enable verbose logging and add
```javascript
video.addEventListener('playing', function() { console.log('PLAY'); });
video.addEventListener('loadedmetadata', function() { console.log('LOADED_METADATA'); });
```
before loading the manifest and check how many fetchAndAppend_ calls there are before "PLAY" is logged?

**Comment by tdrews** [comment]
I forgot to mention that Shaka will download the segment which precedes the one it actually needs (based on the manifest) after seeking and when beginning a live presentation. This is done because the timestamps in the actual media segments may be slightly ahead or behind what is specified in the manifest; by fetching an earlier segment we reduce the possibility of introducing a gap between the playhead and the segment inserted.

So, if your stream is live, this may explain why there are some additional segments being downloaded.

**Comment by joeyparrish** [comment]
@aletorrado Is this still an issue for you, or can we close it?

**Comment by joeyparrish** [comment]
@aletorrado, since we haven't heard from you in a while, I'm closing this issue now.  If you need further support, just let us know and we'll be happy to help.
