### ISSUE TITLE
bufferingGoal is not reached

### ISSUE THREAD

**Issue by ilFuma** [google/shaka-player#3744]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
✔ Yes

**What version of Shaka Player are you using?**
v 3.2.1

**Can you reproduce the issue with our latest release version?**
✔ Yes

**Can you reproduce the issue with the latest code from `master`?**
✔ Yes

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
✔ Yes

Example: [Link](https://shaka-player-demo.appspot.com/demo/#audiolang=it-IT;textlang=it-IT;bufferingGoal=900;uilang=it-IT;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;panel=ALL_CONTENT;build=uncompiled)

**What browser and OS are you using?**
Chrome 95 - Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

N/A

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

I'm using the following config:
- `bufferingGoal: 900`
- `bufferBehind: 180`
- `rebufferingGoal: 2`

**What did you do?**
I'm trying to tune the buffering configuration as explained in the tutorial (https://shaka-player-demo.appspot.com/docs/api/tutorial-network-and-buffering-config.html).

**What did you expect to happen?**
The player should buffer the content till reaching the specified "bufferingGoal"

**What actually happened?**
I initialize the streaming and pause the playback, the player starts requesting the segments to increase the buffer but, after a certain amount of segments, before reaching the bufferingGoal it slows down the requests and eventually stops requesting new chunks even if the bufferingGoal value has not been reached. (screenshot attached)

This behavior has been tested on Chrome and Firefox on windows. 

- Is there any limitation in the amount of segments / duration that can be buffered ?
- Could it be related to the amount of resources available on the device?
- Do you have any best practice to suggest for buffering settings ?

![shaka buffering](https://user-images.githubusercontent.com/1921876/140376502-587951d0-a498-4800-ae37-4a8cf38a8a25.png)

Best,
A.

**Comment by TheModMaker** [comment]
The browser imposes limits on how much content can be buffered.  The media is stored in RAM, so how big this limit is will depend on the device and the content resolution.  You will fill up the buffer much faster with 4k than with 480p since it is much larger.  Unfortunately the browser doesn't give us any info on how much this limit is, we just get an error if we fill it up.

If this is happening, you will see debug logs indicating this.  These logs are only visible in debug/uncompiled mode, see our [debugging](https://shaka-player-demo.appspot.com/docs/api/tutorial-debugging.html) tutorial for more info.

Having a 3 minute behind limit and a 15 minute buffering goal is a huge amount.  Usually these limits are on the order of 30 seconds to maintain smooth playback, but not take up too much space.  Many devices (especially phones) will have a hard time buffering a lot of content.

The reason we re-request the segment at the end is probably #1352.
