### ISSUE TITLE
how to use in react-native

### ISSUE THREAD

**Issue by vaseala** [google/shaka-player#3791]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.2.0

**Please ask your question**
How to use in react-native, have some demos?

**Comment by theodab** [comment]
I don't believe that anyone in the Shaka Player team has any experience with React Native.

**Comment by vasanth-fl** [comment]
Shaka Player uses the open web standards **MediaSource Extensions** and **Encrypted Media Extensions**, neither of which are available in React Native run-time since its not a browser environment. So, i'm pretty sure you wouldn't be able to use Shaka-player in React native.

It might be possible to write a React Native bridge for https://github.com/google/shaka-player-embedded but its currently only supported on iOS.

**Comment by joeyparrish** [comment]
Thanks, Vasanth.  If React Native has no MediaSource Extensions, then Shaka Player is probably a poor fit for that environment.  @vaseala, does that answer your question?
