### ISSUE TITLE
Do shaka-player supports LL-HLS and LL-DASH ?

### ISSUE THREAD

**Issue by hiren3897** [google/shaka-player#3898]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES #1525 

**What version of Shaka Player are you using?**
v3.2.1

**Please ask your question**

I would like to know do shaka player supports Low-Latency HTTP Live Streaming (LL-HLS) and Low-Latency Dynamic Adaptive Streaming over HTTP (LL-DASH)?

**Comment by joeyparrish** [comment]
Yes, since v3.1:

https://github.com/google/shaka-player/blob/master/CHANGELOG.md#310-2021-04-29
https://github.com/google/shaka-player#hls-features

Does this answer your question?

**Comment by hiren3897** [comment]
Yes, It answers my question, Thanks.
@joeyparrish 
I asked this question because we are trying to play the live streams that are DRM protected in shaka-player.

We play DASHWIDEVINE, HLSFAIRPLAY,  and HLS live streams in the player but we have many lags on browsers like Chrome Edge, we are not able to maintain the latency of the player close to the live, our CDN server is getting worst because of multiple requests of streams or ts files.

Can you please answer my questions
1) can you tell me the workflow on how exactly the shaka-player works on live streams for dash or hlsfairplay etc?

2) can you tell do changing the below-mentioned parameter that makes a request for the segments from the manifest affects the performance of the player and the server backend that provides the live stream manifests

```
      bufferBehind: 30,
      bufferingGoal: 30,
      rebufferingGoal: 3,
```

3) Can you tell me how do we provide support for LL-HLS and LL-DASH in the player.

4) Does the shaka-player stress more on making requests to the segments to play the live streams that affect the CDN servers?

**Comment by hiren3897** [comment]
If we have the live stream for example Dash and HLS they need to be low-latency in order to support `lowLatencyMode`?

**Comment by joeyparrish** [comment]
Yes, low-latency mode:

1. Must be enabled in the player, since you have to give up certain other features, such as network response filters for segments
2. Requires corresponding features in the content to enable low-latency streaming (partial segments in HLS, availabilityTimeOffset in DASH)
3. Requires corresponding features in the browser/platform (ReadableStream API for low-latency DASH)

> Does the shaka-player stress more on making requests to the segments to play the live streams that affect the CDN servers?

How Shaka makes requests depends on the structure of your content.  For example, if you have LL-HLS with partial segments, we will have to make more requests at the live edge because the content is broken into smaller pieces.  How many more requests depends on how small your partial segments are.

**Comment by hiren3897** [comment]
Thanks for the nice explanations.

I don't know why because in our web application while playing live streams the segments are fetched too many times from the origin to the cache server and it is causing too much load on the CDN server.

I see in my networks that our live manifest.MPD is fetched every 2-3 seconds to get the latest segments from the live.

and if I test another external live URL: https://livesim.dashif.org/livesim/chunkdur_1/ato_7/testpic4_8s/Manifest300.mpd

it fetches the manifest,mpd only once, and then it fetches the segments to give a playback.

Can you suggest to me the behavior of how the live dash manifest or HLS playlist works?

It would be a great help to know why the player is fetching too many segments because we have a serious problem and stress on the CDN server.

**Comment by hiren3897** [comment]
I found something in the behavior of the shaka-player player while playing the live content. 
we are playing DASH - with DRM and have DVR mode for 3hrs

when playing the live manifest in shaka-player at the live edge we have repeated requests on the manifest to get the chucks for the playback. 
Also, when we navigate in the past of the timeline it makes many requests on the chucks and manifests to get the actually pointed segment navigated on the timeline. 
You can see the behavior in the image below.

In this image, you are seeing the network when the player is on the live it keeps on fetching the manifest again n again
![equ-many](https://user-images.githubusercontent.com/59652404/151191299-eb3b4e8b-52e8-43d2-b042-6b4e7f994adf.png)



The reason I am saying this is that when we click to navigate in past there are so many requests for the chuck files,
is it normal?![onNavigate](https://user-images.githubusercontent.com/59652404/151191353-cecb7a54-a767-4208-80b1-6af4b7914be5.png)


In this image, you will see that when the live is on pause it continuous to fetch the manifest
![onPause](https://user-images.githubusercontent.com/59652404/151191387-df19fd72-c40f-41ae-a960-7f0dd2c0b756.png)


can we control it using? because it is affecting our CDN servers 
```
    bufferBehind: 30,
      bufferingGoal: 30,
      rebufferingGoal: 3,
  ```

**Comment by joeyparrish** [comment]
How often we fetch the manifest and how often we have to fetch new chunks are both results of attributes in the manifest and the structure of the content.

For example, the `minimumUpdatePeriod` attribute dictates how often we fetch a new manifest.  In your now-deleted comment, you linked to https://livesim.dashif.org/livesim/chunkdur_1/ato_7/testpic4_8s/Manifest300.mpd, which has a minimum update period of 100 years.

How can that work?  Well, that comes down to the structure of the content.  If the segment size is consistent, and the encoder isn't suffering from significant drift, then `SegmentTemplate` with a fixed `duration` can be used.  In this case, future segments can be predicted from a single manifest fetch.  If your MPD uses `SegmentTemplate` + `SegmentTimeline` instead, then your segment sizes can vary, and we have to fetch a new manifest to know the size, timestamp, and location of each new segment.

Your screenshots don't indicate anything clearly wrong, but I also can't see enough of the URLs to see what timestamps or segment numbers those requests are for.  But we're getting way into bug-report territory, and you didn't use the bug template or share content with us to debug, so I don't think we can go any further into that without you filing a proper bug report.

If the explanations above are helpful, and you are able to solve your CDN load issues by changing settings on your encoder/packager, then please close this issue and let us know that the issue is resolved.  If you still feel that the player is doing something wrong, please close this issue and file another one using the bug report template.  Most important in that template is the part where we ask you to send us a manifest URL (privately if you need to).

Thanks!

**Comment by hiren3897** [comment]
Hello, thanks for the suggestion on manifest it was very helpful to analyze.

I will close this issue and create a bug issue and I will provide you the URL that will have the player playing our live content with the manifest URLs at the bottom of the player

Thanks see you soon :)

**Comment by hiren3897** [comment]
Hello I have created a bug issue and sent you an email for the same 
Dash and HLS live stream (with 3hours DVR mode) lags in player #3911
