### ISSUE TITLE
Chrome on ipad does not use MSE but Safari on ipad does

### ISSUE THREAD

**Issue by vinod-balakrishnan** [google/shaka-player#3901]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
Shaka player v3.3.0-pre

**Please ask your question**
My usecase is that i want to use the MSE apis in ipads and i am able to do that with setting the useNativeHlsOnSafari config option to false for safari, but chrome on ipad is not able to find the Mediasource object and errors out. Is there an additional api call or configure option that i might be missing?
Thanks for the help!

**Comment by joeyparrish** [comment]
Our decision to use `src=` (native HLS) is based on the code in [`shouldUseSrcEquals_`](https://github.com/google/shaka-player/blob/771619ff0ef8ba0e3da9569ded3894b428d03c58/lib/player.js#L1205) in `shaka.Player`.  The first step is to check for MSE support.  If it's not there, we **must** use src=, because there is no alternative available.

If Chrome doesn't support MSE on iPadOS, there isn't anything we can do about it, unfortunately.

**Comment by vinod-balakrishnan** [comment]
Got it. Thanks 👍
