### ISSUE TITLE
None of the requested configurations were supported.

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#392]
In Chrome 49 and prior we are getting the error "None of the requested configurations were supported." when using codec="avc1.640814". However `MediaSource.isTypeSupported('video/mp4; codecs="avc1.640814"')` returns `true`. This isn't a Shaka issue because 49 is using native MSE as-is but I can't find any discussion of this inconsistency. Has anyone encountered something similar?

**Comment by joeyparrish** [comment]
Is the content encrypted or clear?

**Comment by sanbornhnewyyz** [comment]
The content is encrypted.

**Comment by ddorwin** [comment]
Does it work in Chrome 50 and later or is it still a problem? `document.createElement('video').canPlayType('video/mp4; codecs="avc1.640814"')` returns `"probably"` in Chrome 51, so it should work, though I'm not familiar with the Shaka API

**Comment by sanbornhnewyyz** [comment]
Yes it works in later versions.

**Comment by joeyparrish** [comment]
If it works in Chrome stable (51) but not in Chrome 49, then I have to assume it's a bug in Chrome that was fixed already.

If the content is encrypted, `MediaSource` is not the only component that must support the MIME type.  `MediaKeys` must also support it.  The error you mentioned occurs when EME negotiation fails.  So the EME query for that type/codec must be failing.

Here's a simplified version of Shaka's EME query for that type.  You can run this in the JS console to see what happens on your version of Chrome:

```js
config = {videoCapabilities: [{ contentType: 'video/mp4; codecs="avc1.640814"' }]};
navigator.requestMediaKeySystemAccess('com.widevine.alpha', [config]).then(
    function() { console.log('okay'); },
    function(e) { console.log(fail, e); }
);
```

Unfortunately, though, we will be unable to give direct support for outdated versions of Chrome, since Chrome is meant to be auto-updated.

If you have a fork or an embedded version of Chromium, you may be able to patch the bug yourself.  Since it appears that the bug has been fixed in Chrome stable, though, you may be able to identify the change that fixed it and back port that to your version.

**Comment by sanbornhnewyyz** [comment]
@joeyparrish thanks for the info. I don't expect any Shaka support for this, just trying to get a handle on what's going on. Only reason we were concerned with 49 was that it is the lats version available on OSX 10.7 I believe.

**Comment by sanbornhnewyyz** [comment]
Alright, after checking all the codecs in the manifest in question, they all fail the test you provided in Chrome 49. Thanks for informing me that EME and `MediaSource` support are independent of each other.

**Comment by joeyparrish** [comment]
Oh, I see.  I was not aware of that.  If you can track down the specific issue in crbug.com, it might be worth raising with Chrome team that the bug persists on OSX 10.7.

**Comment by sanbornhnewyyz** [comment]
Okay, good point. I'll see what I can do.
