### ISSUE TITLE
What is the solution for Shaka Error MANIFEST.NO_VARIANTS (), error code - 4036

### ISSUE THREAD

**Issue by chahatmiddha561** [google/shaka-player#3985]
We're using Shaka Version - 3.2.1 and playing HLS live stream, which is not getting played using shaka player. Error coming in - [Shaka Error MANIFEST.NO_VARIANTS ()](https://v3-2-4-dot-shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:4036) 
Do we have any solution for this, because the stream is being played using the HLS player by hls.js?
![Screenshot 2022-02-21 at 2 33 26 PM](https://user-images.githubusercontent.com/40665500/154922439-fb9776de-050d-499a-b084-18846ec544df.png)
Error code below:
{
category: 4,
code: 4036,
data: [],
handled: false,
message: "Shaka Error MANIFEST.NO_VARIANTS ()",
severity: 2,
stack: "Error: Shaka Error MANIFEST.NO_VARIANTS ()\n    at new shaka.util.Error (https://v3-2-4-dot-shaka-player-demo.appspot.com/lib/util/error.js:94:17)\n "
}

**Comment by chahatmiddha561** [comment]
I'm able to play this particular stream on this shaka demo - https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://mirchiplaylive.akamaized.net/hls/live/2036929/MUM/MTOP20_Auto.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled
HLS Stream Path - https://mirchiplaylive.akamaized.net/hls/live/2036929/MUM/MTOP20_Auto.m3u8

**Comment by theodab** [comment]
The `MANIFEST.NO_VARIANTS` error typically means that all of the streams of a manifest got filtered out. For example, if they are all in a format that the browser or player does not support.
Looking at your stream, all of the variants are aac files. We only added support for containerless formats such as aac very recently, and it hasn't been included in a release yet. So that's why the steam works on the nightly, which includes the changes we have yet to put into a feature release.

Incidentally, each `EXT-X-STREAM-INF` in your manifest declares two different `CODECS` values. That's weird, I don't think you're supposed to do that.

**Comment by chahatmiddha561** [comment]
Hi @theodab, thanks for your quick reply. The stream response now contains `.ts` files instead of `.aac`, and now it's playing using shaka. 
Could you let us know when aac files support will be added to the shaka player? Also, let us know where can we subscribe for getting the updates and releases of new shaka versions?

**Comment by joeyparrish** [comment]
The work is in progress already.  Much of it has landed in the `master` branch, but we are still working through some issues introduced by the changes.  The version with aac support will be v4.0.0, and there is no date for the release.  It will be out as soon as we've solved the issues that are blocking the feature release.

You can see a preview of the latest nightly build running at https://nightly-dot-shaka-player-demo.appspot.com/

You can subscribe to release notifications on GitHub by clicking the "Watch" button on https://github.com/google/shaka-player/ and selecting "Custom", then "Releases".

Thanks!
