### ISSUE TITLE
cross origin error

### ISSUE THREAD

**Issue by baljitweb** [google/shaka-player#404]
I am using compiled js for shaka player
i set following things for shaka:

- `var config = ({ 
			abr: {}, 
			drm: {
					servers : {'com.widevine.alpha':"http://192.168.52.22:8080/proxy"} 
			}, 
			manifest: { 
				dash: {} 
			} 
		});`

- `config.manifest.dash.clockSyncUri = '//shaka-player-demo.appspot.com/time.txt';
		player.resetConfiguration();
		player.configure(config);`

- ` 
	  player.getNetworkingEngine().registerRequestFilter(function(type, request) {
		// Only add headers to license requests:
		if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
		  // This is the specific header name and value the server wants:
		  request.allowCrossSiteCredentials = true;
		}
	  });`

shaka only plays 10 sec video after it get following error :

`XMLHttpRequest cannot load http://192.168.52.22:8080/proxy. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. The response had HTTP status code 404.`

Note : I cannot access mpd file directly hence i need proxy server [192.168.52.22:8080] to access it from localhost. Proxy server has following port forwarding:
10.202.8.233:80 and 10.202.8.233:8080

don't know what is wrong here.

thanks in advance.

baljit

**Comment by joeyparrish** [comment]
Based on what you've provided, it appears that you are getting a 404 (not found) error on your license server URL http://192.168.52.22:8080/proxy/header_auth .  The 404 error page from your web server does not contain cross origin headers, which sounds reasonable.  But the request is cross origin, so the CORS error is making it less obvious that the real problem is your 404.

Shaka Player can still play 10 seconds worth because you packaged your content with 10 seconds of clear lead.  So this plays even without a license.

I recommend you check your license server IP, endpoint URL, and web server config.  This does not appear to be a Shaka issue.
