### ISSUE TITLE
Select by role as well as language without disabling ABR

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#412]
Can you explain why abr gets disabled when selecting a different audio track? Most audio track switches are going to be for changing languages and I don't think this should interfere with abr for video tracks.

**Comment by TheModMaker** [comment]
If you select a track using `player.selectTrack`, it will disable abr because you selected a specific track.  If you want to change languages, you can use `player.configure`.  This will cause it to switch tracks without disabling abr.

```js
player.configure({preferredAudioLanguage: 'es'})
```

In the demo app, selecting a track from the drop-down list will use `player.selectTrack`.  You can change the preferred language text box and press Enter and it will change to another language.

**Comment by joeyparrish** [comment]
That's right.  If your UI had manual track selection widget (like YouTube's 360p / 480p / 720p / 1080p / auto), that would connect to `selectTrack`.  If your UI has a language selection widget, that should connect to `configure`.

If that's confusing or unhelpful, let us know while we're still in beta and we can reconsider.

**Comment by sanbornhnewyyz** [comment]
No, I think that is sensible. It should give greater control if we have multiple audio variants of the same language which I assume is the intention. 

Thanks for clearing that up. I think it would be worth putting a note in the v2 migration guide about the difference in APIs in this respect from 1.x to 2.

**Comment by sanbornhnewyyz** [comment]
Actually, on some further reflection and discussion I want to present possible problematic scenario. 

What happens if there are three audio tracks, all of them are english. Two of them are the same audio track with different bitrates but the third is the content audio plus directors commentary. How would we handle this situation? Selecting a specific track will turn of ABR which is not desirable if I want the player to handle switching bitrates between the first two tracks. But configuring the player for english tracks now is ambiguous because it doesn't allow us to specify if we want commentary or not.

**Comment by joeyparrish** [comment]
Makes sense.  In a nutshell, we should allow selection by both role and language without disabling ABR.  Is `configure()` still the best interface for this?

I'm tentatively scheduling this for v2+, but if we have a design sooner we can consider it for v2.0.0.

**Comment by sanbornhnewyyz** [comment]
Assuming that configure() is triggered immediately then I don't see any reason not to continue to use this approach.

**Comment by joeyparrish** [comment]
The current language switching via configure() is immediate, so the role switching could be as well.

**Comment by joeyparrish** [comment]
After further consideration, I think we should stop using `configure()` in this way.

Proposal:
 - Configuration of preferred languages will only affect initial selections when content is loaded.  Changing preferred languages during playback will affect the next piece of content to be loaded.  The configuration represents a user preference, so it does not make sense to use the same mechanism to change languages during playback.  Choosing a new language may be a temporary, manual decision and is not the same as changing a user's preferences.
 - New methods for language choices will be introduced in parallel to `getTracks()` and `selectTrack()`.  Example: `player.getLanguages('audio')` or `player.selectLanguage('audio', 'fr-CA')` or `player.selectLanguage('text', 'de', 'caption')`.  The role argument will be optional, and these APIs will be easy to hook up directly to language-related UI elements.
 - Changing languages will clear the buffer (so that the effect is immediate) but will not disable adaptation.
 - We will add language-related UI elements to our demo app controls to demonstrate how we would expect these methods to be used.

@sanbornhnewyyz, thoughts?

**Comment by ismena** [comment]
Closing due to the fact that the new API has been implemented (and inactivity :)).
Feel free to reopen if you have issues or questions!

**Comment by forbesjo** [comment]
I can see that there's a new API for selecting by audio language while keeping the ABR active, but I don't see how the role of the audio track is taken into account? How would a user enable a commentary track?

**Comment by joeyparrish** [comment]
@forbesjo, I think we made a mistake on that.  We are going to address it as part of #767.
