### ISSUE TITLE
Two DASH VOD sample content cannot be playback with v2.0.0-beta2-debug

### ISSUE THREAD

**Issue by faiyeah** [google/shaka-player#415]
Content 1:
- Affected contents:
-- https://www.dropbox.com/sh/07id6dkczd1jxp2/AAAio3JYCpaWCls-GKF3bqsUa?dl=0
- Shaka player log:
-- https://www.dropbox.com/s/yac77rbjwbvm0r7/PMPO-5501-shaka-player-demo.appspot.com-1465964127792.log?dl=0

Content 2:
- Affect contents:
-- https://www.dropbox.com/s/jqvr2o3i97dii51/PMPO-4977.tar.gz?dl=0
- Shaka player log:
-- https://www.dropbox.com/s/sdpu1thwnkbta2b/PMPO-4977-shaka-player-demo.appspot.com-1465966634255.log?dl=0

Observation (applying to both Content 1 and 2):
- Once click playback, the first frame can be decoded and displayed.
- It does not playback, for both video and audio streams.

More information:
- The same stream can be playback using v.1.6.5 shaka player.

**Comment by joeyparrish** [comment]
According to the DASH IF, your content does not contain video segments that cover the entire period.  To quote them:

> It is not the player that must deal with the problematic section but the production software.
>
> The player should play the entire period from start to finish. It is the responsibility of the mechanism creating the DASH presentation to ensure that there is enough data in all the elementary streams to cover the entire duration of the period.

Shaka v1 had a complex mechanism whereby we effectively clipped off leading audio or video and treated the content as if it started when both streams were present.  Shaka v2 does not have this mechanism because it was complex and subtle and only served to hide bugs in content packagers.

Please report this bug to the vendor of your encoder or DASH packager.

**Comment by liwaiwai** [comment]
The cause of why Shaka Player v2.0.0-beta2-debug cannot do the playback is identified. It's due to https://github.com/google/shaka-player/issues/366

The trunk with the fix can play the
