### ISSUE TITLE
Right clicking video produces varying context menus.

### ISSUE THREAD

**Issue by tdrews** [google/shaka-player#422]
Sometimes right clicking on the video produces one context menu, showing "Loop, Show controls, ...", and other times it produces another, showing "Back, Forward, ...".

Expected: only the "Loop, Show controls, ..." context menu is shown.

Mirrored from http://crbug.com/609879

**Comment by joeyparrish** [comment]
When the context menu shows "Back, Forward", selecting "Inspect" reveals the cause: the cursor is on element ID `giantPlayButtonContainer` instead of `video`.

The actual button (ID `giantPlayButton`) has the style `display: none`, but its container has `display: block`, which is why the container is receiving those clicks.  We should be able to fix it by hiding the container.
