### ISSUE TITLE
How to config DRM with dash generate by shaka_packager

### ISSUE THREAD

**Issue by haithanhnguyen** [google/shaka-player#430]
Hi team,

We want to play dash file generate by [shaka_packager](https://github.com/google/shaka-packager). So, how can I config player? 

Bellow is my packager command. I follow this guide (http://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html) to config player. So, which method I should use to config player, and how to config.

Please help me! Thanks very much!

**PACKAGER COMMAND**
```
packager \
  'input=udp://X.X.X.X:5003,stream=audio,init_segment=live-audio.mp4,segment_template=live-audio-$Number$.mp4,bandwidth=130000'  \
  'input=udp://X.X.X.X:5003,stream=video,init_segment=live-video-sd.mp4,segment_template=live-video-sd-$Number$.mp4,bandwidth=2000000' \
  'input=udp://X.X.X.X:5002,stream=video,init_segment=live-video-hd.mp4,segment_template=live-video-hd-$Number$.mp4,bandwidth=5000000' \
--profile live \
--mpd_output live.mpd \
--enable_widevine_encryption \
--key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" \
--content_id "3031323334353637" \
--signer "widevine_test" \
--aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" \
--aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" \
--crypto_period_duration 1800
```
===================

**Comment by joeyparrish** [comment]
The [Configuration](http://shaka-player-demo.appspot.com/docs/api/tutorial-config.html) tutorial is a good overview of how Player configuration works in general.  It introduces you to the concept of our config system and shows some of the defaults without really going into what they are for.

Next, I suggest you read the [DRM Configuration](http://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html) tutorial, which explains how to configure the Player for DRM content such as yours.  In a nutshell, you must provide a license server URL.

The [License Server Authentication](http://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html) tutorial is a more advanced topic, specifically for license servers which require authentication.  Since you are packaging your own content against Widevine's UAT server, you can use [Widevine's test license server](http://widevine-proxy.appspot.com/proxy) which does not require authentication.  Unless you are specifically setting up your own server, you don't need the authentication tutorial.

Does that help?

**Comment by haithanhnguyen** [comment]
Thanks for your reply,

In my case, I want to deploy private licence server. So, how can I do?

P/S: I've tried  http://widevine-proxy.appspot.com/proxy, but I cannot encrypt with shaka packager. Error: "Widevine encryption key source failed to fetch keys: 7 (HTTP_FAILURE): curl_easy_perform() failed: HTTP response code said error. Response code: 404"

**Comment by joeyparrish** [comment]
The appspot license server you referenced is only used by the player to request a license.  The key server used by the packager is a different endpoint which speaks a different protocol.

The Shaka Packager project has instructions in its README file under the heading ["Driver Program Sample Usage"](https://github.com/google/shaka-packager#driver-program-sample-usage).  These options are the ones I use:

```
--enable_widevine_encryption \
--key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" \
--content_id "3031323334353637" \
--signer "widevine_test" \
--aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" \
--aes_signing_iv "d58ce954203b7c9a9a9d467f59839249"
```

If you need further assistance with [Shaka Packager](https://github.com/google/shaka-packager), that project is maintained by a different team who can help you better than I can.  They have a [public mailing list](https://groups.google.com/forum/#!forum/shaka-packager-users) and [github issue tracker](https://github.com/google/shaka-packager/issues).

I'm not sure what to recommend for running a private license server.  I will ask my colleagues for guidance and reply here.

**Comment by joeyparrish** [comment]
My colleagues have told me that to run a private license server, you should contact Widevine directly: http://www.widevine.com/contact.html

Please let us know if you have any other issues with Shaka Player.  Thanks!
