### ISSUE TITLE
Parse optional line and position settings in VTT

### ISSUE THREAD

**Issue by OrenMe** [google/shaka-player#469]
If VTT cue has position alignment, e.g. `position:10%,line-left` then `vtt_text_parser.parseSettings` method is unable to parse the setting string, resulting in an exception.
Is there any issue with parsing and applying this kind of vtt cue settings?
See here for full options: https://w3c.github.io/webvtt/#webvtt-cue-position-alignment

**Comment by joeyparrish** [comment]
There's no reason we couldn't parse that.  It looks like we're not parsing any of the optional parts of the individual settings.  Here's the relevant text from the spec, for reference:

__A WebVTT line cue setting__ consists of the following components, in the order given:
  1. The string "line" as the WebVTT cue setting name.
  2. A U+003A COLON character (:).
  3. As the WebVTT cue setting value:
    1. An offset value, either:
      1. To represent a specific offset relative to the video viewport, a WebVTT percentage.
      2. Or to represent a line number
        1. Optionally a U+002D HYPHEN-MINUS character (-).
        2. One or more ASCII digits.
    2. __An optional alignment value consisting of the following components:__
      1. __A U+002C COMMA character (,).__
      2. __One of the following strings: "start", "center", "end"__

__A WebVTT position cue setting__ consists of the following components, in the order given:
  1. The string "position" as the WebVTT cue setting name.
  2. A U+003A COLON character (:).
  3. As the WebVTT cue setting value:
    1. A position value consisting of: a WebVTT percentage.
    2. __An optional alignment value consisting of:__
      1. __A U+002C COMMA character (,).__
      2. __One of the following strings: "line-left", "center", "line-right"__

https://w3c.github.io/webvtt/#cue-settings

However, be forewarned Chrome has not yet implemented the `positionAlign` or `lineAlign` properties on the `VTTCue` interface, so those properties will not have any effect in the current version of Chrome.

**Comment by ismena** [comment]
A bug on Chrome to implement support for positionAlign and lineAlign attributes: https://bugs.chromium.org/p/chromium/issues/detail?id=633690

**Comment by joeyparrish** [comment]
@OrenMe, the Chromium authors have stated that these attributes were not implemented in Chromium because they didn't have a real use-case.  If you're interested to see these attributes implemented in Chrome, please go to the Chromium bug tracker and explain what you need: https://bugs.chromium.org/p/chromium/issues/detail?id=633690#c6

**Comment by OrenMe** [comment]
Thanks @joeyparrish, my main concern was that the parser was failing and stopping playback more then actually the support of this attributes in the browser.
As there are vtt files containing these attributes this fix will now enable playback with them.

**Comment by sanbornhnewyyz** [comment]
I'm having a similar issue using the latest from master but it's because the webVTT tracks we are using have `position` `start|center|end` instead of  `line-left|center|line-right`. I believe the disagreement stems from a change in the WebVTT spec. The tracks we have are based on the Working Draft here: https://www.w3.org/TR/webvtt1/#webvtt-position-cue-setting and the implementation seems to be based on the Editor's Draft here: https://w3c.github.io/webvtt/#webvtt-position-cue-setting

As I understand it, that second draft is the bleeding edge and is not settled. What do you think of adding support for the previous version of the spec since that is the one that I think is currently stable.

**Comment by joeyparrish** [comment]
No reason we can't support both for now.

**Comment by ismena** [comment]
@sanbornhnewyyz should be good to go now.
