### ISSUE TITLE
Widevine: Making a single key request for content encrypted with multiple unique keys

### ISSUE THREAD

**Issue by kidmiracleman** [google/shaka-player#479]
Hi,

We are looking at 2016 requirements for a Widevine based DRM deployment and using a separate encryption key for each representation.  We would like it if ShakaPlayer would make only a single key request for such content, given that the recommendations and reference implementation for Widevine shows that we should return ALL keys associated with a specific content_id (regardless of the initData (PSSH) used to initialise the EME Session.

Currently, if the player makes multiple key requests asynchronously  - it interferes with our backend device management implementation  - based on the recommended PCT functionality if the device has not been encountered by the system before...

Thanks in advance for any help/suggestions you may have.

kid_mm

**Comment by joeyparrish** [comment]
To clarify, I do not believe you need a different key for each representation.  I believe you need a different key for each group of representations with different security requirements.

For example, if HD requires hardware security, UHD requires HDCP 2.x, and SD is available everywhere, then you need three different video keys.  If the security policies for video are the same regardless of resolution, you can have one video key.

Different keys require different AdaptationSets according the DASH IOP docs, if I understand correctly.  Shaka supports AdaptationSetSwitching to indicate which sets should be grouped together for adaptation purposes.  Without this, only one video AdaptationSet will be used, so this is important.

Also, you should always have different keys for audio than video.  Audio is typically not protected as strongly video, so they should always use different keys.

**Comment by joeyparrish** [comment]
As for license requests, Shaka Player can't know what's in the payload of the init data.  It has no access to any Widevine-specific fields, such as content ID.  From JavaScript, that's all opaque.

Shaka Player must make a license request for each unique init data because there is no way to know what exactly it contains.  So if your PSSHs are all different, we have to make multiple requests.

If Widevine init data contains a content ID that can be used by the server to look up all keys for that piece of content, then only one request should be necessary.

Init data in the manifest overrides init data in the content.  If init data is present in the manifest, the init data in the content will be ignored by Shaka Player.

So the best thing you can do is use one consistent init data value containing a Widevine content ID.  That value should appear on every AdaptationSet in the manifest.  With this setup, Shaka Player will only make one license request.

**Comment by kidmiracleman** [comment]
Thanks for looking at this Joey,

I am concerned mainly with using a different key for audio/video as per the guidelines...


I assume you are referring to the initData 'filtering' logic in  drm_engine.js?

if we only add a content_id to our Widevine PSSH payload  is this enough to trigger this logic? it seems from looking at content_protection.js  that 'cenc' compliant content protection elements have the entire PSSH set as the initData?  so If the keyIDs  (in the PSSH header)are different  the initdata will be different ?

Or do we need to put the same KeyID in the PSSH header regardless?

**Comment by joeyparrish** [comment]
Yes, the filtering logic in DrmEngine makes sure we only request licenses for unique PSSHs.  The init data in the manifest needs to be the entire PSSH, not just a content ID.

**Comment by joeyparrish** [comment]
@kidmiracleman Is this still an issue for you or can we close it?

**Comment by kidmiracleman** [comment]
Hi,

You can close this.  Thank you for the help!
