### ISSUE TITLE
Controls not work

### ISSUE THREAD

**Issue by voltan** [google/shaka-player#488]
Hello

I setup shaka player on my project , when I try use it controls not work true, browser player loaded and control media and shaka loaded under video and not work.

I use version 2 beta 3 and this settings : 

```
<script type="text/javascript" src="http://localhost/local/pi/pi-25/www/asset/module-video/player/shaka/shaka-player.compiled.js?1471427461"></script>
<script type="text/javascript" src="http://localhost/local/pi/pi-25/www/asset/module-video/player/shaka/controls.js?1471427461"></script>
<link href="http://localhost/local/pi/pi-25/www/asset/module-video/player/shaka/controls.css?1471427461" media="screen" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

<div class="clearfix">
                    <div id="videoContainer" class="overlay-parent">
                        <video id="video"
                               poster="//shaka-player-demo.appspot.com/assets/poster.jpg"
                               autoplay controls></video>
                        <div id="giantPlayButtonContainer" class="overlay">
                            <button id="giantPlayButton" class="material-icons">play_arrow</button>
                        </div>
                        <div id="bufferingSpinner" class="overlay">
                            <svg class="spinnerSvg" viewBox="25 25 50 50">
                                <circle class="spinnerPath" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
                            </svg>
                        </div>
                        <div id="castReceiverName" class="overlay"></div>
                        <div id="controlsContainer" class="overlay">
                            <div id="controls">
                                <button id="playPauseButton" class="material-icons">play_arrow</button>
                                <input id="seekBar" type="range" step="any" min="0" max="1" value="0">
                                <button id="rewindButton" class="material-icons">fast_rewind</button>
                                <div id="currentTime">0:00</div>
                                <button id="fastForwardButton" class="material-icons">fast_forward</button>
                                <button id="muteButton" class="material-icons">volume_up</button>
                                <input id="volumeBar" type="range" step="any" min="0" max="1" value="0">
                                <button id="castButton" class="material-icons">cast</button>
                                <button id="captionButton" class="material-icons">closed_caption</button>
                                <button id="fullscreenButton" class="material-icons">fullscreen</button>
                            </div>
                        </div>
                    </div>
                </div>

<script>
    var manifestUri = 'http://[WOWZA_IP]:1935/[MY_APPLICATION]/_definst_/mp4:http2/upload/video/file/2016/08/media-57b40cc11a116.mp4/manifest.mpd';

    function initApp() {
        // Install built-in polyfills to patch browser incompatibilities.
        shaka.polyfill.installAll();

        // Check to see if the browser supports the basic APIs Shaka needs.
        if (shaka.Player.isBrowserSupported()) {
            // Everything looks good!
            initPlayer();
        } else {
            // This browser does not have the minimum set of APIs we need.
            console.error('Browser not supported!');
        }
    }

    function initPlayer() {
        // Create a Player instance.
        var video = document.getElementById('video');
        var player = new shaka.Player(video);

        // Attach player to the window to make it easy to access in the JS console.
        window.player = player;

        // Listen for error events.
        player.addEventListener('error', onErrorEvent);

        // Try to load a manifest.
        // This is an asynchronous process.
        player.load(manifestUri).then(function() {
            // This runs if the asynchronous load is successful.
            console.log('The video has now been loaded!');
        }).catch(onError);  // onError is executed if the asynchronous load fails.
    }

    function onErrorEvent(event) {
        // Extract the shaka.util.Error object from the event.
        onError(event.detail);
    }

    function onError(error) {
        // Log the error.
        console.error('Error code', error.code, 'object', error);
    }

    document.addEventListener('DOMContentLoaded', initApp);
</script>
``` 

![snapshot77](https://cloud.githubusercontent.com/assets/562083/17732681/42dd4eb2-6488-11e6-9159-f44a98dff3a0.png)
![snapshot78](https://cloud.githubusercontent.com/assets/562083/17732682/42ea89b0-6488-11e6-94c7-f1eef7205de6.png)

anyone can help me to fix it?

**Comment by raskri** [comment]
Map the buttons?
var playPause = document.getElementById('playPauseButton');
playPause.on('click', function(){
document.getElementById('video').pause();
});
...

**Comment by joeyparrish** [comment]
@voltan, can you please explain what the problem is?  Here's a checklist for writing a bug report:

1. Steps to reproduce the problem, including URLs of any necessary apps, manifests, or license servers
2. Expected behavior
3. Actual behavior

**Comment by joeyparrish** [comment]
@voltan, can you please provide us with details to reproduce your issue?

**Comment by voltan** [comment]
Yes , I am sorry for may late answer , I have other problem by wowza ssyetm ( here : https://www.wowza.com/forums/showthread.php?51481-Player-not-work-on-SSL-pages )

But this check page http://www.cafeyab.com/wowza.html , shaka player work and play stream video , but navigation not work true

**Comment by joeyparrish** [comment]
What do you mean by "navigation not work true"?  This phrase does not mean anything to me.

Please provide the following information so that we can understand the issue, reproduce the issue, and help you fix it:

1. Specific steps to reproduce (for example, "load the page, click play, seek to time 5, etc")
2. Expected behavior (for example, "the video should seek to time 5")
3. Actual behavior (for example, "instead of seeking to time 5, the video seeks to time 50")

**Comment by voltan** [comment]
![got27](https://cloud.githubusercontent.com/assets/562083/18287558/dd7f60ea-748c-11e6-8433-da8343e644ab.png)

please see red box , its player controller, it loaded under firefox html5 video player area and not work ( please refresh that page for test ) , but on your example player load complete
------
just , do you have any information about my problem by SSL , its from wowza or player? https://www.wowza.com/forums/showthread.php?51481-Player-not-work-on-SSL-pages

**Comment by joeyparrish** [comment]
@voltan, we really want to help you.  It would have been much easier to help you if you had given us the information we asked for.  In your wowza forum post, you mentioned that the player fails when you load it via HTTPS, but not in plain HTTP.  This is critical information that you did not give us here.  In fact, when you linked us to your page, your link was plain HTTP, not HTTPS.

When I go to the HTTPS URL https://www.cafeyab.com/wowza.html I can see the problem immediately.  The video never loads.  (This would also be a useful description of the problem.)

Looking at the JS console in Chrome, the problem is immediately obvious.  I see these error messages:

> Mixed Content: The page at 'https://www.cafeyab.com/wowza.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://74.84.137.41:1935/faragostaresh/_definst_/mp4:cafeyab/video/2016/09/media-57ca5d223d635.mp4/manifest.mpd'. **This request has been blocked; the content must be served over HTTPS.**

Here, Chrome is telling you exactly what went wrong and how to fix it.  If the page is served over HTTPS, everything else must be over HTTPS, too, for security.  Browsers require this, not Shaka Player, and not Wowza.

Here is a page on MDN that explains all about mixed content, what it means, and why it can be dangerous:  https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

The solution is to serve everything (page, manifest, media) over SSL.

**Comment by voltan** [comment]
thank you very much for this informations , let me time today to work on it

**Comment by voltan** [comment]
thank you very much , its seems we need setup SSL on wowza first, I try do it and tell you result 

thank you for your help

**Comment by voltan** [comment]
Hello

I solve my problem by SSL and setup demo website for better test , please check this link : http://media.cafeyab.com/video/essse-caffe-12

If you check the page, player loaded and play video true, but player skin is default browser skin , player controller loaded under player and not work , hope I can explain my problem true, I think I had mistake on setup player , but could not find that

![got35](https://cloud.githubusercontent.com/assets/562083/18386995/2f78dc0e-76af-11e6-909a-c6cbf5184f64.png)

**Comment by joeyparrish** [comment]
The video tag has built-in controls if you set the `controls` attribute on the tag.  If you omit `controls`, the browser built-in controls do not show up.

The player library does not have its own custom controls as part of the library.  The demo app does have custom controls, but they live outside the library.

The demo app controls have three parts: some HTML in demo/index.html to define the layout, CSS in demo/controls.css to define the style and positioning on to of the video, and demo/controls.js contains the logic.

If you want the built-in controls from the browser, use `<video ... controls>`.  If you want custom controls, omit the `controls` attribute.

If you want to use the custom controls from our demo app, make sure you are using all three pieces.  We don't offer support for the demo app controls outside of the demo app, since it's not part of the library.  However, you can use the demo app as a working example of how to set up these controls.  Don't forget to include the JavaScript and CSS, and don't forget to initialize them:

```js
var myControls = new shakaControls();
myControls.init(castProxy, onError, onCastStatus);
```

**Comment by voltan** [comment]
Thank you for your informations and replay, I try active control by this method and ask my team to  decision about it , But I think will we use browser controls

Thank you very much
