### ISSUE TITLE
Using tracks for multiple video angles, rather than adaptation

### ISSUE THREAD

**Issue by customlogic** [google/shaka-player#495]
Hi,

Thanks for the great library. I have a question about how Player.selectTrack() behaves when changing to a new track and retaining the existing bufferer. 

From what I can tell, the current behavior is:
1) select new track via player.SelectTrack([TRACK], false)
2) new track begins downloading while old track continues to play
3) Once new track has buffered, player continues to play what it has buffered of the old track until that runs out
4) Player swaps to the new track (without any firing any events)

Is this the intended behavior? It can be problematic because there may be quite a bit of old track buffered, so the swap can take 10-20s to take effect.

It'd be great to have the tracks swap as soon as the new track has buffered, and also to be notified via an event when this has happened.

**Comment by TheModMaker** [comment]
The tracks (`player.getTracks`) change immediately.  The new tracks will be used to download new segments, but the old segments will still be in the buffer.  The second argument to `player.selectTrack` is whether to clear the buffer.  Passing `true` will clear the buffer so the resolution change is immediate, but the player will enter a buffering state until the new segments are downloaded.

We do not download segments that have already been downloaded.  So if we have buffered seconds 10-20 and the tracks change, we will download seconds 20-30 in the new resolution.  We could alter the second argument to give a length of time to keep buffered (i.e. passing 10 will keep 10 seconds of the old resolution).

As for an event, the track change happens immediately.  Are you talking about when the video display resolution changes?  We do not control that.  All we do is append the media data into the video element.  The video element will display whatever is at the current position.  When you call `player.switchTrack`, the video resolution will change because the new segments being appended have a new resolution.

**Comment by joeyparrish** [comment]
Why are you calling `player.selectTrack()` in the first place?  It's not clear what you're trying to accomplish.  If you can explain to us what your use case is, we can recommend how to go about it or consider enhancements to meet your needs.

By default, the player should be making ABR decisions for you.  In fact, because of that, `player.selectTrack()` disables ABR to turn control over to the app.

Think of it like this: if your app has a resolution UI, and the default setting is "auto", the player will decide how and when to switch resolutions.  If the user changes from "auto" to "720p", you call `player.selectTrack(...)`.  And since the user clicked that button, they probably want to see that change immediately, so you pass `true` for the second argument.  If the user changes back to "auto", you call `player.configure({abr: {enabled: true}})` to return control to AbrManager.

Does that make sense?

**Comment by customlogic** [comment]
Hi guys,

Thanks for the quick and detailed responses. My use case is probably a bit outside of what the player was designed for. Rather than using 'tracks' to store different quality levels of the same content, I'd like to store different content in each track that the user can change between during playback. For instance, different angles of a sporting event (sideline view, helmet cam, coach cam) or band members performing a song (singer, bass player, drummer). 

For these use cases, its important that audio and video stay perfectly in sync. Also, you don't want to download video you're not watching. So streaming video feels like the right tech to use. 

But in order for it to work seamlessly, it'd be ideal for the new track to play as soon as it has buffered enough data, regardless of how much data of the old track has buffered. So the change should happen as fast as possible, but never cause a pause for buffering (The YouTube player does this when you manually change quality levels). 

Also, the app needs to know when the swap has happened, so it can update UI elements, etc. An event would be useful for this. Or I suppose the app could poll the Player every frame to see which track is currently being displayed?

**Comment by joeyparrish** [comment]
What you're doing is definitely not what tracks were designed for.

The player feeds segments to MediaSource and the browser handles decode and render.  The video element can tell you what resolution it is currently displaying, so in the case of tracks representing different resolutions, that is the indication of what track is being rendered right this moment.  The player really only knows what track is selected, and fetches new segments from that track.

The only way you can know what is being rendered right now without relying on resolution is to clear the buffer any time you switch tracks.  Then the thing being rendered is always what is selected.  This has drawbacks.

If you clear ahead of the playhead but very close to the playhead, you can encounter buffering or in some browsers just a visual stutter.

If you clear everything, you will definitely buffer, but there is no undue or unpredictable visual stuttering.  And if you control the content encoding, you can significantly reduce the amount of buffering.  I recommend 2-second segments and a `minBufferTime` of 2s.  This will allow the player to resume relatively quickly when you change tracks.

You simply can't have a seamless transition that is also immediate.  No browser gives you the ability to do that today.  But with small segments and a low minBufferTime, you can make it as good as possible.

**Comment by customlogic** [comment]
Thanks for that explanation. It sounds like I'll need to find another way to swap between different content.

In regards to a seamless swap between tracks, is there something inherent in MediaSource that prevents the downloading of segments that are already buffered?  I'm just imagining a scenario where you have seconds 0-20 buffered for track A. At 10s, the user asks for track B. We stop downloading track A and start downloading track B from second 10, while track A continues to play. When track B has buffered enough to play through smoothly, we then swap to displaying track B at whatever time it is now. Depending on bitrate and download size, this might happen while track A is at second 11, 14, 17 etc. 

I can understand if this isn't something you feel is appropriate for the Shaka player, but I'm just curious if its even possible.

**Comment by joeyparrish** [comment]
MediaSource doesn't download anything.  The app's JavaScript does that.  In Shaka Player, that's StreamingEngine via NetworkingEngine via XMLHttpRequest.  So Shaka Player is always in control of what we download when, and we feed those downloaded segments to MediaSource to be decoded and displayed.

The problem is that your ideal API of "switch now" doesn't exist.  You can feed segments to MediaSource, and you can clear some range of buffered content.

When you feed a segment to MediaSource that overlaps with something already buffered, you don't have control over what gets displayed.  The browser may show the new data right away, or it may continue to show the old data until a keyframe, or until a segment boundary, or until the old data runs out.  In JavaScript, there's no visibility into this, and no control over the decision.  It's up to the browser's implementation.

What we've found in practice is that to get a smooth transition in most browsers today, you must either:
  1. Avoid overlapping data, OR
  2. accept an unknown latency for the transition, OR
  3. clear some data from the buffer to force that transition.

Avoiding overlapping data saves you bytes.  You don't download any time range you don't already have.  But if you've already buffered, say, 30s, you can't upgrade the visual quality for that long.

You can download overlapping data starting at the current time, but that gets tricky.  At 10s into the clip, you have buffered ahead 30s more (up to 40s).  You find you have just enough bandwidth to keep up with 720p, so you start downloading 720p at 10s.  By the time you've downloaded the 10s segment from 10-20, the play head is now at 20s.  You'll never get ahead of the old data to see that change happen, and at 40s you'll go into a buffering state.

If you clear all the buffered data, you'll see a stutter that lasts as long as it takes to download `minBufferTime` of data, but the upgrade is immediate.

There is a trick to get the transition latency lower by calling `abort()` without any operations running.  According to spec, this should reset the decoder so that it is ready to parse the new data and replace the old data right away.  But this only works on Chrome, Opera, and Firefox.  On IE & Edge, this has no effect, so you see a very noticeable stutter when the transition happens.  On Safari, it throws an error and refuses to decode any more.

What we have found to be the best balance is to clear everything about 10s ahead of the play head, which generally covers one segment or more.  IE and Edge seem to transition without a visual stutter so long as you leave at least one segment in buffer.  This keeps the transition latency down to 10s.  We still call `abort()` to reset the decoder on Chrome, Opera, and Firefox.  On Safari, we avoid calling `abort()`.

This is the most complex thing about MediaSource as far as I can tell, and largely because of implementation differences.

Because Shaka is meant to adapt between different Representations of the same visual content, a little latency is acceptable.  The change is typically not driven by the user and the latency doesn't interrupt the user's experience at all.

For your case, you are switching between different visuals, and at the user's request.  So you want the lowest possible latency.  Sadly, you can't have that without at least a little interruption.  The best way you can minimize latency and minimize visual interruptions is to reduce the segment size and `minBufferTime` as much as possible and to completely clear the buffer when you switch.  I recommend 2s segments and 1.5s `minBufferTime`.

**Comment by customlogic** [comment]
Thank you for the very detailed explanation and helpful advice.  The difference in `abort()` implementation sound like a real pain (the joy of web development, eh?), but it sounds like you guys have found a good way to handle it. 

Thanks again!

**Comment by joeyparrish** [comment]
Happy to help.  Good luck with your project!
