### ISSUE TITLE
[clock sync] Live streams delayed

### ISSUE THREAD

**Issue by raskri** [google/shaka-player#497]
Using 2.0.0-beta3.

What ever I set in the player.configure({streaming: {..}, abr: {defaultBandwidthEstimate: .... }...}), I always have to wait for about 10 seconds before the live-stream starts(logging player.getStats().bufferingTime). 

If I jump back in time in the stream, it starts right away. Also when i use player.load(manifestUrl, some_valid_number_in_the_live_stream) the stream starts right away.

I took a **quick** look in the source code... and found that playHead deep down is using getLiveEdge_ (presentation_timeline) and this is using the javascript Date.now(). And just for fun I adjusted my OS native time 10 seconds back. Now the stream starts right away.

Is there a setting for this? or this is a bug? My dash-streams work perfectly on v1.6.5.

Discussed here: https://groups.google.com/forum/#!topic/shaka-player-users/IjpX5i3sLhw but this is kind of urgent for me so I'm "re-posting" here.

Thanks

**Comment by raskri** [comment]
Changed title

**Comment by TheModMaker** [comment]
If adjusting the native clock fixed it, this is probably a problem with clock sync.  Your browser and server have to have the same time in order to play live streams correctly.  You can either Include a `UTCTiming` element in the manifest or set the [`.manifest.dash.clockSyncUri`](https://github.com/google/shaka-player/blob/master/externs/shaka/player.js#L296) configuration value to your server.

See [this comment](https://github.com/google/shaka-player/issues/376#issuecomment-218382129) for more info.

**Comment by raskri** [comment]
I really cant change anything on the server, as it works for 1.6.5 it should work with 2.0.0.

**Comment by joeyparrish** [comment]
To clarify: you don't have to change anything on your server.  But your client and server must be in sync for live streaming to work correctly.

Clock sync worked differently in v1.6.5 than in v2.  In v1, clock sync was implicit and hacky.  We used a Date header on the manifest for clock sync, which had two critical disadvantages:

1. introduces potential CORS problems that the app can't directly control
2. some servers do not return the current time in the Date header, but rather the creation time of the file, which can actually make clock sync *worse*

In v2, clock sync is explicit.  Either the manifest specifies the clock sync method via a `UTCTiming` element, or the app configures the clock sync endpoint using `.manifest.dash.clockSyncUri` in the player config.  Either way, the choice is explicit and in the app's control.  (Our demo app performs clock sync against our own appspot server so that we can demo third-party live manifests.)

If you don't have clock sync configured through one of these two methods, Shaka Player will emit warnings to tell you that this is a problem you should address.

**Comment by raskri** [comment]
Thanks for the info Joey!
