### ISSUE TITLE
Shaka Player v2.0.0-beta3. Recursive stream load.

### ISSUE THREAD

**Issue by LuckyHamster** [google/shaka-player#499]
If  presentation time stamp in stream > 0 (in my stream 1,4s) it start recursive download first stream сhunk and fail start stream   ##play.

Version: Shaka Player v2.0.0-beta3
Stream: mpd + widevine
Browser: all supported

**Comment by joeyparrish** [comment]
What do you mean by "recursive download"?  Can you provide a manifest URL that reproduces the issue?

**Comment by LuckyHamster** [comment]
Hi, stream example - http://185.5.40.103/DASH_encrypted/SER_03271/video.mpd

**Comment by joeyparrish** [comment]
"Recursive download" is not a term that means anything to me.  What I observe using the [latest nightly build](http://nightly.shaka-player-demo.appspot.com/demo/) is that we buffer 30s of content (the default).  Since your clip starts at 1.4s, we appear to be buffering from 1.4s to 31.4s.

Content should always start at zero.  From Shaka's point of view, this is badly-packaged content.  This could be corrected by using `presentationTimeOffset` in the manifest.  You could also use the optional `startTime` parameter in `player.load()` as a workaround to start playback at 1.5s.

I also noticed one other odd thing about your manifest.  According to the DASH spec, the `lang` attributes in the manifest contain a language code, not a language name.  For example, in your manifest I see `lang="English"` and `lang="Русский"`.  These should be `lang="en"` and `lang="ru"` respectively.

I strongly recommend that you report these two bugs (non-zero start time, language codes) to whomever wrote your encoder/packager software.  Please let us know if we can do anything else to help.
