### ISSUE TITLE
Log and ignore non-standard WebVTT settings

### ISSUE THREAD

**Issue by robwalch** [google/shaka-player#509]
- What version of Shaka Player are you using?

  - Can you reproduce the issue with our latest release version?
**2.0.0-beta3**

  - Can you reproduce the issue with the latest code from `master`?
**Not sure**

- Are you using the demo app or your own custom app?

  - If custom app, can you reproduce the issue using our demo app?
**Yes**

- What did you do?
**Attempt to play a stream**

  - What content did you load?
    - If custom asset, what manifest and license server URIs?
http://dash.edgesuite.net/akamai/test/caption_test/ElephantsDream/elephants_dream_480p_heaac5_1.mpd

  - How did you interact with the content, if at all?
```js
var player = new shaka.Player(video);
player.configure({
  manifest: {
    dash: {
      customScheme: function() {return null;}
    }
  },
  drm: {}
});
player.load(url).then(noop, handleError);
```
- What did you expect to happen?
**Stream plays. Is still plays in v1.6**

- What actually happened?
Error: `Shaka Error NETWORK.HTTP_ERROR (http://dash.edgesuite.net/akamai/test/caption_test/ElephantsDream/elephants_dream_480p_heaac5_1.mpd)`

**Comment by joeyparrish** [comment]
The error you're getting is a mixed content error.  Here's a repro:

https://shaka-player-demo.appspot.com/demo/?play;asset=http://dash.edgesuite.net/akamai/test/caption_test/ElephantsDream/elephants_dream_480p_heaac5_1.mpd

Note that the player is HTTPS, but the manifest is HTTP.  Here's a link to learn more about mixed content, and why browsers don't let you do it: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

If I load both player and manifest over plain HTTP, I see the error INVALID_TEXT_SETTINGS:

http://shaka-player-demo.appspot.com/demo/?play;asset=http://dash.edgesuite.net/akamai/test/caption_test/ElephantsDream/elephants_dream_480p_heaac5_1.mpd

This appears to be caused by your VTT captions, specifically this line:
`00:01:16.042 --> 00:01:18.083 A:start S:25%`

The abbreviation of "align" to "A" and "size" to "S" is out of spec.  See https://w3c.github.io/webvtt/#cue-settings for correct formatting.

**Comment by robwalch** [comment]
Thanks Joey! Sorry I didn't notice the mixed content issue.

For the VTT issue I'm curious if the exception comes from the video tag or text tracks and if it breaks playback. In general all errors we catch or handle from shaka stop playback. If there are any we could just log without interrupting playback we'd want to keep track of these.

**Comment by joeyparrish** [comment]
Most browsers only support WebVTT natively, while a few others only support TTML natively.  We parse cues ourselves and feed them to the browser's TextTrack.  That way, we can support the same set of text formats (WebVTT and TTML, in text or in MP4) regardless of what the browser supports natively.

The INVALID_TEXT_SETTINGS exception is thrown by the VTT parser in Shaka Player.  [shaka.media.VttTextParser.parseSetting](https://github.com/google/shaka-player/blob/17d63566/lib/media/vtt_text_parser.js#L133) fails to parse the settings, returns false, and [shaka.media.VttTextParser.parseCue_](https://github.com/google/shaka-player/blob/17d63566/lib/media/vtt_text_parser.js#L111) throws the exception.

**Comment by robwalch** [comment]
OK. Sounds valid. We do the same in jwplayer when side loading VTT tracks to avoid CORs issues (video src origin is not always the same as the text track scr).

I think our handling of cue parsing a little more lenient. @egreaves correct me I'm wrong - If we can't parse positioning info we ignore it.

@joeyparrish I'm not sure if this track would break video playback but if this is the intended behavior then I'm happy to close this issue.

**Comment by joeyparrish** [comment]
We could always log a warning and ignore bad settings instead of emitting an error.  Would that be helpful?

**Comment by joeyparrish** [comment]
Ping!  @robwalch, would it be helpful to log and ignore when we encounter bad settings?  Or are we okay with dispatching an error?

**Comment by robwalch** [comment]
It would be helpful to log and ignore.

**Comment by joeyparrish** [comment]
Okay, can do.

**Comment by ismena** [comment]
@robwalch Done! No errors anymore.

Let us know if you have any questions.
