### ISSUE TITLE
Chromecast API to force-disconnect

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#523]
- What version of Shaka Player are you using? 2.0.0

  - Can you reproduce the issue with our latest release version? Yes

  - Can you reproduce the issue with the latest code from `master`? Yes

- Are you using the demo app or your own custom app? own custom app

  - If custom app, can you reproduce the issue using our demo app? It's not verifiable because has not shakaDemo.castProxy_.destroy()

- What did you do? Start to reproduce any video, and cast the video. Call to shakaDemo.castProxy_.destroy()

- What did you expect to happen? Chromecast session should be destroyed

- What actually happened? Chromecast session remains open

**Comment by joeyparrish** [comment]
Destroying the proxy does not destroy the remote session because you might wish to leave it open.  Many cast apps allow the sender to be shut down while allowing the receiver to continue running.

However, it appears we don't have a method on CastProxy to force the receiver to shut down.  We can definitely add that.
