### ISSUE TITLE
How do I add additional query params or headers?

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#531]
Hi,

I am using shaka V2 player to play DRM videos from aws s3. For that we need the capability set the query parameters in each seqment/manifest request to s3 server.

Now shaka player is removing the query params from the manifest/segment fetch request.

Pls let us know how to solve this issue

**Comment by joeyparrish** [comment]
@sridhard, this feature has already been implemented.  You can register a request filter to modify any network request.  You can modify URLs, headers, and/or request bodies.

See the License Server Authentication tutorial for an example that adds URL parameters to a license request.  You can do the same for a segment request by looking for request type SEGMENT instead of LICENSE.

**Comment by joeyparrish** [comment]
@sridhard, does this answer your question?  Do you still need help with this, or can we close this issue?

**Comment by sridhard** [comment]
Hi,

Thanks for helping.  You can close this issue
