### ISSUE TITLE
Seeking in live streams not possible with browser-provided controls

### ISSUE THREAD

**Issue by birme** [google/shaka-player#532]
Shaka Player 2.x:
When using live MPEG DASH manifests with wall clock-based segment based timestamps (unix timestamp) the AvailabilityStartTime is 1970-01-01 and each segment timestamp is a unix timestamp, e.g. 1474695988.
This causes an unusable timeline in the native controller on Chrome (possibly other browsers as well) and makes it impossible for the user to seek backward by using the native controllers.

Suggested fix is that the application can set a timeshift window (or that Shaka use timeshiftBufferDepth in Manifest) for the native controller. I looked into this a bit and it seems that on Chrome there is no separation from video.timeline and the presentation timeline in the native controller.

**Comment by joeyparrish** [comment]
The issue is that the browser's built in video controls are insufficient for live streams.  You can't tell the browser that the seekable range is anything but 0 - duration.

We recommend implementing your own controls instead.  We have an example of this in our demo app (demo/controls.js).  The Player object has a `seekRange()` method you can poll to see what part of the timeline should be exposed to the user in the controls.

**Comment by birme** [comment]
Ok, thanks for the answer.
