### ISSUE TITLE
6001 error with DRM protected DASH stream on Tizen 5.5 TV

### ISSUE THREAD

**Issue by thomthomgo** [google/shaka-player#5433]
**What version of Shaka Player are you using?**
4.3.8 and reproduced on 4.3.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Not tried.

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Using the demo app on desktop, I can't reproduce. The problem is specific to the samsung environment.

**What browser and OS are you using?**
Mozilla/5.0 (SMART-TV; LINUX; Tizen 5.5) AppleWebKit/537.36 (KHTML, like Gecko) 69.0.3497.106/5.5 TV Safari/537.36

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Samsung The Frame QE50LS03T QLED 4K UHD Smart TV 50’’ 2020
Firmware T-NKMDEUC-2401.1

**What are the manifest and license server URIs?**
Sending through e-mail

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Sending through e-mail

**What did you do?**
I configured a DRM license server and I'm trying to play a protected DASH Live stream. 
The same code base manages to run DASH unencrypted streams on my Samsung TV. 
Also, the same code base manages to run DRM protected streams on my desktop (Chrome 114).

**What did you expect to happen?**
The stream should play.

**What actually happened?**
Shaka raises an error 6001 - "DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE".
I was assuming we had polyfills for older Chrome versions but they don't seem to be working here.

**Comment by thomthomgo** [comment]
I did some additional testing with previous versions and the bug seems to appear from v3.2.0. 

3.1.8 is able to play the stream as expected.

**Comment by thomthomgo** [comment]
Hi ! I'm still facing the issue, could someone have a look? Thanks!

**Comment by joeyparrish** [comment]
I see some differences between v3.1.8 and v3.2.0 in two significant areas:
 - a "content workarounds" class, which is used in particular to work around firmware issues on Tizen
 - the use of the MediaCapabilities API instead of the direct querying of EME for DRM content, which was optional and off by default for v3.1, and required in v3.2+

One other detail I see is that we don't trust the MediaCapabilities implementation on Tizen, and force Shaka Player to use our polyfill.  Is the application correctly installing Shaka Player's polyfills before instantiating the player?  (`shaka.polyfill.installAll()`)

The MediaCapabilities polyfill wasn't forced into use for Tizen until v3.2.10, v3.3.9, v4.0.5, v4.1.3, and v4.2.0.  So any version before these would not be representative of what we are doing on Tizen today.

-----

I'm unable to test on Tizen 5.5, since I don't have a device, so I'll need you to give us some feedback on these:

 - Does the issue reproduce on v3.2.6 (released same day as v3.1.8, with the same fixes)?  Because both branches were being maintained at the same time, v3.2.0 predates v3.1.8 by 9 months.
 - Does the issue reproduce on v3.2.21 (the final release of v3.2)?  This would have every available fix applied until the date when v3.2 was discontinued, and v3.2 had more maintenance releases than any other branch, over a period of 21 months.
 - Does the issue reproduce on v3.3.19 (final release of v3.3)?

-----

Moving back to the latest code from `main`, please try these things:

In lib/polyfill/media_capabilities.js, there is a section particular to Tizen that looks like this:

```js
        } else if (shaka.util.Platform.isTizen()) {
          let extendedType = videoConfig.contentType;
          if (videoConfig.width && videoConfig.height) {
            extendedType += `; width=${videoConfig.width}`;
            extendedType += `; height=${videoConfig.height}`;
          }
          if (videoConfig.framerate) {
            extendedType += `; framerate=${videoConfig.framerate}`;
          }
          if (videoConfig.bitrate) {
            extendedType += `; bitrate=${videoConfig.bitrate}`;
          }
          isSupported = Capabilities.isTypeSupported(extendedType);
```

If you disable this by changing:

```js
        } else if (shaka.util.Platform.isTizen()) {
```

to:

```js
        } else if (shaka.util.Platform.isTizen() && false) {
```

Does this change your results on Tizen 5.5?  If so, that would point to the platform rejecting some extended parameter of your content, such as resolution, framerate, or bitrate, and might make the failure a legitimate one.  That check didn't exist until v3.2.20, v3.3.18, v4.2.9, and v4.3.5.

There is one other thing specific to Tizen you could change.  If you change this section of the same file:

```js
    let canUseNativeMCap = true;
    if (shaka.util.Platform.isApple() ||
        shaka.util.Platform.isPS5() ||
        shaka.util.Platform.isPS4() ||
        shaka.util.Platform.isWebOS() ||
        shaka.util.Platform.isTizen() ||
        shaka.util.Platform.isChromecast() ||
        shaka.util.Platform.isEOS() ||
        shaka.util.Platform.isHisense()) {
      canUseNativeMCap = false;
    }
```

by commenting out the line with `shaka.util.Platform.isTizen()`, does this change your results on Tizen 5.5?  If so, that would indicate some unknown bug in our polyfill, or that the polyfill isn't needed any more on Tizen 5+.

**Comment by thomthomgo** [comment]
Thanks for looking into this Joey. I'll try these changes and report back in the next few days.

**Comment by thomthomgo** [comment]
Hi Joey,
Installing polyfills with `shaka.polyfill.installAll();` did the trick, I'm now able to play the DRM stream with v3.2 and the latest (v4.3.9). Given that, are the remaining tests required ?
Thomas
