### ISSUE TITLE
Can't read body on manifest requests on errors (HEAD request)

### ISSUE THREAD

**Issue by pakerfeldt** [google/shaka-player#547]
Our video backend returns a detailed error message in the manifest request body on errors like `403 Forbidden`. This information is used to tell the user what went wrong and also for internal logging purposes. However, we can't seem to figure out how to get this information using shaka2.0.

The reason to our problem is that shaka does a `HEAD` request to probe the backend for content type to figure out what parser to use. If the `HEAD` request gives `403 Forbidden` shaka won't even do the `GET` request and we will miss out on the detailed message.

We have identified a few different approaches to this problem.
1. Do we really need to make both `HEAD` and `GET` requests? What if shaka could do the `GET` request immediately and re-use the response for parsing later (after figuring out parser type).
2. A way to force a certain parser type immediately. In our case we know that the content will always be dash so there is no point in doing the `HEAD` request at all. 
3. By exporting the dash parser we could pass this in during `load` and avoid probing for manifest type. 

Do you see more approaches or perhaps even solutions to our problem without modifying the source code? We realize that we can possibly do this with a request interceptor and fake a `200` response code to force the client to do the `GET` but it feels extremely hacky.

**Comment by joeyparrish** [comment]
Hi Patrik,

We only do a HEAD request to probe the manifest type if we are unable to deduce the type from the manifest URI's file extension.  If your URI ends with .mpd (not counting any GET parameters), then we will not have to probe with a HEAD request.

We do provide the HTTP response body when there's an HTTP error, but this only works for GET and POST requests.  A HEAD request does not result in a response body, so we can't provide the text.  The best way to get the error text for a manifest request is to avoid the HEAD request.

As you've noticed, [`Player.load()`](http://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#load)  has an optional parameter `opt_manifestParserFactory` that allows you to specify the manifest parser and avoid the registry completely.  We intended this for custom manifest parsers rather than for overriding detection.  This is why we don't export DashParser already.

We'd be happy to export DashParser going forward because that could be useful for other reasons, but we still feel that the best way to solve this problem is to have a recognizable file extension in the URI.

Does this help?

**Comment by pakerfeldt** [comment]
Joey,

Thanks for the response. I believe it might get difficult for us to change our backend at this moment unfortunately. I will discuss this with the team but having DashParser exported would suit us much better.

**Comment by joeyparrish** [comment]
I filed a new issue to export all plugins in general.

**Comment by joeyparrish** [comment]
Closing this issue now.  To track progress on exporting plugins, follow #551.  Thanks!
