### ISSUE TITLE
Can it be used for audio live streaming ?

### ISSUE THREAD

**Issue by frequeradio** [google/shaka-player#566]
Hi !
I just found your project. I had a question, of course you are focused on video streaming but Shaka would it be a good fit for audio live streaming ? Like icecast/shoutcast radio ?

thanks !

**Comment by joeyparrish** [comment]
Shaka Player ingests DASH streams and plays them using a browser's MediaSource API.  Right now we only have a manifest parser for DASH, but you can write plugins to ingest other manifest formats.  Regardless of manifest format, the underlying media must be supported by MediaSource for it to be playable.

If you know what formats and codecs you want to stream, you can see what MediaSource supports on any given browser by opening the JavaScript console and typing something like this:

```js
// AAC:
MediaSource.isTypeSupported('audio/mp4; codecs="mp4a.40.2"');
// Vorbis:
MediaSource.isTypeSupported('audio/webm; codecs="vorbis"');
// Opus:
MediaSource.isTypeSupported('audio/webm; codecs="opus"');
// MP3:
MediaSource.isTypeSupported('audio/mpeg');
```

Are you trying to do Icecast/Shoutcast specifically?  Or just something like that using DASH or HLS?  Although we are focused on video and adaptive bitrate streaming, you can feed in audio-only data or single-bitrate media without any issues.

**Comment by fdambrosio** [comment]
Hello, are you telling that Shaka can play mp3 audio-only files?

**Comment by joeyparrish** [comment]
I'm saying that Shaka plays the file formats that the browser plays.  Shaka does not do any decoding of media on its own.

You can check MP3 support in your browser by running this in the JavaScript console:

```js
MediaSource.isTypeSupported('audio/mpeg');
```

This returns true for me on Chrome on Linux.  I haven't tested other browsers.

**Comment by Brahmasmi** [comment]
Joey, could you please elaborate on how one could play a *cast stream with audio-only data with single bit-rate media? This is assuming that the media source container and codec are supported on the user agent.

I ask this because the basic usage tutorial (http://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html) suggests instantiating a Shaka Player instance with a video element and then loading the player with a manifest URI.

1) From what I understand, a *cast stream may need an audio element since it does not contain any video. The Shaka.Player constructor (http://shaka-player-demo.appspot.com/docs/api/shaka.Player.html) requires an HTMLMediaElement. Would passing an audio element instead of a video one suffice?

2)  A *cast stream does not really have a manifest, it only has a source URL. As such, for the player.Load function call, would passing the source URL instead of the manifest URI suffice?

I am not proficient with javascript but can read and search code. I apologize in advance if this is an obvious case, and would request guidance on getting a working *cast audio only single bitrate setup.

**Comment by joeyparrish** [comment]
Audio-only data is fine.  If the manifest structure contains no video streams, we will still play it.  We have an example of an audio-only file in the demo app ("Dig the Uke").  Single-bitrate, for us, means only one audio stream, as opposed to several in different bitrates.

An audio element is fine.  We actually accept HTMLMediaElement, which is a base class of both HTMLVideoElement and HTMLAudioElement.

To support shoutcast, you would need to write a manifest parser plugin.  A manifest parser plugin is JavaScript code that implements a certain API and plugs into Shaka Player.  It takes a manifest URL, fetches, parses, and interprets that manifest, and produces output in a standard format that Shaka Player's internals understand.  Your plugin would take the source URL and create a manifest object that drives Shaka's StreamingEngine.  If you are not experienced in JavaScript, this might be challenging.

Shoutcast/icecast isn't on our roadmap, so unfortunately, my team doesn't have the resources to create that plugin.  We are here to help with documentation, pointers, and explanations as they relate to Shaka Player.  We are not familiar with the shoutcast/icecast enough to suggest how that would map to our manifest structure, though.

**Comment by joeyparrish** [comment]
Since we are not planning to work on shoutcast/icecast, I'm going to go ahead and close this issue.  If there's anything else we can do to support you as you work on your own plugin for this, please let us know and I'll be happy to reopen.
