### ISSUE TITLE
[Question] Does Shaka demo page not load for anyone else?

### ISSUE THREAD

**Issue by mlondon1** [google/shaka-player#567]
The following URL continues to load in the latest Chrome on mac for me:
http://shaka-player-demo.appspot.com/demo/

Does this happen for anyone else?  Everything else works fine.

The time to first byte for several of the javascript files is 5 seconds.

**Comment by joeyparrish** [comment]
It's working fine for me.  Could it be your internet connection?

Does it load faster in compiled mode?

[http://shaka-player-demo.appspot.com/demo/?compiled](http://shaka-player-demo.appspot.com/demo/?compiled)

**Comment by sandersaares** [comment]
I note that I have also noticed some sluggishness of the demo site from time to time, though it is fine at the moment for me.

**Comment by joeyparrish** [comment]
Compiled mode should load much faster because there is only one JavaScript file to load for Shaka Player instead of 74 individual class implementations.  For fast internet connections, uncompiled mode is usually fine.  It's also necessary to use uncompiled mode for debugging, which is why it's the default on our demo app.  Production deployments should always use the compiled library.

Hope that helps!

**Comment by mlondon1** [comment]
Yes compiled loads much faster.  thanks
