### ISSUE TITLE
Shaka-Player as Video.js tech

### ISSUE THREAD

**Issue by Watch-Video** [google/shaka-player#59]
Is it possible to use this lib as dash tech for video.js player ?

Regards Sascha

**Comment by joeyparrish** [comment]
Hi Sascha,

I'm not deeply familiar with video.js, but I just took a quick look at [their Tech docs](https://github.com/videojs/video.js/blob/stable/docs/guides/tech.md) and I don't see any reason why you couldn't wrap the Shaka Player library in a video.js Tech object.  You could probably start with [their HTML5 Tech implementation](https://github.com/videojs/video.js/blob/master/src/js/tech/html5.js) as a basis.  You would just use DashVideoSource and Player.load() instead of setting video.src.

**Comment by joeyparrish** [comment]
Hi Sascha, did we answer your question to your satisfaction?  If not, please feel free to either reopen the issue or start a conversation on the mailing list.  Thanks!

**Comment by jbroberg** [comment]
Hi guys.

You might enjoy this:
https://github.com/MetaCDN/videojs-shaka-player

Comments/feedback appreciated.

-James

**Comment by joeyparrish** [comment]
Hi James,

It's great to hear that Shaka is useful as a videojs tech.  Thanks for the link!  We'll check it out.
