### ISSUE TITLE
video.autoplay attribute seems to be getting ignored.

### ISSUE THREAD

**Issue by sanbornhnewyyz** [google/shaka-player#61]
Using 1.3.0 it seems as if the autoplay attribute is getting ignored. Using 1.2.x you could set the autoplay attribute on the video and it would get respected but in 1.3.0 I can't get it not to autoplay.

**Comment by joeyparrish** [comment]
Thanks for the report.  We'll have a fix out soon.

**Comment by palmerj3** [comment]
Sorry to re-open this but has this been published to NPM?  Using 1.3.0 http video plays right away after calling "load" in both cases when the "autoplay" attribute is missing and when autoplay=false.

**Comment by joeyparrish** [comment]
The original bug report was against 1.3.0.  It has since been fixed, and we are working toward publication of 1.3.1 with this and many other fixes.  This bugfix release is currently scheduled for May 22.  NPM only gets release versions, but if you need the fix sooner, please feel free to work from the latest sources on github.
