### ISSUE TITLE
Shaka player does not play video when play button is pressed

### ISSUE THREAD

**Issue by sridhard** [google/shaka-player#637]
Hi,

This is continuation of issue #600 and #585 .

@joeyparrish I have updated the latest code today.

If I play the video several times the issue will be reproduced 1 or 2 times (say 1 out of 10 times). When the video is not played if I seek a little the video starts playing.

Since the #600 and #585 ticket was closed I raised a new ticket.

**Comment by joeyparrish** [comment]
@sridhard, if the issue was not fixed, we can always reopen #600.  That is much easier to follow and understand than opening a new ticket which has no history and no description of the bug.

I will close this and reopen #600.  Next time, please just leave a comment on the original issue letting us know that it is not fixed.  We will see the comment in an email update and we can then reopen the issue for you.

**Comment by hghazzi** [comment]
@joeyparrish @TheModMaker I encountered this exact same issue using v2.0.6 as well as master on Chrome 57. Here's the sample stream: https://akadash0-test.akamaized.net/test/clear/test-multi-audio/master.mpd

It is reproducible in the demo page, and verified that this started occurring between v2.0.0 and v2.0.1

Thoughts?
