### ISSUE TITLE
HDCP (output protection) Detection for browsers

### ISSUE THREAD

**Issue by pjdicke** [google/shaka-player#652]
I have a requirement for detecting HDCP capabilities (output protection) and then to downgrading to SD content if it's not supported and I'm wondering how your player handles that detection for browsers?

Does your player have a callback that I can hook into if HDCP fails?

Thanks

**Comment by TheModMaker** [comment]
Unfortunately, there is no browser API to detect HDCP requirements or status.  We have no way of knowing what the current HDCP support is.  But this doesn't matter since we should handle this case for you already.

When we start playback, we will make the EME requests to get the content licenses.  Then the CDM will detect that the license has an HDCP requirement that is not met and will give us an `output-restricted` key status.  We will use this to indicate this stream is not playable and will automatically switch to the SD stream (assuming it is playable).  We won't play a stream that is restricted.

**Comment by pjdicke** [comment]
I can see the key status `output-restricted` status but is that only indicating that an external device is plugged in? 

**Attempt to violate HDCP configuration**
Looking at Netflix (I know they are not using your player but...) when I plugin a USB display adapter to DVI I can see the key status change from `usable` to `output-restricted` but they don't actually downgrade your experience. Stays at HD quality. (Note: Safari displays a HDCP error message) https://cl.ly/0u0b0k3a0T1q

**Valid HDCP configuration**
If unplug the USB display adapter and just go directly to HDMI with a HDCP supported monitor I still see key status as `output-restricted` but still get HD quality playback.
https://cl.ly/3p1J1E3y0q1O

Along with some other testing in a different player it seems that key status `output-restricted` only tells me that I have an external display device connected not that I have actually violated the HDCP policy.

Are you saying if your player detects if an external display device is connect you automatically downgrade to SD regardless if it's a valid HDCP configuration?

Thanks

**Comment by TheModMaker** [comment]
`output-restricted` means that the content is restricted and *might* not be playable.  It depends on where the content is actually being played.  If you have two monitors (with different HDCP support), the video will play on one monitor, but not on the other.  We have no way of knowing what monitor the video is playing on or whether it meets any requirements.  The only way to detect this would be to try to play and try to recover if we get a video error.

**Comment by joeyparrish** [comment]
The right way to do HDCP detection is not to do HDCP detection.  The best practice for DASH is to have different keys for streams with different security requirements.  For example, if your HD streams require HDCP and your SD streams do not, they should have different keys.

The only thing the player knows is the status of a given key.  There is currently no API we could use for more information than that.  So if your HD content requires HDCP and HDCP is not available, the key status will say `output-restricted` and we will choose SD instead.  For this to work, you must have different keys for HDCP-requiring streams.

Netflix does something different, and they can do that because they own the entire stack, including licensing, security, policies, etc, and they know which streams can be played without HDCP and which can't.  What Netflix does is highly application-specific.

What Shaka Player can do is react generically to the information we can get from browser APIs.  So it is very important that you follow DASH guidelines for interoperable content, which includes using separate keys for streams with different security requirements.  If you do that, you don't need to know the status of HDCP for the player to do the right thing.

**Comment by pjdicke** [comment]
Thanks guys, so to be clear when you see a key status of `output-restricted` you skip it and attempt to use the next on if available?

Also, you don't attempt to play and recover in regards to `output-restricted` key statuses?

**Comment by joeyparrish** [comment]
We don't attempt to play any streams whose keys are `output-restricted`.  There's no fallback system if a bad or unusable stream is chosen, so in the absence of information, we act conservatively to avoid a critical failure.

Before we get a license, we assume that the keys for the lowest res streams will be available and usable.  Other video keys are assumed to not be available until we get a `usable` key status.

So using the example of SD keys and HD keys, we will start by streaming the highest SD res achievable based on the bandwidth estimate.  Once we get a license, if that license contains HD keys and they are not restricted, we will allow the AbrManager to choose from the HD streams as well.

Does that help?

**Comment by pjdicke** [comment]
Very helpful @joeyparrish. Thanks man!
