### ISSUE TITLE
shaka player not auto hide control bar in fullscreen mode on Android device

### ISSUE THREAD

**Issue by yiningc** [google/shaka-player#663]
Chrome Version: 57.0.2970.0
OS: Android

This is not observed on other OS, only on Android. It not repro on HTML5 <video> elements on Android.

What steps will reproduce the problem?
(1) navigate to http://shaka-player-demo.appspot.com/demo/
(2) load any video
(3) switch to fullscreen mode

What is the expected result?
after a some seconds, control bar hide away

What happens instead?
control bar stays, not hide away

**Comment by joeyparrish** [comment]
Thanks for filing!

I did some preliminary investigation.  It appears that we may be missing some touch event in the UI somehow when we enter fullscreen mode.  Only happens on Android because it depends on touch events.

**Comment by TheModMaker** [comment]
The problem is that phones do not have a mouse, but browsers simulate them.  The browser will still fire mouse events (e.g. `mousemove`) and it will still use the CSS `:hover` pseudo-class.  When you click the fullscreen button, the controls will get the `:hover` styles; however, the style doesn't get removed until you "click" somewhere else, even if you drag elsewhere.

So if we are getting touch events, we should override the `:hover` styles and hide the controls.

**Comment by joeyparrish** [comment]
This appears to be happening again.
