### ISSUE TITLE
Audio track changes when video bitrate is manually changed

### ISSUE THREAD

**Issue by radiantmediaplayer** [google/shaka-player#681]
- What version of Shaka Player are you using?
2.0.5
  - Can you reproduce the issue with our latest release version?
Yes
  - Can you reproduce the issue with the latest code from `master`?
don't know

- Are you using the demo app or your own custom app?
demo
  - If custom app, can you reproduce the issue using our demo app?
N/A

- What browser and OS are you using?
Chrome 56 on Windows 10

- What did you do?
go to http://shaka-player-demo.appspot.com/demo/
  - What content did you load?
and load Angel One (multicodec, multilingual)
    - If standard demo asset, which one?
Angel One (multicodec, multilingual)
    - If custom asset, what manifest and license server URIs?
N/A
  - How did you interact with the content, if at all?
Load content then select an alternate audio track - let us say DE - after audio has switched then manually switch to another video track

- What did you expect to happen?
audio should still be DE

- What actually happened?
audio resets to EN

I am not sure if this is something we need to code on our side but I would expect the audio track, especially when it is alternate language, to remain the same when video bitrate is manually switched.
Also re-enabling adaptation after an audio track change also restores audio track to EN.

Another question. For a DASH stream with multiple video bitrates and audio bitrates does shakaPlayer.configure({ abr: { enabled: true } }); restore auto bitrate selection for audio and video or only for video? Is there a way to differentiate abr for audio vs. video for a DASH stream that contains both multiple bitrates for audio and video? An example of such stream would the Car Youtube sample from your demo which has 3 audio bitrates and 6 video bitrates.

Thanks

**Comment by ismena** [comment]
Hi, thanks for reaching out.
We have recently refactored our approach to video and audio tracks in order to support HLS.
In the new world rather than treating audio and video tracks separately, we combine them into variants (audio+video combinations).
It hasn't been officially "released" yet, but you can see it at our nightly build: https://nightly-dot-shaka-player-demo.appspot.com and the latest master has it.
The new approach is that you select a language and get all the audio+video combinations in that language. (The default language is the one specified in player configurations).
Same stands for subtitle language.
Hence the answer to your second question: enabling abr will restore both audio and video since we are now treating them as a single unit.

Please take a look at how it works at the nightly build and let me know if you have any questions.
I can also bug @joeyparrish for the estimation on when this change is going to be released if this is something you would like to know :)

**Comment by radiantmediaplayer** [comment]
Thanks @ismena for your reply. I understand. We are good now with what we have based on shaka 2.0.*. I will review the changes for the new audio/video track management when it is officially released. If I have any question with the new system I will open another issue.
