### ISSUE TITLE
Latency on live stream.

### ISSUE THREAD

**Issue by kloertm** [google/shaka-player#695]
- What version of Shaka Player are you using?
Shaka Player v2.0.0-debug
  - Can you reproduce the issue with our latest release version?
yes
  - Can you reproduce the issue with the latest code from `master`?
yes

- Are you using the demo app or your own custom app?
yes
  - If custom app, can you reproduce the issue using our demo app?

- What browser and OS are you using?
Google chrome.

- What did you do?
I generate a mpd using ffmpeg (the content is from a live stream of a device) 
and then I use demo app with custom asset to point to my mpd file link.
the issue is, the demo app can not play the stream nearly realtime.
from the mpd below, that's ~2s duration for a video segment.
so the best case I think the latency at browser side should be very close to 2s if possible.
but I can't reach the goal, the real latency would be nearly 8 seconds.
it seems that's some buffer mechanism in shaka player.
my hope is I can always play latest timeline segment. (I don't care any frame loss due to connectivity for example)
Any idea ? Thank you !

the mpd content would be like this: (the UTCTiming is generated on-the-fly, as same as server time)
http://pastebin.com/NgPA2UvU

**Comment by TheModMaker** [comment]
The manifest you linked is static, not live.  It provides 5.6 seconds of content and will never update.  To make this  be updateable, it needs a `minimumUpdatePeriod` attribute.

The reason there is a delay is related to the `suggestedPresentationDelay` attribute.  This specifies the amount of delay between when the content is being generated and the user is playing it.  When not provided, we give a default of 10 seconds.  You could reduce this by specifying it in your manifest, but see below.

There is probably going to be at least some delay between when you are recording the live stream and the user sees it.  With 2s segments, the new segments will only be available 2s after they are recorded.  Then the app needs to download them and add them to the `<video>` element and only then can the content be played.  Also note that there needs  to be content in the buffer ahead of the playhead in order to play it.  So even with 2s segments, it will be delayed by a minimum of 1 more segment (4s).

The manifest you linked to also uses `<SegmentTimeline>`, meaning that we need to download the manifest and parse it to determine where to get new segments.  This leads to more delay since we need to wait until the next manifet update, download it, parse it, and add the new segments to our internal structure.  It would help if you used `<SegmentTemplate>` with `duration` attribute.

**Comment by kloertm** [comment]
I updated my manifest to be like this:
http://pastebin.com/ax2TkWdh

I tried hack minimumUpdatePeriod to update mpd more quickly (every 1s)
in file shaka.dash.DashParser.prototype.setUpdateTimer_ (set interval always be 1)

and also make sure suggestedPresentationDelay is 0s.

and I also hack shaka.media.SegmentIndex.prototype.find in lib/media/segment_index.js
shaka.media.SegmentIndex.prototype.find = function(time) {
  // we always use last item to reduce latency.
  var r = this.references_[this.references_.length - 1];
  return r.position;

to always return last timeline segment.

but the real latency is also 7 ~ 9 seconds, I have no idea why, I think if latency is 4s, that is acceptable.

**Comment by TheModMaker** [comment]
With an unmodified Player, by setting the `suggestedPresentationDelay` in the manifest, I am able to get latency down to slightly more than the 2s segment duration.  It will usually enter a buffering state quickly and will fall backwards to about 5s.  If you are on the demo page, you can click the current time in the controls to seek to the live edge.

How are you determining the latency?

**Comment by kloertm** [comment]
by setting the suggestedPresentationDelay to be 0s.
I still have 5 ~ 6 seconds at the live edge using demo app.

this is how I benchmark the latency. (you can see the image below)
I compared real-time snapshot with dash player.
http://i.imgur.com/GPGjKqq.jpg

My hope is to reduce the latency as much as possible. Thank you.

**Comment by kloertm** [comment]
I just found that buffer is in html5 video.
so I think that's minimum buffer required.
closing this issue, Thank you.
