### ISSUE TITLE
Interpreting EMSG events

### ISSUE THREAD

**Issue by sanbornhilland** [google/shaka-player#698]
I'm looking for clarification on how to interpret the EMSG events being sent by Shaka, specifically, the timing info.

Shaka sends an event that looks roughly like this:
```
const mockShakaEmsgEvent = {
      type: 'emsg',
      timestamp: 168271.6,
      detail: {
        messageData: [88, 89, 90 ....],
         eventDuration: 0,
         id: 1000300,
         presentationTimeDelta: 0,
         schemeIdUri: "urn:foo:bar:id3:2016",
         timescale: 48000
         value:"0"
      }
    };
```
Does the `mockSkakaEmsgEvent.timestamp` refer to the `timestamp` of the event stream event? Meaning if you take `( timestamp / timescale ) - presentationTimeDelta` it will give the presentation time of the start of the event?

I think my confusion is resulting from several things. The timescale property docs say:
> Provides the timescale, in ticks per second, for the time and duration fields within this box.

There is an `eventDuration` field on the `event.detail` object so I assume that the `timescale` applies to that property. But there is no `time` property on the `event.detail` object so it's unclear to me which time the timescale applies to. Do I need to parse the `messageData` or does the `timescale` apply to the `timestamp` property? 

Part of my confusion also is coming from the fact that I am getting different emsg timestamps for the same sample content from the Chromecast MPL library than I am from the Shaka player.

**Comment by TheModMaker** [comment]
The `timestamp` field is the time the event was created, so has no use here.  `presentationTimeDelta` represents the time (in units of `timescale`) that the event starts.  This is relative to the segment that it is embedded in.  `eventDuration` represents the duration (in units of `timescale`) that the event lasts.

So the presentation times would be: 

```js
startTime = segmentStartTime + (presentationTimeDelta / timescale);
endTime = startTime + (eventDuration / timescale);
```

We should update the docs to be explicit about these fields.  Currently there is no way to get the start time of the segment.  The reason is that the parsing of the `emsg` box is done as a network response filter, which doesn't have access to the segment info it came from.  We should consider providing this info somehow (e.g. parsing the `sidx`).

Do you have a public manifest that has `emsg` boxes?

**Comment by sanbornhilland** [comment]
Okay thanks that makes things a lot clearer.

You can use this test stream: http://demo.yospace.com/quickplay/dash/vod.mpd
