### ISSUE TITLE
Audio only stream not completing in Chrome

### ISSUE THREAD

**Issue by hghazzi** [google/shaka-player#710]
- What version of Shaka Player are you using? **2.0.5**
  - Can you reproduce the issue with our latest release version? **Yes**
  - Can you reproduce the issue with the latest code from `master`? **Yes**

  - Are you using the demo app or your own custom app? **Both**
  - If custom app, can you reproduce the issue using our demo app? **Yes**
  - What browser and OS are you using? **Chrome 56 on macOS Sierra** (Works in Firefox)
  
  - What did you do? 
      Played an audio only stream, and when the stream ends, the `ended` attribute of the `video` tag is `false` instead of `true`. Causes the player state to be stuck in `playing`.

  - What content did you load? 
      **Broken Stream:** `http://dash.edgesuite.net/dash264/TestCases/3a/fraunhofer/aac-lc_stereo_without_video/ElephantsDream/elephants_dream_audio_only_aaclc_stereo_sidx.mpd`
      (More broken streams can be found [here](http://dashif.org/reference/players/javascript/1.4.0/samples/dash-if-reference-player/)

      **Working Stream:** `Dig the Uke` in the demo assets

@joeyparrish Found an old closed issue that sounds pretty similar to this. The Chrome bug ticket it refers to says its been resolved (also pretty old), so haven't found any references that this is a known issue.

**Comment by joeyparrish** [comment]
Here's a quick repro link based on the asset linked above.  Since the content URL is only available in HTTP and not HTTPS, this link uses a proxy to work around mixed content errors:

https://shaka-player-demo.appspot.com/demo/?play;asset=https://cors-anywhere.herokuapp.com/http://dash.edgesuite.net/dash264/TestCases/3a/fraunhofer/aac-lc_stereo_without_video/ElephantsDream/elephants_dream_audio_only_aaclc_stereo_sidx.mpd

I just tested on Chrome 57.0.2987.75 on ChromeOS, and I was unable to reproduce.  I have not tried on Mac yet.

**Comment by theodab** [comment]
I just tested on chrome 56.0.2924.87 on OSX and reproduced the bug. I'll look into it.

**Comment by theodab** [comment]
Further testing shows that this issue does not occur on 57.0.2987.74 (Chrome Beta) or 58.0.3004.0 (Chrome Canary). Chrome 57 is projected for a stable release in mid-March.

**Comment by hghazzi** [comment]
@theodab Awesome, thanks for looking into this!
