### ISSUE TITLE
thumbnail tooltip for shaka player

### ISSUE THREAD

**Issue by nitin02** [google/shaka-player#713]
I can see the issue #559 open which is for adding thumbnail support to the DASH manifest but I am looking for something which can be implemented using JS.

I'd like to know if there's any easier way to achieve it directly with the shaka player's own event functions or the "video" element's events, wherein a thumbnail tooltip can be shown on hover over the timeline.

{Assume that thumbnails are already generated every second and available}

Please let me know if its possible.

**Comment by joeyparrish** [comment]
It is not trivial to create video thumbnails without getting them from the manifest.  If you wanted to create them from the video element itself, you would need an offscreen video element to seek through while copying frames to a canvas.  It would be very complicated, and you would only be able to do so for clear content.

Because of this, we will not try to implement thumbnails without support from the manifest.  If you want to pursue it yourself, though, please feel free.  The beauty of open source is that you can modify it any way you like.  Good luck!
