### ISSUE TITLE
Difficulty building a custom parser

### ISSUE THREAD

**Issue by fernandoneira** [google/shaka-player#716]
I'm building a parser for our custom Json-based manifest format.

For that I have created a class heavily inspired on the existing shaka.dash.DashParser. The initial goal is that, for a given media, we expose the same Manifest object that would be exposed using the existing parser.

It is a bit hard to evaluate this goal, given the complexity of the object (some properties returned are expected to be functions, which may be closures).

Doing a superficial comparison gives us a good result. We return the same object with the exception of some of the internal ids used in the streams, which shouldn't be an issue afaik. 

**What I expected to happen:** 

Segments are fetched correctly and playback starts.

**What actually happened:** 

Somewhere down the line - upon fetching the first segments - the player throws a BUFFER_READ_OUT_OF_BOUNDS error (code 3000, described as "Some component tried to read past the end of a buffer. The segment index, init segment, or PSSH may be malformed.").

**Setup**

Shaka Player v2.0.5-debug
macOS Sierra, custom app running on CEF.

I can provide V2 level logs of this event, for the same media, with and without the custom parser.

**Comment by TheModMaker** [comment]
First, it would really help if you could post the app so we could look at it.  Another thing would be to get a stack trace for the error.  That error can happen in a few places and knowing where it happened would really help.  Lastly, if you could post the result of `JSON.stringify(yourManifest)`, we could see if there is anything wrong with your version of the manifest.

It might be easier for you to not modify the `DashParser` and instead just look at the manifest object definitions.  There is a lot of work in the `DashParser` that wouldn't be needed in your parser.  The manifest is defined in [externs/shaka/manifest.js](https://github.com/google/shaka-player/blob/master/externs/shaka/manifest.js).  Also what might help is looking at the [OfflineManifestParser](https://github.com/google/shaka-player/blob/master/lib/offline/offline_manifest_parser.js); it is much simpler to read and doesn't do much work besides converting a stored JSON object to a manifest object.

**Comment by joeyparrish** [comment]
I agree with @TheModMaker.  It may be easier to start fresh than to fork `DashParser`, which is very complicated.

I don't see any reason for `BUFFER_READ_OUT_OF_BOUNDS` to be thrown, unless you supplied the wrong byte range or URL for an index segment.  It might be best to look at that first, since there are very few paths in the code that would lead to segments being parsed.

**Comment by fernandoneira** [comment]
Hey Jacob & Joey, thanks for your quick & insightful answers. Here's some extra info:

- [error.json](https://github.com/google/shaka-player/files/824842/error.json.txt) error stack
- [manifest_custom-parser_fail.json](https://github.com/google/shaka-player/files/824843/manifest_custom-parser_fail.json.txt), [manifest_default-parser_ok.json](https://github.com/google/shaka-player/files/824846/manifest_default-parser_ok.json.txt) -> comparison of manifest object generated by `.start` with and without the custom parser
- [log_custom-parser_fail.txt](https://github.com/google/shaka-player/files/824845/log_custom-parser_fail.txt), [log_default-parser_ok.txt](https://github.com/google/shaka-player/files/824844/log_default-parser_ok.txt) -> V2-level logs starting right after `.start` returns the promise up until either failure or a bit down the line.

I initially took the approach of writing the parser from scratch as you mention, but got a bit discouraged halfway given that some of the properties seemed non-trivial to obtain (the callback functions). So while we did rewrite chunks of the parser class, we rely on existing methods in other namespaces - such as the `shaka.dash.SegmentTemplate.createStream` method - to create the streams.

(On a side note, this function relies on data passed being presented in XML, which would make sense to change into something more generic if it is intended to be used in custom parsers. I could think of a contribution if this makes sense to you as well).

The offline manifest parsing is definitely interesting. I may be able to replace some parts of our parser that could have something to do with the problem based on the offline implementation.

**Comment by TheModMaker** [comment]
The error is from the `emsg` box reader.  Since WebM never has `emsg` boxes, you should not be adding the emsg response filter for this content.

All the code in the `shaka.dash` namespace is internal to the `DashParser` and isn't intended for general use.  Using them will likely result in problems.  I am working on a tutorial to help with writing manifest plugins, and I will repeat some of it here.

There are three callback functions you need to define for each stream.  These can be any function you want so long as the have the following behavior:

**createSegmentIndex**: This is called exactly once before the other two.  It should return a Promise that resolves once the index is created.  This is used to reduce latency by delaying fetching the index from the server when it needs to.

**findSegmentPosition**: This is given the time (in seconds) relative to the Period start and should return the (number) index of the segment that contains that time, or `null` if not found.  We will increment this number as we stream, we will *not* call this for every segment.

**getSegmentReference**: This is given an index and should return the `shaka.media.SegmentReference` for that index (doesn't have to be the same object each call), or `null` if not found.

To help you define these, I suggest using the [shaka.media.SegmentIndex](https://shaka-player-demo.appspot.com/docs/api/shaka.media.SegmentIndex.html) class.  This accepts an array of [shaka.media.SegmentReference](https://shaka-player-demo.appspot.com/docs/api/shaka.media.SegmentReference.html) objects and defines the find and get methods for you.  For example:

```js
function uri(str) {
  return function() { return [str]; };
}

var refs = [
  new shaka.media.SegmentReference(0, 0, 10, uri('https://example.com/seg1'), 0, null),
  new shaka.media.SegmentReference(1, 10, 20, uri('https://example.com/seg2'), 0, null),
  new shaka.media.SegmentReference(2, 20, 30, uri('https://example.com/seg3'), 0, null)
];

var index = new shaka.media.SegmentIndex(refs);
var stream = {
  createSegmentIndex: function() { return Promise.resolve(); },
  findSegmentPosition: index.find.bind(index),
  getSegmentReference: index.get.bind(index),
  ...
};
```

**Comment by fernandoneira** [comment]
That did the trick @TheModMaker, thanks. I removed all references to the emsg boxes and will look into redoing the segments part based on that code.
That guide sounds like a really helpful tool, I'd be happy to help you with some input on our experience.

**Comment by joeyparrish** [comment]
@TheModMaker, let's send @fernandoneira a preview for additional feedback once we're done with internal review on your new tutorial.

**Comment by TheModMaker** [comment]
@fernandoneira  We just pushed a new tutorial (in d1bc3fd) for making manifest parsers.  If you have any further questions or comments, feel free to ask.

<https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-manifest-parser.html>

**Comment by fernandoneira** [comment]
Excellent news! Thanks for your work @TheModMaker. I'll give this a full read in the coming weeks and rewrite our parser based on it, and let you know of any feedback/questions I come across.
