### ISSUE TITLE
Offline download progress stuck when exceed 10% of free storage on Android

### ISSUE THREAD

**Issue by phamduongnhatnam** [google/shaka-player#747]
- What version of Shaka Player are you using?
2.0.6
  - Can you reproduce the issue with our latest release version?
Yes
  - Can you reproduce the issue with the latest code from `master`?

- Are you using the demo app or your own custom app?
My custom app
  - If custom app, can you reproduce the issue using our demo app?
Yes

- What browser and OS are you using?
Chrome Android, Crosswalk.
Android 6

- What did you do?
I can use the offline feature to store the media content. It has no problem when I store any content that the total size less than ~400mb. The store process will stuck when the device exceed that size without throwing any error. By the way, my device has about 4GB free storage.
  - What content did you load?

    - If standard demo asset, which one?

    - If custom asset, what manifest and license server URIs?

  - How did you interact with the content, if at all?

- What did you expect to happen?
Throw some error when the downloading process can't store the content any more.

- What actually happened?
The download process get stuck without any error happened.

**Comment by joeyparrish** [comment]
Thanks for the report!  We'll look into it.

**Comment by vaage** [comment]
I have been able to repo this using a Pixel XL running Android 7 (N) and Chrome 57.

Since I did not have a single large piece of content, I was able to repo this by download each piece of test content. It finally froze at 43% on "Tears of Steel (external text)".

Considering I still have over 15 GB free on this device, I do not think this has to do with any relative storage capacity, but something specific about the amount of content we are storing.

**Comment by vaage** [comment]
Using "navigator.webkitTemporaryStorage.queryUsageAndQuota" on Android Chrome I have been able to confirm that we are reaching the max storage allotted to us. I am still looking into where the failure is and why we are not getting the error message.

**Comment by phamduongnhatnam** [comment]
hi @vaage, any update for this?

**Comment by vaage** [comment]
Hello @phamduongnhatnam , Thanks for checking in on this again. I am still working on this but got a little side-tracked with another task. I am currently working up the stack trying to find where the failure is. Currently IndexDB always succeeds and there are never any dangling inserts left open - so the failure has to be somewhere else.

**Comment by vaage** [comment]
Hello @phamduongnhatnam , Good news we found the problem and it is something we can and will fix. Just so you know the full story. The hang was caused because the transaction never called oncomplete or onerror. What we overlooked was that it is possible for a transaction to call onabort. It appears that when store.put cannot write to disk the request will call onsuccess but the transaction will call onabort.

We will be updated our code so that if the transaction is aborted it will appear as an error to Shaka Player and should surface the same as any other error.

Thanks again for finding this and being patient while we looked into it.

**Comment by phamduongnhatnam** [comment]
Thanks @vaage and @joeyparrish, your works are awesome!

**Comment by joeyparrish** [comment]
This fix is being cherry-picked to v2.1.1.

**Comment by joeyparrish** [comment]
Also cherry-picked to v2.0.9.
