### ISSUE TITLE
'bufferingStart' should always fire during start-up.

### ISSUE THREAD

**Issue by tdrews** [google/shaka-player#77]
If the video is paused then a 'bufferingStart' event will not fire. This means that if autoplay=false then an initial 'bufferingStart' event may not fire. It is desirable if buffering events fired regardless of whether the video is paused or not.

**Comment by joeyparrish** [comment]
See also #63

**Comment by joeyparrish** [comment]
@sanbornhnewyyz, it seems to me that this is working as it should already.  Here are the cases I tested:

Create a player, do not load anything, and delay 2 seconds.
Create a player, load with autoplay true, and wait for the first frame to play.
Create a player, load with autoplay true, pause, and delay 2 seconds.
Create a player, load with autoplay false, and delay 2 seconds.

In all of these cases, no bufferingStart event is fired and bufferingHistory.length is 0.  Do you think this should be otherwise?  It was originally my intent for this event to fire when the content underruns, but I could be convinced that the initial buffering should count as well.

**Comment by joeyparrish** [comment]
@sanbornhnewyyz: ping!

**Comment by joeyparrish** [comment]
@sanbornhnewyyz: I added some new integration tests to ensure that we are being consistent with the bufferingStart event.  Please reopen if you feel that the use of bufferingStart is incorrect.
