### ISSUE TITLE
getStats().switchHistory is not returning variant tracks ids

### ISSUE THREAD

**Issue by hghazzi** [google/shaka-player#785]
- What version of Shaka Player are you using? **2.1.0**
  - Can you reproduce the issue with our latest release version? **Yes**
  - Can you reproduce the issue with the latest code from `master`? **Yes**
- Are you using the demo app or your own custom app? **Both**
  - If custom app, can you reproduce the issue using our demo app? **Yes**
- What browser and OS are you using? **MacOS/Chrome**
- What did you do? **Called player.getStats().switchHistory`**
  - What content did you load? **Angel One demo asset**
  - How did you interact with the content, if at all? **Loaded demo asset**
- What did you expect to happen? **According to the [documentation](https://shaka-player-demo.appspot.com/docs/api/shakaExtern.html#StreamChoice), When accessing `switchHistory`, it should return a `StreamChoice` with either a `variant` or `text` type**
- What actually happened? **`StreamChoice` is still returning the old format with types `video` and `audio`, with `id`s not matching the `id`s of the chosen variant tracks**

**Comment by hghazzi** [comment]
Since this is marked at v2.2.0, I'd be happy to fork and create a fix, if it can be cherry picked for the next release. I looked over the code that adds the `audio` and `video` tracks to the history, is there anything that would help to point me in the right direction?

**Comment by joeyparrish** [comment]
Yes, I would be happy to take a PR for this.  I would also be glad to cherry-pick the fix to v2.1.x.

**Comment by joeyparrish** [comment]
I looked into this a little as part of #823, which overlaps a lot.  Here's what I found:

 - `Track` ID for variants is taken from `Variant` ID
 - `Track` ID for text is taken from `Stream` ID
 - `Stream` and `Variant` IDs are auto-incremented integers, not from manifest
 - `switchHistory` contains `Stream` IDs only

The crux of the problem is that variant `Tracks` have the `Variant` ID, but the two `Stream`s inside the `Variant` have their own IDs which are only seen in `switchHistory` and can't be correlated to anything through the public API.

**Comment by joeyparrish** [comment]
Changing `switchHistory` to contain variant changes instead of individual audio/video streams would probably suffice.

**Comment by hghazzi** [comment]
Great, I figured it was something along those lines. Will try to get a PR
up in the next week or so.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.1.3.
