### ISSUE TITLE
Stream playing perfectly on Firefox but got error on Chrome

### ISSUE THREAD

**Issue by ducntrinh** [google/shaka-player#790]
- What version of Shaka Player are you using? 2.1.0-debug

- Are you using the demo app or your own custom app? Demo app

- What browser and OS are you using?
Google Chrome 58.0.3029.96 (64-bit), Ubuntu 16.04

- What did you do?
  - What content did you load? http://118.102.6.118/dash/test.mpd
  
   The stream is played perfectly on Firefox 53 but on Chrome, it can't be played, log:

> (video:1) failed fetch and append: code=3014
> Player error shaka.util.Error {severity: 2, category: 3, code: 3014, data: Array(1), message: "Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_FAILED (0)"…}
> Player error shaka.util.Error {severity: 2, category: 3, code: 3016, data: Array(2), message: "Shaka Error MEDIA.VIDEO_ERROR (4,)"…}
/shaka-player/demo/#asset=http://118.102.6.118/dash/test.mpd;lang=en-US:1 Uncaught (in promise) > DOMException: Failed to load because no supported source was found.

**Comment by TheModMaker** [comment]
The manifest specifies a single stream that is muxed with both video and audio.  This isn't supported by us and may not be supported by the browser.  Your manifest also says the stream contains vp9 codec while it also contains vorbis.  Chrome seems to choke on this while Firefox ignores it.

If you open `chrome://media-internals`, it show an error `Audio stream codec vorbis doesn't match SourceBuffer codecs.`  This is because we used the codec specified in the manifest, `vp9`.

You may be able to change the codec to be `vp9, vorbis` in the manifest, but this is not officially supported and may not work cross browser.  You should be separating the audio and video streams into separate streams.

**Comment by ducntrinh** [comment]
@TheModMaker Thank you very much for your detailed answer. I'm gonna close the issue.
