### ISSUE TITLE
Shaka Error MANIFEST.UNPLAYABLE_PERIOD ()

### ISSUE THREAD

**Issue by pszemus** [google/shaka-player#791]
- What version of Shaka Player are you using?
Shaka Player v2.1.0-debug

  - Can you reproduce the issue with our latest release version?
yes

  - Can you reproduce the issue with the latest code from `master`?
Stream plays ok with 2.0.8

- Are you using the demo app or your own custom app?
demo and custom

  - If custom app, can you reproduce the issue using our demo app?
yes

- What browser and OS are you using?
Fedora Linux 24 @ Chrome 58

- What did you do?
Trying to play https://av-cdn-1.wpimg.pl/wptv/preview_2/manifest.mpd

  - What content did you load?
https://av-cdn-1.wpimg.pl/wptv/preview_2/manifest.mpd

    - If custom asset, what manifest and license server URIs?
https://av-cdn-1.wpimg.pl/wptv/preview_2/manifest.mpd

  - How did you interact with the content, if at all?
load

- What did you expect to happen?
stream playing

- What actually happened?
Shaka Error MANIFEST.UNPLAYABLE_PERIOD ()

**Comment by joeyparrish** [comment]
Hi @pszemus,

This piece of content has a video codec of "avc1.4d001f" (aka h.264) and an audio codec of "mp4a.40.34" (aka mp3).  This video codec is supported by the browser, but the audio codec is not.

In v2.0, our internal model kept video and audio separate.  So in v2.0.x, this plays as a video-only clip.

In v2.1, we changed to a model in which video and audio combinations are modeled as variants.  In this model, none of the variants in your content are playable, because all variants use an audio codec that is not supported by the browser.

I don't think it makes sense for us to play in video-only mode or audio-only mode for content that is clearly meant to have both video and audio.  What do you think?

**Comment by pszemus** [comment]
Hi @joeyparrish
I thought the same untill I tried VLC and DASH-IF players that can play that stream as a video-only stream. Nevertheless it's not a bug nor regression, but a feature to consider.

**Comment by joeyparrish** [comment]
Thanks.  We will consider it.

**Comment by joeyparrish** [comment]
@pszemus, I have discussed this issue with our product managers, and we have decided not to pursue support for video-only playback in content that contains an audio stream.  If content contains audio, ignoring the audio without throwing an error would not be a desirable user experience.  The same is true of content which contains unplayable video.  Ignoring the video stream while playing audio-only would not make sense for the end user.

I apologize for any inconvenience this causes you.
