### ISSUE TITLE
Can't change audio language when DASH content has short periods

### ISSUE THREAD

**Issue by tdaines** [google/shaka-player#797]
- What version of Shaka Player are you using? **2.1.1**

  - Can you reproduce the issue with our latest release version? **Yes**

  - Can you reproduce the issue with the latest code from `master`? **Yes**

- Are you using the demo app or your own custom app? **Custom**

- What browser and OS are you using? **Chrome on Win10**

- What did you do?

  - What content did you load? **https://content.uplynk.com/d915916d22e74d16b21cfeb8e1c59adb.mpd (Content is copyrighted so can't share valid playback url)**

- What did you expect to happen?  **After calling `shakaPlayer.selectAudioLanguage('sp')` I expected the audio language to change.**

- What actually happened? **Nothing.**

I believe this is cause by the playhead being in a different period than the period the `StreamingEngine` is downloading from.  Stepping through the code, inside `Player.chooseStreams_()`  `StreamingEngine.getActiveStreams()` returns streams with a `presentationTimeOffset` different from those in the `currentPeriod.variants` objects.  This prevents the `activeVariant` from changing to the new language.

**Comment by joeyparrish** [comment]
@tdaines, can you please email us a link to the content?  We need to be able to reproduce the issue before we can work on a fix.  You can find my email address in the CONTRIBUTORS file.  Thanks!

**Comment by joeyparrish** [comment]
There is definitely a bug here.  I was able to reproduce your issue, but the fix led me to uncover some related issues which are more complicated.  I'm still working through them.

At the top-most layer, you are right.  We are effectively ignoring this request to change language, and this is caused by the fact that we choose streams for the period we are playing, then compare these to the period we are streaming.  This comparison was easy to fix, but it uncovered issues with `StreamingEngine` which I don't fully understand yet.

Thanks for your patience.

**Comment by tdaines** [comment]
Great, thanks for the update @joeyparrish
