### ISSUE TITLE
Ability to play multiple audio streams simultaneously

### ISSUE THREAD

**Issue by bhh1988** [google/shaka-player#799]
I was wondering whether shaka-player allows you to play two audio streams simultaneously (it doesn't look like it can, from what I can tell in the API). If it doesn't, then let this be the issue to track that request :)

This use-case comes up because sometimes videos are recorded with two or more audio streams. For example, an interview between two people, or a directory's commentary in a movie, or a video-gamer speaking in a separate stream. Sometimes you'd want both streams playing, and sometimes you even want to let the user turn one stream off.

What would doing such a thing entail, and how hard would it be?

**Comment by TheModMaker** [comment]
We definitely don't support this.  Adding support would also be difficult since all of our code assumes there is at most one audio stream and at most one video stream.  Even though this may be a useful feature, I don't think we will be able to implement it, at least not soon.

There is a larger problem than our internals.  We use [MSE](https://w3c.github.io/media-source/) to play content.  We create a SourceBuffer to give the media data to the browser to play.  MSE doesn't support multiple audio streams.  If you try to create another one, you'll get an error.  So using MSE alone, it is not possible for us to play the media.

There is a new standard called [Web Audio API](https://webaudio.github.io/web-audio-api/), which allows more control of audio content.  There is a feature to combine audio sources together.  So it *may* be possible to use this to play, but it would require a major refactoring to use.  Plus, we don't want to use this because it isn't supported on IE.

In general, it is preferable for the sources to be combined on the server.  The advantage of having audio and video streams separate is you can have multiple audio stream sources.  For example, to have a movie commentary, you can have one audio stream be the movie by itself and another stream that includes the commentary.  Then you can switch between them using our tracks API.  Also, by setting the Role, you will be able to switch audio streams by Role, see #767.

**Comment by quiz1991** [comment]
@TheModMaker Thanks for the info!

But let's say my master playlist has two audio streams with different mimeTypes(like "audio/aac" and "audio/mp4; ..."), can I remove one audio sourcebuffer and create a new one after playback starts(i can make sure that only one audio sourcebuffer exists at the same time)

**Comment by joeyparrish** [comment]
The MSE spec does not guarantee support for multiple video SourceBuffers or multiple audio SourceBuffers at the same time, and we have never experimented with adding and removing SourceBuffers during playback.  Your mileage may vary.

**Comment by quiz1991** [comment]
@joeyparrish Thanks Joey!

Just to share what we've experimented so far(on our own hls player):
1. Adding more than one audio/video SourceBuffers inside ```onMediaSourceOpen```: Parsed data 
    can be pushed into main audio and video SourceBuffer but playback cannot start
2. During playback:
    a. Removing SourceBuffer is ok
    b. Adding SourceBuffer would cause QuotaExceedError
