### ISSUE TITLE
Problem when defining Authorization header in licence request by registering filter request

### ISSUE THREAD

**Issue by hdodev** [google/shaka-player#802]
Hi! Here is my problem description. Do you have an idea? Thanks in advance for your help.

- Shaka Version : 2.1.1
  - Can you reproduce the issue with our latest release version : YES
  - Can you reproduce the issue with the latest code from `master` : YES

- Are you using the demo app or your own custom app : CUSTOM
  - If custom app, can you reproduce the issue using our demo app : YES

- What browser and OS are you using : CHROME(58)/WINDOWS10

- I try to add an Oauth Authorization header (2 actually) in a licence request by registering a request filter.  player.getNetworkingEngine().registerRequestFilter(function(type, request) {
			if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
			  request.headers['Authorization'] = 'Basic azerty'; ... }}
  - The content is a Live DASH asset

- What did you expect to happen  : 'Authorization' header added in the POST licence request

- What actually happened : Unfortunately it doesn't work, Error DRM (6) - LICENSE_REQUEST_FAILED (6007). When checking the request, no 'Authorization' header, but found header  'Access-Control-Request-Header: authorization, and the POST request becomes an OPTIONS request (?!)

**Comment by joeyparrish** [comment]
@hdodev, this is a CORS issue ([Cross-Origin Resource Sharing](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)).  This is a very common source of confusion for developers.  We even have [a label for it](https://github.com/google/shaka-player/issues?q=label%3A%22CORS%20issue%22%20) in our issue tracker now.

The OPTIONS request is made automatically by the browser, and it's called a [preflight request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests).  In essence, it's asking the server for permission to make the actual request.

The browser is enforcing these CORS rules to prevent someone from inserting malicious code into a page that then contacts a third-party server.  Any request that goes "cross-origin" (from a page in one domain to a server in another) is subject to CORS rules and restrictions.

When you added a custom header to the license request, this triggered the CORS preflight request.  The server must be able to respond to the OPTIONS request with the following headers:

```
Access-Control-Allow-Origin: foo.example.com
Access-Control-Allow-Headers: authorization
```

[`Access-Control-Allow-Origin`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Origin) indicates that your page is allowed to talk to that server.  The server can respond with `*` instead of the domain name to indicate that any origin is permitted.

[`Access-Control-Allow-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Headers) indicates that your page is allowed to send those custom headers to the server.

If you don't control the license server, you can ask the owners of the license service to make it CORS-friendly and refer them to this post for reference.  If they have questions about implementing CORS, I am happy to answer them.

Does this help?

**Comment by hdodev** [comment]
Hi Joey. Yes it's very helpful thank you! I actually have the following responses. Both seems to be linked to CORS, if you can you please confirm.

- On my manifest request I get: 
XMLHttpRequest cannot load http://IP@/m3gqlxmi5aaaaaaaa.../0000000/GlobalManifest.mpd.
The 'Access-Control-Allow-Origin' header has a value 'http://ip03.test.fr:9800' that is not equal to the supplied origin. Origin 'http://127.0.0.1' is therefore not allowed access.

- On my license request I get:
OPTIONS https://tb.licensedrm.fr:3443/v1/licenses (anonymous function) @ shaka-player.compiled.js:251Uf @ shaka-player.compiled.js:250B.g @ shaka-player.compiled.js:34 app-shaka.php:1 XMLHttpRequest cannot load https://tb.licensedrm.fr:3443/v1/licenses. Response for preflight has invalid HTTP status code 405

I don't have access to server configuration, but I can ask for some configurations on the test bed. Do you please have some recommandations for 'Access-Control-Allow-Origin' and 'Access-Control-Allow-Headers' keys ? Put '*'? Put something more restrictive? Thanks.

**Comment by joeyparrish** [comment]
Yes, both of those are CORS issues.

To allow access on 127.0.0.1, you would have to either add an additional header like so:
`Access-Control-Allow-Origin: http://127.0.0.1`
Or change the origin to a star:
`Access-Control-Allow-Origin: *`

Either would work.

The license request issue is that the server returns an error when the browser makes a pre-flight request.  HTTP 405 means "method not allowed".  This would indicate that the server doesn't support CORS pre-flight requests at all (which use the `OPTIONS` method).

**Comment by hdodev** [comment]
Hi Joey, and thank you it's very clear. I will transfer these indications to the platofrm team.
I close this item.
