### ISSUE TITLE
Shaka 2.x.x cannot play DASH stream from Envivio HALO

### ISSUE THREAD

**Issue by fgutierrezw** [google/shaka-player#806]
What version of Shaka Player are you using?
2.0.6 custom.

Can you reproduce the issue with our latest release version?
Yes

Can you reproduce the issue with the latest code from master?
Yes

Are you using the demo app or your own custom app?
Either

If custom app, can you reproduce the issue using our demo app?
Yes

What browser and OS are you using?
Mainly Chrome but issue is reproduce on any browser and OS

What did you do?
Play a live DASH stream

What did you expect to happen?
Playback of a live DASH stream without issues

What actually happened?

Using shaka 2.0.6 custom, i'm unable to play a DASH stream after a few hours of starting the stream.

Stream comes from an Envivio Packager, at the beggining the streams works OK (encrypted and unencrypted) but after being live for around ~12 hours is not possible to decode the stream anymore. Client downloads the manifest, Headers and then chunks, but just shows a black screen, after a few seconds desist to download more chunks and just request a manifest update.

I try with branch 2.0.x same problem.

Shaka branch 1.6.x can play/decode the stream without issue but i get a warning on the console

_live_segment_index.js.download:265 Timestamp correction (858993.586411) is unreasonably large for live content. The content may have errors in it._

Encoders, Packagers and Client are all in sync with the same NTP.

Attached are two manifest
Euro_OK_manifest.mpd -> Example of a live service recently started and working on version 2.x (before the 12 hours limit)

Euro_FAIL_manifest.mpd -> Same service, same input, same packaging process just a different DASH output running since around 20 days ago.

I suspect about MPD@availabilityStartTime and Period@Start and Representation@presentationTimeOffset are not correct for the failed example. But for some reason 1.6.x can avoid that.

I did try a custom build with streaming.jumpLargeGaps enabled to see if there a difference but it didn't work.

If this is not the place to put this kind of issue here, please let me know to remove this post and move it to some other place.

[manifest.zip](https://github.com/google/shaka-player/files/1004702/manifest.zip)

**Comment by TheModMaker** [comment]
I don't see anything wrong with the manifests, but without a live (playable) manifest, it will be hard to determine where the problem is.  If you want, you can send it to me privately, my email is in CONTRIBUTORS and on my profile.

Also, you say `cannot decode`.  Are you talking about problems playing, or actual decoder errors?  If you are getting decoder errors (e.g. Shaka error VIDEO_ERROR, code 3016) there is nothing we can do.  Decoder errors are caused by the browser and usually are caused by bad content.  But if this is playback problems (e.g. infinite buffering), then it may be our problem.

When it shows the black screen, what are the buffered ranges?  Is the `currentTime` inside a buffered range?  If you go to `chrome://media-internals`, does it show anything (select the button that matches `video.src`)?

Also, you mention that `MPD@availabilityStartTime` may be inaccurate.  We required it to be accurate to be able to play.  In v1.x we would try to correct invalid values.  However, this was complicated and hid content bugs.  In v2 we decided not to support these and only play based on the content.  This means that you need to correctly setup clock sync for live streams.

**Comment by fgutierrezw** [comment]
@TheModMaker thanks for the answer.

I will setup a few streams and sent them to you.

I haven´t seen any VIDEO_ERROR, also with a fresh manifest shaka 2.x.x is able to play and decode. So i use a the wrong term, i think it´s more related to a playback problems, the client downloads the manifest, a few chunks but it never start to play the content (updated title of the issue).

I will recollect the other info that you request and i will put it in another post.

**Comment by fgutierrezw** [comment]
output from chrome://media-internals

render_id: 3930
player_id: 7
pipeline_state: kSeeking
event: WEBMEDIAPLAYER_CREATED
url: blob:http://192.168.0.3/baa864c8-f5bf-41ad-834f-b9bedcbc095e
duration: 4294967296
found_audio_stream: true
audio_codec_name: aac
found_video_stream: true
video_codec_name: h264
audio_dds: false
audio_decoder: FFmpegAudioDecoder
debug: Video rendering in low delay mode.
video_dds: false
video_decoder: GpuVideoDecoder

**Comment by TheModMaker** [comment]
An update from emails: this was caused by time sync issues between the manifest times and the segment times.  This is likely a problem with the packager.

@fgutierrezw Did you hear back from the packager?  Is there anything else we can do?

**Comment by fgutierrezw** [comment]
@TheModMaker indeed, it is a bug on an specific version (the one that i have :)) caused when there is  a PTS wraparound. From that moment the out of sync between manifest and chunks appears.

Thanks for the help.
