### ISSUE TITLE
Problems with playing live stream.

### ISSUE THREAD

**Issue by MegaLabs1** [google/shaka-player#807]
Shaka player version v1.6.5
Cannot reproduce it with latest version. Our packager doesn't support shaka 2.x yet. 
Google Chrome browser, latest version.

Trying to play live stream unsuccessful. Got error in shaka player log 
`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().`

Here is MPD Header
`<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" type="dynamic" minimumUpdatePeriod="PT10S" availabilityStartTime="2017-04-28T09:14:51" minBufferTime="PT30S" suggestedPresentationDelay="PT25.00S" timeShiftBufferDepth="PT64.00S" publishTime="2017-05-16T13:33:55" profiles="urn:mpeg:dash:profile:isoff-live:2011">
  <Period start="PT0.00S" id="1">
    <AdaptationSet mimeType="video/mp4" segmentAlignment="true" subsegmentAlignment="true" startWithSAP="1" subsegmentStartsWithSAP="1" bitstreamSwitching="true">
      <Representation id="1" width="320" height="240" frameRate="25/1" bandwidth="200000" codecs="avc1.4D400D">`

Player download just playlist and one audio|video chunk
v1-video-469722.mpd?scheme=https&_=1494941637286
537035_audio_1_6_init.mp4?m=1493370897
537035_video_1_0_init.mp4?m=1493370897

We cannot check it with 2.x version. Is it bug of 1.6 version or some params are incorrect like https://github.com/google/shaka-player/issues/578

**Comment by joeyparrish** [comment]
I'm so sorry, but we are no longer maintaining v1.6.x.  v1.6.5 came out 11 months ago.  v2.0 came out 8 months ago, and we've made 11 more releases since then.  The latest release is v2.1.1.

My team is just too small to continue maintenance on such an old release.  I apologize for the inconvenience.

What packager are you using?  Have you updated to the latest version of that packager?  If you can send us a manifest URL (publicly or privately), we can test it in v2.1 and help assess what is wrong with the content.  Perhaps we can recommend fixes for your packager.

**Comment by MegaLabs1** [comment]
Main question for us is will this issue gone after upgrading shaka to latest version?
I've attached mpd.(Converted to txt)

[test.txt](https://github.com/google/shaka-player/files/1006909/test.txt)

**Comment by joeyparrish** [comment]
We can't use an attached mpd to test playback.  Can you provide a live URL?  You can email it to me privately if you don't want to share publicly.  My email address is in the CONTRIBUTORS file.

**Comment by MegaLabs1** [comment]
Yes I can. But stream is encrypted.
If I'll provide you with

1. live url
2. cookie
3. widevine url

could you check playback?

**Comment by joeyparrish** [comment]
I believe so, yes.  You'll need to provide instructions on how you want us to use the cookie to authenticate to the license server.  Thanks!

**Comment by MegaLabs1** [comment]
Hello Joe!

I've send url's and cookie privately to your email.

**Comment by joeyparrish** [comment]
Thanks @MegaLabs1.  I have not had time to look at this yet.  I apologize for the delay.

**Comment by joeyparrish** [comment]
@MegaLabs1, I have checked the content, and it appears that the clock sync is way off.  The segments referenced by `<SegmentTimeline>` do not match the MPD's `availabilityStartTime` attribute.

At the time I fetched the manifest, according to `availabilityStartTime`, the presentation times available should have been 3,953,587 through 3,953,651 (seconds).  `<SegmentTimeline>`, though, says the most recent segment was time 3,979,130 - 3,979,138 (seconds).  This is an apparent desynchronization of 25,487 seconds, or about 7 hours.  Because this is a round number of hours, this sounds like a timezone issue.

Wall clock times in the manifest (such as `availabilityStartTime`) should be in UTC according to spec.  Please make sure your server timezone is configured correctly and that the times in the manifest are in UTC.

**Comment by kuznetcoff777** [comment]
@joeyparrish Hi! Can you explain logic of player for current time detection of segment that is playing (live stream). In a code i see this
```
shaka.Player.prototype.getPlayheadTimeAsDate = function() {

  if (!this.manifest_) return null;

  goog.asserts.assert(this.isLive(),

      'getPlayheadTimeInUTC should be called on a live stream!');

  var time =

      this.manifest_.presentationTimeline.getPresentationStartTime() * 1000 +

      this.video_.currentTime * 1000;

  return new Date(time);

};
```
Am i correctly understand that current time = availabilityStartTime + some shift (that is taken from segment)?
Why player does not look at absolute time code that is should be in each segment?

**Comment by joeyparrish** [comment]
@kuznetcoff777, is this related to the original issue in this thread?

`getPlayheadTimeAsDate()` converts the playhead time (presentation time) to the corresponding wall clock time and returns a `Date` object.

For example, assume a presentation starts at presentation time 0 and began streaming at midnight on Jan 1, 2017, UTC.  If the current presentation time under the playhead is 3600 (1 hour into the presentation), then `getPlayheadTimeAsDate()` would return a `Date` object corresponding to 1 AM, Jan 1, 2017, UTC.

Does that answer your question?

**Comment by kuznetcoff777** [comment]
@joeyparrish 

> is this related to the original issue in this thread?

Not at all... just wondering and trying to understand why player does not take absolute time from metadata of video chunks, is it even possible?

**Comment by joeyparrish** [comment]
@kuznetcoff777, please file a new issue or write to the mailing list instead of adding unrelated comments to this issue.  Thanks!
