### ISSUE TITLE
v2.1.1: Widevine Requirements

### ISSUE THREAD

**Issue by hghazzi** [google/shaka-player#819]
So we have a widevine stream that no longer works in v2.1.1. I see the change that causes is it to fail, https://github.com/google/shaka-player/blob/1f8b88430a97c5a5612d507ce784cf1b30688bbf/lib/player.js#L2458.

//demo.keyos.com/DemoContent/dash-bdrm-tears-muldrm-10032015/stream.mpd

Just so we can provide our clients with the correct information, what is missing in the manifest that causes this issue?

**Comment by joeyparrish** [comment]
So that we can fully reproduce, can you please provide a license server URL.  Restrictions are based on the license, so the specific license server matters.  Thanks!

**Comment by hghazzi** [comment]
The servier is //widevine.licensekeyserver.com, but it also includes custom data passed into the header using the network configuration 
```
"headers": [{
   "name": "customData",
   "value": "PEtleU9TQXV0aGVudGljYXRpb25YTUw+DQogIDxEYXRhPg0KICAgIDxXaWRldmluZVBvbGljeSBmbF9DYW5QbGF5PSJ0cnVlIj48L1dpZGV2aW5lUG9saWN5Pg0KICAgIDxXaWRldmluZUNvbnRlbnRLZXlTcGVjIFRyYWNrVHlwZT0iSEQiPg0KICAgICAgPFNlY3VyaXR5TGV2ZWw+MTwvU2VjdXJpdHlMZXZlbD4NCiAgICA8L1dpZGV2aW5lQ29udGVudEtleVNwZWM+DQogICAgPFBsYXk+DQogICAgICA8RW5hYmxlcnM+DQogICAgICAgIDxJZD43ODY2MjdEOC1DMkE2LTQ0QkUtOEY4OC0wOEFFMjU1QjAxQTc8L0lkPg0KICAgICAgPC9FbmFibGVycz4NCiAgICA8L1BsYXk+DQogICAgPEdlbmVyYXRpb25UaW1lPjIwMTUtMDEtMDYgMTk6NDE6MzUuMDAwPC9HZW5lcmF0aW9uVGltZT4NCiAgICA8RXhwaXJhdGlvblRpbWU+MjAyNS0wMS0wNiAxOTo0MTozNS4wMDA8L0V4cGlyYXRpb25UaW1lPg0KICAgIDxVbmlxdWVJZD43Y2Q4MzdiOTE1YjBiMzVjMjcwZjU3YmNiZGJlYzZhZTwvVW5pcXVlSWQ+DQogICAgPFJTQVB1YktleUlkPmRmNDA4NzkyNjdmYTJmYWU4MThhOWEzYmE3YTcwZWIyPC9SU0FQdWJLZXlJZD4NCiAgICA8UlNBUHViS2V5SWQ+ZGY0MDg3OTI2N2ZhMmZhZTgxOGE5YTNiYTdhNzBlYjI8L1JTQVB1YktleUlkPg0KICA8L0RhdGE+DQogIDxTaWduYXR1cmU+WG8vOFZTNk40TDRvK3JtaVU3Q2FYYkNMbjJZN1hpL2VoT1BXMjNSUHJEendaNmFONzVucXNRUkJiWHlpdWRGdzlSQTBzTFdtU3pRRHZRRzR5R0tJWmxUd3N1elF2TmR6QnZQcmQ0L0xqYW1FZ3IyY1F2ZzBqNm1JeWJTQU5tT3loOGRyTHRaeFQ2Z2Y3Umx6b29GaUpHeFJZQmFPQms5N002eUxKMHZBUHROZWdQMWVEMFpNQXVlbVEwK0s2aEdXem5nR2VEbW1QazhhbjZjejg2MzA1YlhXdUptM1Y5SEFUY1JHSERZUW9UWmFXUDB3bm9DbjNLVHArSHNrclFpWXhPTXlQY1BSSlhISEZubURwRjlzeVBxWGhDUjFBQUZTYVBPNm5GYmxVeEQwRHdCMC9DSG1uL1lpTTFSeHp5eUg1N0RWMXpYZVgwV1VpV2dDSGhVZ3JnPT08L1NpZ25hdHVyZT4NCjwvS2V5T1NBdXRoZW50aWNhdGlvblhNTD4="
}
```

**Comment by TheModMaker** [comment]
What's happening here is the manifest specifies a `cenc:default_KID` field which tells us the key ID used for that stream.  When we get the license response, we look at the key statuses and we see that we don't have that key and we mark that track as restricted since we assume we can't play it.  In this case we have restricted every track so we throw an error.

However, the manifest is wrong.  It tells us the key ID is `8e16ef57-d06d-47cb-a5e15fbabfe28a8f` whereas the media is actually encrypted with key ID `cd1260c6-6afe-4f2d-ae71cf27cb942158`.  So you should either use the correct value or remove the field entirely.
