### ISSUE TITLE
error code 4023 while playing HLS

### ISSUE THREAD

**Issue by yuenghole** [google/shaka-player#822]
Version using is v2.1.1, also tried in v2.0.9. 

While playing HLS, it shows Error code 4023. When I try to play mpd and it works fine.

Please help.

**Comment by joeyparrish** [comment]
@yuenghole, please use the issue template so that we can get all the information we need to reproduce your issue and help you.  Here is the template again, for your convenience:

- What version of Shaka Player are you using?

  - Can you reproduce the issue with our latest release version?

  - Can you reproduce the issue with the latest code from `master`?


- Are you using the demo app or your own custom app?

  - If custom app, can you reproduce the issue using our demo app?


- What browser and OS are you using?


- What did you do?

  - What content did you load?

    - If standard demo asset, which one?

    - If custom asset, what manifest and license server URIs?

  - How did you interact with the content, if at all?


- What did you expect to happen?


- What actually happened?

**Comment by yuenghole** [comment]
Hi, Joey.

This ticket can be closed due to there was a coding typo on my application.

Thanks alot.

**Comment by yuenghole** [comment]
I hereby close this issue.

**Comment by joeyparrish** [comment]
Thanks for letting us know!
