### ISSUE TITLE
lang attribute 'eng' v 'en'

### ISSUE THREAD

**Issue by samdutton** [google/shaka-player#83]
FWIW just noticed that the lang attribute is given as both 'en' and 'eng' in [turtle-tube.appspot.com/t/t2/dash.mpd](http://turtle-tube.appspot.com/t/t2/dash.mpd) (as referred to in the [DASH Playback tutorial doc](http://shaka-player-demo.appspot.com/docs/tutorial-player.html)).

**Comment by joeyparrish** [comment]
Both are acceptable to the player, which normalizes all language tags on ingestion.  One could argue that the MPD itself is wrong (supposed to follow BCP47, which says "shortest ISO 639 language code"), but the fact of the matter is that many MPDs in the wild do not follow BCP47.  For example, the language metadata in an MP4 is always a 3-letter code, and some packagers simply extract this and put it directly into the manifest.  This manifest in particular was cobbled together from two different packagers (one WebM and one MP4).

Since the player is actually designed to handle both ISO 639-1 and 639-2 language codes (see also the heading "Language Tags" in the [language tutorial](http://shaka-player-demo.appspot.com/docs/tutorial-language.html), I am closing this as WAI.  Thanks!
