### ISSUE TITLE
HLS video stream is not playing

### ISSUE THREAD

**Issue by boredom2** [google/shaka-player#860]
**Have you read the [FAQ](https://goo.gl/njDlGk) and checked for duplicate issues**:
yes

**What version of Shaka Player are you using**:
2.1.3

**Can you reproduce the issue with our latest release version**:
yes

**Can you reproduce the issue with the latest code from `master`**:
didnt check

**Are you using the demo app or your own custom app**:
both

**If custom app, can you reproduce the issue using our demo app**:
yes

**What browser and OS are you using**:
Firefox (latest), Chrome (latest)

**What are the manifest and license server URIs**:
http://nexxplayplus6.streaming.mediaservices.windows.net/32de1b7d-822c-43b2-b3a5-1cd97f0e9ae7/242391_src.ism/manifest(format=m3u8-aapl)

**What did you do?**
tried to play HLS

**What did you expect to happen?**
Video Playing

**What actually happened?**
Error occured

Hi there,
I know, its me again with Problems on MS Azure and HLS with SHAKA.
All Microsoft generated Manifests fail to play on latest SHAKA, although the initial Problem (couldnt detect HLS) is solved by your Team, thanks for that.
Now the Player complans about "MANIFEST.UNPLAYABLE_PERIOD" - you will see this, once you give this URL into the Demo App.
So sadly, although playable on iOS/Safari, SHAKA does not like that Manifest.
Can we find out why?

Thanks,
Christoph

**Comment by PidginEnemy** [comment]
Hi there, i have the same issue. My HLS manifest not working in Shaka player (latest version).

I tested this in [demo application](https://shaka-player-demo.appspot.com/demo/#license=http://nexxplayplus6.streaming.mediaservices.windows.net/32de1b7d-822c-43b2-b3a5-1cd97f0e9ae7/242391_src.ism;lang=ru)
- select the "custom asset"
- paste this https://media-ci.foxford.ru/dist/hls-issue/issue.master.m3u8 in "Custom manifest" field

Shaka player show error (MANIFEST.UNPLAYABLE_PERIOD, code 4011) - http://prntscr.com/fhgcua

Can you explain why my manifest don't work with shaka player
Thanks,
Evgeny

**Comment by ismena** [comment]
Hi Christoph,
First of all, when I tried to load the manifest, I got a network error due to mixed content (http vs https) which resolved when I changed the link to "https...", but since you mentioned the UNPLAYABLE_PERIOD error, I assume you got past that :)
You said the browsers were Firefox and Chrome. To the best of my knowledge neither of them has support for transport streams at the moment. Shaka should play TS content on Chromecast and Edge (we were unable to make it work on Safari yet due to a bug in their MediaSource implementation).
Now, when I tested your manifest on Chromecast I get audio playback, but no video. I'll look into that! :)
(It's not audio-only content, right?)

**Comment by ismena** [comment]
@PidginEnemy 
Hi Evgeny,
I suspect you're testing on a browser other than Edge or Chromecast, is that right?
Except for Safari these are the only platforms that supports TS segments (and as I mentioned in a previous comment, we couldn't make it work on Safari yet due to a bug in their MediaSource implementation).
I tested your manifest on Chromecast and it works!
Let me know if you have any other questions.

**Comment by boredom2** [comment]
Hi there,
thanks for your fast Response. Yes, you are right, sorry for the http/s Error ehre :)
And No, its not Audio-Only :)

Please help me understand, because obviously, I dont know enough. Isnt it possible to playback HLS Files with MSE on all Browsers? Or am I wrong here? I thought, when interpreting HLS, SHAKA would allow me to also playback HLS in all Browsers? So there is no Way to playback HLS on Firefox for example?
If thats the Case - sorry for my Misunderstanding.

**Comment by TheModMaker** [comment]
We can play HLS content on all platforms so long as the underlying media can be played.  So if the HLS contains MP4 content, then it can be played on all platforms. If the HLS content contains MPEG2-TS, then it can only be played on browsers that support TS, namely Edge, Chromecast, and (eventually) Safari.

So you can play HLS on Firefox so long as the media is MP4.  We have a demo asset that uses MP4 HLS that can be played on all browsers.  But most HLS content uses TS, which isn't playable on all platforms.

**Comment by boredom2** [comment]
Thanks a lor for this Clarification, that explains everything.

**Comment by ismena** [comment]
Okay, about the fact that only an audio stream plays in this manifest: https://nexxplayplus6.streaming.mediaservices.windows.net/32de1b7d-822c-43b2-b3a5-1cd97f0e9ae7/242391_src.ism/manifest(format=m3u8-aapl)

This was introduced by 434f1bf (CL that fixed #841). The fact that we started grouping variants by codecs and choosing the group with the smallest average bandwidth led to the player always choosing audio-only variants for HLS content that has at least one.
We can't switch from audio-only variants to audio+video, so we end up being stuck with audio-only.
Let me open a separate issue to track this and close this one since the HLS questions seem to be answered now.
