### ISSUE TITLE
Seek on player error

### ISSUE THREAD

**Issue by sam2007** [google/shaka-player#89]
Hi Guys,

Is there a way to make shaka player seek to currentTime + 10, for example, when a custom event of "the browser failed to decode the media content" fires? I tried using player.seek() and the bar seeks to the specified time but calling player.play() afterwards no longer works. I asked since we are currently facing an issue where a DASH content have discontinuity errors and each time the player reaches this point where the discontinuity exists it just stops playing even though it continues to request and receive segments from the server. If I drag the seek bar past the point where it is known to occur the player keeps on without any issue. So we thought we might be able to work around this problem by simply skipping the discontinuity point by seeking programatically when the error occurs. Or better yet is there a way we can set the tolerance of the player for discontinuity errors?

Best regards,

**Comment by joeyparrish** [comment]
It depends on what is going on when this happens.  If you could, please use the JavaScript debugger or console.log to find out if shaka.media.Stream.prototype.onUpdate_ is still firing after the error, and if so, for which streams (check this.type_).

**Comment by sam2007** [comment]
Hi Joey,

When the player gets to the point where there is a discontinuity it just stalls. With the following log.

Using native EME as-is.
+ video/mp4; codecs="avc1.4d401e" is supported
+ audio/mp4; codecs="mp4a.40.2" is supported
+ video/mp4; codecs="avc1.4d401e" is supported
+ audio/mp4; codecs="mp4a.40.2" is supported
Initial seek range [0, 3179.84]
Starting each stream from 0
Starting stream for s…a.m…a.StreamInfo {uniqueId: 1, id: "p0a1r0", timestampOffset: 0, currentSegmentStartTime: null, bandwidth: 93000…}
Starting stream for s…a.m…a.StreamInfo {uniqueId: 0, id: "p0a0r0", timestampOffset: 0, currentSegmentStartTime: null, bandwidth: 1500000…}
min/max timestamp corrections [0, 0]
Corrected seek range [0, 3179.84]
CustomEvent {detail: Error: The browser failed to decode the media content.
    at shaka.player.Player.onError_ (http://l…, srcElement: null, target: s…a.p…r.Player, currentTarget: s…a.p…r.Player}bubbles: truecancelBubble: falsecancelable: falsecurrentTarget: shaka.player.PlayerdefaultPrevented: falsedetail: Error: The browser failed to decode the media content.
    at shaka.player.Player.onError_ (http://localhost/shaka-player1.3.1/lib/player/player.js:371:15)eventPhase: 0path: Array[0]returnValue: truesrcElement: nulltarget: shaka.player.PlayertimeStamp: 1433492986848type: "error"__proto__: CustomEvent

On the event listener of the player I put player.seek(1300) for example:

player.addEventListener('error', function(event) {
        console.error(event);
        player.seek(1300);
      });

The bar shows that it did seek but the player is still stalled.

**Comment by sam2007** [comment]
We tried the same stream with exoplayer, it stalls for a fraction of a second but then it kept on.

**Comment by joeyparrish** [comment]
Is shaka.media.Stream.prototype.onUpdate_ still firing when the error occurs?  You can find out either by placing a breakpoint there in the debugger or by adding a console.log to onUpdate_.

**Comment by sam2007** [comment]
Hi Joey,

Yes, I can confirm that while the player stops playing the video, when it reached the point of discontinuity, shaka.media.Stream.prototype.onUpdate_  keeps on firing.

We managed to make the player seek on error event by reloading the source stream by doing the following as an example:

// Listen for errors from the Player.
      player.addEventListener('error', function(event) {
        var videoerror = document.getElementById('video');
        console.error(event);
        console.error("xxx");
        console.error(player.error_time); 
        console.error(parseInt(player.error_time)+1); 
        
  		var mpdUrl = 'http://xxx.xxx.xxx.xxx:1935/vod/stream.mp4/manifest.mpd';
      var estimator = new shaka.util.EWMABandwidthEstimator();
      var source = new shaka.player.DashVideoSource(mpdUrl,interpretContentProtection,estimator);
      	
      player.load(source).then(function() {
      videoerror.pause();
      player.seek(parseInt(player.error_time)+1);
      videoerror.play();
      });

It worked but it is obvious to the viewer that the player restarted the source (screen goes white for a fraction of a second then continue playing).

Is there a better solution to handle this kind of problem? Like maybe a way that we can retain the last frame before the error while reloading the source?

Best regards,

**Comment by joeyparrish** [comment]
If the onUpdate_ timer is still firing, then we are still filling the MSE SourceBuffer.  If it were recoverable from the Player level, seeking would do the trick.  The decode error from the HTML5 video element must be fatal, then.

This sort of problem goes down into MediaSource as far as I can tell.  Chrome's media stack will stall/fail if there is a gap over some hard-coded threshold, and I'm not aware of any way to control that.  The reason Exoplayer can handle it is because the Android media stack is completely different from the browser's.  You could always file a feature request against Chrome to have this MSE behavior changed.

As for retaining last frame or somehow masking the reload, I'm not sure this is easily doable from JavaScript/MSE.

Another workaround (albeit an ugly one) would be to pregenerate a map of discontinuities in each piece of VOD content, then listen for 'timeupdate' events on video and call video.currentTime += timeUntilEndOfGap right before the gap.  If you can't fix your content catalog or your encoder, this extra information would allow you to automate your seeking at the application layer.

In the mean time, is it possible for you to correct the content itself?  I don't understand why discontinuous content would be legitimate.  I would assume that would be a bug in your encoder, especially for VOD content.  Why would a single piece of VOD content have a gap?  I strongly encourage you to file a bug against your encoder software about these discontinuities.

**Comment by joeyparrish** [comment]
Since there has been no response in three weeks, I am closing this issue.  Please feel free to reopen if this is still a problem for you.  Thanks!
