### ISSUE TITLE
xhr appear 401 (Unauthorized)

### ISSUE THREAD

**Issue by babyChou** [google/shaka-player#90]
![error 1](https://cloud.githubusercontent.com/assets/7037478/7975544/94dd8d22-0aa1-11e5-9aa5-9c0224266c6d.PNG)

Is any way to get mpd xml use by auth ajax ??

**Comment by joeyparrish** [comment]
I believe the MPD XML URL is in your screenshot.
http://192.168.0.16:83/upload/index.mpd

Since this is an HTTP 401 error, the library never received the XML itself.

You may want to look into CORS.  Any time an application makes a request to
a different origin, the server must provide certain headers to permit the
request.  You application is hosted at http://192.168.0.39/, but is making
a request to http://192.168.0.16:83/.

See:
  https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
  http://enable-cors.org/

Hope that helps,
Joey

**Comment by joeyparrish** [comment]
@babyChou, I haven't seen any activity on this in a while, so I'm going to close the issue.  If you need further support, either reopen this issue or start a conversation on our [users list](https://groups.google.com/forum/#!forum/shaka-player-users).  Thanks!
