### ISSUE TITLE
Should Shaka be setting Content-Type on license requests?

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#906]
One of our Widevine proxies uses Tomcat's CorsFilter to handle CORS validation. License requests for a custom asset, using the Shaka demo app, fail this validation because there is no Content-Type set on the request.

As part of the Playready unpacking, Shaka sets Content-Type. But other DRM's don't get this.

Do you think, generally speaking, this should be Shaka's responsibility? I think it would be nice to offer consistent behaviour across DRM's, but I also see the argument that this is an application-level responsibility. They can register a request filter.

Thoughts on this?

**Comment by joeyparrish** [comment]
We shouldn't set any headers by default, primarily because of CORS.  If we make a request to a license server that is hosted in the same origin as the application, we can send whatever headers we want.

If the license server is cross-origin, any headers we send must be explicitly allowed by the server, and there is no good way for us to discover at runtime what headers are allowed.  If we send a header that isn't allowed by the server, the request fails and from the JS perspective, we don't know why.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Simple_requests), there are certain headers which are allowed by default, and `Content-Type` is one of them, but only with specific values:
  - `application/x-www-form-urlencoded`
  - `multipart/form-data`
  - `text/plain`

None of these would be appropriate for a license request, which generically should be considered binary and use `application/octet-stream` if anything.

Because of these restrictions, any application whose server needs a specific `Content-Type` would have to:
  - explicitly set `headers['content-type']` in a request filter
  - explicitly configure the server to provide the necessary CORS headers to allow `Content-Type`

If we can't control the server (which as client-side middle-ware, we can't), then setting a default `Content-Type` header could cause surprise failures for many applications.

**Comment by chrisfillmore** [comment]
Thanks Joey.
