### ISSUE TITLE
Make initial buffer size configurable like stream buffer size

### ISSUE THREAD

**Issue by allenevans** [google/shaka-player#91]
I need to be able to configure the player to use an initial buffer size that overrides the buffer size set by the manifest. The initial buffer size value can be set independently of the buffer size.

I propose to add the following apis on player.js:

getInitialStreamBufferSize()
setInitialStreamBufferSize(bufferSizeInSeconds)

The initial buffer size will be used for the amount of content to buffer before playback starts. Once playback has started, the buffering goal revert to use the defined buffer size.

**Comment by joeyparrish** [comment]
Interesting... Can you help me understand your use case?

My understanding is that the bandwidth attribute on a Representation is the minimum bandwidth required to assure uninterrupted playback, assuming that minBufferTime has been buffered before playback begins.

So to me, it seems like overriding minBufferTime with something lower means that you might cause a stall later, while overriding with something higher will increase startup latency.  Is the goal to buffer more at startup to try to avoid rebuffers later?  Or to start faster because the content's minBufferTime is too conservative?  Or perhaps to startup faster for clients which are estimated to have significantly more bandwidth than required, such that minBufferTime can effectively be ignored?

**Comment by allenevans** [comment]
Our use cases are within the VOD context and our goal is to reduce re-buffering. Typically we use a large buffer size of 120 seconds.

Below are the situations why being able to set the initial buffer size would be useful:

1. Through experimentation in live, we have found that tweaking this value has helped to reduce re-buffering during start up for VOD.

2. Having some way to customise this value will allow us to easily A/B test values.

3. We cannot edit the manifest values as they are shared with players across multiple platforms.

4. In the future we would like to set this buffer size based upon estimated line speed or previous playback history to reduce start-up latency without causing re-buffering events.

I've already put together a potential pull request <https://goo.gl/nYhbm0> with the proposed changes.

**Comment by joeyparrish** [comment]
Ah, I see.  This sounds pretty reasonable.  I would suggest a couple of changes to the commit you referenced.

shaka.media.Stream.initialBufferSizeSeconds = Math.max(initialBufferSize, shaka.media.Stream.initialBufferSizeSeconds);

If the static value is low (as in the default value), this line would cause the static value to accumulate across all playbacks in this browser session.  For example, if I were to play content A with a buffer size of 6, then content B with a buffer size of 2, I would want B to start up as fast as specified in the manifest.  With your change, though, B would also buffer 6 seconds worth of content.

I believe it would be preferable to do something like this:

this.initialBufferSize_ = Math.max(initialBufferSize, shaka.media.Stream.initialBufferSizeSeconds);

and then later:

var segmentRange = streamInfo.segmentIndex.getRangeForInterval(this.video_.currentTime, this.initialBufferSize_);

I also think getBufferingGoal_ should revert to its original state.  If the initial buffering goal is larger than 15s, we should attempt to maintain that goal throughout playback.

I would prefer it if the test 'does not hang when seeking to evicted data' did not rely on setStreamBufferSize, since that is not what is under test.  I think the original way of shimming the minBufferTime should be restored.

**Comment by joeyparrish** [comment]
Sorry, this is bad timing.  The next Stream refactoring change in progress on our side is actually going to move all of the minBufferTime logic to StreamVideoSource.  I apologize for the inconvenience.

**Comment by allenevans** [comment]
Not to worry, we're going to wait until this lands in 1.4.0 and review what changes, if any, we need to make.

Thanks.
