### ISSUE TITLE
[Question] Headless live Dash player used for load or presence testing

### ISSUE THREAD

**Issue by mlondon1** [google/shaka-player#934]
Hi,
Is there a way to run the Shaka player "headless" (without GUI, run from a command line) in order to verify the feed requests result in non 4XX/5XX errors, and also to possibly do load testing?

**Comment by vaage** [comment]
Hello @mlondon1, out of the box this is not possible. However, you can import Shaka Player into NodeJs as long as you fake certain media objects - for example the video object.

**Comment by mlondon1** [comment]
Thanks, any chance you could provide a little more detail?

**Comment by vaage** [comment]
Shaka Player depends on the browser to handle all media functions. In order for ShakaPlayer to run without a browser it needs those objects and functions faked. I have talked with another engineer on the team and the three main objects that you would need to fake are:

1. [Video](https://www.w3.org/TR/html51/semantics-embedded-content.html#the-video-element)
2. [MediaSource](https://www.w3.org/TR/media-source/#mediasource)
3. [SourceBuffer](https://www.w3.org/TR/media-source/#sourcebuffer)

Lastly you could need to import a node module that implements xhr to handle networking requests.

**Comment by chrisfillmore** [comment]
As a proof-of-concept, a colleague of mine built Shaka into an Electron app and was able to achieve playback. Perhaps you could do something similar?

**Comment by joeyparrish** [comment]
Yes, Electron and things like it will work because they are actually complete browsers.

Node, however, is just a JS environment.  It is better suited for command-line tasks, but does not provide the media-related APIs we use.

If your goal is just to get Shaka to parse manifests and request segments, you don't need to do much more than stub out video and MediaSource.  For example, video.play() doesn't have to do anything, and SourceBuffer.appendBuffer only has to invoke an event.

You may also be able to repurpose some of the fakes we use in unit tests.  See `simple_fakes.js` in `test/test/util/`.

**Comment by dineshu07** [comment]
Hi @mlondon1 ,  I'm also searching for similar solution. Did you find solution for this? i would like to know your status on this. Please let me know if you found any alternative solution. 

Thanks 
Dinesh

**Comment by vaage** [comment]
An option I failed to mention before is to use [Karam](https://karma-runner.github.io/1.0/index.html). We use Karam to run all our tests. If you look at our `build/test.py` and `karma.conf.js` you can see how we configure Karam to run our tests.

**Comment by mlondon1** [comment]
I was going to use Headless Chrome, but that seemed like a lot of overhead to run a whole browser so I started writing my own Dash parser in Python.

I am not a JavaScript expert so I had trouble getting the Shaka tests running to parse the live Dash stream as the code is complex.

If one of the Shaka developers could give general steps to run the test and stub/mock the non-essential components that might help, but not sure how much effort that is.

**Comment by TheModMaker** [comment]
Using headless Chrome would be the easiest option since it wouldn't require any extra work and would operate the same as a normal production app.  It will also avoid stubbing out components that would affect behavior.

If you want to just run the DashParser, all you need to do is to setup a fake `NetworkingEngine` to make network requests.  It also requires a valid `DOMParser`, which there are some implementations in node.

However, this will only give you the parsed manifest.  In your original question, you wanted to check for segment network errors and load testing.  The DashParser will only parse the manifest, not make segment requests.  To test the segments, you'll need to either make the network requests yourself using the manifest object, or use the whole Player, which would require stubbing out a lot of the media APIs.

**Comment by joeyparrish** [comment]
It seems like this has been solved, at least insofar as we can do anything to solve it from Shaka Player.  If you would like help exploring other options besides headless Chrome or bootstrapping DashParser in node.js, please let us know and we can reopen.  Thanks!
