### ISSUE TITLE
Suggestion: Allow applications to register custom manifest type detection logic

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#946]
Our live DAI ads provider provides us a paramaterized manifest URL that looks roughly like:

```
http://ad-domain.com/path/to/manifest.mpd;sessionid=etc.ad-domain.com?someParam=someValue/
```

In `ManifestParser.getFactory`, Shaka is unable to determine that it's DASH because of the `;sessionid=etc...` portion, so it makes a HEAD request to get the content type. Our ads provider's backend doesn't like the HEAD request and returns 405 Method Not Allowed, so the original call to `Player#load` fails.

I've reviewed #547, which described a similar problem, and for the time being I am patching over the problem by hardcoding my application to DASH via `opt_manifestParserFactory`. I agree with the conclusion that the correct solution is to have recognizable manifest URL's. I am not sure I can persuade our ads provider to make changes. I would also like to eventually use Shaka for HLS down the road, so hardcoding won't be a permanent solution for me.

What do you think of the idea of allowing applications to register a callback to do custom URL parsing for manifest type detection? That way an application could provide a callback roughly like:

```
function getManifestFileExtension (manifestUri) {
  var uriObj = new goog.Uri(manifestUri);
  var uriPieces = uriObj.getPath().split('/');
  var uriFilename = uriPieces.pop();

  if (uriFilename.includes(';')) {
    uriFilename = uriFilename.split(';')[0];
  }

  var extension = uriFilename.split('.').pop();

  return extension;
}
```
Thoughts on this? and/or any idea of effort required?

**Comment by chrisfillmore** [comment]
A question: Why does Shaka do content type detection in this way? Why not simply request the manifest at whatever URL is provided, and look at the Content-Type of the response? If there's no Content-Type in the response, then do detection by file extension. If no detectable file extension, throw an error. Is there a reason it wasn't built this way?

**Comment by joeyparrish** [comment]
Shaka supports multiple manifest formats, so it must have some way to know which parser to use.  There are three ways it does this:

1. Explicit manifest parser factory from the app, using `opt_manifestParserFactory`.  This overrides all else.
2. Extension-based detection.  Parsers are registered to common file extensions, which we parse from the URL.  This is preferable to header-based, since it allows us to instantiate the parser without an additional request.
3. Header-based detection.  Parsers are registered to common MIME types, and we must make a HEAD request to get the MIME type.  Then the parser is instantiated, and the parser makes a GET request for the manifest contents.

The reason we use this order (extension before header) is that manifest parsers are responsible for making their own requests.  The API for parsers works this way because parsers also need to initiate update requests for live manifests on their own schedule.  It was more general to also have them fetch the initial manifest, rather than feed them the initial contents and make them initiate update requests.  It also makes more sense for formats like HLS, where a single fetch is not enough to parse the entire manifest.

As for the format, you can definitely use URL parameters, you just need to separate them from the rest of the URL with a question mark.  This is a normal convention for URLs:

http://foo.bar/manifest.mpd?p1=v1;p2=v2

A URL of that format would still be detected as an MPD.  So you can change this:

http://ad-domain.com/path/to/manifest.mpd;sessionid=etc.ad-domain.com?someParam=someValue/

To this (question mark first, semicolons to separate parameters):

http://ad-domain.com/path/to/manifest.mpd?sessionid=etc.ad-domain.com;someParam=someValue/

Or this (question mark first, ampersands to separate parameters):

http://ad-domain.com/path/to/manifest.mpd?sessionid=etc.ad-domain.com&someParam=someValue/

Both semicolon and ampersand are common conventions to separate parameters from each other, but what is most important is that you use a question mark to separate the path from the parameters.

**Comment by chrisfillmore** [comment]
Our ads provider got back to me and pointed out that this is URL format is in line with the [Java Servlet spec](https://jcp.org/aboutJava/communityprocess/first/jsr053/servlet23_PFD.pdf), section 7.1.1:

> **7.1.1 URL Rewriting**
URL rewriting is the lowest common denominator of session tracking. In cases where a
client will not accept a cookie, URL rewriting may be used by the server to establish session
tracking. URL rewriting involves adding data to the URL path that can be interpreted by the
container on the next request to associate the request with a session.
The session id must be encoded as a path parameter in the resulting URL string. The name of
the parameter must be jsessionid. Here is an example of a URL containing encoded
path information:
http://www.myserver.com/catalog/index.html;jsessionid=1234

He believes that the player should be able to understand this kind of URL, and I'm inclined to agree.

But this just makes me wonder if URL parsing should be application-level business logic. Applications could provide custom functions for different backend API's. What do you think of this idea?

**Comment by joeyparrish** [comment]
If manifest URLs do not follow normal conventions, we already have two fallbacks for this: content-type headers and an explicit parser factory.  Either of these should work, and the explicit factory doesn't require an extra round trip.

Because there are already three ways to determine the manifest type, I'm not inclined to create a fourth through a custom URL parser callback.  In fact, you can, if you wish, do your own URL parsing before calling load(), and use the results of that to determine the right parser factory to specify.  So you don't need additional APIs to do your own URL parsing as part of your business logic.

It is also worth noting that we use the closure library's uri parser to parse the URL into its component pieces, so if you believe that our definition of path is too restrictive, I suggest you file an issue and/or PR with that parser directly:

https://github.com/google/closure-library/tree/master/closure/goog/uri

Thanks!

**Comment by chrisfillmore** [comment]
> In fact, you can, if you wish, do your own URL parsing before calling load(), and use the results of that to determine the right parser factory to specify.

I didn't even think of this. Thanks Joey!

**Comment by chrisfillmore** [comment]
I'm reading the media element spec for an unrelated issue and saw this paragraph:

> This specification does not currently say whether or how to check the MIME types of the media resources, or whether or how to perform file type sniffing using the actual file data. Implementors differ in their intentions on this matter and it is therefore unclear what the right solution is. In the absence of any requirement here, the HTTP specification's strict requirement to follow the Content-Type header prevails ("Content-Type specifies the media type of the underlying data." ... "If and only if the media type is not given by a Content-Type field, the recipient MAY attempt to guess the media type via inspection of its content and/or the name extension(s) of the URI used to identify the resource.").

https://dev.w3.org/html5/spec-preview/media-elements.html#concept-media-load-resource

The portion of the HTTP spec referred to is 7.2.1:

> Any HTTP/1.1 message containing an entity-body SHOULD include a
   Content-Type header field defining the media type of that body. If
   and only if the media type is not given by a Content-Type field, the
   recipient MAY attempt to guess the media type via inspection of its
   content and/or the name extension(s) of the URI used to identify the
   resource. If the media type remains unknown, the recipient SHOULD
   treat it as type "application/octet-stream".

https://tools.ietf.org/html/rfc2616#section-7.2.1

I'm just sharing this for posterity. Future users -- servers really should allow you to make a HEAD request to obtain the Content-Type.
