### ISSUE TITLE
Big Buck Bunny from Nimble Streamer does not work on Shaka Player

### ISSUE THREAD

**Issue by prasadkhambete** [google/shaka-player#955]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes

**What version of Shaka Player are you using**: v2.1.5-debug

**Can you reproduce the issue with our latest release version**: Yes

**Can you reproduce the issue with the latest code from `master`**: I did not try

**Are you using the demo app or your own custom app**: demo app

**If custom app, can you reproduce the issue using our demo app**: NA

**What browser and OS are you using**: Chrome Version 59.0.3071.104 (Official Build) (64-bit) / OSX El Capitain 10.11.4

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*
https://video.wmspanel.com/local/raw/BigBuckBunny_320x180.mp4/manifest.mpd

**What did you do?**
Click on Nimble Streamer -> Big Buck Bunny and try to play the content

Shaka Produces Error NETWORK.HTTP_ERROR 

wget https://video.wmspanel.com/local/raw/BigBuckBunny_320x180.mp4/manifest.mpd
shows that the server's TLS certificate does not match the domain 

wget https://video.wmspanel.com/local/raw/BigBuckBunny_320x180.mp4/manifest.mpd
--2017-07-31 14:05:02--  https://video.wmspanel.com/local/raw/BigBuckBunny_320x180.mp4/manifest.mpd
Resolving video.wmspanel.com (video.wmspanel.com)... 46.101.181.101, 159.203.0.111, 146.185.139.54, ...
Connecting to video.wmspanel.com (video.wmspanel.com)|46.101.181.101|:443... failed: Connection refused.
Connecting to video.wmspanel.com (video.wmspanel.com)|159.203.0.111|:443... failed: Connection refused.
Connecting to video.wmspanel.com (video.wmspanel.com)|146.185.139.54|:443... failed: Connection refused.
Connecting to video.wmspanel.com (video.wmspanel.com)|104.131.143.22|:443... connected.
ERROR: The certificate of ‘video.wmspanel.com’ is not trusted.
ERROR: The certificate of ‘video.wmspanel.com’ hasn't got a known issuer.
The certificate has expired
The certificate's owner does not match hostname ‘video.wmspanel.com’

**What did you expect to happen?**
Expect some way to trust expired/mismatched server TLS certificates in order to run test

**What actually happened?**
Error NETWORK.HTTP_ERROR

**Comment by TheModMaker** [comment]
HTTP_ERROR is caused by the browser rejecting the network request.  We have no control over setting what requests the browser will accept.  

The hosted demo only uses https because it is required for EME.  If your content is clear, you can just run a local copy and just use http.  Also, https is not required when accessing `localhost`, so even if your content is encrypted, you can use http on `localhost`.

If you are only interested in tests, you have a few options:

1) If you are running on localhost, you can start Chrome with `--allow-insecure-localhost` to ignore cert errors on `localhost`.
2) Create a self-signed certificate and add it to your trusted certificates (for example, you can add it in Chrome settings).
3) Start Chrome with `--ignore-certificate-errors` to ignore all certificate errors (UNSAFE).

**Comment by joeyparrish** [comment]
As @TheModMaker, there is nothing Shaka Player can do to trust the bad certificate from video.wmspanel.com.  As an individual user, you can work around it as described above, or by this method:

1. Visit https://video.wmspanel.com/ in Chrome
2. Click the "ADVANCED" button on the error screen
3. Click "Proceed to video.wmspanel.com (unsafe)"
4. [Return to the Shaka demo and play the asset](https://shaka-player-demo.appspot.com/demo/#asset=//video.wmspanel.com/local/raw/BigBuckBunny_320x180.mp4/manifest.mpd;play)

Since the site is not serving the content correctly, we should disable the asset.

**Comment by joeyparrish** [comment]
This has been cherry-picked for v2.1.6.
