### ISSUE TITLE
Error on nightly demo app

### ISSUE THREAD

**Issue by avelad** [google/shaka-player#963]
![error](https://user-images.githubusercontent.com/8983024/29212308-2c1d775c-7e9e-11e7-89bc-8831b09b1f14.png)

navigator.userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36 OPR/47.0.2631.39"

Uncaught exception in event handler TypeError: Cannot read property 'language' of undefined
    at info_section.js:205
    at Array.forEach (<anonymous>)
    at Object.shakaDemo.updateLanguageOptions_ (info_section.js:201)
    at Object.shakaDemo.updateAudioLanguages_ (info_section.js:176)
    at Object.shakaDemo.updateLanguages_ (info_section.js:148)
    at shaka.util.FakeEventTarget.shakaDemo.onTracksChanged_ (info_section.js:55)
    at shaka.util.FakeEventTarget.dispatchEvent (fake_event_target.js:117)
    at shaka.cast.CastProxy.playerProxyLocalEvent_ (cast_proxy.js:529)
    at shaka.Player.shaka.util.FakeEventTarget.dispatchEvent (fake_event_target.js:117)
    at shaka.Player.<anonymous> (player.js:2665)

**Comment by joeyparrish** [comment]
I'm unable to reproduce with the content you sent via email, or with any of our demo content.

Can you provide specific steps to reproduce?  (We ask these questions in our issue template to save time.)

Do you still see the error if you clear your browser cache and reload?

**Comment by avelad** [comment]
@joeyparrish, there are not nothing special, load the assets and open the info section. 
I deleted the browser cache and the issue remains

Note: I can reproduce the error on Chrome v60 also.

**Comment by joeyparrish** [comment]
I managed to reproduce this today.  Let me see what I can do to track down the cause.

**Comment by joeyparrish** [comment]
I am reproducing this with a live stream that is not currently available to the public.  I'm not sure how easily this can be reproduced with other streams.

On the surface, the issue is this:  When the demo app gets a callback for the `'trackschanged'` event, there are no tracks with `.active == true`, so `activeTrack` is undefined and `activeTrack.language` throws an exception.

Digging deeper, the event is triggered more than once.

1. During load(), at which time `getVariantTracks()` returns two tracks, one of which is active.  No exception.
2. From onChangePeriod_, at which time `getVariantTracks()` returns two tracks, neither of which is active.  The exception is triggered.

There is only one period in the manifest, but somehow, our DASH parser creates a second period during the manifest update.  Both periods have `.startTime == 0`, and both have two variants.  The second period's variants are not active, which makes some kind of sense, because they are not being streamed.

The real issue seems to be the creation of a duplicate period on manifest update.

**Comment by joeyparrish** [comment]
We have a bug in the DASH parser in which we don't add track period IDs for the initial manifest.  This means that during the first update, all periods appear to be new and are duplicated.

This was introduced into the `master` branch in d67764b5ff729cb54f5e7a075e9287e5c92a960e and has not appeared in any releases.

**Comment by joeyparrish** [comment]
The fix has been pushed to `master` and we've updated the nightly build early.  Please let us know if this fixed it for you.  Thanks!

**Comment by avelad** [comment]
I just tested and it works perfectly, Thanks!
