### ISSUE TITLE
Streams initially show audio-only poster on Chromecast

### ISSUE THREAD

**Issue by theodab** [google/shaka-player#969]
It looks like when the cast receiver is initially buffering, it mistakenly believes the asset is audio-only (presumably due to not having any streams loaded at all) and shows the audio-only poster. It plays the video as expected once it loads fully.

**Comment by joeyparrish** [comment]
We should double-check this against the nightly build of the receiver.  The introduction of isAudioOnly in #942 may have addressed this for v2.2, in which case we just need a quick fix for v2.1.x.

**Comment by joeyparrish** [comment]
Looks like this just needs a quick fix for v2.1.x.  The bug can't be reproduced on `master`.

**Comment by joeyparrish** [comment]
The original fix (isAudioOnly()) was trivial to cherry-pick to v2.1.x, so I went ahead with that.

The ready isAudioOnly() fixes this is because the old method was checking the number of tracks with a video codec.  If the number of tracks with a video codec was 0, it was considered audio-only.  But this would also be true if the content manifest wasn't fully parsed yet (0 tracks total).  The implementation of isAudioOnly() returns false if there are no tracks at all.

The cherry-pick will be available in v2.1.8.
