### ISSUE TITLE
TextTrack.oncuechange not called as expected in IE11 / Edge

### ISSUE THREAD

**Issue by JeffJassky** [google/shaka-player#971]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: Yes

**What version of Shaka Player are you using**: 2.1.7

**Can you reproduce the issue with our latest release version**: Yes

**Can you reproduce the issue with the latest code from `master`**: Yes

**Are you using the demo app or your own custom app**: Custom

**If custom app, can you reproduce the issue using our demo app**: 2.1.7 demo app has not yet been deployed

**What browser and OS are you using**: Windows 10, IE11 & Edge

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?** Enable closed captions (textTrack[0].mode='hidden') and added an event listener to textTrack[0] for oncuechang.

**What did you expect to happen?** oncuechange to be called periodically

**What actually happened?** oncuechange is not called as expected (often not at all)

oncuechange is called as expected in Shaka 2.0.5. After updating to 2.1.7 it's no longer called as expected in IE11 and Edge on Windows 10.

**Comment by joeyparrish** [comment]
@JeffJassky, we haven't released v2.1.7 quite yet.  (I was planning it for Monday afternoon (PDT), but it looks like it may wait until Tuesday.)  Can you double-check your version number?

**Comment by joeyparrish** [comment]
With the latest code from `master`, I get 'cuechange' events on:
 * Chrome 60 Linux
 * Firefox 54 Linux
 * Safari 9 Mac
 * Edge 15 Windows
 * IE 11 Windows

With the v2.1.x branch, I get the same results.

When we fixed #848 (fb51fe4798ddd564badc81f8082ab9b32407db71) in v2.1.6, we introduced a bug that caused issues with text tracks on IE & Edge.  This has already been fixed in `master` and the v2.1.x branch, and will be released in v2.1.7 (today or tomorrow).  The issue has nothing to do with 'cuechange' directly, but what's happening with that bug is that IE & Edge rejected our cues.

Can you try again with v2.1.x or master?

**Comment by joeyparrish** [comment]
v2.1.7 is out now.  Can you try again with the appspot demo page to confirm that this is fixed?

**Comment by joeyparrish** [comment]
We believe this has been fixed in v2.1.7.  Today, we released v2.1.8 and v2.2.0.  Here are links to specific versions for testing:

Here are links to specific version subdomains:

https://v2-1-7-dot-shaka-player-demo.appspot.com/
https://v2-1-8-dot-shaka-player-demo.appspot.com/
https://v2-2-0-dot-shaka-player-demo.appspot.com/

Closing for now, but if you are still having issues, please let us know so we can reopen and investigate.  Thanks!
