### ISSUE TITLE
Type check on serverCertificate

### ISSUE THREAD

**Issue by chrisfillmore** [google/shaka-player#972]
The serverCertificate configuration gets type-checked as Uint8Array, but per the spec the type of argument accepted by `setServerCertificate` is `BufferSource`:

https://www.w3.org/TR/encrypted-media/#dom-mediakeys-setservercertificate

So an ArrayBuffer should be acceptable. I know this is very minor, but is there any practical way for Shaka to reconcile this?

**Comment by joeyparrish** [comment]
The browser API takes ArrayBuffer or Uint8Array, but the Shaka API takes Uint8Array only.  This is not really a compliance issue, because our API and the underlying browser APIs we depend on are two completely different things.

It's easy to reconcile, though, at the app level.  `new Uint8Array(bufferSource)` should do the trick.

**Comment by joeyparrish** [comment]
Closing for now, but please let us know if you'd like to reopen the issue.  I would be happy to discuss further if you wish.
