### ISSUE TITLE
Playing any video throws error "this.config_.abr.manager.setDefaultEstimate is not a function"

### ISSUE THREAD

**Issue by prasadkhambete** [google/shaka-player#983]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**: yes

**What version of Shaka Player are you using**: v2.1.7-debug

**Can you reproduce the issue with our latest release version**: yes

**Can you reproduce the issue with the latest code from `master`**: I did not try

**Are you using the demo app or your own custom app**: demo app

**If custom app, can you reproduce the issue using our demo app**: NA

**What browser and OS are you using**: MacOSX

**What are the manifest and license server URIs**:
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?** opened https://shaka-player-demo.appspot.com/ in chrome browser, use drop down to select any video and click on the "Load" button

**What did you expect to happen?** Video should play

**What actually happened?** Error was thrown and video did not play
<img width="1147" alt="screen shot 2017-08-23 at 12 00 19 pm" src="https://user-images.githubusercontent.com/6602223/29633522-62a77492-87fb-11e7-8a0e-3ed235ffc0d8.png">

**Comment by joeyparrish** [comment]
This is a caching issue.  We just updated to v2.2.0 today, but some of the v2.1.7 resources are being cached by the server.  For future releases, I will lower the cache time on appspot from 1 day to 1 hour so that this doesn't happen again.

Here are links to specific version subdomains:

https://v2-1-7-dot-shaka-player-demo.appspot.com/
https://v2-1-8-dot-shaka-player-demo.appspot.com/
https://v2-2-0-dot-shaka-player-demo.appspot.com/

Will you confirm that these are all working?  If so, this problem should go away within 24 hours.  I apologize for the inconvenience.

**Comment by prasadkhambete** [comment]
Thanks, Joey. The version-specific subdomains work fine for me.
